### ISSUE TITLE
Filter WEB-DL/WEBRiP to proper category depending on type of release (Movie or TV)?

### ISSUE THREAD

**Issue by testarea1** [nZEDb/nZEDb#1212]
It appears WEB-DL/WEBRiP is hard coded to auto categorize to the TV > HD category. Since movies are also released in WEB-DL/webrip, it's placing those movies in the TV > HD category by default.

For example:
Movie.Name.2013.unrated.1080p.web-dl.h264-phd

Even though that is clearly a movie (as movies always tend to have a year in the name and plus the original release name is a know movie) because it's a web-dl, it goes into TV > HD by default.

Any way to change this behavior? Maybe filter web-dl/webrip releases that have SxxExx as TV > HD and releases that have a year (2013, 2014, etc) as Movies > HD?

Not sure if that's possible, just throwing ideas out.

**Comment by ruhllatio** [comment]
We've since added the Movies -> WEB-DL category which has its own set of processing to properly categorize movies from webdl/webrip.  Closing this issue.
