### ISSUE TITLE
Large file names focks up layout Alpha theme

### ISSUE THREAD

**Issue by MORD0R** [nZEDb/nZEDb#1426]
predb page

Chrome
![image](https://cloud.githubusercontent.com/assets/6746199/3714963/bd08db64-15c7-11e4-8f50-6bde4e9271ea.png)

ie
![image](https://cloud.githubusercontent.com/assets/6746199/3714965/e012aedc-15c7-11e4-94f2-d35ae7bccb14.png)

Alle pages have the same problem this is ebook.
![image](https://cloud.githubusercontent.com/assets/6746199/3714967/09be34f4-15c8-11e4-955d-0aba51073d8b.png)

**Comment by zetas** [comment]
I tweaked this on my site. In the various browse templates it's setup to break release names that are 60 characters or larger iirc. I turned mine down to 30. It should add a newline to the release name and put the rest below it. This keeps the design from going off the page.

**Comment by Bart39** [comment]
think this was fixed
