### ISSUE TITLE
Database Fatal Error

### ISSUE THREAD

**Issue by Mortis7432** [nZEDb/nZEDb#1455]
Hello, 

I've followed the guide for Windows. 

https://github.com/nZEDb/nZEDb/wiki/install-Guide:-Windows

But when I'm setting up the database on step2 I'm getting the following error. 

Fatal error: Uncaught exception 'Exception' with message 'The system cannot find the path specified. /usr/bin/git branch' in C:\xampp\htdocs\nZEDb\libs\Git.php\Git.php:321 Stack trace: #0 C:\xampp\htdocs\nZEDb\libs\Git.php\Git.php(336): GitRepo->run_command('/usr/bin/git br...') #1 C:\xampp\htdocs\nZEDb\libs\Git.php\Git.php(493): GitRepo->run('branch') #2 C:\xampp\htdocs\nZEDb\libs\Git.php\Git.php(533): GitRepo->list_branches(true) #3 C:\xampp\htdocs\nZEDb\nzedb\utility\Git.php(44): GitRepo->active_branch() #4 C:\xampp\htdocs\nZEDb\nzedb\db\DbUpdate.php(66): nzedb\utility\Git->__construct() #5 C:\xampp\htdocs\nZEDb\www\install\step2.php(156): nzedb\db\DbUpdate->__construct(Array) #6 {main} thrown in C:\xampp\htdocs\nZEDb\libs\Git.php\Git.php on line 321

**Comment by zetas** [comment]
I think this is more than just a "install gnu4win", it's looking for git in /usr/bin/git which it obviously won't find in windows. Git for windows does indeed need to be installed but the code needs to look for it in the right place. As far as I know when installing git on windows it asks you if you want to place git in the PATH which you should always say "yes" to. If that's the assumption just executing "git" on the command line should work.

**Comment by ruhllatio** [comment]
Pretty sure this isn't an issue anymore.  Closing.  If this needs to be re-opened the original opener can join IRC to talk about it.
