### ISSUE TITLE
Traileraddict Trailers on Movie Detail Don't Display on HTTPS Site

### ISSUE THREAD

**Issue by testarea1** [nZEDb/nZEDb#1488]
When running nzedb under https, the browser (only tested chrome) gives an unsafe script error when the /details page of the movie contains a trailer from traileraddict. Since the nzedb site is https, the traileraddict site is loading a http link (http://v.traileraddict.com/...). The trailer will load after manually selecting the option in the browser to load unsafe script. This was fixed in the youtube trailers when the movie embed link was changed to https under 1b126df2ea1f1265d89a4060fa652b203321f4a6, but does traileraddict offer an https embed option? I tried some https links on the traileraddict site, but couldn't get the trailer to load under any https links (just a black screen).

**Comment by zetas** [comment]
@testarea1 Is this still an issue? I don't see this problem on my https site.

**Comment by testarea1** [comment]
Actually, I noticed about a week or 2 ago that the traileraddict trailers are now displaying correctly on https. Looks like there was a change to the code to just pull "//:traileraddict" instead of the hardcoded "http://traileraddict".
