### ISSUE TITLE
REQ. Regex

### ISSUE THREAD

**Issue by seias** [nZEDb/nZEDb#1507]
can u add regex for 
alt.binaries.kenpsx    and
alt.binaries.frogs

theres a bunch f releases but very hashed there

![image](https://cloud.githubusercontent.com/assets/5633389/4346417/75f4283e-40fe-11e4-9a55-990187abded3.png)
![image](https://cloud.githubusercontent.com/assets/5633389/4346418/97ec57e0-40fe-11e4-8493-f8ad0dc4a020.png)

**Comment by Bart39** [comment]
nothing viable to be caught via regex, closing
