### ISSUE TITLE
Feature Request:  Support for X-Failure headers

### ISSUE THREAD

**Issue by c4rv** [nZEDb/nZEDb#1513]
Been reading about X-Failure Headers   which will auto-retry a different release in the case download failure. Looks like the indexer as well as downloader needs to support it. Latest version of SABNZB has this added. Haven't checked but apparently there is support in nn+

Information I have been reading is,
http://www.htpcguides.com/automatically-replace-failed-nzbs-for-sabnzbd/
http://www.reddit.com/r/usenet/comments/2hgoht/which_indexers_support_xfailure_header/
https://github.com/sabnzbd/sabnzbd/commit/470c1fc13e88540ea2a2cf5d4b482478bb9f66ff

Thanks,

**Comment by zetas** [comment]
I'll take a look as well, looks interesting.

**Comment by kevinlekiller** [comment]
36c60f8f45cc93fdb2fa26f699754d7f343ffe74
