### ISSUE TITLE
All articles failed to insert!

### ISSUE THREAD

**Issue by rkon88** [nZEDb/nZEDb#1536]
Hi guys 

Can anyone help me out on this problem? I'm nog getting any new releases.

Group alt.binaries.blu-ray has 2,223,522 new articles. Leaving 73,522 for next pass.
Server oldest: 5,901,273 Server newest: 1,244,278,519 Local newest: 1,242,054,997

Getting 50,000 articles (1,242,054,998 to 1,242,104,997) from alt.binaries.blu-ray - (2,100,000 articles in queue).
Received 50000 articles of 50,000 requested, 0 blacklisted, 0 not yEnc.                                             
Warning: 50000 articles failed to insert!

3.43s to download articles, 97.59s to process collections, 0.00s to insert binaries/parts, 12.45s for part repair, 113.47s total.

Getting 50,000 articles (1,242,104,998 to 1,242,154,997) from alt.binaries.blu-ray - (2,050,000 articles in queue).
Received 50000 articles of 50,000 requested, 0 blacklisted, 0 not yEnc.
Warning: 50000 articles failed to insert!

3.10s to download articles, 87.61s to process collections, 0.00s to insert binaries/parts, 1.15s for part repair, 91.87s total.

Getting 50,000 articles (1,242,154,998 to 1,242,204,997) from alt.binaries.blu-ray - (2,000,000 articles in queue).
Received 50000 articles of 50,000 requested, 0 blacklisted, 0 not yEnc.
Warning: 50000 articles failed to insert!

4.19s to download articles, 75.32s to process collections, 0.00s to insert binaries/parts, 1.15s for part repair, 80.66s total.

Getting 50,000 articles (1,242,204,998 to 1,242,254,997) from alt.binaries.blu-ray - (1,950,000 articles in queue).
Received 50000 articles of 50,000 requested, 0 blacklisted, 0 not yEnc.
Warning: 50000 articles failed to insert!

**Comment by Bart39** [comment]
closing - appears to be due to corrupt table(s)
