### ISSUE TITLE
Cover view not working

### ISSUE THREAD

**Issue by rkon88** [nZEDb/nZEDb#1541]
Cover view for movies en audio is not working.

When open up a movie or album release I can see there is a cover attached. Also the /var/www/nZEDb/resources/covers is stuffed with covers. I've got cover overview enabled in my profile.

I'm using a nginx web-server. I used the configuration script from the Ubuntu guide. And the covers directory has 777 permissions.

**Comment by Bart39** [comment]
closing - no update from OP for 2 months
