### ISSUE TITLE
Small bug Options you did are not saved with site-edit.php If you get error Deep password check requires a valid path to unrar binary.

### ISSUE THREAD

**Issue by MORD0R** [nZEDb/nZEDb#1554]
Small bug Options you did are not saved with site-edit.php If you get error Deep password check requires a valid path to unrar binary.

When you get this error all the changes you did are reset.

**Comment by zetas** [comment]
@MORD0R Is this issue resolved for you?

**Comment by ruhllatio** [comment]
Considering issue closed due to no contact with opener.
