### ISSUE TITLE
Trakt IMDB search url format changed

### ISSUE THREAD

**Issue by RickDB** [nZEDb/nZEDb#1572]
Trakt launched their new site and among other things the URL format for searching based on IMDB id has changed from:

http://trakt.tv/search/imdb?q=tt2395427/

to:

http://trakt.tv/search/imdb/tt2395427/

This affects the movie template but might be used in other areas as well, pretty easy fix but though I let you guys know.

**Comment by Bart39** [comment]
merged to dev #1573
