### ISSUE TITLE
Notice: Undefined variable: consoletools in /home/schwick/www/nZEDb/misc/update/predbftmatch.php on line 84

### ISSUE THREAD

**Issue by schwickster** [nZEDb/nZEDb#1575]
predbftmatch.php gives the following error:
Notice: Undefined variable: consoletools in /www/nZEDb/misc/update/predbftmatch.php on line 84

Simple way to fix is of course to declare a consoletool like
$consoletools = new \ConsoleTools(['ColorCLI' => $pdo->log]);

after
$pdo = new Settings();

(or whatever colour you want)

**Comment by niel** [comment]
Fixed in commit 3bff5df0beacdde54230a1224523022448ab5c2e
