### ISSUE TITLE
Innerfileblacklist not saving even with valid regex

### ISSUE THREAD

**Issue by slypknot** [nZEDb/nZEDb#1582]
I've done a clean/new install of both the DEV and Master branches, both exhibit the same behavior and have the same DB setup for this field.  I believe something is wrong with the DB fields causing this:

Table: Settings
+---------+------------+--------------------+-------+------+------------------------------------------------------------------+
| section | subsection | name               | value | hint | setting                                                          |
+---------+------------+--------------------+-------+------+------------------------------------------------------------------+
| indexer | ppa        | innerfileblacklist |       |      | You can add a regex here to set releases to potentially password |
+---------+------------+--------------------+-------+------+------------------------------------------------------------------+

The 'value' and 'hint' fields are empty while the 'setting' field contains the hint.

Regardless of what is saved in the innerfileblacklist form box, nothing is saved into the DB for this entry.  I have manually moved the field data around in the DB and this seemed to allow the entry but doesn't appear to work during post-processing (it's not catching any of the codec.exe listings).

**Comment by niel** [comment]
Fixed in dev

**Comment by kevinlekiller** [comment]
1098979d382d33b7ce863183c5e06d09b5e21d59
