### ISSUE TITLE
Blacklist 2. Possible issue

### ISSUE THREAD

**Issue by BeZazz** [nZEDb/nZEDb#1584]
I noticed a lot of what appeared to be legit stuff getting deleted, I believe that the
bl
was getting BluRay
while
(h|x).?2?64
was getting x264

So for eg.
Star.Trek.Enterprise.S04E02.720p.BluRay.x264-iNGOT Due to BluRay and x264
Was getting deleted.

**Comment by zetas** [comment]
Can you give some more info? What exact blacklist were you using? From what I gather it looks like you were using a specific blacklist for delete bluray files and that's what happened.. so not sure what's going on here.

**Comment by BeZazz** [comment]
It is number 2
https://github.com/nZEDb/nZEDb/blob/master/resources/db/schema/data/10-binaryblacklist.tsv

**Comment by zetas** [comment]
Ah ok, sorry for the misunderstanding. You were using the abbreviated foreign blacklist and it was deleting releases that were not foreign for some reason. Ok, I guess this would be an issue, hopefully @Bart39 or one of the other regex masters can take a look and see whats up.

**Comment by BeZazz** [comment]
Thats ok :)

**Comment by Bart39** [comment]
that is an incorrect assumption,
that blacklist is looking for bl followed by a . space or _ so bluray will not match it.
in fact i just tested it against Star.Trek.Enterprise.S04E02.720p.BluRay.x264-iNGOT and found no match
