### ISSUE TITLE
TMUX: Error SQLSTATE[42S02]: short_groups does not exist

### ISSUE THREAD

**Issue by Sweepr** [nZEDb/nZEDb#1585]
I started running TMUX and i noticed this error:

TMUX: Error SQLSTATE[42S02]: 1146 Table 'sinistra_nzedb.[b]short_groups[/b]' doesn't exist.

[img]http://s27.postimg.org/5d6qjyzlv/SQL.jpg[/img]

Upon checking the SQL database i noticed table "shortgroups" exist's, but not "short_groups", after i copied shortgroups and renamed it "short_groups", the error in TMUX dissapeared and data stated filling into "short_groups".

What for is this table ?
Is there a problem somewhere, if so what is the correct name for this table and which files are concerend checking for typo's?

**Comment by Sweepr** [comment]
Crosspost: http://forums.nzedb.com/index.php/topic,1973.msg11056.html#msg11056

**Comment by Bart39** [comment]
What for is this table ?
it is used by the binary / backfill scripts to compare first/last post of each group of your USP against the first / last post of your local groups

**Comment by Sweepr** [comment]
I understand, but before i used to run simple.sh, and i that data was stored in groups, 
Tmux uses it's own table to keep track of first/last post then?

Anyway the creation of "shortgroups" is not correct then, it should be "short_groups" according Tmux.

**Comment by Bart39** [comment]
tmux uses different methods than simple.sh for binary update / backfill dependant on the settings. we are aware the table name is wrong and will fix it

**Comment by Sweepr** [comment]
Allright, thank you for the confirmation!

**Comment by Bart39** [comment]
still needs fixing - re-opening
