### ISSUE TITLE
Extended Media Info no longer displaying proper info on releases

### ISSUE THREAD

**Issue by testarea1** [nZEDb/nZEDb#1587]
Seems to have happened after I pulled fdb7daba3f1c37618c6032adfb394d8563e3a4d8 as I have media info available for releases before that, but I'm not sure why that would cause the change. I noticed there was a mediainfo CLI program update around the same time that I may of pulled, but to test I tried replacing mediainfo with an older CLI version for Ubuntu 14.04 but it's still doing the same thing now for all releases:

![untitled-1](https://cloud.githubusercontent.com/assets/2273360/6003658/1fb64b64-aab2-11e4-891f-36c6c725ca4e.png)

I am currently on latest dev at the time of posting this issue a6ad927949b0c034c252dbf060bf2353ba90189f

**Comment by niel** [comment]
Nothing in that commit that could cause a problem as it only affects the SQL schema for new installs.

Assuming you're on a Debian based linux distribution, I believe that the program used to get the mediainfo was updated recently and may have introduced a bug preventing it working as intended. I have heard one report that reverting to the previous version fixes the problem.

**Comment by dabtech** [comment]
That's the exact behavior I documented here:
http://forums.nzedb.com/index.php?topic=1966.0

Check your mediainfo version, if it's 0.7.72, you're experiencing a mediainfo bug.

**Comment by testarea1** [comment]
The current 0.7.72 bug is more than likely the issue. I did try downgrading to 0.7.6x and still had the same issue. Is there a link to a working 0.7.71 for Ubuntu?

**Comment by niel** [comment]
Best to do it with apt-get. Remove the current version, then apt-get install the version you want by adding the version string to the package name.

**Comment by testarea1** [comment]
Apt-get is how I received the new .72 version.

**Comment by Wally73** [comment]
install manually

*Mediainfo <http://mediaarea.net/en/MediaInfo>:*

Go to http://mediaarea.net/en/MediaInfo/Download/Ubuntu, download the deb
files for libmediainfo, libzen0 and mediainfo (CLI)

You can download by right clicking on them, copy link, then type wget and
paste the link after.

Once you have all 3 deb files, install them by typing sudo dpkg -i followed
by the name of the file. You may have to install libzen0 package first. If
so do:

sudo apt-get install libzen0

**Comment by testarea1** [comment]
I'm all good now. I actually have a PPA that has updated mediainfo and they just recently updated to the new bad .72 version during the time of the issue, so I installed ppa-purge and purged that PPA/mediainfo and then grabbed the official ubuntu apt-get of mediainfo and it's working again. Thanks all.
