### ISSUE TITLE
Creation of screenshots

### ISSUE THREAD

**Issue by Sweepr** [nZEDb/nZEDb#1592]
I'm seeing releases that sometimes have screenshots and sometimes do not have screenshots, how come?

And can someone tell me which script is responsible for the screenshots that are created?

**Comment by Bart39** [comment]
post processing creates the screenshots along with samples etc depending on the type of release

**Comment by Sweepr** [comment]
I have two releases in xxx category, 

1. 720P.WEBRIP.MP4
2. 1080P.WEBRIP.MP4

1. has media info
2. has no media info

1. has screenshot
2. has no screenshot

1. has preview
2. has no preview

How come, if they are both processed the same way?

Resolution is not a factor here, because this happens to 720p and 1080p / 2160p and vice versa
Also seeing some MP4 Flash video's being catergorized in XXX->WMV

Category: 	XXX > WMV
Media Info: 	
Property 	Value
Overall 	Container Format 	Flash Video
Bitrate 	1 846 Kbps
Video 	Duration 	9s 967ms
Format 	AVC
Codec 	7
Width x Height 	1024x576
Aspect 	16:9
Framerate 	30.0000 fps
Audio 1 	Format 	AAC
Channels 	2 channels
Sample Rate 	32.0 KHz

**Comment by zetas** [comment]
did you download both releases and check the content? It's possible the release with no meta data is corrupt or fake

**Comment by Sweepr** [comment]
@zetas, i will do an investigation on that, thanks for the tip!

**Comment by ruhllatio** [comment]
Closing as the question has been answered...
