### ISSUE TITLE
FreeNAS install manual?

### ISSUE THREAD

**Issue by thejrose1984** [nZEDb/nZEDb#1593]
Hey, I know you provided a general install on top of guides for specific OS and Linux distributions. Any chance someone dabbled with FreeBSD, or more specifically, FreeNAS?

Initial run was on a VM with Ubuntu 14.04 64-bit, but that died a quick death because the VirtualBox plugin keeps aborting the VM. Plus, it would make more sense to run nZEDb within a jail anyway because it would take up less resources (unless I'm missing something).

Anyway, I tried using the general install guide but seemed to be hitting snags. Any chance someone has or can create a guide for this type of install?

**Comment by thejrose1984** [comment]
Status?

**Comment by zetas** [comment]
nZEDb is not something that's geared towards running on a low resource box. It takes quite a bit of "juice" to index usenet effectively, not even counting generating video/audio samples and preview images. This isn't like Sonarr or Sickbeard, It doesn't just sit in the background and do the occasional polling.

That being said, there's no reason it shouldn't work on your Ubuntu VM. I've installed nZEDb on countless dev VM's, all running trusty (14.04). If the VM supplemental software is killing the box remove it, it's not necessary for linux anyway. Even still it's hardly a production-safe usecase. Dedicated hardware is the way to go if you actually plan on using this indexer for more than 1 or 2 usenet groups.

**Comment by thejrose1984** [comment]
nZEDb can run within a FreeNAS jail without issue as long as the main system has enough resources (which mine does by a long shot). After a lot of troubleshooting and aggravation, I finally figured out how to do it and documented the steps...

**Comment by niel** [comment]
Link to documentation please? ;-)

**Comment by thejrose1984** [comment]
Already posted on nZEDb Github Wiki
