### ISSUE TITLE
Predb Updated show -316 days in tmux window

### ISSUE THREAD

**Issue by csmarauder** [nZEDb/nZEDb#1595]
After the last git pull the Predb updated field in tmux is show -316 days.
Any idea if this is impacting and how to fix it?

**Comment by Bart39** [comment]
https://github.com/nZEDb/nZEDb/wiki/Database%20Administration#fix-predb-dates-2016-01-to-2015-01

**Comment by csmarauder** [comment]
Nope that didn't work I still have the negative date and there are predb entries like
2015-12-31 18:45:49 from today.

**Comment by Bart39** [comment]
thats an examp[le of how to fix you need to amend it to match the dates you have

e.g. to correct dec 2015 to dec 2014
update predb set predate = CONCAT('2014', substr(predate, 5)) WHERE predate like '2015-12%' ;

**Comment by csmarauder** [comment]
Ok thanks that fixed it was the year month piece i didn't set right looks good now thanks.
