### ISSUE TITLE
Properly updating sphinx when editing a release.

### ISSUE THREAD

**Issue by kevinlekiller** [nZEDb/nZEDb#1619]
The usage of this method is fine, but it ignores the other data stored in sphinx (name / fromname): https://github.com/nZEDb/nZEDb/blob/master/nzedb/controllers/Releases.php#L786

We can currently use insertRelease method from sphinx since it uses REPLACE INTO: https://github.com/nZEDb/nZEDb/blob/master/nzedb/controllers/SphinxSearch.php#L41

Maybe we can add an "update" method to the sphinx class and make it call insertRelease to avoid confusion.

**Comment by ruhllatio** [comment]
This is remedied in commit 4f8b878b808209ed528f8e1ad730b24db960b461

We now update all fields when changes are made, much like a trigger that isn't enforced at the DB level.
