### ISSUE TITLE
Fanart.tv v3 API Url

### ISSUE THREAD

**Issue by scottia** [nZEDb/nZEDb#1620]
Can the fanart.tv Api links be updated to the v3 API ?

Announcement ;
https://fanart.tv/newsletter/fanart-tv-api-changes/
""In order to keep things a bit more ordered between v2 and v3 we have changed the address from api.fanart.tv to webservice.fanart.tv, in addition SSL is now available and you are encouraged to use it, so the address would be https://webservice.fanart.tv/v3/""

Documentation ;
http://docs.fanarttv.apiary.io/

Lnks in movies.php - 
http://webservice.fanart.tv/v3/
OR
https://webservice.fanart.tv/v3/

**Comment by DariusIII** [comment]
From one of the links you posted:
If you currently use the XML output then you will have to stay on the v2 API for now.

**Comment by scottia** [comment]
I don't.  I modified my string for verison 3.  That's why I added the issue here since the api address and url changed.

**Comment by DariusIII** [comment]
Well, do a PR then :)

**Comment by scottia** [comment]
I am not very good at that sort of thing and am not sure about posting code here but I will if someone wants to review it.

**Comment by DariusIII** [comment]
I have made a PR with changes related to v3 fanart api. Now is up to nZEDb devs to accept it, or not :)

**Comment by scottia** [comment]
Cool.  I looked at it and may pull if I get a moment.  All I really changed was this line, since it validated and pulled the queries I used from it.

$buffer = nzedb\utility\Utility::getUrl(['url' => 'http://webservice.fanart.tv/v3/movies/' . 'tt' . $imdbId . '?api_key=' . $this->fanartapikey . '/xml/']);
