### ISSUE TITLE
TV Poster Wall Only Seems to Display UK/Other Foreign Releases

### ISSUE THREAD

**Issue by testarea1** [nZEDb/nZEDb#1625]
On the New Releases TV Poster Wall, I have really only seen about 98% foreign (mostly just UK) TV shows appear on that page (newposterwall?t=TV). It doesn't seem to really show images for any other updates even though going into TV Browse section there are plenty of other releases. Can this be changed somewhere?

Also, possible to change the TV poster wall layout from 24 posters to 21? 24 leaves only 3 posters on the bottom row compared to the others above with 7 and there is a lot of whitespace. Alpha theme.

**Comment by Bart39** [comment]
It will display anything in the tv categories that has a rageID and has a cover if neither are true then it won't show them
