### ISSUE TITLE
[05:29:11]<root@tardis:~/tmux>php start.php PHP Notice:  Undefined property: stdClass::$running in /var/www/nZEDb/nzedb/controllers/Tmux.php on line 442

### ISSUE THREAD

**Issue by rbaxter82** [nZEDb/nZEDb#1626]
[05:29:11]<root@tardis:~/tmux>php start.php
PHP Notice:  Undefined property: stdClass::$running in /var/www/nZEDb/nzedb/controllers/Tmux.php on line 442
[05:29:41]<root@tardis:~/tmux>php -v
PHP 5.5.22-1+deb.sury.org~trusty+1 (cli) (built: Feb 20 2015 11:26:12)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2015, by Zend Technologies

**Comment by zetas** [comment]
This is just a notice. It can be ignored. In fact you should probably
turn notices off in your php.ini. They aren't an indication of a
problem, just something being used before it was initialized (a
behavior that is a common time saver in PHP)

**Comment by niel** [comment]
I would not recommend turning off warnings. Our Ubuntu guide specifically says to have errors set to E_ALL and turn on logging. Our code is intended to run clean, so any warning is something that needs investigating.

**Comment by zetas** [comment]
I agree but that wasn't a warning it was a notice. If you enable
notices and have display_errors on you will get spammed on most of the
cli scripts.

**Comment by niel** [comment]
Sorry, I meant any kind of warning, not a 'Warning'. ANY thing that turns up in the error log needs to be looked at. ;-)

**Comment by niel** [comment]
Looks like this is caused by a bad tmux table. I've added some code to throw an exception if the flag is missing.
Check that your tmux table has the 'running' setting.
