### ISSUE TITLE
"Illegal Offset" in Movie.php

### ISSUE THREAD

**Issue by scottia** [nZEDb/nZEDb#1627]
Getting illegal offset errors from Movie.php line 678.  This seems to fix them for me anyway :

} else if (isset($art['moviethumb'][0]['url'])) {

**Comment by DariusIII** [comment]
Because niel pushed the broken Movie.php again (which was introduced by me), with the Utility:: and not the nzedb\utility\Utility:: namespace.

**Comment by scottia** [comment]
Don't think so.  I was already using "nzedb\utility\Utility::" that Bart pushed.  That line seems to find an empty variable and errors.  The brackets for whats there are off by one for url.

Current (Neil)
} elseif (isset($art['moviethumb'[0]['url']])) {
You see the extra 'url' "]" bracket there ?

My Revision
} else if (isset($art['moviethumb'][0]['url'])) {

**Comment by DariusIII** [comment]
Ah, damn a bracket on a wrong place.

**Comment by scottia** [comment]
and your right "nzedb\utility\Utility::" needs to be added as well

**Comment by DariusIII** [comment]
Did a PR with fixes.

**Comment by scottia** [comment]
Thank you !!
