### ISSUE TITLE
add group 7020 in /nzedb/controllers/Namefixer.php to make sure that misc->hashed is included to in fixReleaseNames

### ISSUE THREAD

**Issue by Wally73** [nZEDb/nZEDb#1628]
2 lines need to be modified in Namefixer.php

https://github.com/nZEDb/nZEDb/blob/dev/nzedb/controllers/NameFixer.php#L143
to 

$this->timeother = ' AND rel.adddate > (NOW() - INTERVAL 0 HOUR) AND rel.categoryid IN (1090, 2020, 3050, 6050, 5050, 7010, 7020, 8050) GROUP BY rel.id ORDER BY postdate DESC';

and
https://github.com/nZEDb/nZEDb/blob/dev/nzedb/controllers/NameFixer.php#L145

to 
$this->fullother = ' AND rel.categoryid IN (1090, 2020, 3050, 6050, 5050, 7010, 7020, 8050) GROUP BY rel.id';

works fine with fixReleaseNames.php other stuff (somehow not in all mode)

**Comment by Bart39** [comment]
Fixed in #1629

**Comment by Wally73** [comment]
mmm 7020 has disappeared from both lines somehow
