### ISSUE TITLE
ProcessReleases.php Loop

### ISSUE THREAD

**Issue by xxx666yyy777** [nZEDb/nZEDb#1630]
Lines 202-203 say the following:

// This loops as long as there were releases created or 3 loops, otherwise, you could loop indefinately
} while (($nzbFilesAdded > 0 || $releasesAdded > 0) && $loops++ < 3);

Based on the comment, shouldn't the while statement rather say:
} while (($nzbFilesAdded > 0 && $releasesAdded > 0) || $loops++ < 3);

Otherwise, the update releases process (when called via php update_releases.php) will ALWAYS finish after 3 iterations, even if there are still releases to be processed.

**Comment by Wally73** [comment]
it processes the amount you have set in site edit. in a following run of the script it continues

**Comment by xxx666yyy777** [comment]
@Wally73 - How's that? The update_releases.php calls the processReleases function only once and processReleases executes mainly within the while loop i mentioned above - there is no provision for running again. Which parameter on site edit do you refer to?
Thanks!

**Comment by kevinlekiller** [comment]
Should be good now.
