### ISSUE TITLE
Cleanup XXX release filename

### ISSUE THREAD

**Issue by Sweepr** [nZEDb/nZEDb#1631]
I wish to cleanup the XXX filename's, where and how should i do this?

Id like to:

Remove ".14.04.24."  date and replace by dash " - "
Remove all "." between characters and replace by space " "

Example: 

Name.15.03.28.word.word.word.word.word.word.XXX.MP4-SDX264XXX

Name - word word word word word word XXX MP4-SDX264XXX

**Comment by ruhllatio** [comment]
There is no PREG_REPLACE function in MySQL unless you add the UDF library for it to your local MySQL installation.  http://www.mysqludf.org/lib_mysqludf_preg/.  The only other way to do it is by using PHP.  As this has not been requested by multiple people, such a script will not be added to the repository.

You can replace the spaces quite easily.

UPDATE release_files SET name = REPLACE(name, '.', ' ') WHERE name REGEXP '^.+XXX\\.MP4-SDX264XXX\..{2,4}$';

Based on the filenames you gave me, though they were missing the file extension.  I would turn this into a SELECT first and run it to make sure you're updating the correct rows.

SELECT name FROM release_files WHERE name REGEXP '^.+XXX\\.MP4-SDX264XXX\..{2,4}$';

If you need further assistance with this please join the IRC channel or make a post on the forums.
