### ISSUE TITLE
Blank page2.php when trying to install from release tarball

### ISSUE THREAD

**Issue by pezz** [nZEDb/nZEDb#1633]
Hi there,

This has been doing my head in for ages. For like 4 or 5 "release" versions now, I've tried installing nZEDb from the release tarball.

Every time I get the infamous blank page2.php after entering my DB creds. After turning on level 9000+ debug info on my php-fpm and web server, I saw:

`2015/04/01 20:02:10 [error] 17046#0: *14 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'Exception' with message '"/srv/http/nzedb" is not a git repository' in /srv/http/nzedb/libs/Git.php/Git.php:241`

Once I saw this, I went into /srv/http/nzedb and did a "git init ." and it looks like that has done the trick.

Please either fix your code, or the tarball, or perhaps document this little quirk somewhere.

Cheers.

**Comment by DariusIII** [comment]
nZEDb is intended to be installed by using git itself (git clone the nZEDb repository). As you are using tarballs, you don't have initialized git repo. It's not the code that needs fixing. Where did you download the tarball from?

**Comment by pezz** [comment]
https://github.com/nZEDb/nZEDb/releases

If I'm not meant to use releases, why provide releases?

**Comment by DariusIII** [comment]
Main method for installing nZEDb is by doing git clone, and everything is revolving around that method.
Tarballs are there for users who want them, but issues like yours will happen.

**Comment by pezz** [comment]
So perhaps, at the very least, document this quirk if you insist that "git clone" is the only way.

I think it's reasonable for people to expect that something tagged as a release, with a tarball tagged as so, works.

**Comment by DariusIII** [comment]
It's not the only way, but is the way supported. Does the release tarball work? After you did git init it does. So... enjoy.

**Comment by pezz** [comment]
You don't think the problem is a bit obscure, and only revealed by excessive logging?

Well, hopefully this issue serves as documentation for others that may run into this.

Feel free to close this if you feel nothing further is needed.

**Comment by niel** [comment]
Yes it is obscure.
I have not been able to find a way to make github add the .git directory to the tarball, or to disable creation of tarballs once a release is tagged.

**Comment by kevinlekiller** [comment]
Should be added to the README, or on the releases page if possible (that git init is requires), or a modification to the git.php class to either inform that git init is required or to do it automatically.

**Comment by niel** [comment]
@kevinlekiller I simply stopped creating the release tarballs.

**Comment by ruhllatio** [comment]
Issue closed, release tarballs no longer supported.  Use git clone methods instead as it will be much easier to keep up to date with fixes and enhancements.
