### ISSUE TITLE
Releases take 2 hours before available

### ISSUE THREAD

**Issue by testarea1** [nZEDb/nZEDb#1635]
Seems after one of the more recent dev pulls, releases are now taking 2 hours to fully be available on my site for some reason (web interface and api all show posted ~2hrs ago once they actually become available). What could I check in the settings to see if I can resolve this issue? I use tmux to update on ubuntu.

**Comment by niel** [comment]
Which branch. If it is master, nothing has changed there for a month so it is likely a configuration setting causing this.

**Comment by testarea1** [comment]
On latest dev

**Comment by niel** [comment]
ok. There haven't been many updates in the last couple weeks. Define 'recent', a window would help in checking for any potential problems.

**Comment by testarea1** [comment]
Looking at about 3-4 weeks ago this happened. There will be random releases posted around the 30-40 minute "Posted" mark, but everything else below those random releases are 2+ hours every time now. Nothing has changed in the settings of the site.

**Comment by pezz** [comment]
I can confirm this too. I'm running nzedb alongside nn+ as I'm looking to stop using nn+.

Both are using identical groups and nzedb is at least 2 hours, if not more, behind nn+ before releases appear.

**Comment by gregorystorme** [comment]
I'm on previous master 0.4.19.
I only see this happening on releases in the group "alt.binaries.warez".
About 2 hours between postdate/adddate for those releases.
Not seeing any issues with releases in any other group.

**Comment by testarea1** [comment]
I also just noticed that I no longer have any nfo's being added to the release info (I still seem to have everything else with preview image/video/predb, etc, just not nfo). I went back to the releases and nfo's stopped being added to the release about the same time this delay has happened.

**Comment by testarea1** [comment]
Update: I decided to wipe everything out and start from scratch (fresh latest dev git pull and clean mysql DB). Same thing is happening, ~2 hour delay in finishing and posting releases.

**Comment by Bart39** [comment]
2 hours is the default delay time - check your site settings

**Comment by pezz** [comment]
Delay time check?

"The time in hours to wait, since last activity, before releases without parts counts in the subject are are created
Setting this below 2 hours could create incomplete releases.. "

What value would you recommend? Are you sure that is the setting causing it?

**Comment by testarea1** [comment]
I'm going to try setting it to 0. I know I've never messed with that setting before in the 1.5 years I've used Zed, has this just recently been enforced? Up until recently that setting always been on 2 hours and releases were on par with the quick release time of my 3rd party external indexer.

**Comment by pezz** [comment]
Setting it to 0 doesn't seems to make any difference.

Latest post in my HD TV section in nZEDb is 3 hours old, latest in nn+ is 36 minutes old.

**Comment by testarea1** [comment]
I was able to "fix" it on mine setting to 0, but like the summary says on that setting, releases are coming in as incomplete due to it posting the release before it's finished (they eventually update to 100%), but at least they're showing up right away now. Is there anyway to have better control on this setting by minutes instead of hours?

**Comment by Bart39** [comment]
in that case then the issue is more why are you getting incomplete releases, as its those that's causing them to wait until the delay time check has passed before they are created

**Comment by kevinlekiller** [comment]
Did you fail inserting this patch? https://github.com/nZEDb/nZEDb/blob/master/resources/db/patches/mysql/0320~collection_regexes.sql

**Comment by testarea1** [comment]
0320 Patch looks good, I checked my Collections Regex List and it was populated with the items in that patch.

**Comment by kevinlekiller** [comment]
Alright, the only reason this would happen is if those regex don't match. I can't test anymore since I don't have usenet subscriptions, I was hoping people would test it before it was merged, although no one seemed to have any issues until now. You can try reverting this file to this state: https://github.com/nZEDb/nZEDb/blob/96bd9ccc9552e5ff44bbead828cd76cf5e29b9c7/nzedb/controllers/CollectionsCleaning.php

**Comment by kevinlekiller** [comment]
I'd turn on mysql error logging in settings.php and check those also to make sure none of the queries are failing when selecting those regex.

**Comment by testarea1** [comment]
I enabled logging and sql error logging, but nothing really showing in the log file but the init when it created the log
```
[INIT]   [Initiating new log file.]
```

**Comment by Bart39** [comment]
this may be as a result of the bug fixed by https://github.com/nZEDb/nZEDb/commit/6b1a23697cbe2f29139b3e8e784afbc5f0479c45

**Comment by kevinlekiller** [comment]
087f9bc2cdefc174245548ddcbb1c00f4dcc5737

**Comment by testarea1** [comment]
Still seems to be having the delay after I pulled the regexes fix. There are a little bit of releases being posted quicker, but still having the delay of 1-2 hours, not sure if this fixed it for anyone else, but doesn't seem to be working for me.

**Comment by DariusIII** [comment]
You need to truncate the tables, use the reset_truncate script.

**Comment by Adam1986** [comment]
testarea1 do you still have an issue of no NFO's coming through? I am only getting a few NFO's for xxx releases pretty much and nothing else.

**Comment by testarea1** [comment]
@Adam1986 Still no nfo's really coming through, may 1 every other day randomly.
Tried truncating and still getting 2 hour delay, not sure what's going on or what else to try.

**Comment by Adam1986** [comment]
Yes I've noticed this release delay too.  I've now tried it with 4 different USP's and each one is no different.  I powered up my VM I had running until about 9 days ago and i saw that approx 30 days ago that NFO's suddenly stopped coming through practically.

**Comment by Adam1986** [comment]
Has anyone managed to get anywhere with this at all? this is still very much an issue for me.

Cheers

**Comment by niel** [comment]
I need more specific info to look into this. My indexing seems to be fine, releases from less than an hour ago, all but two of the last two dozen with NFOs.

**Comment by Adam1986** [comment]
What info can we give you to help? Just let me know what to do and I will try my best to provide it :-)

**Comment by niel** [comment]
examples of specific releases failing, including group that the release came from, etc.

**Comment by Adam1986** [comment]
Skint.2013.S03E03.720p.HDTV.x264-C4TV - a.b.teevee
Rivermen.S01E03.Sink.or.Swim.720p.HDTV.x264-DHD - a.b.teevee
Revenge.S04E21.1080p.WEB-DL.DD5.1.H.264-KiNGS - a.b.hdtv.x264 (shows up as Revenge.S04E21.Aftermath.1080p.WEB-DL.DD5.1.H.264-KiNGS on nZEDb)
The.Last.Five.Years.2014.LIMITED.720p.BluRay.x264-GECKOS - a.b.triballs

These all have NFO's on newznab but not nZEDb.

**Comment by niel** [comment]
I don't have the last one as I don't index that group. However, all the others are all present and correct (with NFOs). The problem you see with Revenge is because it is using the original subject and hasn't been renamed.

**Comment by Adam1986** [comment]
I am using the Dev branch too.

NFO Processing is set to Yes in site settings.

And Tmux is set to Postprocess All.

That is only a small handful of releases.  Pretty much every release on Newznab has an NFO whereas nZEDb doesnt.

When you see the NFO Postproccessing in nZEDb it just shows -'s

I've tried using different USP's including the same one Newznab is using with no difference.

**Comment by kevinlekiller** [comment]
@Adam1986 If you use [this](https://github.com/kevinlekiller/simple_php_yenc_decode) I pushed a change that could possibly resolve your issue.

**Comment by Adam1986** [comment]
Ah ha! success! I have recompiled simple_php_yenc_decode and straight away NFO's are now starting to come back through! :-) many thanks Kevin!

**Comment by kevinlekiller** [comment]
You might want to run this query to reprocess some that were missing: update releases set nfostatus = -1 where nfostatus = 0;

**Comment by bfincher** [comment]
This may have fixed the NFO issue but releases are still taking 2 hours to show up.

**Comment by niel** [comment]
The time delay is a configuration issue, change your settings if you don't like it. However, be ready for a lot of incomplete releases.

**Comment by bfincher** [comment]
It looks to me like the code is trying to determine if all parts are present and if so the release will be created immediately.  The 2 hour check is for when we don't think all parts are present and no new parts have arrived recently.  Perhaps the determination of all parts are present is incorrect.

**Comment by testarea1** [comment]
I've confirmed that newznab+ along with newznab-tmux from @DariusIII does not have the delay in creating releases. I did a fresh install of newznab+ with the tmux install to have the nzedb features and releases are immediate now (sometimes even quicker than my 3rd party indexer I have).

**Comment by bfincher** [comment]
Temporarily commenting out the "leaveOver" logic in Binaries.php seems to help a lot.  I am not getting releases that were posted a few minutes prior.  I'm sure that totally removing the leaveOver logic isn't the right answer either though.

**Comment by scottia** [comment]
@kevinlekiller - Thanks for the fix to simple_php_yenc_decode .. I am now able to use it again for processing.  Everything working well again.

**Comment by niel** [comment]
NN+ and nZEDb create releases by different methods, so there is no comparison with any meaning for this except whether the releases get created and are complete.
There is no "fix" for this supposed issue, because there's nothing broken. If you don't "like" the delay on badly formed/completed releases, change your settings or use NN+.

**Comment by testarea1** [comment]
I think the thing is that there really wasn't an issue like this delay for years until recently. Something changed and for some reason it's not creating releases quickly like it used to (it was super fast for a long time and would be quicker than NN+ which was one of the big reasons I switched). I would understand if there was no other person with this issue, I would just deal, but we've got multiple people stating it's happening to them also. Maybe this is specific to something else we're all running that's causing this issue with the delay? Probably most people are not having any issues like this. I've tried changing my settings multiple times to try to "fix" this, but it only makes it worse with the incomplete releases. I also started receiving a lot of single releases of the same release for each par file it finds (but I believe that's a whole separate issue). I was able to get NN+ up and running with the tmux config features from Darius for now, so I'm going to stick with that for the time being. I'll keep checking back on updates for zed. I'll close this now since it was stated that there is no fix.

**Comment by niel** [comment]
I think the main change is the number of badly formed or patchy posts on newsnet which highlights this behaviour.
I've noticed that my USPs performance has plummeted this year and suspect the companies are cutting corners to save money.

**Comment by testarea1** [comment]
That's definitely an idea especially with all these dcma takedowns, but wouldn't NN+ have the same issue? I know you can't really compare them at this point with the way they do processing, but after I switched, I'm no longer having any issues with delays or bad posts with the same usp running newznab-tmux on the NN+.

**Comment by niel** [comment]
NN+ does face the same problems, but the way it creates releases is different from nZEDb. I do not use NN+ and have not for a long time, so I cannot comment on its releases' completeness vs. speed.
Any comparison between NN+ and nZEDb is a complete waste of everyone's time, as the main nZEDb developers do not use NN+ and certainly do not look at its code so we couldn't reproduce its behaviour if we wanted to (features might be recreated, but likely with different behaviour).
