### ISSUE TITLE
Feature Request Exclude Categories to specific user roles.

### ISSUE THREAD

**Issue by Adam1986** [nZEDb/nZEDb#1639]
On Newznab you can Exclude Categories to specific user roles which I think is good.

On nZEDb this doesn't appear to be possible - is it possible to implement this feature?

I have also noticed that viewing users in the Admin section does not show their download history or last accessed IP Addresses etc either.

Thanks

**Comment by Fossil01** [comment]
Would like this as well as I had some categories excluded for normal users.
