### ISSUE TITLE
PHP Warning:  preg_match():  Compilation failed: nothing to repeat at offset 17 in /var/www/nZEDb/controllers/Regexes.php on line 341

### ISSUE THREAD

**Issue by Loopher** [nZEDb/nZEDb#1644]
I have updated to the recent dev release and noticed the following error 

PHP Warning:  preg_match():  Compilation failed: nothing to repeat at offset 17 in /var/www/nZEDb/controllers/Regexes.php on line 341.

I have been running with the same regexes for the last month or so, but have not seen this error until today
![nzedb-tmux-error](https://cloud.githubusercontent.com/assets/4019048/7403003/07056b80-ee97-11e4-8ec5-14eed4938fe6.jpg)

**Comment by niel** [comment]
We'll need the full entry from your error log to trace this.

**Comment by Loopher** [comment]
Ok, understood.  I am at work atm and will get that to you asap.

**Comment by Loopher** [comment]
I have not seen the issue repeat, so lets go ahead and close this issue out.   Thanks!
