### ISSUE TITLE
Add Regex to Merge Releases

### ISSUE THREAD

**Issue by testarea1** [nZEDb/nZEDb#1647]
Here are some names/groups of releases that are getting posted 1 per PAR/File instead of grouped together. I'll keep adding to this list when I come across them. These are taken from the "Name:" field in the release:

Group: a.b.hdtv.x264:
```
[ Mad.Men.S07E12.720p.WEB-DL.DD5.1.h.264-NTb ] - [45/45] - "Mad.Men.S07E12.720p.WEB-DL.DD5.1.h.264-NTb.vol197+66.PAR2" yEnc
[ The.Good.Wife.S06E21.1080p.WEB-DL.DD5.1.H.264-CtrlHD ] - [49/49] - "The.Good.Wife.S06E21.Dont.Fail.1080p.WEB-DL.DD5.1.H.264-CtrlHD.vol225+66.PAR2" yEnc
[ Madam.Secretary.S01E22.1080p.WEB-DL.DD5.1.H.264-BS ] - [50/50] - "Madam.Secretary.S01E22.There.But.For.the.Grace.of.God.1080p.WEB-DL.DD5.1.H.264-BS.vol236+66.PAR2" yEnc
```
Group: a.b.moovee
```
Same movie with movie and sub post:
[149277]-[035/122] - "149277.r16" yEnc
[149277]-[013/122] - "149277-Subs.par2" yEnc
```
etc... (if you need all of the releases for this let me know)

**Comment by kevinlekiller** [comment]
The first one should be matching https://github.com/nZEDb/nZEDb/blob/master/resources/db/schema/data/10-collection_regexes.tsv#L356

**Comment by Bart39** [comment]
similarly the 2nd one should be matching https://github.com/nZEDb/nZEDb/blob/master/resources/db/schema/data/10-collection_regexes.tsv#L412

if you do `select * from collection_regexes where id = 411;`  what do you get ?

**Comment by testarea1** [comment]
SQL Commands look good:
```
id	group_regex	regex	status	description	ordinal
355	alt\.binaries\.hdtv\.x264	"/^\[ (?P<match0>.+) \][-_ ]{0,3}\[\d+(?P<match1>\/\d+)\][-_ ]{0,3}"".+?"" yEnc$/"	1	"//[ House.of.Lies.S03E05.1080p.WEB-DL.DD5.1.H.264-NTb ] - [01/35] - ""House.of.Lies.S03E05.Soldiers.1080p.WEB-DL.DD5.1.H.264-NTb.nfo"" yEnc"	15
```
```
id	group_regex	regex	status	description	ordinal
411	alt\.binaries\.moovee	"/^(?P<match0>\[\d+\] - [a-z0-9]+.+?)(\.part\d*|\.rar)?(\.vol\d+\+\d+\.par2|\.[A-Za-z0-9]{2,4}) - \[\d+\/\d+\]\s+yEnc$/"	1	//[133668] - p00okjiue34635xxzx$$Â£Â£zll-b.vol3+2.PAR2 - [005/118]  yEnc	35
```
Looks like pull #1648 above is going to resolve the issue. I went back to check the releases that weren't being merged and thay all ended in .PAR2 instead of .par2. I'll update from dev when that becomes available and recheck.

**Comment by kevinlekiller** [comment]
Sounds good, Bart wrote he can't merge right now due to issues with his DB so might take a cpl of days.

**Comment by kevinlekiller** [comment]
If you find more after a few days after this is merged, keep posting them and I'll check to see if there's more issues.

**Comment by testarea1** [comment]
Just did the dev pull with the updates, is there a command I can run to sort/combine the existing problem ones under these new regexes?

**Comment by Bart39** [comment]
no you can't combine them, once they are created thats it. you would have to reset your release back to a certain date and download them again

**Comment by testarea1** [comment]
ok, I kind of figured so. I'll just clear the DB and start fresh with this update.

**Comment by Snarfster** [comment]
I'm noticing 1 post per file for a.b.inner-sanctum also.

**Comment by kevinlekiller** [comment]
Thanks for reporting, I found a couple of issues while looking into that group.

**Comment by kevinlekiller** [comment]
@Bart39 made a post how to delete the affected releases: http://forums.nzedb.com/index.php?topic=2037.0

**Comment by Snarfster** [comment]
Great turnaround. Thanks gents! If I spot any more I will leave a note here.

**Comment by kevinlekiller** [comment]
Anything to report?

**Comment by Snarfster** [comment]
I am not noticing anything in the groups I am watching. Thanks again

**Comment by testarea1** [comment]
All good now.
