### ISSUE TITLE
Theatre images no longer displaying correctly

### ISSUE THREAD

**Issue by testarea1** [nZEDb/nZEDb#1649]
Receiving broken images from the Theatres /upcoming pages now.

In trying to open the image source links, now receiving this message (example):
```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>movie/11/19/11/11191173_pro.jpg</Key>
<RequestId>64F3E8392CA03167</RequestId>
<HostId>
Lzm7vX/OtsLB2df8ysAZd5ok20dTKx8b/be+xbbWdaEuBbdGIx1ZdGyjkzWZNJ8TBTJVLXin2NY=
</HostId>
</Error>
```

**Comment by Bart39** [comment]
thiis is because rottenttomatoes are now starting to charge for using their api's - looks like your key got revoked

**Comment by Wally73** [comment]
try to set rottentomato pics on original then the pics show up nicely on the upcoming pages (on the other settings it doesn't)

**Comment by DariusIII** [comment]
It looks like content6.flixter.com is removing some of the images that were there.

**Comment by Bart39** [comment]
until we can work out what the new url's are just do as Wally73 suggested

**Comment by kevinlekiller** [comment]
"<Darius> Bart39: http://stackoverflow.com/questions/27364186/getting-decent-sized-pictures-using-the-rottentomatoes-api"

**Comment by testarea1** [comment]
Working good now, thanks.
