### ISSUE TITLE
Installation Step 6: Stuck

### ISSUE THREAD

**Issue by thecorax** [nZEDb/nZEDb#1651]
Hi,
at step 6 (where you enter the admin data) I get stuck. I enter my data, press the button. the page turns white and nothing happens. I can't login to nZEDb.

I am running nZEDb on Raspian (Raspberry Pi 2 with nginx).

**Comment by kevinlekiller** [comment]
Do you see anything in the nginx or php error logs?

**Comment by thecorax** [comment]
nginx.error is empty.  nginx.access seems normal. after step 5 i dont see the "success" which is in 2-4 but i guess thats normal.

can only find php5-fpm.log which doesnt give any usefull information.

where do i find php error logs?

**Comment by kevinlekiller** [comment]
Error logging can be turned on in php.ini, you can set it to E_ALL only to log all errors.

Step 5 creates the file in www folder called config.php, if you don't see that file there might be permission issues on that folder.

**Comment by thecorax** [comment]
it is created, but some crucial parts are empty:

define('NNTP_USERNAME_A', '');
define('NNTP_PASSWORD_A', '');
define('NNTP_SERVER_A', '');
define('NNTP_PORT_A', '');
define('NNTP_SSLENABLED_A', false);
define('NNTP_SOCKET_TIMEOUT_A', '');

can i just enter my stuff in there?

**Comment by kevinlekiller** [comment]
That file is just for database / nntp settings. The admin info is in the database.

**Comment by thecorax** [comment]
PHP Fatal error:  Call to undefined function password_hash() in /var/www/nZEDb/nzedb/controllers/Users.php on line 767


does this help? or is this just a failed login attempt?

php.ini is set to E_ALL

**Comment by kevinlekiller** [comment]
Yes, you need PHP 5.5 or higher - that's why that error appears.

**Comment by thecorax** [comment]
big thanks, will try that tomorrow!

**Comment by kevinlekiller** [comment]
No problem.

**Comment by thecorax** [comment]
one last thing: i have trouble finding php 5.5 for raspbian. i guess its not in the jessie rep anymore (only 5.4) ? do you have any information?

**Comment by kevinlekiller** [comment]
I'm not too experienced with raspberry pi, if you can install PHP 5.6, that's the current main version.

If you can't find PHP 5.5 or 5.6 you can [get this file](https://github.com/ircmaxell/password_compat/blob/master/lib/password.php) and add a require_once('/folder/where/you/have/it/password.php'); at the bottom of your www/config.php file.

**Comment by thecorax** [comment]
thanks!

**Comment by kevinlekiller** [comment]
You're welcome.
