### ISSUE TITLE
Dev: PHP Fatal Class Errors in Tmux after changes

### ISSUE THREAD

**Issue by testarea1** [nZEDb/nZEDb#1659]
**Edit by @kevinlekiller: Temporary fix here: https://github.com/nZEDb/nZEDb/issues/1659#issuecomment-100868792**

Justed pulled dev 4d85cbf0880f9ba7b5728550e0de973022b9d99b

Getting PHP Fatal Error: Class errors:

On Monitor->Multi Process Group Update Receive:
![image](https://cloud.githubusercontent.com/assets/2273360/7559609/22fb5edc-f76e-11e4-925b-d6cc8ffa69a7.png)

On Post->Postprocess_NFO:
![image](https://cloud.githubusercontent.com/assets/2273360/7559614/4a2a865e-f76e-11e4-834a-27befad5d397.png)

Looks like some class issues with Forking.php

**Comment by richierichman** [comment]
I'm getting the same error after the update.

**Comment by DariusIII** [comment]
I have made a PR with fixes to these problems.

**Comment by testarea1** [comment]
Also looks like I'm getting blank web pages after I log out to log back in and test, no webpages are working now on frontend or admin (just blank) after pull.

**Comment by DariusIII** [comment]
Have you enabled captcha maybe?

**Comment by testarea1** [comment]
Ah, yeah I did earlier today during an earlier pull that added it. Was there an new update to change/disable that?

**Comment by DariusIII** [comment]
Try to disable captcha and see if that solves the problem.

**Comment by testarea1** [comment]
I checked my apache log and this is the error:
```
PHP Fatal error:  Class 'Captcha' not found in /var/www/nZEDb/www/pages/BasePage.php on line 179
```
So yeah, def captcha related, but I did remove the keys but still getting all blank pages.

**Comment by DariusIII** [comment]
I have added a possible fix to my PR.

**Comment by testarea1** [comment]
There are some more "\NZB::NZB_ADDED" in Forking, will they all need to be changed? I thought I saw another post process error regarding this error, but can't pull it up now.

**Comment by DariusIII** [comment]
https://github.com/nZEDb/nZEDb/pull/1660

**Comment by DariusIII** [comment]
I have updated the PR with lines i missed in Forking.php.

**Comment by jangrewe** [comment]
+1 - thanks @DariusIII

**Comment by gregster85** [comment]
Similar errors:

PHP message: PHP Fatal error:  Class 'Releases' not found in /var/www/nZEDb/www/pages/ajax_tvinfo.php on line 10
PHP Fatal error:  Class 'PreDb' not found in /var/www/nZEDb/www/pages/ajax_preinfo.php

**Comment by gregster85** [comment]
And another:

PHP Fatal error:  Class 'ReleaseFiles' not found in /var/www/nZEDb/www/pages/ajax_rarfilelist.php on line 10

**Comment by DariusIII** [comment]
I added that to my PR.

**Comment by gregster85** [comment]
Another one

PHP message: PHP Fatal error:  Class 'ReleaseExtra' not found in /var/www/nZEDb/www/pages/ajax_mediainfo.php on line 10

**Comment by scottia** [comment]
Adding a couple more :+1: 


Some more Class Errors to report

[11-May-2015 13:58:22 America/Chicago] PHP Fatal error: Class 'nzedb\nzedb\utility\Utility' not found in /var/www/nZEDb/nzedb/Greenlight.php on line 259

[11-May-2015 14:35:16 America/Chicago] PHP Fatal error: Class 'Utility' not found in /var/www/nZEDb/nzedb/NZBGet.php on line 190

**Comment by niel** [comment]
@scottia pushed.

**Comment by scottia** [comment]
Thanks for the quick Push @niel  !!

**Comment by testarea1** [comment]
no more issues after all the fixes, closing
