### ISSUE TITLE
Dev: Class 'ReleaseFiles' not found

### ISSUE THREAD

**Issue by gregster85** [nZEDb/nZEDb#1661]
**Edit by @kevinlekiller: Temporary fix here: https://github.com/nZEDb/nZEDb/issues/1659#issuecomment-100868792**

I updated to the lastest dev and got blank pages and this error in nginx error log:

PHP message: PHP Fatal error:  Class 'Captcha' not found

Which was fixed after copying nzedb/controllers/Captcha.php to its parent directory.
But now I still have these errors:

PHP message: PHP Fatal error:  Class 'ReleaseFiles' not found in /var/www/nZEDb/www/pages/details.php on line 160
PHP message: PHP Fatal error:  Class 'ReleaseSearch' not found in /var/www/nZEDb/www/pages/search.php on line 146

**Comment by DariusIII** [comment]
I have updated my PR with fixes: https://github.com/nZEDb/nZEDb/pull/1660

**Comment by kevinlekiller** [comment]
See https://github.com/nZEDb/nZEDb/issues/1659#issuecomment-100868792
