### ISSUE TITLE
Class 'NZB' not found @ Forking

### ISSUE THREAD

**Issue by jangrewe** [nZEDb/nZEDb#1662]
Hi guys, this just started to appear in my post pane in tmux:
```
PHP Fatal error: Class 'NZB' not found in /srv/nzedb/nzedb/libraries/Forking.php on line 818
PHP Fatal error: Class 'NZB' not found in /srv/nzedb/nzedb/libraries/Forking.php on line 763
```

**Comment by Wally73** [comment]
same as https://github.com/nZEDb/nZEDb/issues/1659

**Comment by jangrewe** [comment]
oh, sorry, i did only a quick scan of the issue names for NZB and Forking... i'll close this one.
