### ISSUE TITLE
Invalid xml response in /var/www/nZEDb/libs/AmazonProductAPI.php:363

### ISSUE THREAD

**Issue by Loopher** [nZEDb/nZEDb#1667]
This is from the 5/11 dev branch:  I am getting the following error on my tmux screen, under the post processing section for the Amazon stuff.  Here is my entry from the postprocessing_amazon-20150511.log file.

[38;5;011mNo book releases to process for category id 8060[0m
[38;5;011mProcessing 28 console release(s).[0m
[38;5;011mLooking up: [0m[38;5;010mPSP  UMDGen 4 00   EDecrypter 1 4 (PSP)[0m
PHP Fatal error:  Uncaught exception 'Exception' with message 'Invalid xml response.' in /var/www/nZEDb/libs/AmazonProductAPI.php:363
Stack trace:
#0 /var/www/nZEDb/libs/AmazonProductAPI.php(243): AmazonProductAPI->verifyXmlResponse(Object(SimpleXMLElement))
#1 /var/www/nZEDb/nzedb/Console.php(670): AmazonProductAPI->searchProducts('PSP  UMDGen 4 0...', 'VideoGames', 'NODE', '11075221')
#2 /var/www/nZEDb/nzedb/Console.php(320): nzedb\Console->fetchAmazonProperties('PSP  UMDGen 4 0...', '11075221')
#3 /var/www/nZEDb/nzedb/Console.php(722): nzedb\Console->updateConsoleInfo(Array)
#4 /var/www/nZEDb/nzedb/processing/PostProcess.php(172): nzedb\Console->processConsoleReleases()
#5 /var/www/nZEDb/misc/update/postprocess.php(91): nzedb\processing\PostProcess->processConsoles()
#6 {main}
  thrown in /var/www/nZEDb/libs/AmazonProductAPI.php on line 363
[38;5;011m
Processing 7 book release(s) for category ID 3030[0m

**Comment by scottia** [comment]
getting this as well.  can't process Amazon at all.  Amazon key is testing good.

[12-May-2015 20:01:21 America/Chicago] PHP Fatal error:  Uncaught exception 'Exception' with message 'Invalid xml response.' in /var/www/nZEDb/libs/AmazonProductAPI.php:363
Stack trace:
#0 /var/www/nZEDb/libs/AmazonProductAPI.php(243): AmazonProductAPI->verifyXmlResponse(Object(SimpleXMLElement))
#1 /var/www/nZEDb/nzedb/Console.php(670): AmazonProductAPI->searchProducts('LGS Shinsetsu H...', 'VideoGames', 'NODE', '11075221')
#2 /var/www/nZEDb/nzedb/Console.php(320): nzedb\Console->fetchAmazonProperties('LGS Shinsetsu H...', '11075221')
#3 /var/www/nZEDb/nzedb/Console.php(722): nzedb\Console->updateConsoleInfo(Array)
#4 /var/www/nZEDb/nzedb/processing/PostProcess.php(173): nzedb\Console->processConsoleReleases()
#5 /var/www/nZEDb/nzedb/libraries/Forking.php(882): nzedb\processing\PostProcess->processConsoles()
#6 /var/www/nZEDb/nzedb/libraries/Forking.php(160): nzedb\libraries\Forking->processSingle()
#7 /var/www/nZEDb/nzedb/libraries/Forking.php(102): nzedb\libraries\Forking->getWork()
#8 /var/www/nZEDb/misc/update/nix/multiprocessing/postprocess.php(22): nzedb\lib in /var/www/nZEDb/libs/AmazonProductAPI.php on line 363

**Comment by niel** [comment]
Just pushed something that will hopefully deal with this.
https://github.com/nZEDb/nZEDb/commit/429158d9c18239c1760869ca95c44640a842b7ac

**Comment by scottia** [comment]
getting close
Notice: Undefined variable: amaz in /var/www/nZEDb/nzedb/Console.php on line 328

**Comment by niel** [comment]
Sorry, I did the previous coding last thing before going to bed - bad idea ;-)
Working on a proper fix now.

**Comment by scottia** [comment]
Thank you so much.  Last fix this am, resolved it.
