### ISSUE TITLE
Renamed Releases Lose Leading "S" Character

### ISSUE THREAD

**Issue by Enverex** [nZEDb/nZEDb#1684]
I've noticed this a few times and it seems oddly specific so I can only assume it's a bug. What is happening is that some releases are being renamed correctly, but they lose the leading S on the Author or Title. So for example "Bob Bobson - Summer Holiday" would become "Bob Bobson - ummer Holiday".

An example I just saw was:
![image](https://cloud.githubusercontent.com/assets/958670/7670676/33088db2-fca6-11e4-8454-e0c196adb0f1.png)

Where Steve Vai became "teve Vai". The renamer in question here was "sorter audioNFO".

Also to clarify, I've only ever seen this happen with the S character, no other letters seem to be affected.

**Comment by Bart39** [comment]
merged the fix
