### ISSUE TITLE
IRCScraper Directory not moved

### ISSUE THREAD

**Issue by PRLdef** [nZEDb/nZEDb#1697]
https://github.com/nZEDb/nZEDb_Misc/blob/master/Guides/Various/IRCScraper/Guide.md
In the notes section, it claims "May 10th 2015 -> misc/testing/IRCScraper/ moved to misc/IRCScraper/" but it wasn't moved. I did a fresh gitpull of nzedb on a new install May 21 2015.

**Comment by kevinlekiller** [comment]
It's moved on dev branch. Will eventually be moved when changes go to master.
