### ISSUE TITLE
issue with user editing after PR 1705

### ISSUE THREAD

**Issue by gregster85** [nZEDb/nZEDb#1708]
Since PR 1705 has been merged to dev branch, when you click a username (for example in the forum posts), you always end up viewing your own user.
When logged in as the admin user, this is quite annoying.

**Comment by zetas** [comment]
Ok, If this is referencing my change to close that security hole I'll
submit a new pr to add a secure way to view user profiles by admins.

I couldn't find a use for that code so I removed it.

Perhaps there should be an admin option in edit site to make user
profiles public or not.

**Comment by zetas** [comment]
Hrm, mine was #1707. #1705 was just regex changes, I'll assume it was a typo. Incoming PR to restore admin access to profiles.

**Comment by Bart39** [comment]
fix merged in dev
