### ISSUE TITLE
Bug - Select all + delete in adv search not working

### ISSUE THREAD

**Issue by rainje** [nZEDb/nZEDb#1713]
When using the adv search and clicking the select all checkbox and then clicking the admin delete button it only refreshes the page, all results are still there. 

However I think I found the issue.

When clicking the select all checkbox it also checks two checkboxes in the search box, after unchecking both of them the delete button is now functional.

![bug](https://cloud.githubusercontent.com/assets/1025666/7984909/cc4e23e0-0acc-11e5-918f-d0531b7cd770.png)

It may be related to #283

**Comment by Bart39** [comment]
unfortunately sinfuljosh is no longer around so i dont think #283 is going to be fixed anytime soon

**Comment by rainje** [comment]
I'm pretty sure it's a small js issue, i'll check and may push.
