### ISSUE TITLE
Fatal error: Undefined class constant 'SERIALIZER_IGBINARY'

### ISSUE THREAD

**Issue by scottia** [nZEDb/nZEDb#1717]
running "sudo php test_cache_server.php" fails with 

Fatal error: Undefined class constant 'SERIALIZER_IGBINARY' in /var/www/nZEDb/nzedb/libraries/Cache.php on line 306

If I set the following to "1 [Requires igbinary]", I receive the fatal error when testing my cache server (redis).  When set to "2 - [Redis Only]"  the test is successful.  I do have Redis compiled with igbinary.

 * 0 - Use the PHP serializer.
 * 1 - [Requires igbinary] Use igbinary serializer which is faster and uses less memory, works on both Memcached and Redis.
 * 2 - [Redis Only] Use no serializer.

Everything is running great as "2 - [Redis Only]" only but I don't know if I am taking advantage of using a Serializer or not.  Or is that a valid error and 1 should be using "1 - [Requires igbinary]"?  Which is correct?

**Comment by Bart39** [comment]
if your on dev is this still an issue ? as the cache stuff has been rewritten since you opened this

**Comment by scottia** [comment]
Yes, same error different spot since the most recent changes to DEV when set to 1 (Redis) / 1 (Igbinary), 

Running "sudo php test_cache_server.php" fails with 
Fatal error: Undefined class constant 'SERIALIZER_IGBINARY' in /var/www/nZEDb/nzedb/libraries/Cache.php on line 399

Redis Only (2) and NOW APC (3) both seem to run fine.

Whats the preferred setup out of all the choices ?

**Comment by kevinlekiller** [comment]
I'm looking into it.

**Comment by kevinlekiller** [comment]
See the guide here: https://github.com/nZEDb/nZEDb_Misc/blob/master/Guides/Various/Cache/Guide.md

The error you see is probably related to loading igbinary after redis.

You can try following the guide / recompiling to make sure.

**Comment by scottia** [comment]
i checked the order and redis.so is after igbinary.  the guide is perfect btw.

i also re-compiled everything and still receive the Fatal error.

i think its because I compiled Redis with igbinary and selected Igbinary as my serializer in settings instead of Redis Only.  Selecting Redis as the cache and Redis under serializer passes the test, no problem.

If I try apc as my cache and igbinary as the serializer I always get "apc extension is not loaded" and the test fails.  however php -m always shows it loaded.

i dont think I quite understand what settings I should use or the best strategy to follow.

**Comment by kevinlekiller** [comment]
@scottia there might be an issue with that, I submited a PR

**Comment by kevinlekiller** [comment]
#1724 for reference

**Comment by kevinlekiller** [comment]
Hopefully that PR fixes your "Fatal error: Undefined class constant 'SERIALIZER_IGBINARY' in /var/www/nZEDb/nzedb/libraries/Cache.php on line 399" issue.

**Comment by scottia** [comment]
Cool.  Thank you. Kevin.  I will pull it in a little bit if it isn't pushed and let you know.

**Comment by kevinlekiller** [comment]
@scottia can you PM me on IRC?

**Comment by scottia** [comment]
I can in a little bit.  Not near IRC right now

**Comment by scottia** [comment]
Closing.  Resolved via #1724 and other corrections.
