### ISSUE TITLE
Tmux IRCScraper, bad path

### ISSUE THREAD

**Issue by kevinlekiller** [nZEDb/nZEDb#1718]
https://github.com/nZEDb/nZEDb/blob/master/nzedb/TmuxRun.php#L701

The folder has moved, it is not in misc/testing anymore, it is in misc/

**Comment by Bart39** [comment]
fixed in https://github.com/nZEDb/nZEDb/commit/1408a78b6d1289da1dd628da0bfda2eb39ebfc9e
