### ISSUE TITLE
Profile edits not being saved

### ISSUE THREAD

**Issue by Fossil01** [nZEDb/nZEDb#1731]
Encountered this issue in both my custom theme and alpha theme.

When I try to save my updated profile things like movieview, xxxview, bookview etc. and queue type, sab URLs etc. are not being saved to the DB. I verified this by looking at the users table.

Here's some POST data I vardumped after I deselected movieview and musicview and changed queue type to sab:

```
array(17) {
  ["email"]=>
  string(16) "<REMOVED EMAIL FOR GITHUB>"
  ["password"]=>
  string(0) ""
  ["confirmpassword"]=>
  string(0) ""
  ["consoleview"]=>
  string(1) "1"
  ["bookview"]=>
  string(1) "1"
  ["xxxview"]=>
  string(1) "1"
  ["queuetypeids"]=>
  string(1) "1"
  ["nzbgeturl"]=>
  string(34) "http://<REMOVED URL FOR GITHUB>:6789/"
  ["nzbgetusername"]=>
  string(6) "nzbget"
  ["nzbgetpassword"]=>
  string(10) "tegbzn6789"
  ["nzbvortex_server_url"]=>
  string(30) "http://localhost:8080/sabnzbd/"
  ["nzbvortex_api_key"]=>
  string(6) "343333"
  ["cp_api"]=>
  string(0) ""
  ["cp_url"]=>
  string(0) ""
  ["firstname"]=>
  string(0) ""
  ["lastname"]=>
  string(0) ""
  ["style"]=>
  string(0) ""
}
```

But nothing of that is written to the DB. When I type in another email address which is not correct it does return with an error. So that function gets the data OK.

I am running the master branch, fully updated.

**Comment by DariusIII** [comment]
Remove nzbvortex_server_url and nzbvortex_api_key from your templates, as those are leftovers from your newznab/nntmux install.

**Comment by Fossil01** [comment]
Will try but it also did not work with the default alpha theme.

**Comment by Fossil01** [comment]
Nope did not work either.

**Comment by Fossil01** [comment]
With a little help from @DariusIII it turned out to be a caching issue. Clearing templates_c did wonders.
