### ISSUE TITLE
GZip Compression ??

### ISSUE THREAD

**Issue by scottia** [nZEDb/nZEDb#1735]
I keep seeing this as of last and its creating issues with Bins, by filling the screen with illegal characters and stalling the script.  I use Usenetserver with compressed headers and have for over a year now.  Am running current on DEV.

Any ideas ?

![image](https://cloud.githubusercontent.com/assets/5298748/8274304/c6f0b210-1854-11e5-85ba-60215c74140d.png)

**Comment by Fossil01** [comment]
Turn off compressed headers (for now at least). AFAIK only Astraweb works well with compression.

**Comment by Enverex** [comment]
Compressed headers worked fine for me on Highwinds (ThunderNews) and SuperNews.

**Comment by Fossil01** [comment]
Maybe I rely on old knowledge (newznab).

**Comment by scottia** [comment]
Yes, i can disable compressed headers but I believe my bandwidth might be dropping or dropped off for some other reason, resulting in a failed request.  I have been flawless using compression for a long while now so this is new.

@Fossil01 Compressed Headers are faster and saves overall bandwidth usage.  if your ISP tracks or reviews your usage, it would appear as twice or more the amount used w/out compressed headers.  Not a big deal for some, especially me but I do see a performance gain vs. de-selecting the option and its worked quite well except in the past few days.

**Comment by scottia** [comment]
Download the same amount of headers in less time using compression is what I mean by a performance benefit, not your download speed itself.  That does not change.

**Comment by Bart39** [comment]
nothing relevant has changed in the last couple of days so it must be a problem with your USP

**Comment by scottia** [comment]
@Bart39 Before i close.  Do you use compressed headers?

**Comment by Bart39** [comment]
yes i do, newshosting

**Comment by scottia** [comment]
Thanks Everyone!  closed

**Comment by scottia** [comment]
Sweet!  Thanks @kevinlekiller

**Comment by kevinlekiller** [comment]
No problem.
