### ISSUE TITLE
Size saved to NZB files, appears broke in both master and dev

### ISSUE THREAD

**Issue by tonymorella** [nZEDb/nZEDb#1739]
About 2 weeks ago I did a pull on dev and releases stopped being created.  I did a wipe and started over and just did min config to get this back up and running.   Today I started making changes and figured out what's going on. When I set the Min Size under a group I am able to replicate the problem.  Via Admin > Releases > View Releases the file sizes are all sub 10MB vs what they were in the past, the GB range.  When I look at the Release via the home screen I see two "Size" fields, one is the size of the unrar file, .mkv for example, but I am not sure what the other is for but assume the size of the nzb itself??  In any chase something changed, I did could not find any details in the release notes.  This happens on both the master and dev builds.

**Comment by kevinlekiller** [comment]
How are you typing them in? Those settings are in bytes.

It's possible issues have arose with those settings.

**Comment by tonymorella** [comment]
I had a few groups previously working using the size in bytes.  I did a
quick scan on the code but could not find anything related, but I am not a
programmer, when you say it's possible what files / changes are you
thinking about??

Tony

**Comment by kevinlekiller** [comment]
It looks to be done here https://github.com/nZEDb/nZEDb/blob/dev/nzedb/processing/ProcessReleases.php#L420

**Comment by tonymorella** [comment]
FYI Noticed that the file size showing via sabnzdb is incorrect, same as in nzedb few MB, but the files are downloaded correctly. Could this be how the nzb files are being formatted?

**Comment by kevinlekiller** [comment]
No, I've seen other people have had this issue on IRC and it was down to improper configuration.

**Comment by tonymorella** [comment]
Had time to look at this again and posted findings to the nzedb forums. It comes down to the segment sizes in the nzb files created by nzedb.  I don't know why by they are much smaller then the same releases created by the example I used from nzbfriends.   

http://goo.gl/peX8T3

**Comment by niel** [comment]
does this happen with all releases or just some?

**Comment by tonymorella** [comment]
I my case all of them.  I was just looking at the DB > table parts >  colume size and it matches up with whats in the nzb file, i.e. smaller then it should be. So I think this is happening when the parts are downloaded and injected into the DB.

**Comment by niel** [comment]
Sounds like one of two possibilities:
1) The size is getting corrupted being inserted into the db or coming out of it when the NZB is created.
2) The wrong size is being reported by the USP.
Given that you are the only person reporting this specific problem, the latter is most likely. That being said, I'll still look into the code to see if it's possible that it corrupts the value at some point.

**Comment by tonymorella** [comment]
I made a comment on issue #1758 which I think is the same thing from looking at the nzbs posted, same issues with small segment size.

**Comment by tonymorella** [comment]
Have an update, just created a temp account on tweaknews.eu and wouldn't you know it the segment size is correct!  So something changed at frugalusenet.com becouse everthing was working a few months back.  Anyway to trouble shoot why this is happening?
