### ISSUE TITLE
[ERROR] mysqld: Deadlock

### ISSUE THREAD

**Issue by tonymorella** [nZEDb/nZEDb#1743]
Starting getting [ERROR] mysqld: Deadlock found when trying to get lock; try restarting transaction

pt-deadlock-logger is showing the following for example:

nzedb binaries_1000040 PRIMARY RECORD X w 1 INSERT INTO binaries_1000040 (binaryhash, name, collection_id, totalparts, currentparts, filenumber, partsize) VALUES ('eb9bfe74e59857a16dbe6e80c01d605b', 'Adobe Cs 5 5 Master Collection Keygen All Suites For Windows.rar yEnc', 490053, 2, 1, 0, 1306) ON DUPLICATE KEY UPDATE currentparts = currentparts + 1, partsize = partsize + 1306

Double checked the confirm and everything is setup as per the docs, doing a google search brings up references to the queries but I did find one recommendation to try "transaction-isolation   = READ-COMMITTED" but this did not help.

**Comment by DariusIII** [comment]
In your www/settings.php change use transactions to false.

**Comment by tonymorella** [comment]
This stopped the issue but was taking 300+ sec to process a group.  Changed
is back to true but also change "Update Binaries Threads" from 5 to 1 and
now this issues is resolved, but not ideal.

Thanks for the help!
Tony


On Wed, Jun 24, 2015 at 3:59 AM, DariusIII <notifications@github.com> wrote:

> In your www/settings.php change use transactions to false.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nZEDb/nZEDb/issues/1743#issuecomment-114773047>.
>



-- 
Thank you
Tony
