### ISSUE TITLE
PHP Fatal error:  Class 'Smarty' not found in autopatcher.php

### ISSUE THREAD

**Issue by testarea1** [nZEDb/nZEDb#1752]
I use the autopatcher.php script to do a git pull/db update and smarty clear but ever since the smarty changes it's throwing an error:

`PHP Fatal error:  Class 'Smarty' not found in /var/www/nZEDb/misc/testing/DB/autopatcher.php on line 12`

**Comment by niel** [comment]
That script isn't exactly supported anymore. It needs a bit of work.
I'll take a quick look to see if I can make it use the cli/update_db.php script, which has this problem fixed.

**Comment by niel** [comment]
Fixed in commit https://github.com/nZEDb/nZEDb/commit/2a4ab18b6d4ba0d80e77c13f339f89a152361f4b
