### ISSUE TITLE
Incorrect time interval in NameFixer

### ISSUE THREAD

**Issue by bfincher** [nZEDb/nZEDb#1754]
The interval assigned to "timeother" is NOW() - INTERVAL 0 HOUR.  Where the timeall interval is 6 hours.  This seems to always be returning zero releases.  I have tried some manual queries using the 0 hour clause and always get no results.  Shouldn't it be 6 hours?

**Comment by DariusIII** [comment]
I guess you are right.

**Comment by bfincher** [comment]
Closing as a pull request has been submitted.
