### ISSUE TITLE
All nzb files empty???

### ISSUE THREAD

**Issue by thejrose1984** [nZEDb/nZEDb#1758]
Fresh install of nZEDb, added some groups, and allowed indexing for a few days now...any attempts to send a nzb to sabnzbd fails because the nzb's are showing as empty...no clue what's going on here...

I tried downloading the nzb files and just putting them in the watch folder for sabnzbd and it starts downloading, but the content is clearly not what I am seeking.

**Comment by Sweepr** [comment]
Are the NZB's also empty if you look in \nZEDb\resources\nzb\ just pick a random NZB

**Comment by thejrose1984** [comment]
The problem is when I send the nzb directly to my queue, it loads into sabnzbd as an empty nzb file. If I download the nzb and drop it in sabnzbd's watch folder. It looks fine, but the content isn't there. I don't know if it's an issue with the group(s) I'm using, nZEDb, or both but I utilize other indexers and don't have issues.

For example - I'll look for a NZB corresponding to an episode from this year's Shark Week. If I add it to my queue, Sabnzbd reports it's empty. If I download the same NZB and place it in my watch folder, it loads into Sabnzbd fine, but the download is for 1-2MB (which I know for a fact can't be right).

**Comment by Sweepr** [comment]
Could you download an nzb to your local pc and open it with notepad and post the contents in pastebin?

If i look here for example i see proper files, https://www.usenet-crawler.com/search?val=shark%20week&index=3, just as a reference. no files smaller than 300mb

Looking at the information you provided it has either to do with the way you've setup nZEDb, from experience some groups contain ALOT of rubbish and other crap you have to find out a way to filter this the good from the bad by playing with the settings.

But first i'd like to see the real contents of the NZB which you say is empty.

**Comment by Sweepr** [comment]
PS, about the "un-identifiable content" read:

http://forums.nzedb.com/index.php?topic=1860.0

**Comment by thejrose1984** [comment]
My feeling it has to do with configuring my instance of nZEDb
http://pastebin.com/esknZVtQ

**Comment by Sweepr** [comment]
That's weird.

I copied the data from the file from your pastbin, named it test.nzb and dropped it into my SabNZBd's watchdir, it picked up and started downloading.

The weird thing is.. according SabNZBd the files size said to be 2MB, but the download took much longer, also no ETA was given, the download completed succesfully, unpacked and watching a working Shark Week Episode right now..

??

**Comment by thejrose1984** [comment]
And it can't be sent directly to Sabnzbd, it has to been put into the watched folder...

**Comment by Sweepr** [comment]
Hehe, no, clearly not the sharks.. 

Not sure where to go from here, maybe someone else has any idea what the problem is?

Maybe you could post a screenshot of the releases created on the site, hopefully we can figure out what going on here.

**Comment by thejrose1984** [comment]
How's this?
![2015-07-12 19_27_57-search nzbs - an indexer](https://cloud.githubusercontent.com/assets/7573083/8640605/40625180-28cc-11e5-8760-bd862d4f97cf.png)

FYI - I downloaded two from the list without issue aside from no ETA and file sizes being misrepresented...of course that doesn't explain the original issue of empty NZB files being sent to Sabnzbd :)

**Comment by jonnyboy** [comment]
When you say you copied and pasted the text, was/is the first line of the nzb file blank? My recollection is that is usually the cause. My be worth a second or two to confirm that the first line of the nzb is or is not a blank line.

**Comment by thejrose1984** [comment]
@jonnyboy first line is not blank

**Comment by Fossil01** [comment]
I have some of those tiny releases as well. I guess it's just a USP issue (NewsDemon and Supernews for me).

They get deleted by removecrapreleases because of the size.

**Comment by tonymorella** [comment]
AHH I am not the only one going nuts, I just updated the issues I created 29 days ago :)  Also posted findings on the forums. I am able to use the nzb to download the files and it processes correcly as long as I don't let the searchs (Sonarr) uses the file size to score the nzb. The issue is the segment size is smaller then it should be, I can see the same issue in your example   

NZEDB:
<segment bytes="1013" number="1">1436629219.03070.1@reader.easyusenet.nl</segment>

nzbfriends:
<segment bytes="786990" number="1">1436629219.03070.1@reader.easyusenet.nl</segment>

http://goo.gl/peX8T3
