### ISSUE TITLE
update_db error

### ISSUE THREAD

**Issue by gazaz** [nZEDb/nZEDb#1765]
Haven't had an active site for a while now. Did a full install of DEV release a few days ago and everything was working fine.

Did git pull this morning and there was a big update with different templates. My site has now stopped working. White pages when browsing. Restarted nginx, rebooted and mysql seems to be running ok.

Got an error when using php update_db.php true 

PHP Fatal error:  Class 'nzedb\db\Text' not found in/var/www/nZEDb/nzedb/db/DB.php on line
 1150

Is there a problem with the most recent dev release or am I doing something wrong ?? Also posted this on the forum.

**Comment by niel** [comment]
That's an problem with dev. I'll look into it ASAP

**Comment by niel** [comment]
Fixed in https://github.com/nZEDb/nZEDb/commit/b657fcbbe8352ededfeb79212be82bc09a62a60d
