### ISSUE TITLE
Utility.php failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by testarea1** [nZEDb/nZEDb#1766]
Unable to open any /details/ page on site after dev pull today. Apache error log shows:

`PHP Warning:  require_once(/var/www/nZEDb/nzedb/utility/Utility.php): failed to open stream: No such file or directory`

**Comment by DariusIII** [comment]
I guess it happened on console, games or music page?

**Comment by testarea1** [comment]
It's happening on any url with /detail/

I can bring up any page before that, but if you try to go into the detail of any release, the page is just blank.

**Comment by niel** [comment]
Fixed in commit https://github.com/nZEDb/nZEDb/commit/39b5ac6f767eb60b818515fdccc93388f66a2a30
