### ISSUE TITLE
Themes (charisma/omicrom) nzbget/sabnzbd integration only visible from search results

### ISSUE THREAD

**Issue by rabbixx** [nZEDb/nZEDb#1776]
DEV:
(no option to send nzb to nzbget/sabnzbd)
![nzedb_pic1](https://cloud.githubusercontent.com/assets/13499811/8890778/9f883f54-32c1-11e5-9b4d-187965c68d0a.jpg)

(search results show nzbget send option)
![nzedb_pic2](https://cloud.githubusercontent.com/assets/13499811/8890779/a7b1cc40-32c1-11e5-935f-394d504c8439.jpg)

**Comment by DariusIII** [comment]
The four icons you highlighted in first screenshot are: download nzb, comments, send to cart and last one is send to my queue (aka. send to to sab/nzbget). Search, on the other hand, is something i need to fix.

**Comment by rabbixx** [comment]
"send to my queue" and "send to my cart" currently are not doing anything that I can tell. I can click each button, although there is no kind of feedback shown after clicking.  If I check my queue or my cart both show nothing.   Both the queue and cart have never worked for me though, on dev or on master.

There is one difference I see with the queue between the alpha and charisma themes on the current dev branch I have installed (this is with the exact same settings, just switching themes).  The charisma theme shows that message in the bottom left.

Still in both themes I am unable to send an item to the queue.  Maybe I have something configured wrong...

![nzedb_pic3](https://cloud.githubusercontent.com/assets/13499811/8891018/e8f046fa-32cb-11e5-9a27-c5d12fd2a106.jpg)
![nzedb_pic4](https://cloud.githubusercontent.com/assets/13499811/8891020/edaa4416-32cb-11e5-8164-56aeee9f2002.jpg)

**Comment by DariusIII** [comment]
I have made a PR with fix related to queue handling. When it is merged, the issue will be fixed.
