### ISSUE TITLE
Tmux Error - Process Releases -> Request ID Threaded lookup

### ISSUE THREAD

**Issue by testarea1** [nZEDb/nZEDb#1778]
In Tmux monitor:

![image](https://cloud.githubusercontent.com/assets/2273360/8891869/5ee96b94-32ee-11e5-9826-8f8547779d0a.png)

Only error I'm seeing after dev update to 6858a66b11007a088ff0b4d0d0085b07c168ca0b

**Comment by niel** [comment]
Why are you using the python scripts?

**Comment by testarea1** [comment]
Tmux uses all that by default. All I do is run  `/var/www/nZEDb/misc/update/nix/tmux/start.php` and that's part of the steps it runs automatically within the tmux monitor tab, I've never configured any of that manually.

**Comment by testarea1** [comment]
So it looks like if the site settings have "Lookup Request IDs Threaded" it errors (threaded uses they py scripts?), but changing it the non threaded it works fine (I've always just had it on threaded forever):

Error settings in admin control panel:
![image](https://cloud.githubusercontent.com/assets/2273360/8892714/bbf386d2-331e-11e5-83a6-1ffe8ce5d3c0.png)

No more error in the non threaded mode now. May cause issues if anyone else uses that in threaded mode.

**Comment by kevinlekiller** [comment]
@testarea1 I did a search, found this https://github.com/nZEDb/nZEDb/blob/ae41462f0abbf356da8187f0b86fe6ab4adb3493/nzedb/processing/ProcessReleases.php#L194

I guess 2 is "threaded" ?

Might need some other option to select between the python and php one then.

**Comment by DariusIII** [comment]
We have some redundancy (is this the right word?) here, as python uses the php script again:
https://github.com/nZEDb/nZEDb/blob/ae41462f0abbf356da8187f0b86fe6ab4adb3493/misc/update/python/requestid_threaded.py#L68

**Comment by niel** [comment]
Weird, I thought Kevin had removed all the Python dependencies for threaded scripts in tmux. When time permits I'll try to get rid of this one ;-)

**Comment by niel** [comment]
BTW I updated the scripts and pushed to dev, can you let me know if that worked for you please.
