### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by bfincher** [nZEDb/nZEDb#1782]
When you click on a release to see details, you go to the URL 'details/GUID/RELEASE_NAME'.  Similar for clicking to download a NZB you go to the URL 'getnzb/GUID/RELEASE_NAME'.

This works for most releases but for some I get an error in my browser saying the page is not found.  This seems to only be happening when the release name is really long.  However, if I remove the RELEASE_NAME from the URL the page is found.  

This brings me to my suggestion:  If the details and getnzb pages work with only the GUID, why include the release name in the URL if it causes it to sometimes not work?

**Comment by kevinlekiller** [comment]
Fixed.
