### ISSUE TITLE
Tmux run_ircscraper variable is not getting set

### ISSUE THREAD

**Issue by Kruemmelmonster** [nZEDb/nZEDb#1788]
The run_ircscraper variable is not showing up in the MySQL Settings table nor is it in the www/admin/tmux-edit.php file thats why the tmux monitor says its disabled or terminated.
Inserting a line in the table with the variable run_ircscraper does not fix it unfortunatly

Greets Kru~

**Comment by DariusIII** [comment]
No. You understood it completely wrong. You need to enable tmux in tmux edit page located in admin area. You need to set tmux as enabled.

**Comment by Kruemmelmonster** [comment]
yeah i just realized that its already importing PreDB stuff into the Database but still the tmux monitor of the import is not working
