### ISSUE TITLE
scrape.php references config.php from www instead of nzedb/config

### ISSUE THREAD

**Issue by bfincher** [nZEDb/nZEDb#1798]
in misc/testing/IRCScraper/scrape.php.  I tried changing the requireonce to use the correct path but then got the error "Use of undefined constant nZEDb_ROOT.

**Comment by niel** [comment]
What branch is this? And how do you know it's trying in www?

**Comment by bfincher** [comment]
master branch.  it has a require_once on www/config.php

**Comment by niel** [comment]
In which case this is fixed in dev

**Comment by bfincher** [comment]
the latest version of the file in dev still references www/config.php

**Comment by niel** [comment]
I just checked committed master and it is fixed there too. what's the exact URL you are looking at?

**Comment by bfincher** [comment]
It looks like there is an IRCScraper directory in misc and misc/testing.  I was using the one in testing which hasn't been updated.  I'll just change to use the one in misc but the other one should be removed.  Sorry for the confusion.

**Comment by bfincher** [comment]
Closed as result of pull request.

**Comment by niel** [comment]
The other isn't removed automatically because it would also delete your configuration file.

**Comment by bfincher** [comment]
The config file isn't under CM control so it should be safe to remove all
of the files that are under control in testing/IRCScraper.

**Comment by niel** [comment]
When we remove, we'll take the directory too. If we did that now, the config file would go too.

**Comment by bfincher** [comment]
We can delete the files from git which will remove everything except for
the config file.  Then I see in the new scrape code that you will move the
config file to the new config directory.

**Comment by niel** [comment]
Sure, I'll do that.
