### ISSUE TITLE
 php predb_import_daily_batch.php not working for me

### ISSUE THREAD

**Issue by Sweepr** [nZEDb/nZEDb#1802]
when i run:  php predb_import_daily_batch.php 0 local true

I get this in the error_log:

[07-Aug-2015 18:13:51 Europe/Amsterdam] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[28000]: Invalid authorization specification: 1045 Access denied for user 'user_nzedb'@'localhost' (using password: YE$
Stack trace:
#0 /home/public_html/nZEDb/nzedb/db/PreDb.php(122): PDOStatement->execute(Array)
#1 /home/public_html/nZEDb/cli/data/predb_import_daily_batch.php(146): nzedb\db\PreDb->executeLoadData(Array)
#2 {main}
  thrown in /home/public_html/nZEDb/nzedb/db/PreDb.php on line 122

I just pulled the latest master 10 min's ago, 

http://forums.nzedb.com/index.php?topic=2075.0

Does anyone know what this could be?

**Comment by Sweepr** [comment]
it's funny because everything else is working fine.

**Comment by kevinlekiller** [comment]
You need the FILE permission in MySQL.

**Comment by kevinlekiller** [comment]
I recommend reading this section https://github.com/nZEDb/nZEDb_Misc/blob/master/Guides/Installation/Ubuntu/Guide.md#step-7-configuring-mysql

**Comment by Sweepr** [comment]
Ok thanks.. i'll read these files and see if i can figure out what wrong here

**Comment by Sweepr** [comment]
After this: GRANT FILE ON *.* TO 'YourMySQLUsername'@'YourMySQLServerHostName'; the message above disappeared, but seeing another:


[07-Aug-2015 19:14:43 Europe/Amsterdam] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 13 Can't get stat of '/home/public_html/nZEDb/resources/1404152742_predb_dump.csv' (Errcode: 13)' in /home/public_html/nZEDb/nzedb/db/PreDb.php:122
Stack trace:
#0 /home/public_html/nZEDb/nzedb/db/PreDb.php(122): PDOStatement->execute(Array)
#1 /home/public_html/nZEDb/cli/data/predb_import_daily_batch.php(146): nzedb\db\PreDb->executeLoadData(Array)
#2 {main} thrown in /home/public_html/nZEDb/nzedb/db/PreDb.php on line 122

**Comment by kevinlekiller** [comment]
Need to your permissions on your file system for that file.

**Comment by Sweepr** [comment]
Ok, checking.

**Comment by kevinlekiller** [comment]
Also you need to make sure your O/S doesn't have a program that blocks MySQL to read files. Like apparmor https://github.com/nZEDb/nZEDb_Misc/blob/master/Guides/Installation/Ubuntu/Guide.md#step-5-mandatory-apparmor

**Comment by Sweepr** [comment]
No it does not have any, also checked the mysql variable local-infile = on , should be fine.

**Comment by kevinlekiller** [comment]
Try using remote instead of local, it sometimes gets around permission issues.

**Comment by Sweepr** [comment]
Tsss., that actually worked.. ;-)

**Comment by Sweepr** [comment]
Info: Clearing import table
Info: Deleting any records where title <=8 from Temporary Table
Info: Inserting records from temporary table into predb table
Successfully imported PreDB dump 1404152742 406 dumps remaining to import.
Info: Clearing import table
Info: Deleting any records where title <=8 from Temporary Table
Info: Inserting records from temporary table into predb table
Successfully imported PreDB dump 1404235402 405 dumps remaining to import.
Info: Clearing import table
Info: Deleting any records where title <=8 from Temporary Table
Info: Inserting records from temporary table into predb table
Successfully imported PreDB dump 1404321805 404 dumps remaining to import.
Info: Clearing import table
Info: Deleting any records where title <=8 from Temporary Table
Info: Inserting records from temporary table into predb table
Successfully imported PreDB dump 1404408208 403 dumps remaining to import.
Info: Clearing import table
Info: Deleting any records where title <=8 from Temporary Table
Info: Inserting records from temporary table into predb table
Successfully imported PreDB dump 1404494610 402 dumps remaining to import.
Info: Clearing import table
Info: Deleting any records where title <=8 from Temporary Table
Info: Inserting records from temporary table into predb table


thanks!
