### ISSUE TITLE
TV show thumbnail on TV details page not displaying

### ISSUE THREAD

**Issue by testarea1** [nZEDb/nZEDb#1803]
Just pulled dev update 7ccf96e1ad43b420ad5142320f5cc01d94c0985a after all the updates and looks like everything is working except the TV show thumbnails on the show /details/ page. Image is broken. In checking the code, it's trying to grab the image from `src="/getimage?type=tvrage&amp;id=` but that link is showing as 404 and the id= is blank. Movie detail page images are fine, just appears to be related to TV.

**Comment by kevinlekiller** [comment]
Should be good now. Thanks.

**Comment by testarea1** [comment]
Yup, all good now, thanks.
