### ISSUE TITLE
Movie Trailers not being created

### ISSUE THREAD

**Issue by testarea1** [nZEDb/nZEDb#1811]
Seemed to happen around the time of Aug 7 when trailer code changes happened. I still have trailers for the movies that had it before the dev pull around that time, but any move added after has no trailer.

**Comment by Bart39** [comment]
i could be wrong but these come from trakt now - do you have a trakt api key set ?

**Comment by testarea1** [comment]
Yeah, API has been entered for a while now, worked fine before the updates regarding trailers. I also read trakt doesn't use an api key on v2 of their api anymore? Is zed using trakt api v2?

**Comment by Bart39** [comment]
yes it is using v2

**Comment by Bart39** [comment]
v2 does require the client id from your trakt app

trakt-api-key *	Your client_id listed under your trakt applications.

**Comment by testarea1** [comment]
No luck. I created a new api app key on trakt but nothing has changed, still no trailers.

**Comment by DariusIII** [comment]
Have you updated to latest dev, as some changes are made last night regarding trailers?

**Comment by testarea1** [comment]
Yeah, I just pulled 035d15a1c0760d3b6c892a54e5d6cd11929db17a about 30 minutes ago, but was up to date before that.

**Comment by DariusIII** [comment]
And no errors in logs whatsoever?

**Comment by testarea1** [comment]
No errors at all anywhere. Trailers worked fine, and then I did a dev pull and they stopped around Aug 7th. That was the only change that was done.

**Comment by Bart39** [comment]
as per changelog all trailers now come via trakt so they will only save to movieinfo if all other lookups fail when postprocessing movies - they will however dynamically display any available trailers from trakt on the nzb details page when you view them

**Comment by Bart39** [comment]
ignore previous comment it does save them

**Comment by testarea1** [comment]
Trailers are back now, thanks.
