### ISSUE TITLE
403 Forbidden Errors

### ISSUE THREAD

**Issue by thejrose1984** [nZEDb/nZEDb#1812]
Had to do a fresh install within a FreeNAS jail. I followed the instructions I made from last time, but seem to be getting a 403 Forbidden response. I have already confirmed all settings are valid. I also checked the logs from lighttpd and this is the only thing I see:

`nzedb - [14/Aug/2015:09:31:22 -0400] "GET /favicon.ico HTTP/1.1" 200 318 "http://nzedb/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.155 Safari/537.36"`

**Comment by niel** [comment]
That's an HTTPD access log entry, does lighttpd have a separate error log, if so check that? Also make sure the PHP error logging is enabled and check that, as it's far more likely to contain useful information.

**Comment by thejrose1984** [comment]
PHP error logging is enabled, but when I check the log file, nothing is showing
Confirmed the following was set in php.ini file...

`display_errors = Off`

`log_errors = On`

`error_log = /var/log/php-errors.log`

Web server has ownership of the log file and has read/write permissions as file owner. Any ideas why PHP error logging still doesn't document?

**Comment by thejrose1984** [comment]
Nevermind - typo on my part on the PHP error log file...

**Comment by Sweepr** [comment]
Inside your php.ini:

display_errors = on
error_reporting = E_ALL & ~E_NOTICE

Then restart your web server.

**Comment by thejrose1984** [comment]
Did that, no change and nothing being logged

**Comment by Sweepr** [comment]
Do you try to make the log file writable by www-data? or whatever your apache user is called?

sudo touch /var/log/php-errors.log
sudo chown www-data:www-data /var/log/php-errors.log

**Comment by thejrose1984** [comment]
@Sweepr I have established that already - please see comment above

**Comment by ruhllatio** [comment]
If he's getting a 403, I doubt PHP would even be involved at that point.  I'd be looking more at file permissions in /var/www/nZEDb/www.

**Comment by thejrose1984** [comment]
Also set accordingly:

`drwxr-xr-x  8 www  www  14 Aug 14 09:23 /usr/local/www/nZEDb/www/`

**Comment by Sweepr** [comment]
Right..

@thejrose1984 , what does your lighttpd logfile show?

**Comment by ruhllatio** [comment]
When you did your pre-flight did you have any warnings?

**Comment by thejrose1984** [comment]
Ran a tail of the access log (again) and just see this:

`"GET / HTTP/1.1" 403 345 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.155 Safari/537.36"`

`"GET / HTTP/1.1" 403 345 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.155 Safari/537.36"`

Error log simply shows when I've restarted the web service:

`2015-08-14 09:32:20: (server.c.1563) server stopped by UID = 0 PID = 20636`

`2015-08-14 09:32:20: (log.c.164) server started`

`2015-08-15 12:59:20: (server.c.1563) server stopped by UID = 0 PID = 85736`

`2015-08-15 12:59:21: (log.c.164) server started`

`2015-08-15 13:06:40: (server.c.1563) server stopped by UID = 0 PID = 86144`

`2015-08-15 13:06:40: (log.c.164) server started`

`2015-08-15 13:35:24: (server.c.1563) server stopped by UID = 0 PID = 87255`

`2015-08-15 13:35:25: (log.c.164) server started`

`2015-08-15 13:37:39: (server.c.1563) server stopped by UID = 0 PID = 87360`

`2015-08-15 13:37:40: (log.c.164) server started`

**Comment by thejrose1984** [comment]
@ruhllatio haven't done pre-flight yet because of this issue...whether I try to point my browser to http://nzedb (same thing happens when using the resolved IP address) or go directly to install...

**Comment by ruhllatio** [comment]
Oh, right.  IIRC there are permissions that should be set for PHP sessions to the www user.  Also check perms on /nZEDb/libs/smarty/templates_c

**Comment by thejrose1984** [comment]
@ruhllatio if you look at the install WIKI I published for FreeNAS, you'll notice I have the following command used after running git clone for the code...

Deploying the nZEDb code from GitHub:

`cd /usr/local/www

`git clone https://github.com/nZEDb/nZEDb.git`

`chown –R www:www nZEDb`

`service lighttpd start`

**Comment by thejrose1984** [comment]
Mind you, when I was writing this document, I was at my wits end because it was an extreme cause of trial and error so if there's something in my documentation that is off, please advise and update the wiki...

**Comment by ruhllatio** [comment]
IDK man, I don't do FreeNAS.  As for jails I did ten years of up in state penn, now I'm out praise allah.

**Comment by thejrose1984** [comment]
@ruhllatio the issue has, at most, 2% of the problem with being on FreeNAS. The core issue is either in the web server config or PHP settings - both of which are independent of the platform.

**Comment by ruhllatio** [comment]
@thejrose1984 - did you still need help with this?

**Comment by thejrose1984** [comment]
@ruhllatio yes.

**Comment by ruhllatio** [comment]
Can you come in IRC for help?

**Comment by niel** [comment]
error_reporting = E_ALL & ~E_NOTICE
No!
Our code is intended to run clean, i.e. NO error notices, which means that if any are reported it is a problem that needs to be dealt with. Please use: error_reporting = E_ALL for nZEDb

**Comment by ruhllatio** [comment]
I'm convinced it's because you haven't actually configured anything to handle PHP files.  I see in your guide that you modify cgi.conf.  I that everyone used fastcgi?  Create a bullshit index.html file, drop it in the directory and see if you can get to it.  If you can, you know what the problem is.

**Comment by niel** [comment]
I'm pretty much in agreement with ruhllatio. At the very least the configurations have to be verified/validated first to be sure they're not the problem.
My familiarity with FreeNAS is much less than I would like, but I wonder why you went with Lighttpd when nginx is the default on there. I have no experience with lighttpd, so can't help out with its testing. I can try testing with nginx on my FreeNAS server.

**Comment by thejrose1984** [comment]
It's not a matter of FreeNAS - that's just the platform. The issue is either with PHP or the Web server. I only used lighttpd because I was advised from multiple sources to use a lightweight web server. I also tried with Apache 2.4 and having similar issues...I will need to spin up a new jail and try again...

**Comment by ruhllatio** [comment]
Apache2.4 should be good to go out of the box with the few customizations we make (overrides) listed in the other install guides.  Honestly, unless you're running it on a RasPi the web server doesn't need to be lightweight especially if you only have a few users.  To me, it boils down to a preference issue.  Some people prefer NGINX.  Some people prefer Apache.

**Comment by niel** [comment]
I'd recommend nginx, as it is FreeNAS' default web server and a few of the devs use it. There are instructions for its configuration in the Ubuntu guide.

**Comment by ruhllatio** [comment]
I think he switched to NGINX and got it working based on the forum posts.
