### ISSUE TITLE
Tmux Post Process XXX error.

### ISSUE THREAD

**Issue by moloquin** [nZEDb/nZEDb#1814]
Updated to latest dev and seeing this in the post pane in tmux.  All other categories seem to be post processing properly.

Error: SQLSTATE[42522]: Column not found: 1054 Unknown column 'r.categoryid' in 'where clause'

[nzedb\db\DB.queryExec] [UPDATE release SET xxxinfo_id = #### WHERE id = ######## AND r.categoryid IN (6010, 6020, 6030, 6040, 6080,6090)]

Switching back to master seems to clear things up and processing goes normally.

**Comment by ruhllatio** [comment]
Please... don't switch back and forth from master to dev unless it has been recently merged.  You are almost certainly screwing up your CBP and releases tables right now.  I will fix the issue.

**Comment by ruhllatio** [comment]
Issue should be fixed.  Forgot to add the # to the Issue number so it isn't displaying here but w/e.

**Comment by moloquin** [comment]
Looks to be fixed now.  Thanks.
