### ISSUE TITLE
No Cover view Consoles! 

### ISSUE THREAD

**Issue by Atmos01** [nZEDb/nZEDb#1819]
Hi All,

Everything else works fine! Only no cover view for consoles. I just switched to dev maybe this helps..

Anything else i could check?

**Comment by Atmos01** [comment]
when i go to https://www.com/admin/console-list.php its also empty.. When i just browse for consoles i can see all releases..

**Comment by Sweepr** [comment]
What happens when you run "php postprocess.php all true "

**Comment by Atmos01** [comment]
its processing all consoles but nothing appears on cover view.. also still zero releases found in adminpanel.

**Comment by Atmos01** [comment]
This: 0% consoles.

![image](https://cloud.githubusercontent.com/assets/13801996/9300516/1fbe788e-44c7-11e5-9aa4-54fe19cd9093.png)

![image](https://cloud.githubusercontent.com/assets/13801996/9300530/4b55407c-44c7-11e5-8c44-79186b7930df.png)

**Comment by DariusIII** [comment]
One of the patches, i think 372 or 373 which tackled releases table might be the cause of this. Check one of the console releases in releases table, it might have the values in columns wrong.

**Comment by Atmos01** [comment]
no idea where to look.. i do not know how its suposed to look.. i see that the consoleid is -2

here is a export from xbox360 releases: http://www.filedropper.com/releases

**Comment by DariusIII** [comment]
you have some strange group_id's there. Can you do:
SELECT name FROM groups WHERE id = 1000050;

And some of the releases have completion of 0.

**Comment by Atmos01** [comment]
alt.binaries.games.xbox360

**Comment by Atmos01** [comment]
anybody? :(

**Comment by taskym** [comment]
what about account settings? there is a checkbox to view covers:  Browse console covers. Only shows games with known lookup info.

**Comment by Atmos01** [comment]
When i turn that off, i just get a list view of all releases.. as soon when i turn it on i get the msg

**Comment by taskym** [comment]
is there anything in your consoleinfo table? any errors in your php log?

**Comment by Atmos01** [comment]
consoleinfo is empty, no errors in apache/mysql or phplog

**Comment by Atmos01** [comment]
When processing consoles i do not see "Added" only this:

![image](https://cloud.githubusercontent.com/assets/13801996/9324086/40853cd6-4587-11e5-9e69-2ba2d0d0f2a7.png)

**Comment by DariusIII** [comment]
Have you entered your amazon key? Maybe amazon has disabled it?

**Comment by Atmos01** [comment]
Yes, music and books are working.. So is games ,xxx and movies.. only consoles giving me sh*t :D

**Comment by taskym** [comment]
turn debug on in nzedb and rerun the processing consoles script.

**Comment by Atmos01** [comment]
so, i turned on debug in config.. I do not see any errors relating to consoles when i rerun postprocessing consoles

I started over with a clean install (master) and have the same problem.

**Comment by Atmos01** [comment]
isnt there a developer who can tell me where to look? I am lost :-( 
Im trying to get this working for some time now.. 

Please help!

**Comment by DariusIII** [comment]
This is very strange error, most likely caused by some configuration error.

**Comment by Atmos01** [comment]
I installed a new server, installed fresh nzedb, changed amazon keys and still no covers for consoles!

configuration error where lol? everything works except consoles.

**Comment by ruhllatio** [comment]
Can you give me a good release name to search for?  I index console and have plenty of covers.  Would like to see if I have matched one you haven't.

**Comment by ruhllatio** [comment]
@Atmos01 Reset your failed console releases by running the reset_postprocessing consoles false script in /misc/testing/DB/ and see what you get now.
