### ISSUE TITLE
getImdb.php not pulling info

### ISSUE THREAD

**Issue by scottia** [nZEDb/nZEDb#1826]
Shouldn't "nZEDb/misc/testing/PostProcess/getImdb.php" search for empty imdb number by title?  Script stopped working and always returns nothing.

Now I use "nZEDb/misc/testing/PostProcess/getMovieCovers.php" since it seems to look and update Imdb as well but don't know if it can use or uses Trakt.Tv as a lookup if not Imdb cover found?

Please advise ..

**Comment by Bart39** [comment]
that script looks for records with an imdbid but no tmdbid

**Comment by Bart39** [comment]
but probably needs looking at as the defaults are not null any more

**Comment by scottia** [comment]
I remember seeing the tmdb value changes earlier but thought it still looked for imdb value?.  Just need a way to search for covers or populate movie release that are missed for all sources.

Thanks..

**Comment by Bart39** [comment]
"php reset_postprocessing.php movies false" will search for those without covers, samples, previews, etc.

**Comment by Bart39** [comment]
thats in misc/testing/DB btw

**Comment by scottia** [comment]
Yes, I just like to run while sequential is running, side by side.  

getMovieCovers has alot of problems now anyway with this :+1: [17-Aug-2015 11:37:25 America/Chicago] PHP Notice:  Undefined index: title in /var/www/nZEDb/nzedb/Movie.php on line 1002

I will stick with resetting them for now.

**Comment by scottia** [comment]
By the way, "php reset_postprocessing.php movies false"  still says ZERO Imdb's reset

**Comment by scottia** [comment]
Resolved, closing
