### ISSUE TITLE
0375-0376~binaryblacklist.sql update error

### ISSUE THREAD

**Issue by tonymorella** [nZEDb/nZEDb#1828]
resources/db/patches/mysql/0375~binaryblacklist.sql and 0376~binaryblacklist.sql asume the blacklist has not been updated and uses row 13.  An error will happen with the insert if addidtinal blacklists have been added, in my cast 29 total.  I changed the two files to the next usable row, 30, and the updates process as expected.

**Comment by terbonium** [comment]
Maybe @ruhllatio can tweak the patch:

ALTER TABLE binaryblacklist ENGINE=InnoDB AUTO_INCREMENT=1000;
INSERT INTO binaryblacklist (groupname,regex,msgcol,optype,status,description) SELECT groupname,regex,msgcol,optype,status,description FROM binaryblacklist WHERE id >= 13;
DELETE FROM binaryblacklist WHERE id >= 13 AND id < 1000;

**Comment by ruhllatio** [comment]
If your schema were correct, your manual additions would be starting at ID 100000.  I would start with your first blacklist and change the ID or else you will have continued problems.  First set your auto_increment to a reasonable value.  

https://github.com/nZEDb/nZEDb/blob/master/resources/db/schema/mysql-ddl.sql#L148

**Comment by ruhllatio** [comment]
@terbonium Doing that would screw things up for all of our users who are on the correct schema with the right autoinc values.  We'd have to parse the auto_increment value first before changing it to an arbitrary 1000 as the schema sets it at 100000.

**Comment by tonymorella** [comment]
Ah, figured out what happened, imported a blacklist from razorgirl which set the number vs using autoinc.  Fix the numbering.  
Thanks
Tony
