### ISSUE TITLE
[Bug - minor] Multiselected nzbs do not honor recategorization

### ISSUE THREAD

**Issue by mtompkins** [nZEDb/nZEDb#1829]
For example, a release in the Movies->HD category has multiple listings. All listings should have been in TV->SD. If you select all the listings and click [EDIT] you are presented with a modal window to recategorize all selected. After making a change and hitting save, no changes are made.

This is true in the alpha theme - unknown if others are working properly.

Editing each individual release on the individual page does work correctly.

**Comment by ruhllatio** [comment]
Fixed in dev-tv branch commit a2df79e430959fa303502a960b297aed2a05d40a
