### ISSUE TITLE
Register page blank / error

### ISSUE THREAD

**Issue by littlefinger54** [nZEDb/nZEDb#1830]
Everything on the site seems fine except the Register page. I've spoken with Archer on IRC a few weeks ago and was familiar with / working on this issue.

Blank page is displayed and the following is written to the error.log: 

2015/08/18 16:08:34 [error] 1570#0: *13 FastCGI sent in stderr: "PHP message: PHP Warning:  require_once(SmartyException.php): failed to open stream: No such file or directory in
/var/www/nZEDb/www/SPLClassLoader.php on line 158
PHP message: PHP Fatal error:  require_once(): Failed opening required 'SmartyException.php' (include_path='/var/www/nZEDb/www/:.:/usr/share/php:/usr/share/pear') in
/var/www/nZEDb/www/SPLClassLoader.php on line 158" while reading response header from upstream, client: <MY IPADDRESS>, server: <SERVER ADDRESS>, request: "GET /register HTTP/1.1",
upstream: "fastcgi://127.0.0.1:9000", host: "<SERVER ADDRESS>"

**Comment by niel** [comment]
This was fixed. Which branch?

**Comment by littlefinger54** [comment]
* master

**Comment by niel** [comment]
I'll need more details then as it works fine for me.

**Comment by littlefinger54** [comment]
the fix appears to have partially worked , I was able to git pull I then moved config.php and settings.php to /nZEDb/config/ and comment require_once 'automated.config.php'; from config.php 

When I attempt to load the site the install page is displayed **Index Usenet. Now.
Welcome to nZEDb.

Before getting started, you need to make sure that the server meets the minimum requirements. You will also need...

Your database credentials.
Your news server credentials.
SSH & root ability on your server (in case you need to install missing packages).

WARNING:
This software is not practical for use on shared hosting. You should only use this on a server where YOU have the required privileges and knowledge to solve any challenges that might appear.
Installation Locked! If reinstalling, please remove www/install/install.lock.**

**Comment by littlefinger54** [comment]
found the error on my part, config goes in nZEDb/nzedb/config/ all working fine now.
