### ISSUE TITLE
Files containing subtitles stripped out somehow.

### ISSUE THREAD

**Issue by zetas** [nZEDb/nZEDb#1831]
This seems to be endemic to all nZEDb installations. All the indexers we've checked known to be based on nZEDb have the same issue, though I don't know what versions/branches they are all running. I'm running 0.4.22 and I haven't seen anything in the changelog/release notes that makes me think this issue is fixed, please let me know otherwise.

Examples:

![image](https://cloud.githubusercontent.com/assets/1036810/9336965/6c26b9aa-45aa-11e5-83fa-410869c6c0f3.png)
Notice how file 9-13/27 are missing? Those are files with the word "subs" in the title. 

Same release from a different non-nZEDb indexer:
![image](https://cloud.githubusercontent.com/assets/1036810/9336986/9a699fb2-45aa-11e5-9a61-8d5c0b0bc29b.png)
9/27. 10/27, 11/27, 12/27, and 13/27 all there and accounted. 

There are many more examples that users have brought to my attention but I think this one proves the point for the most part. You can also look this release up on many other nn+ and nZEDb based indexers and find the same results. Something in the PP is stripping out those files for some reason.

**Comment by Bart39** [comment]
its more likely to be bad regex thats not grouping them in the first place rather than pp removing them

**Comment by Bart39** [comment]
yea its regex - i'll fix it

**Comment by Bart39** [comment]
won't fix existing releases but at least new ones should be grouped correctly

**Comment by zetas** [comment]
Thanks. I made the change locally and we'll see if it fixes it. Closing until then.
