### ISSUE TITLE
Smarty internal string displayed on clean install

### ISSUE THREAD

**Issue by EeGgSs** [nZEDb/nZEDb#1832]
clean ubuntu install following https://github.com/nZEDb/nZEDb_Misc/blob/master/Guides/Installation/Ubuntu/Guide.md

on install pre flight check page ( http://ip.address/install/step1.php? ) -- **string(49) "/var/www/nZEDb/www/pages/Smarty_Internal_Data.php" string(55) "/var/www/nZEDb/www/pages/admin/Smarty_Internal_Data.php" string(57) "/var/www/nZEDb/www/pages/install/Smarty_Internal_Data.php"** is displayed at the top of the page.

Step 2 (db setup) -- **string(49) "/var/www/nZEDb/www/pages/Smarty_Internal_Data.php" string(55) "/var/www/nZEDb/www/pages/admin/Smarty_Internal_Data.php" string(57) "/var/www/nZEDb/www/pages/install/Smarty_Internal_Data.php" string(65) "/var/www/nZEDb/www/pages/Smarty_Internal_TemplateCompilerBase.php" string(71) "/var/www/nZEDb/www/pages/admin/Smarty_Internal_TemplateCompilerBase.php" string(73) "/var/www/nZEDb/www/pages/install/Smarty_Internal_TemplateCompilerBase.php" string(58) "/var/www/nZEDb/www/pages/Smarty_Internal_Templatelexer.php" string(64) "/var/www/nZEDb/www/pages/admin/Smarty_Internal_Templatelexer.php" string(66) "/var/www/nZEDb/www/pages/install/Smarty_Internal_Templatelexer.php" string(59) "/var/www/nZEDb/www/pages/Smarty_Internal_Templateparser.php" string(65) "/var/www/nZEDb/www/pages/admin/Smarty_Internal_Templateparser.php" string(67) "/var/www/nZEDb/www/pages/install/Smarty_Internal_Templateparser.php" string(63) "/var/www/nZEDb/www/pages/Smarty_Internal_ParseTree_Template.php" string(69) "/var/www/nZEDb/www/pages/admin/Smarty_Internal_ParseTree_Template.php" string(71) "/var/www/nZEDb/www/pages/install/Smarty_Internal_ParseTree_Template.php" string(54) "/var/www/nZEDb/www/pages/Smarty_Internal_ParseTree.php" string(60) "/var/www/nZEDb/www/pages/admin/Smarty_Internal_ParseTree.php" string(62) "/var/www/nZEDb/www/pages/install/Smarty_Internal_ParseTree.php" string(58) "/var/www/nZEDb/www/pages/Smarty_Internal_ParseTree_Tag.php" string(64) "/var/www/nZEDb/www/pages/admin/Smarty_Internal_ParseTree_Tag.php" string(66) "/var/www/nZEDb/www/pages/install/Smarty_Internal_ParseTree_Tag.php" string(56) "/var/www/nZEDb/www/pages/Smarty_Internal_CompileBase.php" string(62) "/var/www/nZEDb/www/pages/admin/Smarty_Internal_CompileBase.php" string(64) "/var/www/nZEDb/www/pages/install/Smarty_Internal_CompileBase.php" string(59) "/var/www/nZEDb/www/pages/Smarty_Internal_ParseTree_Text.php" string(65) "/var/www/nZEDb/www/pages/admin/Smarty_Internal_ParseTree_Text.php" string(67) "/var/www/nZEDb/www/pages/install/Smarty_Internal_ParseTree_Text.php" string(64) "/var/www/nZEDb/www/pages/Smarty_Internal_Extension_CodeFrame.php" string(70) "/var/www/nZEDb/www/pages/admin/Smarty_Internal_Extension_CodeFrame.php" string(72) "/var/www/nZEDb/www/pages/install/Smarty_Internal_Extension_CodeFrame.php" string(55) "/var/www/nZEDb/www/pages/Smarty_Internal_Write_File.php" string(61) "/var/www/nZEDb/www/pages/admin/Smarty_Internal_Write_File.php" string(63) "/var/www/nZEDb/www/pages/install/Smarty_Internal_Write_File.php"**

required to manually save config.php and install.lock 

attempting to load the completed setup displays install page / Installation Locked! If reinstalling, please remove www/install/install.lock.

**Comment by niel** [comment]
Looks like a configuration error for the HTTP server. Please enable PHP logging as per that same guide and provide the error log from that. If it doesn't create one, it is almost certainly a configuration/setup problem.

**Comment by EeGgSs** [comment]
Enable logging, attempting to load install/step1.php? the following is displayed at the top of the page 
**string(49) "/var/www/nZEDb/www/pages/Smarty_Internal_Data.php" string(55) "/var/www/nZEDb/www/pages/admin/Smarty_Internal_Data.php" string(57) "/var/www/nZEDb/www/pages/install/Smarty_Internal_Data.php" string(65) "/var/www/nZEDb/www/pages/Smarty_Internal_TemplateCompilerBase.php" string(71) "/var/www/nZEDb/www/pages/admin/Smarty_Internal_TemplateCompilerBase.php" string(73) "/var/www/nZEDb/www/pages/install/Smarty_Internal_TemplateCompilerBase.php" string(58) "/var/www/nZEDb/www/pages/Smarty_Internal_Templatelexer.php" string(64) "/var/www/nZEDb/www/pages/admin/Smarty_Internal_Templatelexer.php" string(66) "/var/www/nZEDb/www/pages/install/Smarty_Internal_Templatelexer.php" string(59) "/var/www/nZEDb/www/pages/Smarty_Internal_Templateparser.php" string(65) "/var/www/nZEDb/www/pages/admin/Smarty_Internal_Templateparser.php" string(67) "/var/www/nZEDb/www/pages/install/Smarty_Internal_Templateparser.php" string(63) "/var/www/nZEDb/www/pages/Smarty_Internal_ParseTree_Template.php" string(69) "/var/www/nZEDb/www/pages/admin/Smarty_Internal_ParseTree_Template.php" string(71) "/var/www/nZEDb/www/pages/install/Smarty_Internal_ParseTree_Template.php" string(54) "/var/www/nZEDb/www/pages/Smarty_Internal_ParseTree.php" string(60) "/var/www/nZEDb/www/pages/admin/Smarty_Internal_ParseTree.php" string(62) "/var/www/nZEDb/www/pages/install/Smarty_Internal_ParseTree.php" string(58) "/var/www/nZEDb/www/pages/Smarty_Internal_ParseTree_Tag.php" string(64) "/var/www/nZEDb/www/pages/admin/Smarty_Internal_ParseTree_Tag.php" string(66) "/var/www/nZEDb/www/pages/install/Smarty_Internal_ParseTree_Tag.php" string(59) "/var/www/nZEDb/www/pages/Smarty_Internal_ParseTree_Text.php" string(65) "/var/www/nZEDb/www/pages/admin/Smarty_Internal_ParseTree_Text.php" string(67) "/var/www/nZEDb/www/pages/install/Smarty_Internal_ParseTree_Text.php" string(56) "/var/www/nZEDb/www/pages/Smarty_Internal_CompileBase.php" string(62) "/var/www/nZEDb/www/pages/admin/Smarty_Internal_CompileBase.php" string(64) "/var/www/nZEDb/www/pages/install/Smarty_Internal_CompileBase.php" string(64) "/var/www/nZEDb/www/pages/Smarty_Internal_Extension_CodeFrame.php" string(70) "/var/www/nZEDb/www/pages/admin/Smarty_Internal_Extension_CodeFrame.php" string(72) "/var/www/nZEDb/www/pages/install/Smarty_Internal_Extension_CodeFrame.php" string(55) "/var/www/nZEDb/www/pages/Smarty_Internal_Write_File.php" string(61) "/var/www/nZEDb/www/pages/admin/Smarty_Internal_Write_File.php" string(63) "/var/www/nZEDb/www/pages/install/Smarty_Internal_Write_File.php"**

and the following is written to the error log: 
**2015/08/21 15:27:52 [notice] 9661#0: signal process started
2015/08/21 15:28:22 [notice] 9698#0: signal process started
2015/08/21 15:28:39 [error] 859#0: *1 "/var/www/nZEDb/www/index.html" is not found (2: No such file or directory), client: <my.ip.add>, server: <my.ip.add>9, request: "GET / HTTP/1.1", host: "<my.ip.add>9"
2015/08/21 15:28:39 [error] 859#0: *2 "/var/www/nZEDb/www/index.html" is not found (2: No such file or directory), client: <my.ip.add>, server: <my.ip.add>9, request: "GET / HTTP/1.1", host: "<my.ip.add>9"
2015/08/21 15:29:29 [error] 859#0: *3 "/var/www/nZEDb/www/index.html" is not found (2: No such file or directory), client: <my.ip.add>, server: <my.ip.add>9, request: "GET / HTTP/1.1", host: "<my.ip.add>9"
2015/08/21 15:30:29 [error] 859#0: *4 "/var/www/nZEDb/www/index.html" is not found (2: No such file or directory), client: <my.ip.add>, server: <my.ip.add>9, request: "GET / HTTP/1.1", host: "<my.ip.add>9"
2015/08/21 15:31:29 [error] 859#0: *5 "/var/www/nZEDb/www/index.html" is not found (2: No such file or directory), client: <my.ip.add>, server: <my.ip.add>9, request: "GET / HTTP/1.1", host: "<my.ip.add>9"
2015/08/21 15:32:29 [error] 859#0: *6 "/var/www/nZEDb/www/index.html" is not found (2: No such file or directory), client: <my.ip.add>, server: <my.ip.add>9, request: "GET / HTTP/1.1", host: "<my.ip.add>9"
2015/08/21 15:33:29 [error] 859#0: *7 "/var/www/nZEDb/www/index.html" is not found (2: No such file or directory), client: <my.ip.add>, server: <my.ip.add>9, request: "GET / HTTP/1.1", host: "<my.ip.add>9"
2015/08/21 15:34:29 [error] 859#0: *8 "/var/www/nZEDb/www/index.html" is not found (2: No such file or directory), client: <my.ip.add>, server: <my.ip.add>9, request: "GET / HTTP/1.1", host: "<my.ip.add>9"
2015/08/21 15:35:29 [error] 859#0: *9 "/var/www/nZEDb/www/index.html" is not found (2: No such file or directory), client: <my.ip.add>, server: <my.ip.add>9, request: "GET / HTTP/1.1", host: "<my.ip.add>9"
2015/08/21 15:36:29 [error] 859#0: *10 "/var/www/nZEDb/www/index.html" is not found (2: No such file or directory), client: <my.ip.add>, server: <my.ip.add>9, request: "GET / HTTP/1.1", host: "<my.ip.add>9"
2015/08/21 15:37:29 [error] 859#0: *11 "/var/www/nZEDb/www/index.html" is not found (2: No such file or directory), client: <my.ip.add>, server: <my.ip.add>9, request: "GET / HTTP/1.1", host: "<my.ip.add>9"
2015/08/21 15:38:29 [error] 859#0: *12 "/var/www/nZEDb/www/index.html" is not found (2: No such file or directory), client: <my.ip.add>, server: <my.ip.add>9, request: "GET / HTTP/1.1", host: "<my.ip.add>9"
2015/08/21 15:39:29 [error] 859#0: *13 "/var/www/nZEDb/www/index.html" is not found (2: No such file or directory), client: <my.ip.add>, server: <my.ip.add>9, request: "GET / HTTP/1.1", host: "<my.ip.add>9"
2015/08/21 15:40:29 [error] 859#0: *14 "/var/www/nZEDb/www/index.html" is not found (2: No such file or directory), client: <my.ip.add>, server: <my.ip.add>9, request: "GET / HTTP/1.1", host: "<my.ip.add>9"
2015/08/21 15:41:28 [error] 859#0: *15 "/var/www/nZEDb/www/index.html" is not found (2: No such file or directory), client: <my.ip.add>, server: <my.ip.add>9, request: "GET / HTTP/1.1", host: "<my.ip.add>9"
2015/08/21 15:42:28 [error] 859#0: *16 "/var/www/nZEDb/www/index.html" is not found (2: No such file or directory), client: <my.ip.add>, server: <my.ip.add>9, request: "GET / HTTP/1.1", host: "<my.ip.add>9"
2015/08/21 15:43:28 [error] 859#0: *17 "/var/www/nZEDb/www/index.html" is not found (2: No such file or directory), client: <my.ip.add>, server: <my.ip.add>9, request: "GET / HTTP/1.1", host: "<my.ip.add>9"
2015/08/21 15:44:28 [error] 859#0: *18 "/var/www/nZEDb/www/index.html" is not found (2: No such file or directory), client: <my.ip.add>, server: <my.ip.add>9, request: "GET / HTTP/1.1", host: "<my.ip.add>9"
2015/08/21 15:45:28 [error] 859#0: *19 "/var/www/nZEDb/www/index.html" is not found (2: No such file or directory), client: <my.ip.add>, server: <my.ip.add>9, request: "GET / HTTP/1.1", host: "<my.ip.add>9"
2015/08/21 15:53:38 [error] 859#0: *45 FastCGI sent in stderr: "PHP message: PHP Notice:  Use of undefined constant nZEDb_LOGAUTOLOADER - assumed 'nZEDb_LOGAUTOLOADER' in /var/www/nZEDb/www/autoloader.php on line 17
PHP message: PHP Notice:  Use of undefined constant nZEDb_LOGAUTOLOADER - assumed 'nZEDb_LOGAUTOLOADER' in /var/www/nZEDb/www/autoloader.php on line 17
PHP message: PHP Notice:  Use of undefined constant nZEDb_LOGAUTOLOADER - assumed 'nZEDb_LOGAUTOLOADER' in /var/www/nZEDb/www/autoloader.php on line 17
PHP message: PHP Notice:  Use of undefined constant nZEDb_LOGAUTOLOADER - assumed 'nZEDb_LOGAUTOLOADER' in /var/www/nZEDb/www/autoloader.php on line 17
PHP message: PHP Notice:  Use of undefined constant nZEDb_LOGAUTOLOADER - assumed 'nZEDb_LOGAUTOLOADER' in /var/www/nZEDb/www/autoloader.php on line 17
PHP message: PHP Notice:  Use of undefined constant nZEDb_LOGAUTOLOADER - assumed 'nZEDb_LOGAUTOLOADER' in /var/www/nZEDb/www/autoloader.php on line 17
PHP message: PHP Warning:  strftime(): Invalid date.timezone value 'Brisbane/Australia', we selected the timezone 'UTC' for now. in /var/www/nZEDb/libs/smarty/sysplugins/smarty_internal_templatecompilerbase.php on line 347
PHP message: PHP Notice:  Use of undefined constant nZEDb_LOGAUTOLOADER - assumed 'nZEDb_LOGAUTOLOADER' in /var/www/nZEDb/www/autoloader.php on line 17
PHP message: PHP Notice:  Use of undefined constant nZEDb_LOGAUTOLOADER - assumed 'nZEDb_LOGAUTOLOADER' in /var/www/nZEDb/www/autoloader.php on line 17
PHP message: PHP Notice:  Use of undefined constant nZEDb_LOGAUTOLOADER - assumed 'nZEDb_LOGAUTOLOADER' in /var/www/nZEDb/www/autoloader.php on line 17
PHP message: PHP Notice:  Use of undefined constant nZEDb_LOGAUTOLOADER - assumed 'nZEDb_LOGAUTOLOADER' in /var/www/nZEDb/www/autoloader.php on line 17
PHP message: PHP Notice:  Use of undefined constant nZEDb_LOGAUTOLOADER - assumed 'nZEDb_LOGAUTOLOADER' in /var/www/nZEDb/www/autoloader.php on line 17
PHP message: PHP Notice:  Use of undefined constant nZEDb_LOGAUTOLOADER - assumed 'nZEDb
2015/08/21 15:53:38 [error] 859#0: *45 FastCGI sent in stderr: "LOADER - assumed 'nZEDb_LOGAUTOLOADER' in /var/www/nZEDb/www/autoloader.php on line 17
PHP message: PHP Notice:  Use of undefined constant nZEDb_LOGAUTOLOADER - assumed 'nZEDb_LOGAUTOLOADER' in /var/www/nZEDb/www/autoloader.php on line 17
PHP message: PHP Notice:  Use of undefined constant nZEDb_LOGAUTOLOADER - assumed 'nZEDb_LOGAUTOLOADER' in /var/www/nZEDb/www/autoloader.php on line 17
PHP message: PHP Notice:  Use of undefined constant nZEDb_LOGAUTOLOADER - assumed 'nZEDb_LOGAUTOLOADER' in /var/www/nZEDb/www/autoloader.php on line 17
PHP message: PHP Notice:  Use of undefined constant nZEDb_LOGAUTOLOADER - assumed 'nZEDb_LOGAUTOLOADER' in /var/www/nZEDb/www/autoloader.php on line 17
PHP message: PHP Notice:  Use of undefined constant nZEDb_LOGAUTOLOADER - assumed 'nZEDb_LOGAUTOLOADER' in /var/www/nZEDb/www/autoloader.php on line 17
PHP message: PHP Notice:  Use of undefined constant nZEDb_LOGAUTOLOADER - assumed 'nZEDb_LOGAUTOLOADER' in /var/www/nZEDb/www/autoloader.php on line 17
PHP message: PHP Notice:  Use of undefined constant nZEDb_LOGAUTOLOADER - assumed 'nZEDb_LOGAUTOLOADER' in /var/www/nZEDb/www/autoloader.php on line 17
PHP message: PHP Warning:  strftime(): Invalid date.timezone value 'Brisbane/Australia', we selected the timezone 'UTC' for now. in /var/www/nZEDb/libs/smarty/sysplugins/smarty_internal_templatecompilerbase.php on line
347" while reading response header from upstream, client: <my.ip.add>, server: <my.ip.add>9, request: "GET /install/step1.php? HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "<my.ip.add>9", referrer:
"http://<my.ip.add>9/install/"
**

**Comment by niel** [comment]
Have you copied .../nzedb/config/settings.example.php to .../nzedb/config/settings.php and edited it as you want it?

**Comment by EeGgSs** [comment]
It appears to be an issue with master, I tried with dev branch and no errors are displayed and installs fine.

**Comment by niel** [comment]
OK. Master is due to be updated in a couple weeks time. If I can narrow down the specific cause of this I'll consider updating with the fix before then. Don't hold your breath though, as there is plenty of other stuff on my plate at the moment ;-)

**Comment by niel** [comment]
Incidentally, dev was merged into next-master branch today and that is what will go to master in two weeks time. If you would prefer to not be using dev (which breaks frequently - and is to be expected), then switching to next-master will let you have the benefits of dev, but easily allow you to update back to master on 7th Sept.

**Comment by littlefinger54** [comment]
Ok, thanks for your help niel.
