### ISSUE TITLE
processreleases.php error

### ISSUE THREAD

**Issue by davidritterhouse** [nZEDb/nZEDb#1834]
I am running the latest dev from 08/19/2015

Whether I run it in tmux or via command, I get an error:
php /var/www/nZEDb/misc/update/update_releases.php 1 true

It then errors with:
Process Releases -> Attempting to find complete collections.
PHP Fatal error:  Call to a member function rowCount() on a non-object in /var/www/nZEDb/nzedb/processing/ProcessReleases.php on line 1651
![post_process](https://cloud.githubusercontent.com/assets/13871539/9360003/cfe386d2-4661-11e5-861d-7474a630ec57.png)

**Comment by davidritterhouse** [comment]
line count after latest update:
PHP Fatal error:  Call to a member function rowCount() on a non-object in /var/www/nZEDb/nzedb/processing/ProcessReleases.php on line 1653

**Comment by davidritterhouse** [comment]
No error, but now after the first group pull, it goes into a loop.  Attached screenshot
![2015-08-19 17_59_33-mtputty multi-tabbed putty](https://cloud.githubusercontent.com/assets/13871539/9370380/dae6fee2-469d-11e5-923e-520e3943b15f.png)

**Comment by Bart39** [comment]
that loop is it catching up on the release creation that likely never finished due to your error - is it still looping ?

**Comment by davidritterhouse** [comment]
Yes, I left it run from last last night and its still looping over 9 hours now.

**Comment by davidritterhouse** [comment]
oh, the other thing is its now not deleting anything smaller or with less files.  So basically keeping everything.  I have files that are 1 file, when the minimum is set to 11 and I think its like 25megs minimum but I have app cracks showing up.

**Comment by Bart39** [comment]
how many collections / binaries / parts is tmux showing you ?

**Comment by Bart39** [comment]
it looks to me like its still looping through the release creation cycle catching up and has yet to hit the rest of the process that deletes smaller/larger releases etc

**Comment by davidritterhouse** [comment]
Collections is at 727k Binaries- 485k  
collections does not seem to go down and binaries has gone up.  Is this new because it never did this before.  Basically, its not getting new data at all .  Its weird because it just says, 0 releases added and 1000 duplicate collections deleted.  loops and does it all over, with same thing but nothing is getting done.  When I looked this morning, the newest release was over 7 hours ago.  If I go into tmux settings and turn tmux off, wait for everything to stop, then start it again, it pulls groups but then goes into loop after that first grab.

**Comment by Bart39** [comment]
727k collections is a lot - as i said before you are looping the release creation process 1500 releases at a time - it is trying to clear your backlog

**Comment by davidritterhouse** [comment]
anything i can do on my end to speed this up?
Thank you

**Comment by Bart39** [comment]
not really, other than increasing the number of release threads. that won't help if all the collections are against the one group though (one thread per group)

**Comment by davidritterhouse** [comment]
ok, thanks.  When does it start grabbing groups again?  Does collections have to get to 0?

**Comment by Bart39** [comment]
when it has finished creating the releases from complete collections (collections wont go to 0)

**Comment by Bart39** [comment]
keep an eye on the collection count and make sure its going down as its creating the releases (or deleting dupes)

**Comment by davidritterhouse** [comment]
Collections is not going down, its till at 727k which is the same as it was 2 hours ago.

**Comment by Bart39** [comment]
table per group ? or single collections table ?

**Comment by davidritterhouse** [comment]
single

**Comment by Bart39** [comment]
thats why its taking so long - you basically have a single thread processing all those collections

**Comment by davidritterhouse** [comment]
Which is the setting for doing table per group?  thanks Bart!

**Comment by davidritterhouse** [comment]
Ok, I figured out the table per group.  I am sitting at 12k collections and 20k binaries now.  At what point will it start grabbing new data?  Thanks again Bart

**Comment by davidritterhouse** [comment]
Bart,
Its still an issue.  Please view the screenshot.  It just goes into an infinite loop repeating the same stuff over and over again.
Cheers
![2015-08-22 23_25_56-mtputty multi-tabbed putty](https://cloud.githubusercontent.com/assets/13871539/9426813/afbed6b0-4925-11e5-9d56-59fef3144a7e.png)

**Comment by davidritterhouse** [comment]
Bart, I have rebuilt a brand new VM and what you are seeing is right from that.  Its a brand new install.  I have looked at the tables before and then after several hours of this loop I am seeing, and nothing has decreased in size (binaries or collections)  I am willing to run anything you might need to test or anything you need to help with this.

**Comment by davidritterhouse** [comment]
Bart,
Will this screenshot help?  It shows its not deleting any collections/binaries/parts older than 24 hours.
![not_removing](https://cloud.githubusercontent.com/assets/13871539/9428821/6bd773da-4989-11e5-967a-45cc78845c37.png)

**Comment by davidritterhouse** [comment]
This is about the last thing I can show you.  My complete settings.  Screenshots from tmux and settings page.  Is it a personal setting that is causing this just for me?

![settings](https://cloud.githubusercontent.com/assets/13871539/9428893/f4627982-498b-11e5-9523-d2d2892a831c.png)
![tmux_settings](https://cloud.githubusercontent.com/assets/13871539/9428892/f460560c-498b-11e5-9038-ceef8164bbc6.png)

**Comment by davidritterhouse** [comment]
Bart,  great read on this post: http://forums.nzedb.com/index.php?topic=2088.msg11645#msg11645

Discusses the drop trigger and it looks like I am not alone.

**Comment by ruhllatio** [comment]
Issue is now closed with the trigger deletion fix.
