### ISSUE TITLE
Support for passworded releases?

### ISSUE THREAD

**Issue by cytec** [nZEDb/nZEDb#1835]
Hi,

I was just wondering if there would be any need for password support. I'm running my own little indexer which is based upon (a really old version of) nZEDb. i've changed a lot of stuff the time i was setting up the indexer like: allow users to upload their own nzb files to index, support for passworded releases, and some other small stuff...

As i plan to update this site to a more recent version i was wondering if there is anyone out there having a need for those functions as well. I plan to do some of those changes again on the latest version in the near feature and just wanted to ask if a PR for that would be merged (generally) or if i can just skip trying getting that merged and just do the changes for myself.

So long talking short, here is what i plan to add:

1. Upload functionality for registered users (allow them to upload/index .nzb files from somewhere else)
2. Password Support for Releases (see down below for details)
3. Maybe assign the uploads to the user (also display who uploaded it on details page) but that's something im currently not really sure i want to do again...

By Password Support i mean the following:

Assumed the User Uploads a .nzb file from a forum/site which is password protected, he has the ability to include said password in the nzb filename in sabnzb's style (`Release {{password}}.nzb`)... The indexer will then (when importing new releases) go through the upload folder, importing the releases based on nzb Name cutting off the password part and adding to to the release table as a seperate field (ex: `rel_pass` or something similar) those releases will then not be deleted when password protected releases are processed IF have the needed `rel_pass` field 

When the release page is viewed there will be a password (if present) and the user has the ability to check/uncheck 2 options in his profile: 

1. append password to filename (would create `rel.name{{password}}.nzb`)
2. append password to nzb header (would append the password meta head to the nzb-file itself)

**Comment by niel** [comment]
Sound like features we would be interested in. See https://github.com/nZEDb/nZEDb/wiki/Contributing-Code-For-Beginners-to-Git(hub) for info on contributing code.

**Comment by cytec** [comment]
@niel sorry it took me a while i was pretty busy with work and some other things, i've implemented the password stuff here: https://github.com/nZEDb/nZEDb/compare/0.x...cytec:wizznab ... uploading for users is still on my todo list and should come in the next few days...

If you are still interested in this i'd make a PR once i've finished everything...

EDIT: just found out that i started this issue exactly 1 year ago 👍

**Comment by niel** [comment]
Hi. Good to see you back ;-) Please check our Contributing Code as I linked above. Main thing to note is we only take PRs against dev branch.

**Comment by cytec** [comment]
Yeah i know... I'll do a PR against dev once i'm done, just wanted to ask if you'll be interested in this before i'm gonna implement that stuff in dev branch again ;)

**Comment by usenetDude** [comment]
@cytec are you still working on this? Any status on what is needed to get this going?

**Comment by cytec** [comment]
@usenetDude I've got it working for me in the way i needed it at the time i was creating this issue... It's not that much of an effort to make it work... the changes are shown in the compare above... if i remember correctly it's a combination of 3 commits

totally forgot about this issue... if it's still something that'll be considered to be added i'm gonna go through my changes again and create a PR against the dev branch \cc @niel

**Comment by niel** [comment]
Look forward to the PR

**Comment by usenetDude** [comment]
Thank you very much for the answer. I'll copy my setup and try to get it working for me then. I only need the bulk import of passworded nzb, so no user-upload etc.
