### ISSUE TITLE
Not all "Covered" Movies showing ?

### ISSUE THREAD

**Issue by scottia** [nZEDb/nZEDb#1844]
I noticed my Movie counts (pages) with Covers slowly tapering down even though my Max Page Results is set at 500K.  However, if I manually change my "offset=XXXXX" number in the GUI (For example - http://192.168.0.8/movies?t=2000&title=&actors=&director=&rating=&genre=&year=&ob=&offset=14600#results) to a HIGHER number than what's shown in "Home" I see the missing Movie pages but the number count is off.

Here's a screen from a Manual edit.  Notice I have 760+ pages with covers (when manually changes) vs. 731 as shown in the 2nd screenshot below ?

![image](https://cloud.githubusercontent.com/assets/5298748/9457613/4d0f8cea-4aaa-11e5-94d4-cae7a4e13945.png)

Here is the 2nd screenshot showing a "Normal" home view of Movies with Covers.  Notice is shows 731 Movie releases with Covers vs. 760 show above?

![image](https://cloud.githubusercontent.com/assets/5298748/9457642/c4874542-4aaa-11e5-9b1f-c0c5e1e00ec3.png)

The started about 2 days ago when changes to Movies.php were made in DEV.  Since then I see the following error in my logs that may have something to do with it but I can't say for certain.

[24-Aug-2015 20:23:01 America/Chicago] PHP Notice:  Undefined index: title in /var/www/nZEDb/nzedb/Movie.php on line 1002

**Comment by scottia** [comment]
Now I have dropped all the way down to 709 Covered movies showing.  Very odd ?

![image](https://cloud.githubusercontent.com/assets/5298748/9473104/9bc9f162-4b1e-11e5-977b-ed97699f9e01.png)

**Comment by ruhllatio** [comment]
@scottia - is this still happening?  Are you still seeing those errors?  Which script?  I'm assuming movie processing...

**Comment by ruhllatio** [comment]
Near as I can tell, that error is coming from the TraktTv response.  Don't know much about how important that is in the long run, but it seems we aren't checking the return value of 'title' from them.  If that's the only error, it's not hurting anything because it is only doing an echo.

**Comment by scottia** [comment]
No error @ruhllatio 

The page count is off and slowely decreasing.  I am down to 702 pages of movies with covers according to the page but have over 750.  The longer I run, the lower it goes.  I don't appear to be missing releases..

**Comment by ruhllatio** [comment]
That's really strange.  I'm looking at the counts and it doesn't make sense.  Do you have a large backlog of movies to process?  Like did you do a reset on failed movies or something?

**Comment by ruhllatio** [comment]
Yeah, that has to be the case now that I'm looking at it.  The count function is looking for imdbid values on anything other than 0000000 or whatever.  Which means all releases that have imdbid at 0 (not yet processed) will match.  As the processing moves through if the movie matches it gets its IMDB ID which continues to match.  If it fails to match, to gets 0000000 assigned which makes literally no sense to do.  We should set them to -1 and query imdbid > 0.  This would give the user the false impression that they are losing releases or matches, when in fact it shouldn't be counting zero.

Do you have a movieinfo release matching 0?  I do.  Lego Justice Leage something or other.

`SELECT * FROM movieinfo WHERE imdbid = 0`

**Comment by scottia** [comment]
SELECT * FROM movieinfo WHERE imdbid = 0
Empty Set

I didn't have any but I think your onto something

**Comment by ruhllatio** [comment]
Gotta be something like that.  Gotta pack up and head home but we can run some checks later.  Jump into IRC for that.

**Comment by scottia** [comment]
Not a big deal @ruhllatio ~ have a good one.  I will be around some this weekend and will try and catch ya

**Comment by scottia** [comment]
I might know what's up based on your comment below but I don't quite get how setting imdb to 0  would affect the page count ?

"Yeah, that has to be the case now that I'm looking at it. The count function is looking for imdbid values on anything other than 0000000 or whatever. Which means all releases that have imdbid at 0 (not yet processed) will match. As the processing moves through if the movie matches it gets its IMDB ID which continues to match. If it fails to match, to gets 0000000 assigned which makes literally no sense to do. We should set them to -1 and query imdbid > 0. This would give the user the false impression that they are losing releases or matches, when in fact it shouldn't be counting zero."

From time to time I run the following query to clean "In Proess" Moves that will never be processed.  This is all I can think of that might affect the "Count" you speak of..  Thoughts ?

printf "\033[38;5;179mCount & Clean 'In Process' All Movies & Videos........";
echo "SELECT Count(*) FROM releases WHERE imdbID IS NULL and nzbstatus=1 and categoryID BETWEEN 2000 AND 2999;"
echo "update releases set imdbID = 0 WHERE imdbID IS NULL and nzbstatus=1 and categoryID BETWEEN 2000 AND 2999;"

**Comment by scottia** [comment]
Just an update.  I dumped everything and re-installed fresh, same issue.  Not all covered releases show, no matter the GUI setting.  I use "Show Everything".  The releases are there but the page counts slowly decrease.

**Comment by kevinlekiller** [comment]
I think it's an issue in the queries or something, but I'm not good enough to understand those.

**Comment by ruhllatio** [comment]
The only constraint difference between the count and the release query is the count looks for m.cover = 1 and the release query doesn't.  This produces a 6K count difference in distinct IMDB ID on my database.  Might account for some page counts being off.

**Comment by scottia** [comment]
How did you run that query?  I am off by about 200 releases or 10 pages with movie covers by manually changing the header value.

**Comment by ruhllatio** [comment]
```SELECT count(DISTINCT r.imdbid) FROM releases r INNER JOIN movieinfo m USING (imdbid) WHERE m.cover = 1 AND m.title != '' AND r.imdbid != '0000000' AND r.categoryid BETWEEN 2000 AND 2999;```

I think.  Try it without the m.cover=1 and see how big the difference is.

**Comment by scottia** [comment]
Yes there is a difference alright : 

MariaDB [nzedb]> SELECT count(DISTINCT r.imdbid) FROM releases r INNER JOIN movieinfo m USING (imdbid) WHERE m.cover = 1 AND m.title != '' AND r.imdbid != '0000000' AND r.categoryid BETWEEN 2000 AND 2999;
+--------------------------+
| count(DISTINCT r.imdbid) |
+--------------------------+
|                     7508 |
+--------------------------+
1 row in set (0.11 sec)

MariaDB [nzedb]> SELECT count(DISTINCT r.imdbid) FROM releases r INNER JOIN movieinfo m USING (imdbid) WHERE m.title != '' AND r.imdbid != '0000000' AND r.categoryid BETWEEN 2000 AND 2999;
+--------------------------+
| count(DISTINCT r.imdbid) |
+--------------------------+
|                     7829 |
+--------------------------+
1 row in set (0.05 sec)

MariaDB [nzedb]>

**Comment by scottia** [comment]
Reminder for @ruhllatio to check the query mentioned in #1920

**Comment by ruhllatio** [comment]
Thanks dude.  Let me revisit this.  I'm sure I'll push a half assed change shortly.

**Comment by scottia** [comment]
Yes that made a Big difference in Movies!!  Other categories need a similar change when you get a chance.

Thanks again

**Comment by ruhllatio** [comment]
Are you ever satisfied?

**Comment by Bart39** [comment]
scottia ? never :)

**Comment by scottia** [comment]
I am good.  Other might want more stuff, I never do :)
