### ISSUE TITLE
Notice: Undefined property: nzedb\Binaries::$tablePerGroup in /var/www/nZEDb/nzedb/Binaries.php on line 1093

### ISSUE THREAD

**Issue by tonymorella** [nZEDb/nZEDb#1845]
Notice: Undefined property: nzedb\Binaries::$tablePerGroup in /var/www/nZEDb/nzedb/Binaries.php on line 1093

Call Stack:
    0.0002     232888   1. {main}() /var/www/nZEDb/misc/update/update_binaries.php:0
    0.5044    2699720   2. nzedb\Binaries->updateGroup() /var/www/nZEDb/misc/update/update_binaries.php:31
    0.6131    2702456   3. nzedb\Binaries->daytopost() /var/www/nZEDb/nzedb/Binaries.php:316
    3.3049    2709360   4. nzedb\Binaries->postdate() /var/www/nZEDb/nzedb/Binaries.php:1213

Noticed this today when I added a new group.  I was able to get around the error by changing the new group backfill from days to posts,  but I still get this error when I enable backfill on the group. 

Thanks

**Comment by niel** [comment]
Already fixed in dev.

**Comment by tonymorella** [comment]
Thanks :)
