### ISSUE TITLE
Spaces in release names Frontend

### ISSUE THREAD

**Issue by Atmos01** [nZEDb/nZEDb#1846]
check the image:

http://imgur.com/wNiDDPV

**Comment by testarea1** [comment]
Is wordwrap needed? I removed the "wordwrap" code from my site alpha browse.tpl file and haven't had any issues with long filenames, this just caused issue with putting a space at the 30/60 character mark.

**Comment by Bart39** [comment]
i don't know - it was like that before ;) i'll look to maybe truncate long names as it does cause some issues

**Comment by testarea1** [comment]
Ok, I figured. I've always had issues with wordwrap on my site with the space in the title (it never actually ever wordwrapped for me, just put a space where it should) so I just removed it and haven't had any further issues, but everyone is different so I'm sure it's needed for something.

**Comment by Bart39** [comment]
http://i.imgur.com/XyG3dD9.png

**Comment by testarea1** [comment]
Strange, here is a screen of mine with some long titles and no issues after removing wordwrap:
![image](https://cloud.githubusercontent.com/assets/2273360/9481027/d076cb98-4b3b-11e5-9332-debe65498145.png)

I don't use that side menu like in your screen. Could that be pushing the main list together? Could this be a bootstrap responsive layout issue? I notice that if I change the browser size to a smaller window, I run into the issue you're showing in your screen with the black boxes (but show no issues full screen size at 1920+ resolution width):
![image](https://cloud.githubusercontent.com/assets/2273360/9481054/06ebc26e-4b3c-11e5-8980-8e51d71e17ef.png)

**Comment by Atmos01** [comment]
thanks
