### ISSUE TITLE
Three Arrows when viewing movie upper right corner

### ISSUE THREAD

**Issue by Atmos01** [nZEDb/nZEDb#1850]
![image](https://cloud.githubusercontent.com/assets/13801996/9539786/00528a38-4d57-11e5-90db-20ced6014935.png)

**Comment by ruhllatio** [comment]
We provided multiple options for going back, and this is the thanks we get.  Fine, I'll change two of the arrows to be a different color.

**Comment by Atmos01** [comment]
lol... it looked weird.. Did not know it was supposed to look like that.. I expected a  "< > x"

**Comment by ruhllatio** [comment]
Hah, wasn't being serious.  We'll look at it when we have a chance.
