### ISSUE TITLE
nZEDb_LIBSrarinfo

### ISSUE THREAD

**Issue by davidritterhouse** [nZEDb/nZEDb#1851]
when I try to run processAdditional.php I get a fatal error:

/usr/bin/php5 /var/www/nZEDb/nzedb/processing/post/ProcessAdditional.php ReleaseID: 235200
PHP Warning:  require_once(nZEDb_LIBSrarinfo/archiveinfo.php): failed to open stream: No such file or directory in /var/www/nZEDb/nzedb/processing/post/ProcessAdditional.php on line 4
PHP Fatal error:  require_once(): Failed opening required 'nZEDb_LIBSrarinfo/archiveinfo.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/nZEDb/nzedb/processing/post/ProcessAdditional.php on line 4

**Comment by ruhllatio** [comment]
Hmm, that error makes it seem like nZEDb_LIBS isn't being defined.  You didn't mess with constants.php at all did you?  cd to nZEDb root directory and do a git checkout constants.php to be sure.

**Comment by davidritterhouse** [comment]
No, I would not know what to do in that file.
When I run that git command, it just returns to the prompt, no error or anything.  Let me know and I will test anything you need to help.
thanks

**Comment by ruhllatio** [comment]
What branch are you on?  git branch from the command line and your banch is the one that's highlighted and/or has an asterisk next to it.

**Comment by davidritterhouse** [comment]
* dev

**Comment by davidritterhouse** [comment]
![2015-08-28 08_23_01-mtputty multi-tabbed putty](https://cloud.githubusercontent.com/assets/13871539/9549600/ce161346-4d74-11e5-8c92-be0af5939131.png)

This is what I see in tmux

**Comment by ruhllatio** [comment]
Is your indexer set to use rarinfo instead of unrar in Site Edit?  Do you have rarinfo installed and is the OS path for it set properly?  If you have it set to use rarinfo, do a whereis rarinfo from the command line.  If the response doesn't show an absolutely path to rarinfo, that's your problem.

**Comment by ruhllatio** [comment]
Sorry, I was mistaken.  rarinfo isn't a binary it appears to be a PHP library we added.  You're getting an error on one of the binaries.  I would check all of your paths for mediainfo, avconv, lame, etc. in Site Edit.

**Comment by davidritterhouse** [comment]
I basically copy what I have in path into console and it works:
In site edit:
Rar: /usr/bin/unrar
tmp unrar path:  /var/www/nZEDb/resources/tmp/unrar/
7za path: /usr/bin/7za
mediainfo path:  /usr/bin/mediainfo
ffmpeg:  /usr/local/bin/ffmpeg

If I go into console, I paste: /usr/bin/unrar (for example but others are same way)
and it runs unrar, showing me the options.  

If I type::
which unrar  -> /usr/bin/unrar
which 7za -> /usr/bin/7za
which mediainfo -> /usr/bin/mediainfo
which ffmpeg -> /usr/local/bin/ffmpeg

**Comment by davidritterhouse** [comment]
I do not see a text box for the Lame path in site settings

**Comment by davidritterhouse** [comment]
Extract RAR/ZIP using rarinfo - > No 
If I am reading that right, it will use the above settings.  I did try it both ways too and same issue.

**Comment by davidritterhouse** [comment]
Here is all I see in tmux
![2015-08-28 13_35_32-mtputty multi-tabbed putty](https://cloud.githubusercontent.com/assets/13871539/9552939/bd19b7fe-4d89-11e5-9e6a-29cc68564cd4.png)

**Comment by ruhllatio** [comment]
What about timeout?  Is that path set?

which timeout.  That's the only other thing I can think of off the top of my head.

**Comment by davidritterhouse** [comment]
my path says:  120  ??

**Comment by ruhllatio** [comment]
lol that's it.  Remove it or put in /usr/bin/timeout if you want avconv/ffmpeg/mediainfo threads to time out if they run too long.

**Comment by davidritterhouse** [comment]
lol, thanks.. <facepalm>
