### ISSUE TITLE
"Edit" Release button broke with latest update

### ISSUE THREAD

**Issue by nrk666** [nZEDb/nZEDb#1855]
Branch: Master : 3e82f7d6fa66a179a50dc115432b4573907e7479

Issue: Can no longer "Edit Release" by clicking an indexed NZB to change category manually. 

Reproduce: Check the box for an indexed NZB, click "Edit" button, get error window that says "Edit Release  This content failed to load". 

Problem didn't exist prior to last big update, I was able to re-categorize NZB's using the "Edit" button without a problem. git says I'm up to date, and all pending DB patches were applied. Doesn't seem to be affecting anything else, so probably low priority.

**Comment by ruhllatio** [comment]
Duplicate to Issue #1852

**Comment by ruhllatio** [comment]
As I'm moving through the changes for dev-tv branch, I'm resolving all presented issues in the site code.  Even the ones that don't cause an outright failure.  I'm sure I will have fixed this by the time I'm done.

**Comment by ruhllatio** [comment]
Fixed in commit 82119836763bf6d030009520fcf4062bbda16066.  This isn't dev branch yet, but will be merged with the new TV processing soon.
