### ISSUE TITLE
RSS Quota's

### ISSUE THREAD

**Issue by scottia** [nZEDb/nZEDb#1862]
RSS User's reporting this issue to me when selecting RSS site links.  i can't find where quota's are to reset the users.  Any advice?  I get the same as site admin.

Service Unavailable.
Your maximum api or download limit has been reached for the day.

**Comment by niel** [comment]
Admin => Users => View. Will show the details. You can't change the number of API requests they have made though. Instead, you might want to create a new Role (Admin => Users => User Roles => Add) with a higher limit and move these users to that Role. Alternatively raise the limit on the role they are currently in if you want to do so across the board.
BTW GitHub Issues isn't really for support issues like this (forums are better for that), but for errors/problems with the app.

**Comment by scottia** [comment]
Thank you.  i don't know how I missed that setting and is why I posted,

i apologize and am closing.
