### ISSUE TITLE
Undefined index: apikey

### ISSUE THREAD

**Issue by Fossil01** [nZEDb/nZEDb#1863]
Since my last master pull (yesterday) I keep seeing this in my nginx log:

    PHP message: PHP Notice:  Undefined index: apikey in /home/nzedb/www/pages/api.php on line 64" while reading response header from upstream, client: xxxxxxx, server: nxxxxxx, request: "GET /api?age=5000&t=tvsearch&cat=5040%2C5030 HTTP

Any idea?

**Comment by Fossil01** [comment]
Looks like those requests are made without an apikey in the URL. But can we disable the error this causes somehow? My nginx logs fill up quickly.

**Comment by kevinlekiller** [comment]
The issue stems from this commit changing from exit to echo. It causes undefined behavior like that https://github.com/nZEDb/nZEDb/commit/3f2684d69ae45b16f24b41fa71ded1a2dbfc7ec5#diff-f75bc4b797bddc6e251aa4d19ac24f79R356

**Comment by Fossil01** [comment]
So that means it needs to be fixed by the devs?

**Comment by kevinlekiller** [comment]
Or anyone really. I can't since I'm heading out.

**Comment by Fossil01** [comment]
Ok. I'll wait for the fix :+1:

**Comment by niel** [comment]
Should be fixed in master now.
