### ISSUE TITLE
Just updated to latest master. Unknown column 'currentparts' in 'field list

### ISSUE THREAD

**Issue by BeZazz** [nZEDb/nZEDb#1866]
When patching the DB I receive the error

    Error: CALL tpg_change(); Failed \{1054}
       Unknown column 'currentparts' in 'field list'

Any ideas?

Thanks

**Comment by niel** [comment]
Which patch number?

**Comment by BeZazz** [comment]
I posted in the forums. (About 2 days ago)
http://forums.nzedb.com/index.php?topic=2106.0

Plenty of looks and no replies, so as a last resort I posted here.

**Comment by niel** [comment]
Ahhh, ok. I don't have time to read forums unfortunately. If I did it would suck up all my time and leave none for coding. I'm almost always around in IRC though.

You didn't say which patch number it fails on though. Screen capture of output would help.

**Comment by BeZazz** [comment]
I can imagine. I am a mod at WHT.

![nzedb](https://cloud.githubusercontent.com/assets/5167573/9794114/a89c4014-582c-11e5-8b4d-a2703253e640.png)

**Comment by niel** [comment]
Are you using Tables Per Group?

**Comment by BeZazz** [comment]
Yes I am.

**Comment by niel** [comment]
Can you come to the IRC channel to discus this, would make it a whole lot easier.

**Comment by BeZazz** [comment]
Yep Ok be there in 15
