### ISSUE TITLE
After last pull : PreDB and Process Releases Fails.

### ISSUE THREAD

**Issue by hondnl** [nZEDb/nZEDb#1872]
Hi ,

I did a git pull ( master ) 3 days ago.
The pull  before that was a month ago.
After that I ran /cli/update_db.php . No error occurred.

Since then Process releases hangs and no new preDB entries are written to the database ( znc runs nicely...)
![tmux_predb](https://cloud.githubusercontent.com/assets/14273029/9847796/f7f05a7c-5adb-11e5-9bdf-e8c567d617c2.jpg)
![tmux_main](https://cloud.githubusercontent.com/assets/14273029/9847800/fdc0d846-5adb-11e5-8566-0cf83e788a3c.jpg)

the Parts table is growing , but no new collections/releases are being created.
I tried to restart tmux  and mysql.
No clear errors...
Since I once converted the tables to innoDb , I saw that a couple of tables where converted back to MYISAM.
So I ran the DB converter again.
Nothing changed.

Ubuntu.
Percona DB 5.5
InnoDB 
Table per Group : No

Thanks for all the work you guys put into this amazing script.

**Comment by niel** [comment]
Which branch? Have you carefully read the Changelog/ReleaseNotes as appropriate to the branch?

**Comment by hondnl** [comment]
Hi niel , 
thanks for the reply.
I have pulled the last master branch ( as stated above) 3 days ago, master did not change since then.
The one before I cannot say (version) , but it was a month ago since the last (master) pull..  So you can backlog it from there.
I looked carefully for any manual changes in de changeLog or bug reports before doing the pull.
Nothing extreme since august right ?   Before doing a full clean reinstall  I would like to figure out what is going on .. so this does not happen again :)

**Comment by hondnl** [comment]
Fixed the issue... 
After mocking certain queries I finally found an error.
A strange one :
`SQLSTATE[HY000]: General error: 1665 Cannot execute statement: impossible to write to binary log since BINLOG_FORMAT = STATEMENT and at least one table uses a storage engine limited to row-based logging.`

This error can be fixed by adding
`binlog_format = MIXED`  in `my.cnf`

**Comment by terbonium** [comment]
Hondnl - Why are you running mysql replication? Do you need it?  If so, yes, MIXED would fix that.  If not disabling replication would stop those errors, and reduce the load on your DB.  You can also suppress those errors by setting log_warnings < 2 in my.cnf.

**Comment by hondnl** [comment]
@terbonium  : thanks for the details.. 
This can be closed ...
