### ISSUE TITLE
bulkadd behaving oddly

### ISSUE THREAD

**Issue by mgaulton** [nZEDb/nZEDb#1874]
So i tried to bulkadd groups using latest git pull and using the block below, it adds 2276 groups (40+ pages) instead of just the below. I have other blocks that are doing teh same thing. I ended up with 138k groups at one point. I've dumped the contents of the groups table to try and replicate and get the same result every time. Any suggestions would be helpful. Also, is there a script to just restore hte out of the box groups table?

alt.binaries.0day.stuffz|alt.binaries.anime|alt.binaries.astronomy|alt.binaries.ath|alt.binaries.barbarella|alt.binaries.audio.warez|alt.binaries.b4e|alt.binaries.big|alt.binaries.bloaf|alt.binaries.blu-ray|alt.binaries.boneless|alt.binaries.british.drama|alt.binaries.cartoons.french|alt.binaries.cats|alt.binaries.cd.image.linux|alt.binaries.cd.image|alt.binaries.cd.lossless|alt.binaries.chello|alt.binaries.classic.tv.shows|alt.binaries.comics.dcp|alt.binaries.comp|alt.binaries.console.ps3|alt.binaries.cores|alt.binaries.country.mp3|alt.binaries.dc|alt.binaries.dgma|alt.binaries.divx.french|alt.binaries.documentaries|alt.binaries.documentaries.french|alt.binaries.downunder|alt.binaries.dvd|alt.binaries.dvd.movies|alt.binaries.dvdr|alt.binaries.dvd-r|alt.binaries.e-book.flood|alt.binaries.e-book.technical|alt.binaries.e-book|alt.binaries.ebook|alt.binaries.erotica.divx|alt.binaries.erotica|alt.binaries.etc|alt.binaries.font|alt.binaries.french-tv|alt.binaries.frogs|alt.binaries.ftn|alt.binaries.fz|alt.binaries.games.nintendods|alt.binaries.games|alt.binaries.games.wii|alt.binaries.games.xbox360|alt.binaries.games.xbox|alt.binaries.ghosts|alt.binaries.hdtv|alt.binaries.hdtv.german|alt.binaries.hdtv.x264|alt.binaries.highspeed|alt.binaries.hou|alt.binaries.ijsklontje|alt.binaries.inner-sanctum|alt.binaries.illuminaten|alt.binaries.ipod.videos|alt.binaries.linux.iso|alt.binaries.lou|alt.binaries.mac|alt.binaries.mac.applications|alt.binaries.milo|alt.binaries.misc|alt.binaries.mojo|alt.binaries.mma|alt.binaries.mom|alt.binaries.moovee|alt.binaries.movies.divx|alt.binaries.movies.erotica|alt.binaries.movies.french|alt.binaries.movies|alt.binaries.movies.xvid|alt.binaries.mp3.audiobooks|alt.binaries.mp3.bootlegs|alt.binaries.mp3.full_albums|alt.binaries.mp3|alt.binaries.mpeg.video.music|alt.binaries.multimedia.anime.highspeed|alt.binaries.multimedia.anime.repost|alt.binaries.multimedia.anime|alt.binaries.multimedia.cartoons|alt.binaries.multimedia.classic-films|alt.binaries.multimedia.comedy.british|alt.binaries.multimedia.disney|alt.binaries.multimedia.documentaries|alt.binaries.multimedia.erotica|alt.binaries.multimedia.erotica.amateur|alt.binaries.multimedia.scifi|alt.binaries.multimedia.scifi-and-fantasy|alt.binaries.multimedia.sitcoms|alt.binaries.multimedia.sports|alt.binaries.multimedia|alt.binaries.multimedia.tv|alt.binaries.multimedia.vintage-film|alt.binaries.multimedia.vintage-film.post-1960|alt.binaries.music.flac|alt.binaries.music.opera|alt.binaries.nintendo.ds|alt.binaries.nospam.cheerleaders|alt.binaries.pictures.comics.complete|alt.binaries.pictures.comics.dcp|alt.binaries.pictures.comics.reposts|alt.binaries.pictures.comics.repost|alt.binaries.pro-wrestling|alt.binaries.scary.exe.files|alt.binaries.series.tv.divx.french|alt.binaries.sony.psp|alt.binaries.sound.audiobooks|alt.binaries.sound.mp3|alt.binaries.sounds.1960s.mp3|alt.binaries.sounds.1970s.mp3|alt.binaries.sounds.audiobooks.repost|alt.binaries.sounds.country.mp3|alt.binaries.sounds.flac|alt.binaries.sounds.flac.jazz|alt.binaries.sounds.jpop|alt.binaries.sounds.lossless.1960s|alt.binaries.sounds.lossless.classical|alt.binaries.sounds.lossless.country|alt.binaries.sounds.lossless|alt.binaries.sounds.mp3.1950s|alt.binaries.sounds.mp3.1970s|alt.binaries.sounds.mp3.1980s|alt.binaries.sounds.mp3.1990s|alt.binaries.sounds.mp3.2000s|alt.binaries.sounds.mp3.acoustic|alt.binaries.sounds.mp3.audiobooks|alt.binaries.sounds.mp3.bluegrass|alt.binaries.sounds.mp3.christian|alt.binaries.sounds.mp3.classical|alt.binaries.sounds.mp3.comedy|alt.binaries.sounds.mp3.complete_cd|alt.binaries.sounds.mp3.country|alt.binaries.sounds.mp3.dance|alt.binaries.sounds.mp3.disco|alt.binaries.sounds.mp3.emo|alt.binaries.sounds.mp3.full_albums|alt.binaries.sounds.mp3.heavy-metal|alt.binaries.sounds.mp3.jazz|alt.binaries.sounds.mp3.jazz.vocals|alt.binaries.sounds.mp3.musicals|alt.binaries.sounds.mp3.nospam|alt.binaries.sounds.mp3.opera|alt.binaries.sounds.mp3.progressive-country|alt.binaries.sounds.mp3.rap-hiphop.full-albums|alt.binaries.sounds.mp3.rap-hiphop|alt.binaries.sounds.mp3.rock|alt.binaries.sounds.mp3|alt.binaries.sounds.radio.bbc|alt.binaries.sounds.radio.british|alt.binaries.sounds.whitburn.pop|alt.binaries.tatu|alt.binaries.teevee|alt.binaries.test|alt.binaries.town|alt.binaries.triballs|alt.binaries.tun|alt.binaries.tvseries|alt.binaries.tv|alt.binaries.u-4all|alt.binaries.u4e|alt.binaries.ucc|alt.binaries.ufg|alt.binaries.uzenet|alt.binaries.warez.ibm-pc.0-day|alt.binaries.warez.quebec-hackers|alt.binaries.warez.smartphone|alt.binaries.warez|alt.binaries.warez.uk.mp3|alt.binaries.wii|alt.binaries.wmvhd|alt.binaries.worms|alt.binaries.x264|alt.binaries.x|alt.binaries.multimedia.erotica.anime|alt.binaries.multimedia.erotica.asian|alt.binaries.mp3.audiobooks.scifi-fantasy|alt.binaries.sounds.audiobooks.scifi-fantasy|alt.binaries.mp3.abooks|alt.binaries.town.xxx|alt.binaries.software|alt.binaries.nzbpirates|alt.binaries.town.cine|alt.binaries.usenet-space-cowboys|alt.binaries.warez.ibm-pc.games|alt.binaries.warez.games|alt.binaries.e-book.magazines|alt.binaries.sounds.anime|alt.binaries.pictures.erotica.anime

**Comment by ruhllatio** [comment]
You're not escaping any of your periods.  An un-escaped period is a wildcard.  You need to do a replace on . to \. and then do the

**Comment by mgaulton** [comment]
I had no idea it would wildcard. Thank you.

**Comment by kevinlekiller** [comment]
If it's regex, then you'd need to encase it in parenthesis.

**Comment by mgaulton** [comment]
@kevinlekiller can you give me an example, not sure what you mean?

**Comment by kevinlekiller** [comment]
For example `(alt\.binaries.test|dk.binaer\.test)`

**Comment by mgaulton** [comment]
Got it, that worked. Thanks for your patience.

**Comment by kevinlekiller** [comment]
Np, glad to help.
