### ISSUE TITLE
predb load error when running script

### ISSUE THREAD

**Issue by mgaulton** [nZEDb/nZEDb#1875]
running ' php predb_import_daily_batch.php 0 local true'

Info: Clearing import table
Info: Deleting any records where title <=8 from Temporary Table
Info: Inserting records from temporary table into predb table
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'hash' at row 1' in /srv/www/htdocs/nZEDb/nzedb/db/PreDb.php:120
Stack trace:
#0 /srv/www/htdocs/nZEDb/nzedb/db/PreDb.php(120): PDOStatement->execute()
#1 /srv/www/htdocs/nZEDb/cli/data/predb_import_daily_batch.php(161): nzedb\db\PreDb->executeInsert()
#2 {main}
  thrown in /srv/www/htdocs/nZEDb/nzedb/db/PreDb.php on line 120

**Comment by kevinlekiller** [comment]
Weird, never seen this before, not sure, will have to wait for someone else to reply.

**Comment by hondnl** [comment]
The hashed pre release was longer than 20 bytes ?   What kind of releasename is that !
varbinary(20)  is the current max in the table.

It should ignore it and continue...

**Comment by mgaulton** [comment]
@hondnl it does not, it hard exits.

**Comment by mgaulton** [comment]
@hondnl Tried again, any suggestions. This was following a resetdb.php
php predb_import_daily_batch.php progress local true

Info: Clearing import table
Info: Deleting any records where title <=8 from Temporary Table
Info: Inserting records from temporary table into predb table
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'hash' at row 1' in /srv/www/htdocs/nZEDb/nzedb/db/PreDb.php:120
Stack trace:
#0 /srv/www/htdocs/nZEDb/nzedb/db/PreDb.php(120): PDOStatement->execute()
#1 /srv/www/htdocs/nZEDb/cli/data/predb_import_daily_batch.php(161): nzedb\db\PreDb->executeInsert()
#2 {main}
  thrown in /srv/www/htdocs/nZEDb/nzedb/db/PreDb.php on line 120

**Comment by mgaulton** [comment]
For giggles i did an alter to make it varbinary(50) and it now works. I went big not knowing what the largest size likely was.

**Comment by terbonium** [comment]
Can you select out the biggest row for us and see what happened?  The hashes cannot exceed 20bytes.
Yes, these are huge queries, but will only return a few rows.

select count(*), length(hash) l from predb_hashes group by l;

select pre_id, length(hash) l, hex(hash) h from predb_hashes order by length(hash) desc limit 10;

**Comment by mgaulton** [comment]
First query:
count(*) l
530246 32
265123 40

Second query:

pre_id	l	h
2310	40	31313537336433326166356236636137663363613232646138...
2315	40	37343462303739623063313766363939306263653534383732...
2309	40	37383666336530666266316531346366653435646162626531...
2313	40	30633764323932616137613333313135623932663536306661...
281432	40	63646664653634366665613734663863383131303664333831...
2308	40	37386564616335313364613363666438356362613739656162...
2314	40	36373966306333313535363066366333333832386563326434...
2312	40	64383137363562643061383633646637346162316363646661...
2307	40	33323361383564663935343063363362303438393838633463...
2311	40	61396563633636316630626234313366396333303062666238...

**Comment by terbonium** [comment]
This is from an import?  That's really goofy.  They should only be 16bytes and 20bytes.

Can you do a 

SHOW CREATE TABLE predb
SHOW CREATE TABLE predb_hashes

**Comment by mgaulton** [comment]
CREATE TABLE `predb_hashes` (
 `hash` varbinary(50) NOT NULL DEFAULT '',
 `pre_id` int(11) unsigned NOT NULL DEFAULT '0',
 PRIMARY KEY (`hash`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci

CREATE TABLE `predb` (
 `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
 `title` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
 `nfo` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
 `size` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
 `category` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
 `predate` datetime DEFAULT NULL,
 `source` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
 `requestid` int(10) unsigned NOT NULL DEFAULT '0',
 `group_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'FK to groups',
 `nuked` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Is this pre nuked? 0 no 2 yes 1 un nuked 3 mod nuked',
 `nukereason` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'If this pre is nuked, what is the reason?',
 `files` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'How many files does this pre have ?',
 `filename` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
 `searched` tinyint(1) NOT NULL DEFAULT '0',
 PRIMARY KEY (`id`),
 UNIQUE KEY `ix_predb_title` (`title`),
 KEY `ix_predb_nfo` (`nfo`),
 KEY `ix_predb_predate` (`predate`),
 KEY `ix_predb_source` (`source`),
 KEY `ix_predb_requestid` (`requestid`,`group_id`),
 KEY `ix_predb_filename` (`filename`),
 KEY `ix_predb_searched` (`searched`)
) ENGINE=MyISAM AUTO_INCREMENT=558224 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci

**Comment by SchoolBusDriver** [comment]
On a new install starting the predb_import_daily_batch from 0 also gets the same error as above.

Deleting the predb_hashes table and recreating with varbinary(50) instead varbinary(20) allows it to start working.

**Comment by niel** [comment]
changing to varbinary(50) is not a fix, it will just allow bad data to be inserted into the table and hides the real problem.
To properly debug this, it would help to have examples of data that fails to work correctly so we can ascertain where it comes from.

**Comment by Bart39** [comment]
this has to be something specific to your set up - importing the dailies doesn't cause this issue for anyone else as far as i can tell

**Comment by SchoolBusDriver** [comment]
**Fresh Install in Arch Linux:**
--
* MySQL - 5.6.25-73.0
* PHP - 5.6.13
* nZEDb - Dev Branch (https://github.com/nZEDb/nZEDb/commit/969acbd6bd7f02578d1b6523c0bc65b953af2c9c)

**PHP Error:**
--
````
[27-Sep-2015 07:48:10 America/New_York] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'hash' at row 1' in /var/www/nZEDb/nzedb/db/PreDb.php:120
Stack trace:
#0 /var/www/nZEDb/nzedb/db/PreDb.php(120): PDOStatement->execute()
#1 /var/www/nZEDb/cli/data/predb_import_daily_batch.php(161): nzedb\db\PreDb->executeInsert()
#2 {main}
  thrown in /var/www/nZEDb/nzedb/db/PreDb.php on line 120
````
**predb_progress.txt:**
--

````
YToxOntzOjQ6Imxhc3QiO2k6MDt9
````
[1404152742_predb_dump.csv](https://github.com/SchoolBusDriver/predb/blob/master/1404152742_predb_dump.csv)

**Comment by Bart39** [comment]
`show triggers like 'predb%'`
and paste the output
