### ISSUE TITLE
AF_UNIX when using threaded 

### ISSUE THREAD

**Issue by mgaulton** [nZEDb/nZEDb#1876]
I've recently reinstalled nzedb and running into a familiar issue. OpenSuse 13.2 PHP 5.6.9 (cli)
Wondering if:
1. There is a way to correct this
2. Confirmation that the scripts are running, and working despite the message. since it seems to have assumed a value.

PHP Notice:  Use of undefined constant AF_UNIX - assumed 'AF_UNIX' in /srv/www/htdocs/nZEDb/libs/forkdaemon-php/fork_daemon.php on line 1733
PHP Fatal error:  Call to undefined function socket_create_pair() in /srv/www/htdocs/nZEDb/libs/forkdaemon-php/fork_daemon.php on line 1737

**Comment by kevinlekiller** [comment]
Hi mgaulton, you need to install/enable posix extensions for php5.

**Comment by mgaulton** [comment]
ah posix was the keyword i was missing. Looks like that's the ticket. Thanks agian.

**Comment by mgaulton** [comment]
Interestingly, i installed php5-posix but i'm still getting the messages about AF_unix

**Comment by kevinlekiller** [comment]
Have you enabled it in php.ini ?

**Comment by kevinlekiller** [comment]
You can check with this command: `php -r "var_dump(function_exists('socket_create'), defined('AF_UNIX'));"`

You should get bool(true) 2 times.

**Comment by mgaulton** [comment]
Normally, if i install a package like that, it gets updated from the RPM into the ini. Checking... Your snip gave me false.

**Comment by kevinlekiller** [comment]
pcntl function are disabled in php.ini by default

**Comment by kevinlekiller** [comment]
Here's an image of php.ini, posix extension is commented out (the `;`) which disables it:

https://i.imgur.com/HZATgpa.png

**Comment by kevinlekiller** [comment]
Some distros will also disable the individual pcntl functions in php.ini (on my distro they didn't) - you can search for pcntl.

**Comment by mgaulton** [comment]
opensuse doesn't look like that *sigh* let me play with it a bit.

**Comment by kevinlekiller** [comment]
Alright, you can also add the line, like in my screenshot - without the leading `;`

**Comment by kevinlekiller** [comment]
Can run this to see if it's indeed posix.so:

`find $(php-config --extension-dir) -name posix*`

**Comment by mgaulton** [comment]
opensuse makes a folder conf.d with individual ini files for each extension. The pcntl and posix are enabled there

**Comment by mgaulton** [comment]
server5:/usr/lib64/php5/extensions # find $(php-config --extension-dir) -name posix*
/usr/lib64/php5/extensions/posix.so

**Comment by kevinlekiller** [comment]
Alright, you can add `extenstion=/usr/lib64/php5/extensions/posix.so` to php.ini in the extensions section, should work.

Unless it's already loaded in that conf.d config file.

**Comment by mgaulton** [comment]
Yes, it was already loaded in the config file, hence the confusion now.

**Comment by mgaulton** [comment]
So... with some experimenting and a slow, detailed crawl through all fo the possible modules in my library, it required 3 things but does appear to be working now

php5-pcntl
php5-posix
php5-sockets
