### ISSUE TITLE
parts table increasing fast

### ISSUE THREAD

**Issue by gregster85** [nZEDb/nZEDb#1877]
I'm running the latest dev, using tpg and tmux. On debian wheezy.
Parts retention hours is set to 12.

The c/b/p tables are increasing fast, this stated a couple of weeks ago. I don't know what could be causing this. I have set minimum files and size on all groups.

Two days ago I ran "php5 reset_truncate.php true", but the c/b/p tables are increasing fast again.
Collections 101,916 | Binaries 463,115 | Parts 49,388,327

Is it normal that the collections tables have entries with a date that is older than 12 hours (parts retention is set to 12h).
SELECT subject,totalfiles,fromname,date,dateadded FROM `collections_16` ORDER BY `collections_16`.`date` ASC limit 10;
For example this query above shows data with dates from 2015-09-10 which is from 7 days ago.

**Comment by terbonium** [comment]
Did you remove the old triggers on collections?
From the Changelog
▸   Add: *** MUST RUN *** TPG Script to DROP old collections TRIGGERS after Patch 374 /nzedb/build/_runonce/tpg_delete_triggers_2015-08-14.php

**Comment by gregster85** [comment]
Ouch... guess not... I did this and truncated the tables.
Looking stable again now.
Thanks
