### ISSUE TITLE
Provide an option to download the TV Artwork to the TV Cover Folder instead of the SQL Database.

### ISSUE THREAD

**Issue by SchoolBusDriver** [nZEDb/nZEDb#1880]
Along with [Replacing TVRage (issue 1879)](https://github.com/nZEDb/nZEDb/issues/1879) with [thetvdb.com](http://thetvdb.com/) or [tvmaze.com](http://www.tvmaze.com/)

Provide an option to download the TV Artwork to the TV Cover Folder instead of the SQL Database. Movies Artwork does this now.

**Comment by ruhllatio** [comment]
No longer optional... required as of commit 96bd66dc0f32a4b3defdaff1fc252c73cc3da735 :D
