### ISSUE TITLE
API returns errors after PR #1878

### ISSUE THREAD

**Issue by Fossil01** [nZEDb/nZEDb#1881]
After using Darius' api.php from (PR #1878) on the Master branch I am presented with this error when opening the following URL: /api?t=search&q=Entourage
````
    error on line 2 at column 1: Extra content at the end of the document
    Below is a rendering of the page up to the first error.
````
The rest of the page is blank.

Whenever I try to output JSON (/api?t=search&q=Entourage&o=json) I get this error:

````
<br />
<b>Warning</b>:  implode(): Invalid arguments passed in <b>/home/nzedb/nzedb/Releases.php</b> on line <b>1004</b><br />
[]
````

**Comment by DariusIII** [comment]
I have tested the fix and i had no such issues. That line in Releases comes from search and is ($hasNfo != 0 ? ' AND r.nfostatus = 1 ' : ''). The fix just converts possible ASCII into UTF-8, nothing else.

**Comment by ruhllatio** [comment]
@Fossil01 is this still an issue?

**Comment by Fossil01** [comment]
No. Closed.
