### ISSUE TITLE
NZB Import bug sets date incorrectly

### ISSUE THREAD

**Issue by ghost** [nZEDb/nZEDb#1886]
When doing an import of an nzb via tmux, it adds the nzb correctly except the date is about 46 years off.  See the screenshot.
![nzbimport](https://cloud.githubusercontent.com/assets/13871539/10209908/b713fa9c-67ae-11e5-9882-d24874823964.png)

**Comment by niel** [comment]
Which branch?

**Comment by davidritterhouse** [comment]
The Dev branch, sorry about that.

**Comment by niel** [comment]
OK, I have a quick change that may or may not help, I'll push it shortly. Please let me know if it helps.

**Comment by davidritterhouse** [comment]
Thanks, I can test it then and let you know.

**Comment by davidritterhouse** [comment]
I just saw you did an update.  I did a git update and noticed the revised nzbimport file, so ran a test but same issue.  Showing 45.6 days
I looked at phpmyadmin, will this help? 
![db_view](https://cloud.githubusercontent.com/assets/13871539/10226414/3d640142-6835-11e5-81e8-1cb2fd733629.png)

**Comment by niel** [comment]
OK thanks. I'll have to dig deeper into the code. Not sure if this is a problem in the Import or just how the info is displayed after.

**Comment by davidritterhouse** [comment]
The main issue, is after the import, the main tmux release stuff will delete it since I have retention set to  1500 days.

**Comment by davidritterhouse** [comment]
I think I fixed it.  I edited like this:
//                              $postDate = date("Y-m-d H:i:s", (int)$file->attributes()->date);
                              $postDate = date("Y-m-d H:i:s");

And now the post date is today which is fine for me.

**Comment by Bart39** [comment]
So it's a problem with the nzb itself then

**Comment by davidritterhouse** [comment]
I am not sure sure as I have tried many different ones from different sources, like binsearch and nzbindex.

**Comment by ruhllatio** [comment]
I would var_dump($file->attributes()->date) without the INT type cast to be sure.  If it's a string being cast as an int, it needs to be strtotime()'d first and then date() can handle it properly.
