### ISSUE TITLE
TV Series Names Wrong (wrong language?)

### ISSUE THREAD

**Issue by Enverex** [nZEDb/nZEDb#1887]
I've noticed two series now that people weren't finding releases for that I knew were there. Turns out this was happening because the series names were wrong which in turn meant that post-processing wasn't assigning any releases to them.

Two examples that I've encountered so far were:

"Game of Thrones" was named "Le Trone de fer"
"Rick and Morty" was named "Santa postet Rick and Morty"

All the other information for these TV-Rage entries in the tvrage_titles table was correct. The synopsis was there and in the right language, genre, episode dates, times, etc were all fine, country was US. Essentially everything else looked normal. Just the "releasetitle" field was wrong.

Unfortunately I can't track down exactly when this happened as I don't know when these Rage entries appeared in the database.

**Comment by ruhllatio** [comment]
Pretty sure we found why this happens.  From the beginning, TvRage processing was set to insert the cleaned name of the release as the title, not the matched title from TvRage.

**Comment by ruhllatio** [comment]
After processing thousands of shows, I've found no such issue with the new method.  We are not inserting cleaned release names nor are we inserting show names that don't exist in a third-party resource.  While I'm sure the process isn't perfect, we have maintained referential integrity thus far in our tests.  This should not happen again so I'm marking it as fixed.
