### ISSUE TITLE
TV processing is stuck.. 

### ISSUE THREAD

**Issue by Atmos01** [nZEDb/nZEDb#1909]
Last TV post is 13 hours ago.. Seems like my install is delaying all now..

![image](https://cloud.githubusercontent.com/assets/13801996/10418958/14b3c5b6-7069-11e5-8ac7-b9a7c875b409.png)

Got 65 in process for TV.. When i manually process its doing nothing..  i did Notice that Tvrage is down.. Could this be the reason?

**Comment by DariusIII** [comment]
TvRage is down since beggining of september. Processing tv is dead since then. Only TV that is processed is the one you had data in your tvrage table.

**Comment by Atmos01** [comment]
ahhh.. that explains it.. so what kind of solution is there for TV?

**Comment by DariusIII** [comment]
Devs are working on a solution, just be patient.

**Comment by Atmos01** [comment]
Ok Thanks!
