### ISSUE TITLE
Patch 383 update_db error

### ISSUE THREAD

**Issue by moloquin** [nZEDb/nZEDb#1913]
Updated to latest dev and getting this error when trying to update the DB.

php cli/update_db.php true
Db updater starting ...
Looking for unprocessed patches...
Processing patch file: /var/www/html/nZEDb/resources/db/patches/mysql/0385~release_comments.sql
Info: COMMENT: This patch will remove column and index added by patch 383
Info: COMMENT: Drop the text_hash column
Error: ALTER TABLE release_comments DROP text_hash; Failed \{1062}
	Duplicate entry '0' for key 'ix_release_comments_hash_releaseid'

**Comment by Wally73** [comment]
fix is just merged so try to pull again

**Comment by moloquin** [comment]
That's got it.  Thanks!
