### ISSUE TITLE
Error in post AEBN.php

### ISSUE THREAD

**Issue by csmarauder** [nZEDb/nZEDb#1914]
This is on the DEV branch. I have another on main that works fine.
Sometimes in will freeze the window in TMUX and other times it will 
keep running.

Looking up: Young And Natural
Fetching XXX info from: Adult Entertainment Broadcast Network
PHP Notice:  Undefined index: genres in /dump/nzedbdev/nzedb/AEBN.php on line 164
PHP Warning:  array_unique() expects parameter 1 to be array, null given in /dump/nzedbdev/nzedb/AEBN.php on line 164
PHP Warning:  array_unique() expects parameter 1 to be array, null given in /dump/nzedbdev/nzedb/AEBN.php on line 164
Added/updated XXX movie: Young And Natural

**Comment by rainje** [comment]
Same issue in current master.

Can freeze "looking up" and these errors line 164.

**Comment by Bart39** [comment]
the cover issue was fixed in dev yesterday #1918

**Comment by DariusIII** [comment]
This is different issue. Covers are not pulled from AEBN, they changed the page so pulling genres data and covers from site fails.

**Comment by rainje** [comment]
Covers aren't showing in /xxx nor in details.

**Comment by DariusIII** [comment]
But you get the NoCover image, no?

**Comment by rainje** [comment]
Yes, sorry.

**Comment by taskym** [comment]
i'll look into this :)

**Comment by scottia** [comment]
Resolved #1908 as well...
