### ISSUE TITLE
nzedb will not start after update

### ISSUE THREAD

**Issue by raysv** [nZEDb/nZEDb#1917]
Hi, 
Hadn't updated for several months now and did a git pull (MASTER), after the gitpull when i tried to run the update_db script, it dosn't seem to do anything, just jumps back to the promt.

When trying to start my screens i get this:

PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Unable to load configuration file '/var/www/nZEDb/nzedb/config/config.php'. Make sure it has been created and contains correct settings.' in /var/www/nZEDb/nzedb/config/Configure.php:64
Stack trace:
#0 /var/www/nZEDb/nzedb/config/Configure.php(51): nzedb\config\Configure->loadSettings('config', true)
#1 /var/www/nZEDb/nzedb/config/Configure.php(44): nzedb\config\Configure->loadEnvironment('indexer')
#2 /var/www/nZEDb/indexer.php(27): nzedb\config\Configure->__construct('indexer')
#3 /var/www/nZEDb/misc/update/nix/multiprocessing/.do_not_run/require.php(3): require_once('/var/www/nZEDb/...')
#4 /var/www/nZEDb/misc/update/nix/multiprocessing/binaries.php(6): require('/var/www/nZEDb/...')
#5 {main}
  thrown in /var/www/nZEDb/nzedb/config/Configure.php on line 64
PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Unable to load configuration file '/var/www/nZEDb/nzedb/config/config.php'. Make sure it has been created and contains correct settings.' in /var/www/nZEDb/nzedb/config/Configure.php:64
Stack trace:
#0 /var/www/nZEDb/nzedb/config/Configure.php(51): nzedb\config\Configure->loadSettings('config', true)
#1 /var/www/nZEDb/nzedb/config/Configure.php(44): nzedb\config\Configure->loadEnvironment('indexer')
#2 /var/www/nZEDb/indexer.php(27): nzedb\config\Configure->__construct('indexer')
#3 /var/www/nZEDb/misc/update/nix/multiprocessing/.do_not_run/require.php(3): require_once('/var/www/nZEDb/...')
#4 /var/www/nZEDb/misc/update/nix/multiprocessing/backfill.php(4): require('/var/www/nZEDb/...')
#5 {main}
  thrown in /var/www/nZEDb/nzedb/config/Configure.php on line 64
PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Unable to load configuration file '/var/www/nZEDb/nzedb/config/config.php'. Make sure it has been created and contains correct settings.' in /var/www/nZEDb/nzedb/config/Configure.php:64
Stack trace:
#0 /var/www/nZEDb/nzedb/config/Configure.php(51): nzedb\config\Configure->loadSettings('config', true)
#1 /var/www/nZEDb/nzedb/config/Configure.php(44): nzedb\config\Configure->loadEnvironment('indexer')
#2 /var/www/nZEDb/indexer.php(27): nzedb\config\Configure->__construct('indexer')
#3 /var/www/nZEDb/misc/update/nix/tmux/bin/showsleep.php(3): require_once('/var/www/nZEDb/...')
#4 {main}
  thrown in /var/www/nZEDb/nzedb/config/Configure.php on line 64
Total Running Time: 0 minutes and 1 seconds.

Any suggestions on how to fix this?

**Comment by Wally73** [comment]
pretty sure you haven't read the release notes and the changelog.

**Comment by raysv** [comment]
Wally your correct about the release notes, the changelog i did look over however, but probably did miss something. 

Anyway kevin sorted it out on IRC for me so i can close this :) thanks
