### ISSUE TITLE
No covers shown on XXX /details pages

### ISSUE THREAD

**Issue by Fossil01** [nZEDb/nZEDb#1918]
Covers are shown on the /xxx page but not when you open a single release.

Master branch.

**Comment by Fossil01** [comment]
This is not a request or enhancement. This worked for ages and stopped working somewhere in August/September after pulling the latest master.

**Comment by Bart39** [comment]
which theme ?

**Comment by Fossil01** [comment]
All of them including my own. So it's not a theme problem, probably the two if statements are failing in viewnzb.tpl.

**Comment by Wally73** [comment]
I notice the same 'error' in alpha theme (i don't think its a big issue but
ok ;) )

**Comment by Fossil01** [comment]
Fixed by b132c83a1b96c4afa0e72465e800206f4813db65
