### ISSUE TITLE
0313~collections.sql issue

### ISSUE THREAD

**Issue by HarleyCarter1234** [nZEDb/nZEDb#1921]
I've just tried to update from a very old version of nZEDb and had issues with this database update script

it was coming up and telling me that tname was not declared in 0313~collections.sql

i reverted just that 0313~collections.sql file to it's previous state as I noticed it was edited a few weeks ago and then the database updates ran through fine so i am now completely up to date

Looks like an issue with the new version of that file. I was not running my in tpg mode

**Comment by ruhllatio** [comment]
Archer asked that I fixed this in dev.  @niel didn't you intend to cherry pick this over to master?

**Comment by niel** [comment]
Yes I did intend to, and now it is ;-)

**Comment by HarleyCarter1234** [comment]
Good stuff, thanks guys

That should save someone else from the messing around I ended up doing ☺
