### ISSUE TITLE
userseries index fail

### ISSUE THREAD

**Issue by scottia** [nZEDb/nZEDb#1923]
Error with this patch and can't find the commit.  its the most recent dev-tv merge to dev :+1:

Processing patch file: /var/www/nZEDb/resources/db/patches/mysql/0391~user_series.sql
Info: COMMENT: This patch will make the necessary changes to the user_series
Info: COMMENT: table to support the new videos implementation
Info: COMMENT: At this time, we're not sure if we can preserve the users shows
Info: COMMENT: data as the tvrage data is largely useless due to the title insert bug
Info: COMMENT: Truncate for now
SUCCESS: TRUNCATE TABLE user_series;
Info: COMMENT: Change rageid column to new videos_id
Error: ALTER TABLE user_series
  DROP INDEX ix_userseries_userid,
  CHANGE COLUMN rageid videos_id INT(16) NOT NULL COMMENT 'FK to videos.id',
  ADD INDEX ix_userseries_videos_id (user_id, videos_id); Failed \{1034}
	Incorrect key file for table 'user_series'; try to repair it

**Comment by DariusIII** [comment]
Your user_series table is most likely corrupt. Try to repair it first.

**Comment by scottia** [comment]
It wouldn't repair as Innodb, so I changed it to MyIsam.  That allowed the patch.  ? is, why can't for format be innodb?  Is there a list of preferred tables that require MyIsam.  Should I leave user_series as MyIsam?

Thanks for your guidance.

**Comment by DariusIII** [comment]
No, the format can be innodb, but repairs on innodb cannot be done so simply as on myisam. By changing to myisam repair did the job.

**Comment by scottia** [comment]
yes closing.  thanks again

**Comment by ruhllatio** [comment]
To 'repair' an InnoDB table, you need to optimize it.  REPAIR TABLE doesn't apply.  It will recreate the table rebuilding all indexes during an optimize.

**Comment by scottia** [comment]
I did optimize prior to submitting an issue.  Didn't work. Same error

**Comment by DariusIII** [comment]
Well, https://www.percona.com/blog/2008/07/04/recovering-innodb-table-corruption/

**Comment by Fossil01** [comment]
Had the same issue on latest master. My table was perfectly fine.

**Comment by Bart39** [comment]
re-opening - this is an issue for some people on inno

**Comment by ruhllatio** [comment]
Maybe split the alter up into two separate queries?  Or does it just not like creating a composite index over those two columns for some strange reason?

**Comment by josh4trunks** [comment]
hitting this as well on dinnodb

**Comment by Bart39** [comment]
@ ruhllatio - i ran it manually via phpmyadmin and it didn't complain - will do some testing

**Comment by Fossil01** [comment]
I ran it manually and it did complain. So I did the steps manually in Sequel Pro (mac app) which worked.

**Comment by Bart39** [comment]
patch 391 against dynamic inno:
```php
Db updater starting ...
Looking for unprocessed patches...
Processing patch file: /var/www/nZEDb/resources/db/patches/mysql/0391~user_series.sql
Info: COMMENT: This patch will make the necessary changes to the user_series
Info: COMMENT: table to support the new videos implementation
Info: COMMENT: At this time, we're not sure if we can preserve the users shows
Info: COMMENT: data as the tvrage data is largely useless due to the title insert bug
Info: COMMENT: Truncate for now
SUCCESS: TRUNCATE TABLE user_series;
Info: COMMENT: Change rageid column to new videos_id
SUCCESS: ALTER TABLE user_series
  DROP INDEX ix_userseries_userid,
  CHANGE COLUMN rageid videos_id INT(16) NOT NULL COMMENT 'FK to videos.id',
  ADD INDEX ix_userseries_videos_id (user_id, videos_id);
Info: 1 patch(es) applied.
```

**Comment by Fossil01** [comment]
Weird. But maybe still re-write the query to drop the table and re-create it? More foolproof as it's being truncated anyway.

**Comment by josh4trunks** [comment]
works for me now, thanks!
