### ISSUE TITLE
Unable to populate the sphinx release table

### ISSUE THREAD

**Issue by richierichman** [nZEDb/nZEDb#1929]
Hi I'm on the dev branch and I was trying to repopulate the release_rt table but it doesn't seem to add any releases to the search table. I'm on the latest dev, running Mariadb 10.1.8 with Sphinxsearch 2.2.9 on windows but with nZEDb on ubuntu 14.04. I have had it working successfully in the past but was getting an issue with running the removecrap scr releases and I wanted to re-create the index and try again but am running into this issue. I don't get any error when I run php /var/www/nZEDb/misc/sphinxsearch/populate_rt_indexes.php releases_rt and it looks like it is doing its thing but no releases are populated. Can anyone point me in the right location of what I might be missing?

Thanks in advance. Sorry if this is in the wrong area and needs to be in the forum I will raise it there. Thanks again.

Regards
Richie

**Comment by ruhllatio** [comment]
How do you know that no releases are populating?

**Comment by richierichman** [comment]
Because when I do a search there is no results and also when I run the populate_rt_indexes.php it has no progress of it populating with the releases like it used to.

**Comment by richierichman** [comment]
Also when I check my searchd.log file I have a lot of these errors:
WARNING: failed to receive MySQL request body (client=xxx.xxx.xxx.xxx:56337(23999), exp=0, error='WSA error 0')
Not sure if it is related.

**Comment by ruhllatio** [comment]
I only asked because with the new setup you can't pull data from SphinxQL, it only populates the FT indexes and doesn't store the original data per se.

Are you sure your Sphinx configuration in nzedb/config/settings.php is correct?

**Comment by richierichman** [comment]
It has been working all this time. I wanted to update Sphinx to the latest version and then re create the index but it looks like its not working. I have checked my settings.php file and nothing has changed in it from when it used to work.

**Comment by ruhllatio** [comment]
Okay.  Did you rebuild the releases_se table using create_se_tables?

**Comment by richierichman** [comment]
Yes I did that first. Then did the populate_rt_indexes but no luck. It looks like it is trying to populate but I get no out put like I used to when Sphinx was first implemented.

**Comment by ruhllatio** [comment]
You should see ...................10000.....................20000.  This doesn't happen?

**Comment by richierichman** [comment]
No I used to get that before but I am not getting that now. Which is why I think something is broken.

**Comment by ruhllatio** [comment]
Sounds like the case.  It does take time initially to build the list of releases... especially if your database is particularly large.  So, what DOES it do?  Just sits there or does the script exit out?

**Comment by richierichman** [comment]
it sits there for a about a minute and the it back to the prompt. But I do remember it used to take a little while to do the update now not long and no progress indication. I have done a reset/truncate on my database, plus also did a check and optimize but still no luck.

**Comment by ruhllatio** [comment]
So you reset/truncated the whole database or just the groups?  When it is just 'sitting there' for a minute, it is querying the MySQL database for the releases to insert.  If it fails after that, there is something up with its connection to Sphinx.  Can you check the error logs?

**Comment by richierichman** [comment]
The Sphinx log has a lot of these errors:
WARNING: failed to receive MySQL request body (client="ipaddress removed":57427(592), exp=0, error='WSA error 0')

**Comment by richierichman** [comment]
I turned on logging and I have now noticed this error popping up:
Error: SQLSTATE[HY000]: General error: 1430 There was a problem processing the query on the foreign data source. Data source error: bad searchd response length (length=775433577)

**Comment by ruhllatio** [comment]
Yeah yeah, some kind of encoding issue I think.  @kevinlekiller You remember this issue a while back?  Didn't we have to set some parameter within PDO?

**Comment by richierichman** [comment]
Was this something that just changed as I did have it working without any issues before.

**Comment by Bart39** [comment]
how long ago did it last work ? there were some changes a couple of months ago - you might need to recopy the sphinx.conf over again as that was changed

**Comment by richierichman** [comment]
Yes I did that and it was working after as I was able to search. I changed Sphinx versions yesterday to 2.2.10 and tried to recreate the index and re-populate it and have noticed that it is not working.

**Comment by richierichman** [comment]
I even re-ran the create table php after it was noted that there was an issue with MariaDB and it was working.

**Comment by richierichman** [comment]
I have tried going back to the version of Sphinx that was working but it seems to still be broken.

**Comment by richierichman** [comment]
I seem to be getting this error now. 
.Debug: [29/Oct/2015 14:31] [NOTICE] [0.48,0.31,0.20] [00H:05M:29S] [MEM:~~~1GB] [USR: 00H:02M:46S SYS: 00H:00M:25S FAULTS: 0 SWAPS: 0] [PID:671] [nzedb\db\DB.queryExec] [SQLSTATE[42000]: Syntax error or access violation: 1064 unknown column: 'filename']

I noticed that the release_se table did not have the filename row. I created the release_se table using sql code. But I still seem to be getting this error.

**Comment by ruhllatio** [comment]
Let me check on that.  So for sure your releases_se table has no filename column?

**Comment by richierichman** [comment]
I will drop the release_se table and run it again with the script and will post back.

**Comment by richierichman** [comment]
OK the  create_se_tables.php  is not creating the table releases_se table. Is there a way to see if the script is giving an error anyway to turn on logging n the php file to see what its doing?

**Comment by Bart39** [comment]
just turn on php_errors and see if it shows anything

**Comment by richierichman** [comment]
OK looks like I had some kind of firewall / sphinx / madriadb issue. I re-installed Mariadb (10.1.8) and then got the version of Spinx (2.2.9) that works (again). Re created my service for sphinx and made sure the windows firewall was allowing 9306 & 9312 and MYSQL through and then ran the create_release_se once again and this time it all worked and I was able to populate the releases_se table. I now have search working once more. Not sure what the actual issue was as I did do these steps before except for the MariaDB part as that was an upgrade from 10.0.21 to 10.1.8. But I have it working once more. Thank you all for your help in trying to diagnose the issue and thanks for your continued great work.
Richie.

**Comment by stevenmcastano** [comment]
I seem to be having the same issue now... but it's not being resolved. I do have items in the releases_rt table, there's 3G in the sphinx data table, but none of the searches from the web front end work.

**Comment by niel** [comment]
@stevenmcastano, if your problem is not resolved by the same steps as @richierichman's, then it is a different issue. Please create your own issue and supply any relevant details there.

**Comment by ruhllatio** [comment]
Already fixed him up.  He used the wrong port when creating the releases_se table.  Kinda wish we could lock these.

**Comment by niel** [comment]
You mean like that ;-)
