### ISSUE TITLE
Issue with Sickbeard after latest dev branch

### ISSUE THREAD

**Issue by dilbaggins** [nZEDb/nZEDb#1934]
from sickbeard seeing this:

No valid, unique response node was found in the API response.  i see the release for instance in TV HD category.

**Comment by dilbaggins** [comment]
2015-11-01 00:36:00 SEARCHQUEUE-MANUAL-SEARCH :: No valid, unique response node was found in the API response
2015-11-01 00:36:00 SEARCHQUEUE-MANUAL-SEARCH :: No valid, unique response node was found in the API response

**Comment by Wally73** [comment]
i'm on latest dev and I don't see any api issues (but ok i use sickrage not sickbeard) 

2015-11-01 09:48:09 INFO     SEARCHQUEUE-DAILY-SEARCH :: [Newz2WHM] :: Skipping NCIS.S13E01. ... etc  (and new2 is my nzedb install)

**Comment by dilbaggins** [comment]
great. your answer is useless to the shire :) 

try ash vs evil dead for instance via sickbeard.  and let me know :)

**Comment by kevinlekiller** [comment]
You tried browsing to the URL in the log?

**Comment by Wally73** [comment]
http://url/api?t=tvsearch&cat=5030,5040&extended=1&apikey=yourapikey&offset=0&limit=100 

does that give a normal xml output??

**Comment by dilbaggins** [comment]
i am getting a return of only 10 releases vs the 100 specified Wally:

American.Crime.S01E06.Episode.Six.1080p.WEB-DL.DD5.1.H.264-KiNGS
American.Crime.S01E06.Episode.Six.1080p.WEB-DL.DD5.1.H.264-KiNGS

Minority.Report.S01E03.720p.HDTV.x264-FLEET English
Minority.Report.S01E03.720p.HDTV.x264-FLEET English

The.Block.NZ.S04E19.720p.HDTV.x264-FiHTV 
The.Block.NZ.S04E19.720p.HDTV.x264-FiHTV 

Doctor.Who.2005.S09E07.The.Zygon.Invasion.720p.HDTV.x265-HEVC 
Doctor.Who.2005.S09E07.The.Zygon.Invasion.720p.HDTV.x265-HEVC 

NCIS.New.Orleans.S02E06.1080p.WEB-DL.DD5.1.H.264-VietHDWally731185 English
NCIS.New.Orleans.S02E06.1080p.WEB-DL.DD5.1.H.264-VietHDWally731185 English

Thunderbirds.Are.Go.S01E14.Falling.Skies.1080p.WEB-DL.AAC2.0.H.264-YFNWally731184 English
Thunderbirds.Are.Go.S01E14.Falling.Skies.1080p.WEB-DL.AAC2.0.H.264-YFNWally731184 English

Alaska Monsters S02E07 720p HDTV x264
Alaska Monsters S02E07 720p HDTV x264

Doctor Who 2005.S09E07.720p HDTV x264
Doctor Who 2005.S09E07.720p HDTV x264

Hawaii.Five-0.S06E04.Best.Laid.Plans.1080p.WEB-DL.DD5.1.H.264-KiNGS English
Hawaii.Five-0.S06E04.Best.Laid.Plans.1080p.WEB-DL.DD5.1.H.264-KiNGS English

Sleepy.Hollow.S03E05.Dead.Men.Tell.No.Tales.1080p.WEB-DL.DD5.1.H.264-Juggalotus English
Sleepy.Hollow.S03E05.Dead.Men.Tell.No.Tales.1080p.WEB-DL.DD5.1.H.264-Juggalotus English





thanks Kev!

**Comment by Wally73** [comment]
Since you have output it is imo a Sickbeard issue not an nZEDb issue

**Comment by kevinlekiller** [comment]
The output looks weird, it's not XML for one

**Comment by dilbaggins** [comment]
my output in API for movie search with api also only responds with 10 responses vs the 100 in the query.

Kev-  it responds with xml (didnt want to post my url info etc) SHIRE PARANOIA!

**Comment by kevinlekiller** [comment]
Alright, do you get 10 @Wally73?

**Comment by Wally73** [comment]
no i have a lot more as 10 will pm you my link on irc

**Comment by kevinlekiller** [comment]
Alright, not sure then. Do you see any errors in mysql logs or anything @dilbaggins

**Comment by dilbaggins** [comment]
@Wally73 what are you using to browse the api feed.  just chrome.. i want to compare apples to apples.

**Comment by dilbaggins** [comment]
no errors in the logs that i see @kevinlekiller .  will keep looking.

**Comment by Wally73** [comment]
I use Chrome and Firefox @dilbaggins

**Comment by ruhllatio** [comment]
@dilbaggins - http://url/api?t=tvsearch or t=movie.  Nothing else.  Do you get more than 10 responses?

**Comment by dilbaggins** [comment]
@ruhllatio yeah still get 10:  https://SHIRESERVER.com/api?t=tvsearch&apikey=MYKEY is whatimusing  tried t=movie as well.

**Comment by ruhllatio** [comment]
Go to /nzedb/Releases.php and go down to Line 1009.  It should be blank.  Like this: https://github.com/nZEDb/nZEDb/blob/dev/nzedb/Releases.php#L1009

In that line put var_dump($sql); and save it.  Then go to the URL again.  It should give you an invalid XML response.  Do a page source view and there should be the entire SQL query in the source at the top.  Copy and paste it here.

**Comment by dilbaggins** [comment]
string(1027) "SELECT r.*,
				v.title, v.countries_id, v.started, v.tvdb, v.trakt,
					v.imdb, v.tmdb, v.tvmaze, v.tvrage, v.source,
				tvi.summary, tvi.publisher, tvi.image,
				tve.series, tve.episode, tve.se_complete, tve.title, tve.firstaired, tve.summary,
				CONCAT(cp.title, ' > ', c.title) AS category_name,
				1000,1010 AS category_ids,
				groups.name AS group_name,
				rn.id AS nfoid,
				re.releaseid AS reid
			FROM releases r
			INNER JOIN videos v ON r.videos_id = v.id
			INNER JOIN tv_info tvi ON v.id = tvi.videos_id
			INNER JOIN tv_episodes tve ON r.tv_episodes_id = tve.id
			INNER JOIN category c ON c.id = r.categoryid
			INNER JOIN groups ON groups.id = r.group_id
			LEFT OUTER JOIN video_data re ON re.releaseid = r.id
			LEFT OUTER JOIN release_nfos rn ON rn.releaseid = r.id
			INNER JOIN category cp ON cp.id = c.parentid
			
			WHERE r.categoryid BETWEEN 5000 AND 5999
			AND v.type = 0
			AND r.nzbstatus = 1
			AND r.passwordstatus = 0
			AND (1=1)
			     
			ORDER BY postdate DESC
			LIMIT 100 OFFSET 0"

**Comment by ruhllatio** [comment]
Query looks good albeit formatted strange on GH.  You can remove that var_dump now.  Then run the query in mysql (everything between the double quotes is good) and see how many rows it returns.

**Comment by dilbaggins** [comment]
seeing a lot more 

 Showing rows 0 - 99 (100 total, Query took 0.0087 sec)

**Comment by dilbaggins** [comment]
something else to note (using the alpha theme) and under "new releases"  no TV listings are showing.   think its sphinx related? :)

**Comment by dilbaggins** [comment]
ok latest patch for mariaDB seems to have resolved it.  seeing the raw XML feed also shows more results.   seems good for now. free to close.  thanks all for the help!
