### ISSUE TITLE
BUG: after adding shows to myshows, URL is wrong

### ISSUE THREAD

**Issue by bobtongue** [nZEDb/nZEDb#1937]
Pulled from master this morning. When trying to add shows to my shows, they add correctly, but after adding the show, the url that redirects to the series page is incorrect. It trys to open http://news.mysite.com/www/www/www/series/230 instead of http://news.mysite.com/www/series/230.
It looks as if the add works, it shows up in my shows, but the redirect always has the 2 extra www/.
I am running alpha theme in case that matters

**Comment by ruhllatio** [comment]
There shouldn't be a www there at all.  It should be hosturl/series/230

**Comment by bobtongue** [comment]
OK, well, The root of my site is news.mysite.com. I have a rewrite rule to direct to news.mysite.com/www.
The rule is in .htaccess and is as follows.
RewriteCond %{HTTP_HOST} ^(news.)?bobtongue.com$
RewriteRule ^(/)?$ www [L]
Do you see a problem there? That is the only place there would be an issue, which BTW was never an issue before the latest pull.

**Comment by bobtongue** [comment]
At this point, I am wondering if I even need the redirect or if it would be ok to use www as site root. I forget why I did it that way in the first place. I think it had something to do with covers or something like that. I just don;t know.

**Comment by bobtongue** [comment]
OK, I removed the rewrite rule, pointed site root to the www directory. I was right, the issue was covers. They wouldn't show up. created symbolic link to resources/covers and all seems well. I will ride it this way for a while and see if anything else is broken. Thanks for the response. The redirect is now working correctly. If you could look at that rewrite rule and tell me if there is anything wrong with it, I would be very appreciative. It's not my strongest subject and it would help me greatly to learn.

**Comment by ruhllatio** [comment]
That was an early  issue when covers were moved.  We had to add the alias to Apache.  I think the install guides were updated to reflect for NGINX as well but I'm not sure.  In any event, you're now in spec with everyone else.  It probably became a problem because somewhere I switched smarty.const.www.top with WWW_ROOT or something.

**Comment by bobtongue** [comment]
Thanks for the explanation.
