### ISSUE TITLE
Running query to display tv series taking too long

### ISSUE THREAD

**Issue by bobtongue** [nZEDb/nZEDb#1942]
When browsing tvseries, the query that runs is taking well over 600 seconds to complete and the browser times out before completion. Before yesterday's pull, I don't remember it ever taking anywhere near that long to complete. The query listed in mytop is:
SELECT v.* FROM (SELECT v.*, tve.firstaired AS prevdate, tve.title AS previnfo, tvi.publisher, us.id AS userseriesid FROM videos v INNER JOIN tv_info tvi ON v.id = tvi.videos_id INNER JOIN tv_episodes tve ON v.id = tve.videos_id LEFT OUTER JOIN user_series us ON v.id = us.videos_id AND us.user_id = 1 WHERE 1=1 AND tve.firstaired <= NOW() AND v.title REGEXP '^[0-9]' ORDER BY tve.firstaired DESC) v STRAIGHT_JOIN releases r ON r.videos_id = v.id WHERE r.categoryid BETWEEN 5000 AND 5999 GROUP BY v.id ORDER BY v.title ASC

Should this query be taking that long to complete?

**Comment by ruhllatio** [comment]
This was fixed in Dev.  TV Series is almost instantaneous now.

**Comment by ruhllatio** [comment]
https://github.com/nZEDb/nZEDb/blob/dev/nzedb/Videos.php#L107 Copy that whole function over the one in the same file in your local install.

**Comment by bobtongue** [comment]
WOW! Worked great.

Thanks
