### ISSUE TITLE
Sonarr with latest pull

### ISSUE THREAD

**Issue by malanden** [nZEDb/nZEDb#1943]
Since updating to the current master for this month, RSS sync doesnt work anymore with link 
sitename.com/api?t=tvsearch&cat=5040&extended=1&apikey=apikeyhere&offset=0&limit=100

All I get is the following

http://pastebin.com/NT0TPTGF

**Comment by ruhllatio** [comment]
Well, I hope the changes I made to accommodate RSS/API went through.  My Sonarr reviews 100 releases everytime I sync RSS with Dev branch.  Let me look.

**Comment by malanden** [comment]
link didn't work
I stopped tmux.
I just updated from mariadb 5.5 to 10.1, based on comments i saw in a closed issue on something else with search results
rebooted
link still didn't work
started tmux again,
link is working now.

I did this, no clue what actually solved the problem.
