### ISSUE TITLE
TV Processing problem

### ISSUE THREAD

**Issue by bobtongue** [nZEDb/nZEDb#1944]
When I pulled the latest master I had about 1600 tv releases waiting for processing. After the pull all of the tv releases were reset for processing. The processing has been going smoothly, but has just "finished" leaving 111,378 releases left unprocessed. The helpful sql queries for displaying post processing queus from the wiki no longer work with the new db structure. Is there any way to find out why I have 111,378 releases that are not getting processed? Is there any suggestions you can give me as to why these releases are not being processed? How do I find out even which releases these are?

**Comment by ruhllatio** [comment]
It's not a problem.  They are waiting for new scrapers.  Patience.

**Comment by bobtongue** [comment]
Okie Dokie - Thanks
