### ISSUE TITLE
New install php error

### ISSUE THREAD

**Issue by schwickster** [nZEDb/nZEDb#1945]
Upon doing a complete reinstall I get the following error:

Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nzedb2.settings' doesn't exist' in /home/schwick/www/nZEDb/nzedb/db/Settings.php:191 Stack trace: #0 /home/schwick/www/nZEDb/nzedb/db/Settings.php(191): PDO->query('UPDATE settings...') #1 /home/schwick/www/nZEDb/www/install/step2.php(186): nzedb\db\Settings->setSetting(Array) #2 {main} thrown in /home/schwick/www/nZEDb/nzedb/db/Settings.php on line 191

Few tables are made but not all. Step1 I got all checks cleared. nzedb worked fine before.

**Comment by schwickster** [comment]
When doing a manual import of mysql-ddl.sql:
ERROR 1071 (42000) at line 297: Specified key was too long; max key length is 1000 bytes

**Comment by Bart39** [comment]
we are working on it

**Comment by schwickster** [comment]
Managed to get it working by reverting this commit https://github.com/nZEDb/nZEDb/commit/4d58e80b7525848b567c96dc735a7ce0b721ceca

**Comment by Bart39** [comment]
not ther right solution, i said we were working on it. patch just pushed to dev

**Comment by schwickster** [comment]
I know. Was just a quick dirty workaround for me. I'll update once a new master commit is made. Keep up the good work!

**Comment by malanden** [comment]
Any update to this, waiting to reinstall

**Comment by schwickster** [comment]
malanden see these two commits:
https://github.com/nZEDb/nZEDb/commit/608414a88d5187bdf358696f3fc1fe571cd45be1
https://github.com/nZEDb/nZEDb/commit/0adaaab26800327b0ead12b02244d773dfb7ad72

**Comment by malanden** [comment]
Yup, saw that, but, its not pushed to master. When I checkout dev, i still get the same errors you reported earlier.

**Comment by ruhllatio** [comment]
It was still broken in all branches.  Should be fixed in all of them now too.
