### ISSUE TITLE
404 not found in when adding a show

### ISSUE THREAD

**Issue by Fossil01** [nZEDb/nZEDb#1957]
When trying to add a show to My Shows it brings you to the category selection page (myshows/add), I select a category, click next and it 404's on myshows/doadd.

No errors in the logs can be found. I'm on latest master.

**Comment by Fossil01** [comment]
Turns out it was a template issue. One of the default nzedb templates wasnt updated properly and I copied that one.

**Comment by niel** [comment]
Could you update the theme and create a PR for it please.

**Comment by jangrewe** [comment]
@Fossil01 could you share the fix, or better yet: open a pull request here on Github? Thanks! =)
