### ISSUE TITLE
Release source

### ISSUE THREAD

**Issue by scriptzteam** [nZEDb/nZEDb#1967]
This is really not an issue just want to contribute, will you be interest in all new scene/p2p releases feed out? we can make something like request system for releases, like on irc via !req BLAH.BLA-GRP but this will be in nzedb. i have setup all sources, just need to get it work with nzedb if interested.

**Comment by niel** [comment]
We're always interested in ways to improve indexing. ;-)
Need more details to make a decision though.

**Comment by ruhllatio** [comment]
Sounds promising.  Join us in IRC if you you want to talk about it @scriptzteam

**Comment by Fossil01** [comment]
nZEDb needs some CRC matching. (srrdb)
