### ISSUE TITLE
Syntax error or access violation: 1064 You have an error in your SQL syntax

### ISSUE THREAD

**Issue by moloquin** [nZEDb/nZEDb#1972]
Running lastest dev and when browsing cover view I see a page of sql errors (see below). Running with nzedb in "debug to webpage" turned on in settings.php.  Covers show up under all the errors in cover mode.

No errors reported to the page when list view is used.

Page seems to be rendering fine other than showing all the errors.

Turned off debug for the time being to hide the errors.  More just a cosmetic issue than anything as functionality seems to be fine.

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '39448471,39438017,39407241,39358625' at line 3
[24/Nov/2015 09:44] [SQL]    [5.08,5.55,5.95] [00H:00M:00S] [MEM:~~~3MB] [PID:8389] [nzedb\db\DB.queryDirect] [SELECT failed AS num FROM dnzb_failures WHERE release_id = 40690497,39448471,39438017,39407241,39358625]

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '40682490,40682066,40658474,40612493,40595884,40451858,40451021,40409413,40406811' at line 3
[24/Nov/2015 09:44] [SQL]    [5.08,5.55,5.95] [00H:00M:00S] [MEM:~~~3MB] [PID:8389] [nzedb\db\DB.queryDirect] [SELECT failed AS num FROM dnzb_failures WHERE release_id = 40691425,40682490,40682066,40658474,40612493,40595884,40451858,40451021,40409413,40406811,40404288,40403276,40402799,40032466,39681369,39684169,39669404,39640876,38567535,37893683,37898908,37030906,37006582,36618895,36424083,29753115,25621196,23654328,22000639,21993017,21983076,21758111,21652369,21619372,21597453,17610042,15195175]

**Comment by Wally73** [comment]
you sure you're on latest dev? which theme?

**Comment by moloquin** [comment]
Yup.  Just checked out dev approx. 1 hour ago.  Issue first popped up yesterday.

Tested alpha, omicron, charisma and simple and they are all showing the error.

**Comment by Wally73** [comment]
mm i'm on latest dev , alpha theme no issues at all

**Comment by moloquin** [comment]
I wonder if it's something incompatible in the versions I'm running...No errors in the mysql log or the httpd log.

CentOS release 6.7 (Final)

PHP 5.5.29 (cli) (built: Sep  4 2015 06:48:00) 

mysql  Ver 14.14 Distrib 5.6.27, for Linux (x86_64) using  EditLine wrapper

Server version: Apache/2.2.15 (Unix)
Server built:   Aug 24 2015 17:52:49

**Comment by ruhllatio** [comment]
I see the problem.  Definitely a code issue.

**Comment by moloquin** [comment]
Ok.  I'll just wait until there is a new version of dev to checkout.  Thanks!

**Comment by ruhllatio** [comment]
Do a pull.  Should be fixed now.

**Comment by moloquin** [comment]
Yup.  Just did a pull.  Looks good now.  Thanks.
