### ISSUE TITLE
tvsearch api function broken 

### ISSUE THREAD

**Issue by juancitotrucupe** [nZEDb/nZEDb#1974]
A few days back, I made a brand new installation of nZEDb by cloning the latest github release. Everything went well, and the system started indexing fine and making NZBs.  However, I noticed that SickBeard wasn't fetching any NZBs from my new nZEDb server.

So, I had SickBeard search for a show that I knew my server had already added. 
The show I used was "Legends (2014) S02E3". Sure enough, SickBeard could not find it on my server.

I did some troubleshooting and this is what I found out.

Sickbeard sent(apikey deleted):

    http://192.168.0.62/api?apikey=xxxxx&limit=100&t=tvsearch&season=2&rid=33288&maxage=1325&cat=5030%2C5040

My nZEDb server responded:

    <rss xmlns:atom="http://www.w3.org/2005/Atom" xmlns:newznab="http://www.newznab.com/DTD/2010/feeds/attributes/" version="2.0" encoding="utf-8">
    <channel>
    <atom:link href="http://192.168.0.62/api" rel="self" type="application/rss+xml"/>
    <title>NZBServer</title>
    <description>NZBServer API Results</description>
    <link>http://192.168.0.62/</link>
    <language>en-gb</language>
    <webMaster>(NZBServer)</webMaster>
    <category/>
    <image>
    <url>http://192.168.0.62/themes_shared/images/logo.png</url>
    <title>NZBServer</title>
    <link>http://192.168.0.62/</link>
    <description>Visit NZBServer - Local Usenet indexer</description>
    </image>
    </channel>
    </rss>
Which doesn't have nzbs. 

So, I tried changing rid=33288 for tvdbid=265074 and imdbid=tt2402137, and got the same empty result each time. Also, I tried replacing rid=33288 for q=legends, and again the same empty result came back.

Then replaced tvsearch by simply search:

    http://192.168.0.62/api?apikey=xxxxx&limit=100&t=search&q=legends&maxage=1325&cat=5030%2C5040

This time my nZEDb server responded:

    <rss xmlns:atom="http://www.w3.org/2005/Atom" xmlns:newznab="http://www.newznab.com/DTD/2010/feeds/attributes/" version="2.0" encoding="utf-8">
    <channel>
    <atom:link href="http://192.168.0.62/api" rel="self" type="application/rss+xml"/>
    <title>NZBServer</title>
    <description>NZBServer API Results</description>
    <link>http://192.168.0.62/</link>
    <language>en-gb</language>
    <webMaster>(NZBServer)</webMaster>
    <category/>
    <image>
    <url>http://192.168.0.62/themes_shared/images/logo.png</url>
    <title>NZBServer</title>
    <link>http://192.168.0.62/</link>
    <description>Visit NZBServer - Local Usenet indexer</description>
    </image>
    <item>
    <title>Legends.2014.S02E03.720p.HDTV.x264-0SEC</title>
    <guid isPermaLink="true">
    http://192.168.0.62/details/c30ea3ea90875097317ac00ad96311d4240fa81f
    </guid>
    <link>
    http://192.168.0.62/getnzb/c30ea3ea90875097317ac00ad96311d4240fa81f.nzb&i=1&r=xxxxx
    </link>
    <comments>
    http://192.168.0.62/details/c30ea3ea90875097317ac00ad96311d4240fa81f#comments
    </comments>
    <pubDate>Mon, 23 Nov 2015 23:03:42 -0500</pubDate>
    <category>TV > HD</category>
    <description>Legends.2014.S02E03.720p.HDTV.x264-0SEC</description>
    <enclosure url="http://192.168.0.62/getnzb/c30ea3ea90875097317ac00ad96311d4240fa81f.nzb&i=1&r=xxxxx" length="920434857" type="application/x-nzb"/>
    <newznab:attr name="category" value="1010"/>
    <newznab:attr name="size" value="920434857"/>
    </item>
    </channel>
    </rss>

Which is the answer I was looking for.

Please correct me if I'm wrong, but it appears to me that nZEDb is no longer responding correctly to the API tvsearch function and that is why now SickBeard cannot fetch NZBs from it.

**Comment by ruhllatio** [comment]
You're not wrong.  Master doesn't have a bunch of improvements that we have in Dev.  In short, we don't do things the same way any more.  Our matching is a direct match against third-party data now.  The old way was to trust the release but we don't do that now.  The show you're referencing is problematic because it is a show that should include the year in the title and you're not getting a response from TVDB for it.  This has been remedied in Dev.  Wait for the merge early December.  TVMaze should pick up these releases once its merged.  I am getting good matches from Sonarr's auto and manual searches for this show in the Dev branch.

Also, SickBeard hasn't been updated in over a year and does not support the new API specification so results from them will be shoddy at best.  Consider switching to something more recent.  I recommend Sonarr.

**Comment by juancitotrucupe** [comment]
Thanks. Looking forward to the next merge.

**Comment by juancitotrucupe** [comment]
Info. I tried it with Sonarr, and as it is, it won't even let me add it as an indexer. It puts out the following message:

    Invalid request Validation failed:  -- No results were returned from your indexer, please check your settings.

**Comment by Bart39** [comment]
As ruhllatio said it needs updating from Deb

**Comment by ruhllatio** [comment]
Sonarr should 'find' your indexer even on master though the results may still be spotty.  I've never had a problem with it, even when current master was in Dev.  Sure you don't have a configuration issue?

**Comment by juancitotrucupe** [comment]
I am sure. When it failed the first time I rechecked all info (URL and apiley) and tried again. Got the same error message back. I then replaced it with usenet-crawler.com (and my apikey) and that was accepted and works perfectly.

**Comment by Wally73** [comment]
usenet-crawler is 99% sure a NN+ site not nZEDb so you're comparing apples
with eggs

**Comment by juancitotrucupe** [comment]
When I inserted my nZEDb url and the api key I pressed the test button, and I got the error message. I rechecked the info and I tried the add button and I got the same error message. I pressed the add button and it gave me the same message and did not add it.

I checked the apache logs on my nZEDd server and it shows that Sonarr sent this (apikey removed);

    http://192.168.0.62/api?t=tvsearch&cat=5030,5040&extended=1&apikey=xxxx&offset=0&limit=100

This is what my nZEDb server responds:

    <rss xmlns:atom="http://www.w3.org/2005/Atom" xmlns:newznab="http://www.newznab.com/DTD/2010/feeds/attributes/" version="2.0" encoding="utf-8">
    <channel>
    <atom:link href="http://192.168.0.62/api" rel="self" type="application/rss+xml"/>
    <title>NZBServer</title>
    <description>NZBServer API Results</description>
    <link>http://192.168.0.62/</link>
    <language>en-gb</language>
    <webMaster>(NZBServer)</webMaster>
    <category/>
    <image>
    <url>http://192.168.0.62/themes_shared/images/logo.png</url>
    <title>NZBServer</title>
    <link>http://192.168.0.62/</link>
    <description>Visit NZBServer - Local Usenet indexer</description>
    </image>
    </channel>
    </rss>

I don't know guys, I just want to let you know what happened in case the info is useful to you. I really don't want to get you distracted from what you are doing. Thank you very much for your efforts. Please keep up the good work.

**Comment by kevinlekiller** [comment]
It seems to be working on 6box (http://nzedb.6box.me/api?t=tvsearch&cat=5030,5040&extended=1&apikey=xxxxxxxx&offset=0&limit=100), could be some kind of configuration issue?

**Comment by kevinlekiller** [comment]
Have you tried the "Show all passworded releases" setting?

**Comment by Wally73** [comment]
this is true a test account on my nzedb dev install as you can see it works
fine

http://newz2.whmeijer.com/api?t=tvsearch&cat=5030,5040&extended=1&apikey=bd7a3d353637a1ff77ab9539dad53bbe&offset=0&limit=100

**Comment by juancitotrucupe** [comment]
Guys, I do not know if this is a good test or not. It is however, the test that sonarr sends to test an index site in order to include it. The nZEDb version that I dowloaded a few days back from github, doesn't pass sonarr's test.

I had an older version of nZEDb running on my server, before the hard disk failed and had to be replaced. That version worked fine with sickbeard. I never tried it with sonarr. My HD failed so I had to do a complete new installation. This newer installation's api, does not work with either sickbeard nor sonarr.

Wally73, I added your dev install to Sonarr successfully, so whatever the issue is, you guys have already fixed it. Looking forward for the merge in december.

**Comment by ruhllatio** [comment]
We have a lot of folks (with rather large userbases) running master code.  We haven't heard anything like this from them.  And believe me with as long as it has been out there, we would have already heard the complaints.  Out of curiosity do you have TV releases, run TV processing, and have good TV matches?

**Comment by juancitotrucupe** [comment]
Yes, lots of TV releases, and many more come in each day. I can send them to my sabnzbd queue and they download fine. On the web interface, I can search for shows and get good matches.

So, I will start from scratch again. I willl reinstall ubuntu and everything else needed using your guide from github. Perhaps I missed something last time.

The good thing is that my server is private, so I do not have any other users and I am still getting my TV using other indexers out there.

I will let you know the results.

**Comment by ruhllatio** [comment]
Nah, you're missing the point.  Are you post processing TV?

**Comment by juancitotrucupe** [comment]
OK, I did the whole installation from scratch. Ubuntu 14, python, php, mysql,...the whole nine yards. Started indexing just fine. Many TV nzbs from a.b.teevee are already in. 

Still, I get exactly the same behavior from the api as before.

In the "Site Settings" "Post Processing" section I have "Lookup TV" set to "Lookup All TV". It says there that it will attempt to lookup  TVRAGE ids on the web. Is that what you mean when you ask if I'm post processing TV?

I noticed that simple.sh throws out an error message while running update_tvschedule.php. The message says:

    PHP Fatal error:  Class 'nzedb\TvRage' not found in /var/www/nZEDb/misc/update/update_tvschedule.php on line 7

I also notice on the web interface, that despite the fact that there are many TV releases listed for the group a.b.teevee, when I go into the "TV Series" Menu (the one with the "Jump to:  [ 0-9   A   B   C..." headding) there are no TV shows listed there.

**Comment by Bart39** [comment]
That's probably the issue - tmux has been updated for the new tv processing but I'm not sure anyone has updated the screen scripts

**Comment by ruhllatio** [comment]
Honestly, tmux has the option to run exactly like a screen script (full sequential) with better output and much less hassle.  I don't even know why we bother updating them.

**Comment by juancitotrucupe** [comment]
Because, you need an easy, simple way to verify that your very complex piece of software works as expected.

It is no hassle at all, to just run simple.sh to check that everything works fine.

Once you know that, you are ready to take advantage of the benefits of more advanced options that require further configuration.

**Comment by Wally73** [comment]
[quote]Bart39 commented 14 hours ago
That's probably the issue - tmux has been updated for the new tv processing but I'm not sure anyone has updated the screen scripts [/quote]

convinced simple user (ok modified) it works just fine but update_tvschedule.php isn't working anymore since tvrage is down so just remove that line from simple.sh (or put a # in front of it)

**Comment by ruhllatio** [comment]
@Wally73 - working on replacing that update_tvschedule script, but it will be doing a lot more like cross referencing IDs as well as pulling missing covers.
