### ISSUE TITLE
predb_import_daily_batch.php pulls from a non-existent Dropbox location

### ISSUE THREAD

**Issue by rsimplicio** [nZEDb/nZEDb#1978]
BUG

https://github.com/nZEDb/nZEDb/blob/master/cli/data/predb_import_daily_batch.php pulls from a Dropbox location that is no longer usable, returns "Failed to create list of filenames, aborting". 

Can we update this to pull from the Github files instead?

**Comment by Bart39** [comment]
This has already changed in dev branch either copy from there or watt illiterate merged to master next month
