### ISSUE TITLE
Getting loads of other>misc

### ISSUE THREAD

**Issue by rainje** [nZEDb/nZEDb#1981]
Since last master update I'm getting much more other>misc than before, and manually editing all these releases in kinda boring.

I'm having an issue with "abforeign" releases, most of them arent processed and end up in this category.

Here's the regex (release naming) i'm using : 
```
/^(?P<reqid>\d+)-\d+\[(?P<parts>\d{1,3}\/\d{1,3})\] - ".+?" yEnc$/i
```
It's working fine for some releases that get processed in the correct category but a lot of releases now end up in other>misc, even though the regex works with these releases aswell. So i'm not sure what's the issue here. I had pretty much 1 or 2 releases each day that werent being processed and since i updated to the last master i'm getting more that 10/15 each day. Only foreign seems affected, moovee/teevee/erotica seems to work fine even if I'm randomly getting some of them in other>misc.

![other](https://cloud.githubusercontent.com/assets/1025666/11454053/a7a206c0-9621-11e5-959c-7e3f8c5d0718.png)

**Comment by Wally73** [comment]
use https://github.com/nZEDb/nZEDb/blob/master/misc/testing/Release/fixReleaseNames.php

**Comment by rainje** [comment]
Half of them were fixed using fixReleaseNames 6 & 4.

I checked tmux settings and saw that Decrypt Hash Based Release Names was disabled. I can't remember doing this so was this done with the last update ?

I'll see if this helps.

**Comment by kevinlekiller** [comment]
That regex will not work.

**Comment by rainje** [comment]
? It does. It's specific to these releases.

**Comment by kevinlekiller** [comment]
It doesn't work with nzedb.

nzedb requires at least 1 named match, and "parts" / "reqid" are ignored.

Both regexes you posted do not work with nzedb.

https://github.com/nZEDb/nZEDb/blob/master/www/themes_shared/templates/admin/release_naming_regexes-edit.tpl#L24

**Comment by rainje** [comment]
So, there was an issue with the irc bot that wasnt indexing some releases and it's now fixed.
