### ISSUE TITLE
Quietly failing to create nzbs

### ISSUE THREAD

**Issue by rivalblue** [nZEDb/nZEDb#1982]
After a fresh install, twice now, I'm running into an issue every time I try to run 'php update_releases.php 1 true' in misc/update, it quietly exits the script right after it announces "Process Releases -> Create the NZB, delete collections/binaries/parts."

I'm not sure where I can enable logging to better isolate where the problem lies, but if someone can point me in that direction that'd be great!

Here's an example run:

/var/www/nZEDb/misc/update$ php update_releases.php 1 true
Starting release update process (2015-11-28 21:06:49)

Process Releases -> Attempting to find complete collections.
985 collections were found to be complete. Time: 4 second(s)

Process Releases -> Calculating collection sizes (in bytes).
985 collections set to filecheck = 3(size calculated)
0 second(s)

Process Releases -> Delete collections smaller/larger than minimum size/file count from group/site setting.
Deleted 1640 collections: 
0 smaller than, 0 bigger than, 1640 with less files than site/group settings in: 16 second(s)

Process Releases -> Create releases from complete collections.
850 Collections ready to be converted to releases.
Added 846 releases.
846 Releases added and 4 duplicate collections deleted in 5 second(s)

Process Releases -> Create the NZB, delete collections/binaries/parts.
/var/www/nZEDb/misc/update$

**Comment by Wally73** [comment]
turn on error reporting in php.ini's 

copy nzedb/config/settings,example.php to nzedb/config/settings.php and edit it 
log settings are from line 250 and down

**Comment by rivalblue** [comment]
Aha! Thank you!  Seems it was related to an issue with gzopen in nzedb/NZB.php as described here: http://forums.nzedb.com/index.php?topic=1988.0  Very pleased to get this installation back up and running!
