### ISSUE TITLE
Update to Master

### ISSUE THREAD

**Issue by bobtongue** [nZEDb/nZEDb#1993]
I just saw that there was a new merge to the master branch this morning about 2 hours ago. I did a git pull and the output didn't look like the normal output when there is an update. This is what I saw.

sql nZEDb # git pull
remote: Counting objects: 2315, done.
remote: Compressing objects: 100% (210/210), done.
remote: Total 2315 (delta 1302), reused 1183 (delta 1183), pack-reused 908
Receiving objects: 100% (2315/2315), 935.16 KiB | 0 bytes/s, done.
Resolving deltas: 100% (1572/1572), completed with 359 local objects.
From https://github.com/nZEDb/nZEDb
   a5914b5..1d1fb98  master     -> origin/master
   1c813a9..a21e67c  dev        -> origin/dev
 * [new branch]      dev-themes -> origin/dev-themes
 * [new branch]      dev-tmux   -> origin/dev-tmux
   9d18b61..3a1eeb6  dev-tv     -> origin/dev-tv
   6ae3f79..6ffe745  next-master -> origin/next-master
 * [new tag]         0.4.20.1   -> 0.4.20.1
 * [new tag]         v0.4.21    -> v0.4.21
 * [new tag]         v0.4.22    -> v0.4.22
 * [new tag]         v0.4.23    -> v0.4.23
 * [new tag]         v0.4.24    -> v0.4.24
 * [new tag]         v0.4.25    -> v0.4.25
 * [new tag]         v0.4.26    -> v0.4.26
Updating a5914b5..1d1fb98
Fast-forward
 Ubunutu-14.04.2-Install.txt | 224 ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 1 file changed, 224 deletions(-)
 delete mode 100644 Ubunutu-14.04.2-Install.txt

It doesn't look like anything was updated at all. Am I missing something?

**Comment by DariusIII** [comment]
I think it did update, if you do git pull again, it will most likely tell you you are up-to-date.

**Comment by Wally73** [comment]
its not merged into master yet ;)

**Comment by DariusIII** [comment]
I thought it is.

**Comment by bobtongue** [comment]
I thought it was also.

**Comment by Fossil01** [comment]
I thought it was not.

**Comment by ruhllatio** [comment]
https://github.com/nZEDb/nZEDb/pull/1992 - @niel just opened the pull request.  Probably to make sure we aren't missing anything like last go round.  I'm sure he will have it merged shortly.
