### ISSUE TITLE
Gamma Template Issues

### ISSUE THREAD

**Issue by testarea1** [nZEDb/nZEDb#2003]
I'm sure Gamma template is still a work in progress, but just in case, figured I'd submit some issues I've seen while using it:

* Sample video links point to wrong video file
 * Release details sample tab show extension .ogg when nzedb saves them as .ogv, need to change sample video extension to reflect .ogv
* Upcoming Theater movie posters are broken. Looks like the site it pulls them from is no longer valid "https://dkpu1ddg7pbsk.cloudfront.net"

**Comment by DariusIII** [comment]
Upcoming is broken on all the templates, not just Gamma. I will fix the samples extension, as i do not use it, did not notice the wrong extension.

**Comment by testarea1** [comment]
It also appears the browse pre info hover on the PreDB button shows  error: Not found on all the releases that have it. Not showing any predb info in the release details view also.

**Comment by DariusIII** [comment]
It should be fixed in dev-themes branch.

**Comment by ruhllatio** [comment]
@testarea1 can you confirm this is fixed?
