### ISSUE TITLE
Not getting new releases

### ISSUE THREAD

**Issue by thejrose1984** [nZEDb/nZEDb#2009]
Noticed I wasn't getting anything new for a while when I came across these messages:
http://pastebin.com/GH1cAkdD
Checked the DB, which was all of 500MB.
I also checked to make sure there was sufficient space for nzb files.
Any suggestions?

**Comment by Wally73** [comment]
seems like a db issue; so check the tables

**Comment by thejrose1984** [comment]
DB looks fine...

**Comment by Wally73** [comment]
it doesnt insert so db isn't fine for sure

**Comment by thejrose1984** [comment]
DB user, nzedb, has full rights to the database in question, which includes the ability to insert...
Not a DBA so going to need more info than that in order to troubleshoot...

**Comment by Wally73** [comment]
run optimise_db.php full (in /misc/update)

**Comment by thejrose1984** [comment]
done - http://pastebin.com/GgPv57vy

**Comment by thejrose1984** [comment]
issue persists...

**Comment by Wally73** [comment]
which branch?

**Comment by thejrose1984** [comment]
master

**Comment by Wally73** [comment]
since i dont see anymore issues on master the problem lays on your end

**Comment by thejrose1984** [comment]
...

**Comment by Sweepr** [comment]
First stop all the update scripts, thendo a repair on collections, binaries and parts table, something has been corrupted, then try again,.

**Comment by Sweepr** [comment]
If that does not work then truncate collections, binaries and parts table and start over.

**Comment by thejrose1984** [comment]
Tried all that and now I have an empty instance with no releases...

**Comment by Sweepr** [comment]
So what happens when you start the scripts, do you see that error again?

**Comment by Sweepr** [comment]
Could you verify these settings (which can be found here: https://github.com/nZEDb/nZEDb/wiki/install-guide:--General) in your SQL config?

max_allowed_packet = 16M
group_concat_max_len = 8192

**Comment by thejrose1984** [comment]
Adjusted DB settings, restarted SQL service and will advise once I've tested...

**Comment by thejrose1984** [comment]
Resolved by doing a fresh instance of nZEDb, increased allocated resources for SQL instance, and dropping all tables in DB...
