### ISSUE TITLE
Issue with XXX Gamma Pages

### ISSUE THREAD

**Issue by scottia** [nZEDb/nZEDb#2022]
Couple issues with XXX pages in Gamma Theme while browsing around :)

Issues number 1
Click on move poster shows this pop-up
![image](https://cloud.githubusercontent.com/assets/5298748/12185539/116681c2-b561-11e5-9f41-3be1679f0e40.png)

Issue number 2
No icons under move poster
![image](https://cloud.githubusercontent.com/assets/5298748/12185564/3f4a4592-b561-11e5-8312-a7ca49a487f1.png)

**Comment by DariusIII** [comment]
I have pushed a PR to fix both issues, now its up to devs with admin access to merge it.

**Comment by scottia** [comment]
Thank you!  I can wait

**Comment by scottia** [comment]
Closing.  Looks great.  Thanks @DariusIII
