### ISSUE TITLE
Charisma theme. Edit profile doesn't show available themes correctly.

### ISSUE THREAD

**Issue by niel** [nZEDb/nZEDb#2025]
The drop down list looks empty, white ink on white background I think.

**Comment by niel** [comment]
Looks like this is a bad path or URL. Looking into it.

**Comment by niel** [comment]
Not caused by the bad URL. Leaving this for DariusIII to look into.

**Comment by niel** [comment]
@DariusIII can you look into this and do a PR against dev-themes if you find the answer.

**Comment by DariusIII** [comment]
I will have a look at it, it is just a style thing. Will do a PR in the morning.

**Comment by DariusIII** [comment]
Fixed in commit d320c714e11a959a8b7d44b4e81f4a9a29044c29
