### ISSUE TITLE
Backfill Days per Group ignored

### ISSUE THREAD

**Issue by jangrewe** [nZEDb/nZEDb#2028]
I i edit a group and set the Backfill Days to e.g. "2" while "Site Edit -> Usenet Settings -> Where to start new groups: -> Days" is set to "1", the backfill loop will ignore the more specific setting and use the global one.

(dev branch)

**Comment by niel** [comment]
These settings are not connected. 
The where to start applies to a brand new group and starts indexing (update binaries) from the specified point. Note that number of posts is recommended for this setting.
The Backfill days is for the backfilling script which has nothing to do with indexing NEW posts.
