### ISSUE TITLE
No Posters on Theatre Pages

### ISSUE THREAD

**Issue by scottia** [nZEDb/nZEDb#2029]
I validated my Rottentomato API key here ( http://developer.rottentomatoes.com/io-docs ) as valid but no Posters showing on my site, just movie info ?  This occurs on ALL themes in DEV @ the moment.

![theatres rottentomatoes](https://cloud.githubusercontent.com/assets/5298748/12242141/e8e9b8fa-b85c-11e5-8f26-3f3efc6f944d.jpg)

**Comment by niel** [comment]
Can you be more specific. I'm looking at my movie page (covers view) and I have images for them.

**Comment by Wally73** [comment]
@niel its the upcoming stuff ;) 

url/upcoming

**Comment by scottia** [comment]
localhost/upcoming is the link

**Comment by DariusIII** [comment]
RottenTomatoes have blocked pulling better images from their CDN. We need to either use the default,  bad images, or find a method to pull in better ones.
