### ISSUE TITLE
Gamma: no Homepage when not logged in

### ISSUE THREAD

**Issue by jangrewe** [nZEDb/nZEDb#2031]
The content page declared as "homepage" isn't shown to users that are not logged in

**Comment by niel** [comment]
What is shown?

**Comment by DariusIII** [comment]
Most likely a login screen. If that is the case, that is the default behaviour for any theme, as far as i know.

**Comment by jangrewe** [comment]
No, i checked with niel on IRC, the Alpha theme displays the content page just fine.

**Comment by DariusIII** [comment]
Fixed in commit 8200f2e33c0860ee5355c4f671eb21b228d5229b
