### ISSUE TITLE
Gamma: Books->Comics menu

### ISSUE THREAD

**Issue by jangrewe** [nZEDb/nZEDb#2033]
The "Comics" option in the "Books" header menu is linking to /books instead of /browse?t=8020

**Comment by DariusIII** [comment]
It has been fixed in dev-themes.

**Comment by jangrewe** [comment]
I've checked out that branch, cleared the template cache, but... nope. =(

**Comment by DariusIII** [comment]
Pushed the fix to dev-themes, it should be fine now.

**Comment by DariusIII** [comment]
As this is fixed in dev-themes i am closing the issue for now.
