### ISSUE TITLE
REQUEST: include PREDBURL (if PREDB info exists) in extended=1 API information

### ISSUE THREAD

**Issue by doubledrat** [nZEDb/nZEDb#2035]
extended API information does not return either the PREDB status (present or not) or the PREDBurl.  It's there in the GUI, so it would be great if it was accessible from the API too - it helps discern genuine releases from SPAM etc.

please can it be added.

thanks :-)

**Comment by b3rs3rk** [comment]
If you query extended you should now see:

`<newznab:attr name="prematch" value="1" />`

If the release has a valid PreDB match.  Nothing will be returned if it doesn't.  We opted not to provide the URL or ID and determined this would suffice to determine genuineness.
