### ISSUE TITLE
Error 1064 (42000) when restoring from prod to dev box

### ISSUE THREAD

**Issue by dilbaggins** [nZEDb/nZEDb#2038]
Hi Guys,

the two boxes are identical (same mariaDB version etc):  

getting this error upon restore:  

ERROR 1064 (42000) at line 12182: You have an error in your SQL syntax; check th
e manual that corresponds to your MariaDB server version for the right syntax to
 use near '*/' at line 1

havent had this issue in the past with restoring the DB from my prod to dev box.

i am on the latest dev build.

**Comment by niel** [comment]
what's at that line? The whole line, because MySQL isn't very good at pointing to the problem ;-)

**Comment by dilbaggins** [comment]
/*!50003 CREATE*/ /*!50017 DEFINER=`root`@`localhost`*/ /*!50003 TRIGGER insert_MD5 BEFORE INSERT ON release_comments FOR EACH ROW SET NEW.text_hash = MD5(NEW.text); */;;

**Comment by niel** [comment]
Looks like there are spaces in there that don't belong.

**Comment by dilbaggins** [comment]
is there a utility i need to run. i havent had this issue in the past.  all i did was a backup and restore :)

**Comment by niel** [comment]
Try replacing it with:
/!50003 CREATE/ /!50017 DEFINER=root@localhost
//*!50003 TRIGGER insert_MD5 BEFORE INSERT ON release_comments FOR EACH ROW SET NEW.text_hash = MD5(NEW.text); */;;

**Comment by dilbaggins** [comment]
ouch opening a 7GB file is rough.

**Comment by dilbaggins** [comment]
no dice..  getting to another error. 

really wacky one.

**Comment by kaibosh** [comment]
Came across this one last weekend. Used vim to delete that very same line from the sql dump (of 24G). After the import was complete, manually added the trigger with:
CREATE TRIGGER insert_MD5 BEFORE INSERT ON release_comments FOR EACH ROW SET NEW.text_hash = MD5(NEW.text);
Appears to be a mariadb export/import bug. Running 10.0.21 here.

**Comment by dilbaggins** [comment]
thanks @kaibosh that fixed it!!  awesome stuff :)

**Comment by Wally73** [comment]
@kaibosh make a wiki entrance for this please ;) 
@dilbaggins if its solved you can close this issue

**Comment by kaibosh** [comment]
lol, well I could do... there's a few updates I've been meaning to get to.
@dilbaggins what distro are you using?

**Comment by dilbaggins** [comment]
@kaibosh Ubuntu 14.04.3 LTS

**Comment by kaibosh** [comment]
Oh that's a long term release, so I've posted in the forums also:
http://forums.nzedb.com/index.php?topic=2183.0
https://github.com/nZEDb/nZEDb/wiki/Common-Errors
