### ISSUE TITLE
Omnicron Theme - Registration

### ISSUE THREAD

**Issue by DejaVu** [nZEDb/nZEDb#2042]
Sending someone an invite and clicking it asks to login not register when the Invite only option is selected Edit Site.

Does not direct to a registration page. 

Shame because I really love that theme.

**Comment by DariusIII** [comment]
I will have a look at it.

**Comment by DariusIII** [comment]
Fixed in commit 8200f2e33c0860ee5355c4f671eb21b228d5229b
