### ISSUE TITLE
no releases after latest category change Dev pull

### ISSUE THREAD

**Issue by dilbaggins** [nZEDb/nZEDb#2043]
love the bleeding edge.. just odd no releases showing after the script move (on apache pages).  the categories look ok just no releases showing.

**Comment by dilbaggins** [comment]
http://snag.gy/B3TLO.jpg

**Comment by niel** [comment]
make sure you've run the update_db.php script.

**Comment by dilbaggins** [comment]
pop@kliqdev1:/var/www/nZEDb/misc/testing/DB$ php autopatcher.php true
Stopping tmux scripts and waiting 15 seconds for all panes to shutdown
Already up-to-date.
Patching database - nzedb.
Db updater starting ...
Looking for unprocessed patches...
Info: Nothing to patch, you are already on version 422
You should clear your smarty template cache at: /var/www/nZEDb/libs/smarty/templates_c
Starting tmux scripts.

**Comment by niel** [comment]
I'd recommend you don't use autopatcher, it has not been updated in a very long time.
Use: php cli/update_db.php true

**Comment by dilbaggins** [comment]
it has worked fine and did the job of running the update_db.php utility and the git update.  

it seems our db update script for these categories isnt working.

should i run DB/recategorize all?

**Comment by niel** [comment]
More a warning about the future, it might stop working at anytime.
It could be the group(s) you are indexing do not have regexes associated with them. Recategorising might help as we have made some changes recently to improve matching.

**Comment by dilbaggins** [comment]
trying to figure out why all my releases ended up in Misc.

**Comment by niel** [comment]
seems there's a problem with patch 422 that may be the cause of this.

**Comment by dilbaggins** [comment]
today about 20 minutes after your chanelog update

**Comment by niel** [comment]
Probably part of the problem reported by NZBMets then. We're looking into it.

**Comment by jangrewe** [comment]
Yup, same here. I just noticed that all my releases got removed after the last pull.

**Comment by Bart39** [comment]
Have commented on the commit for patch 422 -it's missing an else clause

**Comment by dilbaggins** [comment]
is there going to be instructions on how to re-run or correct ?  thanks guys

**Comment by jangrewe** [comment]
I guess you'll have to restore from a backup, at least that's what i'm doing.

**Comment by dilbaggins** [comment]
i ran a recategorize so my releases are there its just taking a while to process 500k in releases :)

**Comment by jangrewe** [comment]
Lucky you, i'm purging all "other" releases if they're not categorized correctly... and that happened. =(

**Comment by dilbaggins** [comment]
id be luckier if i was eating a Doner Kabob :)  

Good luck

**Comment by Bart39** [comment]
recategorize is your only other option if you can't restore from a backup

**Comment by dilbaggins** [comment]
@Bart39 i did a restore of my db from Sunday.  ran the updated script and things are still ending up in MISC.  as a heads up

**Comment by niel** [comment]
reverted original change back to individual updates. and split the partitioning into a new patch because the original wouldn't work apprently.
