### ISSUE TITLE
Omicron and Charisma Template missing file issues

### ISSUE THREAD

**Issue by bobtongue** [nZEDb/nZEDb#2052]
I don't know if this is addressed in DEV yet, but I am on master. The last couple of updates have changed files for the new templates but there are a couple issues that still exist. 
MyShows still does not list and shows cannot be added to myshows. I know these are not new issues, but I just want to report that they are still not fixed.
Attached is a pic of what the my shows listing looks like:

![myshows](https://cloud.githubusercontent.com/assets/3394024/12750040/659a18d2-c982-11e5-8410-90282d3a0229.jpg)

Here are the errors from my apache error log:

[Mon Feb 01 14:43:18 2016] [error] [client 192.168.1.1] File does not exist: /var/www/myserver.com/htdocs/nZEDb/www/themes/themes, referer: http://myserver.com/themes/shared/styles/admin.css
[Mon Feb 01 15:14:54 2016] [error] [client 192.168.1.1] File does not exist: /var/www/myserver.com/htdocs/nZEDb/www/themes/shared/scripts/jquery.qtip2.js, referer: http://myserver.com/profileedit
[Mon Feb 01 15:14:55 2016] [error] [client 192.168.1.1] File does not exist: /var/www/myserver.com/htdocs/nZEDb/www/themes/Omicron/css, referer: http://myserver.com/profileedit
[Mon Feb 01 15:14:55 2016] [error] [client 192.168.1.1] File does not exist: /var/www/myserver.com/htdocs/nZEDb/www/themes/Omicron/js, referer: http://myserver.com/profileedit
[Mon Feb 01 15:15:06 2016] [error] [client 192.168.1.1] File does not exist: /var/www/myserver.com/htdocs/nZEDb/www/themes/shared/scripts/jquery.qtip2.js, referer: http://myserver.com/myshows
[Mon Feb 01 15:15:06 2016] [error] [client 192.168.1.1] File does not exist: /var/www/myserver.com/htdocs/nZEDb/www/themes/Omicron/css, referer: http://myserver.com/myshows
[Mon Feb 01 15:15:06 2016] [error] [client 192.168.1.1] File does not exist: /var/www/myserver.com/htdocs/nZEDb/www/themes/Omicron/js, referer: http://myserver.com/myshows
[Mon Feb 01 15:15:19 2016] [error] [client 192.168.1.1] File does not exist: /var/www/myserver.com/htdocs/nZEDb/www/themes/shared/scripts/jquery.qtip2.js, referer: http://myserver.com/series
[Mon Feb 01 15:15:19 2016] [error] [client 192.168.1.1] File does not exist: /var/www/myserver.com/htdocs/nZEDb/www/themes/Omicron/css, referer: http://myserver.com/series
[Mon Feb 01 15:15:19 2016] [error] [client 192.168.1.1] File does not exist: /var/www/myserver.com/htdocs/nZEDb/www/themes/Omicron/js, referer: http://myserver.com/series
[Mon Feb 01 15:15:28 2016] [error] [client 192.168.1.1] File does not exist: /var/www/myserver.com/htdocs/nZEDb/www/themes/shared/scripts/jquery.qtip2.js, referer: http://myserver.com/mymovies
[Mon Feb 01 15:15:28 2016] [error] [client 192.168.1.1] File does not exist: /var/www/myserver.com/htdocs/nZEDb/www/themes/Omicron/css, referer: http://myserver.com/mymovies
[Mon Feb 01 15:15:28 2016] [error] [client 192.168.1.1] File does not exist: /var/www/myserver.com/htdocs/nZEDb/www/themes/Omicron/js, referer: http://myserver.com/mymovies
[Mon Feb 01 15:15:31 2016] [error] [client 192.168.1.1] File does not exist: /var/www/myserver.com/htdocs/nZEDb/www/themes/shared/scripts/jquery.qtip2.js, referer: http://myserver.com/myshows
[Mon Feb 01 15:15:31 2016] [error] [client 192.168.1.1] File does not exist: /var/www/myserver.com/htdocs/nZEDb/www/themes/Omicron/css, referer: http://myserver.com/myshows
[Mon Feb 01 15:15:31 2016] [error] [client 192.168.1.1] File does not exist: /var/www/myserver.com/htdocs/nZEDb/www/themes/Omicron/js, referer: http://myserver.com/myshows
[Mon Feb 01 15:15:36 2016] [error] [client 192.168.1.1] File does not exist: /var/www/myserver.com/htdocs/nZEDb/www/themes/Omicron/js, referer: http://myserver.com/myshows
[Mon Feb 01 15:25:40 2016] [error] [client 192.168.1.1] File does not exist: /var/www/myserver.com/htdocs/nZEDb/www/themes/shared/scripts/jquery.qtip2.js, referer: http://myserver.com/myshows
[Mon Feb 01 15:25:40 2016] [error] [client 192.168.1.1] File does not exist: /var/www/myserver.com/htdocs/nZEDb/www/themes/Omicron/css, referer: http://myserver.com/myshows
[Mon Feb 01 15:25:40 2016] [error] [client 192.168.1.1] File does not exist: /var/www/myserver.com/htdocs/nZEDb/www/themes/Omicron/js, referer: http://myserver.com/myshows
[Mon Feb 01 15:25:49 2016] [error] [client 192.168.1.1] File does not exist: /var/www/myserver.com/htdocs/nZEDb/www/themes/shared/scripts/jquery.qtip2.js, referer: http://myserver.com/series
[Mon Feb 01 15:25:49 2016] [error] [client 192.168.1.1] File does not exist: /var/www/myserver.com/htdocs/nZEDb/www/themes/Omicron/css, referer: http://myserver.com/series
[Mon Feb 01 15:25:49 2016] [error] [client 192.168.1.1] File does not exist: /var/www/myserver.com/htdocs/nZEDb/www/themes/Omicron/js, referer: http://myserver.com/series
[Mon Feb 01 15:25:54 2016] [error] [client 192.168.1.1] File does not exist: /var/www/myserver.com/htdocs/nZEDb/www/themes/shared/scripts/jquery.qtip2.js, referer: http://myserver.com/series/2791
[Mon Feb 01 15:25:54 2016] [error] [client 192.168.1.1] File does not exist: /var/www/myserver.com/htdocs/nZEDb/www/series, referer: http://myserver.com/series/2791
[Mon Feb 01 15:25:54 2016] [error] [client 192.168.1.1] File does not exist: /var/www/myserver.com/htdocs/nZEDb/www/series, referer: http://myserver.com/series/2791
[Mon Feb 01 15:25:58 2016] [error] [client 192.168.1.1] File does not exist: /var/www/myserver.com/htdocs/nZEDb/www/themes/shared/scripts/jquery.qtip2.js, referer: http://myserver.com/myshows/add/2791?from=%2Fseries%2F2791
[Mon Feb 01 15:25:58 2016] [error] [client 192.168.1.1] File does not exist: /var/www/myserver.com/htdocs/nZEDb/www/myshows, referer: http://myserver.com/myshows/add/2791?from=%2Fseries%2F2791
[Mon Feb 01 15:25:58 2016] [error] [client 192.168.1.1] File does not exist: /var/www/myserver.com/htdocs/nZEDb/www/myshows, referer: http://myserver.com/myshows/add/2791?from=%2Fseries%2F2791
[Mon Feb 01 15:26:23 2016] [error] [client 192.168.1.1] File does not exist: /var/www/myserver.com/htdocs/nZEDb/www/themes/shared/scripts/jquery.qtip2.js, referer: http://myserver.com/
[Mon Feb 01 15:26:23 2016] [error] [client 192.168.1.1] File does not exist: /var/www/myserver.com/htdocs/nZEDb/www/themes/Omicron/css, referer: http://myserver.com/
[Mon Feb 01 15:26:23 2016] [error] [client 192.168.1.1] File does not exist: /var/www/myserver.com/htdocs/nZEDb/www/themes/Omicron/js, referer: http://myserver.com/
[Mon Feb 01 15:26:29 2016] [error] [client 192.168.1.1] File does not exist: /var/www/myserver.com/htdocs/nZEDb/www/themes/shared/scripts/jquery.qtip2.js, referer: http://myserver.com/profile
[Mon Feb 01 15:26:29 2016] [error] [client 192.168.1.1] File does not exist: /var/www/myserver.com/htdocs/nZEDb/www/themes/Omicron/css, referer: http://myserver.com/profile
[Mon Feb 01 15:26:29 2016] [error] [client 192.168.1.1] File does not exist: /var/www/myserver.com/htdocs/nZEDb/www/themes/Omicron/js, referer: http://myserver.com/profile
[Mon Feb 01 15:28:33 2016] [error] [client 192.168.1.1] File does not exist: /var/www/myserver.com/htdocs/nZEDb/www/themes/shared/scripts/jquery.qtip2.js, referer: http://myserver.com/profile
[Mon Feb 01 15:28:33 2016] [error] [client 192.168.1.1] File does not exist: /var/www/myserver.com/htdocs/nZEDb/www/themes/Omicron/css, referer: http://myserver.com/profile
[Mon Feb 01 15:28:33 2016] [error] [client 192.168.1.1] File does not exist: /var/www/myserver.com/htdocs/nZEDb/www/themes/Omicron/js, referer: http://myserver.com/profile
[Mon Feb 01 15:28:35 2016] [error] [client 192.168.1.1] File does not exist: /var/www/myserver.com/htdocs/nZEDb/www/themes/shared/scripts/jquery.qtip2.js, referer: http://myserver.com/profileedit
[Mon Feb 01 15:28:35 2016] [error] [client 192.168.1.1] File does not exist: /var/www/myserver.com/htdocs/nZEDb/www/themes/Omicron/css, referer: http://myserver.com/profileedit
[Mon Feb 01 15:28:36 2016] [error] [client 192.168.1.1] File does not exist: /var/www/myserver.com/htdocs/nZEDb/www/themes/Omicron/js, referer: http://myserver.com/profileedit
[Mon Feb 01 15:28:46 2016] [error] [client 192.168.1.1] PHP Notice:  Undefined index: firstname in /var/www/myserver.com/htdocs/nZEDb/www/pages/profileedit.php on line 39, referer: http://myserver.com/profileedit
[Mon Feb 01 15:28:46 2016] [error] [client 192.168.1.1] PHP Notice:  Undefined index: lastname in /var/www/myserver.com/htdocs/nZEDb/www/pages/profileedit.php on line 40, referer: http://myserver.com/profileedit
[Mon Feb 01 15:28:46 2016] [error] [client 192.168.1.1] PHP Notice:  Undefined index: firstname in /var/www/myserver.com/htdocs/nZEDb/www/pages/profileedit.php on line 67, referer: http://myserver.com/profileedit
[Mon Feb 01 15:28:46 2016] [error] [client 192.168.1.1] PHP Notice:  Undefined index: lastname in /var/www/myserver.com/htdocs/nZEDb/www/pages/profileedit.php on line 68, referer: http://myserver.com/profileedit
[Mon Feb 01 15:28:47 2016] [error] [client 192.168.1.1] File does not exist: /var/www/myserver.com/htdocs/nZEDb/www/templates, referer: http://myserver.com/profileedit
[Mon Feb 01 15:28:47 2016] [error] [client 192.168.1.1] File does not exist: /var/www/myserver.com/htdocs/nZEDb/www/themes/shared/scripts/jquery.qtip2.js, referer: http://myserver.com/profileedit
[Mon Feb 01 15:28:52 2016] [error] [client 192.168.1.1] File does not exist: /var/www/myserver.com/htdocs/nZEDb/www/templates, referer: http://myserver.com/myshows
[Mon Feb 01 15:28:52 2016] [error] [client 192.168.1.1] File does not exist: /var/www/myserver.com/htdocs/nZEDb/www/themes/shared/scripts/jquery.qtip2.js, referer: http://myserver.com/myshows
[Mon Feb 01 15:34:16 2016] [error] [client 192.168.1.1] File does not exist: /var/www/myserver.com/htdocs/nZEDb/www/templates, referer: http://myserver.com/profile
[Mon Feb 01 15:34:16 2016] [error] [client 192.168.1.1] File does not exist: /var/www/myserver.com/htdocs/nZEDb/www/themes/shared/scripts/jquery.qtip2.js, referer: http://myserver.com/profile
[Mon Feb 01 15:34:19 2016] [error] [client 192.168.1.1] File does not exist: /var/www/myserver.com/htdocs/nZEDb/www/templates, referer: http://myserver.com/profileedit
[Mon Feb 01 15:34:19 2016] [error] [client 192.168.1.1] File does not exist: /var/www/myserver.com/htdocs/nZEDb/www/themes/shared/scripts/jquery.qtip2.js, referer: http://myserver.com/profileedit
[Mon Feb 01 15:34:26 2016] [error] [client 192.168.1.1] PHP Notice:  Undefined index: firstname in /var/www/myserver.com/htdocs/nZEDb/www/pages/profileedit.php on line 39, referer: http://myserver.com/profileedit
[Mon Feb 01 15:34:26 2016] [error] [client 192.168.1.1] PHP Notice:  Undefined index: lastname in /var/www/myserver.com/htdocs/nZEDb/www/pages/profileedit.php on line 40, referer: http://myserver.com/profileedit
[Mon Feb 01 15:34:26 2016] [error] [client 192.168.1.1] PHP Notice:  Undefined index: firstname in /var/www/myserver.com/htdocs/nZEDb/www/pages/profileedit.php on line 67, referer: http://myserver.com/profileedit
[Mon Feb 01 15:34:26 2016] [error] [client 192.168.1.1] PHP Notice:  Undefined index: lastname in /var/www/myserver.com/htdocs/nZEDb/www/pages/profileedit.php on line 68, referer: http://myserver.com/profileedit

**Comment by DariusIII** [comment]
Most of the problems, but not all, are fixed in dev-themes. We will fix the remaining ones.

**Comment by niel** [comment]
Can you provide a more up to date out put, most of those errors are fixed in master now (the nZEDb/www/themes/shared/scripts/jquery.qtip2.js ones) as I updated it an hour or two ago.

**Comment by bobtongue** [comment]
Looks like the missing files problem is solved after another pull, but still seeing the same thing when I try to list my shows. and add a show still doesn't work.
None of the following errors is generated when I try to list myshows. Most are generated when trying to add a show. The last couple came when I clicked on "View Releases for My Shows" from the myshows list page.
I don't seem to be getting any errors now when trying to list. Not in apache error log or php error log. Not sure why the series are not listing. Full series list work and I still can browse releases from my shows. Odd.
Here is output of error file 
[Tue Feb 02 10:26:40 2016] [error] [client 192.168.1.1] PHP Notice:  Undefined index: firstname in /var/www/myserver.com/htdocs/nZEDb/www/pages/profileedit.php on line 39, referer: http://myserver.com/profileedit
[Tue Feb 02 10:26:40 2016] [error] [client 192.168.1.1] PHP Notice:  Undefined index: lastname in /var/www/myserver.com/htdocs/nZEDb/www/pages/profileedit.php on line 40, referer: http://myserver.com/profileedit
[Tue Feb 02 10:26:40 2016] [error] [client 192.168.1.1] PHP Notice:  Undefined index: firstname in /var/www/myserver.com/htdocs/nZEDb/www/pages/profileedit.php on line 67, referer: http://myserver.com/profileedit
[Tue Feb 02 10:26:40 2016] [error] [client 192.168.1.1] PHP Notice:  Undefined index: lastname in /var/www/myserver.com/htdocs/nZEDb/www/pages/profileedit.php on line 68, referer: http://myserver.com/profileedit
[Tue Feb 02 10:35:57 2016] [error] [client 192.168.1.1] File does not exist: /var/www/myserver.com/htdocs/nZEDb/www/series, referer: http://myserver.com/series/2791
[Tue Feb 02 10:36:00 2016] [error] [client 192.168.1.1] File does not exist: /var/www/myserver.com/htdocs/nZEDb/www/series, referer: http://myserver.com/series/2791
[Tue Feb 02 10:36:00 2016] [error] [client 192.168.1.1] File does not exist: /var/www/myserver.com/htdocs/nZEDb/www/myshows, referer: http://myserver.com/myshows/add/2791?from=%2Fseries%2F2791
[Tue Feb 02 10:36:00 2016] [error] [client 192.168.1.1] File does not exist: /var/www/myserver.com/htdocs/nZEDb/www/myshows, referer: http://myserver.com/myshows/add/2791?from=%2Fseries%2F2791
[Tue Feb 02 10:36:38 2016] [error] [client 192.168.1.1] File does not exist: /var/www/myserver.com/htdocs/nZEDb/www/myshows, referer: http://myserver.com/myshows/add/2791?from=%2Fseries%2F2791
[Tue Feb 02 10:41:12 2016] [error] [client 192.168.1.1] File does not exist: /var/www/myserver.com/htdocs/nZEDb/www/myshows, referer: http://myserver.com/myshows/browse
[Tue Feb 02 10:41:12 2016] [error] [client 192.168.1.1] File does not exist: /var/www/myserver.com/htdocs/nZEDb/www/myshows, referer: http://myserver.com/myshows/browse
[Tue Feb 02 10:42:27 2016] [error] [client 192.168.1.1] File does not exist: /var/www/myserver.com/htdocs/nZEDb/www/myshows, referer: http://myserver.com/myshows/browse
[Tue Feb 02 10:42:27 2016] [error] [client 192.168.1.1] File does not exist: /var/www/myserver.com/htdocs/nZEDb/www/myshows, referer: http://myserver.com/myshows/browse

**Comment by niel** [comment]
Those missing file errors are a problem as they're trying to use files without the .php extension - i.e. series and myshow instead of series.php and myshow.php
I'll look into them.

**Comment by thejrose1984** [comment]
Noticing this as well in addition to not being able to add items to SABnzbd queue...

**Comment by DariusIII** [comment]
I have made a PR to fix at least some of those errors. Will fix the rest of them today.

**Comment by thejrose1984** [comment]
Found more - http://pastebin.com/m5YL7PfM

**Comment by niel** [comment]
That's the same error repeated multiple times. Not at all helpful.
The file specified (menu.gif) should exist, if it doesn't your repository is broken somehow.
