### ISSUE TITLE
More PHP errors

### ISSUE THREAD

**Issue by thejrose1984** [nZEDb/nZEDb#2053]
More issues related to [Issue # 2045](https://github.com/nZEDb/nZEDb/issues/2045)

PHP Log File = http://pastebin.com/crFC7mt

**Comment by niel** [comment]
That link is no longer available.

**Comment by thejrose1984** [comment]
Try now - http://pastebin.com/sSWkzCUF

**Comment by niel** [comment]
All those errors are network socket related, nothing to do with nZEDb directly. Off the top of my head I can't think how trace the problem.

**Comment by niel** [comment]
Actually, that address for your USP looks wrong, make sure you have the correct setting in .../nzedb/config/config.php

**Comment by thejrose1984** [comment]
I'm going to need more information than "make sure you have the correct setting" since the information I enter into nZEDb is the same as what I put in SABnzbd.

**Comment by kaibosh** [comment]
Could be a DNS issue. Do you see these warnings generated permanently or more sporadically?

**Comment by DariusIII** [comment]
Disable SSL for start.

**Comment by thejrose1984** [comment]
Seems like the links are hard coded and not relational...

**Comment by thejrose1984** [comment]
Disabling SSL had no impact.

**Comment by thejrose1984** [comment]
http://pastebin.com/3ai1dkFY

**Comment by Wally73** [comment]
i only see notices those you can ignore

**Comment by niel** [comment]
@thejrose1984 that latest list is completely unrelated to the previous one which was all network problems. Remind me which theme you're using, please?

@Wally73 we don't ignore notices/warnings, as our code should run clean.

**Comment by thejrose1984** [comment]
@niel Omicron - please note I was using though nginx SSL proxy. Since noticing all the issues adding to Queue as well as other related issues shown in the logs, I have removed it from the proxy and access it LAN only

@Wally73 the entire point of providing logs is to identify an issue. not sweep it under the rug

**Comment by DariusIII** [comment]
What version of SABnzbd are you using? I see that you are literally having notices with every line where $obj us used?

**Comment by thejrose1984** [comment]
@DariusIII SABnzbd 0.7.20

Changed theme to Alpha and noticed no change. SABnzbd shows empty from nZEDb, even though I can confirm there are active downloads.

nginx-error.log - http://pastebin.com/Wjd6hFrC
php-errors.log - http://pastebin.com/KkuPLamB
php-fpm.log - http://pastebin.com/mZ73wvcP

Also changed php-fpm.conf listen on TCP port 9000 instead of UNIX socket (doesn't seem to make a difference based on the logs)

**Comment by DariusIII** [comment]
Ok, this means it is not theme related. Can you update to latest release of sab (1.0.0 RC1), so we can exclude it is some bug in sabnzbd?

**Comment by thejrose1984** [comment]
SABnzbd is installed within a FreeBSD jail as a package. I'm assuming you're asking me to install from a git repository?

**Comment by DariusIII** [comment]
I realy don't care how, just install it if you can. I need to be sure it is not an bug inside SAB.

**Comment by thejrose1984** [comment]
Upgraded, but now CP won't accept the API key...

**Comment by thejrose1984** [comment]
And to add insult to injury, upgrading SABnzbd didn't resolve the issue. In fact, it caused more...

**Comment by DariusIII** [comment]
I am willing to take the risk of being wrong, but i think that something is borked on your side, as other users have not reported any sab related problems, and i even asked and got the answer that sab IS working.The php-errors log is not related to this issue, those are connection problems to your USP. What version of PHP do you have installed on server?

**Comment by thejrose1984** [comment]
PHP 5.6.17 (cli) (built: Jan 17 2016 04:13:05)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies

**Comment by thejrose1984** [comment]
root@nzedb:/ # pkg info | grep php56
php56-5.6.17                   PHP Scripting Language
php56-ctype-5.6.17             The ctype shared extension for php
php56-curl-5.6.17              The curl shared extension for php
php56-dba-5.6.17               The dba shared extension for php
php56-exif-5.6.17              The exif shared extension for php
php56-filter-5.6.17            The filter shared extension for php
php56-gd-5.6.17                The gd shared extension for php
php56-hash-5.6.17              The hash shared extension for php
php56-iconv-5.6.17             The iconv shared extension for php
php56-json-5.6.17              The json shared extension for php
php56-mbstring-5.6.17_1        The mbstring shared extension for php
php56-mcrypt-5.6.17            The mcrypt shared extension for php
php56-mysql-5.6.17             The mysql shared extension for php
php56-opcache-5.6.17           The opcache shared extension for php
php56-openssl-5.6.17           The openssl shared extension for php
php56-pdo-5.6.17               The pdo shared extension for php
php56-pdo_mysql-5.6.17         The pdo_mysql shared extension for php
php56-posix-5.6.17             The posix shared extension for php
php56-session-5.6.17           The session shared extension for php
php56-simplexml-5.6.17         The simplexml shared extension for php
php56-sockets-5.6.17           The sockets shared extension for php
php56-xml-5.6.17               The xml shared extension for php
php56-zlib-5.6.17              The zlib shared extension for php

**Comment by thejrose1984** [comment]
Figured out the SABnzbd issue. The coding for nZEDb is very, VERY specific how the URL is put into the profile. If it isn't `http://[ip_address]:8080/sabnzbd/` then it will either show a blank queue or not at all. To me, it sounds like a hard coded code segment.

**Comment by thejrose1984** [comment]
Compressed current logs and restarted services. Hopefully the errors will disappear...

**Comment by thejrose1984** [comment]
Wiped out my instance and DB. Started from scratch and seeing the following in the PHP error log:
`[18-Feb-2016 23:49:29 America/New_York] PHP Warning:  stream_socket_client(): unable to connect to tls://news.frugalusenet.com:5563 (php_network_getaddresses: getaddrinfo failed: hostname nor servname provided, or not known) in /usr/local/www/nZEDb/libs/Net_NNTP/NNTP/Protocol/Client.php on line 515`

**Comment by Wally73** [comment]
according to the frugalusenet.com faq your port doesnt exist (5563)

You can use any of the following ports: 20, 23, 53, 119, 443, 2000, 8080,
9000, 9001, 9002

http://frugalusenet.com/faq.html

**Comment by thejrose1984** [comment]
Quoting FAQ:

> 4) My ISP is junk and I need alternate ports, what are they? 
> You can use any of the following ports: 20, 23, 53, 119, 443, 2000, 8080, 9000, 9001, 9002
> 5) How do I connect using SSL?
> Well, you need an SSL capable newsreader. Enable SSL by following your newsreader instructions. You may use either port 563 or 5563.

**Comment by thejrose1984** [comment]
Changed port to 443, then restarted PHP-FPM as well as nginx. Still getting errors:
http://pastebin.com/BGricVt5

**Comment by Wally73** [comment]
try a normal non ssl port

**Comment by thejrose1984** [comment]
Wouldn't it make more sense to use an SSL port?

**Comment by DariusIII** [comment]
PHP Warning: stream_socket_client(): unable to connect to tls://news.frugalusenet.com:5563 (php_network_getaddresses: getaddrinfo failed: hostname nor servname provided, or not known) 

This is purely a USP connection problem.

**Comment by Wally73** [comment]
thejrose1984 commented 4 hours ago
Wouldn't it make more sense to use an SSL port? << i meant try to connect without SSL

**Comment by thejrose1984** [comment]
Apparently nZEDb doesn't like connecting to USP with SSL...that's a major oversight. Even more so than hard coded URL's...

**Comment by thejrose1984** [comment]
Not to mention the strict requirements for SABnzbd integration...

**Comment by Wally73** [comment]
Since you are the only one who's complaining about it its most like an issue on your end (or your USP just sucks) I don't see any more issues with ssl

**Comment by kaibosh** [comment]
SSL to usp works fine here. 

fwiw, SSL is not required for sabnzbd integration, its optional.

**Comment by kevinlekiller** [comment]
> Figured out the SABnzbd issue. The coding for nZEDb is very, VERY specific how the URL is put into the profile. If it isn't http://[ip_address]:8080/sabnzbd/ then it will either show a blank queue or not at all. To me, it sounds like a hard coded code segment..

The only check that I can see done on the sab url is when on the profile page, if it's empty or not.

The code just takes the URL from the DB that you put in your profile and that's it, it's actually just the same code as the newznab code we forked from.

nzedb: https://github.com/nZEDb/nZEDb/blob/dev/nzedb/SABnzbd.php#L106

newznab repo we forked from: https://github.com/anth0/nnplus/blob/momo/www/lib/sabnzbd.php#L47

The individual function just append whatever the rest of the URL as per the sab API spec:

https://github.com/nZEDb/nZEDb/blob/dev/nzedb/SABnzbd.php#L215

https://github.com/anth0/nnplus/blob/momo/www/lib/sabnzbd.php#L81

http://wiki.sabnzbd.org/api#toc22

**Comment by kevinlekiller** [comment]
> Apparently nZEDb doesn't like connecting to USP with SSL...that's a major oversight. Even more so than hard coded URL's...

The only thing that would prevent you from connecting to your SSL USP with nzedb is if you didn't properly set up the SSL stuff on the installer, these are not issues with nzedb, it's how PHP 5.6+ has strict SSL verification of certificates https://secure.php.net/manual/en/migration56.openssl.php

If you just want to run the same way PHP 5.5 was running (which is to not check certificates at all) then go in nzedb/config/config.php and set nZEDb_SSL_VERIFY_PEER / nZEDb_SSL_VERIFY_HOST to 0 and set nZEDb_SSL_ALLOW_SELF_SIGNED to 1, otherwise you'll need to get the proper certificates and put them in the right paths with the right permissions and set up the paths correctly in that config file for all the SSL servers you will connect to.
