### ISSUE TITLE
RSS internal error (wrong function called)

### ISSUE THREAD

**Issue by Antyrael** [nZEDb/nZEDb#2058]
I was getting these errors when I tried to go to the RSS page:
`PHP Fatal error:  Call to undefined method nzedb\Category::getCategories() in /var/www/nZEDb/www/pages/rss.php on line 43`

After taking a look at the file /var/www/nZEDb/nzedb/Category.php, I noticed that the actual function to get the array of categories is simply get(), instead of getCategories().

So, after changing that in /var/www/nZEDb/www/pages/rss.php, it worked again.

**Comment by niel** [comment]
Which branch and theme?

**Comment by Antyrael** [comment]
I'm using the Master branch.

The theme is irrelevant.

**Comment by niel** [comment]
Fixed in dev commit 420137c
