### ISSUE TITLE
alpha theme some buttons very out of alignment 

### ISSUE THREAD

**Issue by Wally73** [nZEDb/nZEDb#2063]
[https://gyazo.com/060b715f5cd0104d85e4501ae52250ab](url)

those buttons are way too far to the right (list overview)

and in spot detail view the cover image is too far to the right also 

[https://gyazo.com/32a82fb3a4c0fc518068c450d536b527](url)

**Comment by niel** [comment]
Is this in dev?
They've always been off for me, so I assumed it is a pre-existing bug.

**Comment by Wally73** [comment]
yeah its in dev (i don't run anything else as dev ;) ) 

yeah they were always off but it seems a lot more off as before

**Comment by DariusIII** [comment]
I believe i have fixed it. It needs a review by @niel .

**Comment by niel** [comment]
Fixed by Commit 271af4

**Comment by Wally73** [comment]
latest dev merge fixed it indeed ;) thx DariusIII and niel
