### ISSUE TITLE
default theme not scaling on my res

### ISSUE THREAD

**Issue by OliverLeitner** [nZEDb/nZEDb#2066]
version: current stable
tested browsers: firefox current, chromium current
os client: ubuntu lts
os server: ubuntu lts (installed php5 plugins accordingly to wiki guide for ubuntu
screen res client: 1280x1024

screens:
http://oi66.tinypic.com/24b9fn5.jpg
http://oi67.tinypic.com/111ngk4.jpg

**Comment by DariusIII** [comment]
Known problem, we are working on it.

**Comment by zetas** [comment]
I believe PR #2074 that was merged into dev-themes fixes this issue.

**Comment by niel** [comment]
Yes, this is fixed in our dev-themes branch which should be merged into dev later this week.

**Comment by OliverLeitner** [comment]
good to hear, ill keep an eye on stable files=)
