### ISSUE TITLE
request: choice to use local copies of javascript libraries

### ISSUE THREAD

**Issue by OliverLeitner** [nZEDb/nZEDb#2067]
this is a mere request.

while it might be easier to keep up to date with external hosted javascript libraries, theres security concerns and sometimes speed concerns with that.
after all, you dont control whats coming downstream from there and how stable the url really is.

it would be nice to have a checkbox or a dropdown to choose either your cdn provider or a local copy.

**Comment by zetas** [comment]
I've actually modified my personal installation to only use local version of the libraries for privacy concerns for users. This is something I could probably submit as a PR. Possibly with a admincp option for toggle. What do you think @niel

**Comment by niel** [comment]
I think an option or drop box is too complicated for the themes system we have. 

The only way an admin can be relatively sure of privacy/security concerns is to audit the files themselves. If they're doing that they should download from a trusted (the creating project's source tree) location and edit. Nothing we can do to make that easier.

**Comment by OliverLeitner** [comment]
ok, i thought id bring it up, thanks for the information, gotta have to check the tpl files then myself. just a bit scared if i edit them and theres an update on the trunk, i loose my changes again.

**Comment by zetas** [comment]
Welcome to my world. I run almost completely custom versions of the Alpha template as well as most of the "pages" php files. Merging is a nightmare. This is why I can't wait for us to migrate to a framework so things can be modular and I could have a custom module instead of changing base code.

**Comment by OliverLeitner** [comment]
well, one might copy the default template to a custom subdir and change some params there, and then set nzedb to use to that one, but still, that way you wont get any changes/fixes in that are provided by the nzedb "team". 

frameworks scare me most of the time, as they blow up the code, as an effect pages get slower, and things like nzedb, that highly depends on system resources get borked by bogus functions.

btw, all templates are kinda broke, i have had a look, so far the best looking really is the default, i can read all the texts, and it doesnt try to shrink and enlarge images too much.

**Comment by DariusIII** [comment]
We use composer now with local libraries, so this should be no issue anymore.
