### ISSUE TITLE
request: output of results count on api / rss requests

### ISSUE THREAD

**Issue by OliverLeitner** [nZEDb/nZEDb#2068]
would it be possible to have a total count of results on search requests and rss category feeds without loosing too much speedwise?

**Comment by b3rs3rk** [comment]
@zetas Don't you have something like this?  If you had a code snippet you could send me I could integrate it.

**Comment by JudsonHat** [comment]
If this requests means to add something like `<newznab:response offset="0" total="1825"/>` to an api result, then I would also like to see this feature added.  Looks like it was removed with this commit. https://github.com/nZEDb/nZEDb/pull/1930 Can it be added back?

**Comment by DariusIII** [comment]
It has been added back 149f53fea3e38ac2852f295a79d5c2a3bc649857

**Comment by JudsonHat** [comment]
Thanks a lot!
