### ISSUE TITLE
api search bug(s)

### ISSUE THREAD

**Issue by OliverLeitner** [nZEDb/nZEDb#2069]
version: current stable
settings.php: memcache cluster enabled, transactions enabled.
php 5.6
mariadb 10.1
table release_search_data: compressed innodb (default after converting tables to cinnodb)

when trying to search via the api, the following errors occured to me:

1. when im logged in, and do a search without apikey, it shows a blank page
2. when im logged in, and add the apikey to the url, i get a blank page too

both those i was unable to avoid.

2. if im not logged in, and provide the apikey, i get a blank page, until i edit settings.php and change nZEDb_RELEASE_SEARCH_TYPE to 1.

**Comment by OliverLeitner** [comment]
even after converting the release_search_data table to myisam, still didnt get the search_type 0 working.

what are the things that need to be given for the search option to work at its default settings?

**Comment by zetas** [comment]
Regardless of your settings, you should never get a blank page. That usually means there is a server error somewhere and the error output is being suppressed. I would look at your error logs to see what happened. If it's a development server, consider turning on display_errors in the settings.php at the bottom. Otherwise, make sure your system is setup to log errors somewhere.

**Comment by OliverLeitner** [comment]
well, the sourcecode of the page looks like this, so its not really blank:

searchstring:
`https://indexinghost.localnet/api?apikey=####################&t=s&q=LEGO`

searchtype: 0

output:

```
<rss xmlns:atom="http://www.w3.org/2005/Atom" xmlns:newznab="http://www.newznab.com/DTD/2010/feeds/attributes/" version="2.0" encoding="utf-8">
<script/>
<channel>
<atom:link href="https://indexinghost.localnet/api" rel="self" type="application/rss+xml"/>
<title>nZEDb</title>
<description>nZEDb API Results</description>
<link>https://indexinghost.localnet/</link>
<language>en-gb</language>
<webMaster>no@none.com (nZEDb)</webMaster>
<category/>
<image>
<url>
https://indexinghost.localnet/themes/shared/img/logo.png
</url>
<title>nZEDb</title>
<link>https://indexinghost.localnet/</link>
<description>Visit nZEDb - A great usenet indexer</description>
</image>
</channel>
</rss>
```

same url gave back a few results with search type 1.

database error log shows nothing (thats the only one itd hit in this case, right?)

of course, both search types "break" (as in, no result returned but the above) if im logged in and try with apikey.

**Comment by jmelen** [comment]
I'm also experiencing this issue. When logged in, API requests return a blank page. Logged out, works as intended. Nginx access log shows a return status of 200.

**Comment by Wally73** [comment]
i have noticed a blank api page too (on dev)
Apache/2.4.10 (Debian) PHP/5.6.17-0+deb8u1
10.1.12-MariaDB-1~jessie mariadb.org binary distribution

**Comment by Enverex** [comment]
Ditto, web front-end works fine, API just returns blank pages (with code 200 success).

**Comment by Wally73** [comment]
yeah in all themes

On Sat, Mar 12, 2016 at 2:58 PM, Benjamin Hodgetts <notifications@github.com

**Comment by beodegit** [comment]
@zetas : I looked into this issue and it seems like there is supposed to be a closing brace somewhere around line 81 of www/pages/api.php. (And there is an excess closing brace at line 353 then)

(Sorry to provide feedback this way, I don't know my way around github yet)

**Comment by OliverLeitner** [comment]
thanks for the fix, beodegit, everything seems to be working fine now in that context=)
