### ISSUE TITLE
request: possibility to import zipped archives

### ISSUE THREAD

**Issue by OliverLeitner** [nZEDb/nZEDb#2071]
i think it would be nice to be able to put a zip with nzbs inside it into the import folder, and the script unzips it, imports, deletes nzbs _and_ the zip file, plus the extracted directory, if any.

other packer formats (i.e. nzb.gz) would be nice to have too...

**Comment by niel** [comment]
simple enough to use a script for that. If we were to implement it, it would most likely be for .gz zipped files.
