### ISSUE TITLE
request: include optimize_db.php into tmux session

### ISSUE THREAD

**Issue by OliverLeitner** [nZEDb/nZEDb#2073]
i think it might be a nice idea to have it run automagically every week or so. controllable via admin panel.

that way you dont have to stop all operations and tmux itself for running it, it could temporarily pause the operations of all other scripts once a week and have the database checked and possibly fixed (maybe even reduced in size by fixing on leftover index interleaves...)

**Comment by kaibosh** [comment]
Online db optimisation was once implemented within tmux but was removed as it caused too many issues.

The screen sequential script still has periodic db optimisation built-in. That code can be copied for tmux complete-sequential.

For tmux basic & non-sequential a cronjob like this might do the trick:

```
php misc/update/nix/tmux/stop.php
php misc/update/optimise_db.php space
php misc/update/nix/tmux/start.php
```

**Comment by OliverLeitner** [comment]
ahh well, i figured i might ask..., thanks for the explanation
