### ISSUE TITLE
tmux "counts" category -> in database for example question

### ISSUE THREAD

**Issue by OliverLeitner** [nZEDb/nZEDb#2075]
these tmux counts, do they show how many releases are in the database, or does it show something else.

because if its the number of releases in the database, it shows the wrong numbers, a select count(*) from releases where categoryid >= something and categoryid <= something shows different numbers.

also if i take passwordstatus and nzbstatus in account, the numbers are still coming up differently.

**Comment by kaibosh** [comment]
There's an explanation of the various counters in the tmux-edit page, monitor information block.

In the wiki page: https://github.com/nZEDb/nZEDb/wiki/Post-Processing-Queue-Management there's a few SQL queries that may help you understand some of the in-process counters. Note, some of the queries may be out-of-date.

It's important to realise that monitor.php does not perform every query each loop as many are too expensive, so various counters may be off by a few percent.

**Comment by OliverLeitner** [comment]
thank you for the link, gotta have a read there...

thats the thing, if i start tmux, everything is showing up "correct" (at least as far as i know at this point...), it gets more and "more out of sync", the longer the script is running (its running about 4 days for me now, and im off about 30.000 entries in the counts.

having a daily cron to stop the script is kinda contraproductive though afaik, because the priority really lays in the results in the database, which are good.

**Comment by b3rs3rk** [comment]
Being accurate with all of the counts is easy with a smaller database, but much harder for the guys running big databases.  The release counts are tabulated by parsing the mysql information tables with respect to the individual partitions.  It is much faster than doing SELECT COUNT(r.id) type operations (like fractions of seconds vs. potentially minutes on larger databases).  If you're all over the map, consider analyzing your releases table every so often to keep the statistics fresh.  No need to kill tmux.
