### ISSUE TITLE
errors from probably creatively named nzbs in resources/logs/php_errors.log

### ISSUE THREAD

**Issue by OliverLeitner** [nZEDb/nZEDb#2076]
heres some entries in the php errors log, seems that some "creatively named" content might cause problems with tmux procedures:

```
PHP Fatal error:  escapeshellarg(): Input string contains NULL bytes in /var/www/nZEDb/libs/rarinfo/rarinfo.php on line 570
PHP Notice:  Trying to get property of non-object in /var/www/nZEDb/nzedb/Binaries.php on line 278
PHP Warning:  substr() expects parameter 1 to be string, array given in /var/www/nZEDb/nzedb/ReleaseExtra.php on line 201
PHP Fatal error:  escapeshellarg(): Input string contains NULL bytes in /var/www/nZEDb/libs/rarinfo/rarinfo.php on line 570
```

**Comment by DariusIII** [comment]
Rarinfo is an external library we use and that is something we cannot fix. Also, it is possible that the actual rar is corrupted in some way, or is out of rar specification for some reason.
The error about line 278 in Binaries.php comes from your USP (code 411, group does not exist) and Binaries should disable that group, but fail to do so for some reason.

**Comment by OliverLeitner** [comment]
Hi DariusIII

thanks for the answer=)

i know that its rarinfo, which is an external lib, not sure what kind of work itd be (for you or the system load) to check the rar for validity before sending it to rarinfo. might it be the name or a zerofile.

**Comment by ghost** [comment]
@OliverLeitner Checkout https://github.com/nZEDb/nZEDb/issues/2143#issuecomment-219288783
