### ISSUE TITLE
TV Show Video & Episode ID removed after NFO processing

### ISSUE THREAD

**Issue by ghost** [nZEDb/nZEDb#2080]
Note: I'm behind by 2 master versions at the moment. So if anything changed with NFO processing since then let me know.

I manually imported a bunch of NZBs which nicely showed up after TV post processing with covers and all. After this I ran NFO post processing and it renamed the release to it's proper name but also removed the covers and all extra info. 

It's this release: http://83.149.75.183/?b=Quantico.S01E12.Alex.720p.HDTV.HEVC.x265-ShAaNiG&g=alt.binaries.hdtv&p=.+%28X265_PAR2_35%25%29&max=250 some files are shown by Binsearch as another collection.

Here's the output:

```
php postprocess.php nfo true

Processing 377 NFO(s), starting at 1000 * = hidden NFO, + = NFO, - = no NFO, f = download failed.

Available to process, -1 = 377.
----------+-+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

New name:  Quantico.S01E12.Alex.720p.HDTV.HEVC.x265-ShAaNiG
Old name:  Quantico.S01E12.Alex.720p.HDTV.HEVC.x265-ShAaNiG.mkv - 01 of 10
Use name:  Quantico.S01E12.Alex.720p.HDTV.HEVC.x265-ShAaNiG.mkv - 01 of 10 yEnc
New cat:   TV HD
Old cat:   TV HD
Group:     alt.binaries.hdtv
Method:    PAR2, fileCheck: Generic TV
ReleaseID: 8972339
-----------------------------
2 NFO file(s) found/processed.
```

**Comment by Bart39** [comment]
this is because nfo pp tv lookups were disabled when we switched to the new scrapers - looks like it didn't get updated

**Comment by ghost** [comment]
It actually gets the name from the PAR2 file. Anyway, how do I fix this?

**Comment by Bart39** [comment]
i'm not 100% sure but i think you will need to wait for someone to re-add the tv lookups from nfo/par2 processing
