### ISSUE TITLE
Request - 4K support

### ISSUE THREAD

**Issue by HarleyCarter1234** [nZEDb/nZEDb#2081]
Now that 4k blue ray seems to finally be starting, add support for 4k movies as another category

**Comment by niel** [comment]
Creating the categories is simple, however we would also need good regexes for identifying them. To start creating those regexes, we would need the scene's rules for those releases and/or examples of how others are posting them.

**Comment by HarleyCarter1234** [comment]
so far i've just been noticing a few items pop up when searching for '2160p' but not really sure what the official naming should be

I'd guess that now the actual disks are starting to filter out there that the content won't be far behind on usenet and we'll start seeing a lot more of it available

**Comment by niel** [comment]
For now it might be easiest to include these in HD categories, unless/until the scene decides if they will handle them differently.

**Comment by HarleyCarter1234** [comment]
will hang fire on this for now and see how things pan out with 4k content releases
