### ISSUE TITLE
UI-Bug: Missing Switch listview-thumbnailview in Movies, TV etc...

### ISSUE THREAD

**Issue by OliverLeitner** [nZEDb/nZEDb#2082]
this id expect:
http://oi64.tinypic.com/2akempk.jpg

thats what im seeing:
http://oi67.tinypic.com/jjb3hv.jpg

steps to reproduce:
install and run nzedb.

**Comment by Wally73** [comment]
in Alpha theme it's indeed missing 
as far as i can tell its present in all other themes

**Comment by DariusIII** [comment]
One part is fixed, but it is not an fix yet.

**Comment by DariusIII** [comment]
I will close this issue now. If something is still borked, feel free to reopen it.
