### ISSUE TITLE
Enhancement: Show releases without cover in thumbnail view (no-cover thumbnail?)

### ISSUE THREAD

**Issue by OliverLeitner** [nZEDb/nZEDb#2083]
what id expect to see:
all releases in both viewmodes.

what currently happens:
if you go to thumbnail view, you just see the releases with covers, others are hidden.

to reproduce it:
install and run nzedb, switch to list view (if switches are available, see my bug report before), remember what you see, then click on thumbnail view (if the switches are available).

**Comment by Wally73** [comment]
why do you want to see releases without covers in cover view???? its just the point that you only see those with covers IMO

**Comment by OliverLeitner** [comment]
this is about accuracy and usability, if youre on cover view and dont know the fact, youre missing out on alot.

**Comment by DariusIII** [comment]
Reading comprehension 0. <-
This is not an issue. Releases with covers can be seen in coverview, all of them in list view. This is by design.

**Comment by OliverLeitner** [comment]
well, thats why the topic says Enhancement;-)

**Comment by DariusIII** [comment]
I understand your view, but it's wrong. There is a reason behind having releases with covers and list view with all the releases. Mixing them would be ugly, wrong and futile.

**Comment by OliverLeitner** [comment]
ok, your software, entirely your decision.

**Comment by niel** [comment]
"Enhancement" is a matter of perspective. In this case I have to agree with Darius and Wally. Making the change you suggest is a change of concept for cover view. We could possibly add a reminder that releases without covers are omitted.
