### ISSUE TITLE
Database error when creating releases (Clean install)

### ISSUE THREAD

**Issue by groentebroer** [nZEDb/nZEDb#2084]
### Expected behaviour

Releases are added based on the imported binaries.
### Actual behaviour

Releases are not added.
Debug log error:
General error: 1364 Field 'videos_id' doesn't have a default value
("fixing by allowing 'null'" this went to:)
General error: 1364 Field 'tv_episodes_id' doesn't have a default value
After setting that to allow 'null' as well, the releases were made.
### Steps to reproduce the behaviour

Clean install.
Import any group and try to create releases.
(Configured for personal use so only the essential things are bing checked. All third party API's, etc are disabled.)

Please let me know if you would like to know any specific settings (eg settings export?)
Occurred with the latest GIT DEV version.

**Comment by niel** [comment]
videos_id should have a default value of zero. NULL will screw up other queries which is why is was not allowed. Please set all NULL values to zero and set the column to default to zero.
This is the second time someone has reported this particular error. I'll look into the master branch to see why it might be happening.

**Comment by groentebroer** [comment]
Oke, will change that.
Please let me know if you would like to have anymore specific settings, which might help you reproduce it.

**Comment by niel** [comment]
This was a problem with the table definition not setting the default value. It is fixed now.

**Comment by groentebroer** [comment]
Thanks!
When using it more with "0" as default value for video_id and tv_episodes_id, I ran into other issues.
Like not finding any Video / Series through the API (newznab).

I changed some options and now do the post processing, which fills the videos and tv_episodes tables. I think I will be able to find more now!

So it could be related to "not postprocessing".
