### ISSUE TITLE
Top menu links

### ISSUE THREAD

**Issue by ghost** [nZEDb/nZEDb#2086]
The top menu links are generated from the server_name variable in nginx configuration file while the category links are not. For example if the server_name is set to "localhost" when accessing the site on lan or via the ip remotely the top menu links become http://localhost/newposterwall which won't work in these cases. The categories menu links work correctly and change depending on where you connect from but the top menu links are maybe generated in a different way? I'm sorry if this is incorrect and an misconfiguration on my part.

**Comment by DariusIII** [comment]
What theme do you use?

**Comment by ghost** [comment]
I'm using the Simple theme. Just tested them all and it seems Charisma and Omicron are the only two working correctly for me.

**Comment by DariusIII** [comment]
I will have a look at it.

**Comment by ghost** [comment]
Thank you.

**Comment by DariusIII** [comment]
Charisma and Omicron have hardcoded menu links, while rest of the themes use links generated based on your site settings. You will have to use different servername if you want to access the site outside of your local network.
