### ISSUE TITLE
website is down

### ISSUE THREAD

**Issue by OliverLeitner** [nZEDb/nZEDb#2088]
website:

https://nzedb.github.io/nZEDb/

shows like this:

http://oi63.tinypic.com/xqezi9.jpg

**Comment by Wally73** [comment]
https://github.com/nZEDb/nZEDb/wiki

wiki works fine here

**Comment by OliverLeitner** [comment]
of course, it does.

but website is down.

**Comment by Wally73** [comment]
you said wiki wasn't working in your first :p 

true the gitio thing wasn't working but is now again 

url is changed to https://nzedb.github.io/

**Comment by OliverLeitner** [comment]
thats why i corrected, anyways, sorry for the first wrong version of info.

yah, works again, closing this.
