### ISSUE TITLE
/usr/bin/git log

### ISSUE THREAD

**Issue by Sweepr** [nZEDb/nZEDb#2090]
While running Tmux i noticed that a process "/usr/bin/git log" is being spawned 4-5 times per 60 seconds,.

When i stop Tmux, the /usr/bin/git log is no longer being called.

Is this normal?
Why does it have to do this 5 times per minute?
And what does it do?

**Comment by Sweepr** [comment]
According to the daily process log from 3-4-2016  usr/bin/git log is on number 6 of highest CPU usage

Top Processes 

User      % CPU     Process
root        69.0    /usr/bin/git log

According to the daily process log from 4-4-2016  usr/bin/git log is on number 2 of highest CPU usage

Top Processes 

User      % CPU     Process
root        92.0    /usr/bin/git log

**Comment by niel** [comment]
I don't have any idea what might cause this. git log is a command used for viewing commit information (https://git-scm.com/docs/git-log), so nZEDb has no need to be running it.

**Comment by Sweepr** [comment]
I don't know if it's a real issue or not but i have renamed the git binary to git.bak to create a error and in the error_log i found this:

/usr/bin/git log ' in /home/public_html/nZEDb/libs/Git.php/Git.php:330
Stack trace:
#0 /home/public_html/nZEDb/libs/Git.php/Git.php(346): GitRepo->run_command('/usr/bin/git lo...')
#1 /home/public_html/nZEDb/nzedb/utility/Git.php(102): GitRepo->run('log ')
#2 /home/public_html/nZEDb/nzedb/utility/Git.php(53): nzedb\utility\Git->log()
#3 /home/public_html/nZEDb/nzedb/TmuxOutput.php(118): nzedb\utility\Git->commits()
#4 /home/public_html/nZEDb/nzedb/TmuxOutput.php(49): nzedb\TmuxOutput->_getHeader()
#5 /home/public_html/nZEDb/misc/update/nix/tmux/monitor.php(324): nzedb\TmuxOutput->updateMonitorPane(Array)
#6 {main}
  thrown in /home/public_html/nZEDb/libs/Git.php/Git.php on line 330

Also the Tmux scripts stalled, renamed back and restarted the scripts and everything is running fine again.

Maybe this helps in finding the root cause if any.

**Comment by niel** [comment]
Hmm, strange. I'll look into that.

**Comment by Bart39** [comment]
In fact "git log" is only used in one place in our whole code base and that is the commit script we use for development

**Comment by niel** [comment]
Ok, I've found where and why this is called. It counts the number of commits made to the repository. for displaying on the main monitor pane.
Obviously, there's no need for this to be happening repeatedly. We'll look into fixing this to be more friendly to system resources.

**Comment by niel** [comment]
We decided to remove the commit count completely as it no longer serves a useful purpose.
Fixed in dev with commit 267907
