### ISSUE TITLE
PHP Fatal error:  require_once(): Failed opening required 'app/libraries/autoload.php'

### ISSUE THREAD

**Issue by moloquin** [nZEDb/nZEDb#2091]
Hello,

Updated dev to latest today, grabbed composer, and now can't start tmux or run the update_db.php script.

Pasted below is the error I'm seeing.  Seem to be missing the autoload.php on the app/libraries/ dir.

[nZEDb]# php /var/www/html/nZEDb/cli/update_db.php true
PHP Warning:  require_once(app/libraries/autoload.php): failed to open stream: No such file or directory in /sata/html/nZEDb/autoloader.php on line 39
PHP Fatal error:  require_once(): Failed opening required 'app/libraries/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /sata/html/nZEDb/autoloader.php on line 39

[nZEDb]# php /var/www/html/nZEDb/misc/update/nix/tmux/start.php 
PHP Warning:  require_once(app/libraries/autoload.php): failed to open stream: No such file or directory in /sata/html/nZEDb/autoloader.php on line 39
PHP Fatal error:  require_once(): Failed opening required 'app/libraries/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /sata/html/nZEDb/autoloader.php on line 39

**Comment by niel** [comment]
It's missing because you haven't run composer's install.
I mean `composer install` from your nZEDb directory, not installing composer.

**Comment by scottia** [comment]
Used the global method, making it globally available ?  Are you saying to move composer.phar to the nZEDb root?  Can you provide the proper nZEDb path.

Am having the same issue.

**Comment by moloquin** [comment]
Thanks.  That's got it.

Had to remove php-mysqld and install php-myslqnd for Centos6.  Tmux is running and things seem to working fine now.

**Comment by niel** [comment]
@scottia No. globally installing just makes it available every where. So you can run `composer install` from the nZEDb directory to tell composer to install the dependencies.
This is needed while we improve the support. I'll be adding a command to handle updating. It might require a global Composer install, unless I can work out a way to make it check for local install.

**Comment by scottia** [comment]
ran "composer install" BUT system is missing ext-mysqlnd extension

**Comment by moloquin** [comment]
I had to yum remove php-myslqd and yum install php-mysqlnd to get it to go.

This was on a Centos box, so not sure what you are running, but should be similar.

**Comment by niel** [comment]
@scottia You can comment out that requirement IF you really need to keep the other php5 MySQL extension.
php5-mysqlnd is the extension we specify in the guides for installing. Do you have some specific need for using the older (no longer updated) MySQL driver?

**Comment by niel** [comment]
BTW this is likely to be changing fairly quickly over the next week or so. You might want to ask in IRC #nZEDb for quicker replies ;-)

**Comment by scottia** [comment]
Can't access IRC from work but I will remember that !!

I have an ORIGINAL install from many years ago LOL.  Installed "php5-mysqlnd" and an up and running.

Thanks Niel

**Comment by OliverLeitner** [comment]
hmmz, may you please add that info i.e. via a link to the corresponding wiki page to the Changelog file?

**Comment by OliverLeitner** [comment]
additional tip:

remove/comment out the following entry from nzedb/config/Configure.php

require_once nZEDb_LIBS . 'autoloader.php';

**Comment by DariusIII** [comment]
There is no such line in Configure.php, anymore. You should check your install, and do git reset --hard, just in case.

**Comment by scottia** [comment]
@DariusIII you speaking to me ?  I did reset btw.  Thank you

**Comment by DariusIII** [comment]
@scottia No, i was reffering to @OliverLeitner

**Comment by OliverLeitner** [comment]
i know, i just checked the git status after i posted, that why i removed the post again. anyways, id find a changelog entry still being a good idea.

**Comment by niel** [comment]
I'm removing some comments because they no longer make sense after the removal of the starting comment.
@OliverLeitner What info would you like in the Changelog?
@All It would be better to have this conversation in IRC as I noted above. This situation is in flux and feedback is appreciated, but this is not the best place for it.

**Comment by OliverLeitner** [comment]
@niel 

cd /path/to/web
composer install

**Comment by niel** [comment]
It is _not_ /path/to/web. All shell commands should be entered from your nZEDb base directory unless specified otherwise (this would be /var/www/nZEDb by default on a Debian based system). Path to web would currently be the 'www' directory under the nZEDb one, and this might change in future.
I will clarify the Changlog to be clearer. I hadn't thought it needed to be spelled out that when you're working on your indexer, you have to be in its directory.

**Comment by OliverLeitner** [comment]
im certainly not entering the discussion on what to run from where, however...

thanks for considering clarification, i think this issue, which btw. i havent opened, shows the need;-) i guess were all not l33t enough...

what i mean, is, that the changelog contains no entry on the fact that you actually need to run "composer install" to have things working after upgrading from git. if you have it somewhere in the wiki, please link to the article. we should read the changelog file when were upgrading, right?
