### ISSUE TITLE
SMARTY_DIR constant not set?

### ISSUE THREAD

**Issue by ialexpw** [nZEDb/nZEDb#2092]
### Expected behaviour

Able to CHMOD the smarty directory and install
### Actual behaviour

Cannot install as I am getting:
"The template compile dir must be writable.
A quick solution is to run:
chmod 777 SMARTY_DIRtemplates_c"
### Steps to reproduce the behaviour

Install nZEDb then run composer install on the nZEDb directory..

Thanks

**Comment by niel** [comment]
Which branch?

**Comment by ialexpw** [comment]
dev

**Comment by niel** [comment]
Hmm, you'll be better off with the 0.x stable branch for now. I haven't got new installs tested on the latest dev, which just had composer support merged in. I'm concentrating on existing users first.

**Comment by ialexpw** [comment]
I'll do that - thanks :-)

**Comment by niel** [comment]
Fixed in dev now.
