### ISSUE TITLE
Preview/sample's broken (all themes)(dev)

### ISSUE THREAD

**Issue by Wally73** [nZEDb/nZEDb#2095]
### Actual behaviour

all covers/previews are broken as the path somehow is now to /var/www/nZEDb/app/webroot/resources/covers/tvshows/1381.jpg (ok that is one example) 
it was /var/www/nZEDb/resources/covers/

**Comment by m0rse** [comment]
same problem on dev:
seems to pointing to old www /covers directory 
on all themes

**Comment by niel** [comment]
@Wally73 are still seeing this after the reinstall?

**Comment by OliverLeitner** [comment]
i had the same problem.

what helped for me, was chmodding /path/to/web/resources again.

funny thing though, all covers are still created and called from the directory i have the covers in, that is outside of resources.

**Comment by Wally73** [comment]
after a fresh install the cover/preview don't work as the path in themes is 
/var/www/nZEDb/app/webroot/resources/covers/
instead of /var/www/nZEDb/resources/covers/

**Comment by PsychoSid** [comment]
Yeah same for me with broken covers etc. I have this in my Apache conf but it's not working for some reason.

Alias /covers /var/www/nZEDb/resources/covers

**Comment by niel** [comment]
Covers (for Apache users) now appear to be fixed in dev.
