### ISSUE TITLE
misc/testing/DB/autopatcher.php broken

### ISSUE THREAD

**Issue by OliverLeitner** [nZEDb/nZEDb#2096]
php autopatcher.php should output information on how to run the script

it currently shows blank, does not execute.

howto reproduce:
cd misc/testing/DB
php autopatcher.php

howto fix:
open file autopatcher.php in your favorite text editor, and comment out the following:

```
------------------------------------------------------------------------------------------------------------------------
...
...
//require_once realpath(dirname(dirname(dirname(__DIR__))) . DS . 'libs' . DS . 'smarty' . DS . 'Autoloader.php');

...
...
//Smarty_Autoloader::register();

...
...
//$smarty = new Smarty;
-------------------------------------------------------------------------------------------------------------------------
```

Explanation: Templating for a commandline script that just does updates in the database and displays nothing irt is not really needed.

**Comment by DariusIII** [comment]
Its not templating. Autopatcher clears templates_c folder for you (aka. Smarty Cache).

**Comment by niel** [comment]
autopatcher is out of date and not really supported. I'll be removing it in the near future once I've written a replacement.
