### ISSUE TITLE
Missing autoload.php

### ISSUE THREAD

**Issue by brando56894** [nZEDb/nZEDb#2100]
I setup my  installation using the Arch installation instructions and when everything is setup I get this error:

Warning: require_once(app/libraries/autoload.php): failed to open stream: No such file or directory in /srv/http/nZEDb/autoloader.php on line 38

Fatal error: require_once(): Failed opening required 'app/libraries/autoload.php' (include_path='.:') in /srv/http/nZEDb/autoloader.php on line 38

If I comment out that require_once() then I get

Fatal error: Uncaught Error: Class 'nzedb\config\Configure' not found in /srv/http/nZEDb/www/smarty.php:28 Stack trace: #0 /srv/http/nZEDb/www/index.php(2): require_once() #1 {main} thrown in /srv/http/nZEDb/www/smarty.php on line 28
### Expected behaviour

execute autoload.php
### Actual behaviour

throws an error because the apps/libraries directory is pretty much empty
### Steps to reproduce the behaviour

clone the repository and setup the vhost, then access it.

**Comment by brando56894** [comment]
Creating an empty autoload.php file in apps/libraries allowed me to continue to the index page but when I clicked the Pre-Flight Check it crashes with 

Fatal error: Uncaught Error: Class 'Smarty' not found in /srv/http/nZEDb/www/pages/InstallPage.php:23 Stack trace: #0 /srv/http/nZEDb/www/install/step1.php(11): InstallPage->__construct() #1 {main} thrown in /srv/http/nZEDb/www/pages/InstallPage.php on line 23

**Comment by niel** [comment]
If you'd searched the closed issues, you would have found this has been asked before.
You need to run `composer install` to install the libraries and have composer create that autoload.php file.

**Comment by brando56894** [comment]
Oh, thanks for the heads up.
