### ISSUE TITLE
New install failing step2

### ISSUE THREAD

**Issue by rcketscientist** [nZEDb/nZEDb#2101]
I have a user created and I can verify that the database grants are working since the database and tables are created correctly, but I still fail step2 with:

`Unable to create database and data. Check permissions of your mysql user.`

I would guess this is actually related to the file grant, but my grants look fine I think:

+---------------------------------------------------------------------------------------------------------------+
| Grants for indexer@localhost                                                                                  |
+---------------------------------------------------------------------------------------------------------------+
| GRANT FILE ON _._ TO 'indexer'@'localhost' IDENTIFIED BY PASSWORD '_----' |
| GRANT ALL PRIVILEGES ON `nzedb`._ TO 'indexer'@'localhost' WITH GRANT OPTION                                  |
+---------------------------------------------------------------------------------------------------------------+

Anywhere I can check for what specifically is failing?

**Comment by niel** [comment]
That doesn't look right to me. Shouldn't that full-stop character be a wildcard like *.*?

**Comment by rcketscientist** [comment]
I think the input gobbled something, sorry:

`GRANT FILE ON *.* TO 'indexer'@'localhost' IDENTIFIED BY PASSWORD >'*---'`
`GRANT ALL PRIVILEGES ON nzedb.* TO 'indexer'@'localhost' WITH GRANT OPTION`

**Comment by niel** [comment]
Is there a space between nzedb and the '.*' for the actual GRANT?

**Comment by niel** [comment]
It probably makes no difference, but I would do the GRANT ALL first.

**Comment by rcketscientist** [comment]
No there is not, and I've confirmed that all the tables are created so the database privilege is correct, at least create is working.

**Comment by rcketscientist** [comment]
I'm pretty sure I did do the database grant first, but this is after probably the 10th wipe and retry.  Most of the attempts were line by line from the doc.

**Comment by niel** [comment]
In which case it would likely be file permissions on the system. Be particularly aware that MySQL needs the traversible permissions on every directory leading to the TSV files, for all users.

**Comment by rcketscientist** [comment]
That was a bit beyond my sql knowledge.  Where should I be checking?

BTW, thanks for the lightning fast support.

**Comment by niel** [comment]
it's not SQL. It's your filesystem. The directories making up the path to your tsv files (in nZEDb/resources/db/data/) need to have the traversible bit set for all users, so that MySQL is allowed to read them.

**Comment by rcketscientist** [comment]
drwxrwxrwx  8 indexer www-data 4096 Apr 10 17:06 .
drwxrwxr-- 15 indexer www-data 4096 Apr 11 15:08 ..
drwxrwxrwx 16 indexer www-data 4096 Apr 10 17:06 covers
drwxrwxrwx  4 indexer www-data 4096 Apr 10 17:06 db
drwxrwxrwx  2 indexer www-data 4096 Apr 11 15:38 logs
drwxrwxrwx  2 indexer www-data 4096 Apr 10 17:06 nzb
drwxrwxrwx  3 indexer www-data 4096 Apr 10 17:06 smarty
drwxrwxrwx  4 indexer www-data 4096 Apr 10 17:06 tmp
indexer@vps:/var/www/nZEDb/resources$ cd db
indexer@vps:/var/www/nZEDb/resources/db$ ls
total 20
drwxrwxrwx 4 indexer www-data 4096 Apr 10 17:06 .
drwxrwxrwx 8 indexer www-data 4096 Apr 10 17:06 ..
-rwxrwxrwx 1 indexer www-data 1703 Apr 10 17:06 README.txt
drwxrwxrwx 3 indexer www-data 4096 Apr 10 17:06 patches
drwxrwxrwx 3 indexer www-data 4096 Apr 10 17:06 schema

Looks like 777 down the chain, but there is no nZEDb/resources/db/data/.

**Comment by rcketscientist** [comment]
I can't even find the error message I'm getting in step2.php, though I'm not even a php novice so I could be missing some sort of include.

**Comment by niel** [comment]
oops I meant resources/schema/data You didn't check the directories ABOVE nZEDb though

**Comment by rcketscientist** [comment]
_sigh_ Somehow /var/www/nZEDb  was 774...once users got execute (755) it was fine.  Sorry for taking your time, not sure how I botched that up.

**Comment by niel** [comment]
It's actually quite common for the nZEDb directory to be a funny set of perms.

**Comment by kimbecause** [comment]
For others that may be having this problem, it may be that new versions of mysql have "secure-file-priv" set by default that will block importing the tsv files from non-standard locations, and will throw the unhelpful "Check permissions of user" error at step 2.

To fix this you need to add

secure-file-priv = ""

to the mysqld section of my.cnf. This will allow mysql to load the files, if all the other file permissions (etc) are correct.

**Comment by ferfey** [comment]
Thanks kimbecause, adding
secure-file-priv = ""
to my.cnf fixed this issue for me.

**Comment by niel** [comment]
@kimbecause The better answer is to set that to the directory containing the TSV files. This will make it the only location that can load directly, making it more secure. This is how our new Ubuntu 16 guide will be doing it.
