### ISSUE TITLE
Not able to access parts of the site after latest dev update

### ISSUE THREAD

**Issue by richierichman** [nZEDb/nZEDb#2102]
### Expected behaviour

Be able to click on New release or browse all releases or search and get pages loading
### Actual behaviour

Web site takes a long time and eventually get _sitename_ is currently unable to handle this request.
500 
### Steps to reproduce the behaviour

updated to the latest version of the dev branch and have used composer + changed the update to now use the ./zed update nzedb process. 
I have checked all permissions but no luck. Only seems to be some of the pages not working and timing out. 
Not sure if this the wrong place for this I can raise it on the forum if need be. Any help would be greatly appreciated.

Rich

**Comment by niel** [comment]
Your reproduce steps don't give me the same problem. 
It sounds like your system is suffering high load and unable to service the request.  If you enable logging, can you see any php or web server errors to help with this?

**Comment by richierichman** [comment]
Thanks for look at the issue. Looks like when my server re-started due to a power failure Spinxsearch was not running correctly and had issues. Once I fixed spinx and got the service up it is fine now. Thanks again for all your hard work.

**Comment by richierichman** [comment]
solved closing issue (not an issues)
