### ISSUE TITLE
Bad or missing nzb directory

### ISSUE THREAD

**Issue by rcketscientist** [nZEDb/nZEDb#2103]
New install, got an error when testing `update_releases.php`:

> Error: Bad or missing nzb directory -

So I tried to set `nzbpath` in settings and no setting seems to take.  I manually edited `settings:nzbpath` (right field?) in the database and still got the error.

PHP didn't throw any errors for the admin page.  Anything else I should look into?

**Comment by niel** [comment]
There is a script .../cli/verify_permissions.php You should run this as both your normal user and your web user, to make sure that directories have correct permissions for important locations.

**Comment by rcketscientist** [comment]
I ran verify and noticed there was a commit related to smarty so I updated and needed to create the hex nzb subfolders by hand.  After that the verify was successful for both users, however I still get the same error from update_releases.php and settings don't take.

**Comment by ASympathy** [comment]
I believe I'm having this identical issue. I just manually created`/var/www/nZEDb/resources/nzb/0` - `/z` and `.../cli/verify_permissions.php` no longer gives me an error message for www-data or my primary user, but I'm still getting the `Error: Bad or missing nzb directory -` when I run `php update_releases.php 1 true`

**Comment by niel** [comment]
Is this still an issue?
