### ISSUE TITLE
Unable to launch /install on ubuntu 14.04

### ISSUE THREAD

**Issue by ASympathy** [nZEDb/nZEDb#2106]
### Expected behaviour

Website loads when I type in 127.0.0.1/install or localhost/install
### Actual behaviour

Error message "127.0.0.1 is currently unable to handle this request." "localhost is currently unable to handle this request."
### Steps to reproduce the behaviour

I was following the steps in https://github.com/nZEDb/nZEDb_Misc/blob/master/Guides/Installation/Ubuntu/Guide.md
verbatim, until I get to step 12 and it doesn't load. I receive the error message " ". I know my apache2 server works, as I was previously using Plexwatchweb (I disabled it when I was told to disable 000-default).

Please advise on more information needed.

**Comment by krypknot** [comment]
Did ya also follow the additional required steps found in the Changelog?

**Comment by ASympathy** [comment]
Likely not. Can you point me to them, as I'm not able to see something with that title. 
I do see https://github.com/nZEDb/nZEDb/wiki/Update-Guide if that's what you mean, I'll give it a go.

**Comment by Wally73** [comment]
https://github.com/nZEDb/nZEDb/blob/dev/Changelog#L31

**Comment by ASympathy** [comment]
Okay, I've installed Composer globally, then ran `sudo composer install` from `/var/www/nZEDb/`and then ran `./zed update nzedb` from `/var/www/nZEDb/` and then rebooted the machine.

I received the same error message initially, but after a couple minutes the site auto-realoaded to what I was expecting to see. Thank you for your assistance guys.

I'd suggest someone update https://github.com/nZEDb/nZEDb_Misc/blob/master/Guides/Installation/Ubuntu/Guide.md with the new composer requirements.

**Comment by niel** [comment]
New users should use 0.x branch, not the dev branch which requires a lot more skill and knowledge to maintain, particularly at the moment while in a period of transition.
