### ISSUE TITLE
Unable to loginto web site

### ISSUE THREAD

**Issue by richierichman** [nZEDb/nZEDb#2107]
### Expected behaviour

Users click on login on site and enter their username and password. Site loads giving correct access to user.
### Actual behaviour

enter correct username and password and user is re-prompted with the login box. no errors in logs. But if incorrect login entered logged in failed-login.log.
### Steps to reproduce the behaviour

 Looking at changelog "Add: New setting for ReCaptcha to switch it off. Defaults to on to prevent BC problems. This allows disabling ReCaptcha without having to remove your keys. NO UI component yet." not sure where this option is to turn off ReCaptcha. Could this be a ReCaptcha error? I did try removing my ReCaptcha keys but made no difference. Admin user also giving same behavior.

**Comment by richierichman** [comment]
Ok seems the only way to get users to log in is to get them to click on the remember me setting. When that is ticked you can log into the site. Again not sure if this is related to the ReCaptcha issue. Users can log in now if they tick the remember me check box.

**Comment by niel** [comment]
This is usually caused by browser plugins. My experience is that Privacy Badger screws with the ReCaptcha code preventing it from being displayed, which in turn causes all attempts to login to fail.

**Comment by richierichman** [comment]
I have tried on a browser without any plugins and I still have this issue. Will work if I click on remember me. I can no longer see ReCaptcha being displayed on the site is it turned off as a global thing?

**Comment by niel** [comment]
Forget about the Changelog entry about ReCaptcha setting. That's just something I added for myself to quickly disable ReCaptcha completely when testing code. The default for all installations is ON, same as it always was.
I cannot imagine how selecting "remember me" changes the behaviour, so you'll have to provide some actual information for the "Steps to reproduce this behaviour" i.e. what theme are you using (it might be connected to that one theme, so test on others). Screen shots of the login process showing the difference between remembering and not remembering might shed some light.
That's about all I can think of for now, it's very late and I should be in bed ;-)

**Comment by richierichman** [comment]
Will do mate no probs. I will grab some screens and try the other themes as well to see whats going on. Thanks for the tips and all the hard work.

**Comment by richierichman** [comment]
PR 2135 fixed my issue. closing.
