### ISSUE TITLE
[bug] Content Add/Edit page truncates carriage returns.

### ISSUE THREAD

**Issue by ghost** [nZEDb/nZEDb#2108]
When editing content via admin page the text area tuncates all formatting. In NN++ this formatting is retained and displays how it is in the mysql table.
### Expected behaviour

Keep text formatted as it's wrote. For example if this was the text box I'd have:
<.br>
Change Log:<.br>
2016-04-13: File bug report<.br>
2016-04-12: Installed nZEDb<.br>
### Actual behaviour

Change Log:<.br>2016-04-13: Filed bug report<.br>2016-04-12: Installed nZEDb<.br>
### Steps to reproduce the behaviour

Edit content in admin/content-list.php. add a few lines of text & save.

**Comment by niel** [comment]
No editing is removed. If you enter a LF character it stays in the content, however it will not be displayed by the page as HTML ignores extra white-space. If you want line-breaks you must enter the HTML break tag (</br>) as with any HTML.

**Comment by ghost** [comment]
Not sure you understand me.
How I type (Or how I manually insert to mysql)
http://pix.toile-libre.org/upload/original/1460569970.png

How it's displayed on content edit page
http://pix.toile-libre.org/upload/original/1460569887.png

The HTML break tags work fine when viewing the web page - but it's the admin page where everything is put on one line. I have quite a large content page with change logs etc and it makes it hard to manage.

**Comment by niel** [comment]
You're right, I don't understand (and still don't). I tested this with one of my repos (using dev branch) and when I entered a newline, it created a newline. When I saved that change, returned main site page to view that content the newline is ignored as expected, returning to admin => Site Settings => Content Pages => Edit - the newline is still there.
Can you describe what process you are following to get different results, please. Alternatively talk to me in IRC, might be easier and quicker.

**Comment by niel** [comment]
Closing as this has already been fixed in dev branch.
