### ISSUE TITLE
no new releases on one particular newsgroup after 0.x pull

### ISSUE THREAD

**Issue by Hobbabobba** [nZEDb/nZEDb#2109]
### Expected behaviour

new headers for group `alt.binaries.multimedia.erotica.asian` are downloaded and nzedb will find new releases on that group
### Actual behaviour

no new releases in group `alt.binaries.multimedia.erotica.asian` after 0.x pull
### Steps to reproduce the behaviour

I am using nzedb on Ubuntu 14.4 LTS. After the 0.x pull (3rd of April in my case) I don´t get any new releases on that group. My USP is cheapnews, but i tried with newshosting, too. Same problem. There is no problem with any other group.

I tried to reset and purge the group, no change.

**Comment by niel** [comment]
Did you ever get releases from this group? Nothing has changed with regard to the groups and how releases are created. The April update only contained changes to templates.

**Comment by richierichman** [comment]
I used to get a lot of release from this group. I'm on the latest dev branch and I have noticed there are no new releases coming through. Last release almost a month old.

**Comment by niel** [comment]
@Hobbabobba you say you switched to 0.x on 3rd April, have you pulled since then because it was updated on the 4th.
If you have pulled since then could you try reverting to the previous version (git reset v0.5.4) to see if this restores the group to fully functional behaviour. If it doesn't we can assume it's not the update but some other factor causing the problem. If it does we will have narrowed down the range of code that needs checking.

**Comment by Hobbabobba** [comment]
Before i got a lot of releases from the group, every day. just reverted to the previous version. Will post an update, soon.

**Comment by Hobbabobba** [comment]
After i added the group again and backfilled for 4 days, i finally see new releases. Strange: in the"Browse groups" page nzedb shows me `alt.binaries.multimedia.erotica.asian  43` (means 43 releases), but after i click on the groups name, there is no release.

**Comment by Wally73** [comment]
they are prob in other/misc or other misc/hashed

**Comment by Hobbabobba** [comment]
i checked with some releases from the last 24-48 hrs, they are not in other/misc or misc/hashed. Unfortunately I can´t not see the list of releases, that nzedb reports to be found. 
But the number of recognized releases does not increase, that is very unusual for this group.
