### ISSUE TITLE
Phpmailer and Gmail error connecting to SMTP. 

### ISSUE THREAD

**Issue by richierichman** [nZEDb/nZEDb#2111]
### Expected behaviour

Configure phpmailer settings in settings.php. send and receive emails from site.
### Actual behaviour

php error connecting to gmail smtp service. Is there any additional settings that needs to be configured to get PHP mailer to send mail via gmail? 

PHP Fatal error:  Uncaught exception 'phpmailerException' with message 'Unable to send mail. Error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting' in /var/www/nZEDb/nzedb/utility/Misc.php:683

**Comment by niel** [comment]
Have you configured the Mail settings in the settings.php file?

**Comment by niel** [comment]
Error seems pretty self explanatory. Either there is a problem with your settings, or with the ability of your machine to connect to gmail.

**Comment by richierichman** [comment]
had to enable "Access for less secure apps" in Gmail to get it to work. The later versions of PHPmailer has a  XOAUTH2 library that works with the newer Gmail authentication. Looks like the one intergated with nZEDb is slightly out dated. Close for now may need to update the version of PHPMailer to the latest version to give the abilty to use  XOAUTH2.
