### ISSUE TITLE
Misc / In Process filling up

### ISSUE THREAD

**Issue by jangrewe** [nZEDb/nZEDb#2114]
### Expected behaviour

I was expecting that the count of releases in "Misc" under "In Process" would follow about the same fluctuation as in all other categories (even if not _exactly_ the same, because of it's nature), and that over time eventually all releases would get their additional postprocessing.
### Actual behaviour

The count keeps on increasing until the "Maximum Postprocess" limit kicks in (in my case 25.000), and then only decreases after some hours, but only until updating of binaries is allowed to run again, because then it hits that limit again within a couple of minutes.

Some releases are indeed being processed, but the amount of releases being queued for additional processing (and not being additionally processed) is several times higher.
### Steps to reproduce the behaviour

tmux with the current dev branch, using "./zed update nzedb"

Monitor:
![fdkkio jpg](https://cloud.githubusercontent.com/assets/126137/14689888/8dc1d8ea-0749-11e6-8098-91119b91c815.png)

**Comment by jangrewe** [comment]
Probably caused by too much going on. Lowered threads to the minimum, except for PPA. Closing for now.

**Comment by jangrewe** [comment]
This brought relief (mark everything unprocessed and older than 4 weeks as 'definitely passworded' so that i gets remove)

```
UPDATE releases r LEFT JOIN category c ON c.ID = r.categoryID SET passwordstatus = 10 WHERE (r.passwordstatus BETWEEN -6 and -1) AND (r.haspreview = -1 AND c.disablepreview = 0) AND (r.addate < NOW() - INTERVAL 672 HOUR);
```

**Comment by jangrewe** [comment]
Updated query for current (0.7.x) schema:
```
UPDATE releases r LEFT JOIN categories c ON c.ID = r.categories_id SET passwordstatus = 10 WHERE (r.passwordstatus BETWEEN -6 and -1) AND (r.haspreview = -1 AND c.disablepreview = 0) AND (r.adddate < NOW() - INTERVAL 672 HOUR);
```

**Comment by niel** [comment]
You might want to put this query on the wiki in the section for useful queries for administrating the db.

**Comment by jangrewe** [comment]
Good idea!
