### ISSUE TITLE
[Request] Add CouchPotato Icons to GAMMA theme similar to Alpha

### ISSUE THREAD

**Issue by scottia** [nZEDb/nZEDb#2115]
Can the Trakt Icons in GAMMA be replaced with CouchPotato like the Alpha theme.  Seems better for those that use CouchPotato (like me) to manage Movie release types by adding directly to CouchPotatio.

**Comment by Wally73** [comment]
add maybe but not by replacing trakt, i do NOT use couchpotato but i do use sickrage and trakt a lot

**Comment by DariusIII** [comment]
Since when does couchpotato manage TV?

**Comment by scottia** [comment]
I also use Trakt but for the adding to nzbget but as an RSS feed.  This is just a more convenient method for me since CouchPotato monitors a release types, date and size.

I would just like the ability add them to CP like Alpha does today.

@DariusIII   CP monitors TV movies.  I will correct it, thanks.

**Comment by DariusIII** [comment]
CP is used for movies in all of the themes. I can easily add an icon for CP to Gamma.

**Comment by scottia** [comment]
That would be great.  All I was looking for @DariusIII

**Comment by scottia** [comment]
Can this be labeled enhancement, front end & request please

**Comment by scottia** [comment]
@DariusIII  Will the icon be added to Gamma soon ?

**Comment by DariusIII** [comment]
It does not work as it should, so i need to investigate the reason behind it (opens blank page and does not add anything to couchpotato).

**Comment by scottia** [comment]
Thanks for the support @DariusIII

**Comment by scottia** [comment]
CP icon doesn't appear to work.  I see the nzedb notification and the CP logs shows the movie query but its not added to CP that I can find, so it doesn't pull in a matching release.

**Comment by DariusIII** [comment]
As i don't use CP at all, i cannot completely test it. Code is same as in alpha, so it should work. Is there any error you can point me at?

**Comment by scottia** [comment]
I appreciate the help Darius !

No errrors logged.  I think its a failed API request.  Bart set it up for Alpha initially and if I switch back to Alpha, requests are added to CP and movie releases match correctly pulling them into my queue.  You actually see the Alpha requested in CP real-time vs. Gamma.

**Comment by DariusIII** [comment]
You wrote that you see the request in CP, can you paste it here?

**Comment by scottia** [comment]
I am mistaken.  I see nZEDb show the CP notification.  What I see in the CP logs are movie queries but not the release I am requesting via the CP icon.  I can provide the CP log from Alpha if that helps ?

**Comment by DariusIII** [comment]
I need logs (php_errors.log) or CP logs when you use Gamma. Log when using Alpha does  not help, unless compared to log when using Gamma.

**Comment by scottia** [comment]
I resolved it.  Movies.tpl & viewnzb.tpl don't need the a site dereferrer reference, since CP is a local application to the LAN.  Nothing to derefer that is, so the request is sent locally vs. sending the API IMDB reference as a blank title to CP.

Removing  "{$site->dereferrer_link}" from both files to your reference link after " rel=" "resolves the issue.  I found it by comparing Gamma to Alpha.

**Comment by DariusIII** [comment]
Then that is your local change, as Alpha has it:
https://github.com/nZEDb/nZEDb/blob/0.x/www/themes/Alpha/templates/viewnzb.tpl#L82

Next time please check your local changes first.

I am closing this as it is resolved.

**Comment by scottia** [comment]
I make NO local changes.  In this case I identified the issue, made the change appropriate to the Gamma files for the feature and tried providing the correction to what you added, hoping you would revise your change.  Perhaps viewnzb.tpl has never worked, I don't know since I don't ever add to CP from there.

This is from the Alpha Movies.tpl file and it does not match what you added for Gamma.  As you can see this is no dereferrer reference.  It should also be removed from viewnzb.tpl

Just trying to help

```
                        {if $cpurl != '' && $cpapi != ''}
                            <a
                                class="sendtocouch"
                                target="blackhole"
                                href="javascript:;"
                                rel="{$cpurl}/api/{$cpapi}/movie.add/?identifier=tt{$result.imdbid}&title={$result.title}"
                                name="CP{$result.imdbid}"
                                title="Add to CouchPotato"
                            ><img src="{$smarty.const.WWW_TOP}/themes/shared/img/icons/couch.png"></a>
                        {/if}
```

**Comment by b3rs3rk** [comment]
@scottia isn't wrong.  CP pushes have been broken a long time.  I have been meaning to look at it, but am looping through issues now to clear out some of the long standing shizz.

**Comment by scottia** [comment]
Can you re-open and label it as a bug @ruhllatio and review my revisions to Gamma.  It works fine w/out a dereferrer as noted.  Maybe it should work with a dereferrer but I don't see why.  I have not ever had an issue with the Alpha theme.

**Comment by b3rs3rk** [comment]
It's a different issue though.  CP Not Working with dereferrer links !== No CP Icon.  Let's open a new one and work fresh por favor.

**Comment by scottia** [comment]
writing up a new issue now.  Thanks

**Comment by DariusIII** [comment]
I admit my tone was a bit harsh. Sorry for that. As i don't use CP at all (stopped at version 2.0.0, which was bad as hell to me), i used what already is in the code and assumed it works. Sorry again.

**Comment by scottia** [comment]
No worries @DariusIII I was just confused, not offended.  Your awesome and I appreciate ya !
