### ISSUE TITLE
[Bug] Issue with populate_rt_index.php (sphinxsearch)

### ISSUE THREAD

**Issue by EDChurly** [nZEDb/nZEDb#2116]
I think there maybe a potential issue in populate_rt_index.php.

As it stands, Line 57 reads

for ($i = $minId; $i <= ($total + $max) ; $i += $max) 

With the idea being to loop through all releases and create the index, passing $max number of rows to sphinx.

$minId is the starting (or minimum) release ID in your database, and $Total is the number of releases.
The issue is, $minID is arbitrary depending on many factors. retention and so forth.  And potentially be approaching or surpassing total and $max in this case is typically a fixed number.  So you can end up looping through a subset of releases or even none at all if minID exceeds Total by enough.

I cannot see how $I itself is referenced within the loop, so a few ways to potentially fix it.

I dont post this with huge confidence, someone smarter than I should take a look?

Cheers
Lulu

**Comment by EDChurly** [comment]
Just to add, I got this working for me and sphinx seems to be working normally now across all releases.

I changed it to 
for ($i = 1; $i <= ($total + $max) ; $i += $max) 

I suspect you only need to iterate upto total also.. probably needs further review.

**Comment by Wally73** [comment]
i'm on latest dev with 10.1.13-MariaDB-1~jessie mariadb.org binary distribution no issues at all here with sphinxsearch

**Comment by EDChurly** [comment]
If you start out with Sphinx search you won't have an issue.   Its changing to sphinx later (or rebuilding post upgrade) and the fact that MinID can potentially be a large number (even greater than total so nothing is indexed at all.

**Comment by EDChurly** [comment]
This issue could have related. https://github.com/nZEDb/nZEDb/issues/1929. Hard to say but same symptoms.

**Comment by Wally73** [comment]
when  you upgrade or restart using sphinx you have to recreate the table anyway 

https://github.com/nZEDb/nZEDb/blob/0.x/Changelog#L486

**Comment by EDChurly** [comment]
The issue is not related to recreating the table or the function of sphinxsearch itself, but how populate_rt_index populates the index.   As it stands now, unless your first release ID is 1 (or close to it), it will not traverse all releases when populating due to the logic.

Maybe this will help, sorry its rather long.  This is the function as its currently written.

```
 function populate_rt($table, $max)
{
    $pdo = new DB();
    switch ($table) {
        case 'releases_rt':
            $pdo->queryDirect('SET SESSION group_concat_max_len=8192');
            $query = (
                'SELECT r.id, r.name, r.searchname, r.fromname, IFNULL(GROUP_CONCAT(rf.name SEPARATOR " "),"") filename
                FROM releases r
                LEFT JOIN release_files rf ON(r.id=rf.releaseid)
                WHERE r.id > %d
                GROUP BY r.id
                ORDER BY r.id ASC
                LIMIT %d'
            );
            $rtvalues = '(id, name, searchname, fromname, filename)';
            $totals = $pdo->queryOneRow("SELECT COUNT(id) AS c, MIN(id) AS min FROM releases");
            if (!$totals) {
                exit("Could not get database information for releases table.\n");
            }
            $total = $totals["c"];
```

 Total is total releases

```
            $minId = $totals["min"];
```

This is min(id) or the minimum release ID, set from this query above
$totals = $pdo->queryOneRow("SELECT COUNT(id) AS c, MIN(id) AS min FROM releases");

```
            break;
        default:
            exit();
    }
    $sphinx = new SphinxSearch();
    $string = sprintf('REPLACE INTO %s %s VALUES ', $table, $rtvalues);
    $lastId = $minId - 1;
    echo "[Starting to populate sphinx RT index $table with $total releases.]\n";

```

```
    for ($i = $minId; $i <= ($total + $max) ; $i += $max) {
```

This is the problem code.

The intention here is to iterate over all releases, and passing upto $max rows to sphinx to populate the index.

If you had a index of 4 million releases that you generated over two years, 
and then decided to set retention to 1 year, your minID would be approx 2 million, 
and Total would also be about 2Million.  
You would only actually pass a subset of releases to the index

I think it should be changed to
for ($i = 1; $i <= $total; $i += $max) {
as $i itself is not referenced within the loop.

The rest of the function is fine

```
        $rows = $pdo->queryDirect(sprintf($query, $lastId, $max));
        if (!$rows) {
            continue;
        }
        $tempString = '';
        foreach ($rows as $row) {
            if ($row["id"] > $lastId) {
                $lastId = $row["id"];
            }
            switch ($table) {
                case 'releases_rt':
                    $tempString .= sprintf(
                        '(%d,%s,%s,%s,%s),',
                        $row['id'],
                        $sphinx->sphinxQL->escapeString($row['name']),
                        $sphinx->sphinxQL->escapeString($row['searchname']),
                        $sphinx->sphinxQL->escapeString($row['fromname']),
                        $sphinx->sphinxQL->escapeString($row['filename'])
                    );
                    break;
            }
        }
        if (!$tempString) {
            continue;
        }
        $sphinx->sphinxQL->queryExec($string . rtrim($tempString, ','));
        echo ".";
    }
    echo "\n[Done]\n";
}
```

**Comment by Bart39** [comment]
this is a confirmed issue as lulunzb said - working on it
