### ISSUE TITLE
deleting releases with completion < x does not work as expected

### ISSUE THREAD

**Issue by Bart39** [nZEDb/nZEDb#2123]
### Expected behaviour

setting completion to a value < 100 should delete releases that have completion less than the value
### Actual behaviour

default completion is being set to 0 and hence ignored (as 0 is deemed potentially unprocessed wrongly)
### Steps to reproduce the behaviour

set completion to delete to a value < 100 and those at 0 (default value in db) will be ignored

**Comment by kevinlekiller** [comment]
#2122

**Comment by Bart39** [comment]
need to correct schema and reset current values for genuine unprocessed releases
ensure that new completion values are stored as float and amend templates accordingly to round up displayed values

**Comment by DariusIII** [comment]
is this still an issue? I have checked and when completion is set below 100 (tested with 95% and 97%) there are no releases below that completion in releases table.
