### ISSUE TITLE
nzeds shows no releases in one group

### ISSUE THREAD

**Issue by Hobbabobba** [nZEDb/nZEDb#2124]
nzedbs shows x releases in group `a.b.multimedia.erotica.asian` (browse groups), but when i click on the groups name, i can´t see any release.
i tried a `git pull`, but the problem is still there.

**Comment by Bart39** [comment]
are they waiting for password checks and you have site admin settings configured to only show confirmed non password releases ?

they are showing for me fine

**Comment by Hobbabobba** [comment]
great idea, but i checked and the settings are ok.

nzedb shows me, that there are 28 releases in this group (from the Browse - Groups menu). After i click on the groups name, it doesn´t show any release.

Update: since nZEDb is running in a VM, i used a snapshot from march, and everything is working fine.

**Comment by Hobbabobba** [comment]
updated yesterday to the new version (incl. Composer) and everything works fine
