### ISSUE TITLE
Strange results with Sphinx search

### ISSUE THREAD

**Issue by EDChurly** [nZEDb/nZEDb#2129]
Current on 0.x branch.

Gone through all the steps to rebuild a fresh Sphinxsearch index (as per Release Notes)

Search for a release abc using catagory "ALL" takes approx 10 seconds or so and finds nothing.
Search for same release under catagory "TV" for example is instant and returns lots.

Any suggestions to what maybe going on? Do others see similar behaviour?

The host is not stressed, everything is otherwise normal.

**Comment by Wally73** [comment]
name example please

**Comment by EDChurly** [comment]
ok - for example Survivor - Search in TV - returns many results - search under catagory "All" seems to time out after 10 seconds and returns nothing...

**Comment by Wally73** [comment]
![survivor all search](https://cloud.githubusercontent.com/assets/2582289/15019415/408e6c70-121e-11e6-8cf1-ddc23aa2fe3c.png)
my survivor on keyword search all result 
same result when i search in TV

**Comment by EDChurly** [comment]
Only other thing to note, searchd seems to be using alot of CPU.   Thats what I see if I select catagory TV, but not All..

**Comment by EDChurly** [comment]
Sphinx storage engine 2.2.10-release  and percona 5.6.28-76.1 fwiw

**Comment by Wally73** [comment]
mm i use 10.1.13-MariaDB-1~jessie mariadb.org binary distribution

**Comment by EDChurly** [comment]
Think this may relate.

![image](https://cloud.githubusercontent.com/assets/15647838/15019979/5966424a-125f-11e6-8db4-23a8a0eb3509.png)

Only 1 release on other -> misc and none in hashed... doesnt look correct.   I retain other for over 48hrs.

**Comment by EDChurly** [comment]
Funnily enough, purging out all the crap in Misc -> Other has fixed it.   Unfortunately I cant really identify which release there caused it, but pleased its working again.

**Comment by Wally73** [comment]
mm computers can be strange but if its solved you can close this issue

**Comment by EDChurly** [comment]
Ok - thanks for your help!
