### ISSUE TITLE
Fatal PHP errors since git pull

### ISSUE THREAD

**Issue by ialexpw** [nZEDb/nZEDb#2131]
### Expected behaviour

After updating no PHP error...
### Actual behaviour

I used git pull to update and now facing PHP fatal errors, on the 0.x branch as below;

Warning: require_once(app/libraries/autoload.php): failed to open stream: No such file or directory in /var/www/nZEDb/autoloader.php on line 39

Fatal error: require_once(): Failed opening required 'app/libraries/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/nZEDb/autoloader.php on line 39
### Steps to reproduce the behaviour

I just did a git pull this morning and it started doing it

Managed to revert back, but would be nice to know what was happening :-)

Thanks!

**Comment by Wally73** [comment]
pretty sure you haven't read the ReleaseNotes

https://github.com/nZEDb/nZEDb/blob/0.x/ReleaseNotes
