### ISSUE TITLE
Fix zed update script on FreeBSD

### ISSUE THREAD

**Issue by josh4trunks** [nZEDb/nZEDb#2132]
### Expected behaviour

`./zed update nzedb`
should update nzedb and patch database
### Actual behaviour

`./zed: not found`
Fixed by using the standard `#!/bin/sh` instead of the less portable `#!/bin/bash`

After that I get the error
`/usr/bin/git: not found`
But, this is an issue with **kbjr/Git.php** so I'll try getting this issue resolved upstream.
### Steps to reproduce the behaviour

See expected behavior

**Comment by josh4trunks** [comment]
Related issue, see https://github.com/kbjr/Git.php/issues/47

**Comment by Wally73** [comment]
create a symlink then as you're using a strange OS

**Comment by niel** [comment]
the other workaround is to change the shebang lines to point at /usr/local/bin/bash I think is the location

**Comment by josh4trunks** [comment]
@Wally73 actually doesn't work that well in my situation, lol. the operating system is jail, and the operating system folders are readonly from its perspective. I could change this from the host thought, but in this case I dont even have bash installed.

@niel I know that would, work to but I'd prefer to keep the application as stock as possible.
what wrong with being as portable as possible like the script this points to `libraries/lithium/console/li3` which uses the standard #!/bin/sh

**Comment by niel** [comment]
Some of our scripts use bash specific syntax, and bash is the default shell on our reference install (Ubuntu LTS).
We try to keep things as portable as possible, but it will always be impossible to be totally portable. That's the nature of different OSes.

**Comment by josh4trunks** [comment]
in this case all the script does is call another POSIX script. it doesn't need bash specifically so why can't we require the standard 'sh', then a vendor specific bash?

I noticed I do have bash installed, I think for the tmux script I run, but I've survived thus far without requiring the /bin/bash location.

**Comment by josh4trunks** [comment]
I guess, I don't see a reason to use bash, since changing things to sh only fixes thinga/, and won't break anything.

**Comment by niel** [comment]
Agreed, and I'll change it in dev.

**Comment by josh4trunks** [comment]
thanks.
lol, its been a lot of investigating to keep my freebsd install running when there's a lot less of us, but things are running great thus far. thanks for all the work

**Comment by niel** [comment]
I'm intending to look at installing on FreeNAS when they release 10.0. I don't see a point for us to spend time on 9.3/9.10 when it will be superceded shortly.

**Comment by josh4trunks** [comment]
It should work the same on either, FreeNAS9.10 uses a FreeBSD10 kernel. I hate the naming!
And newly installed jail would use a FreeBSD10 userland so there would literally be no difference between 9.10 and 10.

This should work, though I haven't needed to install/ test install recently.
https://github.com/nZEDb/nZEDb/wiki/Install-Guide:-FreeNAS-%28FreeBSD%29

####

If others are interested I could also add my init script to run the tmux script. I'm not sure if tmux is currently recommend way to do your background tasks.
This would be saved as /usr/local/etc/rc.d/nzedb-tmux and would start at boot

```
#!/bin/sh
# PROVIDE: nzedb-tmux
# REQUIRE: LOGIN
# KEYWORD: shutdown

. /etc/rc.subr
name="nzedb_tmux"
rcvar="${name}_enable"
load_rc_config $name

: ${nzedb_tmux_enable:="NO"}
: ${nzedb_tmux_user:="www"}
: ${nzedb_tmux_group:="www"}
: ${nzedb_tmux_dir:="/usr/local/www/nzedb"}
export TERM="xterm"
tmux_socket="/tmp/tmux-$(id -u ${nzedb_tmux_user})/default"

nzedb_tmux_chdir="${nzedb_tmux_dir}/misc/update/nix/tmux"
command="/usr/sbin/daemon"
command_args="-f /usr/local/bin/php -f start.php"
procname="/usr/local/bin/tmux"

start_precmd="nzedb_tmux_prestart"
nzedb_tmux_prestart() {
    rm ${tmux_socket} &
    export SHELL="/bin/sh"
}
extra_commands="console"
console_cmd="nzedb_tmux_console"
nzedb_tmux_console() {
    ${procname} -S ${tmux_socket} attach -t nZEDb
}

run_rc_command "$1"
```

Also here's a little trick I used to get the 'ss' stuff working even though FreeBSD doesn't have that. I save this as a script named /usr/local/bin/ss

```
exec 2> /dev/null
netstat -n | grep tcp4 | sed -e "s/\(^[[:alpha:]]*\)/\1 /"
```

**Comment by niel** [comment]
According to something I saw or  read, new jails on 9.10 use the older 9.3 jails if you have anything previously installed. There is no way currently to upgrade them to the FreeBSD 10.0 versions.
That's my reason for waiting.

**Comment by josh4trunks** [comment]
For standard jail, in my testing newly jails will download the FreeBSD 10 template.
For plugin jails, they will continue to use the specific plugin jail template, which was based on FreeBSD9.3

I test this alot, cause I'm in charge of most of the plugins ;]
