### ISSUE TITLE
Can't update nZEDb when specifying a custom port / unix_socket

### ISSUE THREAD

**Issue by josh4trunks** [nZEDb/nZEDb#2133]
### Expected behaviour

`./zed update nzedb`
should update the database
### Actual behaviour

```
Unable to connect to host `localhost`.
```
### Steps to reproduce the behaviour

```
define('DB_HOST', 'localhost');
define('DB_PORT', '');
define('DB_SOCKET', '/mnt/mysql/mysql.sock');
```

**Comment by josh4trunks** [comment]
There's at least 2 issues here.
In nZEDb, `app/config/bootstrap/connections.php` should have the below line added
`'unix_socket' => DB_SOCKET,`

In lithium, the following needs some work. It doesn't even use the $port they say to use.
https://github.com/UnionOfRAD/lithium/blob/master/data/source/database/adapter/MySql.php#L159-163
I'll work on getting lithium fixed and post here once it's done so we can pull in the fixes.

**Comment by niel** [comment]
If you set the DB_HOST to '' it should work.
Oops, should have mentioned it is changed in dev, where we use 'socket' => DB_SOCKET,.

**Comment by josh4trunks** [comment]
sounds good! actually looking at lithium's code, it does respect the passed socket, or even port. I'll get this fixed upstream.

**Comment by niel** [comment]
you should be aware we're using the 1.1 branch NOT master.

**Comment by josh4trunks** [comment]
sounds good, I'll make sure it gets fixed there.

**Comment by josh4trunks** [comment]
Here's my PR for lithium's database handling.
https://github.com/UnionOfRAD/lithium/pull/1274

Once this gets merged, nZEDb won't need this logic since this would be handled in lithium. nZEDb can just pass the parameters directly
https://github.com/nZEDb/nZEDb/blob/dev/app/config/bootstrap/connections.php#L94-98

**Comment by niel** [comment]
Thanks for the update.

**Comment by josh4trunks** [comment]
@niel  UnionOfRAD/lithium ended up handling host/port/socket different than we expected.
They instead expect everything passed in the host variable like the below. See https://github.com/UnionOfRAD/lithium/blob/1.1/data/source/database/adapter/MySql.php#L173-190 

```
host=/path/to/socket
host=localhost
host=HOSTNAME:PORT
```

If needed I can submit a PR for the changes needed in https://github.com/nZEDb/nZEDb/blob/0.x/app/config/bootstrap/connections.php

Also related, how would an admin go about having their lithium updated to the latest revision of the v1.1 branch?
Thanks

**Comment by niel** [comment]
Yeah, I saw the update they put in. I've already fixed this in dev to work as expected now.

As for updating the libraries, you don't. We do that as and when we think it appropriate, and merge that into the composer configuration so that it knows what versions of the libraries to fetch.

**Comment by josh4trunks** [comment]
awesome, I'll wait for the update, thanks!

https://github.com/nZEDb/nZEDb/blob/41762551e7182ff1ace16ba42591a1c73be525d7/app/config/bootstrap/connections.php#L94
Looks like you don't include DB_PORT in **host**, so admins couldn't specify anything but the default port.
Also you no longer need to pass **port** or **socket** since these don't mean anything to lithium.
