### ISSUE TITLE
Column not found 1054 Unknown column 'releaseid' in 'field list'

### ISSUE THREAD

**Issue by moloquin** [nZEDb/nZEDb#2140]
### Expected behaviour

Create releases as normal.
### Actual behaviour

Releases are not created.
### Steps to reproduce the behaviour

Updated to the latest dev this AM using ./zed update nzedb and running into this error during the release creation phase in tmux.

Column not found 1054 Unknown column 'releaseid' in 'field list'

Running Spec:

[nZEDb]# php -v
PHP 5.5.34 (cli) (built: Apr  2 2016 10:11:45) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
[nZEDb]# httpd -version
Server version: Apache/2.2.15 (Unix)
Server built:   Mar 22 2016 19:03:53
[nZEDb]# cat /etc/redhat-release 
CentOS release 6.7 (Final)
[root@CentosIndexer nZEDb]# mysql --version
mysql  Ver 14.14 Distrib 5.6.29, for Linux (x86_64) using  EditLine wrapper

**Comment by Wally73** [comment]
yeah all ppl on dev which has upgraded today have the same issue (is already known on IRC)

**Comment by moloquin** [comment]
Ok.  Thanks for the heads up.  Will sit and wait for an update.

**Comment by DariusIII** [comment]
Triggers need to be updated.

**Comment by moloquin** [comment]
Looks like the update got it.  Thanks!
