### ISSUE TITLE
[Bug] CouchPotato Not Working with dereferrer links !== No CP Icon

### ISSUE THREAD

**Issue by scottia** [nZEDb/nZEDb#2141]
For @ruhllatio review, In reference to closed request #2115 
### Expected behaviour

If site settings dereferrer link specified, CP Icon should be available in all themes.  Works with Alpha theme but not others.
### Actual behaviour

No CP Icon with dereferrer specified in admin / site settings with GAMMA theme selected.
### Steps to reproduce the behaviour

Reviewing Alpha Movies.tpl against Gamma theme as follows shows the CP Icon and functionally works correctly with CP for release adds and Icon as seen under movie poster image.

```
                    {if $cpurl != '' && $cpapi != ''}
                        <a
                            class="sendtocouch"
                            target="blackhole"
                            href="javascript:;"
                            rel="{$cpurl}/api/{$cpapi}/movie.add/?identifier=tt{$result.imdbid}&title={$result.title}"
                            name="CP{$result.imdbid}"
                            title="Add to CouchPotato"
                        ><img src="{$smarty.const.WWW_TOP}/themes/shared/img/icons/couch.png"></a>
                    {/if}
```

Gama's Movie.tpl code with derefferer does not, as shown below

```
                                {if !empty($cpurl) && !empty($cpapi)}
                                    <li>
                                        <a class="sendtocouch fa fa-bed" target="blackhole" href="javascript:;" rel="{$site->dereferrer_link}{$cpurl}/api/{$cpapi}/movie.add/?identifier=tt{$result.imdbid}&title={$result.title}" name="CP{$result.imdbid}" title="Add to CouchPotato"></a>
                                    </li>
                                {/if}
```

**Comment by DariusIII** [comment]
I think that only wrong thing is using derefferer links for CP. Those should be removed, as they actualy re-route your requests, which, in my understanding, is the cause of problems. When i gave it another thought, derefferer links and CP cannot work, due to the nature of doing dereffering, as you anyway send movie to your own instance of CP. We just need to remove those from CP integration.

**Comment by b3rs3rk** [comment]
@DariusIII Agree completely.  De-ref is for sending user requests to outside sources to protect the indexer.

**Comment by scottia** [comment]
Sending to CP not working in any theme now, at least for me.  I see nZEDb stating move added to CP but no query ever shows in the CP logs and the release is not added to "Wanted" in CP for proper searching.  It doesn't appear to send the release query from nZEDb to CP.

I tried with both a site De-ref and without with the same result.  Nothing ever added to CP.

Not sure why the CP icon is on each release when CP searches for the best quality.  Better to have the CP Icon as part of the Poster so it can be clicked once per release as it was previously on Alpha.

**Comment by DariusIII** [comment]
I have tested it, @ruhllatio has tested it and it works. @niel tested it before on Alpha, and it did not work for him, so i wonder how did it work for you?

**Comment by DariusIII** [comment]
Just tested on my local install and it works.

**Comment by scottia** [comment]
Not sure, it worked prior to #2148 on Gamma and Alpha where I tested it.  Nothing is ever sent to CP that I can see in my logs.  Do you use a De-ref in both nZEDb and CP ?

**Comment by DariusIII** [comment]
No de-ref in nZEDb

**Comment by DariusIII** [comment]
As far as i know, it never worked on Gamma.

**Comment by scottia** [comment]
Working in Gamma from the fix you provided here https://github.com/nZEDb/nZEDb/commit/8ef6065b132c7dd64a52bfeabf3cc47552f5db98

**Comment by b3rs3rk** [comment]
@scottia - yeah but that was chincy JavaScript.  The new way is better and fits more with what we did with Sab/NZBGet.  The method should work and should be easier to diagnose with some var_dumping/using the browser's developer console.

**Comment by scottia** [comment]
I have reset both API keys and restarted each system.  Seemed to have done the trick partially.  For me its very random results, meaning any movie selected should be added to CPs "Wanted" list if not available but seems to only pull the Movie if it is available in nZEDb but even that does not occur 100% of the time.

I believe this is something I have to work out on my own.  This can be closed if needed.

Thank you all so much for looking into it and re-factoring the features.  Much appreciated.

**Comment by Bart39** [comment]
It works from movie view but not from upcoming / theatres.
Ruhllatio is working on it

**Comment by DariusIII** [comment]
CP expects imdbid as main and title as optional item in its search. I will look into the issue later, as soon as my kids go to bed.

**Comment by scottia** [comment]
i keep seeing this in CP now after the latest push.  Nothing gets added.

05-17 20:16:37 ERROR
[to.core.media.movie._base] Can't add movie without imdb identifier.

**Comment by niel** [comment]
@scottia yeah that's known about lastest push. Darius/Ruhllatio will be dealing with it tomorrow

**Comment by scottia** [comment]
I just clicked through lots of movies and was able to send to CP for each one and pull a different release based on quality for each release I removed.  Everything working great!  Thanks again.
