### ISSUE TITLE
Smarty Templates

### ISSUE THREAD

**Issue by brando56894** [nZEDb/nZEDb#2142]
I'm reinstalling and revising the installation guide for Arch Linux (I also plan on creating a PKGBUILD) and I ran into a small snag, I'm missing the smarty templates folder. Was it removed or do I need to generate them somehow?

nZEDb/libs/smarty/templates_c/ is the folder that's missing.

**Comment by Wally73** [comment]
since the lithium/composer move its in /resources/smarty/templates_c

**Comment by brando56894** [comment]
Thanks.
