### ISSUE TITLE
Can't Save Settings

### ISSUE THREAD

**Issue by brando56894** [nZEDb/nZEDb#2145]
### Expected behaviour

Settings will be saved when you click "Save Site Settings"
### Actual behaviour

Nothing changed in a text filed is changed
### Steps to reproduce the behaviour

Go to the Admin Hangout and then site settings, and try to change something.

I just saw that someone posted an issue about this a week ago and that it was supposedly fixed, but that person was using Ubuntu with Apache and PHP 5.6, whereas I'm Using Arch with Nginx and PHP 7. There aren't any errors from PHP or nginx regarding why this is happening. /srv/http/nZEDb is owned by http:http and everything is set to 777. 

It can access the database since it has the tables populated, but something seems to be causing problems. Just to be sure I just logged into the database as my nzedb user and it let me in without issue.

**Comment by niel** [comment]
does your settings table exist and is it populated?

**Comment by brando56894** [comment]
Yep! Just for the hell of it I opened up PhpMyAdmin and opened the monitor to watch for active connections and when it was flat I saved my setting and saw a spike in traffic so it's obviously contacting the database.

Here's my settings table. I was able to change the tmp unrar path once (hence /tmp/unrar) but now everything seems locked.

[settings.pdf](https://github.com/nZEDb/nZEDb/files/262135/settings.pdf)

**Comment by niel** [comment]
First, this isn't the same as issue #2104 where the settings tables didn't have most of its data.
It won't save if any of the fields contain bad data. Try changing only a single value, like the template used by default and see it will save that change.

**Comment by brando56894** [comment]
On the site itself I tried to change from 'Alpha' to 'Charisma' and it didn't save.

**Comment by niel** [comment]
ok, what install guide did you follow?

**Comment by brando56894** [comment]
The Arch Guide on here, I was updating it as I went along, not much needed to be updated. I could delete the database and attempt a reinstall. No loss since I have nothing setup.

**Comment by niel** [comment]
Did you follow the 'Install nZEDb' instructions verbatim?

**Comment by brando56894** [comment]
Yep.

**Comment by niel** [comment]
that'll be the problem then. The composer instructions there are not our supported method. See the 'Install Composer' page.

**Comment by brando56894** [comment]
Ah ok I see the difference now, and I actually remember doing this before when I installed this a while ago. I'll setup everything again and when I know it works I'll close this, then update the installation instructions. Thanks!

**Comment by brando56894** [comment]
Yup, everything works.
