### ISSUE TITLE
No Audio Artist / Album only Title in Gamma Audio cover view

### ISSUE THREAD

**Issue by scottia** [nZEDb/nZEDb#2149]
(Correct) Alpha theme shows Album Artist and Album in Audio cover view
![image](https://cloud.githubusercontent.com/assets/5298748/15320178/b9993016-1bf4-11e6-994c-6ef8eda43041.png)

(Issue) Gamma theme shows only Album name / No Artist for Title
![image](https://cloud.githubusercontent.com/assets/5298748/15320231/03483752-1bf5-11e6-8bb8-12d77093dd81.png)

**Comment by DariusIII** [comment]
Not quite a BUG, but alright.

**Comment by scottia** [comment]
Wasn't sure or if affected search somehow.  Changed the Title

**Comment by scottia** [comment]
Perfect, Thank you !
