### ISSUE TITLE
Tmux panes die and don't restart after SQL has restarted.

### ISSUE THREAD

**Issue by Sweepr** [nZEDb/nZEDb#2152]
I noticed that the Tmux panels report "pane is dead" and do not restart after the SQL has restarted

I have to manually tmux kill-server and restart the tmux scripts.

How to resolve this issue?

Script to check if tmux is running is working, because the PID exists, but the pane's are dead..

**Comment by DariusIII** [comment]
You are doing it wrong. You need to stop tmux scripts first, kill tmux session and then restart mysql.
By restarting mysql while tmux is running, you have a 90% chance to kill your database, as scripts controlled by tmux read and write to your db right in the middle of your server restart.

**Comment by Sweepr** [comment]
Thank you, i'm aware of that, but having MySQL update automaticly using yum update -y via cron is not an option then as it restarts inbetween.

**Comment by Bart39** [comment]
you should NEVER update mysql automatically while you're running zed - as Darius said you can severely corrupt your database like that

**Comment by kevinlekiller** [comment]
You would need to set it up as a systemd service, with a depend on mysql.
