### ISSUE TITLE
Ircscraper not updating PreDB details

### ISSUE THREAD

**Issue by dilbaggins** [nZEDb/nZEDb#2157]
### Expected behaviour

expecting Predb to be updated
### Actual behaviour

no titles being scraped from IRC
### Steps to reproduce the behaviour

after updating to the latest (see below) can no longer see updates in tmux PreDB tab.  i tested ircscraper and login and server details are correct and getting output there.

Version Detail
Hash: 738b2ba020526ba78a9ce6353d18481aa483dd59
XML version: 0.0.0
Git version: v0.6.0-RC6

Looking up SQL patch version(s)
XML version: 442
No host configured.

php -v :  PHP 5.6.22-3+donate.sury.org~trusty+1 (cli)
php -m

**Comment by schwickster** [comment]
Same problem however I am running on an older version (version 0.5.1, will be updating soon once the next release is stable).

Connecting to IRC directly (toronto.on.ca.synirc.net:6697 and channel nZEDbPRE) I do see predb stuff being posted.

PHP 5.6.14 (cli) (built: Oct  2 2015 07:11:29) 
git version 2.6.1

Update: Seems it's fixed now. Bot is spamming predb stuff and on my pre-db page I see updates now.

**Comment by dilbaggins** [comment]
closing as bot is up...

**Comment by Wally73** [comment]
My harddrive broke so that is why 

at the moment someone else runs the scrapebots (for the time being)

**Comment by dilbaggins** [comment]
let me know if you need a backup.  glad to help out
