### ISSUE TITLE
Performance Issues during TMUX Sequential  (think PEAR is not correct version) / Stalling on the job run

### ISSUE THREAD

**Issue by dilbaggins** [nZEDb/nZEDb#2160]
### Expected behaviour

No Issues during binaries or other tmux script runs.  now i have to kill script for it to progress to releases.
### Actual behaviour

during binaries download getting a bunch of PEAR issues  for socket connections to both providers that wasnt present before. (mcrypt etc)
### Steps to reproduce the behaviour

I updated to PHP 5.6 after composer update and .nzedb update all (because it required an updated mcrypt extension)  i then ran pear update as it was complaining it required a new PEAR.

see attached screenshot for my PHP versions. https://snag.gy/C0Byjq.jpg

**Comment by dilbaggins** [comment]
Provider was the issue, however id still like someone to validate if the php versions (pear) look ok.

**Comment by niel** [comment]
I see you have both php5 and php5.6 installed. That might be a problem. If you're using the andrej PPA, then the php5 version is no long needed. His changes to using the 5.x format didn't remove the older install apparently. PEAR is usually specific to the PHP distribution, i.e. the same person packages them so they fit together.

**Comment by dilbaggins** [comment]
thanks @niel ,  is there a quick command to remove the old version and get rid of the clutter?

**Comment by niel** [comment]
personally i would remove them all (5.5 and 5.6 stuff too) then just install the ones you need

apt-get remove php5\* 
to remove most of what you have listed, or

apt-get remove php*
to get everything.
