### ISSUE TITLE
PHP ERROR via API Calls

### ISSUE THREAD

**Issue by tonymorella** [nZEDb/nZEDb#2163]
Did an update from DEV 434 to 444 and starting getting following from API calls only:

2016/06/05 18:56:47 [error] 18587#18587: *108 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'Exception' with message 'Failed to open versions XML file '/var/www/nZEDb/build/nzedb.xml'' in /var/www/nZEDb/nzedb/utility/Versions.php:275
Stack trace:
#0 /var/www/nZEDb/nzedb/utility/Versions.php(84): nzedb\utility\Versions->getValidVersionsFile()
#1 /var/www/nZEDb/nzedb/http/Capabilities.php(126): nzedb\utility\Versions->__construct()
#2 /var/www/nZEDb/nzedb/http/Capabilities.php(79): nzedb\http\Capabilities->getForMenu()
#3 /var/www/nZEDb/www/pages/api.php(182): nzedb\http\Capabilities->output(Array, Array, true, 'api')
#4 /var/www/nZEDb/www/index.php(73): include('/var/www/nZEDb/...')
#5 {main}

  thrown in /var/www/nZEDb/nzedb/utility/Versions.php on line 275" while reading response header from upstream, client: 10.220.10.37, server: nas, request: "GET /api?t=tvsearch&cat=5030,5040&extended=1&apikey=<redacted>&offset=0&limit=100 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "10.220.10.21:5058"

 I have a backup of the install, when I move back to it the error does not happen using the same DB, so must be something with the new code??
Did an update from DEV 434 to 444 and starting getting following from API calls only:

2016/06/05 18:56:47 [error] 18587#18587: *108 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'Exception' with message 'Failed to open versions XML file '/var/www/nZEDb/build/nzedb.xml'' in /var/www/nZEDb/nzedb/utility/Versions.php:275
Stack trace:
#0 /var/www/nZEDb/nzedb/utility/Versions.php(84): nzedb\utility\Versions->getValidVersionsFile()
#1 /var/www/nZEDb/nzedb/http/Capabilities.php(126): nzedb\utility\Versions->__construct()
#2 /var/www/nZEDb/nzedb/http/Capabilities.php(79): nzedb\http\Capabilities->getForMenu()
#3 /var/www/nZEDb/www/pages/api.php(182): nzedb\http\Capabilities->output(Array, Array, true, 'api')
#4 /var/www/nZEDb/www/index.php(73): include('/var/www/nZEDb/...')
#5 {main}

  thrown in /var/www/nZEDb/nzedb/utility/Versions.php on line 275" while reading response header from upstream, client: 10.220.10.37, server: nas, request: "GET /api?t=tvsearch&cat=5030,5040&extended=1&apikey=<redacted>&offset=0&limit=100 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "10.220.10.21:5058"

 I have a backup of the install, when I move back to it the error does not happen using the same DB, so must be something with the new code??

**Comment by b3rs3rk** [comment]
Plenty of us are running current dev and aren't seeing any issues with this.  When you're at current dev commit does that file exist and look semi-correct?  /var/www/nZEDb/build/nzedb.xml.  Might want to pastebin the contents and share the link here.

**Comment by tonymorella** [comment]
Figure out what was going on, I updated the PPA for PHP to ppa:ondrej/php which installed PHP7 which caused issues.  Removed PHP7, went back to the PPA and reinstalled PHP56 which fix the issues.
