### ISSUE TITLE
Gamma theme: send to queue

### ISSUE THREAD

**Issue by whiskerface** [nZEDb/nZEDb#2166]
Using the Gamma theme and configured with nzbget as the 'queue type'. The send to queue icon seemingly does nothing. 

Chrome' dev console prints this error: 
`Uncaught TypeError: Cannot read property 'substring' of undefined    utils.js:199`
### Steps to reproduce the behaviour
1. Theme set to Gamma
2. Configure nzbget queue type
3. Send to queue goes 'meh'

**Comment by Wally73** [comment]
Idem with Gamma on latest dev (and with sabnzb+ configured)

**Comment by whiskerface** [comment]
Seems the send to cart/download basket icon doesn't do much either. And yields the same error in the chrome dev console.

**Comment by DariusIII** [comment]
Working on it.
