### ISSUE TITLE
TV API returning results when the ID does not match any series

### ISSUE THREAD

**Issue by ialexpw** [nZEDb/nZEDb#2173]
### Expected behaviour

For the tv series API to return nothing.
### Actual behaviour

Returns the latest shows (unrelated of the search)
### Steps to reproduce the behaviour

Use the API like:

https://nnn.com/api?t=tvsearch&tvdbid=999999&limit=5

The ID does not match, but it returns results - this is on Debian 8 64bit, running nZEDb 0.x using composer - just updated to the latest a few days back and had someone notice this.

**Comment by Wally73** [comment]
on dev it returns nothing as it should

**Comment by ialexpw** [comment]
Alright thanks, I'll move over to dev
