### ISSUE TITLE
updating with new nzbs is failing after upgrade to Ubunti 16.04 with php7

### ISSUE THREAD

**Issue by Netfreak99** [nZEDb/nZEDb#2176]
### Actual behaviour

14-Jun-2016 16:16:28 Europe/Amsterdam] PHP Warning:  preg_match(): Compilation failed: unknown property name after \P or \p at offset 132 in /var/www/nZEDb/nzedb/Binaries.php on line 1388
### Steps to reproduce the behaviour

And this with every binaries update.
I am using mysql 5.7 and php7.0, the LTS default.

**Comment by DariusIII** [comment]
You most likely have a bad blacklist regex. Disable them and then look at errors.

**Comment by OliverLeitner** [comment]
i dont know about mysql 5.7, but id be running php7 for the cli stuff, and that works just fine. the only thing id have additionally added is ondrej's ppa: ppa:ondrej/php (thanks guys for the link to the "newer" ppa btw...)

id be using mariadb 10.2: https://downloads.mariadb.org/mariadb/repositories/#mirror=mirrorba&distro=Ubuntu&distro_release=xenial--ubuntu_xenial&version=10.2

allthough for anyone else id recommend getting the 10.1 version or a current stable of percona if you wanna run this. 10.2 is just me being the freak that id be. oracle still has troubles catching up on features, and if im not mistaken, the nzedb ubuntu howto specifically features percona server (at least in the wiki, if thats changed again... please let us know).

however, dariusiii might be right on the regular expressions blacklist, as theres the preg_match call in your error message coming from binary processing "Binaries.php".

**Comment by Bart39** [comment]
It's nothing to do with MySQL or php versions - it's as Darius said, you have a bad blacklist regex

**Comment by Netfreak99** [comment]
Yes it is correct, some bad blacklist rules are now disabled.
