### ISSUE TITLE
Gamma theme multi-select download only grabbing 1 nzb

### ISSUE THREAD

**Issue by ghost** [nZEDb/nZEDb#2178]
### Expected behaviour

Select multiple releases, download them all in one zip file
### Actual behaviour

Select multiple releases, download last one selected as a zip file
### Steps to reproduce the behaviour

List view in Gamma (cover view seems ok)
Select Multiple releases and use the multi operations download button

**Comment by DariusIII** [comment]
Tested on 2 indexers and both work just fine.

**Comment by DariusIII** [comment]
Tried on yours, no go. Check your logs, problem is most likely local.

**Comment by ghost** [comment]
Yes it was, thanks.
