### ISSUE TITLE
api tvsearch not respecting tvdbid

### ISSUE THREAD

**Issue by ghost** [nZEDb/nZEDb#2181]
### Expected behaviour

www.site.com/api?t=tvsearch&tvdbid=310528

to return results of tvdbid 310528
### Actual behaviour

returns all sorts of shows

**Comment by DariusIII** [comment]
As far as i see it is working ok. Even on yours. That tvdbid stuff are just badly matched releases on your end. With different tvdbids returned shows are fine.

**Comment by ghost** [comment]
It seems if there are no results for tvdb id then it spits out random crap instead of 0 results.

Any idea why that show is not getting matched up? If you search manually for it there are results.

**Comment by Wally73** [comment]
mm on dev if ID isn't found no results (as it should)

**Comment by b3rs3rk** [comment]
I fixed this as well as improved last resort searches in Dev.  It must not have made it into the last merge down to 0.x.  We will have to look at merging it down ahead of schedule.

**Comment by ialexpw** [comment]
Is this also the fix for results coming up for non-existant show ID's? e.g.

https://nnn.com/api?t=tvsearch&tvdbid=999999&limit=5 (shows results in 0.x but not dev)

**Comment by b3rs3rk** [comment]
Yes.

**Comment by niel** [comment]
@ruhllatio if you can give me the commit for that fix I will make sure it gets into stable later today. I'm going to do the fixes Bart did a day or so back anyhow, so one more will not take long.

**Comment by b3rs3rk** [comment]
@niel wb.  I will look it up and send it to you in chat.

**Comment by ghost** [comment]
Resolved.
