### ISSUE TITLE
Some triggers in the schema are incorrect.

### ISSUE THREAD

**Issue by kevinlekiller** [nZEDb/nZEDb#2184]
[This commit](https://github.com/nZEDb/nZEDb/commit/75628b65c3d370980b15b1a971cda921ba609b5d) fixes some triggers in existing databases (but does not fix the triggers in the schema).

Although if we compare the patch to the values in the schema, they differ.

[This trigger](https://github.com/nZEDb/nZEDb/commit/75628b65c3d370980b15b1a971cda921ba609b5d#diff-fb8c180d697188f1461657196764bc52R1234) is missing `\\s?` at the end of the regex.

[This trigger](https://github.com/nZEDb/nZEDb/commit/75628b65c3d370980b15b1a971cda921ba609b5d#diff-fb8c180d697188f1461657196764bc52L1243) is missing an escape at the end on the `\s?`, it should be `\\s?`

**Comment by Bart39** [comment]
Good spot, will fix
