### ISSUE TITLE
Category Regex List no longer working

### ISSUE THREAD

**Issue by ghost** [nZEDb/nZEDb#2187]
Seems with latest 0.x  (e8d0384) Category Regex List has stopped working.

An example would be:
Original name: [02/23] - "[COMIC]  Die.Gringos.4.-.Viva.Mexico.(c2c).(Kult).(1998).(GCA-fab).cbr.part01.rar" - 290,98 MB Usenet-Space-Cowboys.online >>> No.1 NZB source<<< yEnc
Searchname: [COMIC]  Die.Gringos.4.-.Viva.Mexico.(c2c).(Kult).(1998).(GCA-fab).cbr
Group: alt.binaries.erotica

Regex:
group: ^alt.binaries.erotica$
regex: /._[COMIC]._/
Ordinal: 1
Category: 7030

I've also tried applying some patches from Dev to correct this, but it still does not work.
(Regexes.php, category-edit.php, category-list.php)

**Comment by Bart39** [comment]
Not quite sure what you mean but that regex doesn't look right. You need to escape [ and ]
/._[COMIC]._/

**Comment by Bart39** [comment]
Edit: nvm, GitHub is formatting the regex

**Comment by ghost** [comment]
regex: http://kopy.io/HcPyt

**Comment by Bart39** [comment]
Have you checked for any php errors ?

**Comment by ghost** [comment]
Yer, I've not seen any

**Comment by ghost** [comment]
Fixed with latest 0.x  1da4d22

Cheers

**Comment by Bart39** [comment]
Ahh, was missing my fix
