### ISSUE TITLE
bug or by design Minimum File Size to Make a Release

### ISSUE THREAD

**Issue by ghost** [nZEDb/nZEDb#2190]
site setting "Minimum File Size to Make a Release"  over rides 
"Minimum Size" in admin/category-list.php 
and also 
"Minimum File Size to Make a Release" in admin/group-edit.php

(Maybe the same for "Minimum Files to Make a Release"  I've not tested that.)

**Comment by b3rs3rk** [comment]
It depends upon how you're setting them.  Typically, we take the GREATEST value when we do the delete.  If your Minimum file size in Site Settings is larger than the file size in the group settings, it will choose the Site Setting because it is a larger value.
