### ISSUE TITLE
Movies not adding to My Movies

### ISSUE THREAD

**Issue by ghost** [nZEDb/nZEDb#2191]
On 0.x, Gamma theme

browse /movies and click "Add to My Movies"  
Movie is not added to /mymovies

**Comment by ghost** [comment]
I've applied 2dcbeaa0f7397b114fc6b5743727b4b6d022ae45 but still seeing the issue.

**Comment by DariusIII** [comment]
In my test VM it works just fine.

**Comment by ghost** [comment]
Tested again and no joy. No logs or anything. I am adding a movie via /movies and /mymovies search.

I've noticed if I search for a movie that I've added I have the 'remove from mymovies' button but the /mymovies page is empty & so is the rss feed

**Comment by Wally73** [comment]
/mymovies is only a search page 
/mymoviesedit is where they show up (and in my dev gamma they show up and also in the rss feed

**Comment by ghost** [comment]
Ah cheers wally
