### ISSUE TITLE
api search not respecting &group=

### ISSUE THREAD

**Issue by ghost** [nZEDb/nZEDb#2195]
maybe related to issue 2181?

/api?t=caps  
shows 
<search available="yes" supportedParams="q,group"/>

But when specifing &group=a.b.test or &group=alt.binaries.test  it's ignored.

**Comment by Wally73** [comment]
Parameters:
t=caps Caps function, must always be "caps".
Optional parameters:
o=xxx Output format, either "JSON" or "XML. Default is "XML".
that is the only parameter which works with caps
see
https://github.com/nZEDb/nZEDb/blob/dev/docs/newznab_api_specification.txt

**Comment by ghost** [comment]
Sorry yes I should have said, &o=xml is specified.

**Comment by Bart39** [comment]
Not sure what you mean ? If you specify t=caps all other params apart from &o are ignored as wally73 said.
Be specific with what you are trying and you think isn't working

**Comment by ghost** [comment]
eg:
/api?t=search&q=linux&cat=7010&maxage=60&minsize=5000000&maxsize=200000000&o=xml&apikey=xxxxxx&group=a.b.e-book.magazines

**Comment by ghost** [comment]
Clarified with @Bart39 , a better example was

/api?t=search&q=linux&cat=7010&maxage=60&minsize=5000000&maxsize=200000000&o=xml&apikey=xxxxxx&group=a.b.erotica

**Comment by ghost** [comment]
Fixed. Thanks
