### ISSUE TITLE
0.x API search incorrect category value

### ISSUE THREAD

**Issue by ghost** [nZEDb/nZEDb#2196]
.../api?&extended=1&t=search&q=linux

If I do the above (any API ) search, all of the results have this as the category value. 
<newznab:attr name="category" value="10"/>

**Comment by ghost** [comment]
<newznab:attr name="category" value="10"/>

**Comment by ghost** [comment]
newznab:attr name="category" value="10"

**Comment by DariusIII** [comment]
And why is this an incorrect value? 10 is OTHER->MISC

**Comment by ghost** [comment]
For every search the result is 10 even when 
"category>PC > 0day category"

**Comment by Wally73** [comment]
try again after you've upgraded to 0.6.2 ;)

**Comment by ghost** [comment]
resolved with latest 0.x
