### ISSUE TITLE
Database patching freeze... potential connection timeout?

### ISSUE THREAD

**Issue by stevenmcastano** [nZEDb/nZEDb#2201]
### Expected behaviour

When running a `./zed update all` everything goes smoothly until a large database patch runs. Normally you would expect that the current running patch, which in my case right now is `0444~releases.sql` would complete and the next patch in line runs.
### Actual behaviour

Potentially a timeout issue or something, but if the patch takes a while to run, which in this case could be anywhere from 5 - 20 minutes, the patching process stops. It appears like the database patch process doesn't know that line of the patch has completed and to make it continue I have to open up the patch file and comment out with a "#" the last command that ran when re-run `./zed update all` again for it to continue to the next step.
### Steps to reproduce the behaviour

Run `./zed update all` from a level that includes a patch that would modify the entire "releases" table on a table large enough to extend the runtime to over 600 - 800 seconds. In my case my releases table with all partition is ~11GB.

**Comment by DariusIII** [comment]
This is not an nZEDb issue but your DB issue, as your DB needs to apply patches. My best bet is that you need to tweak your my.cnf to avoid issues like this in future. It is known that some patches run for a long time before they complete.

**Comment by stevenmcastano** [comment]
> It is bad practice to sit there connected for arbitrarily long. It is better to have wait_timeout be something more like 30 (seconds) and write code to deal with disconnects. Reconnecting to MySQL is quite quick, so it is not a performance issue. If the app is idle for (say) 30 seconds, it should expect to get an error and have to reconnect.

From: [DBA StackExchange](http://dba.stackexchange.com/questions/97158/mysql-connection-timeout-on-small-traffic-server)

**Comment by niel** [comment]
This is not an issue I suffer from and many updates take an hour or more on my machine.

A PR to fix the patching process, so it also works for you, would be considered for merging.

**Comment by ghost** [comment]
Patches ran fine for me.
