### ISSUE TITLE
Uncaught Exception: Failed to open versions XML file

### ISSUE THREAD

**Issue by ghost** [nZEDb/nZEDb#2202]
``` php
2016/07/05 10:00:44 [error] 29913#29913: *113799557 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Exception: Failed to open versions XML file '/home/nzedb/build/nzedb.xml' in /home/nzedb/nzedb/utility/Versions.php:276
Stack trace:
#0 /home/nzedb/nzedb/utility/Versions.php(84): nzedb\utility\Versions->getValidVersionsFile()
#1 /home/nzedb/nzedb/http/Capabilities.php(126): nzedb\utility\Versions->__construct()
#2 /home/nzedb/nzedb/http/Capabilities.php(79): nzedb\http\Capabilities->getForMenu()
#3 /home/nzedb/www/pages/api.php(182): nzedb\http\Capabilities->output(Array, Array, true, 'api')
#4 /home/nzedb/www/index.php(76): include('/home/nzedb/www...')
#5 {main}
  thrown in /home/nzedb/nzedb/utility/Versions.php on line 276" while reading response header from upstream, client: xxx, server: none, request: "GET /api?apikey=04bdec29c510acf62fc466e8218a0612&t=tvsearch&extended=1&offset=0&limit=100&cat=5030,5040,5070 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "none"
2016/07/05 10:00:44 [error] 29895#29895: *113798576 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Exception: Failed to open versions XML file '/home/nzedb/build/nzedb.xml' in /home/nzedb/nzedb/utility/Versions.php:276
```

Getting this after latest update. The file exists. When I add these lines after line 269 in Versions.xml I am presented with my XML file:

``` php
$test = file_get_contents($filepath);
die($test);
```

**Comment by niel** [comment]
Is this in 0.6.2 code or the version you reverted to?

**Comment by ghost** [comment]
This is the current 0.x branch. I do have to note that I did git update by accident (i was so used to it :P) instead of running ./zed update all. I did ran zed update all after git pull though.

The official git tag is 0.6.2.1 by the way, that did not show in my XML file.

**Comment by niel** [comment]
Is /home/nzedb/ the base directory of your nZEDb?
This doesn't look right.

**Comment by ghost** [comment]
@niel Yes sir. So the www dir sits in /home/nzedb/www for example.

**Comment by niel** [comment]
That is just weird. /home/nzedb should be the home directory of the USER nzedb. Any directories belonging to that user should be under that location. So I would expect nZEDb to be in /home/nzedb/nZEDb/
I wonder if this might be the root of many of your problems?

**Comment by ghost** [comment]
It has worked fine like this since 2012. It's not weird :-)

**Comment by niel** [comment]
lol and you have never had any other 'weird' problems after updating?

**Comment by ghost** [comment]
Nope had nothing like this before. Sure some issues once in a while but nothing fancy.

**Comment by ghost** [comment]
@DariusIII does this commit 3ea359541b246f44a5d55a62a510e7d41250fc4b fix this issue?

**Comment by DariusIII** [comment]
No, but one after that should.

**Comment by ghost** [comment]
This one 3ea359541b246f44a5d55a62a510e7d41250fc4b ?

**Comment by DariusIII** [comment]
This one: d3d35a8cb99c1d76c51b7b228983cf9ce6debb56

**Comment by ghost** [comment]
Alright. Will test after the weekend and report back.

**Comment by ghost** [comment]
This was fixed a while back so closing.
