### ISSUE TITLE
browse?t=0000 displays 404

### ISSUE THREAD

**Issue by lostjackson123** [nZEDb/nZEDb#2203]
### Expected behaviour

Should browse the other category
All other categories work.
### Actual behaviour

Notice: Undefined offset: 0 in /var/www/html/nZEDb/www/pages/browse.php on line 34
404 - File not found.
### Steps to reproduce the behaviour

in category menu, Other > Other

**Comment by lostjackson123** [comment]
Error was fixed by inserting "Other" into the category table
INSERT INTO `nzedb`.`categories` (`id`, `title`, `parentid`, `status`, `description`, `disablepreview`, `minsize`) VALUES ('0', 'Other', NULL, '1', NULL, '0', '0');

**Comment by niel** [comment]
Was this on a new install?

**Comment by lostjackson123** [comment]
Yes this was a new install. Category "Other" with ID 0 did not exist.

**Comment by niel** [comment]
This should be fixed now. A query that should insert that entry was using an old table name.
