### ISSUE TITLE
Tmux doesn't start after update

### ISSUE THREAD

**Issue by bobtongue** [nZEDb/nZEDb#2205]
### Expected behaviour

updated with ./zed update nzedb
start tmux
all runs well
### Actual behaviour

updated with ./zed update nzedb
start tmux
Tmux does not start
error in php_errors.log that says:
[06-Jul-2016 12:07:33 America/New_York] PHP Fatal error:  Class 'app\extensions\util\Versions' not found in /var/www/myserver.com/htdocs/nZEDb/nzedb/db/Settings.php on line 232
### Steps to reproduce the behaviour

See above
I am on master branch

**Comment by scottia** [comment]
Same error when attempting to run TMUX on DEV.  Will not start

**Comment by niel** [comment]
Looking into this now.

**Comment by csmarauder** [comment]
Yup Can confirm
root@c:/dump/nzedb/misc/update/nix/tmux# php start.php
PHP Fatal error:  Uncaught Error: Class 'app\extensions\util\Versions' not found in /dump/nzedb/nzedb/db/Settings.php:232
Stack trace:
#0 /dump/nzedb/nzedb/Tmux.php(38): nzedb\db\Settings->version()
#1 /dump/nzedb/nzedb/Tmux.php(325): nzedb\Tmux->version()
#2 /dump/nzedb/nzedb/Tmux.php(81): nzedb\Tmux->rows2Object(Array)
#3 /dump/nzedb/misc/update/nix/tmux/start.php(17): nzedb\Tmux->get()
#4 {main}
  thrown in /dump/nzedb/nzedb/db/Settings.php on line 232
root@c:/dump/nzedb/misc/update/nix/tmux# tmux -V
tmux 2.0

**Comment by ghost** [comment]
I get the following seemingly related error.

meganomic@sakura> php start.php
PHP Fatal error:  Uncaught Error: Class 'nzedb\utility\Misc' not found in /usr/share/nginx/n
zedb/nzedb/bootstrap.php:25
Stack trace:
#0 /usr/share/nginx/nzedb/libraries/lithium/core/Libraries.php(325): require()
#1 /usr/share/nginx/nzedb/libraries/lithium/core/Libraries.php(303): lithium\core\Libraries:
:_configure(Array)
#2 /usr/share/nginx/nzedb/app/config/bootstrap/libraries.php(133): lithium\core\Libraries::a
dd('nzedb', Array)
#3 /usr/share/nginx/nzedb/autoloader.php(39): include('/usr/share/ngin...')
#4 /usr/share/nginx/nzedb/indexer.php(22): require_once('/usr/share/ngin...')
#5 /usr/share/nginx/nzedb/misc/update/nix/tmux/start.php(9): require_once('/usr/share/ngin..
.')
#6 {main}
  thrown in /usr/share/nginx/nzedb/nzedb/bootstrap.php on line 25

**Comment by scottia** [comment]
Nothing working after earlier update to Dev.  Now am getting this when trying to run anything.

PHP Warning:  require(nzedb/bootstrap.php): failed to open stream: No such file or directory in /var/www/nZEDb/libraries/lithium/core/Libraries.php on line 325
PHP Fatal error:  require(): Failed opening required 'nzedb/bootstrap.php' (include_path='.:/usr/share/php') in /var/www/nZEDb/libraries/lithium/core/Libraries.php on line 325

**Comment by niel** [comment]
Should be fixed in dev now.

**Comment by meganomic** [comment]
Now I get stuff like this.

2016/07/07 02:29:53 [error] 22770#22770: *5 open() "/usr/share/nginx/nzedb/www/index.php/the
mes/shared/img/clearlogo.png" failed (20: Not a directory), client: 192.168.1.1, server: example.com, request: "GET /index.php/themes/shared/img/clearlogo.png HTTP/1.1", host: "example.com", referrer: "https://example.com/"
2016/07/07 02:29:53 [error] 22770#22770: *9 open() "/usr/share/nginx/nzedb/www/index.php/the
mes/shared/js/sorttable.js" failed (20: Not a directory), client: 192.168.1.1, server: example.com, request: "GET /index.php/themes/shared/js/sorttable.js HTTP/1.1", host: "example.com", referrer: "https://example.com/"
2016/07/07 02:29:53 [error] 22770#22770: *11 open() "/usr/share/nginx/nzedb/www/index.php/th
emes/Alpha/scripts/utils.js" failed (20: Not a directory), client: 192.168.1.1, server: example.com, request: "GET /index.php/themes/Alpha/scripts/utils.js HTTP/1.1", host: "example.com", referrer: "https://example.com/"

**Comment by stuartst** [comment]
Just done a quick test on this and received the following error:

```
PHP Warning:  require_once(/var/www/nzedb/misc/update/nix/tmux): failed to open stream: No such file or directory in /var/www/nzedb/misc/update/nix/tmux/start.php on line 10
PHP Fatal error:  require_once(): Failed opening required '' (include_path='.:/usr/share/php') in /var/www/nzedb/misc/update/nix/tmux/start.php on line 10
```

**Comment by scottia** [comment]
same here when starting TMUX on Dev

**Comment by niel** [comment]
@stuartst what does line 10 of start.php look like? and are you sure you're on up to date dev?

**Comment by stuartst** [comment]
My line 10 is:

`require_once realpath(dirname(dirname(dirname(dirname(__DIR__)))) . DIRECTORY_SEPARATOR . 'bootstrap.php');`

Configured to run dev branch using:

`git reset --hard origin/dev`
`./zed update nzedb`

**Comment by niel** [comment]
that command line is just wrong. you have two commands on one line, which will cause problems.

**Comment by stuartst** [comment]
Sorry, that was just a formatting mistake in my reply. The commands were issued separately with no errors.

**Comment by niel** [comment]
Nothing in the commands says you're on dev. run
 ./zed version all
 and let me know the results, please.

**Comment by scottia** [comment]
here are mine.  same error as @stuartst 

scottia@Ubuntu:/var/www/nZEDb$ ./zed version all
Looking up Git tag version(s)
Hash: 4f200bc595c5de94e1b367f06fc522d5cf8303c0
XML version: 0.0.0
Git version: v0.6.1-RC1

Looking up SQL patch version(s)
XML version: 445
 DB version: 445

**Comment by niel** [comment]
@scottia you're not on dev. the git version tag indicates you're on an old version of Latest-testing. Which probably means your repo config is off somehow. do: git checkout dev && ./zed update all

**Comment by scottia** [comment]
no idea why or how, am on dev according to results from "git checkout dev && ./zed update all"

Already on 'dev'
Your branch is up-to-date with 'origin/dev'.
Already up-to-date.

**Comment by csmarauder** [comment]
Same issue
root@c:/dump/nzedb# git checkout dev && ./zed update all
Already on 'dev'
Already up-to-date.

Running composer install process...
Running composer as root/super user is highly discouraged as packages, plugins and scripts cannot always be trusted
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
Checking database version...
Db: 445,        File: 445
Up to date.
The Smarty compiled template cache has been cleaned for you
root@c:/dump/nzedb# cd -
/dump/nzedb/misc/update/nix
root@c:/dump/nzedb/misc/update/nix# cd tmux/
root@c:/dump/nzedb/misc/update/nix/tmux# php start.php
PHP Warning:  require_once(/dump/nzedb/misc/update/nix/tmux): failed to open stream: No such file or directory in /dump/nzedb/misc/update/nix/tmux/start.php on line 10
PHP Fatal error:  require_once(): Failed opening required '' (include_path='.:/usr/share/php') in /dump/nzedb/misc/update/nix/tmux/start.php on line 10

**Comment by PsychoSid** [comment]
Still happening after latest commits:-

$ ./zed version all
Looking up Git tag version(s)
Hash: 4f200bc595c5de94e1b367f06fc522d5cf8303c0
XML version: 0.0.0
Git version: v0.6.2.2

Looking up SQL patch version(s)
XML version: 445
 DB version: 445

[07-Jul-2016 05:49:25 Europe/London] PHP Warning:  require_once(/var/www/nZEDb): failed to open stream: No such file or directory in /var/www/nZEDb/misc/update/nix/tmux/start.php on line 10
[07-Jul-2016 05:49:25 Europe/London] PHP Fatal error:  require_once(): Failed opening required '' (include_path='.:/usr/share/php:/usr/share/pear:') in /var/www/nZEDb/misc/update/nix/tmux/start.php on line 10

**Comment by hondnl** [comment]
Confirm , same as above for me.

**Comment by DariusIII** [comment]
Can you replace line 10 in start.php with the following line: require_once realpath(dirname(dirname(dirname(dirname(**DIR**)))) . DIRECTORY_SEPARATOR . 'nzedb' . DIRECTORY_SEPARATOR .'bootstrap.php');

**Comment by hondnl** [comment]
Changed DIR to`__DIR__`

`require_once realpath(dirname(dirname(dirname(dirname(__DIR__)))) . DIRECTORY_SEPARATOR . 'nzedb' . DIRECTORY_SEPARATOR .'bootstrap.php');
`
No error shown, but also NO tmux session starts.

Update :   In php_error.log 
`
[07-Jul-2016 10:31:59 Europe/Amsterdam] PHP Fatal error:  Class 'app\extensions\util\Versions' not found in /home/nZEDb/nzedb/db/Settings.php on line 232`

**Comment by hondnl** [comment]
Temp solution works... Tmux session started without incident.

**Comment by niel** [comment]
I messed up and forgot to commit the new bootstrap file :-(
Should be working on dev branch now.

**Comment by niel** [comment]
Pushed to stable as release v0.6.2.3

**Comment by stuartst** [comment]
Confirmed as working. Thanks @niel.
