### ISSUE TITLE
PHP 500 Error clicking "TVSeries" on LIGHT user profile 

### ISSUE THREAD

**Issue by nrk666** [nZEDb/nZEDb#2207]
Fresh Ubuntu 16 install (followed wiki guide + forum posts), up to date STABLE as of today 
### Expected behaviour

Click "TV Series" on top menu, should see something other than a bad web page
### Actual behaviour

Get 500 error page.

php_error.log says: 

`[08-Jul-2016 20:45:49 America/New_York] PHP Fatal error:  Uncaught  --> Smarty Compiler: Syntax error in template "file:/var/www/nZEDb/www/themes/Light/templates/viewserieslist.tpl"  on line 34 "<td>{$s.country|escape:"htmlall"}</td>" unclosed {foreach} tag <-- 
  thrown in /var/www/nZEDb/app/libraries/smarty/smarty/libs/sysplugins/smarty_internal_templatecompilerbase.php on line 34
[08-Jul-2016 20:58:06 America/New_York] PHP Notice:  Undefined offset: 0 in /var/www/nZEDb/www/pages/browse.php on line 34
[08-Jul-2016 20:58:07 America/New_York] PHP Notice:  Undefined offset: 0 in /var/www/nZEDb/www/pages/browse.php on line 34`
### Steps to reproduce the behaviour

use "LIGHT" user profile (not sure this happens on all profiles) and click "TV Series" on top menu, causes 500 error page.

**Comment by Wally73** [comment]
confirmed on dev 
on all other themes it works fine

**Comment by Wally73** [comment]
fixed in dev

**Comment by nrk666** [comment]
cheers mate
