### ISSUE TITLE
Repeating errors reported in ~/php_errors.log

### ISSUE THREAD

**Issue by xeddog** [nZEDb/nZEDb#2208]
Since about the time of the July updates to master branch (0.x) I have been getting these errors ~/php_errors.log.  The same 25 messages are repeated each time an nZEDb php program starts, so when running tmux there is a LOT of them.

I am running 0.x on an Ubuntu 16.04 machine with php7.  But on the nZEDb support forum someone said they have the same problem on ubuntu 14.04 lts, and php 5.6.23, and both dev and 0.x branches.

[php_errors.txt](https://github.com/nZEDb/nZEDb/files/356124/php_errors.txt)

**Comment by DariusIII** [comment]
This is not a problem, per se, these are notices about already defined constants. Will be fixed.

**Comment by DariusIII** [comment]
You need to have a valid settings.php file and these errors will be gone.

**Comment by niel** [comment]
I'm already looking into why this happens, but Darius is absolutely correct that it doesn't occur if you have created your settings.php file from the example provided (simply copying it to settings.php from settings.example.php is enough).

**Comment by DariusIII** [comment]
Workaround has been implemented in commit d29be2788cd93b973928670a4d9d407c8a593475
