### ISSUE TITLE
1054 Unknown column 'r.group_id' in 'on clause

### ISSUE THREAD

**Issue by dilbaggins** [nZEDb/nZEDb#2213]
### Expected behaviour

show releases/create releases
### Actual behaviour

this error:  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'r.group_id' in 'on clause' when i click on any of the categories in the menus (movies, TV, etc) 
and no tmux releases created
### Steps to reproduce the behaviour

i restored my live DB to a dev server for testing, and resetDB. so it should be a fresh DB save for my users etc (no releases, nzbs etc.

**Comment by dilbaggins** [comment]
and i tried the delete_tpg_ in runonce.

**Comment by DariusIII** [comment]
What branch are you on?

**Comment by DariusIII** [comment]
Are you manually running requestid_threaaded.py?

**Comment by dilbaggins** [comment]
Branch - ;atest dev
not manually.  doing this via tmux request id threaded

**Comment by DariusIII** [comment]
./zed update nzedb and check if it works now

**Comment by dilbaggins** [comment]
odd (i think this is root issue).  i copied my DB from my prod box to an ec2 instance to test some new things and i think the version in my ec2 instance is out of wack... how do i correct the version disparity?  

Results
 ./zed update all
Not on the stable or dev branch! Refusing to update repository ;-)
Running composer install process...
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
Checking database version...
Db: 445,        File: 442
Up to date.

**Comment by dilbaggins** [comment]
Looking up Git tag version(s)
Hash: 1da4d22a4dc0e4031863fbda8cdb9046c43146da
XML version: 0.6.1
Git version: v0.6.1.3

Looking up SQL patch version(s)
XML version: 442
 DB version: 445

**Comment by DariusIII** [comment]
git checkout dev
git pull
./zed update nzedb

**Comment by dilbaggins** [comment]
error: pathspec 'dev' did not match any file(s) known to git  (odd)

git remote
composer
origin

**Comment by DariusIII** [comment]
git fetch -p origin

Edit: can you join nZEDb channel on IRC so we can fix this faster?

**Comment by dilbaggins** [comment]
@DariusIII  thanks.. going to close for now as i used an install script to do this dev build vs the manual install process i usually do... i think git is out of whack...  

p.s. what do you guys do to automate builds with all the prereqs on it? :)  thank you again for your help.

Dil
