### ISSUE TITLE
blank screen on fresh deployment

### ISSUE THREAD

**Issue by thejrose1984** [nZEDb/nZEDb#2214]
### Expected behaviour

web redirect for install / nZEDb setup
### Actual behaviour

blank screen
php log file = http://pastebin.com/zAcd1F6Q
### Steps to reproduce the behaviour

opened web browser and saw blank screen

**Comment by DariusIII** [comment]
https://github.com/nZEDb/nZEDb/blob/0.x/ReleaseNotes#L148

Read the changelog.

**Comment by thejrose1984** [comment]
Ran commands as noted in the change log, restarted nginx and php-fpm, still get a blank page
php log file = http://pastebin.com/GCNiHArx

root@nzb_git_index01:/usr/local/www/nZEDb # ls -l /usr/local/www/nZEDb/nzedb/config/Configure.php
-rw-r--r--  1 www  wheel  4195 Jul 16 14:17 /usr/local/www/nZEDb/nzedb/config/Configure.php

**Comment by niel** [comment]
You missed the point of that error. It is not saying configure.php is missing, it is say configure.php tried to load 'config.php' and that is missing.
Which branch is this on?
Is that last error from the apache/nginx log?

**Comment by thejrose1984** [comment]
`composer create-project --no-dev --keep-vcs nzedb/nzedb` is what was ran to acquire the code

**Comment by niel** [comment]
can you come to IRC channel to handle this more quickly?

**Comment by niel** [comment]
Confirmed this is a bug. I'm looking into it.

**Comment by niel** [comment]
Fixed in dev.
