### ISSUE TITLE
tmux-edit page (HTTP ERROR 500)

### ISSUE THREAD

**Issue by dilbaggins** [nZEDb/nZEDb#2215]
### Expected behaviour

tmux settings from admin allowing changes
### Actual behaviour

HTTP ERROR 500
### Steps to reproduce the behaviour

go to nzedb/admin click "Tmux-settings"  and you get a 500.

latest dev build.

**Comment by Wally73** [comment]
can confirm it on latest dev (git hash dbf52fe5d122dfa52738bcbc6429ed49ee27e504)
/admin/tmux-edit.php gives HTTP ERROR 500

**Comment by DariusIII** [comment]
It has nothing to do with RSS/API changes.

**Comment by Wally73** [comment]
@DariusIII  I know, I only gave the git hash from where I noticed that issue)

**Comment by dilbaggins** [comment]
fixed.  thx niel.
