### ISSUE TITLE
[Bug] ?get API call does not download the nzb associated with the ID currently in 0.x

### ISSUE THREAD

**Issue by EDChurly** [nZEDb/nZEDb#2218]
### Expected behaviour

?t=get&id=xxx&apikey=yyy should download a nzb if given a valid release id and apikey.  
### Actual behaviour

Currently, it doesnt seem to download the nzb in 0.x.
### Steps to reproduce the behaviour

Enter the api string with valid id and apikey into a browser, blank page appears and no nzb is downloaded.

**Comment by Wally73** [comment]
/guid.nzb&i=2&r=apikey works fine here

**Comment by EDChurly** [comment]
/getnzb/guid.nzb&i=1&r=apikey works for me too, but  

api?t=get&id=guid&apikey=xxx  should work too correct?   The API doco suggests it should?

**Comment by Wally73** [comment]
api?t=get&id=9ca52909ba9b9e5e6758d815fef4ecda that works

api?t=get&id=9ca52909ba9b9e5e6758d815fef4ecda&apikey=xxxx doesn't

**Comment by EDChurly** [comment]
I cant seem to get either to work on current 0.x, but other api functions work fine.

**Comment by DariusIII** [comment]
Both examples Wally73 provided work on dev. Tested couple of minutes ago.

**Comment by ghost** [comment]
I have this issue too #2226.

@DariusIII @Wally73

**Comment by ghost** [comment]
It's fixed in dev

**Comment by EDChurly** [comment]
This can be closed, the fix applied to dev is in 0.x too.
