### ISSUE TITLE
blank page on deployment

### ISSUE THREAD

**Issue by thejrose1984** [nZEDb/nZEDb#2219]
### Expected behaviour

redirect to install page
### Actual behaviour

blank page
### Steps to reproduce the behaviour

tried on firefox and chrome
php error log = http://paste2.org/KDIHIG0Y
nginx access log = http://paste2.org/vsP7asDf

**Comment by niel** [comment]
This is the same issue we looked into last week. It is fixed in dev and will make it to stable branch in just over a week.
