### ISSUE TITLE
After Git pull, nZEDb not working anymore

### ISSUE THREAD

**Issue by groentebroer** [nZEDb/nZEDb#2220]
### Expected behaviour

Git pull and all new features are there!
### Actual behaviour

Git pull updated the DEV branch, which now complains about missing includes:

PHP Warning:  require_once(/wwwroot/app/libraries/autoload.php): failed to open stream: No such file or directory in /wwwroot/www/smarty.php on line 22

Checking GitHub showed me quite a lot of changes :).

So I tried switching to (maybe a more stable version) (Branch 0.x)

PHP Warning:  include(/wwwroot/libraries/lithium/core/Libraries.php): failed to open stream: No such file or directory in /wwwroot/app/config/bootstrap/libraries.php on line 72

In both cases these files are indeed not there.
I also tried tag 0.6.2.4 with sort-alike result.
Which git repo should I use right now to get a working copy?

Thanks for the great work!
### Steps to reproduce the behaviour

I cannot tell exactly.

**Comment by Wally73** [comment]
mm you haven't upgraded in a while then (and haven't read the release notes) 

you need to install composer 

https://github.com/nZEDb/nZEDb/blob/0.x/docs/Installing.md

**Comment by groentebroer** [comment]
Yes it was quite a while back... ;-).
I will take a look at the composer (and the release notes).
Can you tell me which REPO / Tag I need to follow from now on?

**Comment by Wally73** [comment]
the 0.x branch (which is the stable branch )

**Comment by groentebroer** [comment]
Oke, got it working again (sort of).
Got Composer installing all kinds of  stuff.
Updated from PHP 5.5 to PHP 5.6. Some smarty dir write settings and working again!

But in the admin panel (yes I can still login) the "groups" overview is empty (not showing any groups at all).
Is there some update or upgrade script I can run? Or some other advice?

mysql> select count(_) from groups;
+----------+
| count(_) |
+----------+
|      203 |
+----------+

There were some releases, but it is not showing them as well.
mysql> select count(_) from releases;
+----------+
| count(_) |
+----------+
|    75889 |
+----------+
1 row in set (0.00 sec)

**Comment by groentebroer** [comment]
Oke, slept a night over it.
Somewhere in the Release notes I found "zed update", which resolved the issues I had.
Admin looks good again. Will try to import new releases (binaries) later.
