### ISSUE TITLE
Account limits bug

### ISSUE THREAD

**Issue by ghost** [nZEDb/nZEDb#2221]
### Expected behaviour

If a user tries to grab to many nzbs give an error and let them continue to have access to their unused download slots. 
### Actual behaviour

If a user role allows 5 downloads a day and the user tries to make a zip with 10 nzbs the user gets 0 nzbs and is no longer able to download until the 24 hours has passed.
### Steps to reproduce the behaviour

Use an account on a 5 downoad limited role, fill in the checkboxes for 10 releases and hit Download nzbs. You have now exceed your allowance but not actually had any nzbs.

This is on Gamma / 0.x

**Comment by Bart39** [comment]
i can't replicate this,

if i try the same i get api error - download limit reached after selecting 10.
if i retry this time selecting just 5 i gethe zip as expected

**Comment by ghost** [comment]
Neither can I now, must have been fixed in latest 0.x
