### ISSUE TITLE
a.b.inner-sanctum RegEx's 

### ISSUE THREAD

**Issue by DrakeJones** [nZEDb/nZEDb#2228]
### Expected behaviour

Posts to a.b.inner-sanctum recognized by group specific/general RegEx's.
### Actual behaviour

a.b.inner-sanctum is getting a lot posts before a.b.teevee but lacks the proper RegEx's in the RegEx Collections List to process them.
### Steps to reproduce the behaviour

Normal operation.

**Comment by ghost** [comment]
@Bart39 is the regex king here right? :P

**Comment by DrakeJones** [comment]
That's what I be told...

**Comment by Bart39** [comment]
Sat on a beach at the moment, will look when I get back.
Inner sanctum used to be mostly by request Id until they stopped which is why it didn't need regex

**Comment by DrakeJones** [comment]
I only noticed it because Web Crawler is back and inner sanctum appears to be the new hot spot for TV posts so I started indexing it. Enjoy the holiday.
