### ISSUE TITLE
Rss search not working

### ISSUE THREAD

**Issue by ghost** [nZEDb/nZEDb#2229]
Latest 0.x if you search for something then click the rss feed button the results ignore the & filter

**Comment by DariusIII** [comment]
Example?

**Comment by ghost** [comment]
Sorry for delay
https://xxx.com/rss?t=-1&dl=1&i=xxx&r=xxx&uFilter=linux

**Comment by ghost** [comment]
Closing, only Gamma has this button. Removed button. Fixed :D
