### ISSUE TITLE
Advanced Search showing disabled categories

### ISSUE THREAD

**Issue by ghost** [nZEDb/nZEDb#2230]
### Expected behaviour

Select field should only show enabled categories.
### Actual behaviour

I see all categories.
### Steps to reproduce the behaviour

``` smarty
{html_options class="form-control" id="searchadvcat" name="searchadvcat" data-search="true" options=$catlist selected=$selectedcat}
```

**Comment by DariusIII** [comment]
This is by design, excluded cats are not shown only in api/rss.

**Comment by ghost** [comment]
Well that's weird.

**Comment by niel** [comment]
To be clear, "by design" here, means that's how it is coded. Not how we think it should be. We want to extend this to cover all browsing, etc. but current code makes that difficult at best, so we will look into refactoring the code at some stage to allow a better implementation.
