### ISSUE TITLE
problem running install

### ISSUE THREAD

**Issue by raysv** [nZEDb/nZEDb#2232]
Hi, 
Just trying to install a fresh nzedb install on a ubuntu 16.04 server. 

However when trying to run install i'm getting this in the apache log:

[Sun Aug 07 20:18:19.462025 2016] [:error] [pid 10593] [client 192.168.0.7:54547] PHP Warning:  require_once(/var/www/nzedb/www/install): failed to open stream: No such file or directory i$
[Sun Aug 07 20:18:19.462061 2016] [:error] [pid 10593] [client 192.168.0.7:54547] PHP Fatal error:  require_once(): Failed opening required '' (include_path='.:/usr/share/php') in /var/www$

Any idea of why? php is install, /usr/share/php is there etc. 

It's php7 and not 5 on this server tough.

**Comment by kevinlekiller** [comment]
Try the 4th issue/solution here: https://github.com/nZEDb/nZEDb/issues/2182

**Comment by kevinlekiller** [comment]
Possibly fixed in these (dev branch): 99225b36803c8652b4ccac99e0a861a9daf0c130 fc4b631ee0fdb910fefa34153736b8fffc292743 bb3ceffc9c6ce0fddc984328bc5be04a21e36a6b dd60d53438f260be7b2729f32483b5bb81bd236c

**Comment by raysv** [comment]
libapache2-mod-php7.0 is atleast allready installed on this server so thats not the case :)

**Comment by kevinlekiller** [comment]
You can temp fix it by changing [line 21 and 22](https://github.com/nZEDb/nZEDb/blob/0.x/www/install/install.php#L21) like this:

```
require_once realpath(dirname(dirname(__DIR__)) DIRECTORY_SEPARATOR . 'nzedb' . . DIRECTORY_SEPARATOR . 'constants.php');
require_once realpath(nZEDb_ROOT . 'app' . DS . 'libraries' . DS . 'autoload.php');
```

**Comment by kevinlekiller** [comment]
Step2 is broken also, [line 186 and 187 are to blame](https://github.com/nZEDb/nZEDb/blob/0.x/www/install/step2.php#L186)

Temp fix is to change them to

```
$ver = new \nzedb\utility\Versions();
$patch = $ver->getSQLPatchFromFiles();
```

**Comment by kevinlekiller** [comment]
@niel might want to fix these issues

**Comment by raysv** [comment]
Changing the require_once didn't help either, still getting 500 error when trying to go to step1 :(

**Comment by kevinlekiller** [comment]
Alright, I created https://github.com/nZEDb/nZEDb_Misc/blob/master/Scripts/Linux/testinstall.sh to hopefully prevent this recurring issue of the installer breaking. Hopefully the nzedb devs will use it occasionally to test the installer to make sure it's functioning correctly.

**Comment by niel** [comment]
Install should be fixed in dev. I'll be merging changes to stable later today

**Comment by raysv** [comment]
Now I'm coming to step2 atleast, but only getting  "Unable to create database and data. Check permissions of your mysql user" . 
However the DB and table gets created. but not any content of the DB. 

The user has full privs.   Tried with the root user aswell but no go.

**Comment by raysv** [comment]
I tried the "temp fix" for step2 allready posted, but then the server is throwing a 500 error with this error:

[Tue Aug 09 13:15:59.865890 2016] [:error] [pid 11763] [client] PHP Fatal error:  Uncaught Error: Call to undefined method nzedb\utility\Versions::getSQLPatchFromFile() in /var/www/nze$

**Comment by niel** [comment]
Fix for this was released to stable branch yesterday.

**Comment by niel** [comment]
if you have --secure-file-priv on the server you can ONLY load from the directory enabled by that setting. Our files cannot be loaded unless their location is the directory allowed.

**Comment by jutrasb** [comment]
Running either dev or stable branch, this still seems to be a problem. I tried the installer script as well from @kevinlekiller. I get HTTP Error 500 on step1.php and the script also gives me an error with step1.php. There has to be something that's missing?

It is worth noting that PHP is stored at /etc/php/7.0/\* for PHP7 and /etc/php/5.6/\* for PHP5.6.

Edit: Getting this in my error.log
[Wed Sep 07 09:16:52.129702 2016] [:error] [pid 56215] [client 192.168.0.121:64035] PHP Fatal error:  Uncaught Error: Call to a member function count() on boolean in /var/www/nZEDb/app/models/Settings.php:83\nStack trace:\n#0 /var/www/nZEDb/app/config/bootstrap/yenc.php(29): app\models\Settings::value('..yydecoderpath', true)\n#1 /var/www/nZEDb/app/config/bootstrap.php(90): require_once('/var/www/nZEDb/...')\n#2 /var/www/nZEDb/www/install/install.php(31): require_once('/var/www/nZEDb/...')\n#3 /var/www/nZEDb/www/install/step1.php(7): require_once('/var/www/nZEDb/...')\n#4 {main}\n  thrown in /var/www/nZEDb/app/models/Settings.php on line 83, referer: http://127.0.0.1/install/

**Comment by kevinlekiller** [comment]
Yeah I found the issue here: https://github.com/kevinlekiller/nZEDb/commit/9f1eabe79b1517d132ed64d967bf5725c0bec35a

Will be fixed in nzedb soon.

**Comment by niel** [comment]
@jutrasb what PHP version are you on?

**Comment by jutrasb** [comment]
@niel I am using PHP7, installed fresh.

PHP 7.0.8-0ubuntu0.16.04.2 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.8-0ubuntu0.16.04.2, Copyright (c) 1999-2016, by Zend Technologies

**Comment by kevinlekiller** [comment]
@jutrasb currently installing here: https://travis-ci.org/kevinlekiller/nZEDb/builds/158174024

**Comment by jutrasb** [comment]
@kevinlekiller Sorry for the noob question: How do I clone the working build? I'm unfamiliar with Composer.

**Comment by kevinlekiller** [comment]
@jutrasb for now you can manually edit the file like https://github.com/kevinlekiller/nZEDb/commit/9f1eabe79b1517d132ed64d967bf5725c0bec35a until the fix is in nzedb, you can `git checkout app/config/bootstrap/yenc.php` once it is to reset your file before `git pull`ing.

**Comment by jutrasb** [comment]
@kevinlekiller Cheers, will do and report back.

EDIT: Working now, thank you @kevinlekiller!
