### ISSUE TITLE
Local branch 0.x stuck on version 1da4d22a4dc0e4031863fbda8cdb9046c43146da, cant update

### ISSUE THREAD

**Issue by Rawh** [nZEDb/nZEDb#2233]
### Expected behaviour

To be able to run 'zed update nzedb' and keep my local running version up to date that way
### Actual behaviour

It's currently doing all the stuff as explained in the forum post [here](http://forums.nzedb.com/index.php?topic=2276.0)
### Steps to reproduce the behaviour

n/a

**Comment by DariusIII** [comment]
git checkout 0.x
git reset --hard origin/0.x

**Comment by Rawh** [comment]
That seems to have do a lot of things :+1: 

What should be the default action on this question:
-10 more files modified, choose "v" to view the full list
    Discard changes [y,n,v,d,s,?]?

I used 'y', which is ok I'm guessing?

**Comment by DariusIII** [comment]
Yeah.

**Comment by Rawh** [comment]
Suddenly an error occurred: 
Error: ALTER TABLE user_movies
CHANGE COLUMN categories_id categories VARCHAR(64) NULL DEFAULT NULL
COMMENT 'List of categories for user movies'; Failed {1054}
        Unknown column 'categories_id' in 'user_movies'

I remember reading about this on the forum:
http://forums.nzedb.com/index.php?topic=2273.0

I'll apply the fix, rerun 'zed' and see what happens!

**Comment by Rawh** [comment]
You sir are a lifesaver! 
Running the latest version now :)

Thanks a lot @DariusIII :+1:
