### ISSUE TITLE
[Bug] links in "Other" submenu are broken in some templates

### ISSUE THREAD

**Issue by hansenhans** [nZEDb/nZEDb#2237]
### Expected behaviour

links should look like

http://server/nZEDb/www/browse?t=0000
http://server/nZEDb/www/browse?t=0010
http://server/nZEDb/www/browse?t=0020

when not using Apache's docroot as nZEDb's root
### Actual behaviour

links are like

http://server/browse?t=0000
http://server/browse?t=0010
http://server/browse?t=0020
### Steps to reproduce the behaviour

Have nzedb run underneath Apache's docroot, select the Alpha template and browse to Other -> Misc

Here is a patch for the Alpha template. I've seen the same errors in the Default and Gamma template too.

```
--- www/themes/Alpha/templates/headermenu.tpl.bak   2016-08-19 10:55:32.328006998 +0100
+++ www/themes/Alpha/templates/headermenu.tpl   2016-08-19 10:59:22.568006998 +0100
@@ -144,12 +144,12 @@
            {/if}
        {/foreach}
        <li class="dropdown">
-           <a id="cat8" class="dropdown-toggle" data-toggle="dropdown" href="#">Other <b class="caret"></b></a>
+           <a id="cat8" class="dropdown-toggle" data-toggle="dropdown" href="{$smarty.const.WWW_TOP}/other">Other <b class="caret"></b></a>
            <ul class="dropdown-menu" role="menu" aria-labelledby="cat3">
-               <li><a href="/browse?t={$catClass::OTHER_ROOT}">Other</a></li>
+               <li><a href="{$smarty.const.WWW_TOP}/browse?t={$catClass::OTHER_ROOT}">Other</a></li>
                <hr>
-               <li><a href="/browse?t={$catClass::OTHER_MISC}">Misc</a></li>
-               <li><a href="/browse?t={$catClass::OTHER_HASHED}">Hashed</a></li>
+               <li><a href="{$smarty.const.WWW_TOP}/browse?t={$catClass::OTHER_MISC}">Misc</a></li>
+               <li><a href="{$smarty.const.WWW_TOP}/browse?t={$catClass::OTHER_HASHED}">Hashed</a></li>
            </ul>
        </li>
    {/if}
```

The same applies to the "nZEDb" link to the left of the top menu.

```
--- www/themes/Alpha/templates/basepage.tpl.bak 2016-08-19 12:02:11.748006998 +0100
+++ www/themes/Alpha/templates/basepage.tpl 2016-08-19 12:03:14.400006998 +0100
@@ -160,7 +160,7 @@
                style="min-height:30px;height:30px;min-width:1120px;background:none;margin-bottom:0;">
            <div class="container">
                <div class="navbar-header">
-                   <a class="navbar-brand" href="/">{$site->title|default:'ಠ_ಠ'}</a>
+                   <a class="navbar-brand" href="{$smarty.const.WWW_TOP}/">{$site->title|default:'ಠ_ಠ'}</a>
                </div>
                {if $site->menuposition == 2}
                    {include file='topmenu.tpl'}
```

**Comment by DariusIII** [comment]
Links should never, NEVER look like:

> Expected behaviour
> 
> links should look like
> 
> http://server/nZEDb/www/browse?t=0000
> http://server/nZEDb/www/browse?t=0010
> http://server/nZEDb/www/browse?t=0020

As i told you on forums, fix your nZEDb.conf.

**Comment by hansenhans** [comment]
> Links should never, NEVER look like:

Care to explain? I can't and don't want to run nZEDb in Apache's docroot. I have other stuff running on this server too.

And if the links should not look like this, why ALL OTHER links do?

So I rephrase it for you

### Expected behaviour

```
http://server/<nzedb_root>/browse?t=0000
http://server/<nzedb_root>/browse?t=0010
http://server/<nzedb_root>/browse?t=0020
```

It should not matter in what subdirectory I run nZEDb and it never did before.

**Comment by DariusIII** [comment]
You dont need to run it from root, you need to adjust the www folder directive in nZEDb.conf to suit wherever you put nZEDb into.

As per https://github.com/nZEDb/nZEDb_Misc/blob/master/Guides/Installation/Ubuntu/Guide.md#step-8-installing-and-configuring-a-web-server

> <VirtualHost *:80>
>     ServerAdmin webmaster@localhost
>     ServerName localhost
>     DocumentRoot "/var/www/nZEDb/www"
>     LogLevel warn
>     ServerSignature Off
>     ErrorLog /var/log/apache2/error.log
>     <Directory "/var/www/nZEDb/www">
>         Options FollowSymLinks
>         AllowOverride All
>         Require all granted
>     </Directory>
>     Alias /covers /var/www/nZEDb/resources/covers
> </VirtualHost>

You adjust the DocumentRoot to suit your needs

DocumentRoot "/var/www/nZEDb/www" can be whatever you like and need.

That is why i told you to adjust your nZEDb.conf. 
**_Server should never output http://server/nZEDb/www/ pages as such_**

**Comment by hansenhans** [comment]
I can't change the default site on my server as the guide **recommends**. It is not necessary at all.  As I already wrote, I have other stuff running on this server **which would stop working** if I follow the recommendation.

It's a perfectly valid solution to leave the default site as is and have only this in /etc/apache2/sites-enabled/nZEDb.conf

```
    Alias /nZEDb/www/covers /var/www/nZEDb/resources/covers
    <Directory /var/www/nZEDb/www>
        Options FollowSymLinks
        AllowOverride All
        Order allow,deny
        allow from all
    </Directory>
```

Why is this so difficult to understand? Can someone else please comment on this?

Thanks for fixing it in the Gamma template. You need to do the same for the Alpha template too as per changelog.

Also, the fix needs to be applied to basepage.tpl as per my first post.

**Comment by DariusIII** [comment]
I did "fix" it in Alpha too, but in previous commit.  And which part of: 

> DocumentRoot "/var/www/nZEDb/www" can be whatever you like and need.

did **YOU** not understand?

**Comment by hansenhans** [comment]
> I did "fix" it in Alpha too, but in previous commit. 

Sorry, I only saw one commit attached to this bug. Thanks

> And which part of: DocumentRoot "/var/www/nZEDb/www" can be whatever you like and need.
> did YOU not understand?

Exactly, **I need** /var/www because I need to access /var/www/project1, /var/www/project2, ... and /var/www/nZEDb on this server. So, with /var/www as DocumentRoot I access nZEDb via http://server/nZEDb/www. What's wrong with that? I don't care whether the URL looks "ugly" with "nZEDB/www" in it. Who tells me how the URL should look like when my setup works well too?

If you wish we can continue this discussion in the forum. But I don't really see the point in it.

**Comment by kaibosh** [comment]
Are you trying to use an apache vhost without specifying the DocumentRoot? If so, that could lead to apache config issues.

You mention that when you use the normal DocRoot param it breaks other sites. One trick that might help is to have apache load the nzedb.conf vhost file after the ones of the other sites.

**Comment by DariusIII** [comment]
That is why vhosts in Apache exist.

**Comment by hansenhans** [comment]
> Are you trying to use an apache vhost without specifying the DocumentRoot? If so, that could lead to apache config issues.
> 
> You mention that when you use the normal DocRoot param it breaks other sites. One trick that might help is to have apache load the nzedb.conf vhost file after the ones of the other sites.

I only use the default vhost and of course with a DocumentRoot. I only access this server via IP address. I shouldn't have used "server" in my posts when I'm actually use the IP. Maybe this caused confusion here.

When I said it would break other sites I meant I can't change the DocumentRoot to anything else than /var/www.

> That is why vhosts in Apache exist.

You're right, but for this to work I need to setup DNS in my LAN. I didn't bother with this since everything works fine as is.

**Comment by kaibosh** [comment]
It's technically possible to set this up behind one IP/hostname using some funky rewrites, but using an internal DNS will in the long run be way easier than merging several logical vhosts into one monolithic config. You're then also ready for the "next cool thing" to be self-hosted.

**Comment by Wally73** [comment]
this isn't a bug , this is a bad vhost setup

**Comment by hansenhans** [comment]
It was a bug and it has been solved. Why else would you have "{$smarty.const.WWW_TOP}" in some links and not in others? The reason you didn't notice this bug is because you use /var/www/nZEDb/www as DocumentRoot. If you don't want people using their own perfectly working setup then remove these bl**dy "{$smarty.const.WWW_TOP}" from all links. Jeez...

Why is everybody questioning my vhost configuration? It works just fine without the need of other than a default vhost if all links have "{$smarty.const.WWW_TOP}" in it. Period.

**Comment by Wally73** [comment]
i have 12 vhosts on my server works fine with one default. so because you're so ignorant nZEDb has to change???

**Comment by thomasboehm** [comment]
It's like talking to stubborn kids here. Are you able to read and most importantly, to understand?

I don't want nzedb to change anything, just to finish what you started. YOU (the nzedb devs) wrote the code, but forgot "{$smarty.const.WWW_TOP}" for 4 out of 20+ links. Why are we still arguing about that?

I have 1 vhosts on my server (the default) and it works fine too, so what?

Or maybe the bug is the existence of "{$smarty.const.WWW_TOP}" on all other links? Make up your mind, either way, it's a bug.

I surely won't bother submitting bugs in the future...

**Comment by kevinlekiller** [comment]
I appreciate @hansenhans finding the issue and submitting a patch, but I'm disappointed at how both sides have taken the direction of this discussion, there's no need to fuel the frustration, let's try to keep the issue discussions more civil in the future, we are here to try to help each other, not work against each other.
