### ISSUE TITLE
MariaDB -- memory leak in latest Dev?

### ISSUE THREAD

**Issue by dilbaggins** [nZEDb/nZEDb#2238]
### Expected behaviour

memory released when queries are complete and not expanding to RAM capacity.

mysql version:  mysql  Ver 15.1 Distrib 10.1.16-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
nzedb version:

Hash: 95a220f03adf0f8ea914681e3f1575a358cb1295
XML version: v0.0.0-dev
Git version: v0.6.0.2
Looking up SQL patch version(s)
XML version: 448
 DB version: 448

Sphinx 2.2.11-id64-release (95ae9a6)

Ubuntu Version:   Ubuntu 14.04.5 LTS
### Actual behaviour

memory increases and isnt released.  i went from 16GB allocated to VM to 24GB of RAM and it also grew.  this didn't occur in previous releases running Tmux updating releases etc for weeks without the need for restart. i attempted to run the optimize_db (full) 
### Steps to reproduce the behaviour

run nzedb in tmux over the course of 2-3 days, look at htop response. increases and starts to use SWAP until all memory consumed.

**Comment by DariusIII** [comment]
Can you enable debugging, so we can see if some of our code is doing this (unlikely, but one can never know)? 
It might be a bug in MariaDB or Sphinx itself.

**Comment by dilbaggins** [comment]
will do.  as an FYI here is the size of my DB as another factor to consider :  
![image](https://cloud.githubusercontent.com/assets/3989347/17811298/fa9882fc-65ef-11e6-823c-756018bd1079.png)

**Comment by DariusIII** [comment]
My bet is that mysql consumes all the memory. Can you post your my.cnf here?

**Comment by dilbaggins** [comment]
on debugging, i am enabling the settign in /nzedb/config/settings.php (and logging to the nzedb/resources/log/nzedb.log correct?  (sorry want to understand debug best practice) 

here you are (my.cnf):

[mysqld]

# INNODB SETTINGS

#innodb_flush_method=O_DIRECT
#innodb_log_file_size=1G
#innodb_buffer_pool_size=2G
#innodb_force_recovery = 1

# INNODB

innodb_flush_method             = O_DIRECT
innodb_log_files_in_group       = 2
innodb_log_file_size            = 500M
innodb_file_format              = barracuda
innodb_flush_log_at_trx_commit  = 2
innodb_file_per_table           = 1
innodb_buffer_pool_size         = 8G
innodb_lock_wait_timeout        = 240
transaction-isolation           = READ-COMMITTED
#innodb_buffer_pool_instances    = 2
#innodb_use_sys_malloc           = 1

# \* Basic Settings

#
user        = mysql
pid-file    = /var/run/mysqld/mysqld.pid
socket      = /var/run/mysqld/mysqld.sock
port        = 3306
basedir     = /usr
datadir     = /var/lib/mysql
tmpdir      = /run/shm/mysqltemp
lc-messages-dir = /usr/share/mysql
skip-external-locking
#

# Instead of skip-networking the default is now to listen only on

# localhost which is more compatible and is not less secure.

bind-address        = 127.0.0.1
#

# \* Fine Tuning

#
key_buffer      = 2G
join_buffer_size        = 512K
sort_buffer_size        = 512M
read_rnd_buffer_size    = 512M
max_allowed_packet  = 64M
thread_stack        = 192K
thread_cache_size       = 50
group_concat_max_len    = 8192
tmp_table_size          = 1G 
max_heap_table_size     = 1G 

# This replaces the startup script and checks MyISAM tables if needed

# the first time they are touched

myisam-recover         = BACKUP
max_connections        = 500  
table_cache            = 4096
thread_concurrency     = 10
#

# \* Query Cache Configuration

#
query_cache_limit   = 16M
query_cache_size        = 256M
#

# \* Logging and Replication

#

# Both location gets rotated by the cronjob.

# Be aware that this log type is a performance killer.

# As of 5.1 you can enable the log at runtime!

#general_log_file        = /var/log/mysql/mysql.log
#general_log             = 1
#

# Error log - should be very few entries.

#
log_error = /var/log/mysql/error.log
#

# Here you can see queries with especially long duration

#log_slow_queries   = /var/log/mysql/mysql-slow.log
#long_query_time = 2
#log-queries-not-using-indexes
#

# The following can be used as easy to replay backup logs or for replication.

# note: if you are setting up a replication slave, see README.Debian about

# other settings you may need to change.

#server-id      = 1
#log_bin            = /var/log/mysql/mysql-bin.log
expire_logs_days    = 10
max_binlog_size         = 100M
#binlog_do_db       = include_database_name
#binlog_ignore_db   = include_database_name
#

# \* InnoDB

#

# InnoDB is enabled by default with a 10MB datafile in /var/lib/mysql/.

# Read the manual for more InnoDB related options. There are many!

#

# \* Security Features

#

# Read the manual, too, if you want chroot!

# chroot = /var/lib/mysql/

#

# For generating SSL certificates I recommend the OpenSSL GUI "tinyca".

#

# ssl-ca=/etc/mysql/cacert.pem

# ssl-cert=/etc/mysql/server-cert.pem

# ssl-key=/etc/mysql/server-key.pem

# InnoDB stores data in one or more data files forming the tablespace.

# If you have a single logical drive for your data, a single

# autoextending file would be good enough. In other cases, a single file

# per device is often a good choice. You can configure InnoDB to use raw

# disk partitions as well - please refer to the manual for more info

# about this.

#innodb_data_file_path = ibdata1:10M:autoextend

# Set this option if you would like the InnoDB tablespace files to be

# stored in another location. By default this is the MySQL datadir.

#innodb_data_home_dir = <directory>

# Number of IO threads to use for async IO operations. This value is

# hardcoded to 8 on Unix, but on Windows disk I/O may benefit from a

# larger number.

#innodb_write_io_threads = 24
#innodb_read_io_threads = 24

# If you run into InnoDB tablespace corruption, setting this to a nonzero

# value will likely help you to dump your tables. Start from value 1 and

# increase it until you're able to dump the table successfully.

#innodb_force_recovery=1

# Number of threads allowed inside the InnoDB kernel. The optimal value

# depends highly on the application, hardware as well as the OS

# scheduler properties. A too high value may lead to thread thrashing.

#innodb_thread_concurrency = 4

# If set to 1, InnoDB will flush (fsync) the transaction logs to the

# disk at each commit, which offers full ACID behavior. If you are

# willing to compromise this safety, and you are running small

# transactions, you may set this to 0 or 2 to reduce disk I/O to the

# logs. Value 0 means that the log is only written to the log file and

# the log file flushed to disk approximately once per second. Value 2

# means the log is written to the log file at each commit, but the log

# file is only flushed to disk approximately once per second.

#innodb_flush_log_at_trx_commit = 0

# Speed up InnoDB shutdown. This will disable InnoDB to do a full purge

# and insert buffer merge on shutdown. It may increase shutdown time a

# lot, but InnoDB will have to do it on the next startup instead.

#innodb_fast_shutdown

# The size of the buffer InnoDB uses for buffering log data. As soon as

# it is full, InnoDB will have to flush it to disk. As it is flushed

# once per second anyway, it does not make sense to have it very large

# (even with long transactions).

#innodb_log_buffer_size = 8M

# Size of each log file in a log group. You should set the combined size

# of log files to about 25%-100% of your buffer pool size to avoid

# unneeded buffer pool flush activity on log file overwrite. However,

# note that a larger logfile size will increase the time needed for the

# recovery process.

#innodb_log_file_size = 512M

# Total number of files in the log group. A value of 2-3 is usually good

# enough.

#innodb_log_files_in_group = 3

# Location of the InnoDB log files. Default is the MySQL datadir. You

# may wish to point it to a dedicated hard drive or a RAID1 volume for

# improved performance

#innodb_log_group_home_dir

# Maximum allowed percentage of dirty pages in the InnoDB buffer pool.

# If it is reached, InnoDB will start flushing them out agressively to

# not run out of clean pages at all. This is a soft limit, not

# guaranteed to be held.

#innodb_max_dirty_pages_pct = 90

# The flush method InnoDB will use for Log. The tablespace always uses

# doublewrite flush logic. The default value is "fdatasync", another

# option is "O_DSYNC".

#innodb_flush_method=O_DSYNC

# How long an InnoDB transaction should wait for a lock to be granted

# before being rolled back. InnoDB automatically detects transaction

# deadlocks in its own lock table and rolls back the transaction. If you

# use the LOCK TABLES command, or other transaction-safe storage engines

# than InnoDB in the same transaction, then a deadlock may arise which

# InnoDB cannot notice. In cases like this the timeout is useful to

# resolve the situation.

#innodb_lock_wait_timeout = 120

# The flush method InnoDB will use for Log. The tablespace always uses

# doublewrite flush logic. The default value is "fdatasync", another

# option is "O_DSYNC".

[mysqldump]
quick
quote-names
max_allowed_packet  = 256M

[mysql]
#no-auto-rehash # faster start of mysql but no tab completition

[isamchk]
key_buffer      = 16M

#

# \* IMPORTANT: Additional settings that can override those from this file!

# The files must end with '.cnf', otherwise they'll be ignored.

#
!includedir /etc/mysql/conf.d/

**Comment by dilbaggins** [comment]
sorry for the large text... odd i cant change the markup.

**Comment by DariusIII** [comment]
This:

> transaction-isolation = READ-COMMITTED

Always created problems for me. Which process is reported of using all of the RAM in htop?

**Comment by dilbaggins** [comment]
what setting would you change it to? 

![image](https://cloud.githubusercontent.com/assets/3989347/17811832/7bb36d64-65f2-11e6-90a7-2f27cf7c0d79.png)

**Comment by DariusIII** [comment]
Comment out that line. 
Anyway, i think you need to redo Sphinx configuration and do it from start, just to see if Sphinx is at fault here.

**Comment by dilbaggins** [comment]
when you say from start.  i have a sphinx restart script i do every so often.  i use the native Sphinx integration with MariaDB.  in looking at it.. the SE integration looks to be using an older version (2.2.6 vs the 2.2.11 of sphinx i have)

 ill try to update this

![image](https://cloud.githubusercontent.com/assets/3989347/17812087/96b12088-65f3-11e6-9c9e-1be7af66139f.png)

**Comment by DariusIII** [comment]
I mean the SphinxSearch itself, redo the config for nzedb recreate sphinx tables, populate them from start. Btw, version in Mariadb is what it is, you cannot update it and you don't need to.

**Comment by dilbaggins** [comment]
yep i did that as well created a script to do this (SphinxRestart.sh..  p.s. if you guys want to have it vs having to post the individual steps all the time :) ) 

#!/bin/bash
sudo service sphinxsearch stop
sudo rm /var/lib/sphinxsearch/data/*
sudo service sphinxsearch start
php /var/www/nZEDb/misc/sphinxsearch/create_se_tables.php 0 9312
php /var/www/nZEDb/misc/sphinxsearch/populate_rt_indexes.php releases_rt

**Comment by dilbaggins** [comment]
p.s. after making the change to my.cnf (re:  transaction-isolation = READ-COMMITTED)

seeing many more deadlocks.  odd.

**Comment by kaibosh** [comment]
It's normal to see deadlocks after going back to the default(more strict) transaction handling. There are other settings you can try. FWIW, my main system runs fine with that param set to read-committed and am not seeing any memory issues with mariadb. Am running complete sequential so YMMV.

**Comment by dilbaggins** [comment]
@kaibosh are you using the same versions i listed above?

**Comment by kaibosh** [comment]
No, on that server its mariadb-10.0.23. And nzed is v0.6.3.1.

Do you know what process is filling swap, is it really mariadb?

**Comment by stevenmcastano** [comment]
Install “smem” for linux and it will show you what processing are using swap.

*SMC

**Comment by dilbaggins** [comment]
why wouldnt i just use ATOP or HTOP to show swap usage in processes?

**Comment by stevenmcastano** [comment]
That works too, I just use smem because it’s clear and reports in kb so I can see exactly what I’m looking for. Any tool you want is fine, there are a bunch of ways to look at what’s swapping.

**Comment by dilbaggins** [comment]
@DariusIII  redid the sphinx config and run over 2 days. and now im up to 23G of the 24 allocated to VM.  restarting mysql alleviated it  but it is still increasing over time.  anything else i should try?

**Comment by dilbaggins** [comment]
looks like @Bart39 pushed an update that may address out of memory items.  applied and will close this after a few days of item is addressed.

**Comment by Bart39** [comment]
3476a949ed2c13dadbc1a9417fe701bbdf9d1b3a Should fix it (from mine and Enverex tests)

**Comment by dilbaggins** [comment]
i heart you @Bart39 :+1:

**Comment by niel** [comment]
Pushed to stable branch as v0.6.3.3

**Comment by scottia** [comment]
Started for me following @Bart39 patch above.  Disabled Sphinx, same results.  Looks like its been addressed for Mysql 5.7.13
https://bugs.launchpad.net/akonadi/+bug/1576930

**Comment by dilbaggins** [comment]
@scottia  open up another ticket i think because its not the same conditions (p.s. im on 14.04 and MariaDB) and have not seen this issue since the Bart patch

**Comment by scottia** [comment]
Na.  Am good, just sharing the bug.  Not any good at opening those.

**Comment by dilbaggins** [comment]
this appears to have come back: 

Looking up Git tag version(s)
Hash: 8e5203bc72c89703e0197dd4f3281f5cb8d555a5
XML version: vv0.6.4.1
Git version: v0.6.0.2
Looking up SQL patch version(s)
XML version: 448
 DB version: 448

**Comment by niel** [comment]
Looks like something is wrong with your versions. XML says v0.6.4.1 but git reports v0.6.0.2 They should match for stable branch

**Comment by dilbaggins** [comment]
@niel i have done nothing beyond ./zed update all  ( and it shows up to date:

/var/www/nZEDb$ ./zed update nzedb
Already up-to-date.

Running composer install process...
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
Checking database version...
Db: 448,        File: 448
Up to date.
You should clear your Smarty compiled template cache at: /var/www/nZEDb/resources/smarty/templates_c

why would there be a mismatch?

**Comment by DariusIII** [comment]
Now that i looked closely at your my.cnf, there might be a misconfiguration with caches that consumes you memory beyond what you have given to mysql. Can you check with mysqltuner script if limits are fine?

**Comment by dilbaggins** [comment]
nothing beyond the join_buffer _size item.

this started occuring since the latest pull of dev  (that is started again)

**Comment by DariusIII** [comment]
Can you run mysqltuner script?

**Comment by dilbaggins** [comment]
@DariusIII i already ran this and it only gave the join_buffer_size item.

**Comment by dilbaggins** [comment]
interesting that post process is eating up so many resources:

![image](https://cloud.githubusercontent.com/assets/3989347/18420307/6f257044-783d-11e6-9290-8187b811f114.png)

**Comment by DariusIII** [comment]
In php.ini set:
memory_limit = 1024M (or some other value, but do not use -1)

**Comment by dilbaggins** [comment]
@DariusIII you are being contrary to whats prescribed on the setup page:

_The following can be set to -1 if you have a large amount of system RAM (>=8GB):_

i have 24GB of RAM allocated to the VM.  just trying to understand rationale for suggestions

**Comment by DariusIII** [comment]
Rationale is simple: currently many bad releases cause memory leaks in rarinfo and additional postprocessing, and if you have memory_limit set to -1 rarinfo exhausts all of the available memory. That is why you need to set limits to it.

**Comment by dilbaggins** [comment]
got it, thank you Darius .  not questioning your expertise just followed the ubuntu build to the T and wanted to make sure i wasnt doing wholesale changes without noting the setup doc statements.  appreciate the help.  made the change going to let it "burn" in and see if it resolves before closing this one.

**Comment by dilbaggins** [comment]
exhibiting the same behavior it did prior to the patch as all memory is being consumed and now all CPU's are being used.  very odd.
