### ISSUE TITLE
Issues with the python scripts (with fix!)

### ISSUE THREAD

**Issue by langerak** [nZEDb/nZEDb#2240]
Hi,

I'm running nZEDb on Ubuntu 16.04 which uses MySQL 5.7 and causes some issues with the delivered python scripts.

For example the "fixreleasenames_threaded.py" script:

```
root@indexer:~# python /var/www/nZEDb/misc/update/python/fixreleasenames_threaded.py nfo

fixReleasesNames nfo Threaded Started at 14:56:12
Traceback (most recent call last):
  File "/var/www/nZEDb/misc/update/python/fixreleasenames_threaded.py", line 61, in <module>
    cur[0].execute(run, (int(perrun[0]) * int(run_threads[0])))
  File "/usr/local/lib/python2.7/dist-packages/cymysql/cursors.py", line 133, in execute
    self.errorhandler(exc, value)
  File "/usr/local/lib/python2.7/dist-packages/cymysql/cursors.py", line 35, in errorhandler
    self.connection.errorhandler(self, errorclass, errorvalue)
  File "/usr/local/lib/python2.7/dist-packages/cymysql/connections.py", line 118, in errorhandler
    raise errorvalue
cymysql.err.InternalError: (3065, u"Expression #1 of ORDER BY clause is not in SELECT list, references column 'nzedb.releases.postdate' which is not in SELECT list; this is incompatible with DISTINCT")
```

It is easily fixable by editing the script and removing the "DISTINCT" clause from the lines 60, 64, 68 and 72. Maybe it can be fixed within an update so that it works for everyone with MySQL 5.7? It will need some testing for previous MySQL versions but it at least fixed it in my situation.

And with the "requestid_threaded.py" script there is the following issue:

```
root@indexer:~# python /var/www/nZEDb/misc/update/python/requestid_threaded.py


RequestID Threaded Started at 15:32:14
Traceback (most recent call last):
  File "/var/www/nZEDb/misc/update/python/requestid_threaded.py", line 38, in <module>
    cur[0].execute("SELECT DISTINCT(g.id) FROM releases r INNER JOIN groups g ON r.groups_id = g.id WHERE r.nzbstatus = 1 AND r.preid = 0 AND r.isrequestid = 1 AND r.reqidstatus in (0, -1) OR (r.reqidstatus = -3 AND r.adddate > NOW() - INTERVAL " + request_hours + " HOUR)")
  File "/usr/local/lib/python2.7/dist-packages/cymysql/cursors.py", line 133, in execute
    self.errorhandler(exc, value)
  File "/usr/local/lib/python2.7/dist-packages/cymysql/cursors.py", line 35, in errorhandler
    self.connection.errorhandler(self, errorclass, errorvalue)
  File "/usr/local/lib/python2.7/dist-packages/cymysql/connections.py", line 118, in errorhandler
    raise errorvalue
cymysql.err.InternalError: (1054, u"Unknown column 'r.preid' in 'where clause'")
```

Upon examining the releases table it seems that the "preid" column is now called "predb_id". So if I change the following line (38):
`cur[0].execute("SELECT DISTINCT(g.id) FROM releases r INNER JOIN groups g ON r.groups_id = g.id WHERE r.nzbstatus = 1 AND r.preid = 0 AND r.isrequestid = 1 AND r.reqidstatus in (0, -1) OR (r.reqidstatus = -3 AND r.adddate > NOW() - INTERVAL " + request_hours + " HOUR)")`

To:
`cur[0].execute("SELECT DISTINCT(g.id) FROM releases r INNER JOIN groups g ON r.groups_id = g.id WHERE r.nzbstatus = 1 AND r.predb_id = 0 AND r.isrequestid = 1 AND r.reqidstatus in (0, -1) OR (r.reqidstatus = -3 AND r.adddate > NOW() - INTERVAL " + request_hours + " HOUR)")`

It fixes my issue with that script.

I hope it helps others if they run into this issue as well!

**Comment by DariusIII** [comment]
Python scripts are not maintained anymore, as they are replaced by their PHP counterparts now.

**Comment by langerak** [comment]
Ah, that explains a lot.Well, if anybody wants to have their Python scripts working, it's described here :)

**Comment by kevinlekiller** [comment]
8d93ca19e8b9be943e79a4d0da63f0964f286b44
