### ISSUE TITLE
Windows: Followed Wiki, error upon launching site

### ISSUE THREAD

**Issue by DrSeussFreak** [nZEDb/nZEDb#2246]
I performed all the steps on your wiki, and received no errors.  I did create a vhosts entry rather than put everything into htdocs, but otherwise, it is as you outlined.  Upon connecting to the site the first time, I receive

`Warning: include(D:\www\nZEDb\libraries\lithium\core\Libraries.php): failed to open stream: No such file or directory in D:\www\nZEDb\app\config\bootstrap\libraries.php on line 72

Warning: include(): Failed opening 'D:\www\nZEDb\libraries\lithium\core\Libraries.php' for inclusion (include_path='C:\xampp\php\PEAR') in D:\www\nZEDb\app\config\bootstrap\libraries.php on line 72

Fatal error: Uncaught ErrorException: Lithium core could not be found. Check the value of LITHIUM_LIBRARY_PATH in D:\www\nZEDb\app\config\bootstrap\libraries.php. It should point to the directory containing your /libraries directory. in D:\www\nZEDb\app\config\bootstrap\libraries.php:76 Stack trace: #0 D:\www\nZEDb\app\config\bootstrap.php(34): require() #1 D:\www\nZEDb\app\webroot\index.php(21): require('D:\www\nZEDb\ap...') #2 D:\www\nZEDb\index.php(36): require('D:\www\nZEDb\ap...') #3 {main} thrown in D:\www\nZEDb\app\config\bootstrap\libraries.php on line 76`

D:\www\nZEDb\libraries only contains  a single file ".gitignore".  Thoughts?

**Comment by Wally73** [comment]
you forgot the composer part of the install

**Comment by DrSeussFreak** [comment]
I don't see that in the Windows wiki, I see it in the sidebar, but nowhere did it say to run that from the Windows page.  I will follow that now, thanks.

**Comment by niel** [comment]
Windows guide is out of date. Feel free to update it.

**Comment by DrSeussFreak** [comment]
Done, with how I installed it, hopefully will work for the next person
