### ISSUE TITLE
Same Server as NewsNab+ - How do I split the DB?

### ISSUE THREAD

**Issue by DrSeussFreak** [nZEDb/nZEDb#2247]
I just configured this on the same windows box as NewzNab+ is installed on and it took those DB settings, rather than creating a new DB.  How can I go about forcing it to NOT use the NewzNab+ DB and create it's own?

**Comment by Wally73** [comment]
just create nzedb user and db for nzedb

**Comment by niel** [comment]
One of the install steps asks you to provide all of the database settings. Make sure you provide a different database name there. Be careful as your browser is likely to autocomplete it with previously used values.

**Comment by DrSeussFreak** [comment]
THe site came up without any prompting to install, it brought me to the login page of my NewzNab+ site.

**Comment by niel** [comment]
That's a problem with your vhost configuration then.

**Comment by DrSeussFreak** [comment]
`NameVirtualHost *:80

<VirtualHost *:80>
    DocumentRoot "D:/www/newznab/www"
    ServerName www.nab.com
</VirtualHost>

<VirtualHost *:80>
    DocumentRoot "D:/www/nZEDb"
    ServerName www.nZEDb.com
</VirtualHost>`

**Comment by DrSeussFreak** [comment]
haha, I forgot to add "www" to the end, fixed that and am all set now... Thanks, insert facepalm here.

**Comment by DrSeussFreak** [comment]
At install step, configured DB settings, hit next and 

`Fatal error: Uncaught Exception: The system cannot find the path specified. in D:\www\nZEDb\app\libraries\kbjr\Git.php\Git.php:317 Stack trace: #0 D:\www\nZEDb\app\libraries\kbjr\Git.php\Git.php(332): GitRepo->run_command('/usr/bin/git br...') #1 D:\www\nZEDb\app\libraries\kbjr\Git.php\Git.php(492): GitRepo->run('branch') #2 D:\www\nZEDb\app\libraries\kbjr\Git.php\Git.php(532): GitRepo->list_branches(true) #3 D:\www\nZEDb\nzedb\utility\Git.php(42): GitRepo->active_branch() #4 D:\www\nZEDb\nzedb\db\DbUpdate.php(72): nzedb\utility\Git->__construct() #5 D:\www\nZEDb\www\install\step2.php(153): nzedb\db\DbUpdate->__construct(Array) #6 {main} thrown in D:\www\nZEDb\app\libraries\kbjr\Git.php\Git.php on line 317`

**Comment by Bart39** [comment]
I know you have been updating the Windows guide on the wiki but did you verify that 'which git' worked ? Git path should be detected if you followed the steps

**Comment by DrSeussFreak** [comment]
`C:\Users\MFede>which git`
`C:\Program Files\Git\cmd\git.EXE`
