### ISSUE TITLE
[FEATURE REQUEST]rss feeds search for something functionality

### ISSUE THREAD

**Issue by OliverLeitner** [nZEDb/nZEDb#2250]
Hi guys,

this is a feature id love to have:

rss?t=search&q=....

any chance of getting that into nzedb?

thanks in advance

**Comment by OliverLeitner** [comment]
alternatively an rss output of the api data might work too, that way you could maybe have the feed functionality provided via the api interface, reducing your code a bit...

?t=search&q=linux&o=rss

**Comment by Bart39** [comment]
The api is already rss 2.0 compliant, so if you want to search use the api endpoints
