### ISSUE TITLE
the new Yenc module

### ISSUE THREAD

**Issue by crapzDK** [nZEDb/nZEDb#2252]
i have installed the new yenc .deb 

to confirm that it is loaded i run:
php -r "var_dump(get_loaded_extensions());" 

it was not i the list 
there was missing a symlink for 

this is the packed list where is shows that there must be a link 
""""
dpkg -L php7.0-yenc
/.
/etc
/etc/php
/etc/php/7.0
/etc/php/7.0/mods-available
/etc/php/7.0/mods-available/yenc.ini
/etc/php/7.0/cli
/etc/php/7.0/cli/conf.d
/usr
/usr/share
/usr/share/doc
/usr/share/doc/php7.0-yenc
/usr/share/doc/php7.0-yenc/changelog.gz
/usr/lib
/usr/lib/php
/usr/lib/php/20151012
/usr/lib/php/20151012/yenc.so
/etc/php/7.0/cli/conf.d/20-yenc.ini
""""
sudo ln /etc/php/7.0/mods-available/yenc.ini /etc/php/7.0/cli/conf.d/20-yenc.ini 

and now 
 php -r "var_dump(get_loaded_extensions());" 
  string(4) "yenc"
  [54]=>

but when i run 
/nzedb/misc/update/nix/multiprocessing$ php postprocess.php nfo
## it starts and then i says...

PHP Fatal error:  Uncaught Error: Call to undefined method app\extensions\util\yenc\adapter\NzedbYenc::decodeIgnore() in /var/www/nzedb/app/extensions/util/Yenc.php:64
Stack trace:
#0 /var/www/nzedb/nzedb/NNTP.php(1489): app\extensions\util\Yenc::decodeIgnore('\r\n=ybegin part=...')
#1 /var/www/nzedb/nzedb/NNTP.php(629): nzedb\NNTP->_getMessage('alt.binaries.in...', '<1472730568.980...')
#2 /var/www/nzedb/nzedb/NZBContents.php(131): nzedb\NNTP->getMessages('alt.binaries.in...', '1472730568.9805...', false)
#3 /var/www/nzedb/nzedb/Nfo.php(364): nzedb\NZBContents->getNfoFromNZB('1aacfac28a5fc19...', '1551600', '58', 'alt.binaries.in...')
#4 /var/www/nzedb/misc/update/nix/multiprocessing/.do_not_run/switch.php(246): nzedb\Nfo->processNfoFiles(Object(nzedb\NNTP), '', '1')
#5 {main}
##   thrown in /var/www/nzedb/app/extensions/util/Yenc.php on line 64

i will remove the .deb for now but let me know if you need me to debug on this

**Comment by niel** [comment]
My fault, I forgot to update the adapter class for the new extension. I'll get this updated asap.

**Comment by niel** [comment]
Updated on dev branch, please try.
Let me know more about the symlink from conf.d. to mods-available not being created. You're the second person to mention this but not everyone has had the problem.

**Comment by crapzDK** [comment]
just reinstalled the .deb same problem no symlink link

**Comment by crapzDK** [comment]
Same problem :/

fffffffffPHP Fatal error:  Uncaught Error: Class 'yenc' not found in /var/www/nzedb/app/extensions/util/yenc/adapter/NzedbYenc.php:28
Stack trace:
#0 /var/www/nzedb/app/extensions/util/yenc/adapter/NzedbYenc.php(33): app\extensions\util\yenc\adapter\NzedbYenc::decode('=ybegin part=1 ...', Array)
#1 /var/www/nzedb/app/extensions/util/Yenc.php(64): app\extensions\util\yenc\adapter\NzedbYenc::decodeIgnore('=ybegin part=1 ...')
#2 /var/www/nzedb/nzedb/NNTP.php(1489): app\extensions\util\Yenc::decodeIgnore('=ybegin part=1 ...')
#3 /var/www/nzedb/nzedb/NNTP.php(629): nzedb\NNTP->_getMessage('alt.binaries.bl...', '<0tPfeLEcuDTeJ2...')
#4 /var/www/nzedb/nzedb/processing/PostProcess.php(351): nzedb\NNTP->getMessages('alt.binaries.bl...', '0tPfeLEcuDTeJ2K...', false)
#5 /var/www/nzedb/nzedb/NZBContents.php(244): nzedb\processing\PostProcess->parsePAR2('0tPfeLEcuDTeJ2K...', '451826', '9', Object(nzedb\NNTP), 1)
#6 /var/www/nzedb/nzedb/NZBContents.php(129): nzedb\NZBContents->parseNZB('4d0e6d8e0dda271...', '451826', '9', true)
#7 /var/www/nzedb/nz in /var/www/nzedb/app/extensions/util/yenc/adapter/NzedbYenc.php on line 28

 git branch
  0.x
- dev

**Comment by niel** [comment]
The code for this is only in dev branch ;-)
oh wait, only saw the 0.x in your message because github formatted the \* dev line ;-)
I'll do some more testing and get back to you.

**Comment by crapzDK** [comment]
PHP Fatal error:  Uncaught Error: Class 'yenc' not found in /var/www/nzedb/app/extensions/util/yenc/adapter/NzedbYenc.php:28
Stack trace:
#0 /var/www/nzedb/app/extensions/util/yenc/adapter/NzedbYenc.php(33): app\extensions\util\yenc\adapter\NzedbYenc::decode('\r\n=ybegin part=...', Array)
#1 /var/www/nzedb/app/extensions/util/Yenc.php(64): app\extensions\util\yenc\adapter\NzedbYenc::decodeIgnore('\r\n=ybegin part=...')
#2 /var/www/nzedb/nzedb/NNTP.php(1489): app\extensions\util\Yenc::decodeIgnore('\r\n=ybegin part=...')
#3 /var/www/nzedb/nzedb/NNTP.php(629): nzedb\NNTP->_getMessage('alt.binaries.mo...', '<part1of1.QSjqw...')
#4 /var/www/nzedb/nzedb/processing/PostProcess.php(351): nzedb\NNTP->getMessages('alt.binaries.mo...', 'part1of1.QSjqwR...', false)
#5 /var/www/nzedb/nzedb/NZBContents.php(244): nzedb\processing\PostProcess->parsePAR2('part1of1.QSjqwR...', '322209', '1000141', Object(nzedb\NNTP), 1)
#6 /var/www/nzedb/nzedb/NZBContents.php(129): nzedb\NZBContents->parseNZB('4698f69c7266df6...', '322209', '1000141', true)
#7 in /var/www/nzedb/app/extensions/util/yenc/adapter/NzedbYenc.php on line 28

**Comment by crapzDK** [comment]
i can confirm the last fix, works still missing the symlink but mite be a system thing ....

**Comment by niel** [comment]
Rebuilt the deb file to hopefully fix the sym-linking issue. I would appreciate you trying it out.

**Comment by crapzDK** [comment]
Morning mate :D 
sudo dpkg -i php7.0-yenc_1.0.0-1_amd64.deb
dpkg: error processing archive php7.0-yenc_1.0.0-1_amd64.deb (--install):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 8 package 'php7.0-yenc':
 'Depends' field, reference to 'php': error in version: version number does not start with digit
Errors were encountered while processing:
 php7.0-yenc_1.0.0-1_amd64.deb

**Comment by niel** [comment]
Problem with the new packaging script :-(
Should be fixed now.

**Comment by crapzDK** [comment]
sudo dpkg -i php7.0-yenc_1.0.0-2_amd64.deb
Selecting previously unselected package php7.0-yenc.
(Reading database ... 187975 files and directories currently installed.)
Preparing to unpack php7.0-yenc_1.0.0-2_amd64.deb ...
Unpacking php7.0-yenc (1.0.0) ...
dpkg: dependency problems prevent configuration of php7.0-yenc:
 php7.0-yenc depends on php (= 7.0); however:
  Version of php on system is 1:7.0+35ubuntu6.
  Version of php on system, provided by php7.0:all, is <none>.

dpkg: error processing package php7.0-yenc (--install):
 dependency problems - leaving unconfigured
Processing triggers for php7.0-cli (7.0.8-0ubuntu0.16.04.2) ...
Errors were encountered while processing:
 php7.0-yenc

**Comment by crapzDK** [comment]
sudo dpkg -i php7.0-yenc_1.0.0-3_amd64.deb
Selecting previously unselected package php7.0-yenc.
(Reading database ... 187975 files and directories currently installed.)
Preparing to unpack php7.0-yenc_1.0.0-3_amd64.deb ...
Unpacking php7.0-yenc (1.0.0) ...
Setting up php7.0-yenc (1.0.0) ...
/var/lib/dpkg/info/php7.0-yenc.postinst: line 3: php-config: command not found
/var/lib/dpkg/info/php7.0-yenc.postinst: line 4: php-config: command not found
/var/lib/dpkg/info/php7.0-yenc.postinst: line 5: php-config: command not found
Creating symlink for configuration file.
Processing triggers for php7.0-cli (7.0.8-0ubuntu0.16.04.2) ...

**Comment by niel** [comment]
New version (-4) of the package to try when you get time.

**Comment by crapzDK** [comment]
the new build is working
