### ISSUE TITLE
Not getting any releases in Dev branch since latest pull

### ISSUE THREAD

**Issue by PsychoSid** [nZEDb/nZEDb#2254]
Hello,

Since the yEnc stuff has been changed over the past few days I am no longer getting any releases (well a few in books etc).

Nothing else has changed ?

Nothing appears to be throwing errors. Is there a step I have missed as part of the update ?

Thanks

**Comment by niel** [comment]
No changes should be needed. Need these details:
What version of PHP?
What yEnc method are you using?

**Comment by PsychoSid** [comment]
Hi,

nzedb@nzedb:~$ php -v
PHP 5.6.23-1+deprecated+dontuse+deb.sury.org~wily+1 (cli)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

nzedb@nzedb:~$ php -r "var_dump(get_loaded_extensions());" | grep ye
  string(22) "simple_php_yenc_decode"

Also have /usr/local/bin/yydecode and tried setting that also as a yEnc Type.

Thanks

**Comment by PsychoSid** [comment]
Latest commit's appear to have resolved/worked around this for now and all is up and running again. I see there are a few issues open regarding this one now so will close this.

Thanks for all the help/work.
