### ISSUE TITLE
yenc thingy not working 

### ISSUE THREAD

**Issue by ghost** [nZEDb/nZEDb#2258]
### Expected behaviour

PP to create previews etc
### Actual behaviour

Lots of (cB) in logs but no m,s,v,r
### Steps to reproduce the behaviour

Debian 8 
PHP 5.6

> dpkg -l |grep yenc
> ii  php5.6-yenc                       1.0.0                             amd64        no description given
> 
> php -m |grep yenc
> simple_php_yenc_decode
> yenc

Tried blank yenc type in /admin settings and also simple_php_yenc_decode both produce same problem.

**Comment by Wally73** [comment]
same issue here since the introduction of the new yenc class 
and parts in processing are slower too as before 
PHP 5.6.24-0+deb8u1 (cli)
10.1.17-MariaDB-1~jessie

**Comment by DariusIII** [comment]
Dont mix the class with yenc module. Problem, most likely, is with how new yenc module handles articles. PPA needs to download additional segments, and as far as i have experience, this is where it fails for some reason.

**Comment by ghost** [comment]
Tried removing simple_php_yenc_decode and running with just yenc and seen same problem. 
Removed both simple_php_yenc_decode & yenc and PP will work but very slow.

**Comment by sibeinsa** [comment]
same happening here.

**Comment by niel** [comment]
temporarily disable the simple_php_yenc_decode and/or newer yenc extension while we trace the cause of this. Edit the /etc/php/{5.6|7.0}/cli/conf.d/20-<modulename>.ini file and placing a semicolon (;) before the last line.

**Comment by sibeinsa** [comment]
I have mine working nicely again.
here are the steps I took to get it going again.
1.) removed the simple_php_yenc_decode as suggested by Niel from  /etc/php/{5.6|7.0}/cli/conf.d/20-.ini
2.) installed yydecode https://github.com/nZEDb/nZEDb/wiki/yydecode
3.) put /usr/local/bin/yydecode in yEnc Type on the site edit page
4.) shut down tmux
5.) re started tmux and enjoyed previews being added once again.
Im sure this is just a band aid but it worked for me.

**Comment by ghost** [comment]
I did the same sibeinsa, Wally suggested it in IRC. It's a work around but it's slower than simple_php_yenc_decode.

**Comment by sibeinsa** [comment]
Pulled the new update today and seems to be working great again. I can thank you guys enough for all the hard work and long hours you put in.

**Comment by ghost** [comment]
hows your performance sibeinsa? Mine still sucks

**Comment by ghost** [comment]
How do you test it @slug1982 ?

**Comment by ghost** [comment]
Just looking at the PP screen it takes 3+ seconds per release and on simple it used to fly by

**Comment by ghost** [comment]
Ok. Been using yydecode since the switch to PHP7, seems fast though.

**Comment by ghost** [comment]
Yea YY seemed faster than what am on now..

**Comment by ghost** [comment]
humm maybe about the same hard to tell when I flick between them

**Comment by sibeinsa** [comment]
much faster than PHP but seems about the same as it was before, never took notice and don't want to roll back on a snapshot to check.
One thing I have noticed is my average CPU load has defiantly picked up a bit and more ram is being used.
![09092016](https://cloud.githubusercontent.com/assets/6519303/18397933/ba440afa-76ca-11e6-893e-76369c4b857b.jpg)
