### ISSUE TITLE
Few php notices on 0.x php_errors.log

### ISSUE THREAD

**Issue by ghost** [nZEDb/nZEDb#2259]
Few php notices on 0.x
PHP Notice:  Undefined index: group_name in /var/www/nzedb/nzedb/http/XML_Response.php on line 434

PHP Notice:  Undefined index: style in /var/www/nzedb/www/pages/profileedit.php on line 83

PHP Notice:  Undefined offset: 1 in /var/www/nzedb/libs/zeebinz/rarinfo/rarinfo.php on line 1030

**Comment by niel** [comment]
Thanks. We'll get these fixed as soon as we can.
