### ISSUE TITLE
Install error step1.php

### ISSUE THREAD

**Issue by gl3nni3** [nZEDb/nZEDb#2260]
### Expected behaviour

Show step1 on the install
### Actual behaviour

The index page displays but the step1.php doesn't show.
### Steps to reproduce the behaviour

install the program according to https://github.com/nZEDb/nZEDb_Misc/blob/master/Guides/Installation/Ubuntu/Guide.md on ubuntu 16.04 in a vm on unraid

**Comment by jaybird2203** [comment]
Issue has been addressed in Dev branch as we've been informed, issue is with fresh installs only at this time.

Should be pushed to 0.x soon enough

**Comment by niel** [comment]
See issue #2257
