### ISSUE TITLE
Installation Error (Windows)

### ISSUE THREAD

**Issue by DrSeussFreak** [nZEDb/nZEDb#2261]
Running through the install on Windows.  Provided all settings after getting a clear pre-flight checklist, and as soon as I hit "Setup Database" I receive the following error

> Fatal error: Uncaught Exception: The system cannot find the path specified. in D:\www\nZEDb\app\libraries\kbjr\Git.php\Git.php:317 Stack trace: #0 D:\www\nZEDb\app\libraries\kbjr\Git.php\Git.php(332): GitRepo->run_command('/usr/bin/git br...') #1 D:\www\nZEDb\app\libraries\kbjr\Git.php\Git.php(492): GitRepo->run('branch') #2 D:\www\nZEDb\app\libraries\kbjr\Git.php\Git.php(532): GitRepo->list_branches(true) #3 D:\www\nZEDb\nzedb\utility\Git.php(42): GitRepo->active_branch() #4 D:\www\nZEDb\nzedb\db\DbUpdate.php(72): nzedb\utility\Git->__construct() #5 D:\www\nZEDb\www\install\step2.php(153): nzedb\db\DbUpdate->__construct(Array) #6 {main} thrown in D:\www\nZEDb\app\libraries\kbjr\Git.php\Git.php on line 317

I do have git installed properly

> C:\Users\MFede>which git
> C:\Program Files\Git\cmd\git.EXE

**Comment by DrSeussFreak** [comment]
Just grabbed the latest code, and now I get a blank page saying (on url http://www.nz.com/install/step2.php?) - www.nz.com is the local address in my hosts file for nzedb

```
The www.nz.com page isn’t working

www.nz.com is currently unable to handle this request.
HTTP ERROR 500
```

**Comment by niel** [comment]
Stable branch was updated minutes ago. Make sure you did get the latest.

**Comment by kevinlekiller** [comment]
Bug with Git.php, doesn't look like it will ever get fixed.

https://github.com/kbjr/Git.php/issues/47

https://github.com/kbjr/Git.php/pull/48

**Comment by DrSeussFreak** [comment]
@niel - I am on the latest

> From https://github.com/nZEDb/nZEDb
> - branch            0.x        -> FETCH_HEAD
>   Already up-to-date.
>   Press any key to continue . . .

@kevinlekiller - do you know of a workaround?

**Comment by kevinlekiller** [comment]
Use https://github.com/kbjr/Git.php/pull/48

**Comment by DrSeussFreak** [comment]
So we need to enable windows_mode, any ideas on how to do this?

**Comment by kevinlekiller** [comment]
No, just change the line 34 to protected static $bin = 'git';

https://github.com/kbjr/Git.php/pull/48/files#diff-6921b06c8f5b902ba98d065306469673L34

**Comment by DrSeussFreak** [comment]
And that did the trick!  Thanks!!!

**Comment by kevinlekiller** [comment]
No problem, it's too bad they won't fix the issue, I've bumped it a few times, looks like a dead project.

**Comment by DrSeussFreak** [comment]
They seem inclined to leave the hardcoding, as someone pointed out, it has been there since the dawn of time.  I agree, that making it dynamic would make more sense.

**Comment by kevinlekiller** [comment]
An alternative is for nzedb to use https://github.com/josh4trunks/Git.php/tree/patch-1 instead of kjbr/Git.php

Maybe @niel can change it to that?
