### ISSUE TITLE
Rarinfo exceeding php memory limits.

### ISSUE THREAD

**Issue by EDChurly** [nZEDb/nZEDb#2263]
### Expected behaviour

php processes do not exceed 1024MB memory
### Actual behaviour

Getting memory constraint issues on rarinfo.php

PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 32 bytes) in /var/www/nZEDb/libs/zeebinz/rarinfo/rarinfo.php on line 1381

Note - I believe devs are aware of this issue and is a common issue currently, but I could not see an open Issue on it.  Feel free to delete/cross reference if there is.
### Steps to reproduce the behaviour

Enable post processing.

**Comment by EDChurly** [comment]
Note - this is in version v0.6.4.1

**Comment by ghost** [comment]
Happened to me too with previous nzedb master.

**Comment by ghost** [comment]
Just checked my logs, am also seeing a lot of this

**Comment by niel** [comment]
@Fossil01 we don't have a "master", so do you mean stable (0.x) branch?

@all It would help massively, if we could get some stack traces or similar debugging info on this. A RAR guaranteed to cause this issue would be tremendously helpful.

**Comment by ghost** [comment]
Yes 0.x

**Comment by Bogenbroom** [comment]
If i use unrar instead of rarinfo i get lots of segfaults:

`php7.0[28017]: segfault at 28 ip 0000564169ba992f sp 00007ffded3b46a0 error 4 in php7.0[564169a44000+3ab000]`

Here's an nzb, hope it helps.
[rmrzfwrhdjfhkfkshfskf.zip](https://github.com/nZEDb/nZEDb/files/467759/rmrzfwrhdjfhkfkshfskf.zip)

**Comment by Wally73** [comment]
which version of unrar??? 
i use unrar5.40 i rarely have issues 
http://rarlabs.com/download.htm

**Comment by DariusIII** [comment]
@Wally73 depends on activated groups.

**Comment by Bogenbroom** [comment]
unrar 5.30 beta 2
I think that's the default version on Ubuntu 16.04.1

**Comment by ghost** [comment]
UNRAR 5.40 beta 3

**Comment by DariusIII** [comment]
Follow this guide to install latest unrar:

https://github.com/nZEDb/nZEDb_Misc/blob/master/Guides/Installation/Ubuntu/Guide.md#step-10-installing-extra-software

**Comment by Bogenbroom** [comment]
installed unrar 5.40, still segfaults

**Comment by EDChurly** [comment]
I think we're talking about two different issues now, the memory leak, and a seg fault (I don't get the seg fault)

Upgrading to unrar 5.4 has NOT fixed the memory leak, allowed memory size still being exceeded.

Happy to try and get a stack trace or other debug info, but may need some guidance on whats required.   I tried to get something from gdb but I think my skills maybe deficient to get meaningful output.

**Comment by DariusIII** [comment]
Unrar cannot fix the memory exhaustion, just because it is not an unrar problem, but rarinfo one.

**Comment by DariusIII** [comment]
And @Bogenbroom please open new issue, as segfaults in unrar have nothing to do with this issue.

**Comment by kevinlekiller** [comment]
Need some example rar files (which cause the issue), add issue here with them: https://github.com/nZEDb/rarinfo

**Comment by Bogenbroom** [comment]
@DariusIII:
Oh i bet it is exactly the same issue

**Comment by DariusIII** [comment]
Nope it's not.

**Comment by zeebinz** [comment]
If someone posts a rar sample I'll fix it upstream.

**Comment by Bogenbroom** [comment]
The latest PHP update (7.0.11-1+deb.sury.org) seems to have fixed my segfault problem

**Comment by DariusIII** [comment]
https://github.com/zeebinz/rarinfo/issues/9#issuecomment-249521972

**Comment by LeeThompson** [comment]
I think I found the issue, proposed fixes for zeebinz's branch, should work in others but may require modification.

[rarinfo.php](http://pastebin.com/06jWCEFV)
[zipinfo.php](http://pastebin.com/kJiG3HFL)

The short version is rarinfo when processingExtraBlocks does not check to see if the offset is already at the length before adding the extra_block value.    If it happens to be at the end, it basically reads unallocated memory and php goes into a loop until memory_limit is reached.

**Comment by niel** [comment]
@LeeThompson Thanks for the work. Could you do a PR against dev branch please. Copy/pasting those huge files in would introduce too many unnecessary changes, and makes comparing them impossible.

**Comment by LeeThompson** [comment]
@niel, I can give that a try, I don't actually run nZEBb so someone will need to test it.

**Comment by niel** [comment]
lol that's fine, as it was what I was trying to do anyhow ;-)

**Comment by LeeThompson** [comment]
@neil, I'll do my best.  I actually haven't ever done a pull request before so this will be... interesting.

Should this go horribly wrong here are the actual changes made  (against current https://github.com/zeebinz/rarinfo master).

**rarinfo.php**

Line 1244:

from:

`$end = $this->offset + $block['data_size'];`

to:

```
if ($this->offset < $this->length) {
    $end = $this->offset + $block['data_size'];
} else {
    $end = $this->length;
}
```

Line 1277:

from:

`$end = $this->offset + $block['extra_size'];`

to:

```
if ($this->offset < $this->length) {
    $end = $this->offset + $block['extra_size'];
} else {
    $end = $this->length;
}
```

**zipinfo.php**

Line 731:

from:

`$end = $this->offset + $record['extra_length'];`

to:

```
if ($this->offset < $this->length) {
    $end = $this->offset + $record['extra_length'];
} else {
    $end = $this->length;
}
```

**Comment by niel** [comment]
ok, I can work with that. Are the line numbers from zeebinz's original or our bundled version?

**Comment by DariusIII** [comment]
Zeebinz.

**Comment by dilbaggins** [comment]
still seeing a Fatal error in rarinfo:  
![image](https://cloud.githubusercontent.com/assets/3989347/19204383/9353982a-8caa-11e6-9ad3-5842541cb07a.png)

**Comment by niel** [comment]
@dilbaggins what branch are you on?

**Comment by dilbaggins** [comment]
Looking up Git tag version(s)
Hash: 9c7724e53dae6df2604fb29aa98d23c8e21cdf9c
XML version: v0.0.0-dev
Git version: v0.6.4.1
Looking up SQL patch version(s)
XML version: 449
 DB version: 449

**Comment by niel** [comment]
Are you sure you are up to date. That "XML version" should be showing v0.6.5.0 and SQL patch should be 450, if you're on dev branch as that output looks like.

**Comment by dilbaggins** [comment]
i just updated (i bet you were mid checkin when i grabbed perhaps..)
this is what i see when i do the .zed update all:

./zed update all
Already up-to-date.

Running composer install process...
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
Checking database version...
**Db: 450,        File: 450**
Up to date.
You should clear your Smarty compiled template cache at: /var/www/nZEDb/resources/smarty/templates_c

Looking up Git tag version(s)
Hash: d779f3979aebae309e16ee1ef7977ff7fd845bcb
XML version: v0.0.0-dev
Git version: v0.6.4.1
Looking up SQL patch version(s)
XML version: 450
 DB version: 450

**Comment by niel** [comment]
That's better. Still having the problem?

**Comment by niel** [comment]
I've seen this in action myself now :-( Will try debugging it over the weekend if I can find the time.

**Comment by LeeThompson** [comment]
@niel I'm not sure if this will help in this case, but in the other the actual statement that threw PHP into a loop until `memory_limit` was `'size'   => $size = $this->getVarInt(),` in the block: 

```
$rec = array(
    'name'   => 'Unknown',
    'offset' => $this->offset,
    'size'   => $size = $this->getVarInt(),
    'next'   => $this->offset + $size,
    'type'   => $this->getVarInt(),
);
```

`getVarInt` itself _does_ check to see if it's at the end or not, if it is it returns `0`, but for some reason, php still completely throws a fit (from 5.5.30 all the way up to 7.0.1).

**Comment by niel** [comment]
@LeeThompson That makes sense, it is still trying to assign memory space for the integer. The attempt to assign isn't really the problem, just a symptom. The process should be terminating and it isn't apparently.

**Comment by LeeThompson** [comment]
@niel Yup, I actually see it as a PHP bug in a way since it should not just loop like that but anyway; I don't run nZEDb myself but if you can point me at the post(s) doing it, I'd be happy to help debug using Zeebinz as base.

**Comment by zeebinz** [comment]
This should now  have been fixed upstream with https://github.com/zeebinz/rarinfo/commit/719979f117db1bed667e1fc9a51ce92df37d6850

Let me know if not.

**Comment by niel** [comment]
@zeebinz thanks. I'll look into this today.

**Comment by niel** [comment]
Seems Darius already updated it ;-)

**Comment by zeebinz** [comment]
Darius 'port fix' has a typo, so not fixed there yet https://github.com/nZEDb/nZEDb/commit/bdc06eae4b8c0e5326210bfa2322d40b4a03a963#commitcomment-19430712

Edit: may I also suggest running the provided PHPUnit tests on such changes that aren't from upstream, they take mere seconds to run and catch errors like this easily.

**Comment by DariusIII** [comment]
@niel fixed it here https://github.com/nZEDb/nZEDb/commit/4221bf4575c36685c8f26a763a0b1fe6c2a71cdb

It was mistake done by rushing.
