### ISSUE TITLE
PP - NFO shows Fatal Error

### ISSUE THREAD

**Issue by dilbaggins** [nZEDb/nZEDb#2265]
### Expected behaviour

Post Process NFO runs without issue.
### Actual behaviour

This error occurs:
 ![image](https://cloud.githubusercontent.com/assets/3989347/18499954/7ccf775a-7a11-11e6-887d-065c4eea8b68.png)
### Steps to reproduce the behaviour

latest Dev.

**Comment by niel** [comment]
Pushed a temporary fix. Let me know if it works or not please.

**Comment by dilbaggins** [comment]
broke....

![image](https://cloud.githubusercontent.com/assets/3989347/18510643/22809d6a-7a4d-11e6-98d4-827e0dbfe99e.png)

**Comment by scottia** [comment]
+1

[14-Sep-2016 09:01:23 America/Chicago] PHP Catchable fatal error:  Argument 1 passed to nzedb\Nfo::NfoQueryString() must be an instance of nzedb\DB, instance of nzedb\db\Settings given, called in /var/www/nZEDb/nzedb/Tmux.php on line 544 and defined in /var/www/nZEDb/nzedb/Nfo.php on line 264

**Comment by niel** [comment]
Committed hopeful fix for this.
BTW guys, you can also hop into IRC channel to let me know you updated this issue. Sometimes I don't notice for hours otherwise.

**Comment by dilbaggins** [comment]
![image](https://cloud.githubusercontent.com/assets/3989347/18521547/79af8574-7a7a-11e6-8613-bec087b4549b.png)

(sorry on certain networks im blocked from using IRC)  my apologies @niel

**Comment by scottia** [comment]
Can't access IRC from the office @neil but I will remember for next time.  At the moment am upgrading Ubuntu to 16.04 and restoring Db.

**Comment by dilbaggins** [comment]
sidebar -@scottia thinking of upping my dev build to 16.04.  let me know what you run into.

**Comment by scottia** [comment]
@dilbaggins  Am using the following for advice, upgrading to 16.04 and a fresh install of nZEDb with a Db restore.  Will see how it goes.  I expect many obstacles...
https://www.digitalocean.com/community/tutorials/how-to-upgrade-to-ubuntu-16-04-lts

**Comment by niel** [comment]
Pushed fix for that last screenshot.

Main problem with U16.04 currently is the version of tmux it has. If you don't use tmux then nothing seriously stopping using it.

**Comment by dilbaggins** [comment]
latest pull resolved the MaxRetries item,

**Comment by dilbaggins** [comment]
this came back after a while:  
![image](https://cloud.githubusercontent.com/assets/3989347/18532512/80720dc0-7aaa-11e6-8980-636cfcf0a40b.png)

**Comment by niel** [comment]
Fix pushed.
