### ISSUE TITLE
Post Process - Maxing out my CPU's.....

### ISSUE THREAD

**Issue by dilbaggins** [nZEDb/nZEDb#2269]
### Expected behaviour

Less CPU usage and memory usage when Post processing All
### Actual behaviour

100% when running tmux no matter what. (if i hand cancel via control+C it reins the cpu usage back):

![image](https://cloud.githubusercontent.com/assets/3989347/18768779/920653b0-80f5-11e6-83ba-8881f70b9db2.png)
### Steps to reproduce the behaviour

latest dev build and run tmux

**Comment by niel** [comment]
capture showing the top lines using CPU would be better.
Also watch them and see if they are continually changing around, i.e. process finishes then gets replaced by a new one in a cycle.

**Comment by dilbaggins** [comment]
![image](https://cloud.githubusercontent.com/assets/3989347/18769699/6dc56c68-80fd-11e6-968b-c29bea74df9d.png)

**Comment by dilbaggins** [comment]
tmux has been running for a couple of days but noticing wayyyy more CPU usage. 

a couple of weeks ago it was fine after you made some changes which is odd.

**Comment by niel** [comment]
Honestly, that looks pretty normal. How quickly do those lines with "/usr/bin/php5" change?

**Comment by dilbaggins** [comment]
dont know @niel the last year or so its never been pegged for a whole day. the processAdditional.php runs stay up with the similar releaseID's for a while

**Comment by niel** [comment]
Are you using the php-yenc extension, and if so, what version?

**Comment by dilbaggins** [comment]
running your deb (sorry i was under the impression it was integrated in the patch to dev

i.,e. this from changelog: Chg: Update hint for yydecode setting in site-edit.

 php5.6-yenc depends on php (>> 5.6); however:
  Package php is not installed.

dpkg: error processing package php5.6-yenc (--install):
 dependency problems - leaving unconfigured
Processing triggers for php5.6-cli (5.6.26-1+deb.sury.org~trusty+1) ...
Errors were encountered while processing:

heres my php version:  PHP 5.6.26-1+deb.sury.org~trusty+1 (cli)

**Comment by niel** [comment]
But which version of php-yenc? It's part of the file name of the deb file.

**Comment by dilbaggins** [comment]
php5.6-yenc_1.2.2_amd64.deb

**Comment by niel** [comment]
ok. that might explain the additional CPU usage if you recently updated to it. It has fixes in it that improve handling of multi-part yEnc attachments, but that will increase CPU use as it now processes stuff it couldn't before.

**Comment by dilbaggins** [comment]
got over that hurdle but for some reason php 7 needed to be installed... SHEESH! 

getting this error.  ill google it:  PHP Fatal error:  Uncaught PDOException: could not find driver in /var/www/nZEDb/libraries/lithium/data/source/Database.

**Comment by dilbaggins** [comment]
fixed.  php7.0-mysql and simpleXML manual update.

keeping the ticket open as i let this "burn" in

you guys love keeping me on my toes :)

**Comment by niel** [comment]
why would you have to upgrade to PHP 7?

**Comment by dilbaggins** [comment]
no idea... for some reason it prompted it required it when running dpkg -i

**Comment by niel** [comment]
Sounds like you tried to install the wrong version. There are two files on the site. One for 5.6 one for 7.0

**Comment by dilbaggins** [comment]
nope... **php5.6-yenc_1.2.2_amd64.deb: Debian binary package (format 2.0)**

**Comment by niel** [comment]
weird, I'll check my installer script

**Comment by dilbaggins** [comment]
lost memcached now... AHHHH!H!!!

The memcached extension is not loaded!

**Comment by niel** [comment]
Did you have both 5.6 and 7.0 installed?

**Comment by dilbaggins** [comment]
removed 7.0.  now im just on 5.6:

 php -v
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20131226/yenc.so' - /usr/lib/php/20131226/yenc.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP 5.6.26-1+deb.sury.org~trusty+1 (cli)

**Comment by niel** [comment]
I'm going to build a new version of the package for 5.6

**Comment by dilbaggins** [comment]
what i get when attempted to add dpkg:

 php5.6-yenc : Depends: php (> 5.6)
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).
:/var/www/nZEDb/misc/testing/Tests$ sudo apt-get -f install
Reading package lists... Done
Building dependency tree
Reading state information... Done
Correcting dependencies... Done
The following extra packages will be installed:
  libapache2-mod-php7.0 php php7.0 php7.0-cli php7.0-common php7.0-json
  php7.0-opcache php7.0-readline
The following NEW packages will be installed:
  libapache2-mod-php7.0 php php7.0 php7.0-cli php7.0-common php7.0-json
  php7.0-opcache php7.0-readline

**Comment by dilbaggins** [comment]
Unable to load dynamic library '/usr/lib/php/20131226/yenc.so'

think this has to do with the removal of the yenc package i just did.

**Comment by niel** [comment]
Updated the 5.6 deb package on the releases page.

**Comment by dilbaggins** [comment]
good to go.  but still having:  the memcached extension is not loaded but i see it in dynamic extensions in /etc/php5/cli/php.ini.

**Comment by dilbaggins** [comment]
@niel  almost there.  just seeing this:

memcached' already loaded in Unknown on line 0 when running my tmux scripts.  its crazy i see no referrences at all to memcached.

**DISREGARD:  I had to manually remove from dynamic extensions even though our documentation said its required in CLI**

**Comment by danpopHP** [comment]
running overnight.  still high in terms of CPU count and High Memory usage.

**Comment by dilbaggins** [comment]
rarinfo fix has curtailed the high CPU usage.
