### ISSUE TITLE
Comic Books Categorized Under Magazines

### ISSUE THREAD

**Issue by Loopher** [nZEDb/nZEDb#2272]
### Expected behaviour

Comic books should be categorized under Books\Comics.
Technical books should be categorized under Books\Technical category.
### Actual behaviour

Posts from a.b.software are being placed under the Books\Comics category.  Comic book posts are being placed under the Books\Magazine category.
Posts from a.b.software are being placed under the Books\Technical category.

I found there are posts from other groups in here as well.  a.b.ghosts. a.b.triballs,  
### Steps to reproduce the behaviour

Reinstall Nzedb and use the latest dev build.

**Comment by DariusIII** [comment]
I see no book posts in a.b.software at all.

**Comment by Loopher** [comment]
Yes I agree with you, I was not implying that there are book posts in a.b.software, I should have said that software posts are being categorized as books.  These should have gone to a category under PC., not Books.  The Books category was working fine for me before my VM decided to crater and I had to start over from scratch.  To give you an idea, I have taken some snapshots.   Please take a look at these snapshots to see how the posts are being miscategorized.
![books-comics](https://cloud.githubusercontent.com/assets/4019048/19543850/e31bcfe6-963f-11e6-802a-6c7c60804d8b.JPG)
![books-ebook](https://cloud.githubusercontent.com/assets/4019048/19543847/e31ad866-963f-11e6-9b4a-069171437f90.JPG)
![books-foreign](https://cloud.githubusercontent.com/assets/4019048/19543848/e31aff3a-963f-11e6-8d13-e04e55f394dc.JPG)
![books-magazines](https://cloud.githubusercontent.com/assets/4019048/19543849/e31bc186-963f-11e6-8764-65f505ed8d31.JPG)
![books-technical](https://cloud.githubusercontent.com/assets/4019048/19543851/e31db3a6-963f-11e6-8a52-a88d11b565ad.JPG)

Just wanted to point this out in case someone else runs into it.
