### ISSUE TITLE
possible indexes of death

### ISSUE THREAD

**Issue by OliverLeitner** [nZEDb/nZEDb#2273]
expected: mariadb running flawlessly

what happened: i had the experience, that mariadb segfaulted on me, was unable to restart without a long repair session.

to reproduce: now that is tricky, i just had this happening to me, im not sure if theres actually anything, i thought id might report it, just in case...

theres actually an article which i came across, that might be of interrest: https://twindb.com/repair-corrupted-innodb-table-with-corruption-in-secondary-index/

**Comment by niel** [comment]
This isn't an issue with with nZEDb, so there is nothing we can do about it.
This information would be useful in the wiki somewhere.
