### ISSUE TITLE
Some NZB's not found

### ISSUE THREAD

**Issue by ghost** [nZEDb/nZEDb#2276]
Saw this in my nginx error log:

```
[error] 5521#5521: *85474 open() blablabla https://XXXX/details/b1d39bdaefcdc7d20317502931b2b3ce62b68293/Jersey.Boys.2014.720p.BluRay.x264.YIFY.mp4
```

That link cannot be opened in a browser, it throws 404. But when you remove the last part and just open it with the GUID it works:

```
https://XXXX/details/b1d39bdaefcdc7d20317502931b2b3ce62b68293
```

Any idea?

**Comment by DariusIII** [comment]
That is your theme error. Leave just the guid part in detail links.

**Comment by ghost** [comment]
I don't understand what you mean. To clarify, this works fine:

```
https://XXXXX/details/a4daa466a7edf2f5af2b05cd02811449b3a2d6be/VA-Summer_Heat_2010-2CD-FLAC-2010-c05
```

[EDIT]
Whenever you paste a REAL file extension after the URL it throws the 404. So replacing .mp4 with .txt doesnt work. Removing .mp4 works

**Comment by DariusIII** [comment]
Fix links in your theme.

**Comment by ghost** [comment]
I think it's a problem in either the code or nginx rewrites.

**Comment by DariusIII** [comment]
Your theme.

**Comment by DariusIII** [comment]
On every page of your theme that uses this:

`{$smarty.const.WWW_TOP}/details/{$mguid[$m@index]}/{$mname[$m@index]|escape:"url"}`

change it to:

`{$smarty.const.WWW_TOP}/details/{$mguid[$m@index]}}`

**Comment by ghost** [comment]
I know. But i've had it like that for 4 years, any way of keeping it? I like getting links and seeing the releasename in the link. That's how it was in NN+ back in the day.

**Comment by DariusIII** [comment]
Times change!
