### ISSUE TITLE
Can't delete releases based on category id

### ISSUE THREAD

**Issue by ghost** [nZEDb/nZEDb#2277]
php delete_releases.php tegories_id=equals=1000

Output:
Error: Invalid argument supplied: categories_id=equals=1000

**Comment by niel** [comment]
1000 is a category parent, there shouldn't be any releases under it directly. They will be under a more specific category or <catname>_OTHER

**Comment by ghost** [comment]
It isn't the categoryID. It didnt work on any of them.

**Comment by ghost** [comment]
Same problem here

**Comment by ghost** [comment]
change line 1158 to  
 case 'categories_id':
 in nzedb/ReleaseRemover.php

**Comment by ghost** [comment]
That worked. Created a PR for it.

**Comment by niel** [comment]
Damnit. The delete_releases.php shouldn't have been changed. I'll revert that change, please go back to using categoriesid.
