### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by ghost** [nZEDb/nZEDb#2278]
I'm getting a lot of these: `Segmentation fault (core dumped)` after which PP additional crashes until the next run. You can't see these errors in tmux but when running the single threaded `postprocess.php additional true` these errors are thrown.

Any idea how to fix? unrar is v5.4 and 7za v9.20

```
[14416653][4.4GB](cB)r(cB)!@&%rSegmentation fault (core dumped)
```

**Comment by niel** [comment]
What yEnc method are you using? simple, php-yenc, yydecode, or PHP?

**Comment by ghost** [comment]
php-yenc latest version

**Comment by ghost** [comment]
This is a NZB which causes the segfault error on my box:

https://gist.github.com/Fossil01/64e9f82631bf7cd8b0e54e5c28cebed9

When downloaded this specific example results on 1 rar (r20) of a rarset. Somehow zed fails to create a collection, Binsearch lists it as part of this collection: http://binsearch.info/?b=0015690975&g=alt.binaries.nl&p=CPP-gebruiker%40domein.nl+%28CPP-Gebruiker%29&max=250

Here's another one http://binsearch.info/?b=krC12VouS76Sfql1wOTT&g=alt.binaries.x&p=CPP-gebruiker%40domein.nl+%28CPP-Gebruiker%29&max=250

I have got output from the strace command, hit me up on IRC if you want that.

[EDIT] Looks like the problem existed before: http://forums.nzedb.com/index.php?topic=1817.0

**Comment by ghost** [comment]
If it's RARInfo, it this something we can adapt and use? https://github.com/matiasb/python-unrar

[EDIT] I was actually not even using rarinfo, I have it disabled in site-edit.
