### ISSUE TITLE
what storage engine does new created tpg tables have by default?

### ISSUE THREAD

**Issue by OliverLeitner** [nZEDb/nZEDb#2279]
just as the title says, a question...

i hope its reading the engine from the first table to decide.

**Comment by niel** [comment]
It uses whatever is already in use. So if you have changed from MyISAM to InnoDb it will be InnoDb, otherwise still MyISAM.

**Comment by OliverLeitner** [comment]
and what about the dynamic or compressed formatting that you can apply via the converter script?

**Comment by niel** [comment]
I'd have to check the code to be certain, but AFAIR, it uses the original table and copies its structure repeatedly, so the tpg tables should be identical in all but data.

**Comment by b3rs3rk** [comment]
As the devs stated, doing a `SHOW CREATE TABLE collections;` (Or binaries, parts, missed parts) you will see exactly what is copied when the `CREATE TABLE collections_%% LIKE collections;` is run.
