### ISSUE TITLE
unable to import nzb via web

### ISSUE THREAD

**Issue by ghost** [nZEDb/nZEDb#2280]
Running 0.x after selecting a nzb to import via admin/nzb-import.php you get error 500

I've no idea when this last worked. Using nginx 

error.log:
 for model `app\models\Settings`.' in /var/www/nzedb/libraries/lithium/data/Model.php:1479
Stack trace:
#0 /var/www/nzedb/libraries/lithium/data/Model.php(674): lithium\data\Model::connection()
#1 /var/www/nzedb/app/models/Settings.php(58): app\models\Settings::lithium\data{closure}(Array)
#2 /var/www/nzedb/libraries/lithium/data/Model.php(694): app\models\Settings::app\models{closure}(Array, Object(Closure))
#3 /var/www/nzedb/libraries/lithium/aop/Filters.php(229): app\models\Settings::lithium\data{closure}(Array)
#4 /var/www/nzedb/libraries/lithium/data/Model.php(697): lithium\aop\Filters::run('app\models\Sett...', 'find', Array, Object(Closure))
#5 /var/www/nzedb/app/models/Settings.php(81): lithium\data\Model::find('setting', Array)
#6 /var/www/nzedb/nzedb/Categorize.php(57): app\models\Settings::value('indexer.categor...')
#7 /var/www/nzedb/nzedb/NZBImport" while reading response header from upstream, client: x.x.x.x, server: host.com, request: "POST /admin/nzb-import.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "host.com", referrer: "https://host.com/admin/nzb-import.php"

2016/10/07 15:40:18 [error] 14214#0: *72288 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'lithium\core\ConfigException' with message 'The data connection `default` is not configured for model `app\models\Settings`.' in /var/www/nzedb/libraries/lithium/data/Model.php:1479
Stack trace:
#0 /var/www/nzedb/libraries/lithium/data/Model.php(674): lithium\data\Model::connection()
#1 /var/www/nzedb/app/models/Settings.php(58): app\models\Settings::lithium\data{closure}(Array)
#2 /var/www/nzedb/libraries/lithium/data/Model.php(694): app\models\Settings::app\models{closure}(Array, Object(Closure))
#3 /var/www/nzedb/libraries/lithium/aop/Filters.php(229): app\models\Settings::lithium\data{closure}(Array)
#4 /var/www/nzedb/libraries/lithium/data/Model.php(697): lithium\aop\Filters::run('app\models\Sett...', 'find', Array, Object(Closure))
#5 /var/www/nzedb/app/models/Settings.php(81): lithium\data\Model::find('setting', Array)
#6 /var/www/nzedb/nzedb/Categorize.php(57): app\models\Settings::value('indexer.categor...')
#7 /var/www/nzedb/nzedb/NZBImport" while reading response header from upstream, client: x.x.x.x, server: host.com, request: "POST /admin/nzb-import.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "host.com", referrer: "https://host.com/admin/nzb-import.php"

**Comment by niel** [comment]
I'll look into this

**Comment by niel** [comment]
Pretty sure I know the cause of this and there is actually a fix already committed. Unfortunately it is in a branch I haven't finished testing yet, so it hasn't made it into the latest code.
I would cherry pick the fix over, but I suspect that would create more problems than it is worth.

**Comment by ghost** [comment]
Fixed in latest 0.x

Cheers
