### ISSUE TITLE
Trakt no longer serving images via API

### ISSUE THREAD

**Issue by ghost** [nZEDb/nZEDb#2281]
Not sure if this is something that zed will need to adapt to, but here's the mail I got:

> TLDR; Images will no longer be served from the API starting October 31, 2016 due to greatly increased hosting costs. All other API functions will remain the same.

We regret that it has come to this, but starting October 31, 2016, we will no longer be able to serve images from our API. Our CDN has been amazing for the past 5 years, but as we’ve grown in popularity, the amount of traffic we’ve been pushing through them has gotten to the point that we are costing them an arm and a leg. 

The nitty gritty details. 
• Monthly traffic: 1 petabyte (85%+ images) 
• CDN projected cost: $15,000–20,000/mo 
• Trakt currently paying: $25/mo 

The three of us have been working on a way to keep the Trakt API and website running long into the future. The answer is to reduce the 850 terabytes of image traffic we are pushing out of the API each month. We will continue to serve every other aspect of our API and website the same way. 

The API still provides all this and more! 
• Real time scrobbling, manual checkins, and synced playback progress.
• Syncing your watched history, collections, and ratings to use Trakt as a cloud backup and sync between devices.
• Watchlists and custom lists that you can use for anything.
• Personalized and global calendars.
• Commenting, reviews and building your social graph.
• TV show and movie metadata.
• Content discovery and advanced searching.

**Transitioning**
The transition to other image resources should be smooth since Trakt provides IDs for services like TMDB, TVDB, Fanart.tv, and OMDB. All of these services have APIs which provide images. We wrote an article to help with this. 

All three of us are sad this has to happen, but unfortunately it must in order to keep the servers up and running. Removing images provides long term stability for the Trakt API and website.

**Comment by Wally73** [comment]
got the same mail (and on trakt itself etc :P ) most images come from fanart etc anyway afaik

**Comment by DariusIII** [comment]
Support for images from TraktTV has been removed from nZEDb.
