### ISSUE TITLE
Lithium PHP Errors

### ISSUE THREAD

**Issue by ghost** [nZEDb/nZEDb#2286]
```
2016/10/12 21:01:14 [error] 30053#30053: *38425333 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught lithium\core\ConfigException: The data connection `default` is not configured for model `app\models\Settings`. in /ssd/nzedb/libraries/lithium/data/Model.php:1479
Stack trace:
#0 /ssd/nzedb/libraries/lithium/data/Model.php(674): lithium\data\Model::connection()
#1 /ssd/nzedb/app/models/Settings.php(58): lithium\data\Model::lithium\data\{closure}(Array)
#2 /ssd/nzedb/libraries/lithium/data/Model.php(694): app\models\Settings::app\models\{closure}(Array, Object(Closure))
#3 /ssd/nzedb/libraries/lithium/aop/Filters.php(229): lithium\data\Model::lithium\data\{closure}(Array)
#4 /ssd/nzedb/libraries/lithium/data/Model.php(697): lithium\aop\Filters::run('app\\models\\Sett...', 'find', Array, Object(Closure))
#5 /ssd/nzedb/app/models/Settings.php(81): lithium\data\Model::find('setting', Array)
#6 /ssd/nzedb/nzedb/processing/tv/TV.php(65): app\models\Settings::value('..maxrageproces...')
#7 /ssd/nzedb/nzedb/processing/tv/TraktTv.php(70): nzedb\processing\tv\TV->__construct(" while reading response header from upstream, client: 77.174.61.47, server: serverhere, request: "GET /details/3c49de4eee90c99dfbebbb6b132fd16f150c8c83/Independence.Day.Resurgence.2016.1080p.BluRay.x264-GECKOS HTTP/2.0", upstream: "fastcgi://127.0.0.1:9000",
```

Getting this error when trying to view any movie. Works fine on TV, Music, XXX and Books. Looks like the same error sug got when importing nzbs in #2280 & #2284

**Comment by ghost** [comment]
@niel Any idea? None of my movies work right now :-(

**Comment by niel** [comment]
I need more info. I've tried this on an active site and I'm not seeing anything in logs.
So can you please explain exactly what you mean by "when trying to view any movie"?

**Comment by ghost** [comment]
Well /details/someguidwhichisamovie

Anything which isn't a movie works fine but movies throw that error which is very similar to #2280

These started after latest update, I have reverted back to the previous stable version of the 0.x branch and that works without problems.

**Comment by DariusIII** [comment]
I think it is related to switch from Settings to DB in nzedb/processing/Videos.php

`#7 /ssd/nzedb/nzedb/processing/tv/TraktTv.php(70): nzedb\processing\tv\TV->__construct(" while reading response header from upstream, client: 77.174.61.47, server: serverhere, request: "GET /details/3c49de4eee90c99dfbebbb6b132fd16f150c8c83/Independence.Day.Resurgence.2016.1080p.BluRay.x264-GECKOS HTTP/2.0", upstream: "fastcgi://127.0.0.1:9000",`

Line 70 in TraktTv class leads to TV construct, which extends Videos class:

https://github.com/nZEDb/nZEDb/blob/0.x/nzedb/processing/Videos.php#L69

**Comment by ghost** [comment]
I am also getting this error

**Comment by ghost** [comment]
Weird thing is it's only happening ong movies but the stacktrace shows TraktTV.php

**Comment by niel** [comment]
OK, seeing the problem now. I was clicking on the film info, not the release info ;-)

**Comment by niel** [comment]
Pushed a fix to all branches. It's part of what's coming in another branch, hopefully is doesn't cause more problems than it fixes ;-)

**Comment by ghost** [comment]
Seems fixed. Thanks!
