### ISSUE TITLE
Unable to create database and data. Check permissions of your mysql user.

### ISSUE THREAD

**Issue by Sweepr** [nZEDb/nZEDb#2288]
Step 2 of the install: 

I just cannot get passed this error:

The following error(s) were encountered:
• Unable to create database and data. Check permissions of your mysql user.

I can see table are created, but all are size 0 

The folder "resources" has 777 permission's set and all files and folder under that.

```
mysql> CREATE USER 'nzedbe'@'localhost' IDENTIFIED BY 'xxxxxxxxxxx';
Query OK, 0 rows affected (0.01 sec)

mysql> GRANT ALL PRIVILEGES ON nzedbe.* TO 'nzedbe'@'localhost';
Query OK, 0 rows affected (0.00 sec)

mysql> SHOW GRANTS FOR 'nzedbe'@'localhost';
+---------------------------------------------------------------------------------------------------------------------------------+
| Grants for nzedbe@localhost                                                                                            |
+---------------------------------------------------------------------------------------------------------------------------------+

GRANT FILE ON *.* TO 'nzedbe'@'localhost';
Query OK, 0 rows affected (0.00 sec)

mysql> flush privileges;
Query OK, 0 rows affected (0.00 sec)
```

Still: 

The following error(s) were encountered:
• Unable to create database and data. Check permissions of your mysql user.

I'm lost...

**Comment by ghost** [comment]
Is that a typo?
mysql> GRANT ALL PRIVILEGES ON nzedbe.\* TO 'nzedbe'@'localhost';
should it not be
mysql> GRANT ALL PRIVILEGES ON nzedb.\* TO 'nzedbe'@'localhost';

**Comment by Sweepr** [comment]
Depends on what the username and dbname are. ;-)

**Comment by Sweepr** [comment]
`GRANT ALL PRIVILEGES ON`nzedb`.* TO 'nzedbe'@'localhost' WITH GRANT OPTION`

`GRANT ALL PRIVILEGES ON`nzedbe`.* TO 'nzedbe'@'localhost' WITH GRANT OPTION`

For the heck i got both but still no luck

**Comment by Sweepr** [comment]
The connection can be made, because if i fill in a incorrect password or non-existing username i get:

`Unable to connect to database:
Unable to connect to the SQL server.`

**Comment by niel** [comment]
Is 'nzedbe' a typo?
Additionally, have you checked the permissions on ALL the directories involved in the path to .../resources/db/schema/data ? The traversable bit for all users (last x in directory permissions) must be set or the mysql account cannot access the files to read them.

**Comment by Sweepr** [comment]
@niel Everything leading up to /resources has 0755 permission, /resources and all after have 0777

**Comment by Wally73** [comment]
you forgot: 
The ALL permissions doesn't actually grant them all, you MUST add FILE:
GRANT FILE ON _._ TO 'YourMySQLUsername'@'YourMySQLServerHostName';

**Comment by Sweepr** [comment]
@Wally73 

Created a new user and a new DB and did 

```
GRANT FILE ON *.* TO 'shift_user'@'localhost';
Query OK, 0 rows affected (0.00 sec)

mysql> SHOW GRANTS for 'shift_user'@'localhost';
Grants for shift_user@localhost                                                                                  

GRANT FILE ON *.* TO 'shift_user'@'localhost' IDENTIFIED BY PASSWORD '*xxxxxx' 
GRANT ALL PRIVILEGES ON `shift\_base`.* TO 'shift_user'@'localhost'                                           

2 rows in set (0.00 sec)

mysql> flush privileges;
Query OK, 0 rows affected (0.03 sec)
```

Then tried again, but still no luck.

The following error(s) were encountered:
• Unable to create database and data. Check permissions of your mysql user.

**Comment by DariusIII** [comment]
I had same problem in NNTmux, when i added installer. It was due to line endings LF vs. CRLF.With CRLF i had same problems, so i switched line endings in NNTmux to LF and it started working.

**Comment by Wally73** [comment]
you need to do both grant all and grant file

**Comment by niel** [comment]
> I had same problem in NNTmux, when i added installer. It was due to line endings LF vs. CRLF.With CRLF i had same problems, so i switched line endings in NNTmux to LF and it started working.

This is correct. The SQL statement that imports the data has to have line endings explicitly set. I opted for the simpler LF, instead of CRLF combo as it is standard on all platforms except Windows (and makes each line one byte shorter ;-). 
In theory CRLF should be treated the same as LF, as it ends with an LF, but in practise this is dependant on other factors.

**Comment by Sweepr** [comment]
@niel Ok, i understand, could you explain me how and where i must change this?

**Comment by Sweepr** [comment]
@niel 

Ok, i think i found it, set core.autocrlf = input to true.

```
git config --list
core.eol=lf 
core.autocrlf=input <--
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
remote.origin.url=https://github.com/nZEDb/nZEDb.git
branch.0.x.remote=origin
branch.0.x.merge=refs/heads/0.x

```

```
#git config --global core.autocrlf true
#git config --list
core.eol=lf
core.autocrlf=true <--
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
remote.origin.url=https://github.com/nZEDb/nZEDb.git
branch.0.x.remote=origin
branch.0.x.merge=refs/heads/0.x

```

**Comment by Sweepr** [comment]
Ok, great help guys!, after a new git clone and composer install, i went ahead fixing the permission and ownership and then the install passed step 2 without a glitch.

So that solved the issue!

**Comment by niel** [comment]
Damn it, I shouldn't reply to stuff at 2 AM. My previous message is incorrect. Lines in *.tsv files are supposed to end in CRLF. This is so real LF characters can be included in the data without messing up the import.

Our .gitattributes file contains a line that should force this to happen, but it is possible that a user's settings might override that,. I'm not sure which has priority in such a case.

**Comment by RivalScribal** [comment]
I'm also having this problem. I've verified mysql permissions, and to double check those I tried using root, but it didn't matter. I've verified traverse is set to on for all folders down to where the database sits. (/var/www/nZEDb/resources/db/schema/data). I've found two things in the archive that I'm not quite sure on. The first is the above git config. Is this referring to the git config of the nZEDb folder, or should I be looking at another folder? When I list the git config for the nZEDb folder I get:

core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=https://github.com/nZEDb/nZEDb.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.0.x.remote=origin
branch.0.x.merge=refs/heads/0.x

What I've learned about git, I've learned this morning, so I'm barely a novice. I might be doing something wrong, but when I use the global or system flag I get no such file or directory. Would I need to ad core.autocrlf=true to the local git config, or install something else to get a global git config and put it there?

The other thing I found was a suggestion to add secure-file-priv = "" to the my.cnf file, which again I don't know if I added it to the correct file, but even after restarting services, it didn't seem to make any change.

**Comment by niel** [comment]
git config is either your global or local repo. You set it up as you need, globally if you need it as the default behaviour every where, or just for the local repo if you need to do something different from the default.

secure-file-priv = "" should not be needed. if you don't have that setting in your mysql.cnf (or whatever the file is called in your setup) then you do not need to add it. IF it does exist and it isn't set to the location of your *.tsv files you will never be able to load them. Which is why some people tell you to set it empty.

To make diagnosis of the problem easier you should also check your MySQL logs for information on WHY access was denied.

**Comment by RivalScribal** [comment]
I've done some searching for the location of a log file, but I'm not finding anything relevant. The nZEDb/resources/log folder is empty. What I found for the general MYSQL log file doesn't show anything in the last day or so. Going into the older files, I couldn't see anything that seemed to be relevant to this issue.

It looks like it's not logging anything, but I don't know that much about Mysql. Part of the reason to set this up is to learn mysql.
