### ISSUE TITLE
Tmux showing ": command not found" in multiple panes.

### ISSUE THREAD

**Issue by Sweepr** [nZEDb/nZEDb#2292]
In the monitor pane directly below i see this pop up every refresh:

sh: line 2: echo "  

In all Utils and Post pane's i see:

In RemoveCrapReleases:
: command not found
Error: Error, time must be a number or full.
sh: line 3: full: command not found
: command not found

See screenshot:

![untitled](https://cloud.githubusercontent.com/assets/2857865/19417468/1136fe12-93ae-11e6-87f3-39ef3f8fc49c.jpg)

Could this have something todo with the shell version?

sh-4.1# help
GNU bash, version 4.1.2(1)-release (x86_64-redhat-linux-gnu)

**Comment by niel** [comment]
I've no idea, I've never seen this problem before. 
It would help if we knew which command isn't being found.

**Comment by Sweepr** [comment]
Yeah, that's the problem. the log isn't showing me anything more then this.

I'll try to update shell, since there is a newer version. 

https://ftp.gnu.org/pub/gnu/bash/bash-4.4.tar.gz

**Comment by Sweepr** [comment]
Tried upgrading Bash to 4.4 but this didn't help, but lead me into a different error which lead to the CRLF and LF story again, so i recursivly converted CRLF to LF for all files using:

for file in `find . -type f`; do dos2unix $file $file; done

Now all error's are gone.

**Comment by niel** [comment]
hmmm, you will have broken some of those files which require CRLF to function. Also, next time you want to upgrade you'll get a message saying your files have changed and you need to stash or commit your changes to proceed. All in all, I'd say it would  be better to identify what is the real cause and fix it specifically.
