### ISSUE TITLE
 Uncaught exception 'BadMethodCallException' when running tmux

### ISSUE THREAD

**Issue by dilbaggins** [nZEDb/nZEDb#2297]
### Expected behaviour

successful start of tmux scripts.
### Actual behaviour

Starting Tmux...
Resetting expired collections dateadded to now. This could take a minute or two.                                                                                                                                                              Really.
0 collections reset.
PHP Fatal error:  Uncaught exception 'BadMethodCallException' with message 'Unhandled method call `queryOneRow`.' in /var/www/nZEDb/libraries/lithium/data/Model.php:573
Stack trace:
#0 /var/www/nZEDb/misc/update/nix/tmux/run.php(347): lithium\data\Model->__call('queryOneRow', Array)
#1 /var/www/nZEDb/misc/update/nix/tmux/run.php(347): app\models\Settings->queryOneRow('SELECT enabled,...')
#2 /var/www/nZEDb/misc/update/nix/tmux/run.php(115): window_sharing('KLIQMATRIX')
#3 {main}

  thrown in /var/www/nZEDb/libraries/lithium/data/Model.php on line 573
### Steps to reproduce the behaviour

(yes i know this was risky)  
run start.php from /var/www/nZEDb/misc/update/nix/tmux on latest dev

Version Below
./zed version all
Looking up Git tag version(s)
Hash: bc1b27fe8558390fb0812f1fdd9a0b7db41d2945
XML version: v0.0.0-dev
Git version: v0.6.4.1
Looking up SQL patch version(s)
XML version: 453
 DB version: 453

**Comment by dilbaggins** [comment]
resolved by git reset.  i jumped the gun...  sorry fellas.

**Comment by PsychoSid** [comment]
@dilbaggins Hi, I get that as well. What did you reset to get it back up and running please ? "git reset" obviously doesn't cut it.

Thanks.

**Comment by PsychoSid** [comment]
I reset to 06c01cca3bcb9a12f73a2c6d567ab8bfac1eb851.

**Comment by niel** [comment]
git reset v0.6.5.3 --hard
is the currently recommended way ;-)
if it complains it can't find it do: git pull then retry.
