### ISSUE TITLE
PP add not updating passwordstatus on some releases

### ISSUE THREAD

**Issue by ghost** [nZEDb/nZEDb#2298]
php5.6 using niels deb
ii  php5.6-yenc                       1.2.2                             amd64        php-yenc extension build for PHP 5.6

I noticed a release that had been PP'd (got ID from ps fux) had not had it's passwordstatus updated from '-1' in the releases table.

Grep'ing the logs for this ID (and a few others) shows it's stuck in a loop.  I have around 16K releases doing this now.

With the scripts stopped 

Running a loop on /var/www/nzedb/misc/update/nix/multiprocessing/postprocess.php add shows the below sql query result not changing (after it's PP'd the working stuff of course)

SELECT count(*) FROM releases r INNER JOIN categories c ON c.id = r.categories_id INNER JOIN groups g on g.id = r.groups_id WHERE r.nzbstatus = 1 AND r.passwordstatus BETWEEN -6 AND -1 AND r.haspreview = -1 AND c.disablepreview = 0

**Comment by ghost** [comment]
I just switched to simple_php_yenc_decode and the count(*) is dropping (slowly)

**Comment by niel** [comment]
hmm, sounds like my extension is erroring out for some reason then. Will look into this when I can.

**Comment by ghost** [comment]
Is there anything I am missing out on if I stay with simple?

**Comment by niel** [comment]
Not while you are on 5.6. I believe it is also a little faster ;-) SPYD doesn't work on 7.0+ though, so my version is the better option there. Obviously I'd like to fix this problem (and improve performance) so that it does affect 7.0 users.

**Comment by ghost** [comment]
Here is the grep output, you can see it detects a password - maybe that's related?
grep 14208276 postprocessing_additional-20161019.log
http://kopy.io/loqD6

**Comment by ghost** [comment]
Just for infor SYD has not updated this release yet, I am guessing this is due to it processing the 16K and just not hit it yet... I'll post back later if I see it change

**Comment by niel** [comment]
Are those passworded releases the ones causing the problem though? They look like they're processing correctly.

**Comment by ghost** [comment]
It's the same release looping due to not updating the passwordstatus (in my guess)

**Comment by ghost** [comment]
OK this is what I think I've found.
If we get the total of maxppthreads in bad releases then no other older releases for that leftguid get processed. 

we may be able to reproduce this
Get this crap nzb
(----)_[73_75]_-_-v4A1HF3z81Goj6mTWaPk9.vol145+44.PAR2-.nzb
https://file.io/dGd7QG

import it by name
get the release.id of it (14197575) in this example

select id from releases where searchname like '%v4A1HF3z81Goj6mTWaPk9%' and size = '13797035556';

edit nzedb/nzedb/libraries/Forking.php

add the two r.id's  to around line 663 so it looks like this 

SELECT leftguid AS id, **r.id**
          FROM releases r
          LEFT JOIN categories c ON c.id = r.categories_id
          WHERE r.nzbstatus = %d
          AND r.passwordstatus BETWEEN -6 AND -1
          AND r.haspreview = -1
          AND c.disablepreview = 0
**AND r.id = 14197575**
          %s %s
          GROUP BY leftguid
          LIMIT 16',

stick pp in a loop
while true ; do php5 /var/www/nzedb/misc/update/nix/multiprocessing/postprocess.php add ; done

monitor the passwordstatus

select leftguid,passwordstatus from releases where id ='14197575';

**Comment by ghost** [comment]
Fixed in latest dev, Cheers!
