### ISSUE TITLE
No Releases and Admin site not allowing changes (HTTP ERROR 500)

### ISSUE THREAD

**Issue by danpopHP** [nZEDb/nZEDb#2300]
### Expected behaviour

releases created and admin site allowing setting changes 
### Actual behaviour

no releases since latest patch and unable to change admin page settings
### Steps to reproduce the behaviour

1) update to latest dev build
2) run tmux sequenced for some hours notice no releases /  go to admin page/site settings and change any of the settings,  when you click submit you recieve a HTTP ERROR 500.

Version:
 ./zed version all
Looking up Git tag version(s)
Hash: 48ca51af6c3438101b0336cacb833571e319aa5b
XML version: v0.0.0-dev
Git version: v0.6.5.3
Looking up SQL patch version(s)
XML version: 454
 DB version: 454

**Comment by dilbaggins** [comment]
seeing this and it seems releases stuck in "MISC"

**Comment by niel** [comment]
This is due to the settings backend changes and how they interact with Smarty pages. One of the edge cases we needed to find and fix. Working on it now.

**Comment by dilbaggins** [comment]
@niel you rule.

**Comment by niel** [comment]
@danpopHP I'll need more info for the releases issue. Can you provide a PHP error log? You may need to enable it in settings.php, if you haven't previously done so.

**Comment by dilbaggins** [comment]
cli or web?@niel

**Comment by dilbaggins** [comment]
im seeing a bunch of these (CLI): 

Uncaught exception 'Exception' with message 'Unable to fetch setting from Db!' in /var/www/nZEDb/app/models/Settings.php:205

**Comment by dilbaggins** [comment]
in (web):  PHP Fatal error:  Call to undefined method nzedb\db\DB::update() in /var/www/nZEDb/www/admin/site-edit.php on line 30

Undefined index: settings in /var/www/nZEDb/resources/smarty/templates_c/98f014b6326bf35fb73f940b2a8d06af4dbcba30_0.file.site-edit.tpl.php on line 503

**Comment by dilbaggins** [comment]
whats odd is i see releases being created:  
![image](https://cloud.githubusercontent.com/assets/3989347/19620019/e286ff84-9841-11e6-8b36-5e1a626b2b1e.png)

**Comment by dilbaggins** [comment]
whats odd is releases are being created:  
![image](https://cloud.githubusercontent.com/assets/3989347/19620025/fb853870-9841-11e6-94ff-f720f86910c0.png)

**Comment by dilbaggins** [comment]
@niel  the site-admin part is working i can edit values. however still no releases (understood your looking into the second part)

**Comment by dilbaggins** [comment]
was thinking my releases tables were perhaps corrupted but did a mysqlcheck and see they are ok:

nzedb.release_files                                OK
nzedb.release_naming_regexes                       OK
nzedb.release_nfos                                 OK
nzedb.release_search_data                          OK
nzedb.release_subtitles                            OK
nzedb.release_unique                               OK
nzedb.releaseextrafull                             OK
nzedb.releases                                     OK
nzedb.releases_se
note     : The storage engine for the table doesn't support check
nzedb.role_excluded_categories                     OK

**Comment by dilbaggins** [comment]
@niel anything you see from the logs i sent?

**Comment by dilbaggins** [comment]
heres another odd thing.  if i look in "New Releases" i see a release is created (see below)

Posted: 2016-10-23 08:15:22 ( Today)
Added:  2016-10-23 08:31:42 ( Today)

but if i go to TV/HD or TV/ALL  it shows items posted 2.1 days ago... very strange indeed

**Comment by niel** [comment]
@dilbaggins What logs? All I've seen is what is posted above. For the logs both cli and web are relevant, but for different things ;-) 

If your CLI log only contains PEAR errors, there's nothing we can do about that usuually.

The "Uncaught exception 'Exception' with message 'Unable to fetch setting from Db!' in /var/www/nZEDb/app/models/Settings.php:205" mentioned about is not enough info. I need the stack trace (you may have to install/enable xdebug to get that) to find what calls that. That bug indicates that either a settings is missing from the table, or that the code contains the badly named setting. Which is why I need the trace to see what is being asked for and where.

The error in the Smart compiled template is at best difficult to find, because of how Smarty works, which is why I need the PHP logs, as they show where in the actual code problems occur.

With nothing concrete to work from, I'm going to leave this until Monday. Then I will dive into the releases code and go through it line by line if needed.

**Comment by dilbaggins** [comment]
[nzedbLOGS.zip](https://github.com/nZEDb/nZEDb/files/546346/nzedbLOGS.zip)

**Comment by niel** [comment]
@dilbaggins
The CLI log basically shows the same error repeatedly. You have a setting missing from your settings table. Make sure patch 454 has been applied correctly (./zed update db _then_ check the table to be sure it is there). It is supposed to fix that, but one person has reported that it failed. Apply it manually if necessary.
The web log is way too long and most of it is from yesterday or before. Please clean out/delete all those logs and send me a fresh one in an hour or when the log hits ~50K which ever happens first.

**Comment by dilbaggins** [comment]
[ERRORLOG.zip](https://github.com/nZEDb/nZEDb/files/546430/ERRORLOG.zip)
