### ISSUE TITLE
Error when doing install step2 to create the DB

### ISSUE THREAD

**Issue by xionous** [nZEDb/nZEDb#2301]
this is on a XAMPP for windows install, i followed the install steps listed on this site everything else worked fine but im getting this error during install.
### Expected behaviour

when install database is clicked it should create the database
### Actual behaviour

when i click it i get this error:

`PHP Fatal error:  Uncaught exception 'Exception' with message 'The system cannot find the path specified.

' in C:\xampp\htdocs\nZEDb\app\libraries\kbjr\Git.php\Git.php:317
Stack trace:
#0 C:\xampp\htdocs\nZEDb\app\libraries\kbjr\Git.php\Git.php(332): GitRepo->run_command('/usr/bin/git br...')
#1 C:\xampp\htdocs\nZEDb\app\libraries\kbjr\Git.php\Git.php(492): GitRepo->run('branch')
#2 C:\xampp\htdocs\nZEDb\app\libraries\kbjr\Git.php\Git.php(532): GitRepo->list_branches(true)
#3 C:\xampp\htdocs\nZEDb\nzedb\utility\Git.php(42): GitRepo->active_branch()
#4 C:\xampp\htdocs\nZEDb\nzedb\db\DbUpdate.php(72): nzedb\utility\Git->__construct()
#5 C:\xampp\htdocs\nZEDb\www\install\step2.php(155): nzedb\db\DbUpdate->__construct(Array)
#6 {main}

  thrown in C:\xampp\htdocs\nZEDb\app\libraries\kbjr\Git.php\Git.php on line 317`
### Steps to reproduce the behaviour

happens when install database is clicked

**Comment by DariusIII** [comment]
Have you ran 
`composer install` ?

**Comment by xionous** [comment]
Yes i have, that seems to be working as far as i can tell

**Comment by kevinlekiller** [comment]
https://github.com/nZEDb/nZEDb/issues/2261
https://github.com/kbjr/Git.php/issues/47
https://github.com/kbjr/Git.php/pull/48

**Comment by xionous** [comment]
Thanks, that's exactly what it was!

**Comment by josh4trunks** [comment]
@kevinlekiller any idea how we could fix this in the future?

Since kbjr/Git.php is dead maybe we could just incorporate the Git.php file into nzedb, apply my fix, and not have to deal with this issue anymore for non linux systems? I don't see much reason to continue relying on a repo we know will never fix bugs/make improvements.

**Comment by kevinlekiller** [comment]
Indeed, but doesn't seem like the nzedb devs want to change it unfortunately.

**Comment by niel** [comment]
@josh4trunks Make a PR, we'll look at it.
I would prefer that we keep it as a library, I don't like including third party code into the main repo. However, if someone forks it and makes the fixes, we can then include that as a library.

**Comment by josh4trunks** [comment]
Sounds good, I'll get on this.

**Comment by Bart39** [comment]
if these kind of things pop up again and no one is willing to fork the libraries perhaps we should fork ourselves....

**Comment by josh4trunks** [comment]
For Git.php there are some forks, not sure how active they are, or how willing they are to accept fixes.
https://github.com/kbjr/Git.php/network

**Comment by josh4trunks** [comment]
See the issue report here https://github.com/nZEDb/nZEDb/issues/2304

**EDIT**
Oh, you said PR, not issue. We'd need an upstream repo to accept my changes first. I don't plan on keeping my fork of the repo after this issue is fixed.

**Comment by niel** [comment]
I've created a fork of kbjr/Git repo which you can fork. But there will need to be a PR against nZEDb dev branch to enable the library.

https://github.com/nZEDb/Git.php

**Comment by josh4trunks** [comment]
See my PR here https://github.com/nZEDb/Git.php/pull/1

**Comment by b3rs3rk** [comment]
As the PR was merged and the new Git.php fork is being applied in composer.json this issue can be closed.

**Comment by josh4trunks** [comment]
i did a `./zed update nzedb` yesterday and it works as expected =]
