### ISSUE TITLE
Im getting postprocess error with new  pull

### ISSUE THREAD

**Issue by seias** [nZEDb/nZEDb#2302]
### Expected behaviour

postprocess additional
### Actual behaviour

PHP Fatal error:  Uncaught Exception: Unable to fetch setting from Db! in Settings.php:205
Stack trace:
#0 ProcessAdditional.php(416): app/models/Settings::value('indexer.ppa.inn...')
#1 /misc/update/nix/multiprocessing/.do_not_run/switch.php(255): nzedb/processing/post/ProcessAdditional->__construct(Array)
#2 {main}

  thrown in /app/models/Settings.php on line 205
### Steps to reproduce the behaviour

...
it was working before this pull..

**Comment by DariusIII** [comment]
Have you applied latest patch (https://github.com/nZEDb/nZEDb/blob/dev/resources/db/patches/mysql/0454~settings.sql)?
Try to apply it manualy through mysql cli or phpmyadmin.

**Comment by seias** [comment]
yes i did and redid just now just in case still same error

**Comment by DariusIII** [comment]
Do this: 
`SELECT * FROM settings WHERE setting = 'innerfileblacklist';`

and report values.

**Comment by seias** [comment]
indexer ppa innerfileblacklist  /setup.exe|password.url/i   You can add a regex here to set releases to potentially passworded when a file name inside a rar/zip matches this regex.    innerfileblacklist

**Comment by seias** [comment]
i figured the prob  it was a db update way back in 2015 on the settings that got corrupted on the settings somehow went back and patched all setting since 2015 and all works now
