### ISSUE TITLE
Git.php library does not work on FreeBSD / Windows

### ISSUE THREAD

**Issue by josh4trunks** [nZEDb/nZEDb#2304]
### Expected behaviour

kbjr/Git.php should find the **git** executable from PHP's PATH environmental variable
### Actual behaviour

kbjr/Git.php is hardcoded to use **/usr/bin/git** which does not exist on FreeBSD or Windows. I am not sure about other OS's (macOS / various Linux distributions).
### Steps to reproduce the behaviour

Try updating using `./zed update nzedb`

**Comment by josh4trunks** [comment]
This could be fixed if our Git.php function incorporated my fix proposed here https://github.com/kbjr/Git.php/pull/48
The changes I proposed were never merged because kbjr/Git.php is no longer maintained.

One solution would be to merge the changes into another actively maintained fork.
https://github.com/kbjr/Git.php/network

**Comment by niel** [comment]
I'll create an empty repo which you can fork. But there will need to be a PR against nZEDb dev branch to enable the library.

**Comment by DariusIII** [comment]
I believe @niel fixed this by using our own version of Git.php.
