### ISSUE TITLE
NNTP SSL: Handshake timed out

### ISSUE THREAD

**Issue by ghost** [nZEDb/nZEDb#2310]
Seeing this pop up quite frequent in php_errors. It's happened on a few USP's I've been testing.

SSL: Handshake timed out in /var/www/nzedb/libs/PEAR/Net_NNTP/NNTP/Protocol/Client.php on line 515
Failed to enable crypto in /var/www/nzedb/libs/PEAR/Net_NNTP/NNTP/Protocol/Client.php on line 515

**Comment by b3rs3rk** [comment]
With SSL you'll always have the potential for a handshake error.  We account for this with retries.  You can safely ignore them.
