### ISSUE TITLE
Error logging in after updating to latest master.

### ISSUE THREAD

**Issue by moloquin** [nZEDb/nZEDb#2312]
###Expected behaviour
Able to login to site.

###Actual behaviour
After updating to latest master, can no longer log into site.  Seems that if you are logged in while updating, you can stay logged in, but once you are logged out, if you try to login, you get a 500 error, and in the apache logs you see this error (personal info scrubbed).  API calls still work, just logging into the web site fails.

[Sun Nov 13 14:10:24.211750 2016] [:error] [pid 30981] [client X.X.X.X:46338] PHP Fatal error:  Uncaught exception 'Exception' with message 'Unable to fetch setting from Db!' in /var/www/nZEDb/app/models/Settings.php:205\nStack trace:\n#0 /var/www/nZEDb/nzedb/Captcha.php(200): app\\models\\Settings::value('APIs.recaptcha....')\n#1 /var/www/nZEDb/nzedb/Captcha.php(112): nzedb\\Captcha->_bootstrapCaptcha()\n#2 /var/www/nZEDb/nzedb/Captcha.php(87): nzedb\\Captcha->shouldDisplay()\n#3 /var/www/nZEDb/www/pages/login.php(8): nzedb\\Captcha->__construct(Object(Page))\n#4 /var/www/nZEDb/www/index.php(76): require_once('/var/www/nZEDb...')\n#5 {main}\n  thrown in /var/www/nZEDb/app/models/Settings.php on line 205, referer: http://X.X.X.X/

###Steps to reproduce the behaviour
update to latest master, log out, and try to log back in.

**Comment by niel** [comment]
You probably have a missing setting in your settings table. Check for section = 'APIs', subsection = 'recaptcha', name = 'enabled' and that it is set to 0 or 1.

**Comment by moloquin** [comment]
That's got it.  Something funky happened to that entry in the database.  All of the values for that were under the section field rather than broken across the multiple fields.  Changed it to the proper entries and looks like everything is working again.  Thanks!

Before:  section = APIs     recaptcha     enabl
After:  section = APIs
subsection = recaptcha
name = enabled
value = 0

**Comment by sibeinsa** [comment]
You are not alone with this. I hit the same issue and found when I re install nZEDb it came right. I found the settings part of the DB was crashing my site. simply deleted it from my old backup (using phpmyadmin) and imported the new one. I upgraded from 6.5.2 to 6.2.2 .Im running MySQL version 5.5.52 Debian Linux 8.0 INNODB.

**Comment by samwiseg0** [comment]
+1 Had this exact issue

**Comment by niel** [comment]
Check your settings table is correct. Run: ./zed verify settings_table from within your nZEDb directory.
Fix any missing/incorrect settings (you're probably missing the one that controls the recaptcha part of login).

**Comment by Rawh** [comment]
Yes. The settings db had a weird looking issue --> `https://i.imgur.com/ycGB6Lk.jpg`

I manually edited it to represent the values in `/db/patches/mysql/0427%7Esettings.sql`
