### ISSUE TITLE
Not all Book Releases are being post processed

### ISSUE THREAD

**Issue by samwiseg0** [nZEDb/nZEDb#2315]
###Expected behaviour
Post process for Books should be processed.  book_reqids = 3030, 7020, 7040, 7060

###Actual behaviour
7040 is the only book reqid that is being checked

###Steps to reproduce the behaviour
run the latest master and use settings 

Lookup Books: All books 
Type of books to look up: All Options

It seems no matter what the config combination that is set the settings are not honored

**Comment by dilbaggins** [comment]
+1 for @samwiseg00 he is also from the shire

**Comment by b3rs3rk** [comment]
Fixed in c9f14f6fdc8a8cd47c6ad52e9b31de1d4922279d on dev branch.  Replicating this change to your local branch should fix book processing until it makes its way down the line

**Comment by samwiseg0** [comment]
confirmed working. Thanks!
