### ISSUE TITLE
can't load site: Installing imagick on Windows

### ISSUE THREAD

**Issue by DrSeussFreak** [nZEDb/nZEDb#2317]
While installing nZEDb from via composure, I get an error about imagick not being installed, and it is a required tool.  Trying to install it now, so I can reinstall via composure, but I cannot get PHP to recognize the dll.  I followed the instructions from http://hrt0kmt.hatenablog.com/entry/2015/05/27/170608, but everytimg I check "php -m" I get 

`PHP Warning: PHP Startup: Unable to load dynamic library 'C:\xampp\php\ext\php_imagick.dll' - The specified module could not be found. in Unknown on line 0`

Just wondering if any knows how to install this on Windows 10 x64.  I did install the x86 dll for PHP, due to Xamp being 32bit

**Comment by niel** [comment]
Sorry, the developers do not use XAMPP or similar ways to run PHP, so are unable to offer much in the way of advice. I would suggest going to the XAMPP site and get advice from them on how to use their package.

**Comment by DrSeussFreak** [comment]
Worth a shot, ok thanks.
