### ISSUE TITLE
releases not getting renamed on filename

### ISSUE THREAD

**Issue by ghost** [nZEDb/nZEDb#2318]
There are a lot of releases in a.b.games (not limited to this group) that re ending up in misc>hased but actually have there filenames in the rar contents. I can ping examples on IRC.

**Comment by ghost** [comment]
1 example http://kopy.io/KqEj1

**Comment by ghost** [comment]
testing/Release/fixReleaseNames.php 6 false other no
sql output:

http://kopy.io/S7mA6

**Comment by ghost** [comment]
http://d.pr/i/JosS

**Comment by ghost** [comment]
This seems really bad. Loads in a.b.hdtv that have the filename 
eg
Filename: This.Is.Us.S01E10.1080p.WEB-DL.DD5.1.H.264-GoApe.mkv	

We name it: [enjoy]-[non-scene@EFNet]-[ 091216-PGS0107720WDD51H264R ]

**Comment by ghost** [comment]
Got that one too.

**Comment by DariusIII** [comment]
Partialy fixed in commit c07c77501e99c284424b57a904a20f80ead265cd

**Comment by ghost** [comment]
Some releases are now renamed to an empty searchname with that commit.

**Comment by ghost** [comment]
Looks fixed to me with latest version.
