### ISSUE TITLE
Settings Table verification not working

### ISSUE THREAD

**Issue by dilbaggins** [nZEDb/nZEDb#2319]
###Expected behaviour
verify of settings table in the./zed verify settings_table

###Actual behaviour
i see a list of missing sections  (http://pastebin.com/1FS67kbm)  however if i phpmyadmin or adminer i see the table fine:  

![image](https://cloud.githubusercontent.com/assets/3989347/20687289/ed46ee7e-b589-11e6-8b15-e38acda01905.png)

###Steps to reproduce the behaviour
update to latest dev-safe and run ./zed verify settings_table

Version
Hash: aecee0d515ea06c4641ceaeeaf0d52f81b255bdf
XML version: v0.0.0-dev
Git version: dev-safe
Looking up SQL patch version(s)
XML version: 458
 DB version: 458

**Comment by dilbaggins** [comment]
i also get this on running the new zed test functionality:

----
Test
----

F

FAIL

0 / 1 passes
1 fail and 0 exceptions

Failed assertion assertTrue.
 File    : /var/www/nZEDb/app/tests/cases/models/SettingsTest.php
 Class   : app\tests\cases\models\SettingsTest
 Method  : testHasAllEntries()
 Line    : 32
 ________
expected: 1
result:

**Comment by niel** [comment]
do not "update" to dev-safe. that was a tag added when we were testing experimental code. It is now a LONG way behind.

**Comment by niel** [comment]
What version of PHP are you using?

**Comment by dilbaggins** [comment]
PHP: PHP 5.6.28-1+deb.sury.org~trusty

p.s. how do i switch to dev branch again? :)

**Comment by dilbaggins** [comment]
p.s. @niel  whats weird is if you see the hash it looks like its the latest code?  i did a reset hard then git pull because .zed update all isnt doing anything? :(

**Comment by niel** [comment]
OK. Looks like I misread the documentation for a change made for PHP between 5.6 and 7.0. This is causing the test to reverse the order of entries and leads to the problem you're seeing. I'll fix it in dev and Latest-testing branches.
I'd recommend trying Latest-testing before dev. I updated it yesterday and as I said above I'll merge the fix into there also. To do this:
git pull
git checkout -b Latest-testing --track origin/Latest-testing
then run ./zed update nzedb
If you do this you'll have to wait until next Monday to switch back to stable branch, but you'll be ON what will be next release ;-)

**Comment by dilbaggins** [comment]
looks good:  
Test
----

.

OK

1 / 1 pass
0 fails and 0 exceptions
