### ISSUE TITLE
Couple of issues with releases / PostProc

### ISSUE THREAD

**Issue by ghost** [nZEDb/nZEDb#2320]
## Issue 1:

Weird searchnames crafted from subjects. See screenshot below, the proper name is in the usenet name so it's probably just a regex issue.
Also: It would be cool if there could be a renaming regex which removes the [newzNZB_] prefix, i'm currently running a script in cron which does just that.

[Screenshot 1](http://imgur.com/a/dORCo)

## Issue 2: 

Some XXX releases are getting assigned to the Misc>Other category even while they are properly renamed.

[Screenshot 2](http://imgur.com/a/BUizZ)

**Comment by danpopSD** [comment]
@niel  im seeing this as well.  (newzNZB_) most releases.

**Comment by Fossil01** [comment]
Yeah but those are uploaded without RAR's and PARs. Zed only looks for those for renaming IIRC.

**Comment by ghost** [comment]
Closed. NewzNZB is shit anyway and issue 2 doesn't happen anymore.
