### ISSUE TITLE
Some TV Shows don't get episodes listed correct

### ISSUE THREAD

**Issue by cytec** [nZEDb/nZEDb#2322]
### Expected behaviour

S04E08 should be the 8th episode of the 4th season.

### Actual behaviour
it gets listed as the 1st episode no matter which ep it is for some shows for some reason (see screenshots)

![bildschirmfoto 2016-12-01 um 18 40 16](https://cloud.githubusercontent.com/assets/1104903/20805235/4123123e-b7f6-11e6-9217-b4a87508d095.png)
![bildschirmfoto 2016-12-01 um 18 39 59](https://cloud.githubusercontent.com/assets/1104903/20805236/41239042-b7f6-11e6-949c-02cdcd0ea30f.png)

### Steps to reproduce the behaviour
Try adding House of Cards US and Goliath.
I've deleted those shows from the videos table already and reset the pp on all releases, but it happened again... 

if any more information is needed please don't hesitate to ask :=)

**Comment by cytec** [comment]
seems like this is mostly for shows which release several episodes on the same day (netflix etc) since the TV Class checks for airdate before season/episode here: https://github.com/nZEDb/nZEDb/blob/0.x/nzedb/processing/tv/TV.php#L444-L450

changing those lines from 

		if (!empty($airdate)) {
			$queryString = sprintf('DATE(tve.firstaired) = %s', $this->pdo->escapeString(date('Y-m-d', strtotime($airdate))));
		} else if ($series > 0 && $episode > 0) {
			$queryString = sprintf('tve.series = %d AND tve.episode = %d', $series, $episode);
		} else {
			return false;
		}

to

		if ($series > 0 && $episode > 0) {
			$queryString = sprintf('tve.series = %d AND tve.episode = %d', $series, $episode);
		} else if (!empty($airdate)) {
			$queryString = sprintf('DATE(tve.firstaired) = %s', $this->pdo->escapeString(date('Y-m-d', strtotime($airdate))));
		} else {
			return false;
		}


fixed this for me... should i open a PR for this?

**Comment by DariusIII** [comment]
Yeah, do open a PR to dev branch,

**Comment by cytec** [comment]
Here we go https://github.com/nZEDb/nZEDb/pull/2325

**Comment by DariusIII** [comment]
As the fix has been merged, i am closing this issue.
