### ISSUE TITLE
tmux run.php seems to be making a direct call to mysql without using the configured username and password

### ISSUE THREAD

**Issue by liquiz** [nZEDb/nZEDb#2323]
A large number of [Note] Access denied for user 'root'@'localhost' (using password: NO) mysql events where traced back to run.php.

Heres the offending line from run.php
`        if ($showprocesslist == 1) {
                exec("tmux new-window -t $tmux_session -n showprocesslist 'printf \"\033]2;showprocesslist\033\" && watch -n .5 \"mysql -e \\\"SELECT time, state, info FROM information_schema.processlist WHERE command != \\\\\\\"Sleep\\\\\\\" AND time >= $processupdate ORDER BY time DESC \\\G\\\"\"'");
`
Show process list was enabled in the tmux settings which is what was sending the code through that code path.

root@ubuntu:/var/www/nZEDb# ./zed version all
Looking up Git tag version(s)
Hash: d00f00ef543d1ba66b2f16c0e314f93415e6d68a
XML version: vv0.6.6.2
Git version: v0.6.6.2
Looking up SQL patch version(s)
XML version: 454
 DB version: 454

**Comment by niel** [comment]
Simple answer, do not enable show process list ;-)
Longer answer: I couldn't say what the intent was there. I'll talk to the other devs about removing it as an option.

**Comment by ghost** [comment]
Another simple answer (and a massive time saver) add a ~/.my.cnf

```
[mysql]
prompt='\u@\h:\d> '
user=xxx
password=xxx
```

**Comment by b3rs3rk** [comment]
@slug1982 Thanks.  Had they read the description under the setting they would have seen that.

"You will need to create ~/.mytop, an example can be found in 'perldoc mytop'. The pane for this can not be created after tmux starts."
