### ISSUE TITLE
updated nzedb does not load (web site), with exception in log

### ISSUE THREAD

**Issue by tommytyker** [nZEDb/nZEDb#2324]
###Expected behaviour
nzedb loads at standard urls

###Actual behaviour
exception written to log php_errors.log, blank page shown (view page source produces no text)

###Steps to reproduce the behaviour
I updated to the latest version of nzedb. Restarted my system and when loading any page, I get a blank page along with the following error written to php_errors.log

02-Dec-2016 07:27:43 Europe/Berlin] PHP Fatal error:  Uncaught exception 'Exception' with message 'Unable to fetch setting from Db!' in /var/www/nzedb/app/models/Settings.php:205
Stack trace:
#0 /var/www/nzedb/nzedb/SABnzbd.php(126): app\models\Settings::value('saburl')
#1 /var/www/nzedb/www/pages/BasePage.php(366): nzedb\SABnzbd->__construct(Object(AdminPage))
#2 /var/www/nzedb/www/pages/BasePage.php(134): BasePage->setUserPreferences()
#3 /var/www/nzedb/www/pages/AdminPage.php(10): BasePage->__construct()
#4 /var/www/nzedb/www/admin/index.php(5): AdminPage->__construct()
#5 {main}
  thrown in /var/www/nzedb/app/models/Settings.php on line 205

When I go to the DB to check the settings, I have the following for saburl:

INSERT INTO `settings` (`section`, `subsection`, `name`, `value`, `hint`, `setting`) VALUES
('apps', 'sabnzbplus', 'url', 'http://localhost:8080/sabnzbd/', 'The url of the SAB installation, for example: http://localhost:8080/sabnzbd/', 'saburl');

Rasbian Wheezy
Linux XXXX 4.1.19-v7+ #858 SMP Tue Mar 15 15:56:00 GMT 2016 armv7l GNU/Linux
mysql  Ver 14.14 Distrib 5.5.53, for debian-linux-gnu (armv7l) using readline 6.2
PHP 5.6.22-0+deb8u1 (cli) (built: Jun 14 2016 18:21:48)

I did try to upgrade to mysql 5.6 but have not found appropriate instructions.  debian source does not have a package for armv7

**Comment by niel** [comment]
Which branch? It sounds like you're NOT on latest which has fixed this specific problem.

**Comment by niel** [comment]
Oops, take that back, it is still in stable branch apparently but I thought it was fixed.
It IS fixed in our Latest-testing branch, which will be merged into stable next Monday.
