### ISSUE TITLE
AMI or am I not

### ISSUE THREAD

**Issue by z9n** [nZEDb/nZEDb#2326]
Is there an AMI I can grab to quickly get this setup on amzon, or a droplet for something cloud agnostic?  DreamHost:DreamCompute, rackspace, et al?

https://github.com/nZEDb/nZEDb/issues/657
https://github.com/nZEDb/nZEDb/wiki/Install-Guides

**Comment by stevenmcastano** [comment]
Are you asking for an AMI like an actual “Amazon Machine Image” that has nZEDb running in it already?

**Comment by niel** [comment]
Dunno what an AMI is, so no.

**Comment by slydetector** [comment]
@z9n You can try the docker images which is about as close as you're going to get to an AMI - only takes about 30 mins.

https://github.com/slydetector/simply-nzedb

**Comment by stevenmcastano** [comment]
Yes, docker images isn’t a bad way to go… it’s either that or I might be able to, when I have some free time, setup a basic install and make a community AMI out of it, but there would still be some configuration you would need to do to put in your usenet server info and which groups you want to index. It would also be on a single VM with the database included so if things got much bigger than the default, you’d need to expending things out by adding new disks, expanding disks, moving the database to another VM, etc..

**Comment by b3rs3rk** [comment]
Users are free to create whatever installation images or automated installs they like.  It is important to remember that the ONLY supported method of installing is by using the guides provided and the ONLY truly supported installation platform is on Ubuntu Server.  We will help with other installs time permitting, but our primary focus needs to be on supporting what we run in our test environments.
