### ISSUE TITLE
The Grand Tour wrongly assigned to show

### ISSUE THREAD

**Issue by ghost** [nZEDb/nZEDb#2327]
The new "Top Gear" episodes are all attached to an old show called The Grand Tour. Any way to fix this for future releases?

They are currently given this TVDB id: http://thetvdb.com/?tab=series&id=311932&lid=7

**Comment by Wally73** [comment]
scene etc should post it as the grand tour 2016 then it should be right but they don't do it so its how it is :P

**Comment by ghost** [comment]
Ah makes sense
