### ISSUE TITLE
Maximum File Size to Make a Release: does not work when above 2GB

### ISSUE THREAD

**Issue by tommytyker** [nZEDb/nZEDb#2331]
###Expected behaviour
Setting a max file size to 12884901888 should delete releases larger than 12GB

###Actual behaviour
Deletes all releases larger than 2GB

###Steps to reproduce the behaviour
Go to admin/site settings/ set the above setting to the above number which is 12GB in bytes. Click save, run update_releases and watch all of your releases larger than 2GB be removed.

You can sort of confirm that by going into site settings/groups and change any group "Minimum File Size to Make a Release:" to 12884901888, click save and look at the group in View. It will show 2GB

**Comment by niel** [comment]
Are you by any chance, running on a 32 bit operating system?

**Comment by tommytyker** [comment]
Damn it, you are correct. Raspbian running on RPi3

Case closed :'( It's just that since the last few releases the step "Process Releases -> Create the NZB, delete collections/binaries/parts." has been taking 3+ hours to process 200-260 releases.. So I set a max size and the processing sped up.

**Comment by niel** [comment]
I'm sure it did speed up, as it is now ignoring a huge amount of releases because the operating system can only handle numbers up to 2GB ;-)
Make sure you have set a good minimum size too, that can cut out a lot of crap.
