### ISSUE TITLE
Composer Failing due to imagick

### ISSUE THREAD

**Issue by DrSeussFreak** [nZEDb/nZEDb#2333]
###Expected behaviour
Composer completes install.  phpinfo shows an imagick section, I am able to run imagick without issue, yet composer fails at the imagick section.

###Actual behaviour
Composer errors out with
`Installing nzedb/nzedb (v0.6.6.2)
  - Installing nzedb/nzedb (v0.6.6.2)
    Cloning d00f00ef543d1ba66b2f16c0e314f93415e6d68a from cache

Created project in nZEDb
Loading composer repositories with package information
Installing dependencies from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested PHP extension ext-imagick * is missing from your system. Install or enable PHP's imagick extension.`

###Steps to reproduce the behaviour
repeat install.

**Comment by Sweepr** [comment]
Are you sure the PHP extension imagick is loaded by PHP?

**Comment by DrSeussFreak** [comment]
my phpinfo page shows the imagick section, but php -m throws errors about the dll missing from the php ext directory, even though it is there.

**Comment by Sweepr** [comment]
Hmm, seems like your current PHP is looking in the wrong extensions dir somewhere or it's misconfigured in your PHP.ini.

Please check your setup.

**Comment by DrSeussFreak** [comment]
It was a messed up dll file, I have it resolved.  Also been doing a major update to the windows install guide on the wiki for this.  Should be 100% now.
