### ISSUE TITLE
Post Install Issues

### ISSUE THREAD

**Issue by DrSeussFreak** [nZEDb/nZEDb#2334]
Just completed installation on windows, and browsed to the site and am getting the following error

`Fatal error: Uncaught exception 'RuntimeException' with message 'Unable to load configuration file 'D:\www\nZEDb\nzedb\config\config.php'. Make sure it has been created and contains correct settings.' in D:\www\nZEDb\nzedb\config\Configure.php:51 Stack trace: #0 D:\www\nZEDb\nzedb\config\Configure.php(129): nzedb\config\Configure->loadSettings('config', true) #1 D:\www\nZEDb\nzedb\config\Configure.php(42): nzedb\config\Configure->loadEnvironment('indexer') #2 D:\www\nZEDb\nzedb\bootstrap.php(31): nzedb\config\Configure->__construct('indexer') #3 D:\www\nZEDb\libraries\lithium\core\Libraries.php(326): require('D:\\www\\nZEDb\\nz...') #4 D:\www\nZEDb\libraries\lithium\core\Libraries.php(304): lithium\core\Libraries::_configure(Array) #5 D:\www\nZEDb\app\config\bootstrap\libraries.php(136): lithium\core\Libraries::add('nzedb', Array) #6 D:\www\nZEDb\app\config\bootstrap.php(34): require_once('D:\\www\\nZEDb\\ap...') #7 D:\www\nZEDb\app\webroot\index.php(21): require('D:\\www\\nZEDb\\ap...') #8 D:\www\nZEDb\index.php(36): req in D:\www\nZEDb\nzedb\config\Configure.php on line 51`

No issues during install

`d:\www>composer create-project --stability dev --keep-vcs --prefer-source nzedb/nzedb nZEDb
Installing nzedb/nzedb (0.x-dev 8d2e0cf77e1dce99c2f47638ac5ceea3ef45b6cd)
  - Installing nzedb/nzedb (0.x-dev 8d2e0cf)
    Cloning 8d2e0cf77e1dce99c2f47638ac5ceea3ef45b6cd from cache

Created project in nZEDb
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
  - Installing fxp/composer-asset-plugin (v1.2.2)
    Cloning 60bc94db574103dfc73acb907fa79c6dfc86c96e from cache

  - Installing composer/installers (v1.2.0)
    Cloning d78064c68299743e0161004f2de3a0204e33b804 from cache

  - Installing barracudanetworks/forkdaemon-php (v1.0.9)
    Cloning 06462cffb0181514ce2559615f0e892731919187 from cache

  - Installing bower-asset/animate.css (3.5.2)
    Cloning dac3dab7b59cb6072b5d0fe23eae3805e370a58c from cache

  - Installing bower-asset/autosize-3.0.x (3.0.18)
    Cloning fa2fa308e91ff9f8ba1a9fb17a1b9cc620671ca8 from cache

  - Installing bower-asset/jquery (2.0.3)
    Cloning f852e631ba85af7da4ad7594785e122504e7b233 from cache

  - Installing bower-asset/bootstrap-2.3.x (v2.3.2)
    Cloning b4c4072679943773a7582daa63f545ba818fa627 from cache

  - Installing bower-asset/bootstrap-3.3.x (v3.3.7)
    Cloning 0b9c4a4007c44201dce9a6cc1a38407005c26c86 from cache

  - Installing bower-asset/bootstrap (v3.3.7)
    Cloning 0b9c4a4007c44201dce9a6cc1a38407005c26c86 from cache

  - Installing bower-asset/bootstrap-hover-dropdown-2.2.x (v2.2.1)
    Cloning 56c494fbb1f4ad54180c716cc07f4919e49b423a from cache

  - Installing bower-asset/bootstrap-progressbar-0.9.x (v0.9.0)
    Cloning e7ac2690384024feb89bd5122fea14dc4d819567 from cache

  - Installing bower-asset/chosen-1.5.x (v1.5.1)
    Cloning e0d29eab0d1ea12535cf1933eba4c47df099f846 from cache

  - Installing bower-asset/colorbox-1.6.x (1.6.4)
    Cloning bac78120c6ca9e63370cc317ab6f400129cd6608 from cache

  - Installing bower-asset/datatables-1.10.x (1.10.12)
    Cloning 3a432c5db3546b2ef0c192f2ae367811cb5edb9b from cache

  - Installing bower-asset/fastclick-1.0.x (v1.0.6)
    Cloning 9977a916739360ad4ffd7aa19b0016bf375e934b from cache

  - Installing bower-asset/font-awesome-4.5.x (v4.5.0)
    Cloning fddd2c240452e6c8990c4ef75e0265b455aa7968 from cache

  - Installing bower-asset/html5shiv-3.7.x (3.7.3)
    Cloning ed28c56c071bddfe7d635ad88995674957a016be from cache

  - Installing bower-asset/icheck-1.0.x (1.0.2)
    Cloning 8a6eb37bd7dab1e843c1b630c91c6398ff409d05 from cache

  - Installing bower-asset/jquery-1.9.x (1.9.1)
    Cloning d71f6a53927ad02d728503385d15539b73d21ac8 from cache

  - Installing bower-asset/jquery-2.2.x (2.2.4)
    Cloning c0185ab7c75aab88762c5aae780b9d83b80eda72 from cache

  - Installing bower-asset/jquery-migrate-1.4.x (1.4.0)
    Cloning 29077d39689bddad05036a537d49c4cf96488569 from cache

  - Installing bower-asset/jquery.nicescroll-3.6.x (v3.6.8-patch1)
    Cloning 25737c1a8ecfaccf219a13142d300b64e52e6b58 from cache

  - Installing bower-asset/noty-2.3.x (v2.3.8)
    Cloning 6fe2cf81c7b8ecdbdafaa875b82b78cf65e2f100 from cache

  - Installing bower-asset/pace-1.0.x (v1.0.2)
    Cloning c6846cbf6b928e9903b569269fa9fbf32f2554f4 from cache

  - Installing bower-asset/pnotify-3.0.x (3.0.0)
    Cloning 2c6a12b5d8a6b55d21beae5b35c2a643fcfe4a90 from cache

  - Installing bower-asset/respond-1.4.x (1.4.2)
    Cloning 20b7f4a192bb910c8c7e067b961de38519d334e4 from cache

  - Installing bower-asset/responsive-tables-js-1.0.x (v1.0.6)
    Cloning 10c8ea1f59acb8a00dc4af898d0cd54a527eef5d from cache

  - Installing bower-asset/select2-4.0.x (4.0.3)
    Cloning 566c7846fbf8c3b7674346f26d0ee872c0a77629 from cache

  - Installing bower-asset/slimscroll-1.3.x (v1.3.8)
    Cloning cf39d364e777ef95574c30c42d3b85cb2bf325d3 from cache

  - Installing bower-asset/tinymce-builded (4.4.3)
    Cloning b6c9e915a1f0e415725c7cad901165f016eb58f0 from cache

  - Installing giantbomb/giantbomb (dev-master 2f80210)
    Cloning 2f80210e54e8310380221759b26117c1351b8031 from cache

  - Installing google/recaptcha (1.1.2)
    Cloning 2b7e00566afca82a38a1d3adb8e42c118006296e from cache

  - Installing james-heinrich/getid3 (v1.9.12)
    Cloning 41c05612d532d30f07680cad3a4a6efbec7fc7f5 from cache

  - Installing joshpinkney/tv-maze-php-api (dev-master 03e60dd)
    Cloning 03e60ddbb4a5516aee531be5f4fafc92922f8ae4 from cache

  - Installing moinax/tvdb (v1.0.6)
    Cloning 26f33df9e0ddf9b0b6ba9deeb43f1fa83b483085 from cache

  - Installing nzedb/git.php (dev-master 327f844)
    Cloning 327f844c964fc078075a0a77e789b8dfd8b5016f from cache

  - Installing phpmailer/phpmailer (v5.2.16)
    Cloning 1d85f9ef3ecfc42bbc4f3c70d5e37ca9a65f629a from cache

  - Installing smarty/smarty (v3.1.30)
    Cloning ed2b7f1146cfda13df1eea8a5f707a1b771b6e7e from cache

  - Installing unionofrad/lithium (1.2.x-dev 49d2d46)
    Cloning 49d2d46a63d6f2a94c28e392ee67b150aed4d524 from cache

  - Installing zeebinz/rarinfo (v2.5.0)
    Cloning 0ee81ff312bf29257ff82420a8d1b1e02ad42c9d from cache

  - Installing unionofrad/manual (1.1.x-dev 5e7781e)
    Cloning 5e7781e131916b2401245ae7d12e77a41ecc5d2b from cache

nzedb/nzedb suggests installing ext-simple_php_yenc_decode (Greatly improves yEnc decoding speed in PHP 5.x)
nzedb/nzedb suggests installing ext-xdebug (For developement work)
nzedb/nzedb suggests installing ext-php-yenc (Improves yEnc decoding speed for PHP 7.0+ (and 5.6))
phpmailer/phpmailer suggests installing league/oauth2-google (Needed for Google XOAUTH2 authentication)
Generating autoload files`

**Comment by Wally73** [comment]
mm install procedure is changed afaik

just do a fresh git clone in your wwwroot and then composer install

**Comment by DrSeussFreak** [comment]
So same issue, but did a git clone with composure install afterwards

`D:\>cd d:\www

d:\www>git clone https://github.com/nZEDb/nZEDb.git
Cloning into 'nZEDb'...
remote: Counting objects: 117898, done.
remote: Compressing objects: 100% (135/135), done.
remote: Total 117898 (delta 56), reused 0 (delta 0), pack-reused 117760
Receiving objects: 100% (117898/117898), 91.61 MiB | 1.19 MiB/s, done.
Resolving deltas: 100% (81265/81265), done.
Checking connectivity... done.

d:\www>cd nZEDb

d:\www\nZEDb>composer install --prefer-source
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
  - Installing fxp/composer-asset-plugin (v1.2.2)
    Cloning 60bc94db574103dfc73acb907fa79c6dfc86c96e from cache

  - Installing composer/installers (v1.2.0)
    Cloning d78064c68299743e0161004f2de3a0204e33b804 from cache

  - Installing barracudanetworks/forkdaemon-php (v1.0.9)
    Cloning 06462cffb0181514ce2559615f0e892731919187 from cache

  - Installing bower-asset/animate.css (3.5.2)
    Cloning dac3dab7b59cb6072b5d0fe23eae3805e370a58c from cache

  - Installing bower-asset/autosize-3.0.x (3.0.18)
    Cloning fa2fa308e91ff9f8ba1a9fb17a1b9cc620671ca8 from cache

  - Installing bower-asset/jquery (2.0.3)
    Cloning f852e631ba85af7da4ad7594785e122504e7b233 from cache

  - Installing bower-asset/bootstrap-2.3.x (v2.3.2)
    Cloning b4c4072679943773a7582daa63f545ba818fa627 from cache

  - Installing bower-asset/bootstrap-3.3.x (v3.3.7)
    Cloning 0b9c4a4007c44201dce9a6cc1a38407005c26c86 from cache

  - Installing bower-asset/bootstrap (v3.3.7)
    Cloning 0b9c4a4007c44201dce9a6cc1a38407005c26c86 from cache

  - Installing bower-asset/bootstrap-hover-dropdown-2.2.x (v2.2.1)
    Cloning 56c494fbb1f4ad54180c716cc07f4919e49b423a from cache

  - Installing bower-asset/bootstrap-progressbar-0.9.x (v0.9.0)
    Cloning e7ac2690384024feb89bd5122fea14dc4d819567 from cache

  - Installing bower-asset/chosen-1.5.x (v1.5.1)
    Cloning e0d29eab0d1ea12535cf1933eba4c47df099f846 from cache

  - Installing bower-asset/colorbox-1.6.x (1.6.4)
    Cloning bac78120c6ca9e63370cc317ab6f400129cd6608 from cache

  - Installing bower-asset/datatables-1.10.x (1.10.12)
    Cloning 3a432c5db3546b2ef0c192f2ae367811cb5edb9b from cache

  - Installing bower-asset/fastclick-1.0.x (v1.0.6)
    Cloning 9977a916739360ad4ffd7aa19b0016bf375e934b from cache

  - Installing bower-asset/font-awesome-4.5.x (v4.5.0)
    Cloning fddd2c240452e6c8990c4ef75e0265b455aa7968 from cache

  - Installing bower-asset/html5shiv-3.7.x (3.7.3)
    Cloning ed28c56c071bddfe7d635ad88995674957a016be from cache

  - Installing bower-asset/icheck-1.0.x (1.0.2)
    Cloning 8a6eb37bd7dab1e843c1b630c91c6398ff409d05 from cache

  - Installing bower-asset/jquery-1.9.x (1.9.1)
    Cloning d71f6a53927ad02d728503385d15539b73d21ac8 from cache

  - Installing bower-asset/jquery-2.2.x (2.2.4)
    Cloning c0185ab7c75aab88762c5aae780b9d83b80eda72 from cache

  - Installing bower-asset/jquery-migrate-1.4.x (1.4.0)
    Cloning 29077d39689bddad05036a537d49c4cf96488569 from cache

  - Installing bower-asset/jquery.nicescroll-3.6.x (v3.6.8-patch1)
    Cloning 25737c1a8ecfaccf219a13142d300b64e52e6b58 from cache

  - Installing bower-asset/noty-2.3.x (v2.3.8)
    Cloning 6fe2cf81c7b8ecdbdafaa875b82b78cf65e2f100 from cache

  - Installing bower-asset/pace-1.0.x (v1.0.2)
    Cloning c6846cbf6b928e9903b569269fa9fbf32f2554f4 from cache

  - Installing bower-asset/pnotify-3.0.x (3.0.0)
    Cloning 2c6a12b5d8a6b55d21beae5b35c2a643fcfe4a90 from cache

  - Installing bower-asset/respond-1.4.x (1.4.2)
    Cloning 20b7f4a192bb910c8c7e067b961de38519d334e4 from cache

  - Installing bower-asset/responsive-tables-js-1.0.x (v1.0.6)
    Cloning 10c8ea1f59acb8a00dc4af898d0cd54a527eef5d from cache

  - Installing bower-asset/select2-4.0.x (4.0.3)
    Cloning 566c7846fbf8c3b7674346f26d0ee872c0a77629 from cache

  - Installing bower-asset/slimscroll-1.3.x (v1.3.8)
    Cloning cf39d364e777ef95574c30c42d3b85cb2bf325d3 from cache

  - Installing bower-asset/tinymce-builded (4.4.3)
    Cloning b6c9e915a1f0e415725c7cad901165f016eb58f0 from cache

  - Installing giantbomb/giantbomb (dev-master 2f80210)
    Cloning 2f80210e54e8310380221759b26117c1351b8031 from cache

  - Installing google/recaptcha (1.1.2)
    Cloning 2b7e00566afca82a38a1d3adb8e42c118006296e from cache

  - Installing james-heinrich/getid3 (v1.9.12)
    Cloning 41c05612d532d30f07680cad3a4a6efbec7fc7f5 from cache

  - Installing joshpinkney/tv-maze-php-api (dev-master 03e60dd)
    Cloning 03e60ddbb4a5516aee531be5f4fafc92922f8ae4 from cache

  - Installing moinax/tvdb (v1.0.6)
    Cloning 26f33df9e0ddf9b0b6ba9deeb43f1fa83b483085 from cache

  - Installing nzedb/git.php (dev-master 327f844)
    Cloning 327f844c964fc078075a0a77e789b8dfd8b5016f from cache

  - Installing phpmailer/phpmailer (v5.2.16)
    Cloning 1d85f9ef3ecfc42bbc4f3c70d5e37ca9a65f629a from cache

  - Installing smarty/smarty (v3.1.30)
    Cloning ed2b7f1146cfda13df1eea8a5f707a1b771b6e7e from cache

  - Installing unionofrad/lithium (1.2.x-dev 49d2d46)
    Cloning 49d2d46a63d6f2a94c28e392ee67b150aed4d524 from cache

  - Installing zeebinz/rarinfo (v2.5.0)
    Cloning 0ee81ff312bf29257ff82420a8d1b1e02ad42c9d from cache

  - Installing unionofrad/manual (1.1.x-dev 5e7781e)
    Cloning 5e7781e131916b2401245ae7d12e77a41ecc5d2b from cache

phpmailer/phpmailer suggests installing league/oauth2-google (Needed for Google XOAUTH2 authentication)
Generating autoload files`

**Comment by niel** [comment]
When you say "Browsed to the site" what url? You need to go to <your-site-url>/install to setup the configuration, you do not mention doing this in your description, which would explain the lack of config file if you're going to any other address.

**Comment by DrSeussFreak** [comment]
I have a vhost for www.nz.com setup, as well as host file entries, so I go to www.nz.com and I get that error.  When I go to www.nz.com/install I get object not found

**Comment by niel** [comment]
sounds like your install is broken. Make sure your vhost file is correct (rewrite rules mainly).

**Comment by DrSeussFreak** [comment]
Not sure where the install would be corrupt, I had it complete without issue.  As far as my vhosts goes, it is setup as 

<VirtualHost *:80>
	ServerName nz.com
	ServerAlias www.nz.com
	DocumentRoot D:/www/nZEDb
</VirtualHost>

**Comment by DrSeussFreak** [comment]
I am seeing the following error at www.nz.com/www/install, when I try to call out the install directory directly

`Server error!

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there was an error in a CGI script.

If you think this is a server error, please contact the webmaster.

Error 500

www.nz.com
Apache/2.4.23 (Win32) OpenSSL/1.0.2h PHP/5.6.28`

**Comment by Wally73** [comment]
your docroot is wrong

DocumentRoot D:/www/nZEDb
should be D:/www/nZEDb/www

**Comment by DrSeussFreak** [comment]
I have had it set that way, and I get the following error

```
Server error!

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there was an error in a CGI script.

If you think this is a server error, please contact the webmaster.

Error 500

www.nz.com
Apache/2.4.23 (Win32) OpenSSL/1.0.2h PHP/5.6.28
```

**Comment by DrSeussFreak** [comment]
same when I add /install at the end

**Comment by Wally73** [comment]
then its also a permission issue I think (which on windows can be a pain in the ...

**Comment by DrSeussFreak** [comment]
I got it, it was a vhosts issue, I copied the one from the general install guide, and it worked fine.

```
<VirtualHost *:80>   
	<Directory  D:/www/nZEDb/www/>  
		Options FollowSymLinks  
		AllowOverride All  
		Order allow,deny  
		allow from all  
	</Directory>  

	ServerAdmin drseussfreak@gmail.com 
	ServerName nz.com  
	ServerAlias www.nz.com  
	DocumentRoot D:/www/nZEDb/www
	LogLevel warn  
	ServerSignature Off  
</VirtualHost>  
```
