### ISSUE TITLE
Update Error: Your database is not up to date

### ISSUE THREAD

**Issue by Hobbabobba** [nZEDb/nZEDb#2335]
I did an update with
```
git checkout 0.x
git reset --hard origin/0.x
zed update nzedb
```
and got the error message

```
Info: Starting the tmux server and monitor script.
Error:
Your database is not up to date. Reported patch levels
   Db: 442
file: 454
Please update.
 php /var/www/nzedb/cli/update_db.php true
```
but in the new version, `/var/www/nzedb/cli/update_db.php` is gone.
Any idea how to fix it?

**Comment by DariusIII** [comment]
Do ./zed update db.

**Comment by Hobbabobba** [comment]
Still get the same error message:
```
Info: Starting the tmux server and monitor script.

Error:
Your database is not up to date. Reported patch levels
   Db: 442
file: 454
Please update.
 php /var/www/nzedb/cli/update_db.php true
```
the command `./zed update db` finished without any error message.

**Comment by niel** [comment]
What exactly does "./zed update db" output? It should always show some output, so if it doesn't there is a problem.

**Comment by Hobbabobba** [comment]
it shows no output at all. no errormessage, nothing.

**Comment by niel** [comment]
The there is a problem, check your PHP error log.
None of the ./zed commands exit without some output, even if it only says everything is Ok ;-)

**Comment by Hobbabobba** [comment]
can you please give me an idea, where to find the log-file?

**Comment by niel** [comment]
copy the .../nzedb/config/settings.example.php file to settings.php and read the contents. There is a setting in there for enabling error logs in the .../resources/logs directory

**Comment by Hobbabobba** [comment]
my system crashed, so i have to start from scratch with a fresh install anyway :) Merry Christmas!
