### ISSUE TITLE
All Tmux panes dead

### ISSUE THREAD

**Issue by bobtongue** [nZEDb/nZEDb#2337]
###Expected behaviour
Processes run in tmux pane, then countdown and run again

###Actual behaviour
Processes run in tmux pane, countdown, then pane dies. Will not rerun program

###Steps to reproduce the behaviour
stop tmux and restart. Even monitor pane dies. Cannot find any error logs that explain this. I am not a tmux expert however. Help would be appreciated.

**Comment by DariusIII** [comment]
Let me guess, Ubuntu 16.04 with default tmux (2.1)?

**Comment by bobtongue** [comment]
no, Gentoo with tmux 1.9. I haven't updated tmux because of problems with the version 2 configuration. Was there a change in the default config in the last update?

**Comment by niel** [comment]
what's in your PHP error log?

**Comment by bobtongue** [comment]
I see a fatal error here:

[16-Dec-2016 06:55:34 America/New_York] PHP Fatal error:  Uncaught exception 'lithium\data\model\QueryException' with message 'SELECT `Settings`.`value`, `Settings`.`hint` FROM `settings` AS `Settings` WHERE `Settings`.`name` = 'imdblanguage' AND `Settings`.`subsection` = 'categorise' AND `Settings`.`section` = 'indexer';: MySQL server has gone away' in /var/www/news.server.com/htdocs/nZEDb/libraries/lithium/data/source/Database.php:1604
Stack trace:
#0 /var/www/news.server.com/htdocs/nZEDb/libraries/lithium/aop/Filters.php(231): lithium\data\source\Database->lithium\data\source\{closure}(Array)
#1 /var/www/news.server.com/htdocs/nZEDb/libraries/lithium/data/source/Database.php(1605): lithium\aop\Filters::run(Object(lithium\data\source\database\adapter\MySql), '_error', Array, Object(Closure))
#2 /var/www/news.server.com/htdocs/nZEDb/libraries/lithium/data/source/database/adapter/MySql.php(406): lithium\data\source\Database->_error('SELECT `Setting...')
#3 /var/www/news.server.com/htdocs/nZEDb/libraries/lithium/aop/Filters.php(231): lithium\data\sourc in /var/www/news.server.com/htdocs/nZEDb/libraries/lithium/data/source/Database.php on line 1604

I have been getting warnings in the logs about msql server has gone away forever, but not fatal exceptions

**Comment by bobtongue** [comment]
Looking back, I see that this is not a new error in the log. Tmux was running fine up until a week ago when I updated zed. Tmux has been down since then. I just noticed this morning that nothing had updated I restarted tmux after the update. There is nothing new in the log that would explain this.

**Comment by bobtongue** [comment]
In TV processing getting a bunch of these:

Video ID for Dirk Gentlys Holistic Detective Agency not found in local db, checking web.
Bad image data, skipping processing
Found TVDB Match!
Found TVDB Match!
Video ID for Mozart in the Jungle found in local db, attempting episode match.
Video ID for Yuri On ICE found in local db, attempting episode match.
Bad image data, skipping processing
Found TVDB Match!
Found TVDB Match!
Video ID for Mozart in the Jungle found in local db, attempting episode match.
Video ID for Have I Got News For You found in local db, attempting episode match.
Bad image data, skipping processing

**Comment by DariusIII** [comment]
That is Ok, imagick spits that error on bad images.

**Comment by bobtongue** [comment]
Something else interesting, don't know if it has anything to do with this but when I went to restart tmux, i shut it down with php stop.php. After it finished I checked just to see and tmux was still running.

**Comment by DariusIII** [comment]
That just stops tmux, to kill tmux completely you either kill it all with 

`killall tmux`

or kill the session with

`tmux kill-session -t nZEDb`

**Comment by bobtongue** [comment]
gotcha. Thats what I did.

**Comment by bobtongue** [comment]
Do you think it would be wise to upgrade tmux to 2.1? I haven't looked at it in a whuile and I know you guys were working on it.

**Comment by niel** [comment]
Definitely not. If you upgrade go to 2.3+ as 2.1 and 2.2 are both broken for tmux use

**Comment by bobtongue** [comment]
If I go to 2.3, will I need to make changes to the tmux config?

**Comment by niel** [comment]
Not sure if we merged them into dev branch yet, but we have some changes which automatically use the correct file for your version.

**Comment by bobtongue** [comment]
Well, I am on master. So that might be a problem

**Comment by bobtongue** [comment]
If I use misc/update/nix/tmux/tmux-2.1.conf from here: https://github.com/nZEDb/nZEDb/pull/2321/commits/e180aad11cfb010c2d577695d7c11499d937e3f2
Do you think I would be OK with that?

**Comment by bobtongue** [comment]
Nah that won't work
I see what it's doing now

**Comment by niel** [comment]
Look in this branch https://github.com/nZEDb/nZEDb/tree/dev-tmux

**Comment by bobtongue** [comment]
Beautiful. Thanks. I will update to 2.3 and grab those configs. Then we will see if it fixes the problem. Crossing my fingers since tmux 2.3 is not in Gentoo's stable branch yet. It's not the first time I have stepped out onto the "bleeding edge". Hopefully this will do the trick.

**Comment by bobtongue** [comment]
Shoot. Now what

Starting Tmux...
Resetting expired collections dateadded to now. This could take a minute or two. Really.
9,589 collections reset.
no server running on /tmp/tmux-0/default
no server running on /tmp/tmux-0/default
no current session

**Comment by bobtongue** [comment]
OK, so here is the deal. Tmux 2.3 won't run with this config on gentoo. I don't know if its gentoo or the config. I downgraded to both 2.2 and 2.1 and those run, but not well and not right. I downgraded back to 1.9a (it wasn't easy) and at least tmux runs now, but still doing the same thing as I originally wrote about. Back to the drawing board.

**Comment by bobtongue** [comment]
I repaired all mysql tables, rebooted the server and tmux seems to be working properly now. Keeping my fingers crossed. Not sure what the problem was, but as long as it is working I am not complaining.
