### ISSUE TITLE
backfill groups is either 1 at a time or all.

### ISSUE THREAD

**Issue by ghost** [nZEDb/nZEDb#2340]
backfill option 'group'  does not seem to work, as a guess due to misc/update/python/backfill_threaded.py looking at 

SELECT value FROM tmux WHERE setting = 'backfill_days'

So the only backfill options are 1 group at a time (safe) or all backfill enabled groups at once.

**Comment by niel** [comment]
We do not support the python scripts any more. Haven't done so for a lonnnnnnnnggg time.

**Comment by ghost** [comment]
Could we get the option to have safe backfill listen to how many groups you want to backfill?

The issue I am seeing is performance related. If you backfill 1 group fast then you get deadlocks on the table. It would be nice to take advantage of TPG

**Comment by ghost** [comment]
By fast I mean multiple threads (any more than 2 in my case)

**Comment by kaibosh** [comment]
Maybe the php version of "safe backfill" is closer to what you're looking for...

  `misc/update/nix/multiprocessing/safe.php backfill`

However, iirc it won't use multiple threads on a single group like the old python version does.

**Comment by niel** [comment]
Tmux has similar options and I believe it does use the threads setting from Site Edit => Threaded settings => Backfill.

**Comment by ghost** [comment]
The safe backfill (what tmux uses) can do threads but it's threads per one group. Causes deadlocks.

**Comment by ghost** [comment]
If you add  `ORDER BY name ASC` to 
https://github.com/nZEDb/nZEDb/blob/0.x/nzedb/libraries/Forking.php#L288

then you can use the threads to control how many groups are backfilled when using 'All' method.
