### ISSUE TITLE
Releases are taking a bit longer than usual on the latest dev build.

### ISSUE THREAD

**Issue by dilbaggins** [nZEDb/nZEDb#2341]
###Expected behaviour
releases being created as with prior versions

###Actual behaviour
releases are taking upwards of 2-3HRS  from post to be available.  TV for example used to 15-20 after post.

###Steps to reproduce the behaviour
latest dev: 
Hash: 589d924f1e0710b3d54fcd880cf952822ed88bbe
XML version: 0.0.0-dev
Git version: 0.6.6.2
Looking up SQL patch version(s)
XML version: 460
 DB version: 460

run tmux for a while and noticing 
<img width="506" alt="screen shot 2016-12-19 at 3 30 12 pm" src="https://cloud.githubusercontent.com/assets/3989347/21328060/15b4bd42-c600-11e6-9bc7-66a36d2cdb1d.png">

**Comment by niel** [comment]
your version is behind. Current version is v0.6.7.0

**Comment by dilbaggins** [comment]
i see this?  

Your branch is up-to-date with 'origin/dev'

:/var/www/nZEDb$ ./zed version git
Looking up Git tag version(s)
Hash: dbed1da26b9e534d8d729ef43e2d2dee06e56e35
XML version: 0.0.0-dev
Git version: 0.6.6.2

??

**Comment by Wally73** [comment]
dev shows indeed a lower Git version

wally@debian:/var/www/nZEDb$ ./zed version all
Looking up Git tag version(s)
Hash: dbed1da26b9e534d8d729ef43e2d2dee06e56e35
XML version: 0.0.0-dev
Git version: 0.6.6.2
Looking up SQL patch version(s)
XML version: 461
 DB version: 461

**Comment by dilbaggins** [comment]
and my parts table continues to grow... its very strange.  are you seeing this as well @Wally73

**Comment by niel** [comment]
Hmm, I'll look at the version command to see what's up.
As for the reported problem I have no ideas what would cause that.

**Comment by niel** [comment]
this is what I get on dev branch for ./zed version all
Looking up Git tag version(s)
Hash: dbed1da26b9e534d8d729ef43e2d2dee06e56e35
XML version: 0.0.0-dev
Git version: 0.6.7.0
Looking up SQL patch version(s)
XML version: 461
 DB version: 461

I'm at a loss to understand how you guys get something different. For *why* you do, I would guess it is because I do the tagging, but that doesn't explain how you get something else shown.

**Comment by niel** [comment]
ah, think I solved it (the version, not the main problem). try pulling

**Comment by Wally73** [comment]
version is fixed now indeed

wally@debian:/var/www/nZEDb$ git pull
remote: Counting objects: 1, done.
remote: Total 1 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (1/1), done.
From https://github.com/nZEDb/nZEDb
 * [new tag]         v0.6.7.0   -> v0.6.7.0
Already up-to-date.
wally@debian:/var/www/nZEDb$ ./zed version all
Looking up Git tag version(s)
Hash: dbed1da26b9e534d8d729ef43e2d2dee06e56e35
XML version: 0.0.0-dev
Git version: 0.6.7.0
Looking up SQL patch version(s)
XML version: 461
 DB version: 461


I didn't had issues as far as I know with parts etc stuff (or slow build of releases) only releases weren't able to deleted but that is fixed during the night by @niel

**Comment by dilbaggins** [comment]
@niel i have 6.7.0 but still my parts table is growing.  any ideas on what i can do?

**Comment by niel** [comment]
Not really. No one else has reported this as a problem, so it is likely specific to your configuration. This is more likely to be a bunch of crap releases clogging your parts table, as anything else if you haven't made any changes recently.

**Comment by dilbaggins** [comment]
@niel for closure/dev's sake.  the issue above was related to "Crossposted Time Check:" being set to 1 vs default 2...  a cautionary tale folks DO NOT SET CROSSPOST lower than default (2)
