### ISSUE TITLE
Re-Add Browse Menu

### ISSUE THREAD

**Issue by DrSeussFreak** [nZEDb/nZEDb#2344]
Like a dumbass, I deleted the browse menu.  I want to add it back, but am not sure how, could someone let me know?

**Comment by DariusIII** [comment]
What do you mean by: 

> I deleted the browse menu. 

Edited or deleted some theme files?

**Comment by DrSeussFreak** [comment]
On 

`admin --> site settings --> menu items --> view`

I was removing items, and removed brose.

**Comment by DariusIII** [comment]
Do: 

`admin --> site settings --> menu items --> add`

title: Browse
href: browse

ordinal: 12

**Comment by DrSeussFreak** [comment]
I knew it was simple, thanks!
