### ISSUE TITLE
tmux mouse not working

### ISSUE THREAD

**Issue by dilbaggins** [nZEDb/nZEDb#2345]
###Expected behaviour
click on any pane in tmux and be able to traverse the menus

###Actual behaviour
clicking and resizing not happening when im in the tmux panes.  i have not changed anything at all with the tmux.conf file.

###Steps to reproduce the behaviour
**nzedb version:**  

Looking up Git tag version(s)
Hash: 1e8f61486a9be35ce9565129f5cc1468a3664fa9
XML version: 0.0.0-dev
Git version: 0.6.7.0
Looking up SQL patch version(s)
XML version: 461
 DB version: 461

**tmux  version:** 2.0

Ubuntu version:  
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty

**Comment by dilbaggins** [comment]
@kaibosh https://bbs.archlinux.org/viewtopic.php?id=204091

**Comment by kaibosh** [comment]
Do you use powerline mode?

**Comment by dilbaggins** [comment]
> Do you use powerline mode?

yes sir.

**Comment by dilbaggins** [comment]
@kaibosh whats weird is i was thinking it was a bind thing (tried control + m)... didnt see "mouse mode on" etc as i see in the conf.

**Comment by kaibosh** [comment]
Ah, OK ... then I know where the problem is. 

Until I can get a PR in you can either disable powerline, or replace the powerline/tmux.conf file from 0.x i.e:
`misc/update/nix/tmux/powerline/tmux.conf`

**Comment by dilbaggins** [comment]
Happy Holidays!  thank you! (reverting to old resolved the resizing switching issue for now. :)

**Comment by kaibosh** [comment]
Great thanks, about to head out myself. Have a good one!
