### ISSUE TITLE
Web API Documentation

### ISSUE THREAD

**Issue by 8cylinder** [nZEDb/nZEDb#2347]
I want to add support for nZEDb to my app ([TV Overlord](https://github.com/8cylinder/tv-overlord)) and I'm having a hard time finding documentation for the web api.  If it doesn't exist, should I use [newznab's](http://newznab.readthedocs.io/en/latest/misc/api/) web api documentation?

If it is the same as newznab, is there any plans for the api to diverge in the future?

**Comment by DariusIII** [comment]
You did not look in right place :)

https://github.com/nZEDb/nZEDb/blob/0.x/docs/newznab_api_specification.txt

**Comment by 8cylinder** [comment]
Thank you, that's exactly what I need!

**Comment by niel** [comment]
It will possibly diverge in the future, but I don't see that happening in the near term as there is far more important work to be done first.
