### ISSUE TITLE
Duplicate Entry Errors

### ISSUE THREAD

**Issue by PsychoSid** [nZEDb/nZEDb#2354]
###Expected behaviour
Releases get processed

###Actual behaviour
For some they don't.

###Steps to reproduce the behaviour
Run all the steps.

Hi,

Getting these message in the php_errors.log from the latest update.

10-Jan-2017 14:48:12 Europe/London] PHP Fatal error:  Uncaught exception 'lithium\data\model\QueryException' with message 'INSERT INTO `releases_groups` (`releases_id`, `groups_id`) VALUES (123198, 171);: Duplicate entry '123198-171' for key 'PRIMARY'' in /var/www/nZEDb/libraries/lithium/data/source/Database.php:1604
Stack trace:
#0 /var/www/nZEDb/libraries/lithium/aop/Filters.php(231): lithium\data\source\Database->lithium\data\source\{closure}(Array)
#1 /var/www/nZEDb/libraries/lithium/data/source/Database.php(1605): lithium\aop\Filters::run(Object(lithium\data\source\database\adapter\MySql), '_error', Array, Object(Closure))
#2 /var/www/nZEDb/libraries/lithium/data/source/database/adapter/MySql.php(406): lithium\data\source\Database->_error('INSERT INTO `re...')
#3 /var/www/nZEDb/libraries/lithium/aop/Filters.php(231): lithium\data\source\database\adapter\MySql->lithium\data\source\database\adapter\{closure}(Array)
#4 /var/www/nZEDb/libraries/lithium/data/source/database/adapter/MySql.php(409): lithium\aop\Filters::run(Object(lithium\data\source\database\adap in /var/www/nZEDb/libraries/lithium/data/source/Database.php on line 1604

Is it just me or is there some issue. Anyway to clean it up ?

Thanks
Paul

**Comment by DariusIII** [comment]
We are aware of the issue, will be fixed.

**Comment by PsychoSid** [comment]
Wow that was fast. Thanks very much. Appreciate it.

**Comment by tacoflavour** [comment]
Any update, also having this issue,

**Comment by DariusIII** [comment]
I think it is fixed in dev.

Ah it's not, we fixed that in branch we currently work on.

**Comment by niel** [comment]
This should be fixed in dev and Latest-testing branches. It will go to stable branch Monday 6th Feb.
