### ISSUE TITLE
update_releases failing

### ISSUE THREAD

**Issue by DrSeussFreak** [nZEDb/nZEDb#2355]
I am trying to run `php update_releases.php 1 true`, but it fails when I do so.  See below

`d:\www\nZEDb\misc\update>php update_releases.php 1 true
Starting release update process (2017-01-10 20:01:15)

Process Releases -> Attempting to find complete collections.
59951 collections were found to be complete. Time: 34 second(s)

Process Releases -> Calculating collection sizes (in bytes).
59951 collections set to filecheck = 3(size calculated)
9 second(s)

Process Releases -> Delete collections smaller/larger than minimum size/file count from group/site setting.
Deleted 1053359 collections:
9339 smaller than, 0 bigger than, 1044020 with less files than site/group settings in: 1 minute(s)

Process Releases -> Create releases from complete collections.
1000 Collections ready to be converted to releases.

Fatal error: Uncaught exception 'lithium\data\model\QueryException' with message 'DESCRIBE `releases_groups`: Table 'nzedb.releases_groups' doesn't exist' in D:\www\nZEDb\libraries\lithium\data\source\Database.php:1604
Stack trace:
#0 D:\www\nZEDb\libraries\lithium\aop\Filters.php(231): lithium\data\source\Database->lithium\data\source\{closure}(Array)
#1 D:\www\nZEDb\libraries\lithium\data\source\Database.php(1605): lithium\aop\Filters::run(Object(lithium\data\source\database\adapter\MySql), '_error', Array, Object(Closure))
#2 D:\www\nZEDb\libraries\lithium\data\source\database\adapter\MySql.php(406): lithium\data\source\Database->_error('DESCRIBE `relea...')
#3 D:\www\nZEDb\libraries\lithium\aop\Filters.php(231): lithium\data\source\database\adapter\MySql->lithium\data\source\database\adapter\{closure}(Array)
#4 D:\www\nZEDb\libraries\lithium\data\source\database\adapter\MySql.php(409): lithium\aop\Filters::run(Object(lithium\data\source\database\adapter\MySql), '_execute', Array, Object(Closure))
#5 D:\www\nZEDb\libra in D:\www\nZEDb\libraries\lithium\data\source\Database.php on line 1604`

**Comment by DrSeussFreak** [comment]
The table does not exist, I just confirmed.  Can someone send me the sql and I will manually create it?

**Comment by DariusIII** [comment]
https://github.com/nZEDb/nZEDb/blob/0.x/resources/db/patches/mysql/0459~releases_groups.sql
