### ISSUE TITLE
v.06.8.1 Predb search not working (and old link needs removing from homepage)

### ISSUE THREAD

**Issue by adr3nal1n** [nZEDb/nZEDb#2356]
Hi,

I updated to v0.6.8.1 and I understand that the Predb link at the top of the homepage page has now been moved to the Admin panel under Misc. However:

1) The link to the Predb still remains on the homepage. (can this be removed now?)
2) The search function of the predb no longer works and throws a 404 when you try to use it, when accessing via the Admin Panel -> Misc  -> Pred Database and then try and search using the box on the top right of the page.

Thanks very much for your support.

**Comment by DariusIII** [comment]
You can remove PreDB link from homepage yourself, by going onto admin->menu and removing PreDB.

**Comment by adr3nal1n** [comment]
Thanks very much for the pointer on removing the link from the homepage.

Do you know if the 2nd point regarding searching the Pre Database is going to be looked at?

Thanks again.

**Comment by kevinlekiller** [comment]
It's probably related to this line, maybe other lines also : https://github.com/nZEDb/nZEDb/blob/0.x/www/admin/predb.php#L22

**Comment by DariusIII** [comment]
It is related to this: https://github.com/nZEDb/nZEDb/blob/0.x/www/themes/shared/templates/admin/predb.tpl#L2

Will fix it in an hour or two.
