### ISSUE TITLE
update_releases.php failing on deleting PW

### ISSUE THREAD

**Issue by DrSeussFreak** [nZEDb/nZEDb#2357]
Performing an update_releases.php and got very far until it failed with what you see below.  Any ideas?

`Process Releases -> Delete old releases and passworded releases.

Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1305 PROCEDURE nzedb.delete_release does not exist' in D:\www\nZEDb\nzedb\Releases.php:635
Stack trace:
#0 D:\www\nZEDb\nzedb\Releases.php(635): PDOStatement->execute()
#1 D:\www\nZEDb\nzedb\processing\ProcessReleases.php(1310): nzedb\Releases->deleteSingle(Array, Object(nzedb\NZB), Object(nzedb\ReleaseImage))
#2 D:\www\nZEDb\nzedb\processing\ProcessReleases.php(232): nzedb\processing\ProcessReleases->deleteReleases()
#3 D:\www\nZEDb\misc\update\update_releases.php(31): nzedb\processing\ProcessReleases->processReleases(1, 1, '', Object(nzedb\NNTP), true)
#4 {main}
  thrown in D:\www\nZEDb\nzedb\Releases.php on line 635`

**Comment by niel** [comment]
You have a missing stored procedure. See patch 0461 for syntax to add it, or just run ./zed update nzedb if you forgot.

**Comment by DrSeussFreak** [comment]
so between this and the other sql file I missed, I am missing the steps to perform an upgrade on nZEDb.  Is there an already existing wiki guide on how to do this?  Or is it just a matter of pulling the latest code, and checking for new sql files to run?

**Comment by kaibosh** [comment]
Unfortunately, the last monthly release was up for a few days before a bug was noticed with fresh installs. It appears that you performed your installation before a hot-fix (v0.6.8.1) was deployed to correct this.

Your install is likely needing patches 460 & 461 to be applied. The command "zed update nzedb" will normally perform this automatically.

Yes, there is already an existing wiki update guide linked from the wiki home page:
https://github.com/nZEDb/nZEDb/wiki/Update-Guide

**Comment by DrSeussFreak** [comment]
I am on windows, and "zed update nzedb" doesn't work as zed is not a valid command.

`d:\www\nZEDb>zed update nzedb
'zed' is not recognized as an internal or external command,
operable program or batch file.`

also via bash on windows

`d:\www\nZEDb>bash
68 packages can be updated.
39 updates are security updates.
mfederman@USSEXCALIBUR:/mnt/d/www/nZEDb$ zed update nzedb
No command 'zed' found, did you mean:
 Command 'red' from package 'ed' (main)
 Command 'jed' from package 'jed' (universe)
 Command 'med' from package 'ncl-ncarg' (universe)
 Command 'sed' from package 'sed' (main)
 Command 'zec' from package 'zec' (universe)
 Command 'ed' from package 'ed' (main)
zed: command not found`

also

`mfederman@USSEXCALIBUR:/mnt/d/www/nZEDb$ ./zed update nzedb
libraries/lithium/console/li3: 11: libraries/lithium/console/li3: php: not found`

I did run 0459, 0460 and 0461 manually as well.

**Comment by DrSeussFreak** [comment]
Ok, so I got it sorted out for windows, just added a new wiki page for it, it is [here](url)  Let me know if you think any changes are required.
