### ISSUE TITLE
Rename a.b.sounds

### ISSUE THREAD

**Issue by ghost** [nZEDb/nZEDb#2358]
a.b.sounds has a lot of stuff posted to it but most of it is not RAR'ed. It does have a PAR2 file with the proper name in it. Seems like zed isn't trying the PAR2 file because it cannot find RAR's.

Is this correct, if so how do we change that behavior?

**Comment by Bart39** [comment]
Not sure where you got the rar restriction from (but been a while since I looked)
From what I can see, nzbcontents checks for a par2 and attempts to rename, as does namefixer.
Both don't look for presence of rars

**Comment by Bart39** [comment]
i see the problem, most of these are hashed and the parsepar function specifically only looks at "other" cats excluding hashed - will test adding hashed in to the mix

EDIT: nope i'm blind, it does include hashed but am trying something with removing the "00-" from the filenames for a better match

**Comment by Fossil01** [comment]
@Bart39
