### ISSUE TITLE
Unable to browse all releases

### ISSUE THREAD

**Issue by DrSeussFreak** [nZEDb/nZEDb#2367]
When I go to browse `http://www.nz.com/browse` it shows `Sorry! There is nothing here at the moment.`.  Am I missing something?  

I am able to search out specific things, but unable to just browse all releases.

**Comment by niel** [comment]
Theme in use would be helpful

**Comment by DrSeussFreak** [comment]
I have tried Alpha and Gamma

**Comment by DrSeussFreak** [comment]
ALso, if I browse groups, I see that a.b.anime has 49342 releases, but none show up when I click it

**Comment by DariusIII** [comment]
Have you enabled postprocessing of releases? Check in mysql cli or phpmyadmin in categories table, if other is 0000 or some other value.

**Comment by DrSeussFreak** [comment]
![screen shot 2017-01-25 at 7 16 34 pm](https://cloud.githubusercontent.com/assets/175500/22316450/d382bf5a-e332-11e6-8b96-7ba2732ea7b0.png)

**Comment by DariusIII** [comment]
Edit other to be 0000.

**Comment by DrSeussFreak** [comment]
Set ID to 0000, no change

**Comment by DrSeussFreak** [comment]
Any thoughts?

**Comment by Bart39** [comment]
`SELECT r.*, CONCAT(cp.title, ' > ', c.title) AS category_name
FROM releases r
LEFT JOIN categories c ON c.id = r.categories_id
LEFT JOIN categories cp ON cp.id = c.parentid
WHERE r.nzbstatus = 1
ORDER BY r.postdate DESC`

Check what that returns - that's the base query for browse

**Comment by DrSeussFreak** [comment]
So that returned a lot of data ` Showing rows 0 - 499 (139389 total, Query took 0.0675 seconds.) [postdate: 2017-01-10 06:24:58... - 2017-01-01 15:42:02...]`

**Comment by Bart39** [comment]
Ok so in that case I would check what passwordstatus you're releases are, and what password display settings you have in site options. This is coupled with Darius's question earlier around whether you were post processing or not

**Comment by DrSeussFreak** [comment]
Which settings are you looking to gain info from?  I have it set to delete passworded releases, and to not show them.

**Comment by b3rs3rk** [comment]
If you aren't running the post process additional task in your script/pane in tmux it will never check for password and the release will never meet your viewing requirements.

**Comment by DrSeussFreak** [comment]
I just set them up in tmux, running runme_with_scrape.bat now, will see once complete.

**Comment by Bart39** [comment]
runme_with_scrape.bat is a newznab script unless you have a custom version ?

**Comment by Bart39** [comment]
runme_with_scrape does not do any post processing (the win scripts were last updated 3 years ago before current post processing existed, additionally scraping won't work either as it was renamed) so that's your issue, no post processing means all releases are initially flagged as "potentially passworded" and would be hidden based on your site options.
You would need to either amend the script to include post processing or change site options to show potentially passworded releases. You should post process anyway as that provides greater release matching potential

**Comment by DrSeussFreak** [comment]
Ok, so I changed it to show PW releases, how do I kick-off post processing, or is it automatic?

to be clear, should "runme.bat" be used, is it up-to-date?

**Comment by b3rs3rk** [comment]
I think I speak for the rest of the devs when I say we're fucking astounded you've managed to get even get it running on Windows.  We don't even think about Windows when we develop it any more.  Are you SURE you don't want to run it on *nix?

**Comment by Bart39** [comment]
To answer your question, no - all the win scripts are outdated.
None of us test it on Windows either and updates were only ever user submitted

**Comment by niel** [comment]
Not astounded, but seriously impressed ;-)
My reccommended way to run on Windows, is via a VM running Linux ;-) Failing that makes sure you have the bash thingy installed (Windows 10 Anniversary) and run with that.

**Comment by DrSeussFreak** [comment]
Only reason this exists on windows at all for me, is because I have a few apps that require windows for them to run.  I am a Linux user, built a career around it.  At this point, I have spent so much time getting everything working on Windows, it would be a let down to stop.  

I do, of course, have bash installed on Windows, and prior to that, I had cygwin to give me missing functionality.  I do have a linux box at home, but it does not had RAID like my windows server does, which I love having in case of failure.

**Comment by Bart39** [comment]
You can amend the scripts and test them, I might take a look but cannot test

**Comment by DrSeussFreak** [comment]
I will do so, thanks.

That said, I have completed post-processing, and browse still shows no results.
