### ISSUE TITLE
regex issue 

### ISSUE THREAD

**Issue by ghost** [nZEDb/nZEDb#2368]
Posts by nonscene@Ef.net (EF)  have the filename in the rars but we do something else.

eg:
Original Name: [ 240117-LS02121080WDD51H264D ]-[17/48] - "240117-LS02121080WDD51H264D.part16.rar" yEnc

Search Name: [ 240117-LS02121080WDD51H264D ]

Rar Contains: Shadowhunters.S02E04.1080p.NF.WEBRip.DD5.1.x264-ViSUM.mkv

**Comment by Bart39** [comment]
Unless there was a matching scene release / predb entry for this how would we know that was a valid name ?

**Comment by ghost** [comment]
Regexes! 👍
