### ISSUE TITLE
Fix your site?

### ISSUE THREAD

**Issue by scriptzteam** [nZEDb/nZEDb#2372]
Warning: include(/home/nzedb/www/libraries/lithium/core/Libraries.php): failed to open stream: No such file or directory in /home/nzedb/www/nzedb.com/www/app/config/bootstrap/libraries.php on line 68

Warning: include(): Failed opening '/home/nzedb/www/libraries/lithium/core/Libraries.php' for inclusion (include_path='.:/usr/local/lib/php:/usr/local/php5/lib/pear') in /home/nzedb/www/nzedb.com/www/app/config/bootstrap/libraries.php on line 68

Fatal error: Uncaught exception 'ErrorException' with message 'Lithium core could not be found. Check the value of LITHIUM_LIBRARY_PATH in /home/nzedb/www/nzedb.com/www/app/config/bootstrap/libraries.php. It should point to the directory containing your /libraries directory.' in /home/nzedb/www/nzedb.com/www/app/config/bootstrap/libraries.php:72 Stack trace: #0 /home/nzedb/www/nzedb.com/www/app/config/bootstrap.php(32): require() #1 /home/nzedb/www/nzedb.com/www/app/webroot/index.php(21): require('/home/nzedb/www...') #2 {main} thrown in /home/nzedb/www/nzedb.com/www/app/config/bootstrap/libraries.php on line 72

**Comment by tpickles** [comment]
When installing did you install using composer? Its likely you are missing dependencies. 
https://github.com/nZEDb/nZEDb/wiki/Installing-Composer

**Comment by b3rs3rk** [comment]
lol, he's saying our site is broken.  Like nzedb.com.

**Comment by ghost** [comment]
Well that's an excellent error description...

**Comment by kevinlekiller** [comment]
The one linked on the nzedb github page should be used, since anyone can submit a change, because it's hosted on github servers and uses a git repository for the source code.

https://nzedb.github.io/

https://github.com/nZEDb/nzedb.github.io

**Comment by niel** [comment]
Yes, wonderful issue title \</sarcasm>. I'll look into it. No idea why it should suddenly stop working.
I'll try setting up a redirect.

**Comment by niel** [comment]
Sorted. It was a user/permission problem
