### ISSUE TITLE
Incorrect if statement causing regex to not function properly

### ISSUE THREAD

**Issue by ghost** [nZEDb/nZEDb#2373]
https://github.com/nZEDb/nZEDb/blob/dev-mgr/nzedb/ReleaseRemover.php#L867

I was having trouble getting my regex to work. When I investigated I found that this if statement was backwards =)

**Comment by DariusIII** [comment]
No, that statement is not backwards, it is just as it needs to be.

**Comment by ghost** [comment]
pipe it through rev :P

**Comment by ghost** [comment]
Interesting. I wonder what's wrong with my setup then, since it didn't work as expected.
