### ISSUE TITLE
yydecode error

### ISSUE THREAD

**Issue by egyptianbman** [nZEDb/nZEDb#2383]
Since the last update, post processing has been throwing a lot of errors:

```
PHP Fatal error:  Uncaught exception 'Exception' with message 'Error getting data from yydecode.' in /site/app/extensions/util/yenc/adapter/Ydecode.php:52                                                                            [45/2874]
Stack trace:
#0 /site/app/extensions/util/yenc/adapter/Ydecode.php(60): app\extensions\util\yenc\adapter\Ydecode::decode('=ybegin part=1 ...', true)
#1 /site/app/extensions/util/Yenc.php(64): app\extensions\util\yenc\adapter\Ydecode::decodeIgnore('=ybegin part=1 ...')
#2 /site/nzedb/NNTP.php(1452): app\extensions\util\Yenc::decodeIgnore('=ybegin part=1 ...')
#3 /site/nzedb/NNTP.php(629): nzedb\NNTP->_getMessage('alt.binaries.te...', '1486783640.8004...')
#4 /site/nzedb/NZBContents.php(132): nzedb\NNTP->getMessages('alt.binaries.te...', '1486783640.8004...', false)
#5 /site/nzedb/Nfo.php(368): nzedb\NZBContents->getNfoFromNZB('be2f52efff0b7ed...', '4220157', '156', 'alt.binaries.te...')
#6 /site/misc/update/nix/multiprocessing/.do_not_run/switch.php(243): nzedb\Nfo->processNfoFiles(Object(nzedb\NNTP), '', 'b')
#7 {main}
  thrown in /site/app/extensions/util/yenc/adapter/Ydecode.php on line 52
PHP Fatal error:  Uncaught exception 'Exception' with message 'Error getting data from yydecode.' in /site/app/extensions/util/yenc/adapter/Ydecode.php:52
Stack trace:
#0 /site/app/extensions/util/yenc/adapter/Ydecode.php(60): app\extensions\util\yenc\adapter\Ydecode::decode('\r\n=ybegin part=...', true)
#1 /site/app/extensions/util/Yenc.php(64): app\extensions\util\yenc\adapter\Ydecode::decodeIgnore('\r\n=ybegin part=...')
#2 /site/nzedb/NNTP.php(1452): app\extensions\util\Yenc::decodeIgnore('\r\n=ybegin part=...')
#3 /site/nzedb/NNTP.php(629): nzedb\NNTP->_getMessage('alt.binaries.te...', '1486776814.5265...')
#4 /site/nzedb/NZBContents.php(132): nzedb\NNTP->getMessages('alt.binaries.te...', '1486776814.5265...', false)
#5 /site/nzedb/Nfo.php(368): nzedb\NZBContents->getNfoFromNZB('e63afed6c67c168...', '4207497', '156', 'alt.binaries.te...')
#6 /site/misc/update/nix/multiprocessing/.do_not_run/switch.php(243): nzedb\Nfo->processNfoFiles(Object(nzedb\NNTP), '', 'e')
#7 {main}
  thrown in /site/app/extensions/util/yenc/adapter/Ydecode.php on line 52
PHP Fatal error:  Uncaught exception 'Exception' with message 'Error getting data from yydecode.' in /site/app/extensions/util/yenc/adapter/Ydecode.php:52
Stack trace:
#0 /site/app/extensions/util/yenc/adapter/Ydecode.php(60): app\extensions\util\yenc\adapter\Ydecode::decode('=ybegin part=1 ...', true)
#1 /site/app/extensions/util/Yenc.php(64): app\extensions\util\yenc\adapter\Ydecode::decodeIgnore('=ybegin part=1 ...')
#2 /site/nzedb/NNTP.php(1452): app\extensions\util\Yenc::decodeIgnore('=ybegin part=1 ...')
#3 /site/nzedb/NNTP.php(629): nzedb\NNTP->_getMessage('alt.binaries.te...', '1486790285.1521...')
#4 /site/nzedb/NZBContents.php(132): nzedb\NNTP->getMessages('alt.binaries.te...', '1486790285.1521...', false)
#5 /site/nzedb/Nfo.php(368): nzedb\NZBContents->getNfoFromNZB('a2dbc9e82d193c3...', '4252459', '156', 'alt.binaries.te...')
#6 /site/misc/update/nix/multiprocessing/.do_not_run/switch.php(243): nzedb\Nfo->processNfoFiles(Object(nzedb\NNTP), '', 'a')
#7 {main}
  thrown in /site/app/extensions/util/yenc/adapter/Ydecode.php on line 52
PHP Fatal error:  Uncaught exception 'Exception' with message 'Error getting data from yydecode.' in /site/app/extensions/util/yenc/adapter/Ydecode.php:52
Stack trace:
#0 /site/app/extensions/util/yenc/adapter/Ydecode.php(60): app\extensions\util\yenc\adapter\Ydecode::decode('\r\n=ybegin part=...', true)
#1 /site/app/extensions/util/Yenc.php(64): app\extensions\util\yenc\adapter\Ydecode::decodeIgnore('\r\n=ybegin part=...')
#2 /site/nzedb/NNTP.php(1452): app\extensions\util\Yenc::decodeIgnore('\r\n=ybegin part=...')
#3 /site/nzedb/NNTP.php(629): nzedb\NNTP->_getMessage('alt.binaries.te...', 'part1of1.kCQsQ$...')
#4 /site/nzedb/NZBContents.php(132): nzedb\NNTP->getMessages('alt.binaries.te...', 'part1of1.kCQsQ$...', false)
#5 /site/nzedb/Nfo.php(368): nzedb\NZBContents->getNfoFromNZB('993e72d7cf0f7bb...', '4249282', '156', 'alt.binaries.te...')
#6 /site/misc/update/nix/multiprocessing/.do_not_run/switch.php(243): nzedb\Nfo->processNfoFiles(Object(nzedb\NNTP), '', '9')
#7 {main}
  thrown in /site/app/extensions/util/yenc/adapter/Ydecode.php on line 52
.....
```
I'm running yydecode version 0.2.10

This is running inside a Centos-based Docker container:
```
$ uname -a
Linux f609057fbf7e 4.9.6-200.fc25.x86_64 #1 SMP Thu Jan 26 10:17:45 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/redhat-release
CentOS Linux release 7.2.1511 (Core)
```

**Comment by Snarfster** [comment]
Confirmed after the latest 0.x branch pull on Ubuntu 16.04.2 also. Seems to be related to segfaults regarding nfo processing from what I can see. 

sh: #: Syntax error: "(" unexpected

**Comment by niel** [comment]
@Snarfster Unrelated to segfaults.

@egyptianbman make sure you have the correct path to yydecoder in the site settings, as this is caused by the binary failing to return any data.

**Comment by egyptianbman** [comment]
Hey @niel,

Confirmed, the path to yydecode was correct. I had to remove it to fall back to php decoding so post processing could continue.

**Comment by niel** [comment]
That only leaves the binary or the data being corrupt.

**Comment by egyptianbman** [comment]
I tried to figure out what the problem is, to no avail. I'm not familiar with yenc at all so I don't know how to determine which is bad. This happens with a fresh build of the docker container which compiles the binary in the build process.

Where is the yenc encoded content coming from, maybe I can try to convert some of it manually to see if that provides any insight?

**Comment by niel** [comment]
yEnc data comes from usenet. Article bodies contain yEncoded binary data as usenet only allows text bodies.
VERY simple test, is if the PHP decode is working correctly, then your yydecode binary is bad.

**Comment by egyptianbman** [comment]
I added some debug code to [Ydecode.php](https://github.com/nZEDb/nZEDb/blob/0.x/app/extensions/util/yenc/adapter/Ydecode.php#L49). It **_*looks*_** like everything should be working. I'm not sure why `$data` is coming back as null.

![image](https://cloud.githubusercontent.com/assets/323600/22891314/8e732962-f1d4-11e6-8b6b-c37ea7f3d18e.png)

**Comment by bobtongue** [comment]
I seem to have this problem also. Using yydecode binary. No errors if I don't use it. Is someone looking at this?

**Comment by niel** [comment]
@bobtongue not much we can look into. The problem is null being passed from yydecode binary back to PHP. One possible cause is a badly encoded file causing an error in yydecode. I'd need the encoded text of the article body to test this theory.

**Comment by bobtongue** [comment]
Interesting. It was all working great up until i restarted after updating. It is working as long as I dont use yydecode.  I cleared the postprocessing queue and started fresh and it started up with the error again on new releases. I find it hard to believe that all of a sudden the problem is yydecode. However, I defer to your judgement, you have much more experience. 

Just in case you want to see it, here is the error from php,
[17-Feb-2017 16:08:42 America/New_York] PHP Fatal error:  Uncaught exception 'Exception' with message 'Error getting data from yydecode.' in /var/www/myserver.com/htdocs/nZEDb/app/extensions/util/yenc/adapter/Ydecode.php:52
Stack trace:
#0 /var/www/myserver.com/htdocs/nZEDb/app/extensions/util/yenc/adapter/Ydecode.php(60): app\extensions\util\yenc\adapter\Ydecode::decode('\r\n=ybegin part=...', true)
#1 /var/www/myserver.com/htdocs/nZEDb/app/extensions/util/Yenc.php(64): app\extensions\util\yenc\adapter\Ydecode::decodeIgnore('\r\n=ybegin part=...')
#2 /var/www/myserver.com/htdocs/nZEDb/nzedb/NNTP.php(1452): app\extensions\util\Yenc::decodeIgnore('\r\n=ybegin part=...')
#3 /var/www/myserver.com/htdocs/nZEDb/nzedb/NNTP.php(629): nzedb\NNTP->_getMessage('alt.binaries.te...', 'part1of1.4cgB8H...')
#4 /var/www/myserver.com/htdocs/nZEDb/nzedb/processing/PostProcess.php(351): nzedb\NNTP->getMessages('alt.binaries.te...', 'part1of1.4cgB8H...', false)
#5 /var/www/myserver.com/htdocs/nZEDb/nzedb/NZBContents.php(181): nzedb\processing\ in /var/www/myserver.com/htdocs/nZEDb/app/extensions/util/yenc/adapter/Ydecode.php on line 52

**Comment by kevinlekiller** [comment]
This is the only change since September 2016: https://github.com/nZEDb/nZEDb/commit/68e3ab30a527b54f3905ffb14a26fe75ede51b57

Try reverting it and see if it works?

**Comment by bobtongue** [comment]
I reverted those two files, yydecode seems to be working fine now, error free. I will keep an eye on it, but running postprocessing error free right now. I guess you might want to take a look at what's going on with the newer files.

**Comment by DariusIII** [comment]
It means you don't have proper yydecode path setting in settings table.

**Comment by egyptianbman** [comment]
I considered reverting that locally but looking at the diff, reverting it would essentially disable use of the yydecodee binary.

**Comment by bobtongue** [comment]
I have the path of yydecode in my settings that matches the path where my binary is. Is there a "proper" location that I don't know about?

**Comment by bobtongue** [comment]
my path is "/usr/bin/yydecode"

Exactly where the binary is located

**Comment by DariusIII** [comment]
I said 

> It means you don't have proper yydecode path setting in **_## settings table_**

not in site edit, yydecoder path.

All you have to do is, from phpmyadmin or mysql cli:

```
REPLACE INTO settings (section, subsection, name, value, hint, setting)
VALUES ('apps', '', 'yydecoderpath', '', 'Path to yydecode, this will decode yEnc articles. On ubuntu/debian you can get yydecode in the getdeb repository. Compiling yydecode from source is easy/fast also. Use forward slashes in windows c:/path/to/yydecode.exe', 'yydecoderpath');
```


.

**Comment by egyptianbman** [comment]
@DariusIII that will simply unset the value of `yydecode`'s path, effectively disabling it and forcing nZEDb to use php for yenc decoding. An empty value is currently what I have in place because having the path to the `yydecode` binary as the value of that query causes the errors above.

**Comment by Bart39** [comment]
The point Darius was trying to make was that there was an issue before where the setting didn't exist properly. Doing the replace he suggested would create the settings table entry correctly and then you could set the correct path via site edit

**Comment by DariusIII** [comment]
@egyptianbman You are very stubborn you know? I offered you a solution, very simple in matter of fact, and you still refuse to do so.

**Comment by egyptianbman** [comment]
@Bart39 thanks for clarifying. I ran the sql provided, then proceeded to site edit and set the path again. After running `php ./misc/update/postprocess.php additional true`, I still see that it's failing.

![image](https://cloud.githubusercontent.com/assets/323600/23093142/3a011158-f5a0-11e6-9fe9-9a1d47210857.png)

@DariusIII I apologize if I came across as stubborn, I just wasn't sure how the sql would fix the issue. Prior to responding to your comment, I ran the following query:
```
SELECT * FROM settings WHERE name = 'yydecoderpath';
```
and saw that the values you were replacing were identical to what I already had (since I had the binary disabled, to allow decoding to succeed).

**Comment by kevinlekiller** [comment]
It's possibly some kind of escape issue, maybe the yenc data has quotes in it or something? try playing with https://secure.php.net/manual/en/function.escapeshellarg.php

**Comment by egyptianbman** [comment]
@kevinlekiller great idea! Unfortunately, wrapping `$input[1]` with `escapeshellarg` didn't do the trick. I also tried wrapping the whole command in `escapeshellcmd` which also didn't work. Lastly, I tried wrapping just the echo with `escapeshellcmd`, which also didn't work.

What did work however, was reverting https://github.com/nZEDb/nZEDb/commit/7352cf85c2a3d3d7387cc0c752aff0b8bfaf06fe

**Comment by egyptianbman** [comment]
With the commit reverted, I see a stream of `E: File read error` after every few `(cB)` lines. I'm not sure if this is intentional or another issue.

**Comment by kevinlekiller** [comment]
Could it be the silent ? It's maybe piping the output to /dev/null which would cause the return to be null.

**Comment by kevinlekiller** [comment]
I think we would want it to pipe only stderr to /dev/null now instead of stdout & stderr.

**Comment by kevinlekiller** [comment]
[kevin@kevin-pc ~ 0]$ php -r "var_dump(shell_exec('echo \"sdf\" > /dev/null 2>&1'));"
    NULL
    [kevin@kevin-pc ~ 0]$ php -r "var_dump(shell_exec('echo \"sdf\" 2> /dev/null'));"
    string(4) "sdf
    "

**Comment by egyptianbman** [comment]
I took out the silent and it's still coming back as null, running `echo 'YENC_STR' | '/usr/local/bin/yydecode' -o - -b`

**Comment by bobtongue** [comment]
@DariusIII I already have those values in my settings table. Everything ran error free all night with the reversion

**Comment by kevinlekiller** [comment]
@egyptianbman Okay, maybe it's the way nzedb is formatting the yenc data?

**Comment by egyptianbman** [comment]
Unfortunately, I don't know anything about yenc. That may be the issue.

**Comment by bobtongue** [comment]
OK, so I am assuming that since I have the correct info in the settings table and it only works correctly with the reversion, that nzedb is not finding the binary because i reverted to the old path. So when it doesn't find the setting it is using the default method of decoding? So what I see as working is actually nzedb not findng the correct setting for yydecode? Just trying to understand the debacle

**Comment by bobtongue** [comment]
So I guess I should bring the files in question up to date and leave the path to yydecode blank. That should keep things working the way they are right now, and when and if someone figures out what is going on with the yydecode binary, i can re add the path to yydecode? Sound about right?

**Comment by kevinlekiller** [comment]
@egyptianbman I think the issue is escaping, the example data I was using was fine, but I just tested with more data and using escapeshellarg with success.

**Comment by kevinlekiller** [comment]
@egyptianbman In combination with sending stdout to /dev/null

**Comment by kevinlekiller** [comment]
@egyptianbman 

```
<?php
function decode(&$text, $ignore = false, $silent = "> /dev/null 2>&1")
{
    if (!preg_match('/^(=yBegin.*=yEnd[^$]*)$/ims', $text, $input)) {
        exit("Text does not look like yEnc.\n");
    }
    $data = shell_exec(
        "echo " . escapeshellarg($input[1]) . " | '/home/kevin/Downloads/yydecode-0.2.10/src/yydecode" . "' -o - " . ($ignore ? "-b " : " ") . $silent
    );
    if ($data === null) {
        exit("Error getting data from yydecode.\n");
    }
    return $data;
}

$text = file_get_contents("https://github.com/kevinlekiller/simple_php_yenc_decode/raw/master/example/yEnc.zip.yEnc");

if (!$text) {
    exit("err downloading yenc file\n");
}

//decode($text, true); // fails since stdout is sent to /dev/null

decode($text, true, "2> /dev/null"); // good since only stderr is send to /dev/null
```

**Comment by egyptianbman** [comment]
Good catch, I didn't test both fixes together. Testing that now.

**Comment by egyptianbman** [comment]
Unfortunately, still failing:

```
┌──────────────────────────────────────────────────────────────────────────────┐
│                                     [...                                     │
└──────────────────────────────────────────────────────────────────────────────┘
array (3) [
    'original (first 100 chars)' => string (100) "=ybegin part=1 total=274 line=128 size=104857600 name=kSCF7DAVDO7B7ewK3glUnQ1N2Ho4dn.part01.rar
=yp"
    'command' => string (81) "echo ESCAPEDSHELLARG_YENC_STR | '/usr/local/bin/yydecode' -o - -b  2> /dev/null"
    '$data' => NULL
]
════════════════════════════════════════════════════════════════════════════════
Called from .../extensions/util/yenc/adapter/Ydecode.php:80
```

**Comment by kevinlekiller** [comment]
Weird, does that php script I posted above work for you?

**Comment by kevinlekiller** [comment]
You can pass -v also to make yydecode show errors (you might have to remove the redirect to /dev/null)..

**Comment by kevinlekiller** [comment]
For example:

```
echo ESCAPEDSHELLARG_YENC_STR | './yydecode' -o - -b -v
./yydecode: stdin: No `=ybegin' or `begin' line found
```

**Comment by egyptianbman** [comment]
Your script works. I tried replacing `$text` with the yenc content from your github page and that worked in the `Ydecode.php` script but when I switch back to what's coming from usenet, it fails.

**Comment by kevinlekiller** [comment]
It's probably the way nzedb sends the data to it or something? Can you put a full output of the yenc data somewhere?

**Comment by egyptianbman** [comment]
http://filebin.ca/3CpNkRl8Tuqe/yenc-raw

**Comment by kevinlekiller** [comment]
The main difference I see if the "ypart", maybe yydecode does not support multiple part with stdin?

**Comment by egyptianbman** [comment]
I think you may be right:

```
curl -s http://filebin.ca/3CpNkRl8Tuqe/yenc-raw | yydecode -o - -b > /dev/null
yydecode: -:2: Part missing (of 274 parts)
yydecode: -:3: Part missing (of 274 parts)
yydecode: -:4: Part missing (of 274 parts)
yydecode: -:5: Part missing (of 274 parts)
yydecode: -:6: Part missing (of 274 parts)
yydecode: -:7: Part missing (of 274 parts)
yydecode: -:8: Part missing (of 274 parts)
...
yydecode: -:267: Part missing (of 274 parts)
yydecode: -:268: Part missing (of 274 parts)
yydecode: -:269: Part missing (of 274 parts)
yydecode: -:270: Part missing (of 274 parts)
yydecode: -:271: Part missing (of 274 parts)
yydecode: -:272: Part missing (of 274 parts)
yydecode: -:273: Part missing (of 274 parts)
yydecode: -:274: Part missing (of 274 parts)
yydecode: -: wrote 384000 bytes; should have been 104857600
```

**Comment by kevinlekiller** [comment]
I found the real issue.
There's a maximum characters PHP can send to a subshell, it's 218838 characters (found by trial / error). If you try to send 218839 or more the command will fail with exit code 127.

    var_dump(shell_exec("echo " . escapeshellarg(substr($input[1], 0, 218838)) . " | tee /tmp/dsfsdsdf"));
    exit();

**Comment by kevinlekiller** [comment]
To get around this we would need to use https://secure.php.net/manual/en/function.proc-open.php

**Comment by kevinlekiller** [comment]
With testing, it's faster just to write the files like we did before, vs trying to buffer the yenc data into a shell variable using proc open.

**Comment by egyptianbman** [comment]
Subshell character limit, I didn't even know such a thing existed. Some googling shows that the character limit may be different for various operating systems.

**Comment by kevinlekiller** [comment]
Yeah me either. I'm surprised it's so low.

**Comment by ghost** [comment]
Man I had this issue ages ago when I switched to PHP 7.1 and php-yenc wasnt available yet. So switched back to 7.0 with yenc :P

**Comment by egyptianbman** [comment]
I'm running php 7.1.2 atm, no issues that I'm aware of. I do have https://github.com/nZEDb/nZEDb/pull/2393 in place, however.

**Comment by ghost** [comment]
php-yenc should still be faster than yydecode

**Comment by egyptianbman** [comment]
I have both installed. php-yenc was causing a segmentation fault for a while, not sure if that's still happening.

Both seem zippy, do you have a simple way to benchmark?
