### ISSUE TITLE
tmux says releases added..../ pages show no releases in 1.1 days (since last update)

### ISSUE THREAD

**Issue by danpop-chainguard** [nZEDb/nZEDb#2385]
###Expected behaviour
releases reflecting the same values as tmux output

###Actual behaviour
not showing correctly (perhaps) this is smarty related?

tmux:
![image](https://cloud.githubusercontent.com/assets/22457772/22856124/5a09ee12-f059-11e6-8436-ed4d1256bcfe.png)

browing to say TV (browse?t=5000):
![image](https://cloud.githubusercontent.com/assets/22457772/22856129/7479178c-f059-11e6-958e-10032b520ef6.png)

###Steps to reproduce the behaviour
1) latest dev build.
2) check tmux output vs browse for TV-ALL for instance.

**Comment by danpop-chainguard** [comment]
p.s if i look at TV power wall i see releases... strange indeed.

![image](https://cloud.githubusercontent.com/assets/22457772/22859279/4af5bac8-f0a4-11e6-9cdb-4a8bd10ea963.png)

**Comment by dilbaggins** [comment]
also seeing this... :)

Version
Looking up Git tag version(s)
Hash: d94bf9d
XML version: 0.0.0-dev
Git version: 0.6.9.0
Looking up SQL patch version(s)
XML version: 471
DB version: 471

**Comment by dilbaggins** [comment]
@DariusIII the above also is occurring since that patch.

**Comment by danpop-chainguard** [comment]
rollback to prior version. thx @niel
