### ISSUE TITLE
unknown option: set-remain-on-exit

### ISSUE THREAD

**Issue by OliverLeitner** [nZEDb/nZEDb#2394]
tmux does not work anymore...

running php ./start.php results in:

Starting Tmux...
Resetting expired collections dateadded to now. This could take a minute or two. Really.
0 collections reset.
invalid option: set-remain-on-exit
no server running on /tmp/tmux-1000/default
no server running on /tmp/tmux-1000/default
no server running on /tmp/tmux-1000/default
no server running on /tmp/tmux-1000/default
no server running on /tmp/tmux-1000/default
no server running on /tmp/tmux-1000/default
no server running on /tmp/tmux-1000/default
no server running on /tmp/tmux-1000/default
no server running on /tmp/tmux-1000/default
no server running on /tmp/tmux-1000/default
no server running on /tmp/tmux-1000/default
no server running on /tmp/tmux-1000/default
no server running on /tmp/tmux-1000/default
no server running on /tmp/tmux-1000/default
no server running on /tmp/tmux-1000/default
no server running on /tmp/tmux-1000/default
no server running on /tmp/tmux-1000/default
no server running on /tmp/tmux-1000/default
no server running on /tmp/tmux-1000/default
no server running on /tmp/tmux-1000/default
no server running on /tmp/tmux-1000/default
no current session

**Comment by Wally73** [comment]
branch? commit? 
info please

**Comment by OliverLeitner** [comment]
branch development.

aka:

/var/www/nZEDb$ ./zed update all
Not on the stable or dev branch! Refusing to update repository
Running composer install process...
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
Checking database version...
Db: 465,	File: 465
Up to date.
The Smarty compiled template cache has been cleaned for you

with the most current in from:

git pull https://github.com/nZEDb/nZEDb.git 0.x

**Comment by DariusIII** [comment]
You are running version of tmux that does not work with nZEDb, most likely version 2.1. Use tmux 2.0. You can find it in https://github.com/NNTmux/newznab-tmux/tree/0.x/misc/update/nix/tmux/packages folder.

**Comment by OliverLeitner** [comment]
tmux version:

tmux -V
tmux 2.3

had the same problem with a built fresh from master.

ill give the 2.0 a try, maybe that helps...

**Comment by DariusIII** [comment]
2.0 will work

**Comment by OliverLeitner** [comment]
thanks darius iii, that looks different=)
