### ISSUE TITLE
Remember me when login not actually remembering me

### ISSUE THREAD

**Issue by guyspr** [nZEDb/nZEDb#2395]
###Expected behaviour
When I check remember me, I expect the next time I visit the site I get automatically logged in.

###Actual behaviour
If I return to the site after ~1 hour, I will be signed out and have to log in again.

###Steps to reproduce the behaviour
Login with checking remember me.
Close tab and return after a while.

I'm running php7.0 with nginx for serving the site. I followed the guide to setup nZEDb with all required packages.

**Comment by egyptianbman** [comment]
What is the value of your `session.cookie_lifetime` in your server's `php.ini` file?

**Comment by guyspr** [comment]
Thanks! I had it set to 0 which equals browser close. Changed it to somewhat bigger and now works as expected.
