### ISSUE TITLE
A Rename RegEx Perhaps?

### ISSUE THREAD

**Issue by DrakeJones** [nZEDb/nZEDb#2399]
###Expected behaviour
See renamed files w/o leading cruft.

###Actual behaviour
Maybe not enough total titles to justify a new ReEx, but some clever posting is leading titles with "Legalize Suicide " in TV/Movie catagories.  Some examples:  	

"Legalize Suicide The.Daily.Show.2017.02.14.Laverne.Cox.EXTENDED.WEBRip.x264.mkv.vol000+001.PAR2 03 of 11 Disgrace 2 UseNet: NO R00 AnD 2 Few Par2 Blocks !! yEnc"

"Legalize Suicide Raiders.of.the.Lost.Ark.1981.Steven.Spielberg.George.Lucas.Harrison.Fo rd.Karen.Allen.Paul.Freeman.360p.DVDRip.EngSubS.HEVC.x265-RG.mkv.par2 01 of 12"

Legalize Suicide The.3ilmore.Girls.A.Year.in.the.Life.S01E03.Summer.REPACK.720p.WEBRip. EEFGNS.SubS.DD5.1.x264-MiNiGRiP.mkv 02 of 13 Human Grey Area: Labels vs Descriptions

###Steps to reproduce the behaviour
download TV Shows/Movies/MP3s from a.b.hdtv.x264, for example

**Comment by Wally73** [comment]
if i see it like this its better just to blacklist that poster

**Comment by DrakeJones** [comment]
A simple, elegant solution.  Thank you.
