### ISSUE TITLE
Issue with update_binaries

### ISSUE THREAD

**Issue by DrSeussFreak** [nZEDb/nZEDb#2400]
When I run the update_binaries.php script, it returns the following

`Getting 20,000 articles (1,863,454,965 to 1,863,474,964) from alt.binaries.blu-ray - (920,000 articles in queue).
Received 20000 articles of 20,000 requested, 0 blacklisted, 0 not yEnc.
Warning: 20000 articles failed to insert! [nzedb\Binaries::scan]`

for all groups..

**Comment by DrSeussFreak** [comment]
I am guessing their is a DB issue (MySQL), anyone know what to look for, or how to fix it?

**Comment by bobtongue** [comment]
I would say if you are running MyIsam then repair tables will fix it.

**Comment by DrSeussFreak** [comment]
trying that now, didn't know if there was something from the nZEDb side to try or not, but am running mysqlcheck now with the repair flag, it is on the binaries table, and going slow, which makes sense since that was where the problem seemed to be.

**Comment by DrSeussFreak** [comment]
mysqlcheck -r did the trick
