### ISSUE TITLE
TV postprocessing error after upgrade to php 7

### ISSUE THREAD

**Issue by bobtongue** [nZEDb/nZEDb#2401]
###Expected behaviour
TV releases postprocess after downloading

###Actual behaviour
TV stops processing successfully and throws this php error:
[23-Feb-2017 14:25:46 America/New_York] PHP Fatal error:  Uncaught Error: Class 'Imagick' not found in /var/www/myserver/htdocs/nZEDb/nzedb/ReleaseImage.php:92
Stack trace:
#0 /var/www/myserver/htdocs/nZEDb/nzedb/ReleaseImage.php(127): nzedb\ReleaseImage->fetchImage('http://thetvdb....')
#1 /var/www/myserver/htdocs/nZEDb/nzedb/processing/tv/TVDB.php(322): nzedb\ReleaseImage->saveImage('8986', 'http://thetvdb....', '/var/www/myserv...', '', '')
#2 /var/www/myserver/htdocs/nZEDb/nzedb/processing/tv/TVDB.php(158): nzedb\processing\tv\TVDB->getPoster('8986', '307061')
#3 /var/www/myserver/htdocs/nZEDb/nzedb/processing/PostProcess.php(263): nzedb\processing\tv\TVDB->processSite('', 'f', '1')
#4 /var/www/myserver/htdocs/nZEDb/misc/update/nix/multiprocessing/.do_not_run/switch.php(269): nzedb\processing\PostProcess->processTv('', 'f', '1')
#5 {main}
  thrown in /var/www/myserver/htdocs/nZEDb/nzedb/ReleaseImage.php on line 92

###Steps to reproduce the behaviour
upgrade to php 7 and run tmux.

After reverting to 5.6 everything works as it should.

**Comment by Wally73** [comment]
you probably forgot to install the php7 version of imagick

**Comment by bobtongue** [comment]
OK, sounds good, I will recompile imagick and see what happens

**Comment by bobtongue** [comment]
Thanks, that was the ticket. Recompiled imagick with php7 and all is hunky dory.
