### ISSUE TITLE
can't use the same comment for different releases

### ISSUE THREAD

**Issue by hansenhans** [nZEDb/nZEDb#2404]
###Expected behaviour
I should be able to use the same comment for different releases

###Actual behaviour
When I use the same comment for another release, the comment is not inserted and no error message appears on the website.

When I do the same directly in mysql I get the following error

```
MariaDB [nzedb]> INSERT INTO release_comments (releases_id,text,username,user_id,createddate,host) VALUES ("6589240","test2","admin","1","2017-02-28 12:35:13","");
ERROR 1062 (23000): Duplicate entry 'ad0234829205b9033196ba818f7a872b--0' for key 'ux_text_hash_siteid_nzb_guid'
```

###Steps to reproduce the behaviour
comment one release with the word "test", Do the same with another release and the comment is not inserted.

**Comment by DariusIII** [comment]
Your index is wrong, it should be:

https://github.com/nZEDb/nZEDb/blob/0.x/resources/db/schema/mysql-ddl.sql#L748

**Comment by hansenhans** [comment]
Thanks, that solved it. I dropped the table and recreated it. I noticed that the column with the md5 hash of the comment is gone now. Why was it in this table before? Was it used in the past and an update didn't remove it properly?

Anyway, it's solved now.
