### ISSUE TITLE
nZEDb not connecting

### ISSUE THREAD

**Issue by scottia** [nZEDb/nZEDb#2405]
Following [48ea160](https://github.com/nZEDb/nZEDb/commit/48ea160ba7eadfa965ec0e06c09a5448d42f5183) commit I can no longer connect or run nZEDb at all.

Here is the CLI Stack Trace I have following each attempt 

Stack trace:
#0 /var/www/nZEDb/libraries/lithium/data/Model.php(659): lithium\data\Model::connection()
#1 /var/www/nZEDb/app/models/Settings.php(176): lithium\data\Model::lithium\data\{closure}(Array)
#2 /var/www/nZEDb/libraries/lithium/data/Model.php(679): app\models\Settings::app\models\{closure}(Array, Object(Closure))
#3 /var/www/nZEDb/libraries/lithium/aop/Filters.php(231): lithium\data\Model::lithium\data\{closure}(Array)
#4 /var/www/nZEDb/libraries/lithium/data/Model.php(682): lithium\aop\Filters::run('app\\models\\Sett...', 'find', Array, Object(Closure))
#5 /var/www/nZEDb/app/models/Settings.php(251): lithium\data\Model::find('setting', Array)
#6 /var/www/nZEDb/app/config/bootstrap/yenc.php(44): app\models\Settings::value('apps..yydecoder...', true)
#7 /var/www/nZEDb/app/config/bootstrap.php(90): require_once('/var/www/nZEDb/.. in /var/www/nZEDb/libraries/lithium/data/Model.php on line 1470

**Comment by niel** [comment]
And the error message before the trace?

**Comment by niel** [comment]
BTW that commit should have *no* effect on your indexer *unless* the file "dev-config.json" exists. Additionally the previous check (for install.lock file existing) would have to have failed. Check that you read the Changelog and moved the appropriate files to the .../configuration directory.

**Comment by scottia** [comment]
I do not have an install.lock  How do I create one?  No install.lock in the old directory to move over to ./configuration?  i was fine until the last commit to dev

**Comment by scottia** [comment]
Here is the full error output by the way.  Sorry about that 

[28-Feb-2017 17:45:19 America/Chicago] PHP Fatal error:  Uncaught lithium\core\ConfigException: The data connection `default` is not configured for model `app\models\Settings`. in /var/www/nZEDb/libraries/lithium/data/Model.php:1470
Stack trace:
#0 /var/www/nZEDb/libraries/lithium/data/Model.php(659): lithium\data\Model::connection()
#1 /var/www/nZEDb/app/models/Settings.php(176): lithium\data\Model::lithium\data\{closure}(Array)
#2 /var/www/nZEDb/libraries/lithium/data/Model.php(679): app\models\Settings::app\models\{closure}(Array, Object(Closure))
#3 /var/www/nZEDb/libraries/lithium/aop/Filters.php(231): lithium\data\Model::lithium\data\{closure}(Array)
#4 /var/www/nZEDb/libraries/lithium/data/Model.php(682): lithium\aop\Filters::run('app\\models\\Sett...', 'find', Array, Object(Closure))
#5 /var/www/nZEDb/app/models/Settings.php(251): lithium\data\Model::find('setting', Array)
#6 /var/www/nZEDb/app/config/bootstrap/yenc.php(44): app\models\Settings::value('apps..yydecoder...', true)
#7 /var/www/nZEDb/app/config/bootstrap.php(90): require_once('/var/www/nZEDb/.. in /var/www/nZEDb/libraries/lithium/data/Model.php on line 1470
[01-Mar-2017 05:45:48 America/Chicago] PHP Fatal error:  Uncaught lithium\core\ConfigException: The data connection `default` is not configured for model `app\models\Settings`. in /var/www/nZEDb/libraries/lithium/data/Model.php:1470

**Comment by scottia** [comment]
Closing.  Creating a dummy "install.lock" resolved the issue

**Comment by niel** [comment]
The install.lock file would have been in www/install/, and should have been created when you ran the web setup.

**Comment by scottia** [comment]
I have an original install and agree it "should" have been there but was not.  Following the file moves to configuration I was able to run 4 strait days with no issue.  I had no problem until the last commit as noted.

I can't explain it as I am not as familiar with the code as you are.  Just glad a dummy .lock sorted it.

Thanks for your help.

**Comment by niel** [comment]
Glad it is working for you again.
