### ISSUE TITLE
"Minimum version for vendor 'mysql'"RuntimeException in nzedb/db/DB.php

### ISSUE THREAD

**Issue by gstorme** [nZEDb/nZEDb#2410]
Hi,

Using dev branch with latest commit 875f252c87d16cd8b1dcc1a5d5b7bfc257171b86 pulled.
DB server is Percona 5.6 (I know about the recommendation for MariaDB).

The homepage and /movies work fine.
But a 500 internal server error occurs on these pages (not limited to):

/series
/newposterwall
/rss

Also on each /getnzb.

`2017/03/08 20:45:57 [error] 31766#31766: *1563 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Minimum version for vendor 'mysql' is mysql, current version is: ' in /var/www/nZEDb/nzedb/db/DB.php:1407
Stack trace:
#0 /var/www/nZEDb/nzedb/db/DB.php(372): nzedb\db\DB->validateVendorVersion()
#1 /var/www/nZEDb/nzedb/db/DB.php(145): nzedb\db\DB->initialiseDatabase()
#2 /var/www/nZEDb/nzedb/SphinxSearch.php(36): nzedb\db\DB->__construct(Array)
#3 /var/www/nZEDb/nzedb/Releases.php(64): nzedb\SphinxSearch->__construct()
#4 /var/www/nZEDb/nzedb/http/RSS.php(41): nzedb\Releases->__construct(Array)
#5 /var/www/nZEDb/www/pages/rss.php(10): nzedb\http\RSS->__construct(Array)
#6 /var/www/nZEDb/www/index.php(82): require_once('/var/www/nZEDb/...')
#7 {main}
  thrown in /var/www/nZEDb/nzedb/db/DB.php on line 1407" while reading response header from upstream, client: x.x.x.x, server: server.local, request: "GET /rss?t=-2&dl=1&i=575&r=6106161bf697335feeb96d7daf49e515&del=1 HTTP/1.0", upstream: "fastcgi://127.0.0.1:9000", host: "server.local"
`

**Comment by gstorme** [comment]
The predb is updated by tmux ircscraper, but no releases are added.
PHP CLI error log:

`[09-Mar-2017 11:15:30 Europe/Brussels] PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Minimum version for vendor 'mysql' is mysql, current version is: ' in /var/www/nZEDb/nzedb/db/DB.php:1407
Stack trace:
#0 /var/www/nZEDb/nzedb/db/DB.php(372): nzedb\db\DB->validateVendorVersion()
#1 /var/www/nZEDb/nzedb/db/DB.php(145): nzedb\db\DB->initialiseDatabase()
#2 /var/www/nZEDb/nzedb/SphinxSearch.php(36): nzedb\db\DB->__construct(Array)
#3 /var/www/nZEDb/nzedb/NameFixer.php(162): nzedb\SphinxSearch->__construct()
#4 /var/www/nZEDb/nzedb/processing/PostProcess.php(111): nzedb\NameFixer->__construct(Array)
#5 /var/www/nZEDb/misc/update/postprocess.php(73): nzedb\processing\PostProcess->__construct(Array)
#6 {main}
  thrown in /var/www/nZEDb/nzedb/db/DB.php on line 1407
`

**Comment by scottia** [comment]
same issue.  however, just resolved in commit [326b4c1](https://github.com/nZEDb/nZEDb/commit/326b4c1a62156da8f2999115da88010ad292dc4a)
