### ISSUE TITLE
Make NZBImport check for searchname dupes

### ISSUE THREAD

**Issue by ghost** [nZEDb/nZEDb#2411]
https://github.com/nZEDb/nZEDb/blob/0.x/nzedb/NZBImport.php#L408

It only checks for usenet subject dupes. When importing some releases the subject name is slightly different because those NZBs were generated differently (multigroup).

Any way to make it also check for dupes using searchname? Dunno if this will work:
```sql
SELECT id FROM releases WHERE (name = %s OR searchname = %s) AND fromname = %s AND size BETWEEN %s AND %s
```

**Comment by ghost** [comment]
Think this fixed it:

```php
                $dupeCheck = $this->pdo->queryOneRow(
                        sprintf(
                                'SELECT id FROM releases WHERE (name = %s OR searchname = %s) AND fromname = %s AND size BETWEEN %s AND %s',
                                $escapedSubject,
                                $this->pdo->escapeString($cleanName),
                                $escapedFromName,
                                $this->pdo->escapeString($nzbDetails['totalSize'] * 0.99),
                                $this->pdo->escapeString($nzbDetails['totalSize'] * 1.01)
                        )
                );
```

**Comment by niel** [comment]
@Fossil01 that snippet would be better as a PR ;-) Cuz I have no idea where you;re talking about ;-)

**Comment by ghost** [comment]
@niel Here: https://github.com/nZEDb/nZEDb/blob/0.x/nzedb/NZBImport.php#L409

Might do a PR when im home.
