### ISSUE TITLE
php fatal error after the latest git pull

### ISSUE THREAD

**Issue by OliverLeitner** [nZEDb/nZEDb#2414]
PHP Fatal error:  Uncaught lithium\core\ConfigException: The data connection `default` is not configured for model `app\models\Settings`. in nZEDb/libraries/lithium/data/Model.php:1470
Stack trace:
#0 nZEDb/libraries/lithium/data/Model.php(659): lithium\data\Model::connection()
#1 nZEDb/app/models/Settings.php(176): lithium\data\Model::lithium\data\{closure}(Array)
#2 nZEDb/libraries/lithium/data/Model.php(679): app\models\Settings::app\models\{closure}(Array, Object(Closure))
#3 nZEDb/libraries/lithium/aop/Filters.php(231): lithium\data\Model::lithium\data\{closure}(Array)
#4 nZEDb/libraries/lithium/data/Model.php(682): lithium\aop\Filters::run('app\\models\\Sett...', 'find', Array, Object(Closure))
#5 nZEDb/app/models/Settings.php(251): lithium\data\Model::find('setting', Array)
#6 nZEDb/app/config/bootstrap/yenc.php(44): app\models\Settings::value('apps..yydecoder...', true)
#7 nZEDb/app/config/bootstrap.php(90): require_once('nZEDb/.. in nZEDb/libraries/lithium/data/Model.php on line 1470

after latest:
git pull https://github.com/nZEDb/nZEDb.git 0.x

**Comment by niel** [comment]
You did read the ReleaseNotes, didn't you? Last of the Changed section?
