### ISSUE TITLE
misc/update/python/lib/info.py still uses old path for config

### ISSUE THREAD

**Issue by phirestalker** [nZEDb/nZEDb#2416]
###Expected behaviour
read config file from configuration/config.php

###Actual behaviour
looks for config in old location

###Steps to reproduce the behaviour
just use backfill_threaded.py

The offending line is 53

**Comment by niel** [comment]
This was already updated in dev branch and will be in the next release.

**Comment by niel** [comment]
While this has been fixed in dev branch, it looks like we will be removing all of the Python support from our next release.
