### ISSUE TITLE
tmux version compatability

### ISSUE THREAD

**Issue by DrSeussFreak** [nZEDb/nZEDb#2418]
Ok, so I got tired of the Windows BS issues I was having and am running Ubuntu 16.04.2 LTS.  I have nZEDb up and running but I am getting the following error

`Sentinel:/var/www/nZEDb/misc/update/nix/tmux$ php start.php 
Error: tmux versions 2.1 and 2.2 are not compatible with nZEDb. Aborting`

I tried to manually run it when I noticed that even thought I have it enabled, it was not running, so I manually tried to run it and got the error listed above.

**Comment by Wally73** [comment]
tmux 2.0 and 2.3 work with nZEDb

**Comment by DrSeussFreak** [comment]
ok, so how does tmux auto kick-off, or do I need to do something?  I have tmux 2.3 installed now.

**Comment by Wally73** [comment]
I dont use tmux myself but take a look
https://github.com/nZEDb/nZEDb/wiki/Operational-Modii there

**Comment by DrSeussFreak** [comment]
That did the trick, thanks!
