### ISSUE TITLE
Tmux panes not respawning

### ISSUE THREAD

**Issue by bobtongue** [nZEDb/nZEDb#2421]
Every tmux pane runs once, then counts down and dies. Pane is dead. Even the tmux monitor pane. I don't even know where to start debugging this. Everything was running fine. Then yesterday there was a minor update to mariahdb from version 10.0.29 to 10.0.30. After that was when tmux stopped working correctly. And before you ask, I shut down tmux before updating mariahdb. I don't even know if the update has anything to do with it. There is another thing. When I run php.stop.php to stop tmux when it is running, it seems to have no effect. Everything keeps running until it counts down and then the panes die. This too started at the same time. Does anyone have any suggestions as to where to start with this?

**Comment by bobtongue** [comment]
Also I noticed just now, that I have Update TV and Theater Schedules disabled in the tmux settings and yet the pane is still trying to go out and update the schedules. I get an unable to fetch from rotten tomatoes. Verify your API key error.

**Comment by niel** [comment]
What branch?

**Comment by bobtongue** [comment]
0.x - I checked all the logs and don't find anything funny. I tried rebuilding tmux and that didn't help
repaired tables just to be sure, and rebooted. Still no joy.
I am kind of stuck. I am using tmux-1.9a. I am on the latest version of zed. Made sure before I posted here.
If you have any ideas, I would be glad to hear them.
I just can't figure why it would stop spawning out of the blue.
I even reverted the last system updates I did just to be sure.

**Comment by bobtongue** [comment]
Did a restore of the OS from 2 days ago. Still not luck. Tried upgrading to tmux 2.0. Runs fine, but still won't respawn
I have officially run out of ideas

**Comment by niel** [comment]
Without error reports I'm not able to guess at much.
Check your tmux settings in site settings to be sure nothing got corrupted or changed by accident.

**Comment by bobtongue** [comment]
Well after pulling my hair out all day, I threw up a hail mary and dropped the db and restored from a 2 day old backup. It seems to have fixed the problem. Still doesn't tell me what was wrong but it is fixed just the same.
Thank God for daily backups
