### ISSUE TITLE
ircscraper errors after update

### ISSUE THREAD

**Issue by ERR1R** [nZEDb/nZEDb#2423]
###Expected behaviour

working pre release data in database

###Actual behaviour
Spits out errors when there is a release on ircscraper..
`Error: SQLSTATE[3D000]: Invalid catalog name: 1046 no database selected`

When i restart tmux, ircscraper its working for 30 minutes but after a while it spits out the error above..

###Steps to reproduce the behaviour
Update to ubuntu 16.04 with mysql 5.7

**Comment by ERR1R** [comment]
ps. Can i fill releases that i missed? I missed about 3 days.

**Comment by niel** [comment]
Steps to reproduce are a joke. I'm on Ubuntu 16.04 derivative, as are many other users, and they're not seeing this problem.
Please be more specific or we can't help.
As for missed days. If they're because of downtime, they'll automatically be grabbed when your indexer is started again. If some arbitrary date in the past, look at backfilling.

**Comment by ERR1R** [comment]
Hi Niel,

I know its minimal, but this happened after i updated to 16.04 and mysql 5.7.  What more can i say... for the update it was working fine. Ubuntu 14.04, mysql 5.6 nginx and php5-fpm. Also received another weird error like this
`SQLSTATE[42000]: .... incompatible with sql_mode=only_full_group_by` but i fixed that with `sql_mode = ""`
in my.cnf could that be of any help?

btw, i also disabled apparmor.

**Comment by niel** [comment]
My guess, is that you were using MySQL 5.6 before. 5.7 has changed several default behaviours, so you should read its update instructions and check which defaults are screwing your config up.
Incidentally we strongly recommend MariaDB for this reason, as it is the easiest to get working for beginners (non-DBAs).
sql_mode='' is probably overkill, might want to check the forums and search closed issues for how others "fixed" MySQL 5.7

**Comment by ERR1R** [comment]
ok, it seems i fixed it... I replaced the config with the one here on the repo. My guess is after i updated nzedb i placed the old config in the new directory..

This can be closed now.

**Comment by sinfuljosh** [comment]
http://stackoverflow.com/questions/34115174/error-related-to-only-full-group-by-when-executing-a-query-in-mysql 

Im curious as to the query that was run leading up to the error, from looking at the link above it mentioned the changes to with mysql and it could mean an adjustment to the query to ensure more uniformity also.

**Comment by Wally73** [comment]
we're testing a dev branch to get rid of errors out of scrape. when testing
are successful it will be merged in normal dev and later in 0.x

**Comment by niel** [comment]
As @Wally73 says, we're testing a possible fix for this. So far it looks promising and if all goes well it will be merged into dev on Monday for wider testing. If that goes well, i.e. without causing more errors, it will be merged into stable in the normal schedule (first Monday of new month).
