### ISSUE TITLE
PreDB Daily Batch Import

### ISSUE THREAD

**Issue by Boinkers** [nZEDb/nZEDb#2425]
PreDB daily batch import fails after the PreDB GitHub change, sure you guys are aware of it.

**Comment by niel** [comment]
Which branch are you on. A fixed script is already in dev branch and can be downloaded from here: https://raw.githubusercontent.com/nZEDb/nZEDb/dev/cli/data/predb_import_daily_batch.php
If that doesn't work, please let me know (preferably on IRC)
