### ISSUE TITLE
Giantbomb notice

### ISSUE THREAD

**Issue by ghost** [nZEDb/nZEDb#2427]
Release v0.7.1.0 (also on older version)

running tmux php_errors populate with

PHP Notice:  Trying to get property of non-object in nzedb/app/libraries/giantbomb/giantbomb/GiantBomb/GiantBomb.php on line 380

**Comment by DariusIII** [comment]
Can you provide full stack trace?

**Comment by ghost** [comment]
Thats all I get in full debug, it's coming from misc/testing/PostProcess/getGameCovers.php

**Comment by ghost** [comment]
hum, it maybe every time I get a "not found" I get the error, if I re-run the script it retries the same releases and produces the same notice

**Comment by ghost** [comment]
duplicate #2442
