### ISSUE TITLE
unable to recategorize all releases by running misc/update/update_releases.php 6 true

### ISSUE THREAD

**Issue by ghost** [nZEDb/nZEDb#2432]
When adding a new Category Regex we can no longer force it to run through all our releases.

$php misc/update/update_releases.php 6 true

Error: Non-threaded update_releases.php is not supported anymore.You must use /misc/update/nix/multiprocessing/releases.php

**Comment by DariusIII** [comment]
As far as i know, you should run recategorize.php

**Comment by ghost** [comment]
Yep that does it. Webpage admin/category_regexes-list.php has the old method
