### ISSUE TITLE
Releases disabled by date

### ISSUE THREAD

**Issue by PsychoSid** [nZEDb/nZEDb#2433]
Hello,

Just updated:-
nzedb@nzedbbox:~$ ./zed version all
Looking up Git tag version(s)
Hash: d6ffa3f4f1e5b6ef06b4b29c3054657c1d391bc3
XML version: 0.7.1.1
Git version: 0.7.0.0
Looking up SQL patch version(s)
XML version: 471
 DB version: 471

Now I am not getting any releases created. Error message on the tmux monitor panel shows:-
\nreleasesnhave been disabled/terminated by Releases date  +%Y-%m-%d %T

Have I missed some config item somewhere in this new update ?

Thanks

**Comment by niel** [comment]
Check that tmux settings actually has update releases enabled. A couple people have reported that it was disabled for some unknown reason.

**Comment by PsychoSid** [comment]
Yeah that was it. Weird, certainly didn't do that.

Thanks for the tip
