### ISSUE TITLE
"something" breaks with the cli on the shell

### ISSUE THREAD

**Issue by OliverLeitner** [nZEDb/nZEDb#2434]
cleanly running without "destroying" the tmux layout and without leaving "bad" files on the drive.

what happens:

http://imgur.com/1LUgx6q
http://imgur.com/NlMCgVL

to reproduce this: start a terminal in your x session (looks like that with any terminal emulator..., xterm, i3 terminal, gnome terminal, xfce terminal...), connect over to the server via ssh, start the tmux processing and let it run for 'bout 12 hours...

this has been happening now for about 6 months.

**Comment by niel** [comment]
Does disconnecting from the server/tmux session and reconnecting fix the problem?

**Comment by OliverLeitner** [comment]
nope...

i am currently trying to set utf-8 for mbstring internal encoding, also removed some ssh_config options like the setenv thing..., also moved the locale vars LANG and LANGUAGE from xx_....-utf8 to en_US...-utf8. ill update if that fixes stuff...

**Comment by OliverLeitner** [comment]
nope... weve got a problem, houston

ps: it gets even worse, if im using powerline

**Comment by sinfuljosh** [comment]
You sound like you are on the right track. Mostg likely its the same issue described here. 

http://unix.stackexchange.com/questions/320386/seeing-strange-question-marks-in-bash-shell

**Comment by kaibosh** [comment]
Try changing the tmux.conf file to this below and see if it helps.

```
#set 256 color display
set -g default-terminal "screen-256color"
#set -g default-terminal "xterm-256color"
```
