### ISSUE TITLE
Joins without indexes and overall high CPU usage

### ISSUE THREAD

**Issue by ghost** [nZEDb/nZEDb#2437]
I've been having issues with high MySQL CPU usage lately. My avg. CPU usage tripled from 25% 10 months ago to 80+% today.

I have enabled the slow query log and logged joins without indexes. The log file filled at breakneck speed with these two queries:

```sql
SELECT COUNT(z.id) AS count FROM (SELECT r.id FROM releases r
			LEFT OUTER JOIN videos v ON r.videos_id = v.id AND v.type = 0
			LEFT OUTER JOIN tv_info tvi ON v.id = tvi.videos_id
			LEFT OUTER JOIN tv_episodes tve ON r.tv_episodes_id = tve.id
			LEFT JOIN categories c ON c.id = r.categories_id
			LEFT JOIN categories cp ON cp.id = c.parentid
			LEFT JOIN groups ON groups.id = r.groups_id
			LEFT OUTER JOIN video_data re ON re.releases_id = r.id
			LEFT OUTER JOIN release_nfos rn ON rn.releases_id = r.id

			WHERE r.categories_id BETWEEN 5000 AND 5999
			AND r.nzbstatus = 1
			AND r.passwordstatus <= 0
			AND r.tv_episodes_id IN (485589)   AND r.categories_id IN (5010, 5020, 5030, 5040, 5045, 5060, 5070, 5080, 5999, 5070, 5080, 5020, 5040, 5999, 5030, 5060, 5045, 5010)  AND r.postdate > NOW() - INTERVAL 2500 DAY  LIMIT 125000) z;


SELECT users.*, user_roles.apirequests, user_roles.downloadrequests, NOW() AS now
				FROM users
				INNER JOIN user_roles ON user_roles.id = users.role
				WHERE LOWER(users.rsstoken) =
				LOWER('775e155c780ed5af9119f797f814c714') LIMIT 1;
```

When doing `SHOW FULL PROCESSLIST` I can see a LOT of processes of the last query. It's a simple query but it takes 700ms+ to 1,5s. I guess it should easily complete within 100-150ms.

The first query I see a lot too.

MySQL Tuner shows: `[!!] Joins performed without indexes: 968652` and `[!!] Temporary tables created on disk: 59% (29M on disk / 49M total)`

Shouldn't there be indexes for these queries?

**Comment by ghost** [comment]
Okay so I did: `CREATE INDEX ix_rssrole ON users (rsstoken, role);` and it did not use the index. Turns out I had to remove the MySQL LOWER() function from this php function: https://github.com/nZEDb/nZEDb/blob/b9b4c606ac2e01eadc079f7ea63c583756689471/nzedb/Users.php#L533

Query takes about 25ms now. I guess LOWER() is not necessary? I believe @DariusIII told me so a while back.

**My load average dropped from 26-36 to 6 by just adding this index and removing LOWER(). Wow.** This is on a dual socket 16 core machine. My site feels as fast as it was a few months before again :D

**Comment by Fossil01** [comment]
My load average dropped from 26-36 to 6 by just adding this index and removing LOWER(). Wow.

This is on a dual socket 16 core machine.

**Comment by niel** [comment]
Did you remove both LOWER() functions? If not which one did you remove. Only time LOWER() is not needed is if the contents are already lower-cased, if not the queries will fail on those entries.
EDIT: Nevermind, I saw the PR :-)

**Comment by ghost** [comment]
Yes both. API keys are always lowercase so only if a user manually edits or types the key it fails.

My load literally went from 26+ back to <5 just by this fix.

**Comment by ghost** [comment]
Nice find, I would not have thought LOWER would have such an impact. Anyone know why it stops the index being used?

**Comment by ghost** [comment]
@slug1982 both adding the new index plus the remval of lower did the trick for me.
