### ISSUE TITLE
Split Database Tables

### ISSUE THREAD

**Issue by egyptianbman** [nZEDb/nZEDb#2443]
I don't know what happened but at some point, something split or duplicated the following tables:
- binaries
- collections
- missed_parts
- parts

What I have now is:

![image](https://cloud.githubusercontent.com/assets/323600/25516168/83d903a0-2bae-11e7-9c59-e0166c9651a5.png)

As you can see, the duplicate tables have data in them. The data seems to be unique -- searching for an id of one of the entries in `binaries_10` in `binaries` yields no results. Does anyone know how this could have happened? Was it intentional? Should I write a script to migrate the data back to the non-numeric tables? I currently have 326 tables.

**Comment by DariusIII** [comment]
These are not duplicate tables, this is what you get when, now mandatory, table per group is used. Every active group has it's own set of parts, binaries, collections and missed_parts tables. This is not issue, this is by design.

**Comment by egyptianbman** [comment]
Happy to hear nothing's wrong. Thank you for the info.
