### ISSUE TITLE
Need help with new nZEDb install on ubuntu (using nginx) with strange URL behavior.

### ISSUE THREAD

**Issue by ferfey** [nZEDb/nZEDb#2454]
I installed nZEDb on my Ubuntu home intranet server with the intent of having my own usenet indexer. I followed[ these instructions](http://nzedb.readthedocs.io/en/master/ubuntu.html). I was able to get the setup to work (step 1, step 2 etc) and loaded the admin site. 
[This is what the site looks like](http://imgur.com/a/kXqXn) and here are the urls after clicking on a few links. I assume that something is going wrong with the rewrite rules. The error.log is just showing a lot of "file not found" errors.

Here's the tail of the /var/log/nginx/error.log
    
> 2017/05/15 21:20:53 [error] 1094#1094: *29 open() "/var/www/nZEDb/www/admin/index.php/themes/shared/libs/tinymce-builded/js/tinymce/tinymce.min.js" failed (20: Not a directory), client: 192.168.1.44, server: 192.168.1.4, request: "GET /admin/index.php/themes/shared/libs/tinymce-builded/js/tinymce/tinymce.min.js HTTP/1.1", host: "192.168.1.4:90", referrer: "http://192.168.1.4:90/admin/index.php/admin/site-edit.php"
>     

This is what the URLs look like
> http://192.168.1.4:90/admin/index.php/admin/category-list.php?action=add
> http://192.168.1.4:90/admin/index.php/admin/category_regexes-edit.php?action=add
> 
Here's a [screen shot of the home page
](http://imgur.com/a/zk6ag)

Here's the permissions on /var/www/nZEDb/www/
> drwxrwsr-x  2 www-data www-data 4096 May 15 01:27 admin
> -rwxrwxr-x  1 www-data www-data  377 May 15 01:27 autoloader.php
> drwxrwsr-x 15 www-data www-data 4096 May 15 01:27 covers
> -rwxrwxr-x  1 www-data www-data  318 May 15 01:27 favicon.ico
> -rwxrwxr-x  1 www-data www-data 1895 May 15 01:27 index.php
> drwxrwsr-x  4 www-data www-data 4096 May 15 18:25 install
> drwxrwsr-x  2 www-data www-data 4096 May 15 01:27 pages
> drwxrwsr-x  2 www-data www-data 4096 May 15 01:27 plugins
> -rwxrwxr-x  1 www-data www-data   26 May 15 01:27 robots.txt
> -rwxrwxr-x  1 www-data www-data 1975 May 15 01:27 smarty.php
> drwxrwsr-x 11 www-data www-data 4096 May 15 01:27 themes

I ran the permissions check script in ./cli and after adding a few missing directories in ./resources (./tmp, ./tmp/unrar, ./tmp/yEnc, etc) it reported no errors for user www-data

**Comment by DariusIII** [comment]
Have you ran 

`composer install`

at all?

**Comment by Wally73** [comment]
he admitted on irc he did it as root (so no wonder it doesn't work :p )

**Comment by ferfey** [comment]
yes, ran composer install (put my self in the www-data group).
No change to the behavior of the website.

**Comment by ferfey** [comment]
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files

**Comment by DariusIII** [comment]
Please enable all the debugging options in settings.php. If you don't have that file run:
 
```
cd configuration/
cp settings.example.php settings.php
```

After that check error logs (php_error_web.log and php_error_cli.log, or php_error.log).
Also check nginx error log located in /var/log/nginx/error.log for hints on problems with your site.

**Comment by niel** [comment]
I'd suggest you start from scratch and actually follow the directions. Don't use root! If you want support, please follow instructions as given. If you deviate from them, know what the consequences are and expect to be on your own.

**Comment by ferfey** [comment]
Just in case I messed something up, I started from here:
"C. Grab a fresh copy of nZEDb and set the correct permissions."

The script failed here

> Setting cache directory permissions for you...
> [sudo] password for jeff:
> Sorry, try again.
> [sudo] password for jeff:
> chmod: changing permissions of './resources/smarty/templates_c/7d56842a144463d4b442f64aa035caf6ea7c6e91_0.file.index.tpl.php': Operation not permitted
> chmod: changing permissions of './resources/smarty/templates_c/d5d6ca41c15909571152ac5c09cbeceab61eca88_0.file.step2.tpl.php': Operation not permitted
> chmod: changing permissions of './resources/smarty/templates_c/03288c51426155445d78d55d69a76264ae49e475_0.file.installpage.tpl.php': Operation not permitted
> chmod: changing permissions of './resources/smarty/templates_c/575f871bf87fb80b5ef1b6a516331e3de34c7458_0.file.adminmenu.tpl.php': Operation not permitted
> chmod: changing permissions of './resources/smarty/templates_c/25037f67156f77e3913a219fd6a536d6186aa759_0.file.step1.tpl.php': Operation not permitted
> chmod: changing permissions of './resources/smarty/templates_c/42ec8ead14609f147b6a6dfd36e88250b619b2f9_0.file.step5.tpl.php': Operation not permitted
> chmod: changing permissions of './resources/smarty/templates_c/16692131f439f661dcc74ad951cd661e275c6ac1_0.file.step6.tpl.php': Operation not permitted
> chmod: changing permissions of './resources/smarty/templates_c/39cbc1c6d310d0b5d87118dbf101c868da76e7f3_0.file.step3.tpl.php': Operation not permitted
> chmod: changing permissions of './resources/smarty/templates_c/29d3953667332bc36f1b360ab25e298d38f24b93_0.file.step7.tpl.php': Operation not permitted
> chmod: changing permissions of './resources/smarty/templates_c/740c2a78bd3778dc42082d3d82ff0843ca9aa8be_0.file.baseadminpage.tpl.php': Operation not permitted
> chmod: changing permissions of './resources/smarty/templates_c/0934757954fb588830a355ed27e49020e693e1b6_0.file.step4.tpl.php': Operation not permitted
> chmod: changing permissions of './configuration/install.lock': Operation not permitted
> chmod: changing permissions of './configuration/config.php': Operation not permitted
> chmod: changing permissions of './www/admin/php-errors.log': Operation not permitted
> chmod: changing permissions of './www/install/unrar': Operation not permitted
> chmod: cannot read directory './www/install/unrar': Permission denied
> chmod: changing permissions of 'configuration/install.lock': Operation not permitted
> chmod: changing permissions of 'configuration/config.php': Operation not permitted
> chmod: changing permissions of 'resources/smarty/templates_c/7d56842a144463d4b442f64aa035caf6ea7c6e91_0.file.index.tpl.php': Operation not permitted
> chmod: changing permissions of 'resources/smarty/templates_c/d5d6ca41c15909571152ac5c09cbeceab61eca88_0.file.step2.tpl.php': Operation not permitted
> chmod: changing permissions of 'resources/smarty/templates_c/03288c51426155445d78d55d69a76264ae49e475_0.file.installpage.tpl.php': Operation not permitted
> chmod: changing permissions of 'resources/smarty/templates_c/575f871bf87fb80b5ef1b6a516331e3de34c7458_0.file.adminmenu.tpl.php': Operation not permitted
> chmod: changing permissions of 'resources/smarty/templates_c/25037f67156f77e3913a219fd6a536d6186aa759_0.file.step1.tpl.php': Operation not permitted
> chmod: changing permissions of 'resources/smarty/templates_c/42ec8ead14609f147b6a6dfd36e88250b619b2f9_0.file.step5.tpl.php': Operation not permitted
> chmod: changing permissions of 'resources/smarty/templates_c/16692131f439f661dcc74ad951cd661e275c6ac1_0.file.step6.tpl.php': Operation not permitted
> chmod: changing permissions of 'resources/smarty/templates_c/39cbc1c6d310d0b5d87118dbf101c868da76e7f3_0.file.step3.tpl.php': Operation not permitted
> chmod: changing permissions of 'resources/smarty/templates_c/29d3953667332bc36f1b360ab25e298d38f24b93_0.file.step7.tpl.php': Operation not permitted
> chmod: changing permissions of 'resources/smarty/templates_c/740c2a78bd3778dc42082d3d82ff0843ca9aa8be_0.file.baseadminpage.tpl.php': Operation not permitted
> chmod: changing permissions of 'resources/smarty/templates_c/0934757954fb588830a355ed27e49020e693e1b6_0.file.step4.tpl.php': Operation not permitted
> chmod: changing permissions of 'www/admin/php-errors.log': Operation not permitted
> chmod: changing permissions of 'www/install/unrar': Operation not permitted
> chmod: cannot read directory 'www/install/unrar': Permission denied

So I looked at the script and ran each command to see which wasn't working. Turns out a few of them need to be run as sudo (I copied my terminal output so you could see which had to be run as sudo):

> jeff@mythbuntu:/var/www/nZEDb$ sudo chown -R www-data:www-data /var/lib/php/sessions/
> jeff@mythbuntu:/var/www/nZEDb$ chmod 755 ./
> jeff@mythbuntu:/var/www/nZEDb$ chmod -R g+s ./
> chmod: changing permissions of './resources/smarty/templates_c/7d56842a144463d4b442f64aa035caf6ea7c6e91_0.file.index.tpl.php': Operation not permitted
> chmod: changing permissions of './resources/smarty/templates_c/d5d6ca41c15909571152ac5c09cbeceab61eca88_0.file.step2.tpl.php': Operation not permitted
> chmod: changing permissions of './resources/smarty/templates_c/03288c51426155445d78d55d69a76264ae49e475_0.file.installpage.tpl.php': Operation not permitted
> chmod: changing permissions of './resources/smarty/templates_c/575f871bf87fb80b5ef1b6a516331e3de34c7458_0.file.adminmenu.tpl.php': Operation not permitted
> chmod: changing permissions of './resources/smarty/templates_c/25037f67156f77e3913a219fd6a536d6186aa759_0.file.step1.tpl.php': Operation not permitted
> chmod: changing permissions of './resources/smarty/templates_c/42ec8ead14609f147b6a6dfd36e88250b619b2f9_0.file.step5.tpl.php': Operation not permitted
> chmod: changing permissions of './resources/smarty/templates_c/16692131f439f661dcc74ad951cd661e275c6ac1_0.file.step6.tpl.php': Operation not permitted
> chmod: changing permissions of './resources/smarty/templates_c/39cbc1c6d310d0b5d87118dbf101c868da76e7f3_0.file.step3.tpl.php': Operation not permitted
> chmod: changing permissions of './resources/smarty/templates_c/29d3953667332bc36f1b360ab25e298d38f24b93_0.file.step7.tpl.php': Operation not permitted
> chmod: changing permissions of './resources/smarty/templates_c/740c2a78bd3778dc42082d3d82ff0843ca9aa8be_0.file.baseadminpage.tpl.php': Operation not permitted
> chmod: changing permissions of './resources/smarty/templates_c/0934757954fb588830a355ed27e49020e693e1b6_0.file.step4.tpl.php': Operation not permitted
> chmod: changing permissions of './configuration/install.lock': Operation not permitted
> chmod: changing permissions of './configuration/config.php': Operation not permitted
> chmod: changing permissions of './www/admin/php-errors.log': Operation not permitted
> chmod: changing permissions of './www/install/unrar': Operation not permitted
> chmod: cannot read directory './www/install/unrar': Permission denied
> jeff@mythbuntu:/var/www/nZEDb$ sudo chmod -R g+s ./
> jeff@mythbuntu:/var/www/nZEDb$ chmod -R 755 app/libraries
> jeff@mythbuntu:/var/www/nZEDb$ chmod -R 775 app/resources
> jeff@mythbuntu:/var/www/nZEDb$ chmod -R 775 configuration
> chmod: changing permissions of 'configuration/install.lock': Operation not permitted
> chmod: changing permissions of 'configuration/config.php': Operation not permitted
> jeff@mythbuntu:/var/www/nZEDb$ sudo chmod -R 775 configuration
> jeff@mythbuntu:/var/www/nZEDb$ chmod -R 775 libraries
> jeff@mythbuntu:/var/www/nZEDb$ chmod -R 775 resources
> chmod: changing permissions of 'resources/smarty/templates_c/7d56842a144463d4b442f64aa035caf6ea7c6e91_0.file.index.tpl.php': Operation not permitted
> chmod: changing permissions of 'resources/smarty/templates_c/d5d6ca41c15909571152ac5c09cbeceab61eca88_0.file.step2.tpl.php': Operation not permitted
> chmod: changing permissions of 'resources/smarty/templates_c/03288c51426155445d78d55d69a76264ae49e475_0.file.installpage.tpl.php': Operation not permitted
> chmod: changing permissions of 'resources/smarty/templates_c/575f871bf87fb80b5ef1b6a516331e3de34c7458_0.file.adminmenu.tpl.php': Operation not permitted
> chmod: changing permissions of 'resources/smarty/templates_c/25037f67156f77e3913a219fd6a536d6186aa759_0.file.step1.tpl.php': Operation not permitted
> chmod: changing permissions of 'resources/smarty/templates_c/42ec8ead14609f147b6a6dfd36e88250b619b2f9_0.file.step5.tpl.php': Operation not permitted
> chmod: changing permissions of 'resources/smarty/templates_c/16692131f439f661dcc74ad951cd661e275c6ac1_0.file.step6.tpl.php': Operation not permitted
> chmod: changing permissions of 'resources/smarty/templates_c/39cbc1c6d310d0b5d87118dbf101c868da76e7f3_0.file.step3.tpl.php': Operation not permitted
> chmod: changing permissions of 'resources/smarty/templates_c/29d3953667332bc36f1b360ab25e298d38f24b93_0.file.step7.tpl.php': Operation not permitted
> chmod: changing permissions of 'resources/smarty/templates_c/740c2a78bd3778dc42082d3d82ff0843ca9aa8be_0.file.baseadminpage.tpl.php': Operation not permitted
> chmod: changing permissions of 'resources/smarty/templates_c/0934757954fb588830a355ed27e49020e693e1b6_0.file.step4.tpl.php': Operation not permitted
> jeff@mythbuntu:/var/www/nZEDb$ sudo chmod -R 775 resources
> jeff@mythbuntu:/var/www/nZEDb$ chmod -R 775 www
> chmod: changing permissions of 'www/admin/php-errors.log': Operation not permitted
> chmod: changing permissions of 'www/install/unrar': Operation not permitted
> chmod: cannot read directory 'www/install/unrar': Permission denied
> jeff@mythbuntu:/var/www/nZEDb$ sudo chmod -R 775 www
> jeff@mythbuntu:/var/www/nZEDb$ chmod +x ./zed
> jeff@mythbuntu:/var/www/nZEDb$ alias zed='./zed'
> 

After that, I went back through the /install and passed all steps, loaded /admin and saw the same results as last night.

Here's the log from nginx

> 2017/05/16 21:20:45 [error] 1074#1074: *75 open() "/var/www/nZEDb/www/admin/index.php/themes/shared/js/jquery.multiselect.js" failed (20: Not a directory), client: 192.168.1.44, server: 192.168.1.4, request: "GET /admin/index.php/themes/shared/js/jquery.multiselect.js HTTP/1.1", host: "192.168.1.4:90", referrer: "http://192.168.1.4:90/admin/"
> 2017/05/16 21:20:45 [error] 1076#1076: *71 open() "/var/www/nZEDb/www/admin/index.php/themes/shared/libs/tinymce-builded/js/tinymce/tinymce.min.js" failed (20: Not a directory), client: 192.168.1.44, server: 192.168.1.4, request: "GET /admin/index.php/themes/shared/libs/tinymce-builded/js/tinymce/tinymce.min.js HTTP/1.1", host: "192.168.1.4:90", referrer: "http://192.168.1.4:90/admin/"
> 2017/05/16 21:20:47 [error] 1076#1076: *71 open() "/var/www/nZEDb/www/admin/index.php/themes/shared/js/sorttable.js" failed (20: Not a directory), client: 192.168.1.44, server: 192.168.1.4, request: "GET /admin/index.php/themes/shared/js/sorttable.js HTTP/1.1", host: "192.168.1.4:90", referrer: "http://192.168.1.4:90/admin/"
> 2017/05/16 21:20:47 [error] 1076#1076: *71 open() "/var/www/nZEDb/www/admin/index.php/themes/shared/js/utils-admin.js" failed (20: Not a directory), client: 192.168.1.44, server: 192.168.1.4, request: "GET /admin/index.php/themes/shared/js/utils-admin.js HTTP/1.1", host: "192.168.1.4:90", referrer: "http://192.168.1.4:90/admin/"
> 2017/05/16 21:20:47 [error] 1076#1076: *71 open() "/var/www/nZEDb/www/admin/index.php/themes/shared/js/jquery.multifile.js" failed (20: Not a directory), client: 192.168.1.44, server: 192.168.1.4, request: "GET /admin/index.php/themes/shared/js/jquery.multifile.js HTTP/1.1", host: "192.168.1.4:90", referrer: "http://192.168.1.4:90/admin/"
> 2017/05/16 21:20:47 [error] 1076#1076: *71 open() "/var/www/nZEDb/www/admin/index.php/themes/shared/js/jquery.multiselect.js" failed (20: Not a directory), client: 192.168.1.44, server: 192.168.1.4, request: "GET /admin/index.php/themes/shared/js/jquery.multiselect.js HTTP/1.1", host: "192.168.1.4:90", referrer: "http://192.168.1.4:90/admin/"
> 2017/05/16 21:20:47 [error] 1076#1076: *71 open() "/var/www/nZEDb/www/admin/index.php/themes/shared/libs/tinymce-builded/js/tinymce/tinymce.min.js" failed (20: Not a directory), client: 192.168.1.44, server: 192.168.1.4, request: "GET /admin/index.php/themes/shared/libs/tinymce-builded/js/tinymce/tinymce.min.js HTTP/1.1", host: "192.168.1.4:90", referrer: "http://192.168.1.4:90/admin/"
> 2017/05/16 21:21:01 [error] 1076#1076: *71 "/var/www/nZEDb/www/admin/index.php/index.html" is not found (20: Not a directory), client: 192.168.1.44, server: 192.168.1.4, request: "GET /admin/index.php/ HTTP/1.1", host: "192.168.1.4:90", referrer: "http://192.168.1.4:90/admin/"

I'm unable to find the the php log files (tried sudo find / -iname php_error_web.log -print).
Where should I look for these?

**Comment by DariusIII** [comment]
You have permission issues, start completely fresh and don't use root for any operation. 
Please use this guide: 

https://github.com/nZEDb/nZEDb_Misc/blob/master/Guides/Installation/Ubuntu/Guide.md

**Comment by ferfey** [comment]
Followed that guide step by step. No errors.
Same result.

Could it be the way PHP is building the links? These URLs seem odd (admin/index.php/admin)?:
http://192.168.1.4:90/admin/index.php/admin/category-list.php?action=add

**Comment by DariusIII** [comment]
No, PHP is not building anything. Your rewrite rules seem to be off. I can't help as i never used nginx.

**Comment by ferfey** [comment]
ok, I'll try to use Apache

**Comment by niel** [comment]
BTW. Issues is the place to report bugs, not for tech support. Please use the IRC channel or forums for support.
