### ISSUE TITLE
IRC Scraper Crashing and PreDB Import issues.

### ISSUE THREAD

**Issue by scottia** [nZEDb/nZEDb#2457]
IRCScraper intermittently crashes with the following and stops scraping.  Currently using **DEV** , updated as of 05,26.

Also to report daily importing of Predb dumps stops with 32 files left to import in my case (I am probably the only one).  Nothing older that 32 days (33 now) will import.  I have tried all the tricks including @Wally73 assistance on IRC.  I am stuck and baffled by it.

[27-May-2017 02:18:59 America/Chicago] PHP Fatal error:  Uncaught Error: Call to a member function log() on null in /var/www/nZEDb/nzedb/IRCScraper.php:295
Stack trace:
#0 /var/www/nZEDb/nzedb/IRCScraper.php(274): nzedb\IRCScraper->_checkForDupe()
#1 /var/www/nZEDb/nzedb/IRCClient.php(432): nzedb\IRCScraper->processChannelMessages()
#2 /var/www/nZEDb/nzedb/IRCScraper.php(193): nzedb\IRCClient->readIncoming()
#3 /var/www/nZEDb/nzedb/IRCScraper.php(136): nzedb\IRCScraper->_startScraping()
#4 /var/www/nZEDb/misc/IRCScraper/scrape.php(50): nzedb\IRCScraper->__construct(false, false)
#5 {main}
  thrown in /var/www/nZEDb/nzedb/IRCScraper.php on line 295

**Comment by scottia** [comment]
All PreDb imports show skipping.  This is where my import stops (the last entry with all previous skipped based on progress.txt w/33 files to go.
Skipping dump 1492947640, as your minimum unix time argument is 1492947641

I converted Epoch time of 1492947640 here.  You can see the minimum Unix Tim is 04.23

![image](https://cloud.githubusercontent.com/assets/5298748/26521762/1dfc6530-42b6-11e7-85d1-ff00cf05cb83.png)

It makes no difference if I remove progress.txt or change it.  I tried re-importing all dumps, same issue.  I thought I might be able to export/import predb.  Same issue.  As a final attempt, I truncated the table and ran "php /var/www/nZEDb/cli/data/predb_import_daily_batch.php 0 local true".  Result was all files skipped and NO records added from the dumps.  Left with an empty table I re-imported my previous export and re-ran with "0 local true".  Same issue and Unix Time as before, all files skipped and 33 files left to import.

**Comment by niel** [comment]
A few weeks ago we had to change how dailies are downloaded because we hit the file limit for directories. Sounds like the update hasn't been applied properly.

**Comment by scottia** [comment]
How do I tell?  Everything updated and patched correctly without issue.  Or are you saying the latest update is missing files from the update file limit for directories?

**Comment by niel** [comment]
Talk to me in IRC.

**Comment by Wally73** [comment]
check if the import_daily script is right 
https://github.com/nZEDb/nZEDb/blob/0.x/cli/data/predb_import_daily_batch.php

**Comment by scottia** [comment]
Here is the error from predb_import_daily_batch.php I wasn't seeing from before.  I suspect this as he cause.

[28-May-2017 06:56:56 America/Chicago] PHP Fatal error:  Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'j\xB1\xB3\xC5\xE1\xF80U\x86\x19\x92\xEBg\x1Fj\x0D' for key 'PRIMARY' in /var/www/nZEDb/nzedb/db/PreDb.php:122
Stack trace:
#0 /var/www/nZEDb/nzedb/db/PreDb.php(122): PDOStatement->execute()
#1 /var/www/nZEDb/cli/data/predb_import_daily_batch.php(205): nzedb\db\PreDb->executeInsert()
#2 {main}
  thrown in /var/www/nZEDb/nzedb/db/PreDb.php on line 122

**Comment by scottia** [comment]
Thanks @Wally73 I have.  Even git checkout dev to ensure its the correct version.

**Comment by niel** [comment]
Is this still a problem?

**Comment by scottia** [comment]
Yes.  Both IRCScraper error and predb_import_daily_batch.php still occurring.

**Comment by scottia** [comment]
I think I know whats up.  Am no expert but if reading the predb error correctly, it appears that the value from the error "j\xB1\xB3\xC5\xE1\xF80U\x86\x19\x92\xEBg\x1Fj\x0D" is attempting to be inserted into PRIMARY key from predb.  PRIMARY key is only 11 integers, so it fails.  i checked my predb against the schema and its correct, so I don't know where the record or its value is coming from but that appears to be it.

**Comment by scottia** [comment]
I went looking for binary files names in nZEDbPre_Dumps and found 04.23 was removed and re-added.  This is the same date I am stuck on.  Am wondering if i previously imported the file prior to deletion?

![image](https://cloud.githubusercontent.com/assets/5298748/26556915/2219318a-4463-11e7-8c6e-a2f474e50fc1.png)

**Comment by Wally73** [comment]
that is on my fork but still it shouldn't matter (the deleted one) 

to import the dailies from my fork you need 
https://gist.github.com/Wally73/98986708c3ea03a56f6b012b06fdd6cf
(dailies twice a day)

**Comment by scottia** [comment]
Sorry about that.  Was about the remove comment...  Been allover trying to figure anything out.

Questions @Wally73 ?  How do you find or create these strings from progress.txt based on the dump file?
YToxOntzOjQ6Imxhc3QiO2k6MTQ5Mjk0NzY0MTt9

**Comment by Wally73** [comment]
i have no idea how that string is made up sorry

**Comment by scottia** [comment]
do you know where to find it?  You sent me one in IRC, so I wanted to try others.

**Comment by scottia** [comment]
I was able to resolve on my own by dropping old predb and re-creating from Schema and importing older data into new table.  Daily dumps are all successful and IRCScraper errors are gone.
