### ISSUE TITLE
category empty in predb table (via scraper, records imported via dumps are ok)

### ISSUE THREAD

**Issue by sspilleman** [nZEDb/nZEDb#2459]
###Expected behaviour

Records in PreDB table that are created by the scraper should be "the same" to records added via the daily dump import

###Actual behaviour

Key information (like category is missing)

###Steps to reproduce the behaviour

Just fire up "screen php ./misc/IRCScraper/scrape.php true false true" and see how new records are created

**Comment by Wally73** [comment]
fixed in dev 
https://github.com/nZEDb/nZEDb/commit/d0fbf790042baeb1e6a05303d95de64488ed6ee2

**Comment by sspilleman** [comment]
Thanks! Can I "safely" just grab this changed file? Or would there be any regression?

**Comment by Wally73** [comment]
no not safely as there is changed a lot in dev so better wait till its merged into 0.x

**Comment by sspilleman** [comment]
Ok... So for my understanding, what is the impact. From my understanding:
1) It obviously means that you have to run the daily import
2) It could mean that stuff is only matched with a max delay of 24 hours
Anything else? Or does it mean that recent stuff won't be properly categorized at all?

**Comment by Wally73** [comment]
recent stuff is renamed fine (even without the missing category) if you run ircscraper
running the daily import doesn't hurt (duplicates aren't inserted)
