### ISSUE TITLE
./zed update nzedb broken

### ISSUE THREAD

**Issue by ghost** [nZEDb/nZEDb#2462]
looks like it no longer updates db or classes

**Comment by OliverLeitner** [comment]
i can confirm this.

**Comment by OliverLeitner** [comment]
ok, found the problem, read ReleaseNotes (not changelog this time...) and be sure to apply the mysql timezone update as described (dont worry about the lease seconds import not working warning, in case youre getting that too...)

ps, if you got problems still with stuff like some 3rd party libs doing upgrades not working..., maybe try a composer selfupdate...
