### ISSUE TITLE
./zed update nzedb giving an error 0.7.3.0 2017-06-05

### ISSUE THREAD

**Issue by dertbv** [nZEDb/nZEDb#2463]
###Expected behaviour
Updating to update 

###Actual behaviour
Getting an error when i run the update..SUCCESS: DELETE FROM release_naming_regexes WHERE id IN (30, 31, 35, 749, 750, 751, 1160, 1161, 1162);
Info: COMMENT: Adjust previous regex
SUCCESS: UPDATE release_naming_regexes SET id = id - 2 WHERE id IN (32, 33, 34);
Error: UPDATE release_naming_regexes SET id = id - 3 WHERE id BETWEEN 752 AND 1159; Failed \{1062}
   Duplicate entry '1030' for key 'PRIMARY'

###Steps to reproduce the behaviour

**Comment by niel** [comment]
The reason is there in the error (duplicate key). As to how that happened I couldn't say. Have you manually added regexes in the past?
Resolving it will take manual intervention, for which you had best come to the IRC channel as it will take some Q & A to work out how to fix it.

**Comment by bobtongue** [comment]
Any resolution to this error? I have just come across the exact same error

**Comment by dertbv** [comment]
I went on to the chat and got a resolution.  I had to truncate (TRUNCATE release_naming_regexes;) the table reload from the nZEDb/resources/db/schema/data/10-release_naming_regexes.tsv and change the sql patch level 

In my case I was am running a vm so I reverted the vm and did the first 2 steps and then ran ./zed update nzedb and it completed.  If you don't have the ability to rollback a snapshot you will need to following all three..

TRUNCATE release_naming_regexes;

LOAD DATA LOCAL INFILE '/var/www/nZEDb/resources/db/schema/data/10-release_naming_regexes.tsv' INTO TABLE release_naming_regexes FIELDS TERMINATED BY "\t" LINES TERMINATED by "\r\n" IGNORE 1 LINES (id, group_regex, regex, status, description, ordinal);

UPDATE settings SET value = 482 WHERE setting = 'sqlpatch';
