### ISSUE TITLE
broken since update DB on remote server.

### ISSUE THREAD

**Issue by csmarauder** [nZEDb/nZEDb#2464]
I just updated and when I try to run any php or start tmux it just exits.
My DB is on another server and I did the update time zone in the data base and set the timezone in the config file on the remote server.
DO I need to set anything on the machine running the frontend?
Also is there a way (I found something in the forum didn't work) to force zed
to recheck the files against the git repo?

# ./zed version all
Looking up Git tag version(s)
Hash: 1c4835baf1485938643aa417585d2e9cb319b105
XML version: 0.7.3.0
Git version: 0.7.3.0
Looking up SQL patch version(s)
XML version: 482
 DB version: 474
# ./zed update db
Checking database version...
Db: 474,        File: 482
Couldn't change session tz_session!
Modify message

**Comment by richierichman** [comment]
+1 
I have this same issue. On Dev branch. I cant seem to run start.php or do ./zed update all, it gives no output.

**Comment by niel** [comment]
Read the ReleaseNotes. You haven't made the needed changes.

**Comment by csmarauder** [comment]
Are you referring to the time zone update for the  DB?
I set it the DB is on a remote machine so it looks like when it goes to apply the sql updates it fails bases on the error above.

mysql> SHOW GLOBAL VARIABLES LIKE 'time_zone';
+---------------+------------------+
| Variable_name | Value            |
+---------------+------------------+
| time_zone     | America/New_York |
+---------------+------------------+
1 row in set (0.00 sec)

My question is do I need to do anything on the front end machine that is running the scripts.

**Comment by niel** [comment]
Yes. Have you populated the timezone tables? MySQL (and compatibles) only creates the tables, it does not fill them with the timezone data. This you need to do yourself. How it is done, depends on what platform the server is run on.
Your answer implies you have only set the timezone for the server, which is not what the ReleaseNotes advise, not filled the tables.

**Comment by niel** [comment]
@richierichman if you're on dev, you should have noticed any problem long before now. When did you previously last update?

**Comment by niel** [comment]
@csmarauder if you have updated the timezone tables and still have issues, please come to the IRC channel where it will be easier to debug the problem in real time.

**Comment by niel** [comment]
One further thought, is the timezone set for PHP? date.timezone in the appropriate configuration files?
It must be set in both the cli and web configuration files.

**Comment by csmarauder** [comment]
Thanks for the quick turn around I did not have the timezone set in the cli conf file for php.

As soon as I added it I was able to complete the DB patching and it worked fine.

Please close.
