### ISSUE TITLE
nzedb/ADE.php is broken

### ISSUE THREAD

**Issue by sspilleman** [nZEDb/nZEDb#2465]
###Expected behaviour
Should find / match a movie, get the details and insert

###Actual behaviour
*never* finds *any* move. SELECT distinct classused in info table also shows that none of the matches come from ADE.

###Steps to reproduce the behaviour
misc/update/nix/multiprocessing/postprocess.php ama and you'll see :-)

**Comment by Bart39** [comment]
Not seeing any issues, provide more info on what you're seeing

**Comment by sspilleman** [comment]
@Bart39 : Versions:
```
nzedb$ ./zed version all
Looking up Git tag version(s)
Hash: 1a3e1cbf21e803184b8905a0545bb78be88931f0
XML version: 0.7.2.1
Git version: 0.7.2.1
Looking up SQL patch version(s)
XML version: 474
 DB version: 474
```

output of "select distinct(`classused`) from `xxxinfo`;" is:
- aebn
- adm
- pop

**seeing in nzedb/XXX.php the following. It basically means, try ADE ($res = $mov->search();). If nothing found if ($res === false), try POP...**

```php
if ($res === false) {
	$this->whichclass = "ade";
	$mov = new ADE();
	$mov->searchTerm = $xxxmovie;
	$res = $mov->search();
}

if ($res === false) {
	$this->whichclass = "pop";
	$mov = new Popporn();
	$mov->cookie = $this->cookie;
	$mov->searchTerm = $xxxmovie;
	$res = $mov->search();
}
```
I see in nzedb/ADE.php the following:
```php
public function search()
{
	if (!isset($this->searchTerm)) {
		return false;
	}
	if ($this->getUrl($this->_dvdQuery . rawurlencode($this->searchTerm)) === false) {
		return false;
	} else {
		$this->_html->load($this->_response);
		if ($ret = $this->_html->find("a.boxcover", 0)) {
			$title = $ret->title;
			$title = preg_replace('/XXX/', '', $title);
			$title = preg_replace('/\(.*?\)|[-._]/i', ' ', $title);
			$ret   = (string)trim($ret->href);
			similar_text(strtolower($this->searchTerm), strtolower($title), $p);
			if ($p >= 90) {
				$this->found      = true;
				$this->_urlFound  = $ret;
				$this->_directUrl = self::ADE . $ret;
				$this->_title     = trim($title);
				unset($ret);
				$this->_html->clear();
				$this->getUrl($this->_urlFound);
				$this->_html->load($this->_response);
			} else {
				$this->found = false;

				return false;
			}
		} else {
			return false;
		}
	}
	return false;
}
```

**If it finds anything (if ($p >= 90)), it doesn't return true!**

**Comment by sspilleman** [comment]
@Bart39 If I fix that issue (previous message), the function getAll() is called. Most sections are broken. I I can remember, only the directurl, boxcover, backcover and title is correct. I already fixed the synopsis, genres, productInfo. Working on cast and trailers...... You're on IRC?

**Comment by niel** [comment]
@sspilleman you are on an older version of the code. Update to v0.7.3.0 and see if this persists. Be absolutely sure to read the ReleaseNotes as some user action is required for the update.

**Comment by sspilleman** [comment]
@niel, @Bart39  Nope..... nzedb/ADE.php hasn't been changed since a year! And I installed, probably 1 week ago...... So Even though I WISH that were the case..... the search() function in nzedb/ADE.php still doesn't return true if it finds anything

**Comment by sspilleman** [comment]
Please read the comments carefully..... it's just not working

**Comment by niel** [comment]
It may not have changed, but that doesn't mean a file it depends on hasn't. That's not important though, what IS important is we do not debug on old code because we're not running it any more. All fixes have to be applied against the dev branch and debugging against older code simply isn't worth the work it takes.

As others have pointed out, it works for them, so chances are it is something specific to your situation. Updating *might* shake the reason loose.

**Comment by sspilleman** [comment]
I appreciate your comment @niel , but I highly doubt if the people that pointed out its working for them, actually checked if the ADE scarper is working. The solution as a whole isn't broken. it doesn't generate errors. Stuff is matched against aebn, adm and pop.... so more digging is needed to see if it actually IS working....

what do you mean by "old code"? is xxx matching deprecated??

**Comment by niel** [comment]
I said "older code" not old, and I mean anything older than the current release.

**Comment by sspilleman** [comment]
This is release N-1 right? Hmmm.... *makes me wonder why i even bothered creating a ticket in the 1st place*..... if the code hasn't changed, it's still broken right? or maybe we should trust github here ;-)

**Comment by sspilleman** [comment]
I still believe it should be investigated a bit deeper....

**Comment by DariusIII** [comment]
This should have been fixed in my XXX PR so i am closing the issue. Feel free to reopen it if this still does not work.
