### ISSUE TITLE
nzedb/IAFD is broken

### ISSUE THREAD

**Issue by sspilleman** [nZEDb/nZEDb#2466]
###Expected behaviour
Should find / match a movie, get the site where the movie can be found directly scrape from there

###Actual behaviour
never finds any move. 

###Steps to reproduce the behaviour
misc/update/nix/multiprocessing/postprocess.php ama and you'll see :-)

**Comment by Bart39** [comment]
Not seeing any issues, provide more info on what you're seeing

**Comment by DariusIII** [comment]
This should have been fixed in my XXX PR (IAFD has been removed as it is just a search for other sites we use) so i am closing the issue. Feel free to reopen it if this still does not work.
