### ISSUE TITLE
misc/update/nix/multiprocessing/postprocess.php ama shouln't call broken scrapers

### ISSUE THREAD

**Issue by sspilleman** [nZEDb/nZEDb#2467]
###Expected behaviour
AMA postprocess should only call scrapers that work.

###Actual behaviour
As per my other 2 latest issues, ADE and IAFD scrapers are broken. These shouldn't be called untill fixed

###Steps to reproduce the behaviour
run misc/update/nix/multiprocessing/postprocess.php ama

**Comment by Wally73** [comment]
check if your amazon keys still work 
i've heard from a few that their keys are disabled 

2nd you don't need amazon processing period as movies are looked up fine mostly by the other scrapers

**Comment by sspilleman** [comment]
Amzon key is ok. Other processing scripts don't process all movie types, (ADE & IAFD are broken) ;-)

**Comment by Wally73** [comment]
i've never used amazon processing myself 
with tmdb/trakt api they are all looked up

**Comment by Bart39** [comment]
Ama is a red herring, that's just the multi processing mode - it means single thread mode (as used by Amazon and xxx lookups)

However - I am not seeing any issues myself, am getting results from both ade and iafd

**Comment by sspilleman** [comment]
Hmmmm strange @Bart39 . I'm fixing the ADE one currently... What version are you using? With mine, it just searches for the wrong tags etc.....
Can you run the following query "select distinct(`classused`) from `xxxinfo`;" ?

**Comment by sspilleman** [comment]
@Bart39 Can you run this query for me? Tx

**Comment by DariusIII** [comment]
I have fixed XXX processing in nntmux, there are some small quirks to be fixed and ten i will do a PR to zed.

 Showing rows 0 -  3 (4 total, Query took 0.0082 seconds.)

SELECT DISTINCT classused FROM xxxinfo


classused	
aebn	
ade	
adm	
hotm
