### ISSUE TITLE
Steam Post Processing loops

### ISSUE THREAD

**Issue by Boinkers** [nZEDb/nZEDb#2468]
Is this normal for the steam/games post processing, see my unprocessed does not drop:

Notice: Steam search returned no valid results
Notice: GiantBomb returned no valid results
Looking up: 02 (PC)
Info: Populating steam apps table

....
Added 4 new steam apps, 41972 duplicates skipped
Notice: Steam search returned no valid results
Notice: GiantBomb returned no valid results
Looking up: 01 (PC)
Info: Populating steam apps table

....
Added 4 new steam apps, 41972 duplicates skipped
Notice: Steam search returned no valid results
Notice: GiantBomb returned no valid results
Looking up: 02 (PC)
Info: Populating steam apps table

....
Added 4 new steam apps, 41972 duplicates skipped
Notice: Steam search returned no valid results
Notice: GiantBomb returned no valid results
Looking up: 01 (PC)
Info: Populating steam apps table

....
Added 4 new steam apps, 41972 duplicates skipped
Notice: Steam search returned no valid results
Notice: GiantBomb returned no valid results
Looking up: 01 (PC)
Info: Populating steam apps table

It just keeps saying the same thing over and over

**Comment by b3rs3rk** [comment]
```
SELECT value FROM settings WHERE section = 'APIs' AND subsection = 'steam_apps' AND name = 'last_update';
```

Run that in MySQL and paste the result please.

**Comment by Boinkers** [comment]
MariaDB [nzedb]> SELECT value FROM settings WHERE section = 'APIs' AND subsection = 'steam_apps' AND name = 'last_update';
+-------+
| value |
+-------+
| 0     |
+-------+
1 row in set (0.00 sec)

**Comment by niel** [comment]
Looks like the last update time isn't being updated. I'll take a look.

**Comment by Boinkers** [comment]
Hi,

The change you made was still wrong, the correct code change is:

                        ['section' => 'APIs', 'subsection' => 'steam_apps', 'name' => 'last_update']

Updated my Steam.php as above and work 100% now.

**Comment by DariusIII** [comment]
Oh, i fixed that couple of minutes after the first push: https://github.com/nZEDb/nZEDb/commit/8877d4b5aaa6d043a5340a0ecb410a7fa08b88d5

Edit: I guess you are on 0.x branch, hence you do not see changes in dev unless we point you to them :)

**Comment by niel** [comment]
I'll be creating a release for this in 0.x branch today.
