### ISSUE TITLE
./zed update nzedb error

### ISSUE THREAD

**Issue by DrSeussFreak** [nZEDb/nZEDb#2469]
I ran ./zed update nzedb and it ran, and then errored out with

`mfederman@Sentinel:/var/www/nZEDb$ ./zed update nzedb
PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1298 Unknown or incorrect time zone: 'America/Chicago' in /var/www/nZEDb/app/extensions/adapter/data/source/database/MySql.php:116
Stack trace:
#0 /var/www/nZEDb/app/extensions/adapter/data/source/database/MySql.php(116): PDO->exec('SET time_zone =...')
#1 /var/www/nZEDb/app/extensions/adapter/data/source/database/MySql.php(83): app\extensions\adapter\data\source\database\MySql->timezone('America/Chicago')
#2 /var/www/nZEDb/libraries/lithium/data/Source.php(111): app\extensions\adapter\data\source\database\MySql->connect()
#3 /var/www/nZEDb/libraries/lithium/data/source/Database.php(210): lithium\data\Source->_init()
#4 /var/www/nZEDb/libraries/lithium/data/source/database/adapter/MySql.php(192): lithium\data\source\Database->_init()
#5 /var/www/nZEDb/libraries/lithium/core/Object.php(84): lithium\data\source\database\adapter\MySql->_init()
#6 /var/www/nZEDb/libraries/lithium/data/Source.php(94): lithium\core\Object->__construct(Array)
#7 /var/www/nZEDb/l in /var/www/nZEDb/app/extensions/adapter/data/source/database/MySql.php on line 116`

php.ini has always had `date.timezone = "America/Chicago"` so not sure why it is suddenly complaining...

**Comment by DariusIII** [comment]
You failed to read the ReleaseNotes: https://github.com/nZEDb/nZEDb/blob/0.x/ReleaseNotes#L15-L20

**Comment by DrSeussFreak** [comment]
And tht is what I get for skipping them this time.  Thanks, issue resolved.
