### ISSUE TITLE
user cart undeletable

### ISSUE THREAD

**Issue by OliverLeitner** [nZEDb/nZEDb#2471]
###Expected behaviour

mark the entries to delete, click delete, and they disappear from the cart.

###Actual behaviour

mark the entries, click delete, nothing gets deleted.

###Steps to reproduce the behaviour

default ui
just click on profile -> my cart -> check the checkboxes on the things you want to delete and then click the delete button.

**Comment by DariusIII** [comment]
Which theme?

**Comment by OliverLeitner** [comment]
default

**Comment by DariusIII** [comment]
Tested this couple of minutes ago and it worked for me with no problems.

**Comment by OliverLeitner** [comment]
im sure it works for others, thats my luck..., so, what do you guys think this could be? you had this ever happen to you?

**Comment by niel** [comment]
No idea without details. Check your logs. Also, by "default" do you mean 'Default' or 'Alpha'

**Comment by OliverLeitner** [comment]
Theme: Alpha

to which logs are you exactly referring?

have a "workaround" for now, i can delete single entries by clicking the delete "buttons" besides them. just not the selected delete.

**Comment by niel** [comment]
.../resources/logs
You will probably have to enable logging in your .../configuration/settings.php

**Comment by DariusIII** [comment]
That is done by JavaScript so i doubt logs will show anything.

**Comment by OliverLeitner** [comment]
darius, jups, that might be the point.

a little update though, this seems to only happen sometimes, after deleting the cart entry by entry... i had things in cart again, and this time the cart auto deleted, as it should, after viewing the rss version of the cart.
