### ISSUE TITLE
PHP Fatal error in /var/www/nZEDb/app/libraries/b3rs3rk/steamfront/source/b3rs3rk/steamfront/Main.php

### ISSUE THREAD

**Issue by moloquin** [nZEDb/nZEDb#2475]
###Expected behaviour
Post-process to complete and process all categories.

###Actual behaviour
Amazon post-processing looks to fail once it hits the games/pc lookup after book catagories.  Never gets to Audio/XXX/etc.

By Disabling Game Lookups in Edit Site and now it continues on as expected, but no game processing.

PHP Fatal error:  Default value for parameters with a class type hint can only be NULL in /var/www/nZEDb/app/libraries/b3rs3rk/steamfront/source/b3rs3rk/steamfront/Main.php on line 157

###Steps to reproduce the behaviour
Updated to latest 0.x and noticed it.  Installed on a different server, fresh build from scratch and checked out 0.x with the same behaviour.

/var/www/nZEDb# ./zed update nZEDb
Already up-to-date.
Checking database version...
Db: 482,	File: 482
Up to date.
The Smarty compiled template cache has been cleared for you

/var/www/nZEDb# ./zed version all
Looking up Git tag version(s)
Hash: 84a81108a9112f0b018215e6696f02bf88f09e3c
XML version: 0.7.3.1
Git version: 0.7.3.1
Looking up SQL patch version(s)
XML version: 482
 DB version: 482

debian_version 8.8

PHP 5.6.30-0+deb8u1 (cli) (built: Feb  8 2017 08:50:21) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

mysql  Ver 15.1 Distrib 10.0.30-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

Server version: Apache/2.4.10 (Debian)
Server built:   Feb 24 2017 18:40:28

**Comment by niel** [comment]
Can you provide a stack trace from php-cli.log

**Comment by moloquin** [comment]
Here you go.  Thx.

[17-Jun-2017 11:23:30 America/Toronto] PHP Fatal error:  Default value for parameters with a class type hint can only be NULL in /var/www/nZEDb/app/libraries/b3rs3rk/steamfront/source/b3rs3rk/steamfront/Main.php on line 157
[17-Jun-2017 11:23:30 America/Toronto] PHP Stack trace:
[17-Jun-2017 11:23:30 America/Toronto] PHP   1. {main}() /var/www/nZEDb/misc/update/nix/multiprocessing/postprocess.php:0
[17-Jun-2017 11:23:30 America/Toronto] PHP   2. nzedb\libraries\Forking->processWorkType() /var/www/nZEDb/misc/update/nix/multiprocessing/postprocess.php:22
[17-Jun-2017 11:23:30 America/Toronto] PHP   3. nzedb\libraries\Forking->getWork() /var/www/nZEDb/nzedb/libraries/Forking.php:107
[17-Jun-2017 11:23:30 America/Toronto] PHP   4. nzedb\libraries\Forking->processSingle() /var/www/nZEDb/nzedb/libraries/Forking.php:162
[17-Jun-2017 11:23:30 America/Toronto] PHP   5. nzedb\processing\PostProcess->processGames() /var/www/nZEDb/nzedb/libraries/Forking.php:882
[17-Jun-2017 11:23:30 America/Toronto] PHP   6. nzedb\Games->processGamesReleases() /var/www/nZEDb/nzedb/processing/PostProcess.php:186
[17-Jun-2017 11:23:30 America/Toronto] PHP   7. nzedb\Games->updateGamesInfo() /var/www/nZEDb/nzedb/Games.php:803
[17-Jun-2017 11:23:30 America/Toronto] PHP   8. nzedb\Steam->__construct() /var/www/nZEDb/nzedb/Games.php:500
[17-Jun-2017 11:23:30 America/Toronto] PHP   9. spl_autoload_call() /var/www/nZEDb/nzedb/Games.php:45
[17-Jun-2017 11:23:30 America/Toronto] PHP  10. Composer\Autoload\ClassLoader->loadClass() /var/www/nZEDb/nzedb/Games.php:0
[17-Jun-2017 11:23:30 America/Toronto] PHP  11. Composer\Autoload\includeFile() /var/www/nZEDb/app/libraries/composer/ClassLoader.php:322

**Comment by lilHermit** [comment]
I've seen this too, it finds a match, displays it and then bombs out. Same match next iteration so doesn't process anything after games. I too have stopped processing of games however I commented in code.

**Comment by DariusIII** [comment]
This is due to b3rs3rk using PHP7 type hints in his code, while you have php5.6 installed, where these do not work.

**Comment by lilHermit** [comment]
@DariusIII I'm using PHP7

```
xxxxx@sparrow:~/sparrow/nZEDb$ ./zed version all
Looking up Git tag version(s)
Hash: 84a81108a9112f0b018215e6696f02bf88f09e3c
XML version: 0.7.3.1
Git version: 0.7.0.0
Looking up SQL patch version(s)
XML version: 482
DB version: 482

xxxxx@sparrow:~/sparrow/nZEDb$ php -v
PHP 7.0.18-1~dotdeb+8.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.18-1~dotdeb+8.1, Copyright (c) 1999-2017, by Zend Technologies
```

**Comment by DariusIII** [comment]
I have made a PR to remove class type hints.

**Comment by niel** [comment]
These are type declarations (not hints, that term has always been misused for this). The error is not because of 5.6, that would throw a "recoverable fatal error", this is because of the `string $filter = ''`. Th empty single quotes is not a valid default value, it must be null instead.

**Comment by ThePeePs** [comment]
I've had to disable PP on consoles/games because of this error (running php 5.6) any ETA on when this will be fixed?

**Comment by niel** [comment]
@ThePeePs I've given b3rs3rk a poke on this, but he hasn't been around much lately due to work.

**Comment by moloquin** [comment]
Quick update on this issue from my end.  Updated to PHP 7.1 and updated nZEDb this AM to latest 0.x.  Enabled game lookups under Site Edit and although it still crashes out during processing I'm getting a different php debug error now.  Not sure if it is still the same issue or not.

[08-Aug-2017 14:49:33 America/Toronto] PHP Fatal error:  Uncaught exception 'Exception' with message 'Unable to fetch setting from Db!' in /var/www/nZEDb/app/models/Settings.php:257
Stack trace:
#0 /var/www/nZEDb/nzedb/Steam.php(149): app\models\Settings::value('APIs.steam_apps...')
#1 /var/www/nZEDb/nzedb/Steam.php(106): nzedb\Steam->populateSteamAppsTable()
#2 /var/www/nZEDb/nzedb/Games.php(505): nzedb\Steam->search('Sine Mora EX')
#3 /var/www/nZEDb/nzedb/Games.php(808): nzedb\Games->updateGamesInfo(Array)
#4 /var/www/nZEDb/nzedb/processing/PostProcess.php(186): nzedb\Games->processGamesReleases()
#5 /var/www/nZEDb/misc/update/postprocess.php(95): nzedb\processing\PostProcess->processGames()
#6 {main}
  thrown in /var/www/nZEDb/app/models/Settings.php on line 257

**Comment by niel** [comment]
@moloquin make sure sql patches 0476 and 0478 have been applied correctly. That's the setting it is failing to fetch.

**Comment by moloquin** [comment]
Everything DB according to zed says it's up to date.  Can I manually re-apply the two patches without messing anything up?

./zed version all
Looking up Git tag version(s)
Hash: 07ce6f015cd67f8ad062377903fb10dbdc84f7c1
XML version: 0.7.4.0
Git version: 0.7.3.1
Looking up SQL patch version(s)
XML version: 482
 DB version: 482

**Comment by niel** [comment]
Yes you can.

**Comment by moloquin** [comment]
Getting there...Ran the verify settings table before and after the patches.

./zed verify settings_table
Verifying settings table...
(section, subsection, name):
 APIs, steam_apps, last_update: MISSING!
 APIs, APIKeys, section-label: MISSING!

Ran it again after re-applying 0476 and 0478.

./zed verify settings_table
Verifying settings table...
(section, subsection, name):
 APIs, APIKeys, section-label: MISSING!

Any idea what patch I am missing?

**Comment by moloquin** [comment]
Turned game/console processing back on briefly and got this error.  Don't know if it's related to the missing APIKey row in my settings table.

PHP Catchable fatal error:  Argument 1 passed to b3rs3rk\steamfront\http\Http::get() must be an instance of b3rs3rk\steamfront\http\string, string given, called in /var/www/nZEDb/app/libraries/b3rs3rk/steamfront/source/b3rs3rk/steamfront/Main.php on line 108 and defined in /var/www/nZEDb/app/libraries/b3rs3rk/steamfront/source/b3rs3rk/steamfront/http/Http.php on line 37
PHP Stack trace:
PHP   1. {main}() /var/www/nZEDb/misc/update/postprocess.php:0
PHP   2. nzedb\processing\PostProcess->processGames() /var/www/nZEDb/misc/update/postprocess.php:95
PHP   3. nzedb\Games->processGamesReleases() /var/www/nZEDb/nzedb/processing/PostProcess.php:186
PHP   4. nzedb\Games->updateGamesInfo() /var/www/nZEDb/nzedb/Games.php:808
PHP   5. nzedb\Steam->search() /var/www/nZEDb/nzedb/Games.php:505
PHP   6. nzedb\Steam->populateSteamAppsTable() /var/www/nZEDb/nzedb/Steam.php:106
PHP   7. b3rs3rk\steamfront\Main->getFullAppList() /var/www/nZEDb/nzedb/Steam.php:154
PHP   8. b3rs3rk\steamfront\Main->get() /var/www/nZEDb/app/libraries/b3rs3rk/steamfront/source/b3rs3rk/steamfront/Main.php:126
PHP   9. b3rs3rk\steamfront\http\Http::get() /var/www/nZEDb/app/libraries/b3rs3rk/steamfront/source/b3rs3rk/steamfront/Main.php:108

**Comment by niel** [comment]
Don't worry about that last missing row. I keep meaning to fix the problem, but never find the time.

**Comment by moloquin** [comment]
Ok.  Thanks for looking into it.  I'll wait for a fix from b3rs3rk for the steam api calls.

**Comment by niel** [comment]
@moloquin I've pushed a fix for the steam issue to the dev branch. Hopefully, b3rs3rk will have the main repository fixed soon, but if he doesn't, it will be fixed with the next release.

**Comment by moloquin** [comment]
Awesome.  Thanks Niel.

**Comment by niel** [comment]
@moloquin what version of PHP are you using?

**Comment by moloquin** [comment]
I'm running 7.1 (sury's version) on Deb8.  Stuck on Deb8 because of kernel/hardware limitations.

**Comment by niel** [comment]
That is strange. The error you reported shouldn't occur with PHP 7+, it doesn't with my 7.0 install. I'm wondering if you've discovered a bug in PHP itself.

**Comment by moloquin** [comment]
I've seen the same behaviour on PHP 5.6 (deb repo), 7.0(dotdeb repo) and 7.1(sury repo)...maybe a bug or a missing php library?  Not really sure at this point...

If there's anything I can do to help diagnose from my end let me know.

**Comment by DariusIII** [comment]
Is PHP 5.6 still installed on your system? Behavior like this can be observed when older libraries still exist on system, and you need to purge the old php.

**Comment by moloquin** [comment]
Think I found it (thanks for the pointer DariusIII).  Looks like php-pear on my system was still using the deb repo version.  Purged that and re-installed php-pear from sury's repo.  That, mostly, got things running.  YYdecode was not happy with sury's php-pear, so had to revert to php's built in yenc handler (have tried to get php-yenc installed but keep running into problems (same as this, https://github.com/niel/php-yenc/issues/3)).

But, PC/Console is now happily processing, populating and chewing through the backlog.

The only minor thing I'm seeing is a php notice showing up in php_errors_cli.  Since it's just a notice I'm not overly worried about it, but is spamming the log.  I'll leave the stack trace here if anyone wants to take a look for a future release. 

Thanks All.

PHP Notice:  Only variables should be assigned by reference in /usr/share/php/PEAR.php on line 601
PHP Stack trace:
PHP   1. {main}() /var/www/nZEDb/misc/update/nix/multiprocessing/.do_not_run/switch.php:0
PHP   2. nzedb\processing\post\ProcessAdditional->start() /var/www/nZEDb/misc/update/nix/multiprocessing/.do_not_run/switch.php:247
PHP   3. nzedb\processing\post\ProcessAdditional->_processReleases() /var/www/nZEDb/nzedb/processing/post/ProcessAdditional.php:537
PHP   4. nzedb\processing\post\ProcessAdditional->_processNZBCompressedFiles() /var/www/nZEDb/nzedb/processing/post/ProcessAdditional.php:721
PHP   5. nzedb\NNTP->getMessages() /var/www/nZEDb/nzedb/processing/post/ProcessAdditional.php:1028
PHP   6. nzedb\NNTP->_getMessage() /var/www/nZEDb/nzedb/NNTP.php:598
PHP   7. nzedb\NNTP->_handleErrorResponse() /var/www/nZEDb/nzedb/NNTP.php:1467
PHP   8. nzedb\NNTP->throwError() /var/www/nZEDb/libs/PEAR/Net_NNTP/NNTP/Protocol/Client.php:2007
PHP   9. nzedb\NNTP->__call() /var/www/nZEDb/libs/PEAR/Net_NNTP/NNTP/Protocol/Client.php:2007
PHP  10. nzedb\NNTP->_throwError() /usr/share/php/PEAR.php:223

**Comment by niel** [comment]
That is a known issue with PEAR itself. You can edit the PEAR file and remove the & that makes the assignment by reference. There's a second one a few lines down.
