### ISSUE TITLE
Cannot delete release from admin webui

### ISSUE THREAD

**Issue by samwiseg0** [nZEDb/nZEDb#2477]
###Expected behaviour
Clicking delete will delete the release from the DB

###Actual behaviour
Error 500

```
2017/06/19 17:33:47 [error] 2081#0: *30046 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1305 PROCEDURE nzedbdb.delete_release does not exist' in /var/www/nZEDb/nzedb/Releases.php:635
Stack trace:
#0 /var/www/nZEDb/nzedb/Releases.php(635): PDOStatement->execute()
#1 /var/www/nZEDb/nzedb/Releases.php(596): nzedb\Releases->deleteSingle(Array, Object(nzedb\NZB), Object(nzedb\ReleaseImage))
#2 /var/www/nZEDb/www/admin/release-delete.php(10): nzedb\Releases->deleteMultiple('5704140')
#3 {main}
  thrown in /var/www/nZEDb/nzedb/Releases.php on line 635" while reading response header from upstream, client: 1.1.1.1, server: nzedb.example.com, request: "GET //admin/release-delete.php?id=5704140&from=https://nzedb.example.com/browse HTTP/1.1", upstream: "fastcgi://unix:/var/run/php56-php-fpm.sock:", host: "nzedb.example.com"
```

###Steps to reproduce the behaviour
Latest release 0.7.3.1 Attempt to delete a release after logging in as an admin.

**Comment by Wally73** [comment]
seems you're missing the procedure 

in mysql do 
show procedure status where db = 'nzedb';

it should show 2 procedures 
delete_releases 
loop_cbpm  

If needed, you can manually create those procedures/triggers from here: 
https://github.com/nZEDb/nZEDb/blob/0.x/resources/db/schema/mysql-ddl.sql#L1430

**Comment by samwiseg0** [comment]
You are correct. I migrated to a galera cluster and forgot those existed. 

Problem solved!

Thanks!
