### ISSUE TITLE
Feature request: Sort Browse PreDb by most recent

### ISSUE THREAD

**Issue by samwiseg0** [nZEDb/nZEDb#2480]
###Expected behaviour
I think it would make sense to show the most recent items in Browse PreDb webui by most recently added to the the db

###Actual behaviour
Currently it looks like it is sorted by name.

###Steps to reproduce the behaviour
Go to Browse PreDb in admin section.

**Comment by niel** [comment]
And I think you're wrong :-) 
By name seems to be most obvious way to sort, initially at least, but having the option to sort on other criteria and for it to remember that, would be best possible situation I think.

**Comment by samwiseg0** [comment]
I am never opposed to options :)

**Comment by Wally73** [comment]
sorting would be nice yes  ;)
