### ISSUE TITLE
resetdb.php issue

### ISSUE THREAD

**Issue by PsychoSid** [nZEDb/nZEDb#2481]
###Expected behaviour
Cleaned filesystem of nzb files etc

###Actual behaviour
Leaves them around on my setup

So running resetdb.php doesn't get past the first set of table truncates before stopping silently.

$sql = "CALL loop_cbpm('truncate')";
echo $pdo->log->primary("Truncating binaries, collections, missed_parts and parts tables...");
$result = $pdo->query($sql);
echo $pdo->log->primary("Truncating completed.");

Taking out the "$result = $pdo->query($sql);" call allows it to continue and clean up the files. I see this part was changed in the last commit which was some time ago.

So is there an issue with this part of the script, or as I suspect more likely something wrong with my setup to cause this to fail silently here ?

Thanks

**Comment by EDChurly** [comment]
Do you have the loop_cbpm as a stored procedure? 

From a sql prompt:
_show procedure status;_ 

If this doesn't show a stored procedure, that would be the issue.

**Comment by PsychoSid** [comment]
Thanks.

Looks OK
ariaDB [nzedb]> show procedure status;
+-------+----------------+-----------+-----------------+---------------------+---------------------+---------------+------------------------------------------------------------------------------------------+----------------------+----------------------+--------------------+
| Db    | Name           | Type      | Definer         | Modified            | Created             | Security_type | Comment                                                                                  | character_set_client | collation_connection | Database Collation |
+-------+----------------+-----------+-----------------+---------------------+---------------------+---------------+------------------------------------------------------------------------------------------+----------------------+----------------------+--------------------+
| nzedb | delete_release | PROCEDURE | nzedb@localhost | 2017-03-11 09:54:07 | 2017-03-11 09:54:07 | DEFINER       | If is_numeric is true, identifier should be the releases_id, if false the guid           | utf8                 | utf8_general_ci      | utf8_unicode_ci    |
| nzedb | loop_cbpm      | PROCEDURE | nzedb@localhost | 2017-03-11 09:54:07 | 2017-03-11 09:54:07 | DEFINER       | Performs tasks on All CBPM tables one by one -- REPAIR/ANALYZE/OPTIMIZE or DROP/TRUNCATE | utf8                 | utf8_general_ci      | utf8_unicode_ci    |
+-------+----------------+-----------+-----------------+---------------------+---------------------+---------------+------------------------------------------------------------------------------------------+----------------------+----------------------+--------------------+

**Comment by PsychoSid** [comment]
If I run CALL loop_cbpm('repair'); for example from the mysql prompt it's all OK

**Comment by PsychoSid** [comment]
The stored proc matches the refs in 0469 patch file also.

**Comment by PsychoSid** [comment]
Humm my parts tables at least are showing an odd charset it seems
MariaDB [nzedb]> show full columns from parts_86;
+-------------+-----------------------+-------------------+------+-----+---------+-------+---------------------------------+---------+
| Field       | Type                  | Collation         | Null | Key | Default | Extra | Privileges                      | Comment |
+-------------+-----------------------+-------------------+------+-----+---------+-------+---------------------------------+---------+
| binaries_id | bigint(20) unsigned   | NULL              | NO   | PRI | 0       |       | select,insert,update,references |         |
| messageid   | varchar(255)          | latin1_swedish_ci | NO   |     |         |       | select,insert,update,references |         |
| number      | bigint(20) unsigned   | NULL              | NO   | PRI | 0       |       | select,insert,update,references |         |
| partnumber  | mediumint(8) unsigned | NULL              | NO   |     | 0       |       | select,insert,update,references |         |
| size        | mediumint(8) unsigned | NULL              | NO   |     | 0       |       | select,insert,update,references |         |
+-------------+-----------------------+-------------------+------+-----+---------+-------+---------------------------------+---------+

**Comment by niel** [comment]
Have you enabled debugging and logging in ../configuration/settings.php? 
Need more info to narrow the field down. Particularly need SQL and PHP error logs.

**Comment by PsychoSid** [comment]
Ah yes sorry about that.

[22-Jun-2017 06:32:02 Europe/London] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error in /var/www/nZEDb/nzedb/db/DB.php:858
Stack trace:
#0 /var/www/nZEDb/nzedb/db/DB.php(858): PDOStatement->fetchAll()
#1 /var/www/nZEDb/nzedb/db/DB.php(835): nzedb\db\DB->queryArray('CALL loop_cbpm(...')
#2 /var/www/nZEDb/misc/testing/DB/resetdb.php(56): nzedb\db\DB->query('CALL loop_cbpm(...')
#3 {main}
  thrown in /var/www/nZEDb/nzedb/db/DB.php on line 858

**Comment by nickroberts** [comment]
Any luck on this? I'm getting the same error.

**Comment by PsychoSid** [comment]
Nothing other than removing that call from the script.

**Comment by niel** [comment]
That error indicates a problem with the connection to the DBMS. i.e. it is failing for an unknown reason. Throroughly check your DBMS/PHP setup
