### ISSUE TITLE
Category file size not removing items of a certain size

### ISSUE THREAD

**Issue by danpop-chainguard** [nZEDb/nZEDb#2485]
###Expected behaviour
delete releases if a limit is set.  i set 100MB as a minimum for releases in TV-HD, and MOVIES-HD. and not deleting.

###Actual behaviour
files not being deleted.  (using removeCrapReleases or in new releases via tmux scripts)

![image](https://user-images.githubusercontent.com/22457772/27435824-48346f30-572b-11e7-8801-4dd3656b40df.png)

###Steps to reproduce the behaviour
1) set a category limit of say  100MB (in bytes, 104,857,600 B)
![image](https://user-images.githubusercontent.com/22457772/27435707-f66313c8-572a-11e7-9d94-840bfdda1dbd.png)
2) try and run removeCrapRleases true size or delete_releases smaller=104,857,600 B 
3) languish in despair

**Comment by bobtongue** [comment]
Those releases you are showing are not Movies HD, those are WEB-DL

**Comment by danpop-chainguard** [comment]
look again at the category bob.

**Comment by danpop-chainguard** [comment]
hmmm whats weird is now they are gone.  hmmm maybe a cacheing/sphinx issue?  (im using memcached and sphinxsearch)

**Comment by danpop-chainguard** [comment]
closing for now.  but weird cacheing @niel

**Comment by Bart39** [comment]
https://github.com/nZEDb/nZEDb/blob/0.x/configuration/settings.example.php#L240

**Comment by danpop-chainguard** [comment]
@Bart39 can these values be changed?  

define('nZEDb_CACHE_EXPIRY_SHORT', 300);
define('nZEDb_CACHE_EXPIRY_MEDIUM', 600);
define('nZEDb_CACHE_EXPIRY_LONG', 900);

these seems to indicate its a static set of values:

 _The developers of nZEDb decide what should be set as short/medium/long, depending on the type of data._

**Comment by niel** [comment]
@danpopSD Of course they can be changed. That's the point of that file, to allow you to adjust your settings as needed.
We cannot set those depending on the type of your data, because we do not know your data. They are for you to fine tune.

**Comment by danpop-chainguard** [comment]
@niel is there a best practice on how to tune that?

**Comment by niel** [comment]
Not that I'm aware of. Check the wiki. Much of configuring settings is a matter of trial and error, and talking with other users in the IRC channel to get a better idea of what works for them.

**Comment by kaibosh** [comment]
Update_Releases performs release deletion based on those web-gui params, not removeCrap.  Those releases would have remained until the next time update_releases was called. 

delete_releases.php does not have support for deletion by the "pseudo" parent categories (eg. 2000). As input it needs to have the actual category ID that is stored in the releases table (eg. 2010, 2010 etc).
