### ISSUE TITLE
Error 500 On Step 2 of Install

### ISSUE THREAD

**Issue by sixshooterz** [nZEDb/nZEDb#2493]
###Expected behaviour
Set up the database using input from user (me)

###Actual behaviour
Error 500 after inputting correct data..

###Steps to reproduce the behaviour
Fresh install following the Ubuntu 14.04 guide (modified one step because composer requires php5.6)

Checking the Apache2 error log, it shows the following.

> [Thu Jul 13 02:05:43.577034 2017] [:error] [pid 3353] [client 172.16.10.68:62706] PHP Fatal error:  Uncaught exception 'ErrorException' with message 'Couldn't change session tz_session!' in /var/www/nZEDb/nzedb/db/DB.php:1375\nStack trac
> e:\n#0 /var/www/nZEDb/nzedb/db/DB.php(212): nzedb\\db\\DB->connect(Array)\n#1 /var/www/nZEDb/www/install/step2.php(106): nzedb\\db\\DB->__construct(Array)\n#2 {main}\n  thrown in /var/www/nZEDb/nzedb/db/DB.php on line 1375, referer: http
> ://172.16.10.20/install/step2.php?

**Comment by scriptzteam** [comment]
If ya read a bit "Couldn't change session tz_session!" ;)

Set the timezone on DB also PHP

**Comment by Bart39** [comment]
See https://github.com/nZEDb/nZEDb/issues/2470
Response there quotes the lines from the release notes that solve this issue

**Comment by sixshooterz** [comment]
Thank you!
@scriptzteam I set it for PHP but neglected to set it on the DB. Sorry!!

**Comment by KillerdogKD** [comment]
Hi,

i have the same problem in step2 👍 
`Fatal  error: Uncaught exception 'ErrorException' with message 'Couldn't  change session tz_session!' in C:\WPN-XM\www\nzedb\nzedb\db\DB.php on  line 1375--
`

i'm on windows with WPN-XM, but have the same things with wamp, xamp or wtserver.

I configure php.ini with "date.timezone = Europe/Berlin" but it does the same.

What should i do to populate mariaDB with correct timezone ?

Thanks
