### ISSUE TITLE
New hashing scheme being used to generate release names/filenames on some groups

### ISSUE THREAD

**Issue by stravager** [nZEDb/nZEDb#2494]
Actually looks like this scheme has been in use for about 6 months, but I only recently tried to figure it out. a.b.moovee is using it, for one. The following query will populate predb_hashes with the right values, but the predb insert/update/delete triggers would need to be updated too for a full fix

INSERT IGNORE INTO predb_hashes (hash, predb_id) SELECT UNHEX(MD5(CONCAT(title, requestid))), id from predb;
INSERT IGNORE INTO predb_hashes (hash, predb_id) SELECT UNHEX(MD5(CONCAT(title, requestid, requestid))), id from predb;

The double requestid form seems to be more commonly used but I've seen both.

**Comment by niel** [comment]
Thanks for the info. We'll look into this as soon as we can, time is in short supply currently.

**Comment by dilbaggins** [comment]
any updates on this one @niel definitely seeing this with a.b.movee and etc as well

**Comment by niel** [comment]
No update. Still short on time.

**Comment by jangrewe** [comment]
Oh, that would explain why i'm seeing less and less releases! Could this please please please be prioritized? =)

**Comment by jangrewe** [comment]
Would these Triggers do the job?
```
BEGIN
  INSERT INTO predb_hashes (hash, predb_id) VALUES 
  ( UNHEX(MD5(NEW.title)), NEW.id ), 
  ( UNHEX(MD5(MD5(NEW.title))), NEW.id ), 
  ( UNHEX(SHA1(NEW.title)), NEW.id ),
  ( UNHEX(MD5(CONCAT(NEW.title, NEW.requestid))), NEW.id ),
  ( UNHEX(MD5(CONCAT(NEW.title, NEW.requestid, NEW.requestid))), NEW.id );
END
```
```
BEGIN
  DELETE FROM predb_hashes WHERE hash IN ( 
    UNHEX(md5(OLD.title)), 
    UNHEX(md5(md5(OLD.title))), 
    UNHEX(sha1(OLD.title)),
    UNHEX(MD5(CONCAT(OLD.title, OLD.requestid))), 
    UNHEX(MD5(CONCAT(OLD.title, OLD.requestid, OLD.requestid)))
  ) AND predb_id = OLD.id;
END
```
```
BEGIN
  IF NEW.title != OLD.title
  THEN
    DELETE FROM predb_hashes WHERE hash IN ( 
      UNHEX(md5(OLD.title)),
      UNHEX(md5(md5(OLD.title))),
      UNHEX(sha1(OLD.title)),
      UNHEX(MD5(CONCAT(OLD.title, OLD.requestid))), 
      UNHEX(MD5(CONCAT(OLD.title, OLD.requestid, OLD.requestid)))
    ) AND predb_id = OLD.id;
    INSERT INTO predb_hashes (hash, predb_id) VALUES 
      ( UNHEX(MD5(NEW.title)), NEW.id ),
      ( UNHEX(MD5(MD5(NEW.title))), NEW.id ),
      ( UNHEX(SHA1(NEW.title)), NEW.id ),
      ( UNHEX(MD5(CONCAT(NEW.title, NEW.requestid))), NEW.id ),
      ( UNHEX(MD5(CONCAT(NEW.title, NEW.requestid, NEW.requestid))), NEW.id );
  END IF;
END
```
I've taken the existing ones and added the two variations mentioned above (plus some formatting for readability).

**Comment by Bart39** [comment]
In short: no
New hashing is using requestid so you need to change the ones you added to reference NEW.requestid not NEW.ID

E.g. 'UNHEX(MD5(CONCAT(NEW.title, NEW.requestid, NEW.requestid))), NEW.id );'

**Comment by jangrewe** [comment]
Doh, i totally missed that, thanks!
I've updated my comment in case anybody stumbles across it...

**Comment by Bart39** [comment]
Same comment for the deletes - OLD.requestid not OLD.id 😊

**Comment by jangrewe** [comment]
argh, right! fixed! =)

**Comment by Bart39** [comment]
Heh, sorry but one more Set of OLD.requestid in the last code block "DELETE FROM...." ;)

**Comment by jangrewe** [comment]
Sorry, this time i don't see it? There's `OLD.requestid` twice in that last set?

**Comment by Bart39** [comment]
`
BEGIN
  IF NEW.title != OLD.title
  THEN
    DELETE FROM predb_hashes WHERE hash IN ( 
      UNHEX(md5(OLD.title)),
      UNHEX(md5(md5(OLD.title))),
      UNHEX(sha1(OLD.title)),
`
here

`
      UNHEX(MD5(CONCAT(OLD.title, OLD.requestid))), 
      UNHEX(MD5(CONCAT(OLD.title, OLD.requestid, OLD.requestid)))
`
^^
`
    ) AND predb_id = OLD.id;
    INSERT INTO predb_hashes (hash, predb_id) VALUES 
      ( UNHEX(MD5(NEW.title)), NEW.id ),
      ( UNHEX(MD5(MD5(NEW.title))), NEW.id ),
      ( UNHEX(SHA1(NEW.title)), NEW.id ),
      ( UNHEX(MD5(CONCAT(NEW.title, NEW.requestid))), NEW.id ),
      ( UNHEX(MD5(CONCAT(NEW.title, NEW.requestid, NEW.requestid))), NEW.id );
  END IF;
END
`

**Comment by jangrewe** [comment]
Ah, i was looking at the delete trigger, not the delete part of the update trigger! 😁

**Comment by niel** [comment]
@jangrewe if those triggers have met with Bart39's approval, I'll try to find time to refresh my memory of how that stuff works. It'll take a little while at least. If you, or @Bart39, wants to make a PR in the meantime it will speed the process up.

**Comment by Bart39** [comment]
I'll add a PR, needs triggers updating as well as scripting updating from existing records

**Comment by niel** [comment]
Thanks @Bart39

**Comment by DariusIII** [comment]
hash column of predb_hashes table must be increased too from VARBINARY(20) to VARBINARY(40), otherwise insertion of new data will fail.

**Comment by jangrewe** [comment]
Thanks @DariusIII, i've changed that for my DB with
```
ALTER TABLE predb_hashes CHANGE COLUMN hash hash VARBINARY(40) NOT NULL DEFAULT '0x';
```
and ran the two INSERTs again.

**Comment by tommytyker** [comment]
This is great - already added the triggers to my local install. Thanks stravager for the discovery. Still the problem with releases that add additional text to their names, for example XYZ-postbot or XYZ-Obfuscated in the a.b.etc and bloaf groups respectively. Even with those 2 additional methods above (adding the additional text), these -XXX are not getting the names (tried against subject, filename)

**Comment by jangrewe** [comment]
As somebody somewhere mentioned, that hashing scheme seems to have been abandoned again already.
If somebody wants to get rid of those hashes now, i thought the easiest would be to truncate the `predb_hashes` table and just recreate the three defaults:
```
TRUNCATE TABLES predb_hashes;
INSERT IGNORE INTO predb_hashes (hash, predb_id) SELECT UNHEX(MD5(title)), id from predb;
INSERT IGNORE INTO predb_hashes (hash, predb_id) SELECT UNHEX(MD5(MD5(title))), id from predb;
INSERT IGNORE INTO predb_hashes (hash, predb_id) SELECT UNHEX(SHA1(title)), id from predb;
```
Took about 5 minutes for ~9M predb records.

**Comment by houseofdreams** [comment]
Any news on the new scheme?

**Comment by Bart39** [comment]
As above it’s been abandoned already

**Comment by houseofdreams** [comment]
I will rephrase :) 

Any news on a new scheme?

**Comment by jangrewe** [comment]
Then i'll also rephrase what @Bart39 said: 

The poster(s) who used to use it don't use it anymore, so there's no point in adding additional hashes for this scheme either.

**Comment by houseofdreams** [comment]
I'm not referring to any previously existing methods, including what was discussed in this topic, I just wanted to know wat the NEW way of decrypting is, but I assume only a few people will know this and are not willing to share :)

**Comment by jangrewe** [comment]
If you're looking for the NEW way of decrypting, what is that NEW way of encryption? Have you found any other recent schemas?

Hashing has nothing to do with encryption, by the way...
