### ISSUE TITLE
Tmux's IRC Scrapper not fully working

### ISSUE THREAD

**Issue by ghost** [nZEDb/nZEDb#2495]
Hey,

If I run a strace on the ircscraper pid I can see quite a lot of 

> sendto(3, "A\1\0\0\3INSERT INTO `predb` (`title"..., 325, MSG_DONTWAIT, NULL, 0) = 325
> poll([{fd=3, events=POLLIN|POLLERR|POLLHUP}], 1, 1471228928) = 1 ([{fd=3, revents=POLLIN}])
> recvfrom(3, "W\0\0\1\377\f\5#22007Incorrect datetime "..., 117, MSG_DONTWAIT, NULL, NULL) = 91

During these no text is displayed on the tmux pane. 

This only seems to affect INSERTS, UPDATES seem ok.

I am guessing this is unique to my setup but:
```
 php verify_time_settings.php 
Looks like all your dates/times are good.
```

     ```
  Table: predb
Create Table: CREATE TABLE `predb` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  `title` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `nfo` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `size` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `category` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `created` timestamp NOT NULL DEFAULT current_timestamp() COMMENT 'Unix time of when the pre was created, or first noted by the system',
  `updated` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE current_timestamp() COMMENT 'Unix time of when the entry was last updated',
  `source` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `requestid` int(10) unsigned NOT NULL DEFAULT 0,
  `groups_id` int(11) unsigned NOT NULL DEFAULT 0 COMMENT 'FK to groups.id',
  `nuked` tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Is this pre nuked? 0 no 2 yes 1 un nuked 3 mod nuked',
  `nukereason` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'If this pre is nuked, what is the reason?',
  `files` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'How many files does this pre have ?',
  `filename` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `searched` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ix_predb_title` (`title`),
  KEY `ix_predb_nfo` (`nfo`),
  KEY `ix_predb_source` (`source`),
  KEY `ix_predb_requestid` (`requestid`,`groups_id`),
  KEY `ix_predb_filename` (`filename`),
  KEY `ix_predb_searched` (`searched`),
  FULLTEXT KEY `ft_predb_filename` (`filename`),
  FULLTEXT KEY `ix_predb_filename_ft` (`filename`)
) ENGINE=InnoDB AUTO_INCREMENT=2104206 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci ROW_FORMAT=DYNAMIC

```

Release v0.7.3.3

**Comment by niel** [comment]
What errors, if any, are you seeing in PHP logs?

**Comment by hansenhans** [comment]
I think I have the same problem. I only see `...[Updated Pre]...` in the IRCScraper tab in tmux. The znc log shows many more entries and when I run `scrape.php true false true` I also see all these entries, but most of them also don't get inserted into the predb table.

I'm checking with phpmyadmin and sort by the created column. I only see new entries from the source requestWEB (which seem to come from somewhere else) and entries with a date/tame in the updated column.

I only see these 2 lines repeating from time to time

> 
> [30-Jul-2017 23:40:49 Europe/London] PHP Notice:  Only variables should be assigned by reference in /usr/share/php/PEAR.php on line 601
> [30-Jul-2017 23:40:54 Europe/London] PHP Notice:  Undefined index: backfill in /var/www/html/nZEDb/nzedb/TmuxRun.php on line 337

The line regarding backfilling is from another problem I didn't report yet and I don't know whether the other line is related to the problem,

 How else can I help debugging this problem?

**Comment by niel** [comment]
@hansenhans neither of those are related to IRCScraper. The first is in PEAR which is an extension to PHP. You can edit the line it complains about, and remove the first '&'. It will also complain about another one a few lines down.

**Comment by hansenhans** [comment]
Last night I got this error message in php_errors.log

> [31-Jul-2017 04:38:56 Europe/London] PHP Warning:  Error while sending QUERY packet. PID=27958 in /var/www/html/nZEDb/libraries/lithium/data/source/database/adapter/MySql.php on line 404
> [31-Jul-2017 04:38:56 Europe/London] PHP Fatal error:  Uncaught lithium\data\model\QueryException: SELECT * FROM `predb` AS `Predb` WHERE `Predb`.`title` = 'Xtreme.Waterparks.S07E07.Sweet.Falls.HDTV.x264-CRiMSON' LIMIT 1;: MySQL server has gone away in /var/www/html/nZEDb/libraries/lithium/data/source/Database.php:1601
> Stack trace:
> #0 /var/www/html/nZEDb/libraries/lithium/aop/Filters.php(231): lithium\data\source\Database->lithium\data\source\{closure}(Array)
> #1 /var/www/html/nZEDb/libraries/lithium/data/source/Database.php(1602): lithium\aop\Filters::run(Object(app\extensions\adapter\data\source\database\MySql), '_error', Array, Object(Closure))
> #2 /var/www/html/nZEDb/libraries/lithium/data/source/database/adapter/MySql.php(406): lithium\data\source\Database->_error('SELECT * FROM `...')
> #3 /var/www/html/nZEDb/libraries/lithium/aop/Filters.php(231): lithium\data\source\database\adapter\MySql->lithium\data\source\database\adapter\{closure}(Array)
> #4 /var/www/html/nZEDb/libraries/lithium/data/source/database/adapter/MySql.php(409): lithium\aop\Filters::run(Object( in /var/www/html/nZEDb/libraries/lithium/data/source/Database.php on line 1601
> 

Is this related to the problem or was there just a temporarily problem with the MySQL server?

**Comment by DariusIII** [comment]
Just a MySQL server problem.

**Comment by hansenhans** [comment]
I tried a few more things:

Downgraded PHP from 7.0 to 5.6 makes no difference. When running
`php /var/www/html/nZEDb/misc/testing/Tests/verify_time_settings.php`
I get

> These are the settings in your php.ini files:
cat: /etc/php5/cli/php.ini: No such file or directory
CLI PHP timezone : 
cat: /etc/php5/apache2/php.ini: No such file or directory
apache2 timezone : 
The various dates/times:
System time      : Wed  2 Aug 16:48:20 BST 2017
MYSQL time       : Wed Aug 02 16:48:20 BST 2017
PHP time         : Wed Aug 02 16:48:20 BST 2017
Looks like you have 1 or more dates/times set wrong.

The errors about the missing php.ini files is due to the path to them hardcoded into verify_time_settings.php. When I set a symbolic link /etc/php5 -> /etc/php/5.6 these errors dissappears. 

Even though my timezones are set correctly, the format is slightly different between system time and MYSQL/PHP time. Could this be the problem? I'm running Ubuntu 16.04 if that matters.

Next I ran strace like the OP and get also the "Incorrect datetime" errors.

> recvfrom(6, ":Rara73!~Rara73@i.m.very.crazy P"..., 8192, MSG_DONTWAIT, NULL, NULL) = 316
> sendto(4, "r\0\0\0\3SELECT * FROM `predb` AS `P"..., 118, MSG_DONTWAIT, NULL, 0) = 118
> poll([{fd=4, events=POLLIN|POLLERR|POLLHUP}], 1, 1471228928) = 1 ([{fd=4, revents=POLLIN}])
> recvfrom(4, "\1\0\0\1\17)\0\0\2\3def\5nzedb\5Predb\5predb\2"..., 201, MSG_DONTWAIT, NULL, NULL) = 201
> poll([{fd=4, events=POLLIN|POLLERR|POLLHUP}], 1, 1471228928) = 1 ([{fd=4, revents=POLLIN}])
> recvfrom(4, "\3def\5nzedb\5Predb\5predb\10category\10"..., 332, MSG_DONTWAIT, NULL, NULL) = 332
> poll([{fd=4, events=POLLIN|POLLERR|POLLHUP}], 1, 1471228928) = 1 ([{fd=4, revents=POLLIN}])
> recvfrom(4, "\0\0/\0\0\f\3def\5nzedb\5Predb\5predb\5nuk"..., 332, MSG_DONTWAIT, NULL, NULL) = 297
> sendto(4, "H\1\0\0\3INSERT INTO `predb` (`title"..., 332, MSG_DONTWAIT, NULL, 0) = 332
> poll([{fd=4, events=POLLIN|POLLERR|POLLHUP}], 1, 1471228928) = 1 ([{fd=4, revents=POLLIN}])
> recvfrom(4, "W\0\0\1\377\f\5#22007Incorrect datetime "..., 35, MSG_DONTWAIT, NULL, NULL) = 35
> poll([{fd=4, events=POLLIN|POLLERR|POLLHUP}], 1, 1471228928) = 1 ([{fd=4, revents=POLLIN}])
> recvfrom(4, "ue: '-0001-11-30 00:00:00' for c"..., 332, MSG_DONTWAIT, NULL, NULL) = 56
> poll([{fd=6, events=POLLIN|POLLERR|POLLHUP}], 1, 180000) = 1 ([{fd=6, revents=POLLIN}])
> recvfrom(6, ":Rara73!~Rara73@i.m.very.crazy P"..., 8192, MSG_DONTWAIT, NULL, NULL) = 125
> sendto(6, "PING toronto.on.ca.synirc.net\r\n", 31, MSG_DONTWAIT, NULL, 0) = 31
> poll([{fd=6, events=POLLIN|POLLPRI|POLLERR|POLLHUP}], 1, 0) = 0 (Timeout)
> poll([{fd=6, events=POLLIN|POLLPRI|POLLERR|POLLHUP}], 1, 0) = 0 (Timeout)
> poll([{fd=6, events=POLLIN|POLLERR|POLLHUP}], 1, 180000) = 1 ([{fd=6, revents=POLLIN}])
> recvfrom(6, ":irc.znc.in PONG irc.znc.in toro"..., 8192, MSG_DONTWAIT, NULL, NULL) = 54
> poll([{fd=6, events=POLLIN|POLLERR|POLLHUP}], 1, 180000) = 1 ([{fd=6, revents=POLLIN}])
> recvfrom(6, ":Rara73!~Rara73@i.m.very.crazy P"..., 8192, MSG_DONTWAIT, NULL, NULL) = 324
> sendto(4, "\232\0\0\0\3SELECT * FROM `predb` AS `P"..., 158, MSG_DONTWAIT, NULL, 0) = 158
> poll([{fd=4, events=POLLIN|POLLERR|POLLHUP}], 1, 1471228928) = 1 ([{fd=4, revents=POLLIN}])
> recvfrom(4, "\1\0\0\1\17)\0\0\2\3def\5nzedb\5Predb\5predb\2"..., 276, MSG_DONTWAIT, NULL, NULL) = 276
> poll([{fd=4, events=POLLIN|POLLERR|POLLHUP}], 1, 1471228928) = 1 ([{fd=4, revents=POLLIN}])
> recvfrom(4, "redb\7created\7created\f?\0\23\0\0\0\7\241\4\0\0"..., 332, MSG_DONTWAIT, NULL, NULL) = 332
> poll([{fd=4, events=POLLIN|POLLERR|POLLHUP}], 1, 1471228928) = 1 ([{fd=4, revents=POLLIN}])
> recvfrom(4, "redb\nnukereason\nnukereason\f!\0\375\2\0"..., 332, MSG_DONTWAIT, NULL, NULL) = 222
> sendto(4, "=\1\0\0\3INSERT INTO `predb` (`title"..., 321, MSG_DONTWAIT, NULL, 0) = 321
> poll([{fd=4, events=POLLIN|POLLERR|POLLHUP}], 1, 1471228928) = 1 ([{fd=4, revents=POLLIN}])
> recvfrom(4, "W\0\0\1\377\f\5#22007Incorrect datetime "..., 110, MSG_DONTWAIT, NULL, NULL) = 91
> poll([{fd=6, events=POLLIN|POLLERR|POLLHUP}], 1, 180000

How do I get strace to output everything? A lot things are just replaced by "...".

**Comment by hansenhans** [comment]
Ok, I increase the strsize of strace to 100 and get the following.

> recvfrom(6, ":Rara73!~Rara73@i.m.very.crazy PRIVMSG #nZEDbPRE :NEW: \0033[\17DT:\00310 2017-08-02 16:27:33\17\0033]\17 \0033[\17TT:\0031"..., 8192, MSG_DONTWAIT, NULL, NULL) = 352
sendto(4, "\262\0\0\0\3SELECT * FROM `predb` AS `Predb` WHERE `Predb`.`title` = 'Der.Hundetraier.Lucky.Dogs.mit.Brando"..., 182, MSG_DONTWAIT, NULL, 0) = 182
poll([{fd=4, events=POLLIN|POLLERR|POLLHUP}], 1, 1471228928) = 1 ([{fd=4, revents=POLLIN}])
recvfrom(4, "\1\0\0\1\17)\0\0\2\3def\5nzedb\5Predb\5predb\2id\2id\f?\0\v\0\0\0\3#B\0\0\0/\0\0\3\3def\5nzedb\5Predb\5predb\5title\5title\f!\0\375", 92, MSG_DONTWAIT, NULL, NULL) = 92
poll([{fd=4, events=POLLIN|POLLERR|POLLHUP}], 1, 1471228928) = 1 ([{fd=4, revents=POLLIN}])
recvfrom(4, "\2\0\0\375\5@\0\0\0+\0\0\4\3def\5nzedb\5Predb\5predb\3nfo\3nfo\f!\0\375\2\0\0\375\10@\0\0\0-\0\0\5\3def\5nzedb\5Predb\5predb\4size\4size\f!\0\226\0\0\0\375"..., 332, MSG_DONTWAIT, NULL, NULL) = 332
poll([{fd=4, events=POLLIN|POLLERR|POLLHUP}], 1, 1471228928) = 1 ([{fd=4, revents=POLLIN}])
recvfrom(4, "f\5nzedb\5Predb\5predb\trequestid\trequestid\f?\0\n\0\0\0\3)@\0\0\0007\0\0\v\3def\5nzedb\5Predb\5predb\tgroups_id\tgroups_id\f?"..., 332, MSG_DONTWAIT, NULL, NULL) = 332
poll([{fd=4, events=POLLIN|POLLERR|POLLHUP}], 1, 1471228928) = 1 ([{fd=4, revents=POLLIN}])
recvfrom(4, "\0\0\20\3def\5nzedb\5Predb\5predb\10searched\10searched\f?\0\1\0\0\0\1\t@\0\0\0\5\0\0\21\376\0\0\2\0\5\0\0\22\376\0\0\2\0", 332, MSG_DONTWAIT, NULL, NULL) = 74
sendto(4, "Y\1\0\0\3INSERT INTO `predb` (`title`, `created`, `updated`, `source`, `requestid`, `groups_id`, `nuked`"..., 349, MSG_DONTWAIT, NULL, 0) = 349
poll([{fd=4, events=POLLIN|POLLERR|POLLHUP}], 1, 1471228928) = 1 ([{fd=4, revents=POLLIN}])
recvfrom(4, "W\0\0\1\377\f\5#22007Incorrect datetime value: '-0001-11-30 00:00:00' for column 'updated' at row 1", 258, MSG_DONTWAIT, NULL, NULL) = 91
poll([{fd=6, events=POLLIN|POLLERR|POLLHUP}], 1, 180000) = 1 ([{fd=6, revents=POLLIN}])
recvfrom(6, ":Rara73!~Rara73@i.m.very.crazy PRIVMSG #nZEDbPRE :NEW: \0033[\17DT:\00310 2017-08-02 16:27:33\17\0033]\17 \0033[\17TT:\0031"..., 8192, MSG_DONTWAIT, NULL, NULL) = 351
sendto(4, "\261\0\0\0\3SELECT * FROM `predb` AS `Predb` WHERE `Predb`.`title` = 'Der.Hundetraier.Lucky.Dogs.mit.Brando"..., 181, MSG_DONTWAIT, NULL, 0) = 181
poll([{fd=4, events=POLLIN|POLLERR|POLLHUP}], 1, 1471228928) = 1 ([{fd=4, revents=POLLIN}])
recvfrom(4, "\1\0\0\1\17)\0\0\2\3def\5nzedb\5Predb\5predb\2id\2id\f?\0\v\0\0\0\3#B\0\0\0/\0\0\3\3def\5nzedb\5Predb\5predb\5title\5title\f!\0\375\2\0\0\375\5@\0\0"..., 167, MSG_DONTWAIT, NULL, NULL) = 167
poll([{fd=4, events=POLLIN|POLLERR|POLLHUP}], 1, 1471228928) = 1 ([{fd=4, revents=POLLIN}])
recvfrom(4, "b\5predb\4size\4size\f!\0\226\0\0\0\375\0\0\0\0\0005\0\0\6\3def\5nzedb\5Predb\5predb\10category\10category\f!\0\375\2\0\0\375\0\0\0\0\0003\0\0\7\3def\5nzed"..., 332, MSG_DONTWAIT, NULL, NULL) = 332
poll([{fd=4, events=POLLIN|POLLERR|POLLHUP}], 1, 1471228928) = 1 ([{fd=4, revents=POLLIN}])
recvfrom(4, "edb\tgroups_id\tgroups_id\f?\0\v\0\0\0\3!@\0\0\0/\0\0\f\3def\5nzedb\5Predb\5predb\5nuked\5nuked\f?\0\1\0\0\0\1\1\0\0\0\0009\0\0\r\3def\5nzed"..., 332, MSG_DONTWAIT, NULL, NULL) = 331
sendto(4, "X\1\0\0\3INSERT INTO `predb` (`title`, `created`, `updated`, `source`, `requestid`, `groups_id`, `nuked`"..., 348, MSG_DONTWAIT, NULL, 0) = 348
poll([{fd=4, events=POLLIN|POLLERR|POLLHUP}], 1, 1471228928) = 1 ([{fd=4, revents=POLLIN}])
recvfrom(4, "W\0\0\1\377\f\5#22007Incorrect datetime value: '-0001-11-30 00:00:00' for column 'updated' at row 1", 332, MSG_DONTWAIT, NULL, NULL) = 91

There is surely something wrong with this line

...Incorrect datetime value: '-0001-11-30 00:00:00'...

**Comment by ghost** [comment]
Fixed by adding 
`sql_mode = "ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
`

under [mysqld] in /etc/mysql/my.cnf

**Comment by hansenhans** [comment]
you're a genius ;-)

But it's rather a workaround than a fix, isn't it?

**Comment by niel** [comment]
@hansenhans the reason for the hard coded PHP paths is because we tell you to use the PPA that uses those paths. Looks like you used the older package.

**Comment by hansenhans** [comment]
No, I use ondrej's PPA. Since a few versions the path to the php.ini is /etc/php/x.x/{cli|apache2}/php.ini, but the hard coded script has /etc/php5/{cli|apache2}/php.ini. At least that's how it is in Ubuntu 16.04. Shouldn't be the correct path in a config file somewhere? Maybe it's better to read it from there.

**Comment by niel** [comment]
@hansenhans what is your SQL_MODE set to?

**Comment by niel** [comment]
@hansenhans that would be the old version of Ondrej's PPA. His newer one installs to php/5.6, php/7.0, php/7.1 to allow multiple versions of PHP installed

**Comment by hansenhans** [comment]
sql_mode was not set, but now I set it to  "ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION" as slug1982 suggested and it works. But I wonder whether it solves the real problem or whether it's just a workaround.

Regarding the path of the php.ini, that was exactly what I said. /etc/php5/ is hard coded in the php script, but now the correct path is /etc/php/x.x/ eg. /etc/php/5.6 etc.

**Comment by Wally73** [comment]
its due mysql 5.7 (sqlmode)

**Comment by niel** [comment]
If sql_mode was not set, it will use the defaults for whichever DBMS is used. MySQL is known to be too restrictive and they keep adding more restrictions, which is why we no longer support it directly. i.e. if you want to use MySQL instead of the recommended MariaDB, you need to know how to administrate your way out of these problems ;-)

As for the hard-coded path, I'll try to get that fixed soon.

**Comment by hansenhans** [comment]
I'm using an up-to-date MariaDB as per recommendation

nzedb@nzedb:~$ mysql --version
mysql  Ver 15.1 Distrib 10.2.7-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**Comment by niel** [comment]
Check the default SQL_MODE for that version. I haven't used 10.2 yet so have no idea if they changed anything significant.
