### ISSUE TITLE
can't get past step2

### ISSUE THREAD

**Issue by phynias** [nZEDb/nZEDb#2496]
i have read all the other posts about the fixes when you get  the error:
"• Unable to create database and data. Check permissions of your mysql user."

and i have tried them all.
-the main directory and all subs are set to 777.
-i set secure-file-priv = "" and the exact dir of the tsv files, both did not work.
-checked and rechecked all the mysql grant commands and did a flush privs

this is on centos so no apparmor and selinux is disabled.

any help would be appreciated. thanks!

**Comment by Wally73** [comment]
i think you forget the grant file part

**Comment by phynias** [comment]
nope. i did that.

**Comment by phynias** [comment]
one thing i did find. i was able to extract the LOAD INFILE sql queries and i ran a several by hand. 
they execute fine, with no errors, but nothing is loaded into the tables.


MariaDB [nzedb]> LOAD DATA INFILE "/var/www/nZEDb/resources/db/schema/data/10-countries.tsv" IGNORE INTO TABLE `countries` FIELDS TERMINATED BY "\t" LINES TERMINATED BY "\r\n" IGNORE 1 LINES (id, iso3, country);
Query OK, 0 rows affected (0.00 sec)
Records: 0  Deleted: 0  Skipped: 0  Warnings: 0

MariaDB [nzedb]> select * from country;
ERROR 1146 (42S02): Table 'nzedb.country' doesn't exist
MariaDB [nzedb]> select * from countries;
Empty set (0.00 sec)

**Comment by phynias** [comment]
so i messed with the load command and when i changed the LINES TERMINATED BY to "\n" it works.

**Comment by phynias** [comment]
yup in install/step2.php i changed the 'LINES TERMINATED' then ran step2 again and it worked.

**Comment by Wally73** [comment]
glad you solved it ;)

**Comment by niel** [comment]
That's not solved, just worked-around. Our *.tsv files are terminated by \r\n deliberately. If they're not being read in by the normal code you have a problem somewhere that needs to be resolved, changing the code like that only hides the problem.
Check the *.tsv files in a text editor, if the lines are terminated with only \r then your git install probably converted them, there is a setting to do that, which it should not have done.
