### ISSUE TITLE
Amazon lookups crash upon a certain title lookup

### ISSUE THREAD

**Issue by langerak** [nZEDb/nZEDb#2497]
Hi,

I'm running the latest nZEDb on a Ubuntu 16.04.2 server. While having the whole machine setup and working as expected, there seems to be a strange issue ongoing.

Amazon lookups are working as expected as I have had several console, book and music lookups via Amazon but it now seems to "crash" at one particular release due to missing settings:

```
root@indexer:~# php /var/www/nZEDb/misc/update/nix/multiprocessing/postprocess.php ama
No book releases to process for category id 3030
No book releases to process for category id 7020
No book releases to process for category id 7040
No book releases to process for category id 7060
No console releases to process.
Processing 15 games release(s).
Looking up: 002 (PC)
PHP Fatal error:  Uncaught Exception: Unable to fetch setting from Db! in /var/www/nZEDb/app/models/Settings.php:257
Stack trace:
#0 /var/www/nZEDb/nzedb/Steam.php(149): app\models\Settings::value('APIs.steam_apps...')
#1 /var/www/nZEDb/nzedb/Steam.php(106): nzedb\Steam->populateSteamAppsTable()
#2 /var/www/nZEDb/nzedb/Games.php(503): nzedb\Steam->search('002')
#3 /var/www/nZEDb/nzedb/Games.php(803): nzedb\Games->updateGamesInfo(Array)
#4 /var/www/nZEDb/nzedb/processing/PostProcess.php(186): nzedb\Games->processGamesReleases()
#5 /var/www/nZEDb/nzedb/libraries/Forking.php(882): nzedb\processing\PostProcess->processGames()
#6 /var/www/nZEDb/nzedb/libraries/Forking.php(162): nzedb\libraries\Forking->processSingle()
#7 /var/www/nZEDb/nzedb/libraries/Forking.php(107): nzedb\libraries\Forking->getWork()
#8 /var/www/nZEDb/misc/update/nix/multiprocessing/postprocess.php(22): nzedb\libraries\Forking->processWorkType('postProcess_ama', Array)
#9 {main}
  thrown in /var/www/nZEDb/app/models/Settings.php on line 257
```

If there are any items that have to be looked up before starting the game releases everything seems to be working, so at that point the lookups are working. It only crashes at this specific one. It may not be a bug, but at this point I don't know how to proceed either. Is there a way to remove this release or correct the missing settings?

**Comment by niel** [comment]
Looks like you're missing a setting in your database. Look in your settings table to be sure that the SQL patches 0476 and 0478 have been applied correctly.

**Comment by langerak** [comment]
Cool! I've imported the 2 sql files into the database and now it has immediately populated around 45.000 Steam apps and the lookups are continuing as usual!

Thanks very much for the quick help! Will close the issue now.
