### ISSUE TITLE
predb_import script stops trying to import a particular day's data

### ISSUE THREAD

**Issue by kaibosh** [nZEDb/nZEDb#2502]
###Expected behaviour
Lovely filled up predb table

###Actual behaviour
predb import script stops trying to import one particular day of pre's

nzedb:/var/www/nZEDb $php /var/www/nZEDb/cli/data/predb_import_daily_batch.php progress local true
 [...]
Skipping dump 1498220875, as your minimum unix time argument is 1498566512
Skipping dump 1498307285, as your minimum unix time argument is 1498566512
Skipping dump 1498393694, as your minimum unix time argument is 1498566512
Skipping dump 1498480102, as your minimum unix time argument is 1498566512
Skipping dump 1498566511, as your minimum unix time argument is 1498566512
Downloading: https://raw.githubusercontent.com/nZEDb/nZEDbPre_Dumps/master/dumps/1481552532/1498652924_predb_dump.csv.gz
Info: Clearing import table
Info: Deleting any records where title <=8 from Temporary Table
Info: Inserting records from temporary table into predb table
nzedb:/var/www/nZEDb $

In the error logs:
[06-Aug-2017 17:40:47 Europe] PHP Fatal error:  Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry ':\x19\xCE.N\x90\xAA\xE8\xEFm\xF54=\xB0\xD32' for key 'PRIMARY' in /mnt/local/nZEDb/nzedb/db/PreDb.php:122
Stack trace:
#0 /mnt/local/nZEDb/nzedb/db/PreDb.php(122): PDOStatement->execute()
#1 /mnt/local/nZEDb/cli/data/predb_import_daily_batch.php(205): nzedb\db\PreDb->executeInsert()
#2 {main}
  thrown in /mnt/local/nZEDb/nzedb/db/PreDb.php on line 122

It's trying to import the dump from 2017-06-28 which is around the time i used predb_export/import to "sanitize" a rather old predb table. So it's possible, that upset the daily imports.

Looked over the predb_import table but don't see anything obvious, and those weird escaped characters dont give me much to go on.

**Comment by niel** [comment]
You have a duplicate entry, obviously. I'll have to check the code, but as I recall duplicates should be ignored, so I have no idea how this is happening.
I'll look into the import code.

**Comment by Bart39** [comment]
Check current auto_increment value versus highest ID you have.
It's failing on duplicate primary key (ID)

**Comment by kaibosh** [comment]
With the scripts running (i.e. the scraper) I checked the auto_increment and it was fine as it was one higher than my highest ID.

To be sure, I stopped the scripts (incl. scraper) then attempted the daily import. Each time I try the daily import script it increases the auto_increment by one before failing. Now it looks like:

`MariaDB [nzedb]> SELECT `AUTO_INCREMENT` FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'nzedb' AND TABLE_NAME = 'predb';
+----------------+
| AUTO_INCREMENT |
+----------------+
|        8717511 |
+----------------+
1 row in set (0.00 sec)

MariaDB [nzedb]> select id from predb order by id desc limit 1;
+---------+
| id      |
+---------+
| 8717508 |
+---------+
1 row in set (0.00 sec)

MariaDB [nzedb]> 
`

**Comment by CollinChaffin** [comment]
I too am seeing some strange behavior with the predb script.  Not sure if it could be the same root cause, but mine does NOT wind up actually populating anything, and the even stranger thing is the output and the error log.

First, the run output:
````
bash-4.3# php /var/www/nZEDb/cli/data/predb_import_daily_batch.php progress local true
Downloading: https://raw.githubusercontent.com/nZEDb/nZEDbPre_Dumps/master/dumps/1404152742/1404152742_predb_dump.csv.gz
Info: Clearing import table
bash-4.3#
````
As you can see, no real "error" of ANY kind is even being returned.  Just the table clear.....strange.

Then, when I look in the cli error log, it does log (something) for the run seeming to indicate a strange syntaxed db access error:
````
[20-Sep-2017 21:03:07 America/Chicago] PHP Fatal error:  Uncaught PDOException: SQLSTATE[28000]: Invalid authorization specification: 1045 Access denied for user 'nzedb'@'%' (using password: YES) in /var/www/nZEDb/nzedb/db/PreDb.php:141
Stack trace:
#0 /var/www/nZEDb/nzedb/db/PreDb.php(141): PDOStatement->execute(Array)
#1 /var/www/nZEDb/cli/data/predb_import_daily_batch.php(189): nzedb\db\PreDb->executeLoadData(Array)
#2 {main}
  thrown in /var/www/nZEDb/nzedb/db/PreDb.php on line 141
````
Line 141 in predb just being the return line but I do see the pending TODO right above it related to a "local" run like this.  So since my other db activities are certainly working (full runs working fine other than predb), is there some underlying issue with the predb causing both of these issues, or are they definitely not related?

Thanks!

**Comment by niel** [comment]
@CollinChaffin which branch, which version/commit?
