### ISSUE TITLE
nZEDb_MAX_PAGER_RESULTS still in use?

### ISSUE THREAD

**Issue by cytec** [nZEDb/nZEDb#2503]
Seems like `nZEDb_MAX_PAGER_RESULTS` isn't working as it should be.

### Expected behaviour
every page using paginator should show a max of `nZEDb_MAX_PAGER_RESULTS/ITEMS_PER_PAGE ` Pages  

### Actual behaviour

Seems like only the Search respects `nZEDb_MAX_PAGER_RESULTS`. 
Browsing Releases still shows me 2k+ Pages instead of `nZEDb_MAX_PAGER_RESULTS/ITEMS_PER_PAGE ` Pages  

### Steps to reproduce the behaviour

set `nZEDb_MAX_PAGER_RESULTS` to `1250` and `ITEMS_PER_PAGE` to `50` should produce a max of 25 Pages (works when searching but nowhere else)

**Comment by niel** [comment]
Can you be more specific with the page you're looking at? The URL without the domain name is fine.
And what template are you using?

**Comment by cytec** [comment]
nevermind... was working on the wrong branch. Sorry!
