### ISSUE TITLE
Can no longer reach any path with /movies

### ISSUE THREAD

**Issue by ialexpw** [nZEDb/nZEDb#2506]
### Expected behaviour
Browse to any URL with /movies in e.g.
/movies
/movies?t=2060

### Actual behaviour
I browse to any URL with /movies in and I get a status 500 internal error.

### Steps to reproduce the behaviour
I just ran the latest update using ./zed update all - was running fine for the last few months up until this moment

Seems to be happening on every theme I try, I can browse to /browse?t=2060 and see the listings OK. I've tried overwriting my own files manually after to see if the update got confused, still no luck.

Just for info;

nZEDb git:(0.x) ✗ ./zed update nzedb
Already up-to-date.
Checking database version...
Db: 482,        File: 482

**Comment by Wally73** [comment]
debug log? error log? 

i see nothing wrong on my end (in gamma)

**Comment by ialexpw** [comment]
I don't seem to be getting much back in regards to logs.. this is happening on all themes for me (including Gamma) since I last ran the update.

I'll have another look when I can get access to it again shortly and post any logs I can grab.

**Comment by niel** [comment]
did you originally update with: ./zed update all or did you git pull? If the latter try running: composer install

**Comment by ialexpw** [comment]
I did ./zed update all previously - also tried a composer install with no luck. :-(

```
nZEDb git:(0.x) ✗ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating optimized autoload files
> nzedb\build\Composer::postInstallCmd
Updating git hooks... done
```

**Comment by moloquin** [comment]
Ran into the same thing with latest update.  Check the permissions on your resources/tmp/ folder.  I had to open permissions to it then browsing movies worked.

**Comment by ialexpw** [comment]
@moloquin Thank you, that was it!
