### ISSUE TITLE
Blank page (added log file)

### ISSUE THREAD

**Issue by Assassin286** [nZEDb/nZEDb#2510]
The site always shows me a blank page, i can't do anything, i gave all permissions... I am on Raspberry Pi2

`Wed Aug 16 01:56:14.763330 2017] [:error] [pid 808] [client 192.168.2.105:57968] PHP Warning:  include(/var/www/nZEDb/libraries/lithium/core/Libraries.php): failed to$
[Wed Aug 16 01:56:14.763582 2017] [:error] [pid 808] [client 192.168.2.105:57968] PHP Warning:  include(): Failed opening '/var/www/nZEDb/libraries/lithium/core/Librar$
[Wed Aug 16 01:56:14.764037 2017] [:error] [pid 808] [client 192.168.2.105:57968] PHP Fatal error:  Uncaught exception 'ErrorException' with message 'Lithium core could not be found$

`

**Comment by niel** [comment]
Those log lines are truncated, so do not tell us anything usefull. Enable logging by copying the .../configuration/settings.example.php file to settings.php and editing that file to switch on logging.

**Comment by Assassin286** [comment]
Hey sry :D 
i saw some issues as mine here, with the same log.. and all users said something about a composer.. 
So i saw this in your wiki: https://github.com/nZEDb/nZEDb/wiki/Guides:-composer

and i did the first step.. cloning the git..

This is the error:

> Fatal error: Uncaught exception 'ErrorException' with message 'Lithium core could not be found. Check the value of LITHIUM_LIBRARY_PATH in /home/nzedb/www/nzedb.com/www/app/config/bootstrap/libraries.php. It should point to the directory containing your /libraries directory.' in /home/nzedb/www/nzedb.com/www/app/config/bootstrap/libraries.php:72 Stack trace: #0 /home/nzedb/www/nzedb.com/www/app/config/bootstrap.php(32): require() #1 /home/nzedb/www/nzedb.com/www/app/webroot/index.php(21): require('/home/nzedb/www...') #2 {main} thrown in /home/nzedb/www/nzedb.com/www/app/config/bootstrap/libraries.php on line 72

**Comment by Assassin286** [comment]
Can be closed.. i fixed it with installing composer.. i totaly forgot this step
