### ISSUE TITLE
releases days behind

### ISSUE THREAD

**Issue by phynias** [nZEDb/nZEDb#2514]
for some reason my releases are days behind. nothing has changed, i just noticed today that nothing was updating.

 ./zed version all
Looking up Git tag version(s)
Hash: 07ce6f015cd67f8ad062377903fb10dbdc84f7c1
XML version: 0.7.4.0
Git version: 0.7.4.0
Looking up SQL patch version(s)
XML version: 482
DB version: 482

![capture](https://user-images.githubusercontent.com/10147213/29551959-0e84a240-86ca-11e7-96e0-16236cc51dea.PNG)

**Comment by DariusIII** [comment]
You use sequential mode and you are still downloading headers, so no wonder you have no releases added.

**Comment by phynias** [comment]
ok, that hasn't changed since i started and only 2 days ago did it start to do this.

**Comment by DariusIII** [comment]
Your header download queue is getting bigger and bigger, that is why it starts to slow down.

I do not know specs of your server, are tables myisam or innodb, etc. But i would highly recommend switching to full threaded tmux.

**Comment by phynias** [comment]
cpu: 2xL5520 2.26Ghz 
mem: 24GB 
innodb tables, 

i will try full threaded. as for it slowly getting behind, it has always been at the very most like an hour behind.

**Comment by DariusIII** [comment]
You need to tune your database, most likely.

**Comment by phynias** [comment]
would love suggestions.
```

symbolic-links=0
thread_concurrency = 8
query_cache_size = 32M
thread_cache_size = 8
myisam_sort_buffer_size = 64M
read_rnd_buffer_size = 8M
read_buffer_size = 2M
sort_buffer_size = 2M
table_open_cache = 512
max_allowed_packet = 1M
key_buffer_size = 384M
group_concat_max_len=8192
innodb_file_per_table
max_allowed_packet=128M

local-infile=1
secure-file-priv = ""
skip-external-locking

innodb_data_home_dir = /var/lib/mysql
innodb_log_group_home_dir = /var/lib/mysql
innodb_data_file_path = ibdata1:2000M;ibdata2:10M:autoextend
innodb_buffer_pool_size = 10G
innodb_additional_mem_pool_size = 20M
innodb_log_file_size = 3G
innodb_log_buffer_size = 8M
innodb_flush_log_at_trx_commit = 0
innodb_lock_wait_timeout = 50
innodb_flush_method=O_DIRECT
skip-name-resolve


```

**Comment by DariusIII** [comment]
This is my innodb section, for server with 32G of RAM:

innodb_log_file_size    = 1G
innodb_buffer_pool_size = 23G
innodb_buffer_pool_instances = 10
innodb_log_buffer_size  = 48M
innodb_file_per_table   = 1
innodb_file_format      = BARRACUDA
innodb_large_prefix     = 1
innodb_open_files       = 4000
innodb_io_capacity      = 2000
innodb_lru_scan_depth   = 256
innodb_read_io_threads  = 64
innodb_thread_concurrency = 0
innodb_write_io_threads = 64
innodb_flush_method     = O_DIRECT
innodb_flush_log_at_trx_commit = 2
innodb_lock_wait_timeout       = 250
transaction_isolation   = READ-COMMITTED
innodb_adaptive_hash_index = 0

**Comment by phynias** [comment]
thanks. i will give this all a try.
