### ISSUE TITLE
Please tag v0.7.4.1

### ISSUE THREAD

**Issue by slydetector** [nZEDb/nZEDb#2515]
###Expected behaviour
git tag for v0.7.4.1 exists

###Actual behaviourase 
git tag for v0.7.4.1 does not exist

###Steps to reproduce the behaviour
```
/git/nzedb ((HEAD detached at v0.7.4.0)) $ git fetch; git tag | tail  
v0.7.1.0  
v0.7.1.1  
v0.7.1.2  
v0.7.2.0  
v0.7.2.1  
v0.7.3.0  
v0.7.3.1  
v0.7.3.2  
v0.7.3.3  
v0.7.4.0 
```

**Comment by niel** [comment]
Apologies, I forgot to push the tags :-)
