### ISSUE TITLE
NZB feeding to indexers! Distributed nzb system, with sync or api/rss from our own BOT!

### ISSUE THREAD

**Issue by scriptzteam** [nZEDb/nZEDb#2516]

**Comment by Bart39** [comment]
Closed as spam

**Comment by scriptzteam** [comment]
Not spam just an offer how to find a content in better way :)

**Comment by niel** [comment]
It IS spam. Unrequested messages from a stranger is the definition of spam. Not to mention this is a place for issues with the software NOT self promotion.
