### ISSUE TITLE
No valid error description and no log location/details in provided app documentation for troubleshooting

### ISSUE THREAD

**Issue by CollinChaffin** [nZEDb/nZEDb#2517]
###Expected behaviour
Type a command and if an error occurs, receive some form of an error description.

###Actual behaviour
This output:
````
bash-4.3# cd /var/www/nZEDb/misc/update
bash-4.3# php update_binaries.php
Error: Unable to connect to usenet.
````

###Steps to reproduce the behaviour
1. Configure 2 working NNTP servers, all services start, can configure everything via PHP.
2. Receive the error with commands above
3. Read the "FAQ" found at:  https://github.com/nZEDb/nZEDb/wiki/FAQ's which does NOT list anything about even looking at an error log
4. (Optional) Hope you don't get past this and then have a backfill issue, because yet again this doc is 404: https://github.com/nZEDb/pre-info)

I've been a dev almost 30yrs myself and could never get away with this kind of lack of any real documentation so I'm here to ask If anyone could help shed some light into which log (I would hope) has captured the details behind the very nondescriptive "Error: Unable to connect to usenet" without me having to yet again have to dig through actual sourcecode to reverse engineer the program for something so basic.  I would really appreciate it!  TIA!

**Comment by CollinChaffin** [comment]
Let me start the answers myself after scouring myself.

First, THIS should be in the FAQ:  
````
If you have any error running your commands, the FIRST place you should look is here:

/var/www/nZEDb/resources/logs/php_errors_cli.log

````
Followed by:

````
If you receive any error in the aforementioned CLI log indicating TLS certificate errors such as in this example:

[19-Sep-2017 14:44:19 America/Chicago] PHP Warning:  failed loading cafile stream: `/etc/ssl/certs/cacert.pem' in /var/www/nZEDb/libs/PEAR/Net_NNTP/NNTP/Protocol/Client.php on line 514
[19-Sep-2017 14:44:19 America/Chicago] PHP Warning:  stream_socket_client(): Failed to enable crypto in /var/www/nZEDb/libs/PEAR/Net_NNTP/NNTP/Protocol/Client.php on line 514
[19-Sep-2017 14:44:19 America/Chicago] PHP Warning:  stream_socket_client(): unable to connect to tls://MY-NNTP-SERVER:563 (Unknown error) in /var/www/nZEDb/libs/PEAR/Net_NNTP/NNTP/Protocol/Cli
````
Even if you performed the following per the instructions:
````
sudo wget -P /etc/ssl/certs/ http://curl.haxx.se/ca/cacert.pem
chmod 744 /etc/ssl/certs/cacert.pem

````
That if you are in any standard docker container, __OR EVEN RESTARTING THE SERVICE VIA "MAKE START"__ (via the easy script) or of course a container restart (which I did NOT perform) still erroneously results (because of lack of volume mapping) the required cacert.pem being blown away and results in the above very vague error that is even called "uknown" in the log, despite it being obvious via other lines what has happened.

This HAS to be common to EVERY Docker user who has not done custom volume mapping, because I just ran through the few docker images/setup scripts out there and none of them worked around this.  I will be compiling a new docker image/build with nzedb setup automation and may even be basing it on photon to make it even lighter but either way will incorporate automating this persistence to avoid these "unknown" errors in nzedb.

I will close this issue now that I have confirmed that this is the root cause and will also come back to update one last time once I provide a more permanent solution.

**Comment by kaibosh** [comment]
You're welcome to update the FAQ.

Any issues with a docker image should be directed to its author.

**Comment by niel** [comment]
We only officially support the Ubuntu platform, all others are community supported.
The beginning of all of our 'official' docs tell you that you are expected to be able to do basic administration and troubleshooting of the components that make up this project, which is why looking at logs isn't mentioned in the FAQ. It seems you have the skills for this, as the error logs you refer to must be manually enabled (in .../configuration/settings.php).
