### ISSUE TITLE
simple-expanded.sh error

### ISSUE THREAD

**Issue by CollinChaffin** [nZEDb/nZEDb#2518]
###Expected behaviour
No errors

Line 47 is:
````
$PHP ${NZEDB_PATH}/postprocess.php all true
````
###Actual behaviour
Produces an error because "all" is for some reason not an accepted argument in postprocess.php, but is being called via:
````
LINE47:  $PHP ${NZEDB_PATH}/postprocess.php all true
````
###Steps to reproduce the behaviour
execute:
````
bash-4.3# php /var/www/nZEDb/misc/update/nix/multiprocessing/postprocess.php all false
````
Results in this output indicating the proper syntax was not used - also what appears when called via simple-expanded.sh:
````
First argument (mandatory):
ama => Do amazon processing, this does not use multi-processing, because of amazon API restrictions.
add => Do additional (rar|zip) processing.
mov => Do movie processing.
nfo => Do NFO processing.
sha => Do sharing processing, this does not using multi-processing.
tv  => Do TV processing.

Second argument (optional):
true|false => Only post-process renamed releases. This is for the mov|tv options.
````

**Comment by Wally73** [comment]
php /var/www/nZEDb/misc/update/nix/multiprocessing/postprocess.php (threaded)  isn't the same as 
/var/www/nZEDb/misc/update/postprocess.php (sequential) 
php /var/www/nZEDb/misc/update/postprocess.php all true works fine 

simple-expanded is a sequential script 
for threaded see treaded.sh see https://github.com/nZEDb/nZEDb/blob/0.x/misc/update/nix/screen/sequential/threaded.sh

**Comment by CollinChaffin** [comment]
Hmm it looked like it was missing releases so I tracked it back and through testing got the error, but I do see that the two scripts for some reason despite being the same don't both support "all".  That has to be a prior oversight on an update I would assume?  Whether threaded or sequential I would think the input params like the "all" one still would certainly want in both cases.

Also I wanted to ask I've been digging and now see where (through db "patching") the changing release regexes are added to the db table(s).  As both a question and suggestion, if you put something in place with instructions to allow the community to quickly add new patterns/collection info they have that you guys (and the app) do not - even if only an "addition" issue template then it would really help you guys grow this app similar to how other Open Source projects have grown.  iSpy is a great example when we put in place the template and methods to allow the community to add their camera details (commands, etc.) there was very quickly saw an explosion on the project and iSpy suddenly had support for THOUSANDS of cameras etc. and even blew past the commercial apps out there of supported cameras.  You want to increase the power of this tool exponentially - allow the community to build it's filters.

As a perfect example, I'm still staring at literally THOUSANDS of hashed releases right now from a specific poster from the last 48hrs (goes back many months, too) that could be regex'd and very easily supported by the app, but there is no clear path either 1. for me find the docs showing me how I could even further test and perfect my method (power of community open source), or 2. - any request/input procedures similar to other apps to basically help me add the filtering that I know about, and you may not.  It's frustrating because heck, many of these I just opened with plain old winrar I could rename by hand to the correct filename but all I can think is despite (most) others being renamed, these must be because they have been identified as "hashed" so they are simply being ignored?  Maybe in the future one new generic php manual run script to allow a user to give it a new user-provided regex, and match type (poster, filename, etc) and quickly run a simulated fixreleasenames run but based on their NEW method to ensure that you then get TESTED working additions. 
 Make sense?

I'll keep digging on this other issue to see if I can figure out why the threaded is missing releases but it seems similar to another post where the exact same thing was happening with many missed, so perhaps it's the same issue.  I'll let you know what i find.  Thanks!
