### ISSUE TITLE
predb_import_daily_batch.php not working

### ISSUE THREAD

**Issue by camarokris** [nZEDb/nZEDb#2519]
###Expected behaviour
running `php data/predb_import_daily_batch.php progress local true` in /var/www/nZEDb/cli should go out and fetch the latest predb file from https://github.com/nZEDb/nZEDbPre_Dumps/tree/master/dumps

###Actual behaviour
```[nzbadmin@17thstreet cli]$ pwd
/var/www/nZEDb/cli
[nzbadmin@17thstreet cli]$ php data/predb_import_daily_batch.php progress local true
Error: {"message":"API rate limit exceeded for xxx.xxx.xxx.xxx. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://developer.github.com/v3/#rate-limiting"}
[nzbadmin@17thstreet cli]$
```

I have run this randomly over the course of the day and it appears that something is hitting the API too often but there is nothing running on cron that i am aware of that would be hitting the github API enough to run out of API requests. 

###Steps to reproduce the behaviour
Refer to Actual Behaviour

I have created a bash script to get around using the API calls for the time being that I run daily. Feel free to check it out and use it if you like but I am curious if nZEDb makes regular calls to the github API enough to use the alotted request limit. 

https://github.com/camarokris/nZEDbPreDBUpdater

**Comment by CollinChaffin** [comment]
Hey @camarokris that is a very nicely written, and thorough script!  You may want to kick a wall after reading this, LOL.  It was posted, totally committed but to the DEV branch (You'd think this project was 20 yrs old from the number of branches - it's kind of a mess to find anything).  Here's the link where you can see what changed (although the way they are doing it will NOT get around the continued rate-limit issues so you may want to hang on to your script as well):
````
https://github.com/nZEDb/nZEDb/commit/1dae595e3bfb4d599e0c350ec4f8f74d3d1375bb
````
LINK:  https://github.com/nZEDb/nZEDb/commit/1dae595e3bfb4d599e0c350ec4f8f74d3d1375bb

*Note you need to follow the rabbit hole to find the issue actually lies in the class file PreDb.php above.  I did not need to make any changes to the predb_import_daily_batch.php.

Just back up your /var/www/nZEDb/nzedb/db/PreDb.php, and replace it with the above version committed back on 9/12, and it should again work for you.  I still had to wait a bit until my rate limiting cleared, but then for the first time in many months it returned to pulling down and successfully committing the daily predb dumps.
