### ISSUE TITLE
Composer DEV build results in outdated build 17 commits behind latest

### ISSUE THREAD

**Issue by CollinChaffin** [nZEDb/nZEDb#2521]
## Expected behaviour

Latest commit DEV branch build per the official instructions doc at:
````
https://github.com/nZEDb/nZEDb/blob/0.x/docs/Installing.md
````
Using these instructions:

![snag_9-23-2017_07-47-59a](https://user-images.githubusercontent.com/9301483/30773634-078c6d18-a03a-11e7-8012-c3d3adb14265.png)

## Actual behaviour

Here is the build log showing the same commit level as in stable being applied (Commit #6e24bb19ae58c056c4f0f7ca1488e05e9c101eb4 albeit correctly from DEV):
````
 $  composer clear-cache && composer create-project --stability dev --keep-vcs --prefer-source nZEDb/nZEDb

Do not run Composer as root/super user! See https://getcomposer.org/root for details
Cache directory does not exist (cache-vcs-dir):
Cache directory does not exist (cache-repo-dir):
Cache directory does not exist (cache-files-dir):
Clearing cache (cache-dir): /root/.composer/cache
All caches cleared.
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Installing nzedb/nzedb (0.x-dev 6e24bb19ae58c056c4f0f7ca1488e05e9c101eb4)
  - Installing nzedb/nzedb (0.x-dev 6e24bb1): Cloning 6e24bb19ae from cache
Created project in /var/www/nZEDb
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 53 installs, 0 updates, 0 removals
  - Installing fxp/composer-asset-plugin (v1.3.1): Cloning 0bfdd307d2 from cache
  - Installing composer/installers (v1.3.0): Cloning 79ad876c74 from cache
  - Installing b3rs3rk/steamfront (dev-master 286962e): Cloning 286962ea79 from cache
  - Installing barracudanetworks/forkdaemon-php (v1.0.10): Cloning 6675af59d0 from cache
  - Installing bower-asset/animate.css (3.5.2): Cloning dac3dab7b5 from cache
  .......(TRUCATED)........
````

## Steps to reproduce the behaviour

Execute the command provided in the nzedb setup instructions of:
````
composer create-project --stability dev --keep-vcs --prefer-source nZEDb/nZEDb
````

**Comment by CollinChaffin** [comment]
Are there any plans to update the composer stuff to return to supporting building the latest DEV commit via create-project?

**Comment by niel** [comment]
@CollinChaffin Not in the foreseeable future. create-project only seems to work with the master branch and cannot identify a specific branch used for development.
 Additionally, it is only a short-cut for cloning the master branch at the tip and doing a composer install. You should just clone the dev branch directly and run composer install.
Eventually, I'd like to restructure to be working on the 'master' branch for dev work, but it is not a priority.
