### ISSUE TITLE
Can't pas step2 with new install still missing SQL tables

### ISSUE THREAD

**Issue by hvdrunen** [nZEDb/nZEDb#2522]
###Expected behaviour
I can't pas step 2 with a new install, stil missing SQL tables, i try it several days to find a solution but nothing works
my Sql create only 32 tables
plaese help me

I install  
Release v0.7.4.1 from Git
Ubuntu server 16.04.03
Apache2
Mysql

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nzedbdb.user_roles' doesn't exist
File: /var/www/nZEDb/resources/db/schema/data/10-binaryblacklist.tsv Inserting data into table: 'binaryblacklist' File: /var/www/nZEDb/resources/db/schema/data/10-categories.tsv Inserting data into table: 'categories' File: /var/www/nZEDb/resources/db/schema/data/10-category_regexes.tsv Inserting data into table: 'category_regexes' File: /var/www/nZEDb/resources/db/schema/data/10-collection_regexes.tsv Inserting data into table: 'collection_regexes' File: /var/www/nZEDb/resources/db/schema/data/10-countries.tsv Inserting data into table: 'countries' File: /var/www/nZEDb/resources/db/schema/data/10-forum_posts.tsv Inserting data into table: 'forum_posts' File: /var/www/nZEDb/resources/db/schema/data/10-genres.tsv Inserting data into table: 'genres' File: /var/www/nZEDb/resources/db/schema/data/10-groups.tsv Inserting data into table: 'groups' File: /var/www/nZEDb/resources/db/schema/data/10-menu_items.tsv Inserting data into table: 'menu_items' File: /var/www/nZEDb/resources/db/schema/data/10-page_contents.tsv Inserting data into table: 'page_contents' File: /var/www/nZEDb/resources/db/schema/data/10-release_naming_regexes.tsv Inserting data into table: 'release_naming_regexes'
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nzedbdb.release_naming_regexes' doesn't exist
File: /var/www/nZEDb/resources/db/schema/data/10-settings.tsv Inserting data into table: 'settings'
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nzedbdb.settings' doesn't exist
File: /var/www/nZEDb/resources/db/schema/data/10-tmux.tsv Inserting data into table: 'tmux'
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nzedbdb.tmux' doesn't exist
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nzedbdb.tmux' doesn't exist

###Actual behaviour

###Steps to reproduce the behaviour

**Comment by niel** [comment]
That error lists a whole bunch of missing tables. Make sure you created the permissions for the nzedb user.
What guide are you following?

**Comment by hvdrunen** [comment]
![nzedb knipsel](https://user-images.githubusercontent.com/32242622/30784872-91bbfdae-a15d-11e7-8618-49b411d56b17.JPG)
I used  https://forums.nzedb.com/index.php?topic=2366.0

sudo update-rc.d apparmor disable

mysql> mysql> SHOW GRANTS FOR 'nzedbindexer'@'localhost';
+-------------------------------------------------------------------------------------+
| Grants for nzedbindexer@localhost                                                   |
+-------------------------------------------------------------------------------------+
| GRANT FILE ON *.* TO 'nzedbindexer'@'localhost'                                     |
| GRANT ALL PRIVILEGES ON `nzedbdb`.* TO 'nzedbindexer'@'localhost' WITH GRANT OPTION |
+-------------------------------------------------------------------------------------+
2 rows in set (0,00 sec)

hans@ubuntu-server:~$ ls -l /var/www/nZEDb
totaal 520
drwxrwsrwx 11 hans hans   4096 sep 23 21:54 app
-rwxrwxrwx  1 hans hans    803 sep 23 21:54 bootstrap.php
drwxrwsrwx  3 hans hans   4096 sep 23 21:54 build
-rwxrwxrwx  1 hans hans 287193 sep 23 21:54 Changelog
drwxrwsrwx  3 hans hans   4096 sep 23 21:54 cli
-rwxrwxrwx  1 hans hans    349 sep 23 21:54 commit
-rwxrwxrwx  1 hans hans   4011 sep 23 21:54 composer.json
-rwxrwxrwx  1 hans hans  83095 sep 23 21:54 composer.lock
drwxrwsrwx  2 hans hans   4096 sep 24 12:29 configuration
drwxrwsrwx  3 hans hans   4096 sep 23 21:54 docs
-rwxrwxrwx  1 hans hans   1254 sep 23 21:54 index.php
drwxrwsrwx  2 hans hans   4096 sep 23 21:54 _install
-rwxrwxrwx  1 hans hans   6647 sep 23 21:54 INSTALL.txt
drwxrwsrwx  4 hans hans   4096 sep 23 21:58 libraries
drwxrwsrwx  4 hans hans   4096 sep 23 21:54 libs
drwxrwsrwx  6 hans hans   4096 sep 23 21:54 misc
drwxrwsrwx 10 hans hans   4096 sep 23 21:54 nzedb
-rwxrwxrwx  1 hans hans    176 sep 23 21:54 nZEDbBase.php
-rwxrwxrwx  1 hans hans   7483 sep 23 21:54 README.md
-rwxrwxrwx  1 hans hans  63835 sep 23 21:54 ReleaseNotes
drwxrwsrwx  7 hans hans   4096 sep 23 21:54 resources
drwxrwsrwx  8 hans hans   4096 sep 24 12:22 www
-rwxrwxrwx  1 hans hans     45 sep 23 21:54 zed


When i make the table myself then the install delete them and make not a new one
When I delete the database complete then the install is making a new databse 
witdh missing
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nzedbdb.user_roles' doesn't exist
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nzedbdb.release_naming_regexes' doesn't exist
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nzedbdb.settings' doesn't exist
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nzedbdb.tmux' doesn't exist

**Comment by niel** [comment]
That guide uses MySQL, we don't directly support it anymore because of weird issues like this. Try removing MySQL and replacing with MariaDB,
If you have any issues with MariaDB, look at the Upgrading Guide on the wiki for hints on things that might need manual intervention.

**Comment by hvdrunen** [comment]
I did a fresh install width mariaDB en install works now.
now the movies pages is total blank the other pages works well

Gr Hans
