### ISSUE TITLE
How-To request, repopulate a DB table to original values - release names

### ISSUE THREAD

**Issue by stevenmcastano** [nZEDb/nZEDb#2524]
Somewhere along the way, my release naming regex settings got jacked up and it cause the last two updates I've done to fail. So I've needed to go in manually and comment out certain lines and/or do manual updates with a patch level.

This has also led to some release not being found, or all parts not being grouped together properly.

What I'd like to do is reset this DB table to the most recent version manually. Basically, do the latest update of nZEDb, then either delete all the values and reimport the .sql file, maybe drop the whole table and reimport, etc... This way my current install correctly matches the default values for the latest version. That patched and updates into the future should start working again without any issues.

So... how would I go about doing this??

**Comment by niel** [comment]
I'll try to add a page to the Wiki for this later tonight.

**Comment by stevenmcastano** [comment]
That would be awesome, thanks! I'll be on the lookout for it to test it out ASAP.

**Comment by niel** [comment]
Updated the Database Administration page on the wiki.
https://github.com/nZEDb/nZEDb/wiki/Database-Administration#reset-tables-to-default-values

Let me know if you need more info, preferably in IRC ;-)
