### ISSUE TITLE
Error kicking-off update scripts

### ISSUE THREAD

**Issue by DrSeussFreak** [nZEDb/nZEDb#2525]
I am running Ubuntu 16.04.3, and have had this running forever without any issues, until I rebooted after performing some systems updates today...

Something to note, I can browse the site without issue, only the scripts fail

###Expected behaviour
run ./start and the processes kick-off as they should

###Actual behaviour
I receive the following errors

> mfederman@Sentinel:/etc$ cd /var/www/nZEDb/misc/update/nix/screen/threaded/
> mfederman@Sentinel:/var/www/nZEDb/misc/update/nix/screen/threaded$ ./start.sh 
> Start Multi-Processing binaries.php...
> string(21) "could not find driver"
> PHP Fatal error:  Uncaught PDOException: could not find driver in /var/www/nZEDb/libraries/lithium/data/source/Database.php:325
> Stack trace:
> #0 /var/www/nZEDb/libraries/lithium/data/source/Database.php(325): PDO->__construct('mysql:host=127....', 'nzedb', 'nzedb', Array)
> #1 /var/www/nZEDb/libraries/lithium/data/source/database/adapter/MySql.php(209): lithium\data\source\Database->connect()
> #2 /var/www/nZEDb/app/extensions/adapter/data/source/database/MySql.php(79): lithium\data\source\database\adapter\MySql->connect()
> #3 /var/www/nZEDb/libraries/lithium/data/Source.php(111): app\extensions\adapter\data\source\database\MySql->connect()
> #4 /var/www/nZEDb/libraries/lithium/data/source/Database.php(210): lithium\data\Source->_init()
> #5 /var/www/nZEDb/libraries/lithium/data/source/database/adapter/MySql.php(192): lithium\data\source\Database->_init()
> #6 /var/www/nZEDb/libraries/lithium/core/Object.php(84): lithium\data\source\database\adapter\MySql->_init()
> #7 /var/www/nZEDb/libraries/lithium/data/Source.php(94): lithium\core\Objec in /var/www/nZEDb/libraries/lithium/data/source/Database.php on line 340
> Start Multi-Processing backfill.php...
> string(21) "could not find driver"
> PHP Fatal error:  Uncaught PDOException: could not find driver in /var/www/nZEDb/libraries/lithium/data/source/Database.php:325
> Stack trace:
> #0 /var/www/nZEDb/libraries/lithium/data/source/Database.php(325): PDO->__construct('mysql:host=127....', 'nzedb', 'nzedb', Array)
> #1 /var/www/nZEDb/libraries/lithium/data/source/database/adapter/MySql.php(209): lithium\data\source\Database->connect()
> #2 /var/www/nZEDb/app/extensions/adapter/data/source/database/MySql.php(79): lithium\data\source\database\adapter\MySql->connect()
> #3 /var/www/nZEDb/libraries/lithium/data/Source.php(111): app\extensions\adapter\data\source\database\MySql->connect()
> #4 /var/www/nZEDb/libraries/lithium/data/source/Database.php(210): lithium\data\Source->_init()
> #5 /var/www/nZEDb/libraries/lithium/data/source/database/adapter/MySql.php(192): lithium\data\source\Database->_init()
> #6 /var/www/nZEDb/libraries/lithium/core/Object.php(84): lithium\data\source\database\adapter\MySql->_init()
> #7 /var/www/nZEDb/libraries/lithium/data/Source.php(94): lithium\core\Objec in /var/www/nZEDb/libraries/lithium/data/source/Database.php on line 340
> waiting 60 seconds...

###Steps to reproduce the behaviour
`cd /var/www/nZEDb/misc/update/nix/screen/threaded/`
and run
` ./start.sh `

**Comment by DrSeussFreak** [comment]
Another note, I ran

`mysqlcheck -r -u root -p nzedb`

and everything was fine

> mfederman@Sentinel:/etc$ mysqlcheck -r -u root -p nzedb
> Enter password: 
> nzedb.allgroups                                    OK
> nzedb.anidb_episodes                               OK
> nzedb.anidb_info                                   OK
> nzedb.anidb_titles                                 OK
> nzedb.audio_data                                   OK
> nzedb.binaries                                     OK
> nzedb.binaries_1                                   OK
> nzedb.binaries_1000001                             OK
> nzedb.binaries_1000002                             OK
> nzedb.binaries_1000004                             OK
> nzedb.binaries_1000005                             OK
> nzedb.binaries_1000008                             OK
> nzedb.binaries_1000011                             OK
> nzedb.binaries_1000012                             OK
> nzedb.binaries_1000016                             OK
> nzedb.binaries_1000017                             OK
> nzedb.binaries_1000024                             OK
> nzedb.binaries_1000032                             OK
> nzedb.binaries_1000034                             OK
> nzedb.binaries_1000045                             OK
> nzedb.binaries_1000060                             OK
> nzedb.binaries_1000078                             OK
> nzedb.binaries_1000080                             OK
> nzedb.binaries_1000087                             OK
> nzedb.binaries_1000089                             OK
> nzedb.binaries_1000093                             OK
> nzedb.binaries_1000102                             OK
> nzedb.binaries_1000150                             OK
> nzedb.binaries_1000191                             OK
> nzedb.binaries_1000204                             OK
> nzedb.binaries_1000215                             OK
> nzedb.binaries_1000221                             OK
> nzedb.binaries_1000228                             OK
> nzedb.binaries_1000267                             OK
> nzedb.binaries_1000274                             OK
> nzedb.binaries_1000278                             OK
> nzedb.binaries_1000282                             OK
> nzedb.binaries_1000284                             OK
> nzedb.binaries_1000285                             OK
> nzedb.binaries_1000286                             OK
> nzedb.binaries_1000290                             OK
> nzedb.binaries_1000291                             OK
> nzedb.binaries_1000297                             OK
> nzedb.binaries_1000303                             OK
> nzedb.binaries_1000362                             OK
> nzedb.binaries_1000371                             OK
> nzedb.binaries_1000380                             OK
> nzedb.binaries_1000432                             OK
> nzedb.binaries_1000441                             OK
> nzedb.binaries_1000458                             OK
> nzedb.binaries_1000459                             OK
> nzedb.binaries_1000492                             OK
> nzedb.binaries_102                                 OK
> nzedb.binaries_103                                 OK
> nzedb.binaries_104                                 OK
> nzedb.binaries_105                                 OK
> nzedb.binaries_106                                 OK
> nzedb.binaries_108                                 OK
> nzedb.binaries_11                                  OK
> nzedb.binaries_111                                 OK
> nzedb.binaries_115                                 OK
> nzedb.binaries_12                                  OK
> nzedb.binaries_130                                 OK
> nzedb.binaries_14                                  OK
> nzedb.binaries_156                                 OK
> nzedb.binaries_160                                 OK
> nzedb.binaries_162                                 OK
> nzedb.binaries_176                                 OK
> nzedb.binaries_179                                 OK
> nzedb.binaries_18                                  OK
> nzedb.binaries_180                                 OK
> nzedb.binaries_181                                 OK
> nzedb.binaries_182                                 OK
> nzedb.binaries_185                                 OK
> nzedb.binaries_186                                 OK
> nzedb.binaries_19                                  OK
> nzedb.binaries_193                                 OK
> nzedb.binaries_196                                 OK
> nzedb.binaries_197                                 OK
> nzedb.binaries_2                                   OK
> nzedb.binaries_20                                  OK
> nzedb.binaries_203                                 OK
> nzedb.binaries_3                                   OK
> nzedb.binaries_30                                  OK
> nzedb.binaries_40                                  OK
> nzedb.binaries_42                                  OK
> nzedb.binaries_44                                  OK
> nzedb.binaries_45                                  OK
> nzedb.binaries_52                                  OK
> nzedb.binaries_54                                  OK
> nzedb.binaries_63                                  OK
> nzedb.binaries_64                                  OK
> nzedb.binaries_66                                  OK
> nzedb.binaries_67                                  OK
> nzedb.binaries_70                                  OK
> nzedb.binaries_71                                  OK
> nzedb.binaries_74                                  OK
> nzedb.binaries_75                                  OK
> nzedb.binaries_76                                  OK
> nzedb.binaries_81                                  OK
> nzedb.binaries_82                                  OK
> nzedb.binaries_83                                  OK
> nzedb.binaries_84                                  OK
> nzedb.binaries_85                                  OK
> nzedb.binaries_86                                  OK
> nzedb.binaries_87                                  OK
> nzedb.binaries_88                                  OK
> nzedb.binaries_89                                  OK
> nzedb.binaries_90                                  OK
> nzedb.binaries_91                                  OK
> nzedb.binaries_92                                  OK
> nzedb.binaries_93                                  OK
> nzedb.binaries_95                                  OK
> nzedb.binaries_96                                  OK
> nzedb.binaries_97                                  OK
> nzedb.binaries_98                                  OK
> nzedb.binaryblacklist                              OK
> nzedb.bookinfo                                     OK
> nzedb.categories                                   OK
> nzedb.category_regexes                             OK
> nzedb.collection_regexes                           OK
> nzedb.collections                                  OK
> nzedb.collections_1                                OK
> nzedb.collections_1000001                          OK
> nzedb.collections_1000002                          OK
> nzedb.collections_1000004                          OK
> nzedb.collections_1000005                          OK
> nzedb.collections_1000008                          OK
> nzedb.collections_1000011                          OK
> nzedb.collections_1000012                          OK
> nzedb.collections_1000016                          OK
> nzedb.collections_1000017                          OK
> nzedb.collections_1000024                          OK
> nzedb.collections_1000032                          OK
> nzedb.collections_1000034                          OK
> nzedb.collections_1000045                          OK
> nzedb.collections_1000060                          OK
> nzedb.collections_1000078                          OK
> nzedb.collections_1000080                          OK
> nzedb.collections_1000087                          OK
> nzedb.collections_1000089                          OK
> nzedb.collections_1000093                          OK
> nzedb.collections_1000102                          OK
> nzedb.collections_1000150                          OK
> nzedb.collections_1000191                          OK
> nzedb.collections_1000204                          OK
> nzedb.collections_1000215                          OK
> nzedb.collections_1000221                          OK
> nzedb.collections_1000228                          OK
> nzedb.collections_1000267                          OK
> nzedb.collections_1000274                          OK
> nzedb.collections_1000278                          OK
> nzedb.collections_1000282                          OK
> nzedb.collections_1000284                          OK
> nzedb.collections_1000285                          OK
> nzedb.collections_1000286                          OK
> nzedb.collections_1000290                          OK
> nzedb.collections_1000291                          OK
> nzedb.collections_1000297                          OK
> nzedb.collections_1000303                          OK
> nzedb.collections_1000362                          OK
> nzedb.collections_1000371                          OK
> nzedb.collections_1000380                          OK
> nzedb.collections_1000432                          OK
> nzedb.collections_1000441                          OK
> nzedb.collections_1000458                          OK
> nzedb.collections_1000459                          OK
> nzedb.collections_1000492                          OK
> nzedb.collections_102                              OK
> nzedb.collections_103                              OK
> nzedb.collections_104                              OK
> nzedb.collections_105                              OK
> nzedb.collections_106                              OK
> nzedb.collections_108                              OK
> nzedb.collections_11                               OK
> nzedb.collections_111                              OK
> nzedb.collections_115                              OK
> nzedb.collections_12                               OK
> nzedb.collections_130                              OK
> nzedb.collections_14                               OK
> nzedb.collections_156                              OK
> nzedb.collections_160                              OK
> nzedb.collections_162                              OK
> nzedb.collections_176                              OK
> nzedb.collections_179                              OK
> nzedb.collections_18                               OK
> nzedb.collections_180                              OK
> nzedb.collections_181                              OK
> nzedb.collections_182                              OK
> nzedb.collections_185                              OK
> nzedb.collections_186                              OK
> nzedb.collections_19                               OK
> nzedb.collections_193                              OK
> nzedb.collections_196                              OK
> nzedb.collections_197                              OK
> nzedb.collections_2                                OK
> nzedb.collections_20                               OK
> nzedb.collections_203                              OK
> nzedb.collections_3                                OK
> nzedb.collections_30                               OK
> nzedb.collections_40                               OK
> nzedb.collections_42                               OK
> nzedb.collections_44                               OK
> nzedb.collections_45                               OK
> nzedb.collections_52                               OK
> nzedb.collections_54                               OK
> nzedb.collections_63                               OK
> nzedb.collections_64                               OK
> nzedb.collections_66                               OK
> nzedb.collections_67                               OK
> nzedb.collections_70                               OK
> nzedb.collections_71                               OK
> nzedb.collections_74                               OK
> nzedb.collections_75                               OK
> nzedb.collections_76                               OK
> nzedb.collections_81                               OK
> nzedb.collections_82                               OK
> nzedb.collections_83                               OK
> nzedb.collections_84                               OK
> nzedb.collections_85                               OK
> nzedb.collections_86                               OK
> nzedb.collections_87                               OK
> nzedb.collections_88                               OK
> nzedb.collections_89                               OK
> nzedb.collections_90                               OK
> nzedb.collections_91                               OK
> nzedb.collections_92                               OK
> nzedb.collections_93                               OK
> nzedb.collections_95                               OK
> nzedb.collections_96                               OK
> nzedb.collections_97                               OK
> nzedb.collections_98                               OK
> nzedb.consoleinfo                                  OK
> nzedb.countries                                    OK
> nzedb.dnzb_failures                                OK
> nzedb.forum_posts                                  OK
> nzedb.gamesinfo                                    OK
> nzedb.genres                                       OK
> nzedb.groups                                       OK
> nzedb.invitations                                  OK
> nzedb.logging                                      OK
> nzedb.menu_items                                   OK
> nzedb.missed_parts                                 OK
> nzedb.missed_parts_1                               OK
> nzedb.missed_parts_1000001                         OK
> nzedb.missed_parts_1000002                         OK
> nzedb.missed_parts_1000004                         OK
> nzedb.missed_parts_1000005                         OK
> nzedb.missed_parts_1000008                         OK
> nzedb.missed_parts_1000011                         OK
> nzedb.missed_parts_1000012                         OK
> nzedb.missed_parts_1000016                         OK
> nzedb.missed_parts_1000017                         OK
> nzedb.missed_parts_1000024                         OK
> nzedb.missed_parts_1000032                         OK
> nzedb.missed_parts_1000034                         OK
> nzedb.missed_parts_1000045                         OK
> nzedb.missed_parts_1000060                         OK
> nzedb.missed_parts_1000078                         OK
> nzedb.missed_parts_1000080                         OK
> nzedb.missed_parts_1000087                         OK
> nzedb.missed_parts_1000089                         OK
> nzedb.missed_parts_1000093                         OK
> nzedb.missed_parts_1000102                         OK
> nzedb.missed_parts_1000150                         OK
> nzedb.missed_parts_1000191                         OK
> nzedb.missed_parts_1000204                         OK
> nzedb.missed_parts_1000215                         OK
> nzedb.missed_parts_1000221                         OK
> nzedb.missed_parts_1000228                         OK
> nzedb.missed_parts_1000267                         OK
> nzedb.missed_parts_1000274                         OK
> nzedb.missed_parts_1000278                         OK
> nzedb.missed_parts_1000282                         OK
> nzedb.missed_parts_1000284                         OK
> nzedb.missed_parts_1000285                         OK
> nzedb.missed_parts_1000286                         OK
> nzedb.missed_parts_1000290                         OK
> nzedb.missed_parts_1000291                         OK
> nzedb.missed_parts_1000297                         OK
> nzedb.missed_parts_1000303                         OK
> nzedb.missed_parts_1000362                         OK
> nzedb.missed_parts_1000371                         OK
> nzedb.missed_parts_1000380                         OK
> nzedb.missed_parts_1000432                         OK
> nzedb.missed_parts_1000441                         OK
> nzedb.missed_parts_1000458                         OK
> nzedb.missed_parts_1000459                         OK
> nzedb.missed_parts_1000492                         OK
> nzedb.missed_parts_102                             OK
> nzedb.missed_parts_103                             OK
> nzedb.missed_parts_104                             OK
> nzedb.missed_parts_105                             OK
> nzedb.missed_parts_106                             OK
> nzedb.missed_parts_108                             OK
> nzedb.missed_parts_11                              OK
> nzedb.missed_parts_111                             OK
> nzedb.missed_parts_115                             OK
> nzedb.missed_parts_12                              OK
> nzedb.missed_parts_130                             OK
> nzedb.missed_parts_14                              OK
> nzedb.missed_parts_156                             OK
> nzedb.missed_parts_160                             OK
> nzedb.missed_parts_162                             OK
> nzedb.missed_parts_176                             OK
> nzedb.missed_parts_179                             OK
> nzedb.missed_parts_18                              OK
> nzedb.missed_parts_180                             OK
> nzedb.missed_parts_181                             OK
> nzedb.missed_parts_182                             OK
> nzedb.missed_parts_185                             OK
> nzedb.missed_parts_186                             OK
> nzedb.missed_parts_19                              OK
> nzedb.missed_parts_193                             OK
> nzedb.missed_parts_196                             OK
> nzedb.missed_parts_197                             OK
> nzedb.missed_parts_2                               OK
> nzedb.missed_parts_20                              OK
> nzedb.missed_parts_203                             OK
> nzedb.missed_parts_3                               OK
> nzedb.missed_parts_30                              OK
> nzedb.missed_parts_40                              OK
> nzedb.missed_parts_42                              OK
> nzedb.missed_parts_44                              OK
> nzedb.missed_parts_45                              OK
> nzedb.missed_parts_52                              OK
> nzedb.missed_parts_54                              OK
> nzedb.missed_parts_63                              OK
> nzedb.missed_parts_64                              OK
> nzedb.missed_parts_66                              OK
> nzedb.missed_parts_67                              OK
> nzedb.missed_parts_70                              OK
> nzedb.missed_parts_71                              OK
> nzedb.missed_parts_74                              OK
> nzedb.missed_parts_75                              OK
> nzedb.missed_parts_76                              OK
> nzedb.missed_parts_81                              OK
> nzedb.missed_parts_82                              OK
> nzedb.missed_parts_83                              OK
> nzedb.missed_parts_84                              OK
> nzedb.missed_parts_85                              OK
> nzedb.missed_parts_86                              OK
> nzedb.missed_parts_87                              OK
> nzedb.missed_parts_88                              OK
> nzedb.missed_parts_89                              OK
> nzedb.missed_parts_90                              OK
> nzedb.missed_parts_91                              OK
> nzedb.missed_parts_92                              OK
> nzedb.missed_parts_93                              OK
> nzedb.missed_parts_95                              OK
> nzedb.missed_parts_96                              OK
> nzedb.missed_parts_97                              OK
> nzedb.missed_parts_98                              OK
> nzedb.movieinfo                                    OK
> nzedb.multigroup_binaries                          OK
> nzedb.multigroup_collections                       OK
> nzedb.multigroup_missed_parts                      OK
> nzedb.multigroup_parts                             OK
> nzedb.multigroup_posters                           OK
> nzedb.musicinfo                                    OK
> nzedb.page_contents                                OK
> nzedb.parts                                        OK
> nzedb.parts_1                                      OK
> nzedb.parts_1000001                                OK
> nzedb.parts_1000002                                OK
> nzedb.parts_1000004                                OK
> nzedb.parts_1000005                                OK
> nzedb.parts_1000008                                OK
> nzedb.parts_1000011                                OK
> nzedb.parts_1000012                                OK
> nzedb.parts_1000016                                OK
> nzedb.parts_1000017                                OK
> nzedb.parts_1000024                                OK
> nzedb.parts_1000032                                OK
> nzedb.parts_1000034                                OK
> nzedb.parts_1000045                                OK
> nzedb.parts_1000060                                OK
> nzedb.parts_1000078                                OK
> nzedb.parts_1000080                                OK
> nzedb.parts_1000087                                OK
> nzedb.parts_1000089                                OK
> nzedb.parts_1000093                                OK
> nzedb.parts_1000102                                OK
> nzedb.parts_1000150                                OK
> nzedb.parts_1000191                                OK
> nzedb.parts_1000204                                OK
> nzedb.parts_1000215                                OK
> nzedb.parts_1000221                                OK
> nzedb.parts_1000228                                OK
> nzedb.parts_1000267                                OK
> nzedb.parts_1000274                                OK
> nzedb.parts_1000278                                OK
> nzedb.parts_1000282                                OK
> nzedb.parts_1000284                                OK
> nzedb.parts_1000285                                OK
> nzedb.parts_1000286                                OK
> nzedb.parts_1000290                                OK
> nzedb.parts_1000291                                OK
> nzedb.parts_1000297                                OK
> nzedb.parts_1000303                                OK
> nzedb.parts_1000362                                OK
> nzedb.parts_1000371                                OK
> nzedb.parts_1000380                                OK
> nzedb.parts_1000432                                OK
> nzedb.parts_1000441                                OK
> nzedb.parts_1000458                                OK
> nzedb.parts_1000459                                OK
> nzedb.parts_1000492                                OK
> nzedb.parts_102                                    OK
> nzedb.parts_103                                    OK
> nzedb.parts_104                                    OK
> nzedb.parts_105                                    OK
> nzedb.parts_106                                    OK
> nzedb.parts_108                                    OK
> nzedb.parts_11                                     OK
> nzedb.parts_111                                    OK
> nzedb.parts_115                                    OK
> nzedb.parts_12                                     OK
> nzedb.parts_130                                    OK
> nzedb.parts_14                                     OK
> nzedb.parts_156                                    OK
> nzedb.parts_160                                    OK
> nzedb.parts_162                                    OK
> nzedb.parts_176                                    OK
> nzedb.parts_179                                    OK
> nzedb.parts_18                                     OK
> nzedb.parts_180                                    OK
> nzedb.parts_181                                    OK
> nzedb.parts_182                                    OK
> nzedb.parts_185                                    OK
> nzedb.parts_186                                    OK
> nzedb.parts_19                                     OK
> nzedb.parts_193                                    OK
> nzedb.parts_196                                    OK
> nzedb.parts_197                                    OK
> nzedb.parts_2                                      OK
> nzedb.parts_20                                     OK
> nzedb.parts_203                                    OK
> nzedb.parts_3                                      OK
> nzedb.parts_30                                     OK
> nzedb.parts_40                                     OK
> nzedb.parts_42                                     OK
> nzedb.parts_44                                     OK
> nzedb.parts_45                                     OK
> nzedb.parts_52                                     OK
> nzedb.parts_54                                     OK
> nzedb.parts_63                                     OK
> nzedb.parts_64                                     OK
> nzedb.parts_66                                     OK
> nzedb.parts_67                                     OK
> nzedb.parts_70                                     OK
> nzedb.parts_71                                     OK
> nzedb.parts_74                                     OK
> nzedb.parts_75                                     OK
> nzedb.parts_76                                     OK
> nzedb.parts_81                                     OK
> nzedb.parts_82                                     OK
> nzedb.parts_83                                     OK
> nzedb.parts_84                                     OK
> nzedb.parts_85                                     OK
> nzedb.parts_86                                     OK
> nzedb.parts_87                                     OK
> nzedb.parts_88                                     OK
> nzedb.parts_89                                     OK
> nzedb.parts_90                                     OK
> nzedb.parts_91                                     OK
> nzedb.parts_92                                     OK
> nzedb.parts_93                                     OK
> nzedb.parts_95                                     OK
> nzedb.parts_96                                     OK
> nzedb.parts_97                                     OK
> nzedb.parts_98                                     OK
> nzedb.predb                                        OK
> nzedb.predb_hashes                                 OK
> nzedb.predb_imports                                OK
> nzedb.release_comments                             OK
> nzedb.release_files                                OK
> nzedb.release_naming_regexes                       OK
> nzedb.release_nfos                                 OK
> nzedb.release_search_data                          OK
> nzedb.release_subtitles                            OK
> nzedb.release_unique                               OK
> nzedb.releaseextrafull                             OK
> nzedb.releases                                     OK
> nzedb.releases_groups                              OK
> nzedb.role_excluded_categories                     OK
> nzedb.settings                                     OK
> nzedb.sharing                                      OK
> nzedb.sharing_sites                                OK
> nzedb.short_groups                                 OK
> nzedb.steam_apps                                   OK
> nzedb.tmux                                         OK
> nzedb.tv_episodes                                  OK
> nzedb.tv_info                                      OK
> nzedb.upcoming_releases                            OK
> nzedb.user_downloads                               OK
> nzedb.user_excluded_categories                     OK
> nzedb.user_movies                                  OK
> nzedb.user_requests                                OK
> nzedb.user_roles                                   OK
> nzedb.user_series                                  OK
> nzedb.users                                        OK
> nzedb.users_releases                               OK
> nzedb.video_data                                   OK
> nzedb.videos                                       OK
> nzedb.videos_aliases                               OK
> nzedb.xxxinfo                                      OK

**Comment by niel** [comment]
Did PHP get upgraded? Sounds like there is a change regarding your MySQL drivers.

**Comment by DrSeussFreak** [comment]
There might have been a minor PHP update, but I have since then removed and reinstalled PHP and MariaDB, the issue persists.

> mfederman@Sentinel:~$ php -v
> PHP 7.1.9-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Sep  2 2017 05:56:43) ( NTS )
> Copyright (c) 1997-2017 The PHP Group
> Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
>     with Zend OPcache v7.1.9-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2017, by Zend Technologies

**Comment by niel** [comment]
What's the result of "php -m"

**Comment by DrSeussFreak** [comment]
> mfederman@Sentinel:~$ php -m
> [PHP Modules]
> calendar
> Core
> ctype
> date
> exif
> fileinfo
> filter
> ftp
> gettext
> hash
> iconv
> imagick
> json
> libxml
> mbstring
> openssl
> pcntl
> pcre
> PDO
> Phar
> posix
> readline
> Reflection
> session
> shmop
> sockets
> SPL
> standard
> sysvmsg
> sysvsem
> sysvshm
> tokenizer
> Zend OPcache
> zlib
> 
> [Zend Modules]
> Zend OPcache

**Comment by niel** [comment]
As I thought, you're missing the mysqlnd and pdo_mysql extensions. Install them the same way as you did when originally installing nZEDb.

**Comment by DrSeussFreak** [comment]
So I am at a loss, as the packages are installed, and up-to-date.

Attached is the output of my phpinfo page
[phpinfo-output.rtfd.zip](https://github.com/nZEDb/nZEDb/files/1346563/phpinfo-output.rtfd.zip)

**Comment by Bart39** [comment]
https://stackoverflow.com/questions/32728860/php-7-rc3-how-to-install-missing-mysql-pdo

**Comment by DrSeussFreak** [comment]
Yea, just got past that, now working on an error, but I think I wil get it resolved in a moment

**Comment by DrSeussFreak** [comment]
now I am seeing

> mfederman@Sentinel:/var/www/nZEDb/misc/update/nix/screen/threaded$ ./start.sh 
> Start Multi-Processing binaries.php...
> PHP Warning:  app\extensions\adapter\data\source\database\MySql::app\extensions\adapter\data\source\database\MySql::timezone: Empty value passed for timezone setting! Check date.timezone setting is set in PHP's configuration file. in /var/www/nZEDb/app/extensions/adapter/data/source/database/MySql.php on line 114
> PHP Fatal error:  Uncaught ErrorException: Couldn't change session tz_session! in /var/www/nZEDb/nzedb/db/DB.php:1375
> Stack trace:
> #0 /var/www/nZEDb/nzedb/db/DB.php(212): nzedb\db\DB->connect(Array)
> #1 /var/www/nZEDb/nzedb/libraries/Forking.php(101): nzedb\db\DB->__construct()
> #2 /var/www/nZEDb/misc/update/nix/multiprocessing/binaries.php(12): nzedb\libraries\Forking->processWorkType('binaries', Array)
> #3 {main}
>   thrown in /var/www/nZEDb/nzedb/db/DB.php on line 1375
> Start Multi-Processing backfill.php...
> PHP Warning:  app\extensions\adapter\data\source\database\MySql::app\extensions\adapter\data\source\database\MySql::timezone: Empty value passed for timezone setting! Check date.timezone setting is set in PHP's configuration file. in /var/www/nZEDb/app/extensions/adapter/data/source/database/MySql.php on line 114
> PHP Fatal error:  Uncaught ErrorException: Couldn't change session tz_session! in /var/www/nZEDb/nzedb/db/DB.php:1375
> Stack trace:
> #0 /var/www/nZEDb/nzedb/db/DB.php(212): nzedb\db\DB->connect(Array)
> #1 /var/www/nZEDb/nzedb/libraries/Forking.php(101): nzedb\db\DB->__construct()
> #2 /var/www/nZEDb/misc/update/nix/multiprocessing/backfill.php(11): nzedb\libraries\Forking->processWorkType('backfill', Array)
> #3 {main}
>   thrown in /var/www/nZEDb/nzedb/db/DB.php on line 1375
> waiting 60 seconds...

**Comment by Bart39** [comment]
https://github.com/nZEDb/nZEDb/blob/0.x/ReleaseNotes#L61

**Comment by DrSeussFreak** [comment]
I had tried that, I get the following

> root@Sentinel:~# mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql -p
> Enter password: 
> Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.

**Comment by Bart39** [comment]
https://community.c9.io/t/bug-error-when-generating-mysql-time-zone-tables-convert-tz-returns-null/7638

Look at last reply and also don’t think the leap seconds is important, if that’s the only one that errored you are fine

**Comment by niel** [comment]
@DrSeussFreak github issues is not the place for general help and support. 
Please use the IRC channel or the forums.
