### ISSUE TITLE
Uncaught Error: Class 'TMDb' not found

### ISSUE THREAD

**Issue by ghost** [nZEDb/nZEDb#2526]
When searching for IMDB ID in .com/mymovies you get:

PHP Fatal error:  Uncaught Error: Class 'TMDb' not found in www/pages/ajax_mymovies.php:34

**Comment by ghost** [comment]
in latest 0.x

**Comment by niel** [comment]
@slug1982 I'll try to create a new 0.x release in the next day or two.

**Comment by ghost** [comment]
@niel I've applied 1940c87 and now see 
"PHP message: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to nzedb\processing\tv\TMDB::__construct() must be of the type array, string given, called in www/pages/ajax_mymovies.php on line 35 and defined in nzedb/processing/tv/TMDB.php:55
Stack trace:
#0 www/pages/ajax_mymovies.php(35): nzedb\processing\tv\TMDB->__construct('80018ea4f75aa9f...', 'en')
#1 www/index.php(89): require_once('/nz...')
#2 {main}
  thrown in nzedb/processing/tv/TMDB.php on line 55" while reading response header from upstream, client: x.x.x.x, server: xx.com, request: "GET /ajax_mymovies?rand=xxx&id=somefilm HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "xxx.com", referrer: "https://xxx.com/mymovies"

**Comment by niel** [comment]
I'll take another quick look. If I can't see a fix I'll pass it on to Darius who did the conversion.

**Comment by ghost** [comment]
Hmm applied this fix and the error is now gone but all I get is a blank page.

**Comment by niel** [comment]
Nothing in logs?

**Comment by ghost** [comment]
Nope

**Comment by ghost** [comment]
Ah it seems it only works with IMDB ID's now? I tried searching for a Movie name, I think that's how it worked in the past.

**Comment by niel** [comment]
No idea, ask @DariusIII :-)
