### ISSUE TITLE
PHP Fatal error:  Uncaught Exception: Failed to open versions XML file

### ISSUE THREAD

**Issue by tonymorella** [nZEDb/nZEDb#2529]
This happens when I try and open http://x.x.x.x/profileedit 
Noticed this happen in 2016 in a ticket that was close, but did not give a reason just that is was fixed.

root@nas:/var/www/nZEDb/www# more php_errors.log 
[13-Oct-2017 02:15:01 America/New_York] PHP Fatal error:  Uncaught Exception: Failed to open versions XML file '/var/www/nZEDb/build/nzedb.xml' in /var/www/nZEDb/app/extensions/uti
l/Versions.php:310
Stack trace:
#0 /var/www/nZEDb/app/extensions/util/Versions.php(188): app\extensions\util\Versions->loadXMLFile()
#1 /var/www/nZEDb/nzedb/NZB.php(127): app\extensions\util\Versions->getGitTagInFile()
#2 /var/www/nZEDb/nzedb/NZBGet.php(97): nzedb\NZB->__construct(Object(nzedb\db\DB))
#3 /var/www/nZEDb/www/pages/profileedit.php(16): nzedb\NZBGet->__construct(Object(Page))
#4 /var/www/nZEDb/www/index.php(87): require_once('/var/www/nZEDb/...')
#5 {main}
  thrown in /var/www/nZEDb/app/extensions/util/Versions.php on line 310

**Comment by niel** [comment]
The error is straight-forward, nZEDb couldn't open the file. Check it exists at nZEDb/build/nzedb.xml, that the case is the same, and that it has appropriate permissions for both web and CLI user access.

BTW the file is provided with the code, so it should exist. If it does not, or it is corrupted, you should be able to force it to be created again with `git reset --hard`

**Comment by tonymorella** [comment]
Sorry, should have said I did all the typical things :) 
The file does exist, permission is set to www-data:www-data and 777 for testing any ideas?

root@nas:/var/www/nZEDb/build# pwd
/var/www/nZEDb/build

drwxrwsrwx  3 www-data www-data   4096 Oct 13 15:12 build

-rwxrwxrwx  1 www-data www-data  457 Oct 13 15:12 nzedb.xml

root@nas:/var/www/nZEDb/build# more nzedb.xml 
<?xml version="1.0" encoding="UTF-8"?>
<nzedb>
	<versions>
		<git>
			<tag>0.8.0.0</tag>
			
			<hooks>
				<precommit>9</precommit>
				
			</hooks>
		</git>
		<scripts>
			<last>
				<date>0000-00-00</date>
				<ordinal>0</ordinal>
			</last>
		</scripts>
		<sql>
			<db>482</db>
			<file>482</file>
		</sql>
	</versions>
</nzedb>

**Comment by niel** [comment]
First, don't run as root :-)
Did you try the git reset command above? If the file exists, the only two reasons for that particular error message is permission problems or the file is corrupt. The reset would fix a corrupt file.

**Comment by tonymorella** [comment]
This is strange if I refresh 3 times it comes up, then it does not work, refresh 3 more times comes back up.
