### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'TMDb' not found in ajax_mymovies.php:34

### ISSUE THREAD

**Issue by ghost** [nZEDb/nZEDb#2533]
`PHP Fatal error:  Uncaught Error: Class 'TMDb' not found in ajax_mymovies.php:34`

https://github.com/nZEDb/nZEDb/blob/0.x/www/pages/ajax_mymovies.php#L34

**Comment by Wally73** [comment]
duplicate from https://github.com/nZEDb/nZEDb/issues/2526

**Comment by ghost** [comment]
Oh, isn't it monday today? :P Closing.
