### ISSUE TITLE
IRC Scraper Fails on Insert

### ISSUE THREAD

**Issue by r33g** [nZEDb/nZEDb#2534]
###Expected behaviour
Insert new PreDB Entry

###Actual behaviour
Fails on insert with invalid date: SQL Error
```
 Incorrect datetime value: '-0001-11-30 00:00:00' for column 'updated' at row 1
```

###Steps to reproduce the behaviour
Not entirely sure, it may be a PHP or MySQL setting I'm missing, but several others have also reported this issue
MySQL server is remote, timezone info has been populated, also the SQL mode doesn't have NO_ZERO_DATES

**Comment by niel** [comment]
Can you provide an example of the IRC line that caused IRCScraper to have this issue.

**Comment by r33g** [comment]
Nevermind this was fixed in commit https://github.com/nZEDb/nZEDb/commit/6c1e4ae47dbcfcbb9c2e2310143878f8a997f936

Must've updated wrong
