### ISSUE TITLE
With LOG_ERRORS enabled, IRCScraper.php throws PHP error

### ISSUE THREAD

**Issue by AlienXAXS** [nZEDb/nZEDb#2535]
###Expected behaviour
It not to error :D

###Actual behaviour
The following error appears in the php error log:
[21-Oct-2017 11:52:47 Europe/London] PHP Fatal error:  Uncaught Error: Call to a member function log() on null in /mnt/data/www/nZEDb/nzedb/IRCScraper.php:295
Stack trace:
#0 /mnt/data/www/nZEDb/nzedb/IRCScraper.php(274): nzedb\IRCScraper->_checkForDupe()
#1 /mnt/data/www/nZEDb/nzedb/IRCClient.php(432): nzedb\IRCScraper->processChannelMessages()
#2 /mnt/data/www/nZEDb/nzedb/IRCScraper.php(193): nzedb\IRCClient->readIncoming()
#3 /mnt/data/www/nZEDb/nzedb/IRCScraper.php(136): nzedb\IRCScraper->_startScraping()
#4 /mnt/data/www/nZEDb/misc/IRCScraper/scrape.php(50): nzedb\IRCScraper->__construct(false, true)
#5 {main}
thrown in /mnt/data/www/nZEDb/nzedb/IRCScraper.php on line 295

###Steps to reproduce the behaviour
Enable LOG_ERROR in settings.php, run 'misc/IRCScraper/scrape.php true false true'

**Comment by Wally73** [comment]
i run it like that on latest dev, no issues here
you sure you're up to date?

**Comment by AlienXAXS** [comment]
Hey Wally,
I am running the latest master, v0.8.0.0.

Is it recommended to upgrade to Dev or stay on a proper release?

**Comment by niel** [comment]
If you have to ask, it's recommended to stay on stable 0.x.
