### ISSUE TITLE
Lot of movie covers not downloaded but set to having one in DB

### ISSUE THREAD

**Issue by ghost** [nZEDb/nZEDb#2536]
I had this issue for a while now, probably over 2 years.

A lot of my movies are listed having a cover in the DB but the actual file does not exist. So it's displayed on the website in a weird way thinking it should load a cover.

I cannot find any reason for this on my local system, permission/disk space wise etc.

Running update_movieimages.php works to delist the release from having a cover but I would like to resolve this issue somehow. Running getMovieImages.php goes thru like 4000+ movies but doesn't fix the ones without it seems.

I checked IMDB for the covers of some of the movies not having one, they exist. But they do not exist on FanArt.tv so it looks like when it cannot get a cover from there it just fails but still writes to DB as having one.

**Comment by ghost** [comment]
Wrote a quick script if anyone is interested. It fetches missing covers where the DB thinks there should be one:

```php
<?php
//This script will update all records in the movieinfo table where there is no cover
require_once realpath(dirname(dirname(dirname(__DIR__))) . DIRECTORY_SEPARATOR . 'bootstrap.php');

use nzedb\db\DB;
use nzedb\Movie;
use nzedb\utility\Misc;

$pdo = new DB();
$movie = new Movie(array('Echo' => true, 'Settings' => $pdo));

if ($argc == 1 || $argv[1] != 'true') {
    exit($pdo->log->error("\nThis script will check all images in covers/movies and compare to db->movieinfo. Then fetch the ones missing.\nTo run:\nphp $argv[0] true\n"));
}

$row = $pdo->queryOneRow("SELECT value FROM settings WHERE setting = 'coverspath'");
if ($row !== false) {
    Misc::setCoversConstant($row['value']);
} else {
    die("Unable to set Covers' constant!\n");
}
$path2covers = nZEDb_COVERS . 'movies' . DS;

$movies = $pdo->queryDirect("SELECT imdbid FROM movieinfo WHERE cover = 1 ORDER BY year ASC, id DESC");

$starttime = microtime(true);
$exists = $updated = 0;

if ($movies instanceof \Traversable) {
    echo $pdo->log->primary("Checking " . number_format($movies->rowCount()) . " movie covers.");
    foreach ($movies as $mov) {
        if (file_exists($path2covers . $mov['imdbid'] . "-cover.jpg")) {
            //echo $pdo->log->info($mov['imdbid'] . " already exists.");
            $exists++;
        } else {
            // tmdb limits are 30 per 10 sec, not certain for imdb
            $diff = floor((microtime(true) - $starttime) * 1000000);
            if (333333 - $diff > 0) {
                // echo "\nSleeping...\n";
                usleep(333333 - $diff);
            }
            $mov = $movie->updateMovieInfo($mov['imdbid']);
            $updated++;
        }
    }
    echo "\n";
}
echo $pdo->log->header($updated . " covers updated.");
echo $pdo->log->header($exists . " already existed.");
```

**Comment by scottia** [comment]
Thanks for the script !

**Comment by cyberbabacool** [comment]
Hi, sorry to bump a such old post, I have the same problem for movies not having covers and I found your script.
Where do I need to put this file ??
I tried many path but I always get a php fatal error

PHP Warning:  require_once(/var/www/nZEDb): failed to open stream: No such file or directory in /var/www/nZEDb/covers.php on line 3
PHP Fatal error:  require_once(): Failed opening required '' (include_path='.:/usr/share/php') in /var/www/nZEDb/covers.php on line 3

what am I doing wrong ??
Thanks for help :)

**Comment by DariusIII** [comment]
I believe it should be in misc/testing folder

**Comment by cyberbabacool** [comment]
thanks for this fast answer, but still not working :'(

PHP Warning:  require_once(/var/www/nZEDb/misc/testing): failed to open stream: No such file or directory in /var/www/nZEDb/misc/testing/covers.php on line 3
PHP Fatal error:  require_once(): Failed opening required '' (include_path='.:/usr/share/php') in /var/www/nZEDb/misc/testing/covers.php on line 3

I'm a real noob in php, but I try to look at the code to understand how it works

**Comment by DariusIII** [comment]
Try with misc/testing/PostProcess, it should work from there

**Comment by Wally73** [comment]
script is [https://github.com/nZEDb/nZEDb/blob/0.x/misc/testing/PostProcess/getMovieCovers.php](url) 

although i'm not sure if it still works since the change from 7 digits to 8 (as somehow php/mariadb don't like the autofilled first 0 )
