### ISSUE TITLE
Zed not updating NZEDB

### ISSUE THREAD

**Issue by dilbaggins** [nZEDb/nZEDb#2537]
###Expected behaviour
.zed update updates nzedb

###Actual behaviour
stays on 7.3.3.1

when i run git branch -v i see:

/var/www/nZEDb$ git branch -v
  0.x        9d4dee1 [behind 119] Release v0.7.3.3
  0v         ca5c24b Use stripos instead of forcing the whole query to upper-case.
* dev        c9b0ec2 Remove tokudb options from convert_mysql_tables script.
  origin/dev 84a8110 Release v0.7.3.1

###Steps to reproduce the behaviour

**Comment by dilbaggins** [comment]
./zed version all
Looking up Git tag version(s)
Hash: c9b0ec2384aa01cd98e7ccfe1a9e75ec4a2c276e
XML version: 0.0.0-dev
Git version: 0.8.0.0
Looking up SQL patch version(s)
XML version: 482
 DB version: 482

**Comment by Wally73** [comment]
try a git pull

**Comment by dilbaggins** [comment]
/var/www/nZEDb$ git pull
Already up-to-date.

**Comment by niel** [comment]
Try upgrading to the last of each 0.y.z.0 release one by one.
git reset v0.7.3.3 && ./zed update all
git reset v0.7.4.1 && ./zed update all
git reset v0.8.0.0 && ./zed update all

**Comment by dilbaggins** [comment]
now im getting this:

```> nzedb\build\Composer::postInstallCmd
PHP Fatal error:  Uncaught Error: Call to undefined function nzedb\build\exists() in /var/www/nZEDb/nzedb/build/Composer.php:28
Stack trace:
#0 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(282): nzedb\build\Composer::postInstallCmd(Object(Composer\Script\Event))
#1 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(205): Composer\EventDispatcher\EventDispatcher->executeEventPhpScript('nzedb\\build\\Com...', 'postInstallCmd', Object(Composer\Script\Event))
#2 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(96): Composer\EventDispatcher\EventDispatcher->doDispatch(Object(Composer\Script\Event))
#3 phar:///usr/local/bin/composer/src/Composer/Installer.php(307): Composer\EventDispatcher\EventDispatcher->dispatchScript('post-install-cm...', true)
#4 phar:///usr/local/bin/composer/src/Composer/Command/InstallCommand.php(119): Composer\Installer->run()
#5 phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php(266): Compo in /var/www/nZEDb/nzedb/build/Composer.php on line 28

Fatal error: Uncaught Error: Call to undefined function nzedb\build\exists() in /var/www/nZEDb/nzedb/build/Composer.php:28
Stack trace:
#0 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(282): nzedb\build\Composer::postInstallCmd(Object(Composer\Script\Event))
#1 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(205): Composer\EventDispatcher\EventDispatcher->executeEventPhpScript('nzedb\\build\\Com...', 'postInstallCmd', Object(Composer\Script\Event))
#2 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(96): Composer\EventDispatcher\EventDispatcher->doDispatch(Object(Composer\Script\Event))
#3 phar:///usr/local/bin/composer/src/Composer/Installer.php(307): Composer\EventDispatcher\EventDispatcher->dispatchScript('post-install-cm...', true)
#4 phar:///usr/local/bin/composer/src/Composer/Command/InstallCommand.php(119): Composer\Installer->run()
#5 phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php(266): Compo in /var/www/nZEDb/nzedb/build/Composer.php on line 28
```

**Comment by niel** [comment]
That was a typo. Updated dev with the fix.

**Comment by dilbaggins** [comment]
@niel i see this now:
/var/www/nZEDb$ ./zed update all
Running composer install process...
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating optimized autoload files
> nzedb\build\Composer::postInstallCmd
Script nzedb\build\Composer::postInstallCmd handling the post-install-cmd event terminated with an exception


  [ErrorException]
  Use of undefined constant nZEDb_CONFIGS - assumed 'nZEDb_CONFIGS'


install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...

Composer failed to update!!

**Comment by niel** [comment]
Oops. I forgot something. Will fix it tomorrow. Hmm, later today for me ;-)

**Comment by dilbaggins** [comment]
that resolved the issue.
