### ISSUE TITLE
PHP date.timezone = UTC handled incorrectly

### ISSUE THREAD

**Issue by LuckyFellow** [nZEDb/nZEDb#2542]
If PHP's date.timezone option is set to a value mariadb does not know (e.g. UTC), connecting to the database results in PHP errors / execptions

**During Setup in step 2:**

> ( ! ) Fatal error: Uncaught ErrorException: Couldn't change session tz_session! in public_html/nZEDb/nzedb/db/DB.php on line 1376
> ( ! ) ErrorException: Couldn't change session tz_session! in public_html/nZEDb/nzedb/db/DB.php on line 1376
> Call Stack
> 	Time	Memory	Function	Location
> 1	0.0002	364880	{main}( )	.../step2.php:0
> 2	0.0109	742024	nzedb\db\DB->__construct( )	.../step2.php:104
> 3	0.0130	745688	nzedb\db\DB->connect( )	.../DB.php:212
> 

**After setup when accessing the website frontend:**

> ( ! ) Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 1298 Unknown or incorrect time zone: 'UTC' in public_html/nZEDb/app/extensions/adapter/data/source/database/MySql.php on line 116
> ( ! ) PDOException: SQLSTATE[HY000]: General error: 1298 Unknown or incorrect time zone: 'UTC' in public_html/nZEDb/app/extensions/adapter/data/source/database/MySql.php on line 116
> Call Stack
> 	Time	Memory	Function	Location
> 1	0.0002	359168	{main}( )	.../index.php:0
> 2	0.0002	359616	require_once( 'public_html/nZEDb/www/smarty.php' )	.../index.php:2
> 3	0.0004	361984	require_once( 'public_html/nZEDb/app/config/bootstrap.php' )	.../smarty.php:22
> 4	0.0097	491608	require_once( 'public_html/nZEDb/app/config/bootstrap/connections.php' )	.../bootstrap.php:59
> 5	0.0099	503888	spl_autoload_call ( )	.../connections.php:127
> 6	0.0099	503992	lithium\core\Libraries::load( )	.../connections.php:127
> 7	0.0099	505632	include( 'public_html/nZEDb/app/models/Settings.php' )	.../Libraries.php:493
> 8	0.0101	579080	app\models\Settings::init( )	.../Settings.php:293
> 9	0.0101	579400	lithium\data\Model::finder( )	.../Settings.php:179
> 10	0.0101	579400	lithium\data\Model::_object( )	.../Model.php:728
> 11	0.0101	580536	lithium\data\Model::_initialize( )	.../Model.php:1480
> 12	0.0102	583448	lithium\data\Connections::get( )	.../Model.php:372
> 13	0.0102	584224	lithium\core\Adaptable::adapter( )	.../Connections.php:177
> 14	0.0105	586048	lithium\core\Adaptable::_initAdapter( )	.../Adaptable.php:123
> 15	0.0105	586744	lithium\aop\Filters::run( )	.../Adaptable.php:224
> 16	0.0105	586744	lithium\core\Adaptable::lithium\core\{closure}( )	.../Filters.php:231
> 17	0.0118	622720	app\extensions\adapter\data\source\database\MySql->__construct( )	.../Adaptable.php:223
> 18	0.0118	623832	app\extensions\adapter\data\source\database\MySql->__construct( )	.../MySql.php:67
> 19	0.0118	624944	app\extensions\adapter\data\source\database\MySql->__construct( )	.../MySql.php:158
> 20	0.0118	625640	app\extensions\adapter\data\source\database\MySql->__construct( )	.../Database.php:198
> 21	0.0118	626336	app\extensions\adapter\data\source\database\MySql->__construct( )	.../Source.php:94
> 22	0.0118	627032	app\extensions\adapter\data\source\database\MySql->_init( )	.../Object.php:84
> 23	0.0119	627768	app\extensions\adapter\data\source\database\MySql->_init( )	.../MySql.php:192
> 24	0.0119	627768	app\extensions\adapter\data\source\database\MySql->_init( )	.../Database.php:210
> 25	0.0119	627768	app\extensions\adapter\data\source\database\MySql->connect( )	.../Source.php:111
> 26	0.0129	638624	app\extensions\adapter\data\source\database\MySql->timezone( )	.../MySql.php:83
> 27	0.0129	638672	exec ( )	.../MySql.php:116

My OS runs in UTC, PHP is set to UTC and MariaDB's default timezone is SYSTEM, which equals UTC in my case. The nZEDb PHP scripts do not detect this circumstance.

To set MariaDB's timezone to UTC, I need to specify it as: default_time_zone=+00:00
But that, again, is not detected correctly by the PHP scripts.

**Comment by AshleyJackson** [comment]
I am having this exact same issue with the exact same error code.

My timezone is Australia/Brisbane

**Comment by niel** [comment]
I'll look into this

**Comment by niel** [comment]
Setting to a value not known in the time_zone table(s) should cause an error, that is expected. 
However UTC (and Australia/Brisbane) *is* in the timezone tables so shouldn't be a problem if you have set them up correctly.

Please make sure that you have correctly loaded the table data. Incidentally, I also run in UTC for all my servers and haven't had any issues.

**Comment by LuckyFellow** [comment]
Alright, that probably is the issue.
Yet I did not verify whether, but assume that this will fix the situation:

https://mariadb.com/kb/en/library/time-zones/
https://mariadb.com/kb/en/library/mysql_tzinfo_to_sql/

Since the documentation states:

> By default, the mysql time zone tables are created, but not populated. It is usually preferable for the system to handle the time zone, ...

I wonder, whether it would be reasonable and possible, for nZEDb to leave the connection time zone untouched, if it is set to SYSTEM:

```
MariaDB [(none)]> SELECT @@global.time_zone as global, @@session.time_zone as session;
+--------+---------+
| global | session |
+--------+---------+
| SYSTEM | SYSTEM  |
+--------+---------+

```

**Comment by niel** [comment]
Leaving the connection TZ unset is not an option. The reason for this is when your server is set to SYSTEM, it's not possible for us to determine what your actual zone is, so we have to set it on the connection so we can work with a known value.

**Comment by LuckyFellow** [comment]
I can confirm, that importing the time zone data into the mysql time zone tables solve the issue.
