### ISSUE TITLE
/install/stepX.php are unprotected accessible

### ISSUE THREAD

**Issue by LuckyFellow** [nZEDb/nZEDb#2544]
The URLs
/install/step1.php
/install/step2.php
/install/step3.php
/install/step4.php
/install/step5.php
/install/step6.php
/install/step7.php

are unprotected accessible and expose sensitive data, if some setup has been done.

It would be nice, if there was some sort of protection for the while /install folder.

At least in the install docs should be a big hint to protect / remove that folder from the public after setup completion.

**Comment by Flashbert** [comment]
Points to install/index.php and says:

Installation Locked! If reinstalling, please remove nZEDb/configuration/install.lock.

What do you mean?

**Comment by LuckyFellow** [comment]
You are right. I can't reproduce the behaviour anymore.
Possibly the install.lock file was missing during my tests.
