### ISSUE TITLE
index.php maintenance mode and broken site access

### ISSUE THREAD

**Issue by scottia** [nZEDb/nZEDb#2545]
Running dev 

All TMUX panes show "No connection defined" However, TMUX would run BUT site access showing "No connection defined" on a white page.

PHP Errror thrown as follows when accessing site >

[10-Nov-2017 17:57:07 US/Central] PHP Fatal error:  Uncaught Error: Class 'Misc' not found in /var/www/nZEDb/www/index.php:4
Stack trace:
#0 {main}
  thrown in /var/www/nZEDb/www/index.php on line 4

Resolved Site access showing "No connection defined" by removing line 4 from index.php

nZEDb/www/index.php Line 4
Misc::maintainanceCheck();

All TMUX panes still show "No connection defined" but processing, headers etc. are still working correctly.

**Comment by scottia** [comment]
Resolved  "No connection defined" by updating settings.php.  My Bad :)

Index.php still throwing a line 4 exception ; Line 4 reads  Misc::maintainanceCheck();

I have commented it out in order for site to load.  Here is the error ;

[11-Nov-2017 08:38:56 US/Central] PHP Fatal error:  Uncaught Error: Class 'Misc' not found in /var/www/nZEDb/www/index.php:4
Stack trace:
#0 {main}
  thrown in /var/www/nZEDb/www/index.php on line 4

**Comment by scottia** [comment]
I'll add that I can't change settings.php define('nZEDb_SETTINGS_FILE_VERSION', 4); to Version 5 without getting the Out of Date settings error.  settings.example.php is showing version 5

**Comment by niel** [comment]
Just pushed a potential fix for this to dev.

**Comment by scottia** [comment]
settings.php is good now.  Thanks for the fix.

Index.php still throwing a line 4 exception ; Line 4 reads Misc::maintainanceCheck();

I have it commented out in order to load site.

**Comment by niel** [comment]
@scottia I'll check that Misc::maintainanceCheck(); exception

**Comment by niel** [comment]
@scottia I'm not seeing any problems from index.php. Nothing in the logs at all.
If you're still seeing it, can you provide the stacktrace from the logs.

**Comment by scottia** [comment]
@niel 

Yes, still occurring.  Here is the most recent error.  Same as before 

[12-Nov-2017 19:47:39 US/Central] PHP Fatal error:  Uncaught Error: Class 'Misc' not found in /var/www/nZEDb/www/index.php:4
Stack trace:
#0 {main}
  thrown in /var/www/nZEDb/www/index.php on line 4

**Comment by niel** [comment]
Ok. Just pushed a fix for that. Weird that I don't see any problems, pretty sure I should have, but I'm not going to waste time thinking more on that. ;-)

**Comment by scottia** [comment]
That did the trick.  Thank you @niel
