### ISSUE TITLE
Weird queries

### ISSUE THREAD

**Issue by ghost** [nZEDb/nZEDb#2547]
I saw my load go up from 6 to 18+ and noticed lots of these:

`SELECT * FROM users WHERE LOWER(username) = LOWER('someemailaddrhere@gmail.com') LIMIT 1`

Why the heck is it searching for an e-mail address in the username field? Also those LOWER() functions should be replaced with strtolower() in PHP as per: https://github.com/nZEDb/nZEDb/issues/2437

Also I see a shitload of these:

`SELECT * FROM users WHERE LOWER(email) = LOWER('blablablabla@hotmail.com')  LIMIT 1`

Whenever I run those queries I get no results. When looking up that e-mail address in my users table manually it does not exist. So I'm curious where that comes from.

**Comment by ghost** [comment]
Okay turns out I was being attacked on the /login page. Explains that.

**Comment by niel** [comment]
Updated the queries.

**Comment by ghost** [comment]
That was quick, cheers :-)
