### ISSUE TITLE
API issues (after last update) (SONARR/COUCH)

### ISSUE THREAD

**Issue by dilbaggins** [nZEDb/nZEDb#2548]
###Expected behaviour
api calls to work

###Actual behaviour
**SONARR: this error:  An error occurred while processing feed. https://DILDOSSERVER/api?t=tvsearch&cat=5030,5040,5999&extended=1&apikey=(removed)&offset=0&limit=100: Data at the root level is invalid. Line 1, position 1.**
** COUCH ERROR
[edia._base.providers.base] Invalid XML returned, check "https://DILDOSERVER/api?imdbid=0093713&apikey=xxx&t=movie&extended=1&cat=2000" manually for issues**

if i go to the default api url:

**This page contains the following errors:
error on line 1 at column 1: Document is empty
Below is a rendering of the page up to the first error.**

###Steps to reproduce the behaviour
1) update to latest dev
2) enter in api details as normal in sonarr, etc.
3) languish in a pit of woe.

**Comment by niel** [comment]
I'll need to see the actual data returned for the request. Feel free to PM me in IRC.

**Comment by dilbaggins** [comment]
thought i could get away with just changing my settings file from 4 to 5 (had settings for phpmailer, SPHINX, etc) and got lazy.  thx @niel
