### ISSUE TITLE
Errors during NFO processing, lot's of them....

### ISSUE THREAD

**Issue by stevenmcastano** [nZEDb/nZEDb#2550]
When my post processing script runs, I get a bunch of errors and at times a lot of garbage on the screen almost like it's the contents of a binary file, then it starts to mess up the entire tmux display.

Things like this:

```
There are 3 process(es) still active with 3 job(s) left in the queue.
Downloaded: (xB) = yEnc article, f= Failed ;Processing: z = ZIP file, r = RAR file
Added: s = Sample image, j = JPEG image, A = Audio sample, a = Audio MediaInfo, v = Video sample
sh: 1: Syntax error: word unexpected (expecting ")")
sh: 3: Syntax error: ")" unexpected
sh: 1: Syntax error: word unexpected (expecting ")")
sh: 3: Syntax error: ")" unexpected
sh: 1: Syntax error: word unexpected (expecting ")")
sh: 1: Syntax error: word unexpected (expecting ")")
sh: 3: Syntax error: ")" unexpected
Process ID #45056 has completed.
```

**Comment by niel** [comment]
Have you modified anything? Those look like bash script errors.

**Comment by stevenmcastano** [comment]
They do appear to be bash script errors, but no I haven’t modified anything. This is a pure brand new install on Ubuntu 16.04 that was just completed a few days ago. I’m starting to reindex all my groups and attempting to backfill for only about the 2 - 3 months that I was down, then I’m going to import all of my old NZBs which is basically as far back as my provider goes for about 300 groups.

*SMC

**Comment by niel** [comment]
can you try to narrow down where the errors are occurring please. Try your error logs first. If there's nothing there try disabling scripts (like backfilling) to see if/when the errors stop. It would also help to know if this is with tmux, and if so, in what tab/pane the errors show.

**Comment by stevenmcastano** [comment]
It is with tmux, it’s in the”2:post” window, top pane. “Multi-processing for PostProcess_nfo” step.

I get things like this:



I have disabled backfilling, even updating, it seems like it’s only with the NFO processing… I’m try to look in error logs, but I’m not really seeing anything. Any idea on where exactly to look?

**Comment by niel** [comment]
get things like what?

Now I know where to look, I can keep an eye on my test machine.

**Comment by stevenmcastano** [comment]
![screen shot 2017-11-17 at 3 21 07 pm](https://user-images.githubusercontent.com/6171444/32972399-3fd52f1e-cbc0-11e7-9d53-4064dfc717f4.png)

Sorry, screen shot didn't post via email reply. Lots of errors like the ones above... as well as ones where it looks like binary data is being confused with a file name or some sort of text output like this:

![screen shot 2017-11-17 at 5 54 14 pm](https://user-images.githubusercontent.com/6171444/32972451-7171ea80-cbc0-11e7-87a6-eec7312d7e03.png)

**Comment by niel** [comment]
thanks for the update. those screen shots will give me something to look for.

**Comment by ghost** [comment]
Do you use yydecode?

**Comment by niel** [comment]
@stevenmcastano I'll echo Fossil's question. Which method are you using for yEnc decoding? yydecode is the only one that would obviously run in a bash environment, so the answer could shed light on the problem.

**Comment by stevenmcastano** [comment]
Yes "yydecode-0.2.10”… is there a better option or way to stop this??

*SMC

**Comment by ghost** [comment]
Yes use php-yenc. yydecode is shit.

**Comment by niel** [comment]
yydecode is deprecated. I'll be removing support for it soon, because of the problems it causes.
