### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError: Argument 2 passed to nzedb\SphinxSearch::updateRelease()

### ISSUE THREAD

**Issue by itsecbern** [nZEDb/nZEDb#2551]
###Expected behaviour
Resetting "Search Names" for already existing releases, after creating the correct Release-Naming Regexes.

###Actual behaviour
michael@blackNET-indexer-v3:/var/www/nZEDb/misc$ php testing/Release/resetSearchname.php reset
Going to reset search names, this can take a while.
PHP Fatal error:  Uncaught TypeError: Argument 2 passed to nzedb\SphinxSearch::updateRelease() must be an instance of nzed                                      b\db\DB, none given, called in /var/www/nZEDb/misc/testing/Release/resetSearchname.php on line 113 and defined in /var/www                                      /nZEDb/nzedb/SphinxSearch.php:106
Stack trace:
#0 /var/www/nZEDb/misc/testing/Release/resetSearchname.php(113): nzedb\SphinxSearch->updateRelease('1990')
#1 {main}
  thrown in /var/www/nZEDb/nzedb/SphinxSearch.php on line 106

###Steps to reproduce the behaviour
By executing:
michael@blackNET-indexer-v3:/var/www/nZEDb/misc$ php testing/Release/resetSearchname.php reset

**Comment by itsecbern** [comment]
The Same is as well happening with the "full option":

```
michael@blackNET-indexer-v3:/var/www/nZEDb/misc$ php testing/Release/resetSearchname.php full
Going to recreate all search names, recategorize them and fix the names with namefixer, this can take a while.
PHP Fatal error:  Uncaught TypeError: Argument 2 passed to nzedb\SphinxSearch::updateRelease() must be an instance of nzed                                      b\db\DB, none given, called in /var/www/nZEDb/misc/testing/Release/resetSearchname.php on line 37 and defined in /var/www/                                      nZEDb/nzedb/SphinxSearch.php:106
Stack trace:
#0 /var/www/nZEDb/misc/testing/Release/resetSearchname.php(37): nzedb\SphinxSearch->updateRelease('1990')
#1 {main}
  thrown in /var/www/nZEDb/nzedb/SphinxSearch.php on line 106

```

**Comment by niel** [comment]
try changing line 113 of that script (/var/www/nZEDb/misc/testing/Release/resetSearchname.php) to read:
$sphinx->updateRelease($row['id'], $pdo);

If that works, I'll commit it to dev.

**Comment by niel** [comment]
If that works, I'll commit it to dev.

**Comment by itsecbern** [comment]
Thank you, for your fast help! It worked! 

Additional I changed the same on line 37, so now as well the "full" option is working!
-> As Hint, maybe there is a liddle bug, when using the option "resetSearchname.php **full**" ; because I saw, that after this command all privious well categorised series, went to the others section (HD as well as 3D, SD)

Cheers Michael

**Comment by niel** [comment]
Pushed the fix, for both lines, to dev branch.
I have no idea how/when that got broken.
