### ISSUE TITLE
Warning: Nzb is broken ( is has not header content)

### ISSUE THREAD

**Issue by hondnl** [nZEDb/nZEDb#2554]
Hi ,

I am getting more and more  
`Warning: Nzb is broken ( is has not header content) for GUID :guidnumber`

In Additional post-processing  ( tmux) .

What could that be?

**Comment by niel** [comment]
It means the NZB was saved to the disc without the list of headers needed for download and this is noticed when PPA tries to count the number of files the headers refers to.
We haven't determined why the headers are missing yet, we're still looking into it.

**Comment by egyptianbman** [comment]
Any luck on this? I'm getting it also (a lot).

**Comment by niel** [comment]
No progress so far.
@egyptianbman If you get this a lot run the script to clear broken NZBs and their releases.
