### ISSUE TITLE
verify_time_settings.php need to updated for php7 and nginx

### ISSUE THREAD

**Issue by DrakeJones** [nZEDb/nZEDb#2557]
###Expected behaviour
Execute 'verify_time_settings.php' - get tz setting verifications.

###Actual behaviour
Shows error even if tz settings are correct.  Also, System Time has no zero preceding single digit day values, MySQL and PHP Times do (at least with Debian 9) - may also be causing false error msg

###Steps to reproduce the behaviour
run 'verify_time_settings.php' on machine with no php5 install

**Comment by niel** [comment]
After spending far too much time looking how to fix this, I've realised it doesn't need fixing. It needs removing, as there is no purpose to it in the current context.
The various differences in time settings are now irrelevant, due to how we handle time in the code.
I'll be removing this script.

**Comment by DrakeJones** [comment]
Sorry that you spent so much time on it, Niel.  That script helped me with an issue a couple of years ago. I didn't know if it mattered any longer or not.  Thank you.

**Comment by niel** [comment]
No problem. 
Couple years ago, it mattered. A few months ago I added code to make our end set a timezone on the mysql connection to match the PHP timezone. That bypasses most of the problems involved with timezones.
