### ISSUE TITLE
No connection defined

### ISSUE THREAD

**Issue by thesneakernet01** [nZEDb/nZEDb#2558]
###Expected behaviour
Expected web pages to load correctly and update scripts to update correctly

###Actual behaviour
Get "No connection defined" errors for both update scripts and web pages to load correctly.

###Steps to reproduce the behaviour
Clean install on Ubuntu 16.04 LTS with php 7.0.22 and mariadb.  Installed pre-reqs, ran the install script in _install and checked to make composer was correctly installed.  Permissions are correct for the whole folder.  ./zed update all also errors with "No connection defined"  Also happens after running ./zed update all on a working site as well.

**Comment by kaibosh** [comment]
There's a few incomplete guides for this OS. Which one did you follow?

It's worth checking the DB params in configuration/config.php.

If those look fine, try enabling the debug logging in configuration/settings.php and look for log file output in resources/logs/.

**Comment by thesneakernet01** [comment]
I've had this happen on a previously working installation that I ran ./zed update all on and on a new installation that started having the problem right away.  I'm able to go through the whole installation process, it creates the database and i can login. I just can't leverage the API to Sonarr or Radarr via the API.  I'll turn on debug logging and see if I get any additional errors.  I'll also dig up the install guide I used.

**Comment by niel** [comment]
Updated the stable branch (0.x) with a fix for this. Please test and let me know if it works for you.

**Comment by forkless** [comment]
I am having the same issue, this didn't fix it for me unfortunately. 

EDIT: I just noticed it didn't write a config.php when it arrived at step 2. I presume it should have? I looked at the permissions which look all fine.

**Comment by forkless** [comment]
Never mind, I fixed it. I forgot to import the TZ table into Maria DB using

`mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql`

**Comment by thesneakernet01** [comment]
This has indeed fixed the problem!  Thanks for the quick fix!
