### ISSUE TITLE
&season=3 does not return results

### ISSUE THREAD

**Issue by ghost** [nZEDb/nZEDb#2560]
## Expected behaviour
`/api?q=Crazy.Ex-Girlfriend&apikey=xxxxx&limit=100&t=tvsearch&season=3&maxage=500&cat=5030%2C5040` to return Season 03 releases.

## Actual behaviour
Zero releases.

## Steps to reproduce the behavior
If you strip the &season=3 out of the URL then there are Season 3 episodes being returned which are also correctly seen as Season 03 in the DB.

**Comment by niel** [comment]
Looks like this might be deliberate. As far as I can see in the code, it assumes that a series without episode  is a search for Season Packs and ignores individual episodes.
Not sure why it is that way though.

**Comment by ghost** [comment]
Ah so they need to add &episode= to the query?

**Comment by niel** [comment]
I don't think that would work. The code checks for series equals something and episode doesn't equal anything.
https://github.com/nZEDb/nZEDb/blob/0.x/nzedb/Releases.php#L963

**Comment by ghost** [comment]
Just tried, works when you add &ep=2 for example.

**Comment by niel** [comment]
Does it return all the episodes or just episode 2?

**Comment by ghost** [comment]
Just 2.

**Comment by niel** [comment]
Thought so. Not exactly what you want if you're trying to cut out other series from the search.

**Comment by ghost** [comment]
? It works as expected when you add the episode.

**Comment by niel** [comment]
lol yeah, but not as expected without.

**Comment by ghost** [comment]
Affirmative :)

**Comment by niel** [comment]
I don't see this changing anytime soon. Not until the entire DB access has been switched to model based code.

**Comment by ghost** [comment]
Im fine with the way it is.
