### ISSUE TITLE
Issue with Dev and Sphinx Releases

### ISSUE THREAD

**Issue by dilbaggins** [nZEDb/nZEDb#2563]
###Expected behaviour
click a release and see detail

###Actual behaviour
no details

###Steps to reproduce the behaviour
patch to latest dev.
click a release
see this issue:  SQLSTATE[HY000]: General error: 1430 There was a problem processing the query on the foreign data source. Data source error: searchd error: index releases_rt: query is non-computable (singl

i recreated the releases table and everything

**Comment by dilbaggins** [comment]
Sphinx Version:  Sphinx 2.2.11-id64-release (95ae9a6)
Copyright (c) 2001-2016, Andrew Aksyonoff
Copyright (c) 2008-2016, Sphinx Technologies Inc (http://sphinxsearch.com)

mysql  Ver 15.1 Distrib 10.2.11-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

using the Sphinx Engine

**Comment by Wally73** [comment]
mmm i think its just maybe with a few releases as i've clicked 150 of my releases and have no issues at all with sphinx

**Comment by dilbaggins** [comment]
try with odd ones such as `
[01/47] - "A.Good.Day.To.Die.Hard.2013.720p.BluRay.x264-x0r.nfo` or `(????) [01/98] - "Transformers-`
which regex dont seem to fix.

**Comment by ollie9999** [comment]
Having the same problem.
When Sphinx is enabled I get SQLSTATE[HY000]: General error: 1430 generated for releases that have minus sign in first part of search name field. Example: "Dodgeball - A True Underdog Story 2004 Unrated 1080p Blu-ray Remux AVC DTS-HD MA 5.1 - KRaLiMaRKo" trigger SQL error, but "Dodgeball # A True Underdog Story 2004 Unrated 1080p Blu-ray Remux AVC DTS-HD MA 5.1 - KRaLiMaRKo" works.

**Comment by danpop-chainguard** [comment]
any updates on this?  @niel

**Comment by niel** [comment]
@danpopSD No updates as I haven't had time to look. I'm assuming, until shown otherwise, that this has something to do with the way Sphinx handles special characters.

**Comment by DariusIII** [comment]
This is a sphinxsearch issue, not MySQL one.
