### ISSUE TITLE
nfo downloads failing

### ISSUE THREAD

**Issue by EDChurly** [nZEDb/nZEDb#2566]
###Expected behaviour
See some + for downloaded nfo's

###Actual behaviour
All nfo's are showing up as "f"

###Steps to reproduce the behaviour
run misc/update/postprocess nfo true

In short, I'm sure this is something I've done, but for the life of my I cannot figure it out.

In post process, either in tmux or cli, I get the following.

:/var/www/nZEDb/misc/update# php postprocess.php nfo true

Processing 100 NFO(s), starting at 100 * = hidden NFO, + = NFO, - = no NFO, f = download failed.

Available to process, -5 = 1, -3 = 15, -2 = 63, -1 = 230.
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff----------------------

No nfo's are being downloaded.
Using php7.0-yenc, also tried the default php yenc decoder.
Tried rarinfo and unrar... 
Checked permissions.

... Nothing.

Running v0.8.3.0.

Any suggestions?  Enabled all logging but couldnt see anything in a log that shows a php error or other explanation.

**Comment by niel** [comment]
Is this for current releases or for backfilling?

**Comment by EDChurly** [comment]
Backfilling a few groups.   I think its an issue with php7.0-yenc - I must have not removed it properly previously,  having removed it now, getting nfo's with the default php yenc decoder.   Reinstalling php7.0-yenc now to see if the failures return.

**Comment by EDChurly** [comment]
using https://github.com/niel/php-yenc/releases/download/v1.3.0/php7.0-yenc_1.3.0_amd64.deb 
php -v = PHP 7.0.27-1+ubuntu14.04.1+deb.sury.org+1

**Comment by niel** [comment]
Also realise that backfilling may have a lot of failures due to DMCAs on the releases.
I'm unable to check this currently as my test server is down while I move all the files to a new drive, it's taking forever because of the NZBs. As soon as that is done I'll have a few days of catch up to do myself so I'll be able to test then.

**Comment by EDChurly** [comment]
No rush now, have a work around.  Will let you know if the failures come back.

**Comment by EDChurly** [comment]
Btw - the error came back - running without yenc for now.

**Comment by Wally73** [comment]
when you use php7.x you really don't need php-yenc anymore period 
php's own is as fast as the old yenc-decode was if not faster
