### ISSUE TITLE
lithium fresh install issue.

### ISSUE THREAD

**Issue by m0rse** [nZEDb/nZEDb#2567]
###install fresh 0.x also dev

###step 2
`PHP Fatal error:  Uncaught lithium\core\ConfigException: The data connection `default` is not configured for model `app\models\Settings`. in /****/libraries/lithium/data/Model.php:1470`

` /*****/libraries/lithium/data/Model.php(659): lithium\data\Model::connection()
 /*****/app/models/Settings.php(176): lithium\data\Model::lithium\data\{closure}(Array)
/*****/libraries/lithium/data/Model.php(679): app\models\Settings::app\models\{closure}(Array, Object(Closure))
 /*****/libraries/lithium/aop/Filters.php(231): lithium\data\Model::lithium\data\{closure}(Array)
 /*********/libraries/lithium/data/Model.php(682): lithium\aop\Filters::run('app\\models\\Sett...', 'find', Array, Object(Closure))
 /*****/app/models/Settings.php(253): lithium\data\Model::find('setting', Array)
 /******/app/config/bootstrap/yenc.php(44): app\models\Settings::value('apps..yydecoder...', true)
/******/app/config/bootstrap.php(92): require_once('/********/a...')
/** in /******/libraries/lithium/data/Model.php on line 1470`

###fresh install

**Comment by niel** [comment]
Will need more info than that. What guide were you following for example? Are you sure you haven't missed any steps?
Are you using Apache or nginx?

**Comment by niel** [comment]
I'm looking into this, but it appears that for no explicable reason testing for a file works with shell run scripts, but NOT for web run scripts. So the indexer runs just fine, but the web site, including installing, gets screwed up.

**Comment by niel** [comment]
Ok, turns out it that was a file permission issue for the web user. Check your permissions for files in .../configuration/ particularly install.lock and config.php

**Comment by m0rse** [comment]
thank you
