### ISSUE TITLE
predb release gets sometimes matched to wrong releases

### ISSUE THREAD

**Issue by hansenhans** [nZEDb/nZEDb#2568]
###Expected behaviour
releases from preDB should be matched to releases if the name matches the hash.

###Actual behaviour
from time to time there are predb releases which get matched to completely wrong releases, sometimes even hundreds of times 

###Steps to reproduce the behaviour
one example:

```
SELECT id FROM predb WHERE title LIKE "Various.Artists.-.Smash.Hits.80s.Mixtape.[2017].[Mixtape]";
+---------+
| id      |
+---------+
| 9111335 |
+---------+
SELECT name FROM releases WHERE predb_id = 9111335;
+--------------------------------------------------------------------------------------------------------------------------------------------------+
| name                                                                                                                                             |
+--------------------------------------------------------------------------------------------------------------------------------------------------+
| Wolfgang Haffner - Kind Of Cool (2015) wav [2 of 16] "Kind Of Cool.part02.rar" yEnc                                                              |
| Jason Seizer - Cinema Paradiso (2014) [3 of 15] "Cinema Paradiso.part03.rar" yEnc                                                                |
| Songs: Ohia - The Lioness (2000) wav [11 of 14] "The Lioness.part0.vol07+8.par2" yEnc                                                            |
| Rachelle Ferrell - First Instrument (1990) wav [2 of 16] "First Instrument.part02.rar" yEnc                                                      |
| Dieter Ilg - Mein Beethoven (2015) wav [2 of 16] "Mein Beethoven.part02.rar" yEnc                                                                |
| Osmoze - Osmoze (NMR) [03/17] - "02 The Fire Mith.flac" yEnc                                                                                     |
| trtk13433 - [01/25] - "The Dreadnought - Legends Never Die (2007)(flac).par2" yEnc                                                               |
| Avishai Cohen Trio - From Darkness (2015) wav [4 of 14] "From Darkness.part04.rar" yEnc                                                          |
| Leonard Cohen - Live In Dublin (2014) wav [3 of 34] "Live In Dublin.part03.rar" yEnc                                                             |
| Antonio Forcione - Tears Of Joy (2005) wav (24-44.1) [7 of 22] "Tears Of Joy.part07.rar" yEnc                                                    |
| Cassandra Wilson - Coming Forth By Day (2015) [1 of 16] "Coming Forth By Day.part01.rar" yEnc                                                    |
| trtk14113 - [02/18] - "Josh Groban - Stages (Deluxe Edition) (2015)(flac).part01.rar" yEnc                                                       |
| trtk13630 - [02/15] - "Mantovani - Strauss Waltzes (1958)(899).part1.rar" yEnc                                                                   |
| trtk13602 - [05/30] - "Dire Straits & Mark Knopfler - Greatest Hits (2014)(flac24bits).part04.rar" yEnc                                          |
| trtk13570 - [07/23] - "VA - Lounge Set Mauritius (40 Tunes for Your Relax) (2015)(flac).part06.rar" yEnc  
...
```

**Comment by niel** [comment]
I'm not seeing this. I can't verify your example as I'm not indexing whatever group those entries are from.

**Comment by Bart39** [comment]
its a flaw in matching predb filenames

```
New name:  Various.Artists.-.Smash.Hits.80s.Mixtape.[2017].[Mixtape]
Old name:  Charley Patton - Complete Recorded Works, Vol. 3 (1990)
Use name:  Charley Patton - Complete Recorded Works, Vol. 3 (1990) [01/29] - "Charley Patton - Complete Recorded Works, Vol. 3 (1990).sfv" yEnc
New cat:   Audio->Lossless
Old cat:   Audio->Lossless
Group:     alt.binaries.sounds.lossless
Method:    PreDB file match, file matched source: m2v.ru
ReleaseID: 13692
Filename:  Folder

```
"Folder" is too common a match
we should either exclude common words from trying to match or maybe only match over a certain length filename

**Comment by JReming85** [comment]
Goto predb table and remove all the "common" filenames

Few I have found are:

Folder
Front
Sample
NFO
info

There are a few others I cant think of atm but that should stop a good amount

**Comment by niel** [comment]
@Bart39  Can you explain this further? An idea of where and how this is happening would help a lot toward tracking it down and fixing it.

**Comment by DariusIII** [comment]
These predb matches come from m2v.ru. They have common names as their filenames and we are matching them for some reason to a wrong release because of that.

**Comment by JReming85** [comment]
Few more 
Cover
Covers
autorun
image
Oriental.1001
reload
reloaded
setup

Most of these are old badly created matches from m2v as @DariusIII stated,  Lets hope they dont get lazy on filenames in the future

**Comment by niel** [comment]
Thanks for replying, but this doesn't answer my question of *where* or *how* this happens. Last time I tackled a renaming problem I spent most of a week tracking through the code. I'm not about to do that again without a better idea of where to start, as I could be doing many other things in that time.

**Comment by JReming85** [comment]
It matches from match_prefiles.php

If you have your setup extract files and list them, match_prefiles.php will then attempt to match them with the predb table using the extracted filenames.

Not 100% on this but it seems to take the first filename it gets and matches to the first listing in the table, as I have seen several of the same filenames in the predb table, but all the false matching goes to the same entry

**Comment by DariusIII** [comment]
What i did in NNTmux is adding the following:

https://github.com/NNTmux/newznab-tmux/blob/master/Blacklight/NameFixer.php#L1206-L1207

```
similar_text($preMatch[1], $preFtMatch[1], $percent);
                                if ($percent >= 93) {
```

**Comment by JReming85** [comment]
I know for some of them the only way is to delete them from the table.

I think setup was one of them with 7-8 entries with that filename, and no matter what it would always match to the first one, when none of them were correct.

Pretty much all the ones I have listed, I have found by having it match incorrectly within the past 2-3 months.  Also I think the newest one it matched to was from early 2016/2017

**Comment by Bart39** [comment]
https://github.com/nZEDb/nZEDb/blob/0.x/nzedb/NameFixer.php#L920

as above comments, crap common filenames are being stored from ircscraper (mainly m2v) and then matched incorrectly against by matchPredbFiles

**Comment by niel** [comment]
Committed some changes to dev branch. Please let me know if this helps or not.

**Comment by Sweepr** [comment]
Problem running match_prefiles.php with latest release:

php /home/public_html/misc/update/match_prefiles.php 50 show

Match PreFiles (50) Started at 2:49:46
Matching predb filename to cleaned release_files.name.

50 releases to process.

Finishes within a split-second, but error_log show this:

[08-Dec-2018 14:49:46 Europe/Amsterdam] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to nzedb\NameFixer::nzedb\{closure}() must be of the type string, null given, called in /home/public_html/nzedb/NameFixer.php on line 929 and defined in /home/public_html/nzedb/NameFixer.php:915
Stack trace:
#0 /home/public_html/nzedb/NameFixer.php(929): nzedb\NameFixer->nzedb\{closure}(NULL)
#1 /home/public_html/nzedb/NameFixer.php(877): nzedb\NameFixer->matchPredbFiles(Array, 1, 1, true, 1)
#2 /home/public_html/misc/update/match_prefiles.php(22): nzedb\NameFixer->getPreFileNames(Array)
#3 {main}
  thrown in /home/public_html/nzedb/NameFixer.php on line 915

**Comment by niel** [comment]
@Sweepr please file that as a separate bug report.
