### ISSUE TITLE
Big Brother isn't being matched to a show

### ISSUE THREAD

**Issue by lawsontyler** [nZEDb/nZEDb#2570]
###Expected behaviour
Releases in alt.binaries.tv.big-brother are matched to the correct TV show

###Actual behaviour
Nothing in this group gets matched at all.
Releases' `searchname` look like:

BB10US Day 34 - Live Feed - Cam 1 & 3 - #Big-Brother @ EFNet [00/29] - "bb10.us.live.feed.cam1_cam3.day34.nzb"

or

CBB21UK E24a Daily [01/17] - "Celebrity.Big.Brother.UK.S21E24a.Daily.HDTV.x264-PLUTONiUM.par2"

###Steps to reproduce the behaviour
Activate alt.binaries.tv.big-brother and backfill a little.

**Comment by niel** [comment]
We don't provide a regex for matching in this group, you will have to create one yourself.
If you provide a PR for it we can include it in the code.
