### ISSUE TITLE
SQLSTATE 22001 String Data Truncated (xref column)

### ISSUE THREAD

**Issue by AlienXAXS** [nZEDb/nZEDb#2572]
###Expected behaviour
The error not to appear

###Actual behaviour
The following error spams the heck out of the Update Binaries and Backfill panes:
Error: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'xref' at row 1

###Steps to reproduce the behaviour
Run tmux start.php and wait

Any ideas?

**Comment by DariusIII** [comment]
Its not an error, it is just mysql informing you that data in xref has been truncated to allowed length. This happens because we are adding  crossposted groups to xref column, and sometimes duplicates cause this behaviour.

**Comment by AlienXAXS** [comment]
Thanks for the fast response, is it possible to stop this error from being reported in the tmux panes as it's spamming so quickly i cannot see the actual output.

**Comment by DariusIII** [comment]
I think there is an option to add to my.cnf that removes these errors.

**Comment by AlienXAXS** [comment]
Alright i'll have a google :)
