### ISSUE TITLE
Tmux Panes missing

### ISSUE THREAD

**Issue by vidschofelix** [nZEDb/nZEDb#2573]
Since i killed my tmux session with kill -9 "pid" i miss two panes after executing php start.php. 
I already checked database and everything seems fine to me from this point of view. Does anyone has an idea how i can fix this or is this just normal behavior? 
OS: centos 7.4 and tmux 1.8, switching to tmux 2.3 did not help

![image](https://user-images.githubusercontent.com/8752158/37026560-15c884ae-212f-11e8-8e7c-2f3c01ca6e3e.png)

**Comment by DariusIII** [comment]
Those are not missing, you switched on sequential mode.

**Comment by vidschofelix** [comment]
I did not change anything regarding tmux settings in admin panel i will check this thank you

You were right i had the setting run basic sequential enabled but on fiirst run tmux was not in sequential mode even with basic sequential setting enabled . I disabled it now and panes are back thank you.

Can be closed, thanks
