### ISSUE TITLE
zed verify settings_table returns strange output

### ISSUE THREAD

**Issue by garrettben** [nZEDb/nZEDb#2574]
###Expected behaviour

`zed verify settings_table` should return verification of the settings table and tests

###Actual behaviour

returns output preceded by the following:

```
object(lithium\console\Request)#24 (8) {
  ["argv"]=>
  array(2) {
    [0]=>
    string(6) "verify"
    [1]=>
    string(14) "settings_table"
  }
  ["params"]=>
  array(3) {
    ["command"]=>
    string(6) "verify"
    ["action"]=>
    string(14) "settings_table"
    ["args"]=>
    array(0) {
    }
  }
```

(see https://pastebin.com/tB2KdKS3 for full output)

###Steps to reproduce the behaviour

Any newly installed nZEDb on ubuntu 16.04, either from dev or 0.x branch
composer 1.6.3
PHP 7.0.28-0ubuntu0.16.04.1 (cli)
mariadb-server 10.0.34-0ubuntu0.16.04.1

**Comment by niel** [comment]
That is debugging info that should have only been shown if nZEDb_DEBUG or nZEDb_LOGGING are true. I have fixed the code in dev branch to enforce that now.

BTW the syntax for what you are trying has changed. Do:

./zed verify table Settings

Make sure you get the case of the 'S' correct. The command now takes a table name as its argument and 'settings' is a different table to 'Settings'. In time I'll add other tables that can be verified, and this change will make that much easier.

**Comment by garrettben** [comment]
Thanks, Niel.  I ran `./zed verify table Settings` without problems.

Closing issue.
