### ISSUE TITLE
no new releases since enabling mgr

### ISSUE THREAD

**Issue by hansenhans** [nZEDb/nZEDb#2575]
###Expected behaviour
new releases being created

###Actual behaviour
No new releases are getting created since enabling mgr. The process hangs and gets killed after "running too long"

###Steps to reproduce the behaviour
enable mgr and fetch header then run releases.php and it reports something like this

```
Multi-processing started at Wed, 25 Apr 2018 11:58:07 +0100 for releases with 19 job(s) to do using a max of 1 child process(es).
Process Releases -> Attempting to find complete collections.
Deleted 23 broken/stuck collections.
0 collections were found to be complete. Time: 0 second(s)

Process Releases -> Calculating collection sizes (in bytes).
0 collections set to filecheck = 3(size calculated)
0 second(s)

Process Releases -> Delete collections smaller/larger than minimum size/file count from group/site setting.
Deleted 0 collections: 
0 smaller than, 0 bigger than, 0 with less files than site/group settings in: 0 second(s)

Process Releases -> Create releases from complete collections.
0 Collections ready to be converted to releases.

0 Releases added and 0 duplicate collections deleted in 0 second(s)

Process Releases -> Create the NZB, delete collections/binaries/parts.
Force kill 16737 has run too long
Process ID #16737 has completed.
There are 0 process(es) still active with 18 job(s) left in the queue.

Process Releases -> Attempting to find complete collections.
Deleted 962 broken/stuck collections.
118 collections were found to be complete. Time: 0 second(s)

Process Releases -> Calculating collection sizes (in bytes).
118 collections set to filecheck = 3(size calculated)
0 second(s)

Process Releases -> Delete collections smaller/larger than minimum size/file count from group/site setting.
Deleted 2328 collections: 
0 smaller than, 0 bigger than, 2328 with less files than site/group settings in: 0 second(s)

Process Releases -> Create releases from complete collections.
52 Collections ready to be converted to releases.
Added 52 releases.
52 Releases added and 0 duplicate collections deleted in 0 second(s)

Process Releases -> Create the NZB, delete collections/binaries/parts.
Force kill 28230 has run too long
Process ID #28230 has completed.
```

**Comment by DariusIII** [comment]
> Process Releases -> Create the NZB, delete collections/binaries/parts.
> Force kill 28230 has run too long
> Process ID #28230 has completed.

The part above is the cause. NZBs are not created because process was killed.

Edit: This is your server/server config error not nZEDb one.

**Comment by hansenhans** [comment]
> NZBs are not created because process was killed.

of course, Sherlock  ;-)

What setting could it be? The script got killed after ~30 minutes, so it can't be the php setting "max_execution_time = 120"
It must be a setting in nZEDb. It can't be one of the tmux settings, as the same happens, when I run it outside tmux. But I can't find it. Or is it hard coded somewhere?

**Comment by niel** [comment]
Reduce the number of headers or groups you are fetching so the creation process does not run so long. I would guess you need to reduce it by a LOT, as it should never take any where near 30 minutes to process.

**Comment by hansenhans** [comment]
Ok, I restored my nZEDB VM from last Sunday's backup and set "max_execution_time = 0". Now it seems to run and releases are created, but I'm getting deadlocks quite frequently .

Do I need to tweak something? And what should max_execution_time be set to? I don't think leaving it at unlimited is a good idea. All guides say 120, but this wasn't enough in my case.

**Comment by hansenhans** [comment]
Deadlocks are gone after switching to "Simple Threaded Update"

**Comment by niel** [comment]
You shouldn't run with max_execution_time = 0. That will allow a single run-a-way script to block the others.

**Comment by hansenhans** [comment]
thanks, I already changed it back to 120 and everything works with "Simple Threaded Update".
