### ISSUE TITLE
SQL Error when inserting collections Error: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'xref' at row 1

### ISSUE THREAD

**Issue by CrunchBite** [nZEDb/nZEDb#2578]
###Expected behaviour
Collections are inserted into database when checking for new posts or backfilling

###Actual behaviour
After articles are received from provider an SQL error is returned for a subset of the articles (some still work!)
```
Getting 20,000 articles from a.b.anime, 0 group(s) left. (221,602 articles in queue).
Received 788KB from group (alt.binaries.anime).
Received 20000 articles of 20,000 requested, 0 blacklisted, 0 not yEnc.
Error: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'xref' at row 1

Error: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'xref' at row 1

Error: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'xref' at row 1
```

###Steps to reproduce the behaviour
I'm seeing this across multiple groups but notably alt.binaries.anime
My provider is newsgroupdirect with compression ON

**Comment by CrunchBite** [comment]
Seems to be solved after running:
```
alter table multigroup_collections MODIFY column xref VARCHAR(4096);
alter table collections_1000075 MODIFY column xref VARCHAR(4096);
alter table collections_1000076 MODIFY column xref VARCHAR(4096);
...
```
(all collections tables have to be altered)
(4096 is overkill but whatever)

**Comment by niel** [comment]
yes, it appears your usenet server has unusually long xref headers. I will create an update to the DB schema to account for a larger field to hold them.

**Comment by DariusIII** [comment]
This error is actually not related to USP xref headers length, but with the way we are inserting them. 

https://github.com/nZEDb/nZEDb/blob/0.x/nzedb/Binaries.php#L922

We update xref to have all the groups release has been posted to.

**Comment by CrunchBite** [comment]
I had to bump that number (255) up as well, forgot to mention that above

**Comment by niel** [comment]
@DariusIII looks like that line is only used for Multigroup, whereas this error was occurring in collections table which isn't used by multigroup. That implies it is USP length that was the problem.
That said, I think the sooner we can refactor that code the better ;-)

**Comment by CrunchBite** [comment]
I keep having to bump these up:

`alter table multigroup_collections MODIFY column xref VARCHAR(16384);`
```PHP
$xref = ($this->multiGroup === true ? sprintf('xref = CONCAT(xref, "\\n"%s ),', $this->_pdo->escapeString(substr($this->header['Xref'], 2, 16000))) : '');
```
EDIT: And all the other collections tables too

**Comment by DariusIII** [comment]
Don't bump them, just ignore these, they are not errors.

**Comment by niel** [comment]
If you have to do the multigroup AND collections tables your install is broken as you should only be using one or the other
