### ISSUE TITLE
error code 300 while trying to download an NZB

### ISSUE THREAD

**Issue by stevenmcastano** [nZEDb/nZEDb#2579]
###Expected behaviour
When a link is clicked to download an NZB via the normal browser UI or the API the nzb file is returned

###Actual behaviour
Instead an error code 300 message is displayed:
```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<error code="300" description="NZB file not found!"/>
```

Any ideas on where this might come from? I've been trying to scan through logs from both the web server and php nzedb logs and I can't seem to find anything out of place.

**Comment by niel** [comment]
This doesn't look like an error at all. It's a response from your nZEDb server telling you that it could not find the nzb file you wanted.
You should check that your NZB files are being created correctly. There is a script that will check releases against saved nzb files and remove any that do not exist.

**Comment by stevenmcastano** [comment]
I think I've mostly resolved the issue, it appears to have been a permissions issue on the root NFS mount folder. It's just with 37 million releases things get really hard to check.

So what script is this that check the releases vs. nzb files? Also, with that meany releases, I have well over 4.6 million files in a single directory which is WAY too many, so I noticed there is the ability to change the NZB depth. Will is still find NZB files while the script is being run to move them? Or should I shut down updates and the site while having the script move everything?

**Comment by niel** [comment]
> It's just with 37 million releases things get really hard to check.

Yup, that's why these scripts exist :-) .../misc/testing/NZBs/
You can run each of them without any parameters to get info on how to use them.
As with any maintenance scripts, stop all other nZEDb scripts before running nzb-rorg.php

**Comment by stevenmcastano** [comment]
Got it handled... pushing it out to 5 levels deep really fixed a bunch of things. Now I'm setting up a new indexer and working on getting rid of a bunch more of the junk so only the good stuff is left over! Thanks!
