### ISSUE TITLE
percona-server-5.7.21-21-sphinx-2.2.9-release-build

### ISSUE THREAD

**Issue by pdachnowicz** [nZEDb/nZEDb#2581]
I have referenced build documents, however compile fails on net.h
fatal error: my_net.h: No such file or directory (which exists)
I have referenced https://github.com/riden/sphinx/tree/mysqlse-mysql-5.7 as well.
to no avail. 

Anybody have a solution or a ha_sphinx.so

thank you

**Comment by niel** [comment]
Sorry but this is not a problem with nZEDb.
Seek support from the percona people, or try asking in the nZEDb forums for community help.
