### ISSUE TITLE
[Question] Remove releases based on category criteria?

### ISSUE THREAD

**Issue by stevenmcastano** [nZEDb/nZEDb#2583]
I've just recently set some new size and min files limits on a few groups, but the biggest one is that I've set minimum sizes for the categories I use the most. Mainly the TV and Movie categories and imposed minimum sizes that vary from 50M up to 250M.

The problem is, I have a ton of releases already, want to import a ton of NZBs from a previous install, and want them all to follow these new limits.

Is there script to go back and impose these new limits, or maybe a SQL query that could be run to properly clean everything out, the just run the clean-nzb script afterwards?

**Comment by Bart39** [comment]
Normal release processing will already do this (assuming your using tmux).
One of the steps it does at the end is to delete unwanted releases based on your settings

**Comment by Bart39** [comment]
https://github.com/nZEDb/nZEDb/blob/0.x/misc/testing/Release/delete_disabled_category_releases.php

This script will remove existing releases for categories you have disabled

**Comment by stevenmcastano** [comment]
Right... this is while the tmux scripts are running and things are updating, but what about retroactively? 


If I up the minimum size for a category, is there anyway to go back and rescan everything that's already there?


Also, do these size settings work on nzb importing?
