### ISSUE TITLE
[IRCScraper] Uncaught Error: Call to a member function log() on null

### ISSUE THREAD

**Issue by jangrewe** [nZEDb/nZEDb#2584]
###Expected behaviour
IRC scraper scrapes

###Actual behaviour
IRC scraper dies

###Steps to reproduce the behaviour
After noticing that the IRC server i was bouncing to has left the network, i tried to get my IRC scraper back to work, but for some reason the pane kept dying.
In the `php_errors_cli.log` i get loads of these errors:
```
[15-Jun-2018 22:49:19 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to a member function log() on null in /srv/nzedb/nzedb/IRCScraper.php:295
Stack trace:
#0 /srv/nzedb/nzedb/IRCScraper.php(274): nzedb\IRCScraper->_checkForDupe()
#1 /srv/nzedb/nzedb/IRCClient.php(432): nzedb\IRCScraper->processChannelMessages()
#2 /srv/nzedb/nzedb/IRCScraper.php(193): nzedb\IRCClient->readIncoming()
#3 /srv/nzedb/nzedb/IRCScraper.php(136): nzedb\IRCScraper->_startScraping()
#4 /srv/nzedb/misc/IRCScraper/scrape.php(50): nzedb\IRCScraper->__construct(false, false)
#5 {main}
  thrown in /srv/nzedb/nzedb/IRCScraper.php on line 295
```
I'm currently on the `dev` branch, current commit.

**Comment by niel** [comment]
Sorry, I can't reproduce this.

Please check your db doesn't have any crashed tables as this is caused first by a failure to insert a new entry, then by the logger not being initialised - which should not be possible.

**Comment by jangrewe** [comment]
I ran a `mysqlcheck -A`, but none of the tables had any errors.

**Comment by jangrewe** [comment]
I'm not sure if i'm ready this correctly, but it does look like the logger is not initialized (class is `NULL`)?
![https://i.snag.gy/lL8sht.jpg](https://i.snag.gy/lL8sht.jpg)

**Comment by niel** [comment]
You are correct, the logger appears not to have been set, which should not be possible as it is initialised when the scraper script starts IRCScraper. This is what the original error message was saying "Uncaught Error: Call to a member function log() on null in /srv/nzedb/nzedb/IRCScraper.php:295"

**Comment by jangrewe** [comment]
As copying from tmux isn't that easy, here's another screenshot:
![https://i.snag.gy/GXqTsx.jpg](https://i.snag.gy/GXqTsx.jpg)

**Comment by jangrewe** [comment]
This errors are cause by an invalid datetime in the INSERT, which now considered an error and not replaced with the default for that field.

It can be mitigated by removing `STRICT_TRANS_TABLES` from the SQL modes, which is one of the default modes since MariaDB 10.2.24.

Temporarily, on the mysql shell:
```
SET sql_mode = 'ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
SET GLOBAL sql_mode = 'ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
```

Permanenty, in your e.g. `/etc/mysql/conf.d/mysqld.cnf`:
```
[mysqld]
sql_mode = 'ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
```
