### ISSUE TITLE
Zed broke after latest dev build.

### ISSUE THREAD

**Issue by dilbaggins** [nZEDb/nZEDb#2585]
###Expected behaviour
zed to work

###Actual behaviour
it doesnt

###Steps to reproduce the behaviour
1) update to latest dev build
2) ./zed version all
./zed: 2: ./zed: pushd: not found
./zed: 3: ./zed: ../libraries/lithium/console/li3: not found
./zed: 4: ./zed: popd: not found

languish in a pit of despair because you can 1) not update nzedb or 2) see what version you are running (db and git wise)

**Comment by niel** [comment]
do you not have bash installed as the default shell?

**Comment by dilbaggins** [comment]
yes of course my default shell is bash... @niel 

:/var/www/nZEDb$ more zed
#!/bin/sh
pushd app
../libraries/lithium/console/li3 "$@"
popd

**Comment by dilbaggins** [comment]
looks like you addressed it but changing from "sh" to "bash"

#!/bin/bash

pushd app
../libraries/lithium/console/li3 "$@"
popd

resolved by patch.....
