### ISSUE TITLE
various issues with groups refactor on dev branch

### ISSUE THREAD

**Issue by Bart39** [nZEDb/nZEDb#2586]
group-list-active.php - missing $page    = new AdminPage();
group-list-inactive.php - incorrect use statement - should be "use app\models\Groups;"

browsegroups.php - returns an empty dataset

**Comment by niel** [comment]
I was unable to find a problem with browsegroups.php, could you provide more details please.

**Comment by Bart39** [comment]
![image](https://user-images.githubusercontent.com/1813305/42245651-679056f0-7f11-11e8-8254-79d9df773ebc.png)

click groupslist from menu - no results

no errors either as far as i can tell

**Comment by niel** [comment]
This is a theme problem. Workaround, switch to default theme while I get the theme(s) fixed, hopefully. As you know I didn't create the themes so this may take a bit.

**Comment by Bart39** [comment]
ok so i see the issue now, non default themes also show the total releases per group which isn't provided by the new model

**Comment by Bart39** [comment]
all fixed with latest update
