### ISSUE TITLE
Setup not possible / HTTP 500 / Smarty-File not found

### ISSUE THREAD

**Issue by sebst3r** [nZEDb/nZEDb#2587]
I want to setup fresh from scratch under Ubuntu, so i followed this guide:

=> https://forums.nzedb.com/index.php?topic=2464.msg13516#msg13516

This site works: http://xxx/install/

When i click next i end up at: http://xxxxx/install/step1.php? which gives a HTTP500

In the apache2 log i see:

[Wed Jul 04 17:58:04.386831 2018] [:error] [pid 15175] [client xxxx:54641] PHP Warning:  require_once(/var/www/nZEDb/app/libraries/smarty/smarty/libs/sysplugins/smarty_internal_data.php): failed to open stream: No such file or directory in /var/www/nZEDb/libraries/smarty/smarty/libs/Smarty.class.php on line 78, referer: http://xxxxx/install/
[Wed Jul 04 17:58:04.386899 2018] [:error] [pid 15175] [client xxxxxx:54641] PHP Fatal error:  require_once(): Failed opening required '/var/www/nZEDb/app/libraries/smarty/smarty/libs/sysplugins/smarty_internal_data.php' (include_path='.:/usr/share/php') in /var/www/nZEDb/libraries/smarty/smarty/libs/Smarty.class.php on line 78, referer: http://xxxx/install/

And yes, that error makes sense, because no files are in here:

=> /var/www/nZEDb/app/libraries

To give a full picture, my install.sh-output looks good:

 ./install.sh
nZEDb Installer
----------------------

Getting the nZEDb app from GitHub

fatal: destination path 'nZEDb' already exists and is not an empty directory.

Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating optimized autoload files
> nzedb\build\Composer::postInstallCmd
Updating git hooks... done

Setting cache directory permissions for you...

Installation complete.
Now run the setup via the web site's /install page.
------------------------

Any clue somebody? :) Thanks in advance.

**Comment by niel** [comment]
Look at the output from running/install.sh:

`fatal: destination path 'nZEDb' already exists and is not an empty directory.`

That's the start of your problems.

TBH if you can't diagnose such a simple error message, you shouldn't be using this application.

**Comment by sebst3r** [comment]
@niel Thanks for getting back to me so quickly!

As is said, i followed the guide in your forum: 

....
git clone https://github.com/nZEDb/nZEDb.git
./install.sh
......

So, yes, of course i see that error message. Which leads to me to skipping the git clone and letting "install.sh" do the job on his own. Now even running it not as root anymore:

.....
Generating optimized autoload files
> nzedb\build\Composer::postInstallCmd
Updating git hooks... done

Setting cache directory permissions for you...
[sudo] password for nzedb:
**chmod: changing permissions of './': Operation not permitted
chmod: changing permissions of './': Operation not permitted**


Installation complete.
Now run the setup via the web site's /install page.
------------------------

I got to HOST/install, click on "Go to step one: Preflight check" and get the HTTP500 again. 

Apache-Log:  Nothing new, no errors. 

So the only error i see for now: chmod: changing permissions of './': Operation not permitted

I am in /var/www running the install.sh script. I looked into the install.sh-script and set the permissions via sudo by hand, still the 500 error here: http://xxxx/install/step1.php?

**Comment by niel** [comment]
Sounds like a permissions issue, which means you've either missed a previous step or need to completely remove the directory and files and start from the beggining.

**Comment by Wally73** [comment]
install.sh does the git clone so doing a git clone before that is asking for problems

**Comment by sebst3r** [comment]
@Wally73 according to the tutorial i do a git clone in order to get the "install.sh" in the first place ;)

**Comment by niel** [comment]
That install.sh script is *not* intended to be used as the guide tells you. It is intended to be invoked remotely, so that it clones its own repo and then starts `composer install` process. It is part of an ongoing move away from the web install. As such it is not complete or documented yet.
