### ISSUE TITLE
Segfault in Multiprocessing-Postprocessing

### ISSUE THREAD

**Issue by DrakeJones** [nZEDb/nZEDb#2589]
###Expected behaviour
No Segfaults

###Actual behaviour
Segfaults

###Steps to reproduce the behaviour
Start tmux.

syslog
Every 2.0s: tail -20 /var/log/syslog                                                                                                                                                               ocean: Fri Jul 13 14:34:24 2018

Jul 13 14:30:57 oceanfront kernel: [71086.613002] php7.0[101466]: segfault at 1 ip 00007f1298cb8676 sp 00007ffe59cd6e58 error 4 in libc-2.24.so[7f1298c38000+195000]
Jul 13 14:30:59 oceanfront kernel: [71089.198463] php7.0[101677]: segfault at 1 ip 00007f1f339b0676 sp 00007ffd8e234fd8 error 4 in libc-2.24.so[7f1f33930000+195000]
Jul 13 14:31:13 oceanfront unar: 2018-07-13 14:31:13.694 unar[102187:102187] File NSCalendarDate.m: 1563. In -[NSCalendarDate initWithYear:month:day:hour:minute:second:timeZone:] invalid second given - 60
Jul 13 14:31:13 oceanfront unar: 2018-07-13 14:31:13.756 unar[102190:102190] File NSCalendarDate.m: 1563. In -[NSCalendarDate initWithYear:month:day:hour:minute:second:timeZone:] invalid second given - 60
Jul 13 14:31:59 oceanfront kernel: [71149.238433] php7.0[102565]: segfault at 1 ip 00007fbae17a2676 sp 00007ffda1c44a78 error 4 in libc-2.24.so[7fbae1722000+195000]
Jul 13 14:32:02 oceanfront kernel: [71151.467317] php7.0[102634]: segfault at 1 ip 00007f9ce8308676 sp 00007ffee63940d8 error 4 in libc-2.24.so[7f9ce8288000+195000]
Jul 13 14:32:16 oceanfront unar: 2018-07-13 14:32:16.201 unar[103032:103032] File NSCalendarDate.m: 1563. In -[NSCalendarDate initWithYear:month:day:hour:minute:second:timeZone:] invalid second given - 60
Jul 13 14:32:16 oceanfront unar: 2018-07-13 14:32:16.260 unar[103037:103037] File NSCalendarDate.m: 1563. In -[NSCalendarDate initWithYear:month:day:hour:minute:second:timeZone:] invalid second given - 60
Jul 13 14:33:00 oceanfront kernel: [71209.831041] php7.0[103668]: segfault at 1 ip 00007fc0f0bac676 sp 00007fff26e18ff8 error 4 in libc-2.24.so[7fc0f0b2c000+195000]
Jul 13 14:33:02 oceanfront kernel: [71212.108374] php7.0[103754]: segfault at 1 ip 00007f8e143cb676 sp 00007fff53163528 error 4 in libc-2.24.so[7f8e1434b000+195000]
Jul 13 14:33:23 oceanfront unar: 2018-07-13 14:33:23.218 unar[104057:104057] File NSCalendarDate.m: 1563. In -[NSCalendarDate initWithYear:month:day:hour:minute:second:timeZone:] invalid second given - 60
Jul 13 14:33:23 oceanfront unar: 2018-07-13 14:33:23.332 unar[104060:104060] File NSCalendarDate.m: 1563. In -[NSCalendarDate initWithYear:month:day:hour:minute:second:timeZone:] invalid second given - 60
Jul 13 14:34:11 oceanfront kernel: [71280.594566] php7.0[104938]: segfault at 1 ip 00007f6daffa5676 sp 00007fff066bafd8 error 4 in libc-2.24.so[7f6daff25000+195000]
Jul 13 14:34:13 oceanfront kernel: [71282.867499] php7.0[105022]: segfault at 1 ip 00007f2f508d6676 sp 00007fffdb89fff8 error 4 in libc-2.24.so[7f2f50856000+195000]

![capture1](https://user-images.githubusercontent.com/6259352/42693334-2773a504-86af-11e8-9ed6-358421a74d3a.PNG)

**Comment by niel** [comment]
Syslog is useless for us, as it doesn't tell us anything. We need your PHP error log from .../resources/logs/,
which you may need to enable in your .../configuration/settings.php

**Comment by DrakeJones** [comment]
Changed my.cnf and problem seems to have cleared up the segfault issue.

#character-set-client-handshake = FALSE
#character-set-server = utf8mb4
#collation-server = utf8mb4_unicode_ci

character-set-server = utf8
collation-server = utf8_general_ci
skip-character-set-client-handshake
