### ISSUE TITLE
zed not working (mergetable php file missing...)

### ISSUE THREAD

**Issue by nevbear666** [nZEDb/nZEDb#2590]
specs:

php 5.6, 7.1 and 7.2 (jic)
mariadb 10.something
current ubuntu (bionic...) with all the updates and the patches...
last install date of nzedb: ~5 weeks ago (worked fine ever since...), things just stopped working after the "pull". that mergetable thingy also breaks the processing...

expected: ./zed update all... works

./zed update all
/var/www/nZEDb/app /var/www/nZEDb

Warning: require(/var/www/nZEDb/libraries/lithium/core/MergeInheritable.php): failed to open stream: No such file or directory in /var/www/nZEDb/app/config/bootstrap/libraries.php on line 91

Fatal error: require(): Failed opening required '/var/www/nZEDb/libraries/lithium/core/MergeInheritable.php' (include_path='.:/usr/share/php') in /var/www/nZEDb/app/config/bootstrap/libraries.php on line 91
/var/www/nZEDb

to reproduce:
git pull https://github.com/nZEDb/nZEDb.git 0.x
cd /path/to/nzedb
./zed update all

also tried the usual composer update...:
sudo composer self-update (works fine, as expected...)
composer version: Composer version 1.6.5 2018-05-04 11:44:59
composer update:
Loading composer repositories with package information
Updating dependencies (including require-dev)                             
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package bower-asset/animate.css could not be found in any version, there may be a typo in the package name.
  Problem 2
    - The requested package bower-asset/autosize-3.0.x could not be found in any version, there may be a typo in the package name.
  Problem 3
    - The requested package bower-asset/bootstrap-2.3.x could not be found in any version, there may be a typo in the package name.
  Problem 4
    - The requested package bower-asset/bootstrap-3.3.x could not be found in any version, there may be a typo in the package name.
  Problem 5
    - The requested package bower-asset/bootstrap-hover-dropdown-2.2.x could not be found in any version, there may be a typo in the package name.
  Problem 6
    - The requested package bower-asset/bootstrap-progressbar-0.9.x could not be found in any version, there may be a typo in the package name.
  Problem 7
    - The requested package bower-asset/bootswatch could not be found in any version, there may be a typo in the package name.
  Problem 8
    - The requested package bower-asset/chosen-1.5.x could not be found in any version, there may be a typo in the package name.
  Problem 9
    - The requested package bower-asset/colorbox-1.6.x could not be found in any version, there may be a typo in the package name.
  Problem 10
    - The requested package bower-asset/fastclick-1.0.x could not be found in any version, there may be a typo in the package name.
  Problem 11
    - The requested package bower-asset/font-awesome-4.5.x could not be found in any version, there may be a typo in the package name.
  Problem 12
    - The requested package bower-asset/html5shiv-3.7.x could not be found in any version, there may be a typo in the package name.
  Problem 13
    - The requested package bower-asset/icheck-1.0.x could not be found in any version, there may be a typo in the package name.
  Problem 14
    - The requested package bower-asset/jquery-1.9.x could not be found in any version, there may be a typo in the package name.
  Problem 15
    - The requested package bower-asset/jquery-2.2.x could not be found in any version, there may be a typo in the package name.
  Problem 16
    - The requested package bower-asset/jquery-migrate-1.4.x could not be found in any version, there may be a typo in the package name.
  Problem 17
    - The requested package bower-asset/jquery.nicescroll-3.6.x could not be found in any version, there may be a typo in the package name.
  Problem 18
    - The requested package bower-asset/noty-2.3.x could not be found in any version, there may be a typo in the package name.
  Problem 19
    - The requested package bower-asset/pace-1.0.x could not be found in any version, there may be a typo in the package name.
  Problem 20
    - The requested package bower-asset/pnotify-3.0.x could not be found in any version, there may be a typo in the package name.
  Problem 21
    - The requested package bower-asset/respond-1.4.x could not be found in any version, there may be a typo in the package name.
  Problem 22
    - The requested package bower-asset/responsive-tables-js-1.0.x could not be found in any version, there may be a typo in the package name.
  Problem 23
    - The requested package bower-asset/select2-4.0.x could not be found in any version, there may be a typo in the package name.
  Problem 24
    - The requested package bower-asset/slimscroll-1.3.x could not be found in any version, there may be a typo in the package name.
  Problem 25
    - The requested package bower-asset/tinymce-builded could not be found in any version, there may be a typo in the package name.
  Problem 26
    - The requested package unionofrad/manual 1.1.x-dev exists as unionofrad/manual[v1.0.0, v1.0.0-rc1] but these are rejected by your constraint.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by Wally73** [comment]
from the releasenotes

0.8.8.0 2018-07-03
***NOTE*** After updating you may have to do `composer install && ./zed update nzedb` to get things
working again.

**Comment by nevbear666** [comment]
ty for the information...
q: would it be possible to have the mentoining of "read releases file" if theres changes in it in the changelog as well? that might ease up things for lazy guys that keep up par with a single file like me...

man, those are alot of libraries added in one step...

**Comment by niel** [comment]
> q: would it be possible to have the mentoining of "read releases file" if theres changes in it in the changelog as well? that might ease up things for lazy guys that keep up par with a single file like me...

Simple answer: no
Longer answer: 
If you use the Stable branch, you should read the ReleaseNotes,as it contains notes specific to each release.
If you are on the dev branch, read the Changelog as it contains a log of changes as they happen in that branch.

**Comment by nevbear666** [comment]
ahh, thank you for the explanation, ill continue following the releasenotes then rather than the changelog.
