### ISSUE TITLE
PHP Fatal Error

### ISSUE THREAD

**Issue by DrSeussFreak** [nZEDb/nZEDb#2594]
I am trying to get nZEDb going on Ubuntu 18.04 LTS with PHP 7.0.  I am borrowing from the 16.04 wiki, and when I get to the step of browsing to my site, I get an http error 500, with the followng error in the "php_errors_web.log"

`[03-Aug-2018 19:45:03 America/Chicago] PHP Fatal error:  require_once(): Failed opening required '/var/www/nZEDb/app/libraries/smarty/smarty/libs/sysplugins/smarty_internal_data.php' (include_path='.:/usr/share/php') in /var/www/nZEDb/libraries/smarty/smarty/libs/Smarty.class.php on line 78`

###Expected behaviour
Installation to proceed to http://nzedb-01/install/step1.php? without issue

###Actual behaviour
http error 500 with the error message above

###Steps to reproduce the behaviour
Browse to the site and click install

I am stuck on https://github.com/nZEDb/nZEDb/wiki/Install-Guide:-Ubuntu-18.04#configure-nzedb

**Comment by niel** [comment]
Sounds like you haven't installed Composer.
See https://github.com/nZEDb/nZEDb/wiki/Guides:-composer
Obviously you will not need to clone nZEDb again ;-)

**Comment by DrSeussFreak** [comment]
I installed composer globally

```
which composer
/usr/local/bin/composer
```

> [03-Aug-2018 23:57:45 America/Chicago] PHP Warning:  require_once(/var/www/nZEDb/app/libraries/smarty/smarty/libs/sysplugins/smarty_internal_data.php): failed to open stream: No such file or directory in /var/www/nZEDb/libraries/smarty/smarty/libs/Smarty.class.php on line 78
> [03-Aug-2018 23:57:45 America/Chicago] PHP Fatal error:  require_once(): Failed opening required '/var/www/nZEDb/app/libraries/smarty/smarty/libs/sysplugins/smarty_internal_data.php' (include_path='.:/usr/share/php') in /var/www/nZEDb/libraries/smarty/smarty/libs/Smarty.class.php on line 78

I did run the following

```
composer install --prefer-source
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating optimized autoload files
> nzedb\build\Composer::postInstallCmd
Updating git hooks... done
```

Same issue :(

**Comment by niel** [comment]
I'll try to do an install on a U18.04 VM some time this weekend.
Have you checked that path to see if the file(s) exist. If it/they don't, that would appear to be a problem with Composer not installing the required dependency.

If you have questions I should be available in our IRC channel today and most of tomorrow.

**Comment by niel** [comment]
I noticed that your guide has some contradictory instructions.  For example you have the "Install Composer" section and link, but that uses the git command which you do not instruct to install until later in the "Install nZEDb" section. You should move the preliminary steps (setting your group, installing git and the php packages), so they are before "Install Composer" section.
You also install the composer app again with `curl -sS https://getcomposer.org/installer | php` and run it with `php composer.phar install`. Thos steps are not need if the global option was followed.

Additionally, PHP v7.0 is not particularly appropriate for Ubuntu 18.04 as it comes with either 7.1 or 7.2 (nZEDb will not support 7.2 until the next release) by default.

Do you have the output from the initial run of `composer install`? That might help to diagnose your problems.

**Comment by DrSeussFreak** [comment]
What entry should I see in PATH?  right now I have

`PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`

As for my guide, I am switching to the global method and removing the other set.  It is very much a work-in-progress, I am updating it as I make it farther each time I do something. 

I chose PHP 7.0 as I was getting some corruption issues with PHP 7.1 (and as you said, 7.2 isn't supported).   I may try rebuilding the VM from scratch with PHP 7.1, but as I have had no issues with 7.0, I was content to proceed.   Do you have an ETA for the next release?

I do not have the output of the initial composer run, I didn't think to save it at the time, as I had not run into any issues.

**Comment by niel** [comment]
Barring any major issues, next release will be Monday. We normally release updates first Monday of every month, provided there are updates to release. :-)
However, I misspoke previously. 7.2 support will be in the release after the coming one on Monday, as that release is already branched and ready to go out. The 7.2 support was added less than a week ago and needs to spend more time in dev branch to be sure there are no edge-cases to be fixed.

Your PATH looks fine to me. We don't have a specific policy on that really. It's up to the distro to include locations that include php binaries for cli use.

**Comment by DrSeussFreak** [comment]
The PATH seems fine, as it is similar to other VMs I have running that leverage similar binaries, and they all work without issue.

I am not sure how to proceed next, as I am very unfamiliar with composer.  Any thoughts?

**Comment by niel** [comment]
This is fixed in dev branch and will get released to stable branch tomorrow.

**Comment by DrSeussFreak** [comment]
Awesome, thanks!
