### ISSUE TITLE
PHP7.1 + PHP7.2 Errors

### ISSUE THREAD

**Issue by JReming85** [nZEDb/nZEDb#2597]
###Expected behaviour
1 - No errors
2 - Video/Image Previews working

###Actual behaviour
PHP7.0 worked fine, but ever since I reinstalled using 7.1 (which was super fast) and again with 7.2 since I thought I messed it up, previews & attached images are not displaying.

First the error I get:
PHP Notice: A non well formed numeric value encountered in /var/www/nZEDb/nzedb/utility/Misc.php on line 592

Second, both the previews & videos are generated just fine.  The the listings even show their is a preview/video available, however whenever I goto see the details, its not showing up, it acts as if it doesnt even have a preview to display.

I noted on some of them, the console shows a 404 error, and when I goto cross ref the file its trying to server, it is there but for some reason it 404ed.

That also extends to fontawesome-webfont.woff2?v=4.5.0 having always been 404ing even with php7.0 despite it being there.

###Steps to reproduce the behaviour

Use PHP7.1/2 - ppa:ondrej/php
Mariadb10
Apache2 - ppa:ondrej/apache2

igbinary
memcached
apcu

happened with a combination of 
memcached + igbinary w igbinary as the serializer
memcached + igbinary w php as the serializer
memcached + apcu + igbinary w apcu/igbinary as the serializer

Sorry if I left anything out

**Comment by JReming85** [comment]
Well I fixed the woff2 by adding it in the .htaccess file

**Comment by niel** [comment]
I'll need a stack trace to determine where the bad number in the error is coming from.

Also, be very sure the old version of PHP is completely removed. A number of people have had issues where different versions are being used to what they expect

**Comment by JReming85** [comment]
yea I did a purge, and after I got I switched it over from php 7.0 to 7.1, and it started giving me the errors I decided to do a full wipe and start with 7.2 out of the box.

Im going to just post all of them here for you.

php_errors_cli

This one has been with me since 7.1/7.2, it deletes releases, but some slip through
[13-Oct-2018 01:42:43 America/New_York] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1305 PROCEDURE nzedb.delete_release does not exist in /var/www/nZEDb/nzedb/Rel$Stack trace:
#0 /var/www/nZEDb/nzedb/Releases.php(637): PDOStatement->execute()
#1 /var/www/nZEDb/nzedb/processing/ProcessReleases.php(1306): nzedb\Releases->deleteSingle(Array, Object(nzedb\NZB), Object(nzedb\ReleaseImage))
#2 /var/www/nZEDb/misc/update/nix/multiprocessing/.do_not_run/switch.php(173): nzedb\processing\ProcessReleases->deleteReleases()
#3 {main}
  thrown in /var/www/nZEDb/nzedb/Releases.php on line 637

That one is repeated numerous times, with ProcessReleases.php as well and this one repeats with the different removeCrapReleases.php options. it also never deletes anything
[13-Oct-2018 04:00:58 America/New_York] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1305 PROCEDURE nzedb.delete_release does not exist in /var/www/nZEDb/nzedb/Rel$
Stack trace:
#0 /var/www/nZEDb/nzedb/Releases.php(637): PDOStatement->execute()
#1 /var/www/nZEDb/nzedb/ReleaseRemover.php(1096): nzedb\Releases->deleteSingle(Array, Object(nzedb\NZB), Object(nzedb\ReleaseImage))
#2 /var/www/nZEDb/nzedb/ReleaseRemover.php(884): nzedb\ReleaseRemover->deleteReleases()
#3 /var/www/nZEDb/nzedb/ReleaseRemover.php(254): nzedb\ReleaseRemover->removeBlacklist()
#4 /var/www/nZEDb/misc/testing/Release/removeCrapReleases.php(67): nzedb\ReleaseRemover->removeCrap(true, '4', 'blacklist', '')
#5 {main}
  thrown in /var/www/nZEDb/nzedb/Releases.php on line 637

For the web, this is whats in the error log

[12-Oct-2018 23:21:13 America/New_York] PHP Notice:  A non well formed numeric value encountered in /var/www/nZEDb/nzedb/utility/Misc.php on line 592
[13-Oct-2018 01:41:26 America/New_York] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/www/nZEDb/resources/smarty/templates_c/521bcbd14f5f99df1b63481973cc38dc63$


Attaching logs
[php_errors_cli.log](https://github.com/nZEDb/nZEDb/files/2477088/php_errors_cli.log)
[php_errors_web.log](https://github.com/nZEDb/nZEDb/files/2477089/php_errors_web.log)

If you need anything else let me know.

**Comment by JReming85** [comment]
I'm going to reinstall ubuntu 16.04 again and try again.  I have only used 1.4TB of my 15TB so I have some room to play.

Will report what happens.

**Comment by JReming85** [comment]
@niel sorry for the trouble but I think I got it figured out.

Haven't started running it yet, but the errors are gone with my mysql tables.

After reinstalling and using my custom mysql config, it was having issues importing the tsv files. 

After trying all the different caching methods and without, I figured maybe the database was the thing that was corrupt, ended up deleted /var/lib/mysql and recreated it, and everything imported without error.

Will report back after I finish configuring and start running

**Comment by niel** [comment]
I figured your triggers were missing from the first two errors above, but I don't see how that would cause the third one, so I'll continue to look into that unless it disappears also.

**Comment by JReming85** [comment]
@niel I just looked it up

All my triggers are there, however I have 0 routines.

Now I just need to figure out how I can create them

**Comment by JReming85** [comment]
After trying to run then as an sql query and failing, I clipped the procedures out of mysql-ddl.sql into a new file.  Line 1416 -> EOF

and I am getting an error 
ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 5

which ref     DECLARE done INT DEFAULT 0;

First entry after main: BEGIN

Still working on it

**Comment by JReming85** [comment]
@niel 
FIGURED IT OUT

It finally imported after I changed the delimiter

It was failing to import due to it thinking the procedure import was finished after the first ;

Might need to change the delimiter, or split that into to imports

**Comment by JReming85** [comment]
and thanks for the help.

I would still be here scratching my head if you wouldnt have suggested looking at the triggers/procedures

**Comment by niel** [comment]
That's strange. The normal install procedure should create those triggers/procedures when it creates the database. Only reason I can think of that would prevent it would be lack of SQL permissions for the nZEDb user.

**Comment by JReming85** [comment]
I spoke too soon.

No more CLI errors but still having the same issue with no previews

[15-Oct-2018 19:25:47 America/New_York] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/www/nZEDb/resources/smarty/templates_c/05b35b5fbe879987a8b9268ca9a1c74c9c1f75ef_0.file.viewnzb.tpl.php on line 257
[15-Oct-2018 19:25:47 America/New_York] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/www/nZEDb/resources/smarty/templates_c/05b35b5fbe879987a8b9268ca9a1c74c9c1f75ef_0.file.viewnzb.tpl.php on line 898

<?php if (count($_smarty_tpl->tpl_vars['reVideo']->value['releases_id']) > 0 || count($_smarty_tpl->tpl_vars['reAudio']->value) > 0) {?>
                                                                                <li><a href="#pane8" data-toggle="tab">MediaInfo</a></li>

and

<?php if (count($_smarty_tpl->tpl_vars['reVideo']->value['releases_id']) > 0 || count($_smarty_tpl->tpl_vars['reAudio']->value) > 0) {?>
                                                                                <div id="pane8" class="tab-pane">


Yes, its strange.  I never had an issue using php7 so it might be how I have php7.1/2 configured thats knocking it out.  I always use a new user with full permissions for their own database, and this one through me through a loop.  I even tried importing it with my special super account, and for some reason the only way it would work (importing the snippet from cli, or running a sql query) was if I changed the delimiter.  Since it worked before and stopped when I switched chances are its my config somewhere.

Any idea on web errors?  I noticed since there was a composer.lock, I dont run composer update is that something you would recommend?

**Comment by JReming85** [comment]
I ended up resetting my db again last night and noticed in the patches that add or add/remove procedures they define their delimiter as $$.

Also when I successfully imported the snippet file, I also set the delimiter to $$ and that worked.

I think I am going to switch back to php7.0 to see if anything changes (despite it being what seems like 100x slower) and work my way forward.

**Comment by JReming85** [comment]
Would have had an update sooner, but was sitting at the hospital for the last day and a half with my son.  Had a case of Intussusception and they had to perform the procedure twice and verify it resolved the issue.

Looks like redoing the whole thing with php7.0 worked perfectly fine.

It imported the procedure, and after I finish importing the predb, animedb, and steam db's I will start testing further, including upgrading to php7.2

**Comment by JReming85** [comment]
Switched from php7.0 to php7.2 and it looks like everything is working as intended, however still getting the same old errors as before only difference is everything still works.

Previews, Samples, Videos, Audio are there
