### ISSUE TITLE
Latest Mediainfo is not supported

### ISSUE THREAD

**Issue by JReming85** [nZEDb/nZEDb#2598]
Newer versions of mediainfo output a different json sytle then older versions, making the system unable to parse it.

For those that use the [auto updating script](https://github.com/nZEDb/nZEDb_Misc/blob/master/Scripts/Linux/autobin.sh) located in [nZEDn_Misc](https://github.com/nZEDb/nZEDb_Misc/) might want to disable it from updating.

Sample JSON outputs:
Valid - v0.7.82

[mediainfo - 0.7.82.txt](https://github.com/nZEDb/nZEDb/files/2511941/mediainfo.-.0.7.82.txt)

Invalid - Latest - v18.08.1

[mediainfo - 18.08.1.txt](https://github.com/nZEDb/nZEDb/files/2511946/mediainfo.-.18.08.1.txt)

**Comment by niel** [comment]
That output is XML not JSON at all. I'll check our code to see what it actually expects. If needed, I'll look into creating an additional parser and code to select the appropriate one.

**Comment by JReming85** [comment]
Yea sorry, long day reading json responses.

I remember seeing some complaints about them changing the output, but I don't remember the version numbers and thanks for looking into it.

**Comment by Wally73** [comment]
last working version of mediainfo on my debian jessie box is 0.7.70
all v18.x version don't work

**Comment by JReming85** [comment]
@Wally73 is that the version in the debian package manager?

For me the latest available in ubuntu 16.04.5 repository is 7.82 and also works for me perfectly fine.

I know debian and ubuntu are different, but since ubuntu is built off of debian that should still be pretty similar, and I suspect 7.82 might work for it as well if you want to give it a shot.

**Comment by niel** [comment]
Current on Ubuntu is v17.12

BTW I'm working on this. I'm almost done on the first pass.

**Comment by niel** [comment]
A fix has been merged into the dev branch.
