### ISSUE TITLE
Some Themes have broken pagination for Browse Groups - [originally] Request Browse All & Browse Groups Results Number Be Delinked in Settings.php 

### ISSUE THREAD

**Issue by DrakeJones** [nZEDb/nZEDb#2603]
###Expected behaviour
Select Browse Groups from main menu and see all groups by default.

###Actual behaviour
Number of Groups returned is actually defined by same variable as 'Releases to show per page in list view' defined under Web Settings in Settings.php; i.e., choosing 50 releases per page  will also limit Groups returned to 50.  And, there is no option to advance page.  I'm using Alpha Theme.

###Steps to reproduce the behaviour.
Set variable page releases in Settings.php

**Comment by niel** [comment]
I can't see this changing any time soon.
This is actually a problem with some themes, including Alpha. Default, Light, Simple, and None do not have the problem as they correctly implement the pagination.
Obviously if someone provides a PR to fix the issue, we'll gladly look into it.

**Comment by DrakeJones** [comment]
Got it. Pagination problem fixed: `{$pager}` was missing from browsegroup.tpl in Alpha theme.  Inserted `{$pager}` @ lines 2 and 27. I'll try to decipher the instructions for a PR, but the in mean time, here is the code:

`{include file='elements/ads.tpl' ad=$site->adbrowse}
{if $results|@count > 0}
{$pager}
	<table class="table-striped table-condensed table-highlight data Sortable table" id="browsetable">
		<thead>
		<tr>
			<th>name</th>
			<th>description</th>
			<th>updated</th>
		</tr>
		</thead>
		<tbody>
		{foreach $results as $result}
			{if $pagertotalitems > 0}
				<tr>
					<td>
						<a title="Browse releases from {$result.name|replace:"alt.binaries":"a.b"}" href="{$smarty.const.WWW_TOP}/browse?g={$result.name}">{$result.name|replace:"alt.binaries":"a.b"}</a>
					</td>
					<td>
						{$result.description}
					</td>
					<td class="less">{$result.last_updated|timeago} ago</td>
				</tr>
			{/if}
		{/foreach}
		</tbody>
	</table>
{$pager}
{/if}
`

**Comment by DrakeJones** [comment]
Got it. Pagination problem fixed: {$pager} was missing from browsegroup.tpl in Alpha theme. Inserted {$pager} @ lines 2 and 27. I'll try to decipher the instructions for a PR - 
[browsegroups.txt](https://github.com/nZEDb/nZEDb/files/2589316/browsegroups.txt)
