### ISSUE TITLE
PHP Fatal error: Uncaught TypeError: Argument 1 passed to nzedb\NameFixer::nzedb

### ISSUE THREAD

**Issue by Sweepr** [nZEDb/nZEDb#2607]
###Expected behaviour

Rename releases without error.

###Actual behaviour

Problem running match_prefiles.php with latest release:

Match PreFiles (50) Started at 2:49:46
Matching predb filename to cleaned release_files.name.

50 releases to process.

Finishes within a split-second, but error_log show this:

[08-Dec-2018 14:49:46 Europe/Amsterdam] PHP Fatal error: Uncaught TypeError: Argument 1 passed to nzedb\NameFixer::nzedb{closure}() must be of the type string, null given, called in /home/public_html/nzedb/NameFixer.php on line 929 and defined in /home/public_html/nzedb/NameFixer.php:915
Stack trace:
#0 /home/public_html/nzedb/NameFixer.php(929): nzedb\NameFixer->nzedb{closure}(NULL)
#1 /home/public_html/nzedb/NameFixer.php(877): nzedb\NameFixer->matchPredbFiles(Array, 1, 1, true, 1)
#2 /home/public_html/misc/update/match_prefiles.php(22): nzedb\NameFixer->getPreFileNames(Array)
#3 {main}
thrown in /home/public_html/nzedb/NameFixer.php on line 915

###Steps to reproduce the behaviour

Problem running match_prefiles.php with latest release:

php /home/public_html/misc/update/match_prefiles.php 50 show

**Comment by Sweepr** [comment]
Reverted NameFixer.php back to https://github.com/nZEDb/nZEDb/blob/aa6e28a5c45f6777e1bc53b0969608585daeff69/nzedb/NameFixer.php

No problem running match_prefiles.php with latest release.

Will try https://github.com/nZEDb/nZEDb/blob/0a71049b019707aa75faf8abf0c9ec8e19207148/nzedb/NameFixer.php tomorrow, see if it will run properly.

**Comment by Sweepr** [comment]
Tried using https://github.com/nZEDb/nZEDb/blob/0a71049b019707aa75faf8abf0c9ec8e19207148/nzedb/NameFixer.php but it still reports back error's

[10-Dec-2018 06:30:31 Europe/Amsterdam] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to nzedb\NameFixer::nzedb\{closure}() must be of the type string, null given, called in /home/public_html/nzedb/NameFixer.php on line 929 and defined in /home/public_html/nzedb/NameFixer.php:915
Stack trace:
#0 /home/public_html/nzedb/NameFixer.php(929): nzedb\NameFixer->nzedb\{closure}(NULL)
#1 /home/public_html/nzedb/NameFixer.php(877): nzedb\NameFixer->matchPredbFiles(Array, 1, 1, true, 1)
#2 /home/public_html/misc/update/match_prefiles.php(22): nzedb\NameFixer->getPreFileNames(Array)
#3 {main}
  thrown in /home/public_html/nzedb/NameFixer.php on line 915

php --version
PHP 7.2.12 (cli) (built: Dec  3 2018 20:08:09) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

This one works just fine:

https://github.com/nZEDb/nZEDb/blob/aa6e28a5c45f6777e1bc53b0969608585daeff69/nzedb/NameFixer.php

**Comment by niel** [comment]
The fix is commited here d47efcbb
