### ISSUE TITLE
PHP Notice:  Undefined offset: 1 in /libraries/zeebinz/rarinfo/rarinfo.php on line 1030

### ISSUE THREAD

**Issue by Sweepr** [nZEDb/nZEDb#2615]
###Expected behaviour

No notice in error_log

###Actual behaviour

PHP Notice:  Undefined offset: 1 in /libraries/zeebinz/rarinfo/rarinfo.php on line 1030

###Steps to reproduce the behaviour

Unknown.

Found an issue posted by Niel few years ago, issue still exists: https://github.com/zeebinz/rarinfo/issues/15

**Comment by niel** [comment]
As you mentioned, I raised this with the library author a couple years ago. Without samples of the RAR file causing the issue, there is nothing more we can do.
