### ISSUE TITLE
Releases where pred_id = 0, releases exist in PreDB, but can't be matched.

### ISSUE THREAD

**Issue by Sweepr** [nZEDb/nZEDb#2617]
while searching the un-renamed "searchname" I'm seeing releases being created in SQL but some of them have pred_id = 0 so can't be matched.

Any reason why this could happen?

**Comment by Sweepr** [comment]
Something extra i found:

Looking at the contents of the RAR files, i can tell to which PredDB they should belong, altought i can find the id belonging to that release using:

SELECT id FROM predb WHERE title LIKE "ReleaseName";

but when running: 

SELECT name FROM releases WHERE predb_id = id;

I get no result.

How is that possible?

Others releases in the same category/group/source yield results, others do not.

Almost looks like a hashing issue.

**Comment by niel** [comment]
> while searching the un-renamed "searchname" I'm seeing releases being created in SQL but some of them have pred_id = 0 so can't be matched.
> 
> Any reason why this could happen?

I think you're misunderstanding how this works. When a new entry is created for the releases table, we check the cleaned up search name to see if it matches the name of a known predb entry. If it does, the id of that predb is inserted into the predb_id field. This doesn't "prevent matching", it is a failed match.

**Comment by niel** [comment]
> Something extra i found:
> 
> Looking at the contents of the RAR files, i can tell to which PredDB they should belong, altought i can find the id belonging to that release using:
> 
> SELECT id FROM predb WHERE title LIKE "ReleaseName";
> 
> but when running:
> 
> SELECT name FROM releases WHERE predb_id = id;
> 
> I get no result.
> 
> How is that possible?

It's possible because your ability to match is much better/looser than the code's. For whatever reason, matching failed so it doesn't have a predb_id, that's what a value of 0 in that field means.

**Comment by niel** [comment]
BTW, these are more questions of how things work, not issues that should be in this issue tracker.

**Comment by Sweepr** [comment]
True Niel, thanks for your explanation here, next time i will ask such question on the channels for which they are supposed. ;-)
