### ISSUE TITLE
IRCScraper.php is unable to insert new PreDB Entry

### ISSUE THREAD

**Issue by stanleykylee** [nZEDb/nZEDb#2621]
###Expected behaviour
Insert new PreDB Entry

###Actual behaviour
Fails on insert with invalid date: SQL Error:

`Incorrect datetime value: '-0001-11-30 00:00:00' for column 'updated' at row 1`

This is a similar issue with #2534.

###Steps to reproduce the behaviour
New installation of nZEDb and setup ZNC with IRCScraper following the [wiki instructions](https://github.com/nZEDb/nZEDb_Misc/blob/master/Guides/Various/IRCScraper/Guide.md).

**Comment by niel** [comment]
Make sure your DB accepts zero dates. Newer versions disable this by default so you need to change the behaviour

**Comment by adamr-space** [comment]
$data = [
                        'title' => $this->_curPre['title'],
                        'created' => $this->_curPre['predate']->format('Y-m-d H:i:s'),
                        'updated' => null,
                ];
That does the trick.

**Comment by niel** [comment]
It would help if you said 'where' that does the trick :-)

**Comment by niel** [comment]
After checking through the code, and DB schema... If that "does the trick" for you, then your DB is configured incorrectly. As noted above, the correct fix is to allow the timestamp fields to accept ZERO_DATE.
The zeroed date is there to tells us it has NOT been updated, useful for some checks. Putting NULL into the update field causes the database to automatically insert the current timestamp, which defeats the design.
