### ISSUE TITLE
TMUX scrolling settings not loading in tmux.conf

### ISSUE THREAD

**Issue by Benouch** [nZEDb/nZEDb#2623]
Hi Niel!
###Expected behaviour
Being able to use the mouse scrolling in tmux (2.8.1)

###Actual behaviour
Scrolling doesn't work

###Steps to reproduce the behaviour
execute tmux attach -t nZEDb
try to scroll the mouse.
Doesn't work!

The issue comes from the fact that tmux.conf "source <file>" only takes absolute paths.
so line 58 of misc/update/nix/tmux/tmux.conf should read:
if-shell "tmux -V |awk ' {split($2, ver, \".\"); if (ver[1] < 2) exit 1 ; else if (ver[1] == 2 && ver[2] < 1) exit 1 }' " "source $PWD/tmux_ge_2.3.conf" "source $PWD/tmux_le_2.0.conf"
instead of:
if-shell "tmux -V |awk ' {split($2, ver, \".\"); if (ver[1] < 2) exit 1 ; else if (ver[1] == 2 && ver[2] < 1) exit 1 }' " 'source tmux_ge_2.3.conf' 'source tmux_le_2.0.conf'

**Comment by DariusIII** [comment]
Try to use scripts and tmux.conf from NNTmux and see if that helps.

> https://github.com/NNTmux/newznab-tmux/blob/master/misc/update/tmux/tmux.conf

> https://github.com/NNTmux/newznab-tmux/blob/master/install_tmux.sh

**Comment by Benouch** [comment]
Hello @DariusIII ,
Thanks for the hint.
Although I could modify the scripts out on NNTmux from Debian to Arch I just figured I would let everyone now since I fixed it on my environment that way.

**Comment by DariusIII** [comment]
That is completely fine.

**Comment by niel** [comment]
@Benouch thanks for reporting and for the fix.
