### ISSUE TITLE
Debug: Postdate retried when updating binaries or backfilling.

### ISSUE THREAD

**Issue by nkfs** [nZEDb/nZEDb#2632]
###Expected behaviour
update_binaries or backfill to complete successfully

###Actual behaviour
Backfilling: 5 group(s) - Using compression? No

Starting group 1 of 5

Processing a.b.blu-ray

Debug: Postdate retried 0 time(s).
Debug: Postdate retried 1 time(s).
Debug: Postdate retried 2 time(s).
Debug: Postdate retried 3 time(s).
Debug: Postdate retried 4 time(s).
Debug: Postdate retried 5 time(s).
Debug: Postdate retried 6 time(s).
Debug: Postdate retried 7 time(s).
Debug: Postdate retried 8 time(s).
Debug: Postdate retried 9 time(s).
Debug: Postdate retried 10 time(s).
Debug: Postdate retried 11 time(s).
Debug: Postdate retried 12 time(s).
Debug: Postdate retried 13 time(s).
Debug: Postdate retried 14 time(s).
Debug: Postdate retried 15 time(s).
Debug: Postdate retried 16 time(s).
Debug: Postdate retried 17 time(s).
Debug: Postdate retried 18 time(s).
Debug: Postdate retried 19 time(s).
Debug: Postdate retried 20 time(s).
Debug: Postdate retried 21 time(s).

###Steps to reproduce the behaviour
php update_binaries.php

**Comment by niel** [comment]
Could you check your php log for errors please. Post the stack trace of any reported.

**Comment by nkfs** [comment]
no errors in php7.2-fpm.log or in apache error.log

**Comment by JReming85** [comment]
I got a few

php_errors_cli.log
```
PHP Notice:  Undefined index: Subject in /var/www/nZEDb/nzedb/Binaries.php on line 754
```
php_errors_web.log
```
Warning:  Use of undefined constant include_once__DIR__ - assumed 'include_once__DIR__' (this will throw an Error in a future version of PHP) in /var/www/nZEDb/nzedb/db/DB.php on line 3
```

EDIT::

Just installed xdebug, but only created php_errors_cli.php for the moment

```
Notice:  Undefined index: Subject in /var/www/nZEDb/nzedb/Binaries.php on line 754
PHP Stack trace:
    PHP   1. {main}() /var/www/nZEDb/misc/update/update_binaries.php:0
    PHP   2. nzedb\Binaries->updateAllGroups() /var/www/nZEDb/misc/update/update_binaries.php:38
    PHP   3. nzedb\Binaries->updateGroup() /var/www/nZEDb/nzedb/Binaries.php:336
    PHP   4. nzedb\Binaries->scan() /var/www/nZEDb/nzedb/Binaries.php:530
```

**Comment by nkfs** [comment]
Lots of errors now.. 
[12-Jul-2019 14:53:55 America/Denver] PHP Warning:  Use of undefined constant include_once__DIR__ - assumed 'include_once__DIR__' (this will throw an Error in a future version of PHP) in /var/www/nZEDb/nzedb/db/DB.php on line 3
[12-Jul-2019 14:53:59 America/Denver] PHP Notice:  Undefined index: Date in /var/www/nZEDb/nzedb/Binaries.php on line 1079
[12-Jul-2019 14:53:59 America/Denver] PHP Notice:  Undefined index: Date in /var/www/nZEDb/nzedb/Binaries.php on line 1084
[12-Jul-2019 14:53:59 America/Denver] PHP Notice:  Undefined index: Subject in /var/www/nZEDb/nzedb/Binaries.php on line 754
[12-Jul-2019 14:53:59 America/Denver] PHP Notice:  Undefined index: Subject in /var/www/nZEDb/nzedb/Binaries.php on line 754

**Comment by niel** [comment]
Thanks for the stack traces, that will help tracking this down.

**Comment by niel** [comment]
@nkfs That first error looks like your file is corrupted. Try doing: `git reset  --hard` to restore it/them.

**Comment by docmeth02** [comment]
i got the exact same problem. I setup a new install and let it run for two hours backfilling and indexing 5 groups. When i came back i had 25GB error logs full of 
`Undefined index: Subject in /var/www/nZEDb/nzedb/Binaries.php on line 754`
and no releases where found.

is there any other debugging i can try to narrow down the problem?

**Comment by docmeth02** [comment]
I think i found the problem. The array keys are all (returned by my ntp server) in uppercase:
`[0] => Number
[1] => SUBJECT
[2] => FROM
[3] => DATE
[4] => MESSAGE-ID
[5] => REFERENCES
[6] => BYTES
[7] => LINES
[8] => XREF`

I patched Binaries.php to use uppercase keys and it seems to have fixed the issue of not matching the headers. Im not really a php guy but i suspect this is a provider issue? Should be easy enough to fix by always making the keys lowercase when receiving them from the ntp server.

Let me know if i can help out in any way fixing this

**Comment by niel** [comment]
The case of the header was my suspicion. I'll now need to find a way to workaround that without adding a huge overhead to processing.

**Comment by niel** [comment]
I have a potential fix, but I need someone suffering the issue to test it for me. If anyone is willing, please give me a shout in IRC at some point.

**Comment by JReming85** [comment]
I can get on when I get home, at some friends house about an hour away (took my son to his first movie 3y, saw Toy Story 4, loved it)... Not sure when we are leaving so no ETA.


Wish I knew this was a bug before I wiped my 1.5 year install because I thought the provider screwed it up but thanks for the quick fix.

**Comment by niel** [comment]
I'm heading to bed now (5 am here). I'll be back on in about 12 hours or so.

**Comment by nkfs** [comment]
Oh no.. just missed you.  How do we provide stack traces to help? 

I also did the git reset --hard and returned the following message:
HEAD is now at 0b0eec99c Make sure settings is loaded if available.

**Comment by niel** [comment]
that message is fine, It is just informing you where it has reset to.

**Comment by nkfs** [comment]
Hey @niel I can't seem to catch you on IRC... can we coordinate a fix / test via this issue?

**Comment by niel** [comment]
I'm normally around from 15:00 UTC until 02:00 UTC. Often online a little earlier or later depending on what specifics I have to do on a particular day.
You'll need to be more patient though, as I replied to your DM today after 5 minutes but you didn't answer. It will probably take a few minutes for me to reply as I cannot often just drop what I'm doing to respond immediately.

**Comment by nkfs** [comment]
That's fine, thanks for getting back to me.  I'm not very well versed in git/irc at all, and wasn't sure if there was an easier way to coordinate. I must have closed a window or something.  I will try to be online during the same time tomorrow.

**Comment by niel** [comment]
Final commit to solve last issue a68b5f
