### ISSUE TITLE
SQL Error when updating binaries

### ISSUE THREAD

**Issue by nkfs** [nZEDb/nZEDb#2633]
###Expected behaviour
php update_binaries.php to complete successfully

###Actual behaviour
received 21 articles of 21 requested, 0 blacklisted, 0 not yEnc.
Debug: Sending 1.85 KB of MGR parts to MySQL
Error: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '322,258553),(1295,1499467621,'part381of411.YitrnUZS&AseruFfVTR7@powerpost2000AA.' at line 1

Warning: 21 articles failed to insert! [nzedb\Binaries::scan]
##No further error log.

###Steps to reproduce the behaviour
php update_binaries.

**Comment by JReming85** [comment]
damn it, I am on my 2nd reinstall due to this issue all for a ,


@niel thanks for the quick fix

**Comment by niel** [comment]
> damn it, I am on my 2nd reinstall due to this issue all for a ,
> 
> @niel thanks for the quick fix

You don't need to reinstall, just cleaning the DB and running ./zed update all to get the new release would have worked. ;-)
