### ISSUE TITLE
warning: PHP 7.4 Array and string offset access syntax with curly braces is deprecated

### ISSUE THREAD

**Issue by DrakeJones** [nZEDb/nZEDb#2636]
###Expected behaviour
No errors

###Actual behaviour
Debug Error: "PHP 7.4 Array and string offset access syntax with curly braces is deprecated /var/www/nZEDb/libraries/lithium/util/text.PHP on line 290."

###Steps to reproduce the behaviour
Upgrade to Debian Buster, install PHP7.4.  Start nZEDb.  

Changed "{ }" to "[ ]" seemed to solve the problem.

**Comment by DariusIII** [comment]
PHP 7.4 is still in beta and is not supported...yet.

**Comment by DrakeJones** [comment]
Thanks.

**Comment by niel** [comment]
I've submitted a PR for this upstream.
