### ISSUE TITLE
OpenSSL setup - Windows OS : Cannot register Certificate file / folder

### ISSUE THREAD

**Issue by reiichido** [nZEDb/nZEDb#2641]
Hello,

I'm trying to locally install nZEDb on a Windows 7 64 bits with httpd.
As stated in the setup page
"The file must be readable by both your web user and your CLI user running scripts"
which is the case for me (same user user for CLI and httpd check with "whoami" in both environments).

I finally narrowed down the issue to checkPathsReadable function in step3.php.
In fact a directory separatory is systematically add a directory separator before the splitted paths. this causes is_readable function to fail on drive letters in windows (e.g is_readable('\D:') is false.

###Expected behaviour
Being able to register openSSL certificates on Windows.

###Actual behaviour
Registration fails.

###Steps to reproduce the behaviour
Try to register an openSSL certificate on windows.

As I am not a PHP developper I don't have a suitable environment to be able to contribute, but here is a new version of the faulty function :

function checkPathsReadable($location)
{
	$paths = preg_split('#\/#', $location);
	$directory = '';
	if ($paths && count($paths)) {
		foreach ($paths as $path) {
			// If the first path contains : we unfortunately we're on Windows...
			// Don't directory separator before drive letter
			if($path == $paths[0] && strpos($path, ':') !== false) {
				$directory = $path;
			} else {
				$directory .= DS . $path;
			}
			if (!is_readable($directory)) {
				return false;
			}
		}
		return true;
	}
	return false;
}

**Comment by ghost** [comment]
Don't run it on Windows.

**Comment by reiichido** [comment]
Thanks for the advice, I knew I was gonna get that :). But If it can help others...

**Comment by reiichido** [comment]
@niel Thanks a lot!

**Comment by niel** [comment]
> @niel Thanks a lot!

Very welcome. Please test as I don't have a Windows machine to test on.

**Comment by niel** [comment]
> Don't run it on Windows.

Or use the Linux subsystem for Windows if you have to ;-)
