### ISSUE TITLE
Cannot connect to TVDB.

### ISSUE THREAD

**Issue by DrakeJones** [nZEDb/nZEDb#2648]
Getting PP error: Warning: Could not reach TVDB API. Running in local mode only!

Manual testing gives same result:

php '/var/www/nZEDb/misc/testing/Tests/test_tvdb_API.php' "prodigal son" 2 1 
Warning: Could not reach TVDB API. Running in local mode only!

**Comment by Wally73** [comment]
duplicate from 2647

**Comment by DrakeJones** [comment]
I'll close then.
