### ISSUE TITLE
http:xxx/install will not run

### ISSUE THREAD

**Issue by genebeck** [nZEDb/nZEDb#2658]
###Expected behaviour

###Actual behaviour

###Steps to reproduce the behaviour

**Comment by DariusIII** [comment]
We  need more data than this.

**Comment by genebeck** [comment]
what data do you need?

**Comment by genebeck** [comment]
It appears my comment did not post before.

I double check all of the steps on the ubuntu 18.04 guide.
Software Test from command line version test:
```
mysql  Ver 15.1 Distrib 10.3.27-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
PHP 7.2.34-8+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Oct 31 2020 16:57:15) ( NTS )
Composer version 2.0.8 2020-12-03 17:20:38
Server version: Apache/2.4.29 (Ubuntu)
```

Git cloned appears to have run normally.  Apache worked before removing the default section.  When I try to access the server using 192.168.0.210/install I get an http 500 error.  

 ```
 [Sun Jan 03 14:25:50.824549 2021] [mpm_prefork:notice] [pid 10079] AH00163: Apache/2.4.29 (Ubuntu) configured -- resuming normal operations
[Sun Jan 03 14:25:50.824603 2021] [core:notice] [pid 10079] AH00094: Command line: '/usr/sbin/apache2'
[Sun Jan 03 14:25:55.923581 2021] [php7:warn] [pid 10130] [client 192.168.0.50:63701] PHP Warning:  include_once(/var/www/nZEDb/libraries/lithium/core/Libraries.php): failed to open stream: No such file or directory in /var/www/nZEDb/app/config/bootstrap/libraries.php on line 74
[Sun Jan 03 14:25:55.923648 2021] [php7:warn] [pid 10130] [client 192.168.0.50:63701] PHP Warning:  include_once(): Failed opening '/var/www/nZEDb/libraries/lithium/core/Libraries.php' for inclusion (include_path='.:/usr/share/php') in /var/www/nZEDb/app/config/bootstrap/libraries.php on line 74

```
It appears that the error points to the lithium library missing.  I check the /var/www/nZEDb/libraries/ location and it is empy.  Otherwise the nZEDb folder is well populated with what appears to be correct files to make the webserver run.

I am at this point lost.

**Comment by Bart39** [comment]
Did you install composer and then run it ?

**Comment by Wally73** [comment]
when installing composer, make sure you use version 1 (not 2)

**Comment by genebeck** [comment]
That was my problem.  Missed the line about running composer install then ran into a brick wall with v2.  All I needed to do was download directly to the nzedb root folder the composer app and then run "php composer-1.php install ----prefer-source".  That populated everything else need to start the webserver. 

I suggest that the guide be updated to reflect that the composer.phar ver 1 is simple direct download from the bottom of the composer site.  Rather than wading thru multiple linked pages, change the guide to grab the app link from the composer site, then download and run one command.

Thank you very much for the help!

**Comment by Wally73** [comment]
https://github.com/nZEDb/nZEDb/wiki/Guides:-composer
(did add the downgrade to 1.10.x) 

If you did the global composer install method a simple 

composer self-update 1.10.19 

should work too ;)

**Comment by genebeck** [comment]
Good to know.  

BTW.  My install is now downloading headers and creating releases.  

Thanks for the help.
