### ISSUE TITLE
Feature Request - Mark as old releases.

### ISSUE THREAD

**Issue by bert0901** [nZEDb/nZEDb#533]
One thing I loved in old indexers was to mark old posts, and not have it done automatically.

So when went back in next day/week, I can easily see what was new on the site since last visit.

Anyway to have this?

Almost a total convert to this now. Love the speed and accuracy.

**Comment by ruhllatio** [comment]
Don't know why this is till open.  Rows are tinted green seems to work fine in alpha theme.  Might need to be replicated to other themes.  If this is important use Alpha for now.  Tested on Master branch.
