### ISSUE TITLE
Only german TV, Movies & Books

### ISSUE THREAD

**Issue by wizzardking** [nZEDb/nZEDb#668]
Hello
Is it possible to implement a script that nzedb delete all tv, movie and book Releses who doesnt have the word german or deutsch.
If i make this with whitelist it cant add any audio and pc releases because this doesnt need this words. The oher problem with a whitelist is that some releases have the word german only after postprocessing and the fixrelease name script.
So it would be very nice if nzedb have a script that check all tv, movie and book releases after the fixreleasename script and delete every release in those cats who doesnt have this word.

**Comment by cactushydrocodone** [comment]
@wizzardking 
could you please tell or elaborate how you did it?
